### ISSUE TITLE
Remove ServiceMatrix menu item from docs

### ISSUE THREAD

**Issue by petersgiles** [Particular/docs.particular.net#1002]
I think we are ready to remove the menu items 

- ServiceMatrix
   - Getting Started
   - Using ServiceMatrix

People who want the information about ServiceMatrix can use the search facility

@SimonCropp @indualagarsamy thoughts?

<img width="413" alt="screenshot 2016-01-06 09 31 45" src="https://cloud.githubusercontent.com/assets/1644481/12130013/81fc7506-b45b-11e5-83fd-8989bc234887.png">

**Comment by indualagarsamy** [comment]
@petersgiles - The plan was to add "Discontinued" to the text of SM issue.

**Comment by petersgiles** [comment]
@indualagarsamy do we need to have the menu items though?

**Comment by indualagarsamy** [comment]
@petersgiles - The idea is to leave documentation around until end of February and then completely remove it. At least that's what we said in the announcement.

**Comment by indualagarsamy** [comment]
All the articles do say that it is no longer available. So clicking on any documentation, that's the first thing the user will see.

**Comment by petersgiles** [comment]
Yes I have seen that and its why I think only having the search option is enough. 

My problem is that there is a menu item that says `Getting Started` under the ServiceMatrix item and `Using ServiceMatrix` seems pretty silly too given our current position on the product. 

At the very least can we remove those sub menu items

**Comment by SimonCropp** [comment]
i removed the getting started as a compromise
