### ISSUE TITLE
Should WCF handle do a return ?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1003]
here http://docs.particular.net/nservicebus/hosting/expose-an-endpoint-as-a-web-wcf-service

we got some feedback 

> Apparently you need to make a call to Bus.Return in the message handler. Add it to docs maybe?

Is this correct?

**Comment by SimonCropp** [comment]
@DavidBoike can u look into this?

**Comment by DavidBoike** [comment]
Ugh. Yes it is. Otherwise the callback will sit waiting for a response that never comes.

**Comment by SimonCropp** [comment]
@DavidBoike r u ok patching that?

**Comment by SimonCropp** [comment]
@DavidBoike ping
