### ISSUE TITLE
Update Sql Transport Samples to V6 and latest transport

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1010]
Based on @mat-mcloughlin list

- [x] sqltransport-nhpersistence relates to: https://github.com/Particular/docs.particular.net/pull/1044
  - [x] [doco needs](http://docs.particular.net/samples/sqltransport-nhpersistence/ ) code snippet for sender project 
  - [x] [doco needs](http://docs.particular.net/samples/sqltransport-nhpersistence/ ) code snippet for receiver project 
- [x] sqltransport\native-integration relates to: https://github.com/Particular/docs.particular.net/pull/1041
- [x] sql-bridge relates to: https://github.com/Particular/docs.particular.net/pull/1010
- [x] outbox\sqltransport-nhpersistence https://github.com/Particular/docs.particular.net/pull/1162
- [x] outbox\sqltransport-nhpersistence-ef   https://github.com/Particular/docs.particular.net/pull/1169

The last two need resolution of related bugs: https://github.com/Particular/NServiceBus/issues/3499, https://github.com/Particular/NServiceBus.NHibernate/issues/161 

@Particular/tf-async-transport ping

**Comment by petersgiles** [comment]
relates to: https://github.com/Particular/docs.particular.net/pull/1044

**Comment by petersgiles** [comment]
@SzymonPobiega I am looking at outbox\sqltransport-nhpersistence samples and I'm confused by the versions of the samples. The subject 'outbox' is attached to the core. Yet the versions of the samples seem to be a mix of core versioning and the versions of downstream plugin libraries. I think that the existing samples should all be V5, V6 etc not the version of the downstream plugin libraries.

**Comment by SzymonPobiega** [comment]
@petersgiles the reason behind the samples being labeled 2.2 is that some of the features used there were not available in previous versions of SQL transport targeting NSB 5 (2.0 and 2.1). Not sure how we can handle it best but I am leaning towards using NSB version numbers, as you said.

**Comment by petersgiles** [comment]
@SzymonPobiega yes I think we should align this to the NSB version.
