### ISSUE TITLE
Update Host sample

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1013]
@petersgiles for your reference based on @mat-mcloughlin list

**Comment by petersgiles** [comment]
@danielmarbach I'm sorry I don't know what this is about, or what it is reminding me of. Can you throw a little more context in here for me.

**Comment by danielmarbach** [comment]
@petersgiles 

http://docs.particular.net/samples/hosting/nservicebus-host/

Sorry late for me, but you can talk to @SimonCropp how to update samples

**Comment by petersgiles** [comment]
done http://docs.particular.net/samples/hosting/nservicebus-host/#nservicebus-host-v6-pre
