### ISSUE TITLE
Update Azure samples to latest V6 and transports

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1014]
Based on @mat-mcloughlin list

- [x] azure\azure-service-bus
- [x] azure\blob-storage-databus
- [x] azure\native-integration-asb
- [x] azure\polymorphic-events-asb
- [ ] azure\shared-host
- [x] azure\storage-persistence
- [x] azure\storage-queues

@Particular/tf-async-transport ping

**Comment by SeanFeldman** [comment]
Changing items into tasks to be able to see the progress on a higher (issues) level

**Comment by SimonCropp** [comment]
duplicate of https://github.com/Particular/docs.particular.net/issues/804
