### ISSUE TITLE
Update Scalout sample to v6

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1015]
@janovesk @SzymonPobiega @indualagarsamy I couldn't find a team for the client side distribution TF so I pinged you

Based on @mat-mcloughlin for your reference

https://github.com/Particular/docs.particular.net/tree/master/Snippets/Snippets_5/Distributor

**Comment by johnsimons** [comment]
@SzymonPobiega assigned you to this since you the scale out guru

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/scaleout/
