### ISSUE TITLE
Update mongodb sample to latest V6 and transport updates

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1016]
Based on @mat-mcloughlin list

@Particular/tf-async-persistence ping

Connects to https://github.com/Particular/PlatformDevelopment/issues/682.

**Comment by johnsimons** [comment]
It seems NServiceBus.Persistence.MongoDb nuget package is an external package amintained by a community member, so I assume we need to wait for the community to upgrade the package to v6 before we can do anything here.
I recommend removing the `Core v6` label from this

**Comment by SimonCropp** [comment]
@johnsimons agreed. done

**Comment by weralabaj** [comment]
The issue is related to https://github.com/Particular/PlatformDevelopment/issues/682 and we'll tackle it there.
