### ISSUE TITLE
Update serializer samples to V6

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1020]
Based on @mat-mcloughlin list

* [x] serializers\binary (deprecated in v6, notice added)
* [x] serializers\jil
* [x] serializers\json-external
* [x] serializers\message-pack
* [x] serializers\wire

@Particular/tf-async-core @Particular/nservicebus ping

**Comment by hmemcpy** [comment]
How should be the external serializers versioned? Just tag the latest release as v5, then upgrade to 6? Or just UPGRADE ALL THE THINGS?

**Comment by SimonCropp** [comment]
closing this. the external ones dont need to be part of v6

**Comment by timbussmann** [comment]
@SimonCropp wouldn't it make sense to keep it open and just remove the v6 tag instead?

**Comment by SimonCropp** [comment]
@timbussmann done

**Comment by SimonCropp** [comment]
@hmemcpy do u have any intention of updating wire?

**Comment by hmemcpy** [comment]
@SimonCropp sure, I'll do it!

**Comment by SimonCropp** [comment]
@distantcam awesome. thanks

**Comment by hmemcpy** [comment]
@SimonCropp v2.0 targeting NSB 6 is on nuget

**Comment by SimonCropp** [comment]
done
