### ISSUE TITLE
PlatformInstaller logs location

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1021]
If the Platform Installer UI freezes the user cannot click the Log hyperlink. The doco doesn't say where the user should look for the log files on their system if the UI is unusable.

**Comment by gbiellem** [comment]
Hi @MarcinHoppe  

:+1: fo documenting the log location. 

I didn't see an associated bug raised against the Platform Installer though for the UI freeze problem. Can you raise an issue in https://github.com/Particular/PlatformInstaller/ and provide whatever details you have?

**Comment by MarcinHoppe** [comment]
@gbiellem Thanks for fixing the doco. 

I discussed filing the UI freeze issue with @andreasohlund and we came to a conclusion we did not capture enough data to allow any sort of diagnosis and categorized the incident as a "glitch".

Running the installer again resolved the freeze.
