### ISSUE TITLE
Change code samples on "Upgrade from Version X to Version Y" docs to be side-by-side

### ISSUE THREAD

**Issue by dbelcham** [Particular/docs.particular.net#1029]
The thought process here was that in a normal documentation page the tab-per-version layout of code makes sense. As a reader of those I'm looking for information on that topic and version number specifically. 

When I read the "Upgrade from...." pages I'm looking to transition from one piece of code to another. When the two versions of the code are side-by-side it's easier to see how the code transition is going to look. You can easily see 8 lines of code turn into 3. You can see that the method name is the only change. Things like that.

![side-by-side](https://cloud.githubusercontent.com/assets/1378057/12210882/76e93dfa-b61a-11e5-9153-19f85e7f8552.jpg)

The only issue that I see with this idea is page formatting. Is there enough horizontal room to put two code snippets side by side in a meaningful way? Adding horizontal scrolling to each one is an option but if there are differences visible and also some differences that are out of view (due to scrolling) it increases the chances that people will miss things.

**Comment by SimonCropp** [comment]
Please raise in https://github.com/Particular/Operations.DocsWeb
