### ISSUE TITLE
re add broken doco

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1034]
https://github.com/Particular/docs.particular.net/commit/8f30406c35da702cb6c150d9cb2b657577482fcf

**Comment by SimonCropp** [comment]
@timbussmann @SzymonPobiega can you guys work on re including these files once you have fixed the doco

**Comment by SzymonPobiega** [comment]
Routing part done via 39a9ffc35ec1a4b494686c85058524678250baed

**Comment by timbussmann** [comment]
working on the pipeline extension part. It uncovered a a bug which needs to be fixed on develop first.

**Comment by SimonCropp** [comment]
@timbussmann @SzymonPobiega thanks
