### ISSUE TITLE
NHibernate persistence manual table creation

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1046]
Have info on how to manually create NHibernate persistence tables in SQL. List creation scripts with indexes and included troubleshooting section that includes that probably the indexes are not configured correctly when deadlocks occur.

**Comment by weralabaj** [comment]
ping @Particular/nhibernate-persistence-maintainers :)
let me know if I can help with pushign this forward

**Comment by SzymonPobiega** [comment]
@weralabaj well, I guess what needs to be done is somebody has to configure the NHibernate for all the dialects we support and capture the generated scripts and add to the doco. I am still not convinced about the value of this exercise as the documented scripts would not contain the saga tables. So we are talking only about Outbox, Subscriptions and Timeouts.

**Comment by weralabaj** [comment]
Synced with @MarcinHoppe - the issue will be taken care of, but is not a top priority for maintainers, so probably we have to wait a bit.

**Comment by SimonCropp** [comment]
this would seem larger than can be handled under just docs. suggest raising a plat dev issue to see if the ROI is there given he current state of nhibernate
