### ISSUE TITLE
Move messages between SQL transport queues with TSQL

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1049]
Put the following somewhere in the SQL transport doco.

``` sql
DELETE FROM receiver..Receiver
OUTPUT
[deleted].[Id]
,[deleted].[CorrelationId]
,[deleted].[ReplyToAddress]
,[deleted].[Recoverable]
,[deleted].[Expires]
,[deleted].[Headers]
,[deleted].[Body]
INTO sender..Sender([Id]
,[CorrelationId]
,[ReplyToAddress]
,[Recoverable]
,[Expires]
,[Headers]
,[Body])
WHERE RowVersion IN (SELECT TOP 50000 RowVersion FROM receiver..Receiver)
```

**Comment by weralabaj** [comment]
@ramonsmits When would you use that (in what situation)? Depending on that it'd be easier to determine where we should put it.

**Comment by ramonsmits** [comment]
@weralabaj When not using ServiceControl to retry messages or when you want to move messages from an instance specific queue that is not running anymore.

**Comment by weralabaj** [comment]
Hm... so something like archiving an endpoint?

**Comment by SimonCropp** [comment]
@ramonsmits if you still feel this is required can u start a draft PR
