### ISSUE TITLE
v6 Azure snippets

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1058]
https://github.com/Particular/docs.particular.net/tree/master/Snippets/Snippets_5/Azure

**Comment by yvesgoeleven** [comment]
Review existing documents for consistent usage of snippets as well

- [ ] ASB
- [ ] ASQ
- [ ] ASP
- [ ] Cloud Service Hosting

Copied from https://github.com/Particular/docs.particular.net/issues/1151

**Comment by SimonCropp** [comment]
@yvesgoeleven do u consider this done?

**Comment by yvesgoeleven** [comment]
@SimonCropp no, hosting hasn't been touched yet

**Comment by weralabaj** [comment]
Seems like that has been addressed already?
I see snippets for the newest version http://docs.particular.net/nservicebus/hosting/cloud-services-host/.

**Comment by weralabaj** [comment]
@yvesgoeleven @SeanFeldman :point_up:

**Comment by yvesgoeleven** [comment]
@weralabaj indeed, we can close this issue
