### ISSUE TITLE
v6  ninject sample

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1060]
https://github.com/Particular/docs.particular.net/tree/master/samples/containers/ninject

**Comment by distantcam** [comment]
Is this a duplicate of #1059? Do we need 2 tasks for this?

**Comment by SimonCropp** [comment]
One is the snippets the other is the sample. They require different amounts of effort, do not conflict and can be done by different people. So yeah i think it makes sense to have two issues

**Comment by SimonCropp** [comment]
done
