### ISSUE TITLE
v6 distributor sample

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1062]
https://github.com/Particular/docs.particular.net/tree/master/samples/scaleout/

**Comment by andreasohlund** [comment]
Since version 6 won't have a distributor can we close this?

@SzymonPobiega @janovesk is there some other samples that should be modified/created instead? (interop with v5 distributor comes to mind)

**Comment by SimonCropp** [comment]
@andreasohlund in that case shouldnt that info be captured both here http://docs.particular.net/nservicebus/upgrades/5to6 and here http://docs.particular.net/nservicebus/scalability-and-ha/distributor/ and a warning in that sample as well?

**Comment by andreasohlund** [comment]
agreed, @janovesk / @SzymonPobiega can you deal with it?

**Comment by SzymonPobiega** [comment]
The **Task Force 133** can deal with anything!

**Comment by SzymonPobiega** [comment]
PR open here: https://github.com/Particular/docs.particular.net/pull/1132
