### ISSUE TITLE
v6 endpoint mapping snippets

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1065]
https://github.com/Particular/docs.particular.net/tree/master/Snippets/Snippets_5/EndpointMapping

**Comment by johnsimons** [comment]
@SzymonPobiega are we going to still promote xml config for mappings ?

**Comment by SimonCropp** [comment]
"promote"? either way if it still exists it needs to be documented

**Comment by SzymonPobiega** [comment]
@johnsimons we'll 'promote' them as legacy that continues to work as before

**Comment by SzymonPobiega** [comment]
Here's PR: https://github.com/Particular/docs.particular.net/pull/1112
