### ISSUE TITLE
v6 header writers

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1068]
https://github.com/Particular/docs.particular.net/tree/master/Snippets/Snippets_5/Headers/Writers

**Comment by johnsimons** [comment]
How is this updated @SimonCropp ? Did u gen it ?

**Comment by SimonCropp** [comment]
@johnsimons yeah this is finicky. i will work on it

**Comment by SimonCropp** [comment]
outstanding https://github.com/Particular/docs.particular.net/blob/master/Snippets/Snippets_5/Headers/Writers/HeaderWriterError.cs

**Comment by SimonCropp** [comment]
blocked by https://github.com/Particular/NServiceBus/pull/3063

**Comment by SimonCropp** [comment]
@ramonsmits what is the status of the encryption in v6?
