### ISSUE TITLE
v6 Monitoring Snippets

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1069]
https://github.com/Particular/docs.particular.net/tree/master/Snippets/Snippets_5/Monitoring

**Comment by mikeminutillo** [comment]
Currently blocked by https://github.com/Particular/NServiceBus/issues/3388

**Comment by mikeminutillo** [comment]
Updated in https://github.com/Particular/docs.particular.net/commit/22583676a2d7028c96d5e8acd11f36ac326d8d21

Waiting on confirmation about https://github.com/Particular/NServiceBus/issues/3388 before closing this issue.

**Comment by mikeminutillo** [comment]
If `UseLegacyMessageDrivenSubscriptionMode()` is removed from the API, the snippet won't compile anymore so I am closing this.
