### ISSUE TITLE
v6 scaleout snippet

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1076]
https://github.com/Particular/docs.particular.net/tree/master/Snippets/Snippets_5/ScaleOut

**Comment by johnsimons** [comment]
@SzymonPobiega what should we do with the doco about `ScaleOut()` ... ?

**Comment by SzymonPobiega** [comment]
@johnsimons depends on the outcome of https://github.com/Particular/NServiceBus/issues/3369

**Comment by SimonCropp** [comment]
@SzymonPobiega since https://github.com/Particular/NServiceBus/issues/3369 is closed  and https://github.com/Particular/NServiceBus/pull/3374 is merged can this issue now be progressed?

**Comment by SzymonPobiega** [comment]
Clarified it based on the current V6 API. It will probably change before release but at least we are up to date now: https://github.com/Particular/docs.particular.net/pull/1201
