### ISSUE TITLE
v6 UnitTesting snippets

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1080]
https://github.com/Particular/docs.particular.net/tree/master/Snippets/Snippets_5/UnitTesting

Relies on: https://github.com/Particular/NServiceBus.Testing/issues/29 and https://github.com/Particular/NServiceBus.Testing/pull/43

**Comment by petersgiles** [comment]
@timbussmann what is the status of the Testing V6 upgrade?

**Comment by timbussmann** [comment]
@petersgiles not in progress yet :(

**Comment by timbussmann** [comment]
@SimonCropp @hmemcpy I think we can close this one as we have snippets updated to v6 (e.g. here https://github.com/Particular/docs.particular.net/pull/1305)

**Comment by SimonCropp** [comment]
@timbussmann ok. thanks
