### ISSUE TITLE
Clarify MSMQ Connection Deadletter behavior

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/docs.particular.net#1088]
There could be an element of uncertainty when reading the MSMQ connection documentation where it's not immediately obvious what the side-effects of the deadletter configuration is when there is no endpoint processing the messages at the other end.

We should update the docs to explicitly state what the implications are of not processing messages when deadletter is on.

**Comment by SimonCropp** [comment]
@WilliamBZA since the PR is merged can this be closed?
