### ISSUE TITLE
NServiceBus Sagas And Concurrency

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#109]
From 'Particular Migration Guidelines' spreadsheet: 57

http://particular.net/articles/nservicebus-sagas-and-concurrency
http://particular.cloudapp.net/Admin/Contents/Edit/216
http://particular.net/Contents/Item/Preview/216

KB
- [ ] fix the 'manufacturing sample' link [point to the video store?]
- [x] update code to gist

**Comment by mauroservienti** [comment]
The document is ok, the sample is missing. @ramonsmits which type of sample can we provide?

**Comment by SimonCropp** [comment]
current doco is here http://docs.particular.net/nservicebus/sagas/concurrency. dont think it needs a sample
