### ISSUE TITLE
Performance considerations ServiceControl

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#1097]
I really liked the discussion here by @petersgiles : https://nservicebus.desk.com/agent/case/16582

Perhaps we could write some documentation on what Peter suggests here? Something like best practices on auditing, logging, etc. Might help a lot of developers & operations out there.

**Comment by weralabaj** [comment]
@dvdstelt does that  http://docs.particular.net/servicecontrol/servicecontrol-in-practice cover what you had in mind? If so then can we close?

**Comment by dvdstelt** [comment]
Most definitely!
