### ISSUE TITLE
RavenDB simple sample v6

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1100]
http://docs.particular.net/samples/ravendb/simple/#code-walk-through-handler-using-raven-session

Related to https://github.com/Particular/NServiceBus.RavenDB/issues/113

**Comment by johnsimons** [comment]
Working on it #1121

**Comment by SimonCropp** [comment]
@johnsimons https://github.com/Particular/docs.particular.net/pull/1047
