### ISSUE TITLE
Update RavenDB doco to V6

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1101]
http://docs.particular.net/nservicebus/ravendb/

Related to: https://github.com/Particular/NServiceBus.RavenDB/issues/113

**Comment by johnsimons** [comment]
Duplicate @1074

**Comment by mauroservienti** [comment]
They are not really the same thing, the other one is for snippets, this was related to the page content itself, some of the API drastically changed and we need to reflect it in the page content, IMO.
