### ISSUE TITLE
Create a SQL Transport sample to show how to add multi-instance support in V6

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1102]
Task force: @justabitofcode @tmasternak 

As discussed with @andreasohlund we decided to ship the multi-instance support as a sample and provide guidance around it.

**Comment by indualagarsamy** [comment]
@justabitofcode @tmasternak - any updates?

**Comment by tmasternak** [comment]
@indualagarsamy hopefully we will be able to finish around Monday next week. /cc: @weralabaj

**Comment by tmasternak** [comment]
@justabitofcode should we create PR for https://github.com/Particular/docs.particular.net/tree/sql-transport-multi-instance-sample and link it to this issue?

**Comment by weralabaj** [comment]
That's been done http://docs.particular.net/samples/sqltransport/multi-instance/.
