### ISSUE TITLE
SQL Transport multi instance guidance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1103]
Task force: @mauroservienti @tmasternak @justabitofcode 

Create guidance that describes why we don't want to support multi-instance in the SQL Transport and options for customers that may benefit of such a deployment topology.

As discussed with @andreasohlund we decided to ship the multi-instance support as a sample and provide guidance around it.

- [ ] Cover changes in upgrade guide for v5 to v6

**Comment by indualagarsamy** [comment]
@mauroservienti @tmasternak @justabitofcode - since the upgrade guide for SqlServer transport is already completed, and has this section http://docs.particular.net/nservicebus/upgrades/sqlserver-2to3#sql-server-transport-multi-schema-support
can this issue be closed? 
cc / @weralabaj

**Comment by weralabaj** [comment]
@indualagarsamy this is actually a different thing that @justabitofcode is working on at the moment. We're tracking this in PlatformDev https://github.com/Particular/NServiceBus.SqlServer/issues/139, so if we're ok with PR with no issue in docs I"m +1 for closing.

**Comment by weralabaj** [comment]
This issue is covered by https://github.com/Particular/docs.particular.net/pull/1354 and https://github.com/Particular/docs.particular.net/pull/1353. No need to track it here.
