### ISSUE TITLE
no longer pretty printing XML

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1120]
should the below be captured in the upgrade guide?

in v5
```
<?xml version="1.0" ?>
<MessageToSend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://tempuri.net/Snippets5.Headers.Writers">
<LargeProperty1>
<Key>2016-02-01_14\1ac6a39a-2a2f-4775-836f-5164cf757ad2</Key>
<HasValue>true</HasValue>
</LargeProperty1>
<LargeProperty2>
<Key>2016-02-01_14\6f940655-a6df-45bb-ae41-bb16ef3821d0</Key>
<HasValue>true</HasValue>
</LargeProperty2>...
```

in v6
```
<?xml version="1.0"?><MessageToSend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://tempuri.net/Snippets6.Headers.Writers"><LargeProperty1><Key>2016-02-01_14\61b3e30f-f0e4-49e9-a509-572152f1f1d2</Key><HasValue>true</HasValue></LargeProperty1><LargeProperty2><Key>2016-02-01_14\4cbcdbe1-8f05-4e68-a2af-0316b63dab0f</Key><HasValue>true</HasValue></LargeProperty2></MessageToSend>
```

**Comment by SimonCropp** [comment]
@danielmarbach do u have any idea about this change?

**Comment by danielmarbach** [comment]
I hear @WilliamBZA is on it. I have no idea

**Comment by WilliamBZA** [comment]
The XML changes I made could not have had an effect on this.

How are you reproducing the result @SimonCropp? Perhaps there is another change that has caused this somewhere down the line.

**Comment by SimonCropp** [comment]
@WilliamBZA running this test https://github.com/Particular/docs.particular.net/blob/master/Snippets/Snippets_5/Headers/Writers/HeaderWriterEncryption.cs versus this test  https://github.com/Particular/docs.particular.net/blob/master/Snippets/Snippets_6/Headers/Writers/HeaderWriterEncryption.cs

**Comment by WilliamBZA** [comment]
@SimonCropp So here's something that's rather confusing: The unit tests around the Xml Serializer still serializers in the "pretty" format including the linebreaks.

Which means the Xml serialization code still generates the linebreaks. I'll have to dig a bit deeper to see where the linebreaks are being removed.

**Comment by SimonCropp** [comment]
replaced by https://github.com/Particular/NServiceBus/issues/3431
