### ISSUE TITLE
CustomRetryPolicy code gets fired twice per 2nd level retry

### ISSUE THREAD

**Issue by nfdias** [Particular/docs.particular.net#1124]
I got the following in the EndpointConfig

```
var retriesSettings = configuration.SecondLevelRetries();
retriesSettings.CustomRetryPolicy(new NServiceBusSecondLevelHandling().RetryPolicy);
```

And here is my policy

```
public class NServiceBusSecondLevelHandling
{
	public TimeSpan RetryPolicy(TransportMessage transportMessage)
	{

// this gets fired twice

	   if (transportMessage.ExceptionType() != typeof(WebException).FullName)
		{
			return TimeSpan.MinValue;
		}

		if (transportMessage.NumberOfRetries() >= 1)
		{
			return TimeSpan.MinValue;
		}

		return TimeSpan.FromSeconds(10);
	}
}
```

I tried the same but with static. The only way to make this fire once per 2nd level retry is to have the RetryPolicy code in the EndpointConfig class.

Is it suppose to be like this ?

I am using NServiceBus 5.2.14

**Comment by SimonCropp** [comment]
on the first run through transportMessage.NumberOfRetries() will be 0. so the above will execute twice with a delay of 10 seconds for web exceptions. and no retries for non webexceptions. is that the intent?

**Comment by nfdias** [comment]
That is the intent but not whats happening.

Here is an example. In the handler I have:

`throw new WebException("exception error");`

Then I got extension helper methods to get: the number of the retry, messageId and the exception message info:

```
internal static int NumberOfRetries(this TransportMessage transportMessage)
{
string value;

return transportMessage.Headers.TryGetValue(Headers.Retries, out value) ? int.Parse(value) : 0;
}

internal static string MessageId(this TransportMessage transportMessage)
{
 return transportMessage.Headers["NServiceBus.MessageId"];
}

internal static string Message(this TransportMessage transportMessage)
{
return transportMessage.Headers["NServiceBus.ExceptionInfo.Message"];
}
```

Finally, in the beginning of the RetryPolicy i am logging in the database some info:

```
ExceptionDate	ExceptionMessage
2016-02-03 04:17:52.283	Retry #0 MessageId:21b3ae7b-d3ad-4c8a-aa0b-652ed0f14fab\493150 Message:exception error
2016-02-03 04:17:52.850	Retry #0 MessageId:21b3ae7b-d3ad-4c8a-aa0b-652ed0f14fab\493150 Message:exception error
2016-02-03 04:18:05.197	Retry #1 MessageId:21b3ae7b-d3ad-4c8a-aa0b-652ed0f14fab\493150 Message:exception error
```

As you can see the message gets repeated twice the first retry. The second time its only once because of the return TimeSpan.MinValue;

Hope this helps

**Comment by indualagarsamy** [comment]
Hey @nfdias - I was able to repro this bug. Will investigate and let you know.

**Comment by indualagarsamy** [comment]
@nfdias - I've moved this issue over to NServiceBus repository here: https://github.com/Particular/NServiceBus/issues/3443
