### ISSUE TITLE
update using idocumentstore

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1128]
this is well out of date
http://docs.particular.net/nservicebus/ravendb/#previous-releases-can-i-use-the-idocumentstore-used-by-nservicebus-for-my-own-data

**Comment by SimonCropp** [comment]
@DavidBoike @mauroservienti can on of u look at this one?

**Comment by DavidBoike** [comment]
@colin-higgins You worked on the V6 edition of sharing the Raven session. Would you be able to tackle this? I skimmed the section Simon is referring to and it is all sorts of wrong.

**Comment by indualagarsamy** [comment]
@DavidBoike @colin-higgins - any updates on this?

**Comment by DavidBoike** [comment]
Blocked by figuring out what to do with Raven.

**Comment by colin-higgins** [comment]
I missed the ping, but I will put a WIP up for this and we can fix it up once we establish what we're doing.

**Comment by indualagarsamy** [comment]
@colin-higgins - any updates on this?

**Comment by SimonCropp** [comment]
@Particular/ravendb-persistence-maintainers any update on this? need any help from @Particular/docs-maintainers  ?

**Comment by weralabaj** [comment]
Seems the doco has been updated, the problematic section doesn't exist anymore, I believe it was replaced with http://docs.particular.net/nservicebus/ravendb/#nservicebus-3-and-nservicebus-4-using-the-nservicebus-idocumentstore-for-business-data-is-not-possible.
