### ISSUE TITLE
Standardize how to document bus operations in v6

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#1131]
There are multiple contexts in which you can send/publish a message. In v6 this has been made explicit. The doco for [sending a message](http://docs.particular.net/nservicebus/messaging/send-a-message#basicsend-v6-pre) explicitly calls out the Endpoint Direct context and Message Handler context.

When documenting items orthogonal to this, do we need to show both contexts? Can we standardize on showing a single context? 

As an example, Message Deferral can be done using a `DateTime` or a `TimeSpan`. Do we need to show both usages in both contexts in order to document message deferral or can we show them both in Message Handler context and have a note that this feature is available in Endpoint Direct context?

[This Pull](https://github.com/Particular/docs.particular.net/pull/1127) demonstrates the Message Deferral case.

**Comment by timbussmann** [comment]
Again linking to this PR: https://github.com/Particular/docs.particular.net/pull/1040
The idea was to raise awareness between out-of-pipeline and in-pipeline operations. While we abstract this away in v5 and earlier, I think it's a very important difference users should know. In v6 we made that explicit by separating interfaces. I think it makes sense to show basic samples how to send a message in the two different contexts. But that does not mean we have to repeat this for every operation. 

> As an example, Message Deferral can be done using a DateTime or a TimeSpan. Do we need to show both usages in both contexts [...]?

message deferral acts on `SendOptions` which you pass into bus operations. So I think it's enough to show the difference between `TimeSpan` and `DateTime` on one API. The concept is: everywhere you can pass in `SendOptions` you can apply the same knowledge.

**Comment by mikeminutillo** [comment]
OK. Well in that case, I think we should standardize on showing the Handler Context scenario for orthogonal concepts as it will be the most common. 

Do we need a taskforce and RFC period for this?

**Comment by timbussmann** [comment]
@mikeminutillo any idea how many docs page/snippets would be affected?

**Comment by mikeminutillo** [comment]
Any markdown file with a `bus.Send` in the text is a potential candidate. There are only [13 of those](https://github.com/Particular/docs.particular.net/search?l=markdown&q=%22bus.Send%22&type=Code&utf8=%E2%9C%93). 

Any v5 snippet that includes `bus.Send` is a candidate as well. There are [23 of these](https://github.com/Particular/docs.particular.net/search?utf8=%E2%9C%93&q=%22bus.Send%22+path%3ASnippets%2FSnippets_5&type=Code).

Any/all of these may already be OK. They'd need to be looked at individually.

**Comment by mikeminutillo** [comment]
You could repeat those searches for `bus.Publish` too.

**Comment by mikeminutillo** [comment]
@Particular/docs-maintainers Do we need a standard for this or should I close this issue? If we choose to have a standard, does it just get added to the readme?

**Comment by weralabaj** [comment]
Given the current level of detail in the Readme if we can come up with something more generic than guideline for a specific method then I'm ok. Otherwise IMO let's raise an issue to review it and make sure it's consistent for now.

**Comment by indualagarsamy** [comment]
@mikeminutillo - I don't think we need to add it in the readme. 
I think it depends on a case by case basis. In some cases like the message sending like @timbussmann said, it might make sense to highlight it, and when you have established doco that highlights the differences, you wouldnt need it everywhere (my 2 c).

**Comment by mikeminutillo** [comment]
OK. I will close this issue and we'll review on a case by case basis.

Thanks all.
