### ISSUE TITLE
MSMQ Permissions

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1140]
We have a bit of documentation on how to script MSMQ queues and permissions but we would need to add a little bit of info on how to restrict permissions and give guidance on how to make sure endpoints can only read messages from their owning queue but are not able to read from other queues or drop/purge its own or other queues.

Also mention how to make sure that queues can be managed by administrators and mention that domain administrators can be locked out if a queue is not setup correctly.

**Comment by apylypchuk** [comment]
Well, if we can make it possible to install an instance and it's endpoint core configuration from within the ServiceControl, it would be just great(I can create audit and error queues there, to point my endpoints at, which is part of the solution already). Or a separate tool withing the NSB package to make the deployment of the system easier.

**Comment by gbiellem** [comment]
@ramonsmits I think this should be closed.  Nothing about managing MSMQ queue permissions is specific to NServiceBus.  This information should be sourced from Microsoft
