### ISSUE TITLE
Order of Assert/Act statements

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1145]
While working on a GG case, have ran into an issue with NSB.Testing (https://github.com/Particular/NServiceBus.Testing/issues/39). Our documentation on unit testing NSB doesn't clarify what order should be applied.

**Comment by weralabaj** [comment]
@timbussmann I don't see that used anywhere. I could document but I'm not sure how's that different from the OnMessage? When would you use both?

**Comment by timbussmann** [comment]
> I could document but I'm not sure how's that different from the OnMessage? When would you use both?

sorry, not enough context :confused: what are you referring to?

**Comment by weralabaj** [comment]
@timbussmann I commented on the wrong issue should be https://github.com/Particular/docs.particular.net/issues/1146

**Comment by weralabaj** [comment]
Merged
