### ISSUE TITLE
Test.CreateInstance<T> is absent from unit testing documentation

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1146]
Test.CreateInstance<T> is absent from the [unit testing documentation](http://docs.particular.net/nservicebus/testing/).

**Comment by weralabaj** [comment]
@timbussmann I don't see that used anywhere. I could document but I'm not sure how's that different from the OnMessage? When would you use both?

**Comment by timbussmann** [comment]
this is a helper method to create instances of interface message definitions. I don't think there is any need to document this, as there are APIs around which do the same for you. It's merely a tool in case the other API won't do the trick.

**Comment by weralabaj** [comment]
So at the moment we don't have a clear use case, but are leaving it "just in case"?

**Comment by timbussmann** [comment]
yes
