### ISSUE TITLE
add OutgoingHeaders change to upgrade guide and doco

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1147]
OutgoingHeaders has been changed to SetOutgoingHeaders but that has not been captured in doco

**Comment by hmemcpy** [comment]
Was this change already merged into v6? Because I can't find the SetOutgoingHeaders method...

**Comment by SimonCropp** [comment]
seems this is done http://docs.particular.net/nservicebus/upgrades/5to6#header-management-setting-outgoing-headers-for-the-entire-endpoint 

but the obsolete was wrong. so i fixed the obsolete
