### ISSUE TITLE
update azure documentation, generic remarks

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1151]
Task Force: @SeanFeldman @weralabaj @Scooletz @melkio @YvesGoeleven

# Goal

Bring the existing documentation into a state where it can be easily extended with today's documentation needs (core v6/transport v7 as well as the context of azure itself)

# Context 

Azure was a different thing years ago when we started with supporting it, the doco still somewhat reflects this. F.e. thinking of Azure as a whole: this stems from the time where azure equaled what is now called the 'Classic Model', aka everything was a cloud service. The model was predefined and acted as a whole.

Times have changed though, we should aknowledge that and reflect it back in new doco structure. With the introduction of the 'Resource Model (ARM)', all resources in azure are now separate and evolve independently. This lead to an explosion in services, as well as changes in these services at different levels. It would be better to think of these services as individual technologies which we support, instead of a whole (ASB, ASQ, ASP, Cloudservice host, Service fabric, etc...) 

# Plan of attack

- [x] Analyze & document current doco structure and context
- [x] Define new doco structure in new context
- [x] Define migration path for existing doco items (splitting/restructuring)
- [x] Execute migration of existing doco into the new structure & guidelines

# Current doco structure

`Transports` section (2 articles):
- `Azure Service Bus` (http://docs.particular.net/nservicebus/azure/azure-servicebus-transport) covers a lot of different topics (enabling transport, detailed configuration, brokered message, naming conventions, transactions, performance tips)
- a generic `Azure transports` (http://docs.particular.net/nservicebus/azure/azure-transport) covers how to configure (ASB / ASQ) for cloud or hybrid scenario
- NOTE: _no article related to ASQ transport here_

`Persistence` section (2 articles):
- `Azure Storage Persistence` (http://docs.particular.net/nservicebus/azure/azure-storage-persistence) covers cloud hosting scenario, configuration (with code and with config file) and performance tips
- `NHibernate in SQL Azure` (http://docs.particular.net/nservicebus/nhibernate/sql-azure) 

`Hosting` section (2 articles):
- `Hosting in Azure` (http://docs.particular.net/nservicebus/azure/hosting) explains different hosting scenarios: VM, WebSite, Cloud services and Cloud Services (with shared hosting)
- `Hosting in Cloud Services` (http://docs.particular.net/nservicebus/azure/hosting-in-azure-cloud-services) covers `Worker role` and `Web role` scenarios

`Azure` general section (10 articles): 
- `Azure Service Bus` 
- `Azure Storage Persistence`
- `Azure Storage Queues` (http://docs.particular.net/nservicebus/azure/azure-storage-queues-transport) that covers how to enable the transport and how to configure it. At the end explains supported transaction mode
- `Azure Transports`
- `Hosting in Azure`
- `Hosting in Azure Cloud Services`
- `Multiple Azure Storage Accounts for Scale Out` (http://docs.particular.net/nservicebus/azure/multiple-azure-storage-accounts-for-scaleout)
- `Shared Hosting in Azure Cloud Services` (http://docs.particular.net/nservicebus/azure/shared-hosting-in-azure-cloud-services) covers in details a paragraph listed in `Hosting in Cloud Services` article under `Hosting` section
- `Transaction in Azure` (http://docs.particular.net/nservicebus/azure/transactions) a detailed explanation about how to survive on Azure without DTC describing different scenarios: sharing local transactions, atomic operations and transport retries, sagas and compensation logic, routing slips and compensation logic. The article covers also "the need for idempotency".
- `Azure FAQ` (http://docs.particular.net/nservicebus/azure/faq)
- NOTE: _this section seems like a sort of aggregator for the others articles except for ASQ transport related article_

# Future doco structure

* No `Azure` section
* Each "component" to be listed with other related "components" (transport, persistence, host, etc.)
* Complex pages (like `Azure Service Bus` transport) to become a landing page with sub-pages such as configuration, transactions, performance tuning, etc. Sub-division not to be too fine grained. 

Suggested tree structure:

Azure Service Bus​
- Configuration
	- All settings
- Topologies
	- Endpoint Oriented
	- Forwarding
- Routing
	- Publisher Names @melkio
	- Multi namespace support
- Performance Tuning
	- Batching
	- Message Lock Renewal
	- Multi Namespace Support 
	- Message sender/receiver
- High Availability
	- Multi Namespace Support 
- Security & cryptography
	- Keep connectionstrings safe
	- MD5 vs SHA1
	- Namespace hierarchy

# Migration path

1. Adopt the existing content to the new structure: split files to fit new tree structure
2. Add new content

# Simon's original remarks (part of migration path)

so this is well out of date
http://docs.particular.net/nservicebus/azure/azure-transport

 * seems to be leaking in hosting details
 * needs to use snippets
 * hard coded to busConfiguration
 * better linking. eg do we have more reference material on "Hybrid scenario" or "Cloud hosting scenario"

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers can someone look at this?

**Comment by yvesgoeleven** [comment]
The azure document structure probably needs to change, split into something more specific to each transport, persistence, hosting, etc...

**Comment by SeanFeldman** [comment]
We need to layout the structure to start adding to the documentation

**Comment by melkio** [comment]
Filled `Current doco structure` section

**Comment by weralabaj** [comment]
@yvesgoeleven @SeanFeldman @melkio keep in mind that the same articles can be linked in a few places in the menu (as we currently do), so the question is mainly how to split the current and future content into articles. Where to put them in the menu could be discussed afterwards.

**Comment by SeanFeldman** [comment]
The whole `Azure` Section should disappear IMO. Transports should be under transports. Persistence under persistence, and so on.

**Comment by SeanFeldman** [comment]
Updated `Future doco structure` section.

**Comment by yvesgoeleven** [comment]
Existing doco has been migrated, but Simon's original remarks have not all been applied yet (snippets, busconfiguration)
