### ISSUE TITLE
SQL Transport V3 Multi-schema v3 backward compatibility

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1152]
Document how to setup an environment where a V6 endpoint using the SQL Transport and the multi-schema feature needs to exchange messages with endpoints based on previous versions of the SQL Transport.

Moved from https://github.com/Particular/NServiceBus.SqlServer/issues/135
Related to https://github.com/Particular/NServiceBus.SqlServer/issues/100

**Comment by weralabaj** [comment]
After discussing with @tmasternak we think it's not necessary to have a special guide. Important thing is to remember to update refs in samples and test. So I'll open issues for that.
