### ISSUE TITLE
Host shutdown guidance

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#1167]
Branched off from https://github.com/Particular/NServiceBus.Host/issues/51
Related to https://github.com/Particular/NServiceBus.Host/issues/56, which might have 'breaking changes' to documentation.

The idea is to provide proper guidance on how to setup a Windows Service and deal with termination by user and/or Windows.

According to [this documentation on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms685149%28v=vs.85%29.aspx):
- On Windows shutdown/reboot, you have an x-amount of settings, specified in the `WaitToKillServiceTimeout` registry key before Windows terminates the process. No option to extend it.
- On Windows Service shutdown via MMC plugin you have 125 seconds to shutdown, before Windows will mark the service is 'hanging'. After that, killing the process or reboot is required to restart the Windows Service.

We need guidance for developers and operations how to deal with Windows Services that hang indefinitely or improperly shut down due to system reboot or due to `Environment.FailFast`. Although not sure if we need to actually mention this, but instead inform users that it's possible it might terminate the current proces.

One of the reasons is that non-transactional transports and persistence might lose data. Another one is to properly set up service recovery.

**Added:**

> I forgot to mention to advice users to shutdown manually before rebooting the machine. That way the endpoint has time to gracefully shut down.

**Comment by dvdstelt** [comment]
I forgot to mention to advice users to shutdown manually before rebooting the machine. That way the endpoint has time to gracefully shut down.

**Comment by weralabaj** [comment]
@dvdstelt is that something we should do for v6? If so can you add the label?

**Comment by dvdstelt** [comment]
It's definitely not specific to V6, as this is a current problem. In V6 some of the problems go away due to various reasons, but it might still be a good decision to shut down the hosts yourself, before a reboot. :)

**Comment by weralabaj** [comment]
TODO: (moved from https://github.com/Particular/docs.particular.net/issues/1195)
- [ ] Document new shutdown behavior for SQL Server transport
- [ ] Document new shutdown behavior for MSMQ

**Comment by weralabaj** [comment]
@Particular/host-maintainers can you take care of it?

**Comment by SimonCropp** [comment]
@Particular/host-maintainers please submit a PR if you think this is valuable
