### ISSUE TITLE
add v6 store-and-forward

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1168]
Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/139

## Plan of Attack
 - [x] Update v5 and v6 samples [PR](https://github.com/Particular/docs.particular.net/pull/1362)

**Comment by SimonCropp** [comment]
@SzymonPobiega can u have a look at this one?

**Comment by SzymonPobiega** [comment]
@tmasternak the purpose of this sample was to show how to add store-and-forward feature to a transport that does not have it. The main target was SQL Server transport in multi-DB mode. With this sample, instead of sending messages directly to the other database, we would send it to ourselves and use outbox to push it to the other DB.

Since we are no longer supporting multi-DB/outbox combo in V6 (at least for now), does this sample still make sense? It does not make much sense in context of other transports (in this form).

**Comment by SzymonPobiega** [comment]
The alternative we can provide is a sample where we enable the outbox for the messages sent from `IMessageSession` but since we have not yet decided the fate of the outbox, I'd leave it for now.

**Comment by johnsimons** [comment]
Started the v6 version in #1216, if this does not go anywhere feel free to delete PR

**Comment by tmasternak** [comment]
@SzymonPobiega correct we decided to drop multi-DB/outbox combo in v6 so the sample does not really make sense.

**Comment by timbussmann** [comment]
@SzymonPobiega @tmasternak so can we close this since it wouldn't make sense on v6 as far as I understood you?

**Comment by SzymonPobiega** [comment]
@timbussmann :+1: for closing. I am not sure if we manage to provide a replacement for it in the 6.0 time frame but the proper replacement (which might come a bit later) would be allowing the outbox to be used with the message session unit of work. We discussed that with @andreasohlund recently. You would pass the dedup ID to the method that opens the session.

**Comment by SimonCropp** [comment]
@timbussmann or @SzymonPobiega can u please add some text that explains why there is no v6 version. or perhaps link to some upgrade guide or other page that handles that explanation?

**Comment by tmasternak** [comment]
@SimonCropp I think that we don't have a good place to link to yet. This should change this week. I've added this PR to PoA for Multi-instance in v6 issue and will track it from there.

**Comment by SimonCropp** [comment]
@tmasternak thanks

**Comment by weralabaj** [comment]
@SzymonPobiega @tmasternak Since I'm missing some context - do we now have the info we need?

**Comment by tmasternak** [comment]
@weralabaj We cannot support this sample in v6 as it is right now because we do not supoort DTC in `MultiLegacyInstanceMode`. There is some chance we can make it work with custom behavior and suppressing `TransactionScope` but we would have to check that.

**Comment by SzymonPobiega** [comment]
I'll check it.

**Comment by tmasternak** [comment]
It looks that we can still provide store-and-forward like behavior in V5 and V6. Once the #1362 is merged this should be done.

**Comment by weralabaj** [comment]
Merged sample
