### ISSUE TITLE
Clarify SQL transport transaction options

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1175]
SQL transport configuration doco does not mention transport transaction modes and only mentions DTC / native transaction / no transaction. These need to be reconciled.

A good way forward would be to move the discussion on SQL specific transaction modes to the Design doco and leave the transaction options to the main Transport Transaction doco page.

/cc @weralabaj

**Comment by indualagarsamy** [comment]
@andreasohlund @SzymonPobiega - Can you comment on the different modes for Sql and what they mean, so we can doco this?

**Comment by mauroservienti** [comment]
I'm sorry @indualagarsamy, but I cannot help here, @tmasternak knows a lot more than me in regards to  the transport transaction modes.

**Comment by tmasternak** [comment]
Here is the behavior in v3:
 * None - we operate in autocommit mode which means that when message is received from input queue it's removed from input queue. If processing fails the message is gone (no rollback). Any other operation performed on the transport send/receive is performed in auto-commit mode as well.
 * ReceiveOnly - input message is received using native transaction which gets committed only when message processing succeeds. This transaction is not shared outside of message receiver which means that there is possibility of persistent side-effects when processing fails e.g. ghost  messages.
 * SendsAtomicWithReceive - same as ReceiveOnly but transaction is shared with sending operations. What it means is that message receive operation and any send/publish operations are atomically committed.
 * TransactionScope - message receive operation and processing (including any send/publish operations) are performed inside TransactionScope. That enables any transactional resource used during message processing (e.g. persistence, db hodling user data) to enlist in it.

**Comment by weralabaj** [comment]
The issue was addressed by :
- Creating [transactions matrix](http://docs.particular.net/nservicebus/messaging/transactions#transactions-transaction-levels-supported-by-nservicebus-transports)
- Reviewing and updating content in the relevant section of the [SQL Server transport doco](http://docs.particular.net/nservicebus/sqlserver/design#transactions-and-delivery-guarantees)

I'm closing this issue.
