### ISSUE TITLE
List transports that support a given transaction mode

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1176]
We describe different [transport transaction modes](http://docs.particular.net/nservicebus/messaging/transactions#transactions) but do not tell the reader to which of the transport can a given option be applied.

On the other side, we need to clearly document how transport transaction modes map to transport-specific behaviors:
- [x] SQL: #1175 
- [x] MSMQ: #1184 
- [x] RabbitMQ: #1185 
- [x] ASQ: #1186 
- [x] ASB: #1187 

/cc @weralabaj @indualagarsamy

**Comment by andreasohlund** [comment]
:+1: 

So some kind of "Transaction support" matrix on http://docs.particular.net/nservicebus/transports/ ?

**Comment by MarcinHoppe** [comment]
Looks like a good place to put and link from http://docs.particular.net/nservicebus/messaging/transactions.

**Comment by SimonCropp** [comment]
@andreasohlund no not a matrix. Just different pages that explain it for each transport

**Comment by MarcinHoppe** [comment]
@SimonCropp That's one thing. Another thing is that we don't have an overview of what are transactional capabilities of different transports.

**Comment by indualagarsamy** [comment]
@MarcinHoppe - I added task list on the issue description.

**Comment by MarcinHoppe** [comment]
@indualagarsamy Thanks.

**Comment by weralabaj** [comment]
I started work on it, I suggest limiting it to v 6 for now only if possible and raising a new issue to cover others later.

**Comment by SimonCropp** [comment]
@weralabaj no objection to limiting to v6
