### ISSUE TITLE
How to author a custom NServiceBus V5 transport

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#118]

**Comment by SimonCropp** [comment]
closing this one. Any sample on "how to implement a transport" will get too bogged down in the details of the transport rather than the "how to" part. Also the ROI isnt there. Anyone who wants to implement a transport can look at the API xml doco combined with the exiting transports.

**Comment by indualagarsamy** [comment]
I think this topic could be more of a blog than our doco.

**Comment by mauroservienti** [comment]
it is hard to write a blog post for a thing like that, it evolves over time and over versions and needs to be kept up to date.

**Comment by dannycohen** [comment]
@mauroservienti - thinking about this, I think this can be re-phrased a blog post if taken from the point of view of "what would it take for me to create a transport-neutral wrapper that can provide various features like Retry, Reliability, Scalability, Auditing etc." 
Thoughts ?

**Comment by mauroservienti** [comment]
If I understood correctly: describe the effort involved in building a transport that supports all what we support so to basically tell, between the lines, buy don't make.
