### ISSUE TITLE
Clarify MSMQ transport transaction options

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1184]
MSMQ transport configuration doco does not mention transport transaction modes. These need to be reconciled with description on the [Transoport transactions](http://docs.particular.net/nservicebus/messaging/transactions) doco page.

/cc @weralabaj @indualagarsamy

**Comment by weralabaj** [comment]
would it be possible to get more details, similar to what Yves and Sean said on ASB https://github.com/Particular/docs.particular.net/issues/1187#issuecomment-187606884?

**Comment by weralabaj** [comment]
@andreasohlund in MSMQ do we differentiate between ReceiveOnly and SendAtomicWithReceive?

**Comment by andreasohlund** [comment]
No, but we should => https://github.com/Particular/NServiceBus/issues/3562

**Comment by weralabaj** [comment]
@andreasohlund Given that it was decided to be low-impact should I document as it is now?

**Comment by andreasohlund** [comment]
Just doco that ReceiveOnly works just like SendAtomicWithReceive and make a note that its a "known issue"?
