### ISSUE TITLE
Clarify RabbitMQ transport transaction options

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1185]
RabbitMQ transport configuration doco does not mention anything about [transport transaction modes](http://docs.particular.net/nservicebus/messaging/transactions). These need to be reconciled.

/cc @weralabaj @indualagarsamy

**Comment by indualagarsamy** [comment]
@bording - Can you please comment on this issue on what the modes are and what they mean, so we can capture them in doco? Thanks.

**Comment by bording** [comment]
The highest transaction mode that RabbitMQ supports is Receive Only.

**Comment by weralabaj** [comment]
@bording would it be possible to get more details, similar to what Yves and Sean said on ASB https://github.com/Particular/docs.particular.net/issues/1187#issuecomment-187606884?

**Comment by bording** [comment]
After making some changes in the v5 version of the transport to backport a fix, I want to review the v6 version to make sure everything is correct. Let me do that first, and then I should be able to give you some more details.

**Comment by indualagarsamy** [comment]
@bording - after all the conversations we've had regarding transaction modes, are we in a good position to update this now?

**Comment by bording** [comment]
I'm still working through some changes to the core v6 version of the transport that came out of those discussions, but I'm almost done with them. Once that's done then I should be able to go into more detail.

Looking over this issue, is this scoped to just the core v6 version of the transport, or do you need details for v5 as well?

**Comment by weralabaj** [comment]
@bording for now it's V6 specific and should also cover differences between V5 and V6 (what to expect after upgrade), we can extend it later

**Comment by weralabaj** [comment]
ping @bording, do we have info we need now?

**Comment by bording** [comment]
#1395 is merged, so this is done.
