### ISSUE TITLE
topology and infrastructure guidance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1188]
This targets mainly new customers or people new to messaging based architecture. I was [on site at a customer](https://github.com/Particular/CustomerSuccess/issues/166) and on of the issues raised was the lack of guidance around infrastructure, and topology, required to support a large system (as the one they have). This lack caused them, for example, to mis configure ServiceControl.

**Comment by SimonCropp** [comment]
@mauroservienti not really enough information to act on here. perhaps work with the @Particular/servicecontrol-maintainers to submitting a draft PR
