### ISSUE TITLE
Guidance ServiceControl deployment considerations

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1189]
Some high level docu on how and where to deploy ServiceControl in a production environment based on a broker-based transport.
During an [on site review](https://github.com/Particular/CustomerSuccess/issues/166#issuecomment-180225876) emerged that the Ops team completely misunderstood how ServiceControl was expected to be deployed.

Should we link such a thing from the `Platform Installer` as well?

**Comment by weralabaj** [comment]
@mauroservienti is that helpful http://docs.particular.net/servicecontrol/servicecontrol-in-practice? If so would that issue be solved by adding a link somehwere?

**Comment by mauroservienti** [comment]
I'll review that @weralabaj and report back here, thanks.

**Comment by mauroservienti** [comment]
All what is needed is listed, however my experience with https://github.com/Particular/CustomerSuccess/issues/166 says that customers don't get there or they don't read enough. How can we improve that?

**Comment by weralabaj** [comment]
Hm... I think the article itself is fresh, it didn't exist when you were at the customer's site that might be the part of the reason ;)
Generally though, maybe creating some "getting started" page with links to the important resources?

**Comment by mauroservienti** [comment]
> Generally though, maybe creating some "getting started" page with links to the important resources?

it might be part, or a follow up, to the `first time user experience` initiative.

**Comment by weralabaj** [comment]
@mauroservienti is that still relevant? anything to do here?

**Comment by mauroservienti** [comment]
Everything we need is listed here https://docs.particular.net/servicecontrol/servicecontrol-in-practice
I still believe, with no evidence, that we should link that page in the Platform Installer or find a better way to drive customers there

**Comment by weralabaj** [comment]
How about adding a warning/note box on this page https://docs.particular.net/servicecontrol/ with a link?

> I still believe, with no evidence, that we should link that page in the Platform Installer or find a better way to drive customers there

I'm concerned this is true for most of our documentation, so why this one is special? ;)

**Comment by weralabaj** [comment]
I added comment https://github.com/Particular/docs.particular.net/commit/be123887abc4984277edd4ba462af179c4b631d0 with a link, for now I don't see other quick wins.
