### ISSUE TITLE
Guidance on virtualization, high availability, redundancy and scaleout

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1198]
We currently only have guidance on howto setup a HA distributer using Windows Clustering. We need guidance to also mention that a customer can setup a HA virtual machine that does not have to rely on windows clustering but rely on the virtualized infrastructure for HA.

If their virtualized environment does not support HA VM hosting then can point to windows clustering when using MSMQ.

Keywords:

- MSMQ
- Distributor
- Virtualization
- Live migration (vMotion)
- High availability
- Windows Clustering
- SAN HA
- Virtualization HA
- Virtual storage
- Redundancy
- Scaling
- Staleness
- Backup
- Disaster Recovery
- Fault Tolerance

**Comment by ramonsmits** [comment]
@indualagarsamy @jdrat2000 
> The challenge is there are MANY ways to recover state in a virtual machine.  Any of them can work.  HA, Vmotion,  even some backup solutions like VEEAM capture snapshots.   How updated the storage is will determine how much state/data you lose.   It's an infrastructure requirement depending on their SLA which the VM team internally would have to manage.  They rank from lower cost where machine dies on host A and you manually migrate it to machine B to putting the MSMQ on a separate volume and re-mounting it to a totally different host.     Some people have their SAN sync in near real time and bring the VM up in another datacenter.  Others pay even more $$ and have the RAM synch in real time.

**Comment by SimonCropp** [comment]
@ramonsmits can you outline how this would be NSB specific doco rather than simply "generic doco on MSMQ"?
