### ISSUE TITLE
Worker disconnect improvements

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1203]
- Add that when a worker is restarted, it reenlist itself at the distributor
- Then worker is disconnected, while worker is busy, distributor is restarted, the worker is not disconnected.

**Comment by SimonCropp** [comment]
given the current status of the distributor moving forward i am closing this one. please feel free to open a PR if u think it is still work doinggiven the current status of the distributor moving forward i am closing this one. please feel free to open a PR if u think it is still work doing
