### ISSUE TITLE
Encryption service changes to the upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1207]
http://docs.particular.net/nservicebus/upgrades/5to6#encryption-service

related:
 
 * https://github.com/Particular/docs.particular.net/pull/1199
 * https://github.com/Particular/NServiceBus/pull/3063

**Comment by WojcikMike** [comment]
@SimonCropp @ramonsmits I am not entirely sure what to put into migration guide. As Particular/NServiceBus#3063 Is just a port of already implemented change to v5: https://github.com/Particular/NServiceBus/pull/3000 

Which means that if one is on v5.2.11+ then there are no changes (at least that were part of this PR). However if customer is on version lower than 5.2.9 than there will be differences that were documented in a release notes and we could refer to them, or inspire content creation by it (copy). What do you think?

**Comment by SimonCropp** [comment]
If it is a 1 to 1 api with v5 then feel free to close this

**Comment by WojcikMike** [comment]
I checked it and it is identical.
