### ISSUE TITLE
Distributor workers do not support zero downtime / side-by-side

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1212]
Workers cannot support zero downtime / side-by-side configurations like normal MSMQ endpoints do support.

Workers have a worker session ID which is different between multiple instances.

As the distributor is used if a single endpoints is not enough to meet a desired SLA. Because the worker does not support rolling upgrades / zero downtime / side-by-side it could mean that while a worker is down the SLA cannot be met.

**Comment by SzymonPobiega** [comment]
Not sure I understand. There is usually more than one worker so somebody can upgrade them one-by-one. In V6 this is a non-issue because input queue names are stable (based on endpoint name) even in distributor setup.

**Comment by SimonCropp** [comment]
given the current status of the distributor moving forward i am closing this one. please feel free to open a PR if u think it is still work doing
