### ISSUE TITLE
Why don't all upgrade articles relate to each other?

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#1223]
Of the three upgrade guides:
* [3to4](http://docs.particular.net/nservicebus/upgrades/3to4)
* [4to5](http://docs.particular.net/nservicebus/upgrades/4to5)
* [5to6](http://docs.particular.net/nservicebus/upgrades/5to6)

I noticed:
* All are tagged `upgrade` and `migration`.
* 3to4 and 4to5 have no related articles
* 5to6 has as related articles:
  *3to4, but I don't know why
  * [Sagas and Concurrency](http://docs.particular.net/nservicebus/sagas/concurrency) which does make sense as it's in the YAML

How does 5to6 get 3to4 as a related article based on the metadata I see? And shouldn't they all be related to each other?

**Comment by SimonCropp** [comment]
@DavidBoike 5to6 doesnt have 3to4. it has "Upgrade NServiceBus.RavenDB from 3 to 4"

no i dont think they need to be all related to each other. the breadcrumb at the top allos that level of navigation

**Comment by DavidBoike** [comment]
Ah, I get it. Sorry! My brain skimmed right over "RavenDB" there

**Comment by SimonCropp** [comment]
@DavidBoike no worries
