### ISSUE TITLE
Upgrade to v6 "Accessing the current message context" should use snippets

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1227]
http://docs.particular.net/nservicebus/upgrades/5to6#unicastbus-made-internal-accessing-the-current-message-context

the code in that md it broken. it should move over to be snippets

**Comment by SimonCropp** [comment]
Done here https://github.com/Particular/docs.particular.net/commit/b496abd9ccd274082e72eb16d6a4fbe8fd16f59a

@danielmarbach can you look at this one

**Comment by danielmarbach** [comment]
I made inline notes and will add snippets
