### ISSUE TITLE
"upgrade: Transaction configuration API" move to snippets

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1228]
http://docs.particular.net/nservicebus/upgrades/5to6#transaction-configuration-api

should be snippets

**Comment by SimonCropp** [comment]
done here https://github.com/Particular/docs.particular.net/commit/9873c130a354b0388ba3fd6af157d527b63e5261

so @andreasohlund can u work on this

**Comment by andreasohlund** [comment]
Trying to trick @MarcinHoppe into doing this, stay tuned

**Comment by MarcinHoppe** [comment]
I'll do it.
