### ISSUE TITLE
Split out gateway upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1229]
http://docs.particular.net/nservicebus/upgrades/5to6#gateway

the next release of https://www.nuget.org/packages/NServiceBus.Gateway/1.0.1 will be 2 so it does not make sense to be in the 5to6 upgrade guide

**Comment by SimonCropp** [comment]
done here
https://github.com/Particular/docs.particular.net/commit/adfb2d44e8f6d59e387d7952efb8087679d4d32b

so @janovesk can you work on this one

**Comment by janovesk** [comment]
The gateway is still part of what the customer considers NServiceBus even though it is in its own package.

Customers need to know this when they upgrade an endpoint with the gateway from version 5 to version 6. And you can't upgrade just the gateway from version 1 to version 2 without upgrading NServiceBus version 5 to 6. 

I think it makes sense to have all this in a single upgrade guide. @SimonCropp

**Comment by SimonCropp** [comment]
@janovesk that won't work. It is plausible that another release of the gateway will happen in the v6 timeframe. That would void the current approach
