### ISSUE TITLE
duplicate snippet:Routing-StaticRoutes-Endpoint

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1234]
this page http://docs.particular.net/nservicebus/scalability-and-ha/scale-out#routing-staticroutes-endpoint-v6-pre

imports the same snippet twice `snippet:Routing-StaticRoutes-Endpoint`

@SzymonPobiega is this correct?  if so can we reference that above these two headings?

**Comment by SzymonPobiega** [comment]
Yes, it is correct. I can replace the second usage with a note that broker transport require only logical routing "as shown above"

**Comment by SimonCropp** [comment]
fixed
