### ISSUE TITLE
Do a search and QA on usages of `IBus`

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1237]

**Comment by WojcikMike** [comment]
I will first identify places where IBus is used and then decide colelctively decision will be made which sentences fix in what way

**Comment by WojcikMike** [comment]
After I searched the doco for IBus reference I found following files (I search only through *.md files):

* [NServiceBus/Containers/Index IBus Resoultion Section] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/containers/index.md#ibus-resolution)
* [NServiceBus/Containers/Index Cleanup Section] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/containers/index.md#cleanup)
* [NServiceBux/Containers/Injecting IBus] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/containers/injecting-ibus.md) - this one contains note saying that in v6 IBus was removed but I would add a link to a page showing sample with IMessageHandlerContext 
* [NServiceBus/gateway/Index Using the gateway first line] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/gateway/index.md#using-the-gateway)
* [NServiceBus/histing/publishing from web applciation - Storage Driven Transport Topology section] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/publishing-from-web-applications.md#storage-driven-transport-topology)
* [NServiceBus/messaging/memory-transport How to Raise In memory... section] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/memory-transport.md#how-to-raise-an-in-memory-event)
* [NServiceBus/messaging/reply-to-a-message ] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/reply-to-a-message.md) - summary field
* [NServiceBus/sagas/reply-replaytooriginator-differences] (https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sagas/reply-replaytooriginator-differences.md) - contains a note that IBus is deprecated but summary still contains IBus
* [samples/hosting/multi-hosting/sample] (https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/multi-hosting/sample.md)
* [samples/hosting/windows-service/sample] (https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/windows-service/sample.md#code-walk-through)
* [samples/web/asp-mvc-app/sample Initialize the Bus Section and below]  (https://github.com/Particular/docs.particular.net/blob/master/samples/web/asp-mvc-application/sample.md#initializing-the-bus) - 6 occurrences
* [samples/web/asp-mvc-injecting-bus/sample Injection into the controller] (https://github.com/Particular/docs.particular.net/blob/master/samples/web/asp-mvc-injecting-bus/sample.md#injection-into-the-controller) - summary field as well
* [samples/web/asp-web-application/sample Initializing the bus section & Handling the message section] (https://github.com/Particular/docs.particular.net/blob/master/samples/web/asp-web-application/sample.md#initializing-the-bus)
* [samples/web/owin-pass-through/sample The endpoint configuration section] (https://github.com/Particular/docs.particular.net/blob/master/samples/web/owin-pass-through/sample.md#the-endpoint-configuration)

**Comment by WojcikMike** [comment]
Documentation and Samples are updated still working on Endpoint/Endpoint Instance concept description

**Comment by WojcikMike** [comment]
Ok, everything is done in this manner. Closing the issue
