### ISSUE TITLE
Include upgrade guides in menu

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1239]
Currently upgrade guides are not accessible from menu, they can be accessed by search, "related" links or direct links.

Given we split upgrade guides per package in v6, we should provide a better way to access them. I suggest including in menu, other ideas are welcome.

**Comment by mikeminutillo** [comment]
:+1: We could have a landing page that includes general advice as well such as

- Do not skip majors
- Update one endpoint at a time (they are wire compatible anyway)

**Comment by SimonCropp** [comment]
flagging this a v6

should be trivial to achieve.

how about we go with 

 * a 2nd level menu under NSB 
 * a 3rd level menu under the related areas. eg under rabbitmq  http://docs.particular.net/nservicebus/rabbitmq/

**Comment by weralabaj** [comment]
@SimonCropp +1, I think in the NSB menu that should be somewhere high (1st, 2nd menu element?)

we also need to include release policy there etc. (http://docs.particular.net/nservicebus/upgrades/release-policy)

**Comment by SimonCropp** [comment]
done http://docs.particular.net/nservicebus/upgrades/

@mikeminutillo think your other points are covered here http://docs.particular.net/nservicebus/upgrades/release-policy#we-backport-important-bugfixes
