### ISSUE TITLE
Upgrade guide v5 to v6 - document obsoletes

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1245]
`IManageMessageFailures` is not documented, there might be more.

**Comment by SimonCropp** [comment]
@weralabaj was that actually obsoleted in v6? ping @andreasohlund

**Comment by weralabaj** [comment]
@SimonCropp yes, see the header on that interface ;)

**Comment by andreasohlund** [comment]
Yes, obsoleted in favor of the notifications

**Comment by indualagarsamy** [comment]
@weralabaj - I've documented both IManageMessageFailures and ISatellites and IAdvancedSatellites. But we should open separate issues for it IMO. 
Here are the issues regarding those interfaces.
https://github.com/Particular/docs.particular.net/issues/1281
https://github.com/Particular/docs.particular.net/issues/532

**Comment by indualagarsamy** [comment]
@weralabaj - Did you mean for this issue to be more of a checklist? If so can you be clear in the issue description? If not can we close this?

**Comment by weralabaj** [comment]
Resolved by @indualagarsamy
