### ISSUE TITLE
document rabbit DisableCallbackReceiver and CallbackReceiverMaxConcurrency removal

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1249]
and handle fixing this hack https://github.com/Particular/docs.particular.net/commit/acfaa0875d8232ecd3e4ecde88bca0061186115d

**Comment by mauroservienti** [comment]
@SimonCropp does this affects the upgrade guide as well?
@bording can you handle this?

**Comment by SimonCropp** [comment]
@mauroservienti i would think rabbit needs its own upgrade guide

**Comment by WojcikMike** [comment]
@SimonCropp @mauroservienti I decided to create two issues to correspond to this ask and decision made in this task:
#1356 - to upgrade whole configuration-api for Rabbit
#1357 to create upgrade guide. Becasue of that I will close this issue, so we don't have duplicates
