### ISSUE TITLE
Perf counters for satellites are no longer provided in v6

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#1251]
This needs to be added to the upgrade guide, see https://github.com/Particular/NServiceBus/issues/3079  for details

**Comment by andreasohlund** [comment]
We might still support this https://github.com/Particular/NServiceBus/issues/3079 so lets hold off with this until we get closer to launch

**Comment by andreasohlund** [comment]
Looks like  Particular/NServiceBus#3079 is not going yo get done so this is needed before we go live

**Comment by indualagarsamy** [comment]
@andreasohlund - Looking at the linked issue isn't informative enough. At least I couldn't get enough information regarding the below:

What performance counters are no longer supported? All of them? Ones from v3, v4 and v5?
Is there any indication to the user that's starting the endpoint that currently has those counters enabled to know that they may not work?

**Comment by andreasohlund** [comment]
>What performance counters are no longer supported? All of them? Ones from v3, v4 and v5?

All counters are still provided but we no longer provide counter instances for satellites

In short: Instances for eg. "timeouts" and "timeoutsdispatcher" no longer shows up as available instances in perfmon. 

I know that v5 provided `Num messages pulled from q`, `Num messages successful` and `Num messages failed` for satellites. Not sure if we provided processing time and critical time? (needs to be verified)

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers this would seem to be un finished work from v6. please submit a PR if you still feel this is important
