### ISSUE TITLE
Review Raven-related docs for V6

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#1252]
This is dependent upon my changes related to the NSB.Raven 3.1.1 release. (No PR yet, will update when there is one.)

Connects to https://github.com/Particular/PlatformDevelopment/issues/733

**Comment by weralabaj** [comment]
@DavidBoike given that the issue you referenced is closed, is it now a good time to work on it? or maybe it's been done already? in such case please close.

**Comment by weralabaj** [comment]
Also related issue https://github.com/Particular/docs.particular.net/issues/1128
