### ISSUE TITLE
Create a Guidance Area

### ISSUE THREAD

**Issue by petersgiles** [Particular/docs.particular.net#1254]
Recently we created http://docs.particular.net/servicecontrol/servicecontrol-in-practice which concerned itself with helping our customer think more broadly about ServiceControl's strengths in different circumstances.

It took some time to settle on a format that suited our docs but I think the final product was so good that we should take the time to produce more.

I would like to a see a section in the docs menu called Guidance. 

Here is a list I can think would be useful off the top of my head but I'm sure this could be expanded as there are so many desk cases with customers asking "how do I..." or "what's the best way to..."

- [x] [ServiceControl in Practice](https://github.com/Particular/docs.particular.net/pull/1241)
- [ ] Distributed Transaction Management with NSB (outbox vs MSDTC)
- [ ] Managing Change with NSB (How to design sagas and handlers to be resilient to change)
- [ ] [Choosing a Transport](https://github.com/Particular/docs.particular.net/pull/791)
- [ ] Choosing a Persistence
- [ ] Unpicking a Big Ball of Mud with NSB (how to take a bit of you domain and isolate it)

There are also mini [guidances](https://github.com/Particular/docs.particular.net/search?utf8=%E2%9C%93&q=guidance) within the doco that could be pulled out into something more coherent or aligned with a practice.

I just read [this article](https://blog.prototypr.io/product-and-content-are-two-sides-of-the-same-value-proposition-acadba6aa65b#.vp1mp0pee) and the following quote articulates my interest in this.

>    [Commercial insight is] designed to upend the status quo. As such, insight isn’t about one thing, it’s about two things. [Unlike thought leadership, it] doesn’t just convey an idea of what the customer could be doing…but also conveys a story around what the customer is currently doing, explicitly laying out why the current behavior is costing the customer time or money in ways they never realized.

>    That’s the key. The contrast. It’s the cost of current behavior juxtaposed to the potential of alternate action.

>    -p67, The Challenger Customer

It's about saving the customer time, money and embarrassment. We are the 'thought leader' and buying licenses is the commercially actionable thing they can do to take advantage of our guidance. The documentation as it stands doesn't achieve that.

> Customers buy products because of what those products enable them to do, the value of which is communicated and partially delivered (in the form of education) through content.

We are capable of growing our content to deliver quality advice that will in turn drive people to our product. IMHO these guidances are the beginning of that.

/cc @DavidBoike @SimonCropp @mikeminutillo

**Comment by SimonCropp** [comment]
@petersgiles i think this is a very large piece of work. the end result may not even be placed in this repo. ie it could go into a diff site. so i suggest closing this and raising in platform dev
