### ISSUE TITLE
operational scripting for ASQ

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1256]
Similar to
- [RabbitMQ](http://docs.particular.net/nservicebus/rabbitmq/operations-scripting)
- [SQL](http://docs.particular.net/nservicebus/sqlserver/operations-scripting)
- [MSMQ](http://docs.particular.net/nservicebus/msmq/operations-scripting)

to complete the [native integration sample](https://github.com/Particular/docs.particular.net/issues/887)

**Comment by SimonCropp** [comment]
@yvesgoeleven since we dont currently have any operational scripting for azure i dont think this should have a v6 label

**Comment by Scooletz** [comment]
@yvesgoeleven Could you clarify this issue? In my opinion it's not needed for beta of ASQ.

**Comment by yvesgoeleven** [comment]
@Scooletz this is indeed not needed for beta and can be done later. The intent is to have similar doco like the transports mentioned where we show how to do native integration as well as powershell scripts to set up the queues as part of an installation script

**Comment by SeanFeldman** [comment]
Suggested approach to take is similar to [ASB](https://docs.particular.net/nservicebus/azure-service-bus/operational-scripting).
- [.NET API](https://docs.microsoft.com/en-us/azure/storage/storage-dotnet-how-to-use-queues)
- [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/queue-service-rest-api)
etc

**Comment by SeanFeldman** [comment]
Moved to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/204.
