### ISSUE TITLE
ASB SendVia feature & it's impact on 'transactional behavior'

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1257]
Document how we leverage the sendvia feature to improve transactional consistency in the ASB transport and under what conditions it is available/used

**Comment by indualagarsamy** [comment]
@Particular/azure-service-bus-maintainers - any updates on this?

**Comment by SeanFeldman** [comment]
Documented [here](http://docs.particular.net/nservicebus/azure-service-bus/understanding-transactions-and-delivery-guarantees?version=ASB_7)
