### ISSUE TITLE
ASB Topologies

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1259]
Document the concept of a topology in ASB & it's concrete implementations (how they work)

- [x] Concept
- [x] Endpoint Oriented Topology
- [x] Forwarding Topology
- ~~Authoring a custom?~~

**Comment by weralabaj** [comment]
Would Sean's post be a good starting point here http://weblogs.asp.net/sfeldman/choosing-topology-with-azure-service-bus? 
Is authoring custom topology relevant for beta? If not is that a big effort to cover it?

**Comment by SeanFeldman** [comment]
@weralabaj authoring a custom topology is a very advanced topic, usually would be after new version of NSB and transport are well understood. So probably not a candidate for the beta.

Authoring a custom topology should be a separate issue outside of `v6 launch`. Opened #1394 for that.
