### ISSUE TITLE
Pub/Sub in MSMQ HOL guide inaccurate

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#126]
User feedback:

> Section involving modifying App.Config was innaccurate in manual.

* Relates to Lab103, "[Publish Subscribe using MSMQ](http://online.holsystems.com/Software/holLaunchPadOnline/holLaunchPadOnline.application?eng=NServiceBus&auth=none&src=microsoft.holsystems.com&altadd=true&labid=8969)"
* Submitted 12/24/2013 

#### Note:

* This issue relates to a Hands On Labs which is part of the guidance platform we're supplying / supporting. 
* I believe this would be a good location for guidance related issues, regardless of whether they are in articles or HOLs.

**Comment by SimonCropp** [comment]
over a year since update I assume this is done. if not please re-raise it in https://github.com/Particular/HandsOnLabs/issues
