### ISSUE TITLE
ASB entity name length limitations and how to change the validation rules

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1262]
As the rules for naming entities in ASB changes every now (https://github.com/Particular/NServiceBus.AzureServiceBus/issues/28) and then, it's important that we document our current assumptions here, and teach users how they can change our validation rules if needed

Possibly, completely covered by #1629 PR. Please verify.

**Comment by indualagarsamy** [comment]
@Particular/azure-service-bus-maintainers - can you update this issue? Seems like `Entity name length limitations and how to change the validation rules #1262` has been completed?

**Comment by SeanFeldman** [comment]
@indualagarsamy working on other items from the list in https://github.com/Particular/V6Launch/issues/81 Needs to be verified. If indeed it's already covered, we'll close the issue.

**Comment by SeanFeldman** [comment]
Going to close this one. As @indualagarsamy outlined correctly, this is already covered by PR #1629.
