### ISSUE TITLE
ASB Batching

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1264]
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

Document how ASB's batching works in v7 and what throughput to expect from it

**Comment by SeanFeldman** [comment]
1. Entity batching `EnableBatching`
1. MessageFactory  (individual sends) `BatchFlushInterval`
1. Multiple messages from a single handler: batching with size limit 
  1. Msg size difference between tiers
