### ISSUE TITLE
ASB MaxRetries

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1265]
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

Document how ASB MaxRetries works vs Core's MaxRetries

- [x] Differences between Standard & Forwarding Topology
- [x] What to keep in mind when scaling out (and why)

**Comment by weralabaj** [comment]
Isn't that covered in http://docs.particular.net/nservicebus/azure-service-bus/retries? Anything left to do or could we close?

**Comment by yvesgoeleven** [comment]
We can close it
