### ISSUE TITLE
ASB Document the structure of the new configuration API

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1270]
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

ASB now has a code only configuration api, which has quite a lot of options, we should provide a document that shows how it is structured (leave all the details for topic oriented doco)

**Comment by SeanFeldman** [comment]
- [ ] Structure https://github.com/Particular/docs.particular.net/issues/1270
 - [ ] `MaxDeliveryCount` change from 6 to 10
 - [ ] `ForwardingTopology` startup task will not allow partitioning on topic #131 
 - [ ] For XML based configuration, a sample to show how to do it. Same for Cloud Services configuration
(.cscfg) connect to Core https://github.com/Particular/NServiceBus/issues/3424

**Comment by yvesgoeleven** [comment]
Done in https://github.com/Particular/docs.particular.net/pull/1416
