### ISSUE TITLE
ASB Upgrade guide

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1271]
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

Provide an upgrade guide for asb

**Comment by weralabaj** [comment]
This probably should be a separate article in docs.particular.net\nservicebus\upgrades.

**Comment by SimonCropp** [comment]
i added a placeholder upgrade guide http://docs.particular.net/nservicebus/upgrades/asb-6to7

and some snippets https://github.com/Particular/docs.particular.net/commit/2069465b3ad496c669b4b65c4e50e33bcc418619
I could not work out how to convert NamingConventionsUsage and BrokeredMessageBodyConventionUsage. so i assume they should be in the upgrade guide

**Comment by yvesgoeleven** [comment]
Thank you @SimonCropp 

The API for changing naming convention rules is totally different now indeed, we'll cover it

**Comment by weralabaj** [comment]
Should we start compiling a TODO list when going through other issues?
One should be about topologies https://github.com/Particular/docs.particular.net/pull/1411#discussion_r59530293

**Comment by indualagarsamy** [comment]
@Particular/azure-service-bus-maintainers - can you please update this issue? What needs to be done? All the `Azure Servicebus Transport` items in the related issue seems to be struck out.

**Comment by SeanFeldman** [comment]
I'd like to include it as a part of the https://github.com/Particular/V6Launch/issues/81 to ensure the upgrade guide is up-to-date with the changes for RC. Originally it was for Beta.

**Comment by SeanFeldman** [comment]
Upgrade guide is in place. It will be reviewed again as part of RC work (https://github.com/Particular/V6Launch/issues/81).

Closing this issue.
