### ISSUE TITLE
ASB Batch size calculation

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1273]
ASB library [`BrokeredMessage.Size`](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.brokeredmessage.size.aspx) does not report message total size correctly. Data stored in [`BrokeredMessage.Properties`](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.brokeredmessage.properties.aspx) is not taken into consideration.

Repro code: [link](https://gist.github.com/yvesgoeleven/681b211f585c3402bf98)

TODO
* [x] Document
  * default message size padding 5%
  * configuration option

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/docs.particular.net/commit/a805273adc2ba3b1060a9c1c8eb1f425b9f6b5c3
