### ISSUE TITLE
ASQ Upgrade guide

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1275]
Connects to https://github.com/Particular/PlatformDevelopment/issues/723
Create an upgrade guide for ASQ

**Comment by weralabaj** [comment]
This probably should be a separate article in docs.particular.net\nservicebus\upgrades.

**Comment by SimonCropp** [comment]
i took the liberty of creating a placeholder page for this http://docs.particular.net/nservicebus/upgrades/asq-6to7 and adding it to the menu

**Comment by yvesgoeleven** [comment]
Thank you @SimonCropp

**Comment by timbussmann** [comment]
seems like this has been done by https://github.com/Particular/docs.particular.net/pull/1404 , so should we close this? @yvesgoeleven

**Comment by yvesgoeleven** [comment]
@timbussmann if http://docs.particular.net/nservicebus/upgrades/asq-6to7 contains all the changes need for ASQ, then you can close this one indeed (I did not make any changes to it in https://github.com/Particular/docs.particular.net/pull/1404 though)
