### ISSUE TITLE
ASQ Multinamespace support

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1276]
Document multi namespace support, with attention to

- [x] scaleout
- [ ] HA
- [ ] georeplication
- ~~sharding~~ currently not possible

**Comment by andreasohlund** [comment]
Since multinamespace is no longer in scope for v6 is there still something we need to do related to this or can we remove the label?

**Comment by Scooletz** [comment]
We need to create the page and include information about mapping the namespaces, which properly addresses sending messages to other accounts from the API perspective, but we don't have to elaborative now when we describe reasons for that.

**Comment by indualagarsamy** [comment]
@Particular/azure-storage-queues-maintainers - is this done? It;s hard to tell from the PR what's Azure Storage Related. Also a lot of the tasks are struck out as opposed to checked.

**Comment by SeanFeldman** [comment]
Update based on what I know:

1. scaleout - done [here](http://docs.particular.net/nservicebus/azure-storage-queues/multi-storageaccount-support)
1. HA - ???
1. georeplication - ???
1. sharding - not possible. General description updated.

**Comment by Scooletz** [comment]
I agree with @SeanFeldman . IMO this is done in its current format and can be closed. @yvesgoeleven Could you comment on this?

**Comment by yvesgoeleven** [comment]
we decided to only do scaleout for now, leave the rest for later. feel free to move those to other issues.

**Comment by Scooletz** [comment]
@yvesgoeleven but these issues haven't been implemented yet. Should we close this one and document these features once they are implemented?

**Comment by yvesgoeleven** [comment]
@Scooletz that's what I meant indeed, ensure there is an issue in the asq repo

**Comment by Scooletz** [comment]
I've updated the original issue for it https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/21 unpinning from the `v6` issue as well as removing already implemented parts (aliases). I'm closing this.
