### ISSUE TITLE
NSB Major version upgrade (migration) guide

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#128]
Customer Quote:

> Migrating from one version of NSB to another has been a miserable process, with numerous backwards incompatibilities that aren’t immediately obvious due to changes in the way the config should be written

**Comment by SimonCropp** [comment]
@dannycohen 

>  Is there an article that summarizes the upgrade policy and lists the resources to look at for troubleshooting any issues ?

yes http://docs.particular.net/nservicebus/release-policy

**Comment by SimonCropp** [comment]
replaced by https://github.com/Particular/docs.particular.net/issues/658
