### ISSUE TITLE
No Doco for `IManageMessageFailures` extension now obsolete message in v6

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#1281]
In version 5, in order to override the behavior of SLR and moving messages to error queue, the user can extend the IManageMessageFailures interface and do custom logic there. See v5 code. 

In Version 6, we now have an obsolete message:
IManageMessageFailures is no longer an extension point. If full control over what happens when a message fails (including retries) is required then override the MoveFaultsToErrorQueue behavior. To get notified when messages are being moved use BusNotifications.Errors.MessageSentToErrorQueue.Subscribe(e=>{})

However we don't have any doco on this in the upgrade guide. 

**Version 5 code**
```c#
public class CustomFaultManager : IManageMessageFailures, INeedInitialization
{
    public void SerializationFailedForMessage(TransportMessage message, Exception e)
    {
        Console.WriteLine("CustomFaultManager - SerializationFailedForMessage");
    }

    public void ProcessingAlwaysFailsForMessage(TransportMessage message, Exception e)
    {
        Console.WriteLine("CustomFaultManager - ProcessingAlwaysFailsForMessage");
    }

    public void Init(Address address)
    {
        Console.WriteLine("CustomFaultManager - Init");
    }
        
    public void Customize(BusConfiguration configuration)
    {
        configuration.RegisterComponents(c => c.ConfigureComponent<CustomFaultManager>(DependencyLifecycle.InstancePerCall));
    }
}
```

**Comment by indualagarsamy** [comment]
@SeanFeldman - any reason you removed the `Project: V6 Launch` label from this issue?

**Comment by SimonCropp** [comment]
@indualagarsamy it was a GH glitch. we need to go through and add them all back

**Comment by indualagarsamy** [comment]
@SimonCropp - ok, thanks.

**Comment by indualagarsamy** [comment]
PR merged. https://github.com/Particular/docs.particular.net/pull/1418
