### ISSUE TITLE
No Doco for this obsolete message 'Configure' is obsolete: 'This is no longer a public API'

### ISSUE THREAD

**Issue by petersgiles** [Particular/docs.particular.net#1282]
'Configure' is obsolete: 'This is no longer a public API. Will be removed in version 7.0.0.'

I looked through the [upgrade guide ](http://docs.particular.net/nservicebus/upgrades/5to6 ) and wasn't able to find examples of what to do.

I looked at the NServiceBus v6 code no hints there

``` C#
    [ObsoleteEx(
        Message = "This is no longer a public API",
        RemoveInVersion = "7.0",
        TreatAsErrorFromVersion = "6.0")]
    public class Configure
    {
    }
```

While I understand that it is likely that this was only used internally It would be nice to have some kind of clue as to what to replace it's usage with in downstream assemblies.

/cc @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Usually the replacement is either EndpointConfiguration or the Settings but
mostly endpoint configuration

On Tuesday, March 8, 2016, Pete <notifications@github.com> wrote:

> 'Configure' is obsolete: 'This is no longer a public API. Will be removed
> in version 7.0.0.'
>
> I looked through the upgrade guide
> <http://docs.particular.net/nservicebus/upgrades/5to6> and wasn't able to
> find examples of what to do.
>
> I looked at the NServiceBus v6 code no hints there
>
>     [ObsoleteEx(
>         Message = "This is no longer a public API",
>         RemoveInVersion = "7.0",
>         TreatAsErrorFromVersion = "6.0")]
>     public class Configure
>     {
>     }
>
> While I understand that it is likely that this was only used internally It
> would be nice to have some kind of clue as to what to replace it's usage
> with in downstream assemblies.
>
> /cc @Particular/nservicebus-maintainers
> <https://github.com/orgs/Particular/teams/nservicebus-maintainers>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/docs.particular.net/issues/1282>.
>


-- 
*Don't miss the Async/Await Webinar Series*
*• Learn more <http://go.particular.net/l/27442/2016-02-15/681bjl> →*

**Comment by petersgiles** [comment]
@danielmarbach thanks for the advice but I was asking where this decision to obsolete had been documented and where the documentation is for how to convert from `Configure` to `EndpointConfiguration` or whatever the right thing is. 

I had hoped that I wouldn't need to write it myself without any context. To me it seems to be a supreme waste of time for me to do all the investigation, trying to locate someone with the answers or dig through the code when @Particular/nservicebus-maintainers already have all the answers.

How is a customer who does not have access to @Particular/nservicebus-maintainers or intimate knowledge of our closed PRs and conversations going to manage upgrading to V6. There are literally dozens of things changing and there really isn't much information coming from the source.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers this need to be fixed in both the core and in doc. "This is no longer a public API" is not enough. so who should I assign this to?

**Comment by timbussmann** [comment]
@SimonCropp raise an issue, label as v6 and let anyone looking for work do it?

**Comment by andreasohlund** [comment]
@timbussmann not sure this is a low hanging fruit. The `Configuration` object was used by our self at runtime as a hack to provide access to settings and was never intended to be used by customers. We have to go through each one and see if there is some sensible guidance we can give. This requires indepth knowledge of the core and the changes that was made. 

@SzymonPobiega do you want to pair up with me sometime later this week and try to figure it out?

**Comment by SzymonPobiega** [comment]
`Later this week` might be hard. Probably next week. @andreasohlund do you have any ideas of cases we need to go through and document?

**Comment by andreasohlund** [comment]
I will deal with this next week (invite sent to @SzymonPobiega )

**Comment by SimonCropp** [comment]
@andreasohlund that was 2 weeks ago

**Comment by indualagarsamy** [comment]
@andreasohlund - any progress on this?

**Comment by andreasohlund** [comment]
PR opened

There is no obsoletes in the core for the individual properties. Should I add that? @Particular/nservicebus-maintainers  (not sure the ROI is there)
