### ISSUE TITLE
Document `Queue Schema=` in Connection String for Sql Transport

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#1304]
When using Sql Transport you can specify a schema for your queues in the connection string by adding `Queue Schema=<schema name>`.

This is not covered in http://docs.particular.net/nservicebus/sqlserver/configuration

**Comment by mikeminutillo** [comment]
Although it is covered here http://docs.particular.net/nservicebus/sqlserver/multiple-databases

@Particular/transport-maintainers would it make sense to have this in the general config doco?

**Comment by tmasternak** [comment]
@mikeminutillo As mentioned it is covered in multi-database section. I agree that it should be moved to some other than multi-database page. We should do it when cleaning up terminology used in the docs around multi-instance, multi-database and multi-schema deployments. /cc: @weralabaj

**Comment by weralabaj** [comment]
Ok I'm on it!

**Comment by weralabaj** [comment]
This issue is tracked now in https://github.com/Particular/NServiceBus.SqlServer/issues/139. So I'm closing this one.
