### ISSUE TITLE
Document how many queues are created in scale-out for all transports

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1317]
Raised here https://github.com/Particular/docs.particular.net/pull/1287#issuecomment-197263722.

For SQL Server it is covered here http://docs.particular.net/nservicebus/sqlserver/design#queues.

The goal of the issue is to review what information we provide now and decide if we need more. If so, then collaborate to document missing information for all transports.

**Comment by weralabaj** [comment]
@SzymonPobiega that seems to be related to https://github.com/Particular/docs.particular.net/issues/1732?

**Comment by SzymonPobiega** [comment]
@weralabaj yeah I think so.

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers @Particular/nservicebus-maintainers if you see this as valuable please submit a PR for your respective transports
