### ISSUE TITLE
make sqltransport-nhpersistence use an endpoint name

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1322]
make endpoints use an endpoint name

 * [x] `\Samples\outbox\sqltransport-nhpersistence\`
 * [x] `\Samples\outbox\sqltransport-nhpersistence\`
 * [x] `\Samples\outbox\sqltransport-nhpersistence-ef\`
 * [x] `\samples\sqltransport-nhpersistence`

**Comment by SimonCropp** [comment]
@SzymonPobiega can u work on this?

**Comment by SzymonPobiega** [comment]
@SimonCropp yeah
