### ISSUE TITLE
Explain our reasoning for the transition from "Bus" to "Endpoint" or "Message"

### ISSUE THREAD

**Issue by boblangley** [Particular/docs.particular.net#1327]
Would it be helpful to provide a short explaination, either in the 5-6 upgrade guide or elsewhere why we changed the names of some of our core objects?

We have adequately covered that they have changed, but should we provide some context / reasoning?

Relevant discussions:

* https://github.com/Particular/PlatformDevelopment/issues/600
* https://github.com/Particular/NServiceBus/issues/3411
* https://github.com/Particular/NServiceBus/issues/3401
* https://github.com/Particular/NServiceBus/issues/3399
* https://github.com/Particular/NServiceBus/issues/3425

/cc: @Particular/tf-v6-launch @indualagarsamy

**Comment by DavidBoike** [comment]
I vote absolutely. We will need to have an answer for this. Better to provide it proactively.

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - can you please add a list of relevant documents that needs to be updated based on the above?

**Comment by timbussmann** [comment]
@indualagarsamy That seems to be a task for the taskforce working on this issue?

**Comment by SzymonPobiega** [comment]
I think the best place is the intro to the upgrade guide where we outline key changes.

**Comment by indualagarsamy** [comment]
What I'd like to do is:
Have a proper introduction for the upgrade guide. 
Outline the major changes that are in v6. Namely the async and moving away from IBus to more into Contexts. And provide why we went that route. 
Rearrange some of the content, such as Endpoint Naming, IBus being obsolete etc to make more cohesive sense.

**Comment by SimonCropp** [comment]
@indualagarsamy still working on this? or should i remove your name?

**Comment by indualagarsamy** [comment]
What's major in v6 is more of a release notes / announcement thing.
What i've done in the PR is covered the IBus obsoletes and the various scenarios where IBus was previously used and what to do in each of the cases instead.
