### ISSUE TITLE
NSB supported transports article

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#133]
Raised by @dannycohen
Migrated from by https://github.com/Particular/NServiceBus/issues/1454

See, for example, article for [Windows Azure tranport](http://particular.net/articles/windows-azure-transport), including details on [config](http://particular.net/blog/nservicebus-v4.0-release-notes#transports), and referencing the VideoStore samples per transport

**Comment by mauroservienti** [comment]
@SimonCropp what about merging this with #134 ? or the intent is different?

**Comment by SimonCropp** [comment]
@mauroservienti agreed. closing
