### ISSUE TITLE
5to6 upgrade guide mentions IBusSession

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#1330]
http://docs.particular.net/nservicebus/upgrades/5to6#ibus-is-obsolete

`IBusSession` was renamed to `IMessageSession`

A search also reveals some other areas containing IBusSession:

http://docs.particular.net/search?q=IBusSession

I don't think I'm out of line marking this `Project: V6 Launch`.

**Comment by weralabaj** [comment]
Is it the only rename of that kind? Or maybe we should make this task a review of upgrade guide to make sure all interfaces and types are up to date?

**Comment by DavidBoike** [comment]
I think the full review would be the best idea.

**Comment by weralabaj** [comment]
This was covered in https://github.com/Particular/docs.particular.net/pull/1285.

**Comment by SimonCropp** [comment]
@weralabaj i dont think this is completely done yet http://docs.particular.net/search?q=IBusSession

**Comment by weralabaj** [comment]
Now should be good https://github.com/Particular/docs.particular.net/commit/9c1d69e9e3f4749630f4aa775caf19af3d800449.
