### ISSUE TITLE
Dead Branches

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1331]
The following branches seem dead. Can people either

 * create a PR so it can be discussed/merged/taken over by someone else; or
 * move it to a private fork; or
 * delete the branch

For any that i dont get a response on iwill be deleting on monday afternoon

The list:

 * [ ] https://github.com/Particular/docs.particular.net/tree/msmq-insufficient-resources @ramonsmits 
 * [ ] https://github.com/Particular/docs.particular.net/tree/authoring-custom-transports @yvesgoeleven 
 * [x] https://github.com/Particular/docs.particular.net/tree/obsolete-configureproperty @andreasohlund 
 * [x] https://github.com/Particular/docs.particular.net/tree/saga-concurrency-update @dvdstelt 
 * [ ] https://github.com/Particular/docs.particular.net/tree/serilog-seq @ramonsmits 
 * [ ] https://github.com/Particular/docs.particular.net/tree/sql-transport-multi-instance-sample @Particular/transport-maintainers 
 * [x] https://github.com/Particular/docs.particular.net/tree/unit-testing-samples @hmemcpy

**Comment by hmemcpy** [comment]
Sent a WIP pr for mine: #1336

**Comment by andreasohlund** [comment]
Removed mine

**Comment by SimonCropp** [comment]
dead branches deleted

**Comment by ramonsmits** [comment]
Is there any way I can still access these branches?

**Comment by SimonCropp** [comment]
only if u have a local copy of the repo where they are not deleted

**Comment by ramonsmits** [comment]
Then I'll check my laptop and desktop. Thanks @SimonCropp

**Comment by SimonCropp** [comment]
@ramonsmits i suspect either @weralabaj, @indualagarsamy or @mikeminutillo would have a local copy

**Comment by weralabaj** [comment]
Of which branch?

**Comment by ramonsmits** [comment]
Found them
