### ISSUE TITLE
clean up "Removed serviceControlUrl argument and changed path"

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1338]
https://github.com/Particular/docs.particular.net/commit/8a3a3f9ec1fcef27b43eded055d1b81603169afb#commitcomment-16778101

**Comment by ramonsmits** [comment]
@gbiellem @SimonCropp 

Just did a test without the argument to be sure. It is not needed as that value is used by default.

```js
;(function (window, angular, undefined) {  'use strict';

    angular.module('sc')
        .constant('version', '1.2.0')
        .constant('scConfig', {
            service_control_url: 'http://localhost:33333/api/'
        });

}(window, window.angular));
```

**Comment by gbiellem** [comment]
Should we add a note then that highlights the need to add it you aren't going with the default?

**Comment by ramonsmits** [comment]
@gbiellem What do you mean? Isn't this based on the currently configured value so will always match?

**Comment by ramonsmits** [comment]
Are you suggesting that we should document the commandline arguments that was rejected previously in #921 ?

**Comment by gbiellem** [comment]
@ramonsmits  I meant that without the command line option there is no indication in that doco that  the `service_control_url` should be set in the config if your SC isn't setup on the default URL.

That why I'm suggesting we either add a note or as I said [here](https://github.com/Particular/docs.particular.net/commit/8a3a3f9ec1fcef27b43eded055d1b81603169afb#commitcomment-16778101)  reorder the doco so the section about changing that setting isn't solely part of the reverse proxy config.

**Comment by SimonCropp** [comment]
seems done
