### ISSUE TITLE
Make Sean Farmar's integration sample official

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1339]
Sean has an interesting sample that he used with clients https://github.com/sfarmar/Samples/tree/master/WebServiceIntegration. I think it'd be valuable to make it an official sample.

The steps would be to review code, see if all is clear and doesn't need any changes, then write description explaining what that sample does and why.

IMO that could also be potentially included in guidance content for integration.

**Comment by weralabaj** [comment]
@SimonCropp that's related to the [upcoming webinar](https://github.com/Particular/Events/issues/212) that Sean and Joe are working on. They can publish sample in Labs or somewhere else, but I think it'd be useful to have that in official docs. What do you think?

**Comment by SimonCropp** [comment]
Samples are meant to show the smallest amount of code to get an idea across. That code base does not seem to meet that criteria.

The exception to that rule is the showcase. Which shows many features together. 

So if there is some scenario in that sample that is not covered by other samples then we should add a new targeted sample with just that code.

If it is using some compelling feature then that feature should be used in the showcase

**Comment by SimonCropp** [comment]
@weralabaj @sfarmar closing this for now. if u still think it qualifies then please re-open with some more ino
