### ISSUE TITLE
Detail how to do a clean uninstall of ServiceControl 

### ISSUE THREAD

**Issue by gbiellem** [Particular/docs.particular.net#1340]
Related to https://github.com/Particular/ServiceControl/issues/702

Detail how to uninstall
Detail what's left behind after an uninstall i.e queues, any empty directories and UrlAcls

**Comment by indualagarsamy** [comment]
@gbiellem - any updates on this?

**Comment by gbiellem** [comment]
@indualagarsamy  - Sorry dropped the ball here.  This one is still something I intend to do though.
Will get to it in the new year

**Comment by SimonCropp** [comment]
@gbiellem can u submit a draft PR for this

**Comment by timbussmann** [comment]
@Particular/servicecontrol-maintainers I think we should reopen this issue. I saw this question coming up from users.

**Comment by weralabaj** [comment]
@timbussmann since 2 out of 3 people involved in that issue have left, I think we should open a new one. can be with identical description, doesn't matter.

**Comment by timbussmann** [comment]
@weralabaj fine with that. Reraised this here: https://github.com/Particular/docs.particular.net/issues/3483
