### ISSUE TITLE
Guidance content on security in SQL Server transport

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1347]
@ramonsmits could you list what you had in mind specifically?

**Comment by SimonCropp** [comment]
@weralabaj @ramonsmits this does not have enough context to move forward. either give some more details or close the issue

**Comment by ramonsmits** [comment]
Instead of relying on message encryption a customer can also use connection, table, database encryption.

Basically, differentiate between:

- Message
- Transport
- Storage

Together with some links to the relevant MSDN guidance.

**Comment by ramonsmits** [comment]
Confused with a different part. This was probably about authorization on tables.

Mention that there is a difference between reads (receiver/sender) / writes (sender).

Endpoint A should R/W to its queues, but not R from others. How to set this up.

Mention that all endpoints only need write access to AUDIT and ERROR queues.

**Comment by SimonCropp** [comment]
@ramonsmits can u submit a draft PR that include your above notes
