### ISSUE TITLE
Document how devops should host  and maintain and upgrade endpoints in production

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#135]
- Why is the nsb host preferred
- Tips and trick for IIS hosting https://groups.google.com/forum/#!msg/particularsoftware/IsL4ATSqAXY/edKXby7SBPUJ
- Win services should be set to restart automatically (sc.exe to setup the restarts)
- How "on critical error" behaves for the different hosting options and the reasoning behind why we kill the process when we detect critical issues 
- Side by side deployments

**Comment by mauroservienti** [comment]
I see a relation with #491 what about merging them or correlating them in some way:

* setup
* maintenance

**Comment by mauroservienti** [comment]
Also #164 is related to this

**Comment by weralabaj** [comment]
@andreasohlund given that we're planning to get rid of NSB host is that still relevant? Should that be replaced by another issue or maybe could you update description to be more aligned with our current thinking?

**Comment by andreasohlund** [comment]
I'd say still relevant since this isn't tied to our host at all.

Perhaps this is covered by the launch wave? ( @Particular/launchwave-devopsadvancedmonitoring-squad )

**Comment by udidahan** [comment]
I'd like to clarify something:

There hasn't yet been any decision to "get rid of the NSB host".

**Comment by SimonCropp** [comment]
@andreasohlund this would seem to be well out of date and and bundling a large amount of work together. I suggest raising a plat dev issue instead
