### ISSUE TITLE
Updating configuration doco to correspond to RabbitMQ changes

### ISSUE THREAD

**Issue by WojcikMike** [Particular/docs.particular.net#1356]
Connects to https://github.com/Particular/docs.particular.net/issues/1378

This is a high level issue to track changes that need to be done to documentation related to RabbitMQ changes that were made to support NSB v6.

Upgrade guide for RabbitMQ will be tracked in a separate issue.

cc: @bording

**Comment by weralabaj** [comment]
@WojcikMike wasn't that addressed already? Can we close?

**Comment by WojcikMike** [comment]
yes we can close it, sorry I forgot about it
