### ISSUE TITLE
Finish upgrade guide for RabbitMQ v3 to v4

### ISSUE THREAD

**Issue by WojcikMike** [Particular/docs.particular.net#1357]
Connects to https://github.com/Particular/docs.particular.net/issues/1378

This task is to track work related to creation of upgrade guide of Rabbit transport from v3 to v4.
http://docs.particular.net/nservicebus/upgrades/rabbitmq-3to4

cc: @bording

**Comment by SimonCropp** [comment]
@WojcikMike @bording i made a start http://docs.particular.net/nservicebus/upgrades/rabbitmq-3to4

**Comment by SimonCropp** [comment]
tracked by https://github.com/Particular/docs.particular.net/issues/1378
