### ISSUE TITLE
Update RabbitMQ guides for V6

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1378]
Includes upgrade guide and all other docs. Also extending the existing content, where necessary.

To get it ready, review the docs and identify what needs to be created/updated/removed and list it in Plan of Attack here.

PoA:
- [x] Create upgrade guide for RabbitMQ v3 to v4 
- [x] Update configuration page for RabbitMQ: http://docs.particular.net/nservicebus/rabbitmq/configuration-api
- [x] Review and determine if we need more samples (currently we have only 2)

Connects to https://github.com/Particular/PlatformDevelopment/issues/719

**Comment by weralabaj** [comment]
@WojcikMike @bording Could you form a proper TF and get it "ready" (define PoA) to work on this one? Seems like big enough to make sense to be tracked and to fall under WIP limit.

/cc: @andreasohlund

**Comment by andreasohlund** [comment]
:+1:

**Comment by WojcikMike** [comment]
@mat-mcloughlin , @bording  - I added you 2 to this TF as we planned to do this doco changes.

**Comment by weralabaj** [comment]
"Review and determine if we need more samples (currently we have only 2)" - do it as part of "getting ready" to avoid extending scope while working on the issue, as much as possible ;)

**Comment by WojcikMike** [comment]
> do it as part of "getting ready" 
Ok I will ping the TF so that we can determine this. ATM I reviewed other samples and what we could build is:
* Rabbit + Outbox
* Polymorphic Events (similar to http://docs.particular.net/samples/azure/polymorphic-events-asb/)

**Comment by andreasohlund** [comment]
Issue to get rabbit beta ready raised - https://github.com/Particular/PlatformDevelopment/issues/719

Removing the task force from this one since we'll track this from the new issue

**Comment by bording** [comment]
Per https://github.com/Particular/docs.particular.net/pull/1395#issuecomment-207137182, we should make sure we include transaction mode changes from v3 to v4 in the upgrade guide.

**Comment by johnsimons** [comment]
@weralabaj regarding
> Review and determine if we need more samples (currently we have only 2)

Has there been any demand for extra samples from our customers ? If not, I would leave it for now.

**Comment by johnsimons** [comment]
Update the upgrade guide to include transaction mode changes

**Comment by SimonCropp** [comment]
the only possible thing i can think of for more samples is typologies. are they complex enough to satisfy the sample criteria https://github.com/Particular/docs.particular.net#when-to-write-a-sample  ?

if not then i would close this as done

**Comment by johnsimons** [comment]
IMO the proposed changes in https://github.com/Particular/docs.particular.net/pull/1466/files#diff-dd047f28015c890ed724e37367146fa8, cover quite well the topologies of Rabbit, hence I don't see a reason to create samples for that.

**Comment by bording** [comment]
Since it sounds like the conclusion is that we don't need any more samples, I'm going to go ahead and consider this one done.
