### ISSUE TITLE
Update NServiceBus.Host Sample to show IWantToRunWhenEndpointStartsAndStops usage

### ISSUE THREAD

**Issue by boblangley** [Particular/docs.particular.net#1379]
http://docs.particular.net/samples/hosting/nservicebus-host/ enhance sample using IWantToRunWhenEndpointStartsAndStops

**Comment by SimonCropp** [comment]
Nor should it. Add that to the nsb host sample

**Comment by boblangley** [comment]
@SimonCropp That works too. Updated title/description.
