### ISSUE TITLE
Register instance of IWantToRunWhenEndpointStartsAndStops undocumented

### ISSUE THREAD

**Issue by colin-higgins** [Particular/docs.particular.net#1386]
The below methods and behaviors is as of now undocumented. This was discovered in the initiative to move IWantToRun from core to hosts.

In v5 there is a method on the EndpointConfiguration for registering an instance of `IWantToRunWhenBusStartsAndStops`. 
For only this instance to be picked up, the type needs to be excluded from assembly scanning, or else two instance will be registered.

In v6 there is an extension method on EndpointConfiguration for registering an instance of `IWantToRunWhenEndpointStartsAndStops`.
Any type registered through this method will be excluded from the instances that are grabbed from assembly scanning.

cc / @kbaley @boblangley

**Comment by SimonCropp** [comment]
Now documented

 * https://docs.particular.net/nservicebus/lifecycle/endpointstartandstop
 * https://docs.particular.net/nservicebus/upgrades/host-6to7
 * https://docs.particular.net/nservicebus/upgrades/5to6/endpoint#interface-changes
