### ISSUE TITLE
Authoring a custom ASB toloplogy

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1394]
ASB has two topologies out of the box:
-  `EndpointOrientedTopology`
- `ForwardingTopology`

Document how to author a custom topology (part of #1259).

**Comment by melkio** [comment]
We can include this paragraph to explain how to configure a custom topology for mapping between publisher names and event types:

`ITopology` interface exposes a property (`NeedsMappingConfigurationBetweenPublishersAndEventTypes`) to instruct transport environment if mapping must be configured. Custom topologies have to properly configure this property.   
Configuration is disabled for topologies that don't support mapping. If `RegiterPublisherForType` or `RegisterPublisherForAssembly` methods are called during configuration with a toplogy that doesn't support mapping, transport raises an `InvalidOperationException`.

**Comment by SeanFeldman** [comment]
@melkio This is an external information leaking out of the `EndpointOrientedTopology` topology. Please refer to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/179

**Comment by SeanFeldman** [comment]
@Particular/tf-azure-service-bus-doco 
@Particular/docs-maintainers 

Please review

**Comment by SeanFeldman** [comment]
Closing this one. `ITopology` is going to be internalized.
