### ISSUE TITLE
Abort the pipeline in mutators

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1405]
https://github.com/Particular/NServiceBus/issues/2914

Every now and then we have people trying to abort the message handling pipeline in muators. For me that is a smell. @DavidBoike seems to come to the [same conclusion.](http://stackoverflow.com/questions/30075526/discard-message-from-nservicebus-mutator). Should we clarify this in the docs?

@Particular/docs-maintainers any thoughts on this one?

**Comment by SimonCropp** [comment]
I think "dont abort in mutators" contradicts other adive we have given out. Eg http://docs.particular.net/samples/messagemutators/

**Comment by DavidBoike** [comment]
That mutator throws on a validation error. I see that as a lot less smelly. Throw anywhere and it's going to wind up doing retry or in an error queue.

DoNotContinueDispatchingCurrentMessageToHandlers or HandleCurrentMessageLater seem a lot more suspect in a mutator, because those just set things in the pipeline that have to be checked somewhere in order to have any effect, and the assumption is that they're going to be called within a handler, not from some random point in the pipeline.

**Comment by SimonCropp** [comment]
The problem with the mutator approach is we suffer retries unnecessarily. Wasting resources and cluttering the log.

**Comment by SimonCropp** [comment]
@danielmarbach so given i have supplied a use case do u still think it is a smell?

**Comment by mikeminutillo** [comment]
> The problem with the mutator approach is we suffer retries unnecessarily. Wasting resources and cluttering the log.

Should a behavior be able to mark a message as Faulted? i.e. Don't bother to retry, this is a non-transient issue.

**Comment by SimonCropp** [comment]
@danielmarbach can you express your proposed changes in a PR?

**Comment by SimonCropp** [comment]
@danielmarbach bump

**Comment by danielmarbach** [comment]
@SimonCropp you provided an example yes. It is our own sample application that so far doesn't convince me we need to abort the pipeline in a mutator. In fact, it even enforces my opinion. What are mutators here for? Like the name already implies they are meant to mutate either the logical or the physical message or validate a message. If you validate a message you'd normally throw some kind of validation exception. And yes this would lead to SLR and FLR. But I think it is much more helpful to then provide a custom retry policy which says

every time you see a validation exception don't bother retry and just move it

instead of coding it with `DoNotContinueDispatchingCurrentMessageToHandlers` inside each mutator.

**Comment by indualagarsamy** [comment]
@danielmarbach - If I understand you right, a validation exception more falls under the category for implementing a custom retry policy and not necessarily a mutator? If so, when would we abort the pipeline using Bus.DoNot...? 
Is the Bus.DoNot... loosing its relevance now that we have a super customizable pipeline?

**Comment by mikeminutillo** [comment]
Are we missing a core concept here of a faulted message here?

When you fall out of FLR/SLR the message has Faulted. When you fail deserialization, the message has Faulted. If you fail validation, the message has Faulted.

The default behavior is to forward Faulted messages to the configured error queue.

**Comment by danielmarbach** [comment]
@mikeminutillo not sure we are missing anything. Or maybe I just don't understand it enough

@indualagarsamy 

with the new custom recoverability policy it is simple to come up with something like this

```
public class ValidationException : Exception
{
   public ValidationException(string message) : base(message) { }
}

var recoverabilitySettings = endpointConfiguration.Recoverability();
recoverabilitySettings.CustomPolicy(MyCustomRetryPolicy);

RecoverabilityAction MyCustomRetryPolicy(RecoverabilityConfig config, ErrorContext context)
{
   if (context.Exception is ValidationException)
   {
      return RecoverabilityAction.MoveToError();
    }

    return DefaultRecoverabilityPolicy.Invoke(config, context);
}
```

This then completely bypasses FLR and SLR for ValidationExceptions.

We could just update the sample here.

http://docs.particular.net/samples/messagemutators/

**Comment by danielmarbach** [comment]
@indualagarsamy you brought up a good point:

Should we deprecate `DoNotContinueDispatchingCurrentMessageToHandlers` ? Any use cases that could not be done with custom recoverability policy?

**Comment by SeanFeldman** [comment]
@danielmarbach my 2c on the code snippet above. We're educating developers to rely on the context for the operations, yet in the [code above](https://github.com/Particular/docs.particular.net/issues/1405#issuecomment-233926843)
rather than using `context` to move a message to an error (queue) or invoke a default policy, we use `RecoverabilityAction` and `DefaultRecoverabilityPolicy` that are not very friendly to discover. Am I missing something here? Thanks.

**Comment by danielmarbach** [comment]
This is a totally different seam @seanfeldmann
Context operations can be actual physical operations. A recoverability
policy is a strategy which gets the data to make a decision and returns a
decision back to recoverability. The actual operations are not invokable.
Are proposing to inject something like an IRecoverabilityContext alongside
with the error context? The problem is that the user would still need to
return a decision. I fail to see if it would be clearer that way. The
current proposal also aligns with the mental model of previous SLR policies
where you returned TimeSpan for delayed retry or TimeSpan.Min for move to
error. But this time we are actuall explicit.

**Comment by SimonCropp** [comment]
@SeanFeldman @danielmarbach @DavidBoike  can u guys have a call and hash out if a PR should be submitted for this
