### ISSUE TITLE
Transport specific Scale-out pages

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#1421]
When trying to scale-out an MSMQ endpoint, the documentation was not a very big help. While all the configuration options are listed, the documentation is quite generic. Some parts were even confusing (e.g. the sample using the `Machine` attribute in the scale-out config although this is not listed in the schema).

I think having dedicated scale-out pages for each transport would be much more helpful for users and make the documentation much easier to understand.

@Particular/docs-maintainers I think this should have the v6 tag since I doubt that users will be able to configure scale-out (at least for msmq) without help.

**Comment by SimonCropp** [comment]
@SzymonPobiega thoughts?

**Comment by SzymonPobiega** [comment]
@SimonCropp we agreed with @timbussmann that the sections in the scale out page should be ideally expanded to a separate page. Not sure how big a priority it is. With the previous system I could just work on it whenever I don't have anything specific but with the new process we need a proper TF to form around this issue. 

I am not convinced I should lead it as this will further silo the routing knowledge.

**Comment by SimonCropp** [comment]
> I am not convinced I should lead it as this will further silo the routing knowledge

@SzymonPobiega i think you leading a documentation effort in this would be the opposite effect

**Comment by SzymonPobiega** [comment]
OK, then how do I mark it as a proposal for the V6 launch so it can be prioritized?

**Comment by WojcikMike** [comment]
Idea came into my mind, Let's pick someone who never done this scale-out for MSMQ and make him do this with our doco. He should write down notes or record whole process. Then we would know what is misleading and unclear.

But we can also do it at the end when we will fill the gaps that we know of.

**Comment by boblangley** [comment]
Is this what @ramonsmits just did in https://github.com/Particular/NServiceBus/issues/3678? As somebody who isn't very familiar with the new non-distributor/non-competing consumer scaling it looks like he went through the exercise @WojcikMike described.

The description could use some links to the doco pages in question as well. Are these the articles in question?

http://docs.particular.net/nservicebus/scalability-and-ha/scale-out
http://docs.particular.net/nservicebus/scalability-and-ha/individualizing-queues-when-scaling-out
http://docs.particular.net/nservicebus/messaging/routing
http://docs.particular.net/nservicebus/messaging/file-based-routing
http://docs.particular.net/nservicebus/messaging/message-owner

**Comment by boblangley** [comment]
For clarity, I am somebody who is not very familiar with the new scaling / routing capabilities.

**Comment by indualagarsamy** [comment]
@weralabaj @SzymonPobiega - can this issue be closed? Have all the concerns from @timbussmann addressed?

**Comment by weralabaj** [comment]
I think so, if not @timbussmann please reopen with details of what's left.
