### ISSUE TITLE
Azure Servicebus =>  Azure Service Bus

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1428]
it is "Azure Service Bus" not "Azure Servicebus", "Cloud Services" not "cloudservices"

 * [x] fix the urls http://docs.particular.net/nservicebus/azure-servicebus/, http://docs.particular.net/nservicebus/hosting/cloudservices-host/
 * [x] ensure the redirects are in place
 * [x] fix any links pointing to those pages
 * [x] Search and replace for "Azure ServiceBus" and "cloudservices"

**Comment by SimonCropp** [comment]
@Particular/tf-azure-service-bus-doco how do u want to play this? i am happy to do it but it might cause merge merge conflict for any branches.

**Comment by weralabaj** [comment]
@SimonCropp I'll sync with others and do it.

**Comment by weralabaj** [comment]
Resolved in https://github.com/Particular/docs.particular.net/pull/1429
