### ISSUE TITLE
ASQ perf tuning

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1434]
After testing it seems that ServicePointManager settings can highly influence performance if the value is set to high. So for regular usage, connection reuse is more important than having the ability to open a lot of connections.

Change the guidance to use corecount \* 6 (or 12), not the 5000 we recommend now. If the process is running .net 4.5, the default will work well (as it changed from 2 to a more sensible number based on hardware)

**Comment by timbussmann** [comment]
> If the process is running .net 4.5, the default will work well (as it changed from 2 to a more sensible number based on hardware)

sorry, I think I gave some wrong information about this yesterday. Doesn't seem to choose reasonable defaults in .net 4.5. (it seems like it does for asp apps http://stackoverflow.com/questions/5488235/system-net-servicepointmanager-defaultconnectionlimit-24-bug/5649013#5649013 but other than that it still uses 2).

**Comment by SeanFeldman** [comment]
This has been addressed (the new algorithm implemented by ASQ).
[Doco updated](https://docs.particular.net/nservicebus/azure-storage-queues/performance-tuning#parallel-message-retrieval) as well.
