### ISSUE TITLE
Rewrite Gateway index file

### ISSUE THREAD

**Issue by boblangley** [Particular/docs.particular.net#1442]
http://docs.particular.net/nservicebus/gateway/

The wording of this article should be updated to remove the conversational wording. It reads like a blog and contains "story" elements to justify the usage of the gateway. While doing so it also assumes the user understands many DDD/SOA terms.

The article should be rewritten to meet our newer standards for technical writing.

**Comment by weralabaj** [comment]
@boblangley do you mean that the content is no longer accurate or is that about style?

**Comment by boblangley** [comment]
@weralabaj I updated the description, does this help? 

/cc: @SimonCropp

**Comment by weralabaj** [comment]
Yes, a lot, thank you!
