### ISSUE TITLE
ASB DLQ forwarding

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1446]
Explain the why and how of DLQ forwarding should (or NOT) be used.

Ensure to make it clear that forwarding **does not** contain information about the failed queue
(feature request for ASB) or SC specific headers.

**Comment by yvesgoeleven** [comment]
Do note the downsides (f.e. the origin of the msg is lost & no SC specific headers my be present)

**Comment by SeanFeldman** [comment]
[Centralized DLQ ](http://bit.ly/deadlettersource) is an option, but not for SC.
