### ISSUE TITLE
ASB long running operations

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1447]
- [ ] Explain how to do long running operations properly
  - [ ] Related sample: https://github.com/Particular/docs.particular.net/issues/1533
- [ ] Explain relationship between lock duration, autorenewtimeout and long running operations.

**Comment by SeanFeldman** [comment]
Should this one be closed?

**Comment by weralabaj** [comment]
@yvesgoeleven @SeanFeldman should we close? there's a similar issue https://github.com/Particular/docs.particular.net/issues/1533, I'm not sure how both are (or aren't) related

**Comment by SeanFeldman** [comment]
👍
