### ISSUE TITLE
Azure host configuration system

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1448]
The hosting document mentions this:

Configuration system: This system allows you to update configuration settings from the Azure management portal, or through the service management API, and the platform will promote these configuration settings to all instances in the roles without downtime.

But this isn't entirely correct. 
- First off, in needs to mention that you need more than 1 instance in order to offer 'no downtime' as the individual instance needs a restart.
- Secondly, azure cloudservices no longer automatically restarts the instances on config changes, one needs to opt into that: https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.serviceruntime.roleenvironment.changing.aspx

**Comment by SimonCropp** [comment]
@Particular/azure-host-maintainers  still needs to be done?

**Comment by SeanFeldman** [comment]
@SimonCropp it's there: https://docs.particular.net/nservicebus/hosting/cloud-services-host/configuration#convention-to-override-configuration-applying-configuration-changes
