### ISSUE TITLE
ASB addressing logic

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1453]
Describe how the new addressing logic in ASB transport works and how it replaces NamingConventions in v6

- [x] Article which includes description of how the new logic works + the how it works in v6 http://docs.particular.net/nservicebus/azure-service-bus/native-integration#naming-conventions
- [x] Upgrade guide section
- [x] Samples of custom implementations of addressing strategies (can be a copy or variation of implementations currently in the transport)

**Comment by melkio** [comment]
this (https://github.com/Particular/NServiceBus.AzureServiceBus/tree/2a6a7cd33cc81d5c6f80f7344b6e5c97392acdc7) is the commit before removing `ReplicatedNamespacePartitioning` and `ShardedNamespacePartitioning` from transport codebase
