### ISSUE TITLE
Create sample for Gateway custom channels

### ISSUE THREAD

**Issue by boblangley** [Particular/docs.particular.net#1458]
We need a sample on how to create custom channels in the Gateway.

From @weralabaj in https://github.com/Particular/docs.particular.net/issues/1683:

The current content is not sufficient to help somebody implement it, so as part of this article cleanup #1682 I'm moving it here for future reference and removing from the overview page. Ideally one day we'll have a more extensive "How to implement your own gateway channel" article. As it is now, it won't help much anyway.

Custom Channel Types

The Gateway includes an HTTP/HTTPS channel implementation, but it is possible to create additional channel types by implementing the IChannelSender and IChannelReceiver interfaces.

NServiceBus will pass message data (headers and payload) to the configured IChannelSender which is responsible for transmitting this information over the desired channel to a receiving Gateway.

IChannelReceiver must accept transmissions from the incoming channel and provide the incoming data to NServiceBus through a DataReceivedOnChannelArgs instance that is passed to a provided Func<DataReceivedOnChannelArgs, Task>.

IChannelSender and IChannelReceiver implementations are not automatically registered through assembly scanning. The custom channel types must be registered using a channel factory Func through the ChannelFactories setting:

snippet: GatewayChannelFactoriesConfiguration
```
void GatewayChannelFactoriesConfiguration(EndpointConfiguration endpointConfiguration)
{
    #region GatewayChannelFactoriesConfiguration


var gateway = endpointConfiguration.Gateway();
gateway.ChannelFactories(
    senderFactory: channelType => new CustomChannelSender(),
    receiverFactory: channelType => new CustomChannelReceiver());

#endregion
}
```

**Comment by weralabaj** [comment]
@boblangley @janovesk is that something that we might want to do at some point, or should we burn it?

**Comment by janovesk** [comment]
As long as we have the feature, a sample would be helpful. Not seeing high priority here, though.. Backlog?

**Comment by weralabaj** [comment]
Given that now is quite slow period, I wonder if we don't do it now, will we honestly ever do? :)

**Comment by SimonCropp** [comment]
@weralabaj looks like the answer is "no"
