### ISSUE TITLE
ASB doco should focus on features first and APIs second

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1460]
So this http://docs.particular.net/nservicebus/azure-service-bus/configuration/configuration is a top level list of all the config APIs. This it a good as a first start. however i think moving forward we want to invert this documentation structure.

So split this document and document the features rather than the API. then at the bottom of each feature page list the apis to manipulate that feature. so for example the typologies page  http://docs.particular.net/nservicebus/azure-service-bus/topologies/ and the new batching page https://github.com/Particular/docs.particular.net/pull/1452

**Comment by SimonCropp** [comment]
@SeanFeldman ping

**Comment by SeanFeldman** [comment]
@yvesgoeleven we can review this together

**Comment by SimonCropp** [comment]
just to be clear this does not need to be done in the short term

**Comment by SeanFeldman** [comment]
Absolutely @SimonCropp. We should be done by the next sun eclipse :)

**Comment by yvesgoeleven** [comment]
@SimonCropp the plan is indeed to have more 'scenario/customer oriented' pages which refer to this document instead of the other way around, but most of those articles have been move to the RC timeframe because we needed to get something out

**Comment by SimonCropp** [comment]
@SeanFeldman @yvesgoeleven is there any reason to keep this open?

**Comment by SeanFeldman** [comment]
👍 @SimonCropp
