### ISSUE TITLE
RuntimeEnvironment.MachineNameAction

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1461]
raised in relation to this https://github.com/Particular/NServiceBus/pull/3710

so our current doco for `RuntimeEnvironment.MachineNameAction` is this
http://docs.particular.net/nservicebus/msmq/full-qualified-domain-name 
which seems to imply it is a MSMQ only setting. this is not true. 

so we need to flesh out what else it is used for. also need guidance on if it should be cached or not.

**Comment by weralabaj** [comment]
The related PR has been merged, that can be addressed now?

**Comment by SimonCropp** [comment]
@weralabaj that PR was never blocking this. we need to do a full code search over all repos and document the various usages of it

**Comment by SimonCropp** [comment]
replaced by https://github.com/Particular/NServiceBus/issues/4553
