### ISSUE TITLE
where should upgrade guides be located on the filesystem

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1467]
currently we have 

 * https://github.com/Particular/docs.particular.net/tree/master/nservicebus/upgrades 
 * https://github.com/Particular/docs.particular.net/tree/master/nservicebus/ravendb/upgrades

Should we move the raven ones to `nservicebus/upgrades`? or split the rest out?

**Comment by SimonCropp** [comment]
ping @Particular/docs-maintainers @Particular/ravendb-persistence-maintainers

**Comment by DavidBoike** [comment]
I think it makes sense to move the Raven ones into the main directory. This will also force the filename to be raven-3to4.md so I won't get confused about what 3to4.md I'm looking at when I see a filename.
