### ISSUE TITLE
Exposing endpoints as WCF Service when using NServiceBus Host Version 7

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#1472]
According to the [existing documentation](http://docs.particular.net/nservicebus/hosting/expose-an-endpoint-as-a-web-wcf-service), it looks like no code changes are required, however that's not the case. 

Relates to https://github.com/Particular/V6Launch/issues/35

**Comment by SimonCropp** [comment]
dont u mean "Exposing endpoints as WCF Service when using NServiceBus Host Version 7" ?

**Comment by DavidBoike** [comment]
What didn't work?

Not that this has ever been the most straightforward process in the first place.

**Comment by indualagarsamy** [comment]
@DavidBoike - If you're interested, take the old wcf usage in V5. Try it in V6. See what happens.

**Comment by SimonCropp** [comment]
@DavidBoike @indualagarsamy is this still happening?

**Comment by DavidBoike** [comment]
OK, after a **lot** of digging, I discovered that apparently we [outright removed the WCF code from the NSB Host](https://github.com/Particular/NServiceBus.Host/commit/d62af6e6425eb551ad35faa1beac59c3fb217752) without an obsolete or anything

**Comment by indualagarsamy** [comment]
@danielmarbach - I am closing this issue doco relating to WCF integration got merged.
