### ISSUE TITLE
The move from Bus.Dispose to Endpoint.Stop

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#1473]
When upgrading endpoints, people that were self hosting had the IBus create section in an using block.
When converting over to V6, what we have in the upgrade guide doesn't seem sufficient. 

Current doco:
http://docs.particular.net/nservicebus/upgrades/5to6#endpoint-start-and-stop-interface-changes-self-hosting

What might make it more clear is to show the IBus in an using statement to the new Endpoint.Stop in the upgrade guide. 

Relates to: https://github.com/Particular/V6Launch/issues/35

**Comment by mikeminutillo** [comment]
Do people often create/destroy the endpoint within a using? Usually whatever hosting infrastructure you are building on (Windows Services, ASP.NET, etc.) have separate methods for start and stop. You'd only use `using` if you were running in a console host. 

If we want to make it clearer that the reader should always shut down the endpoint cleanly, we might be better off showing both cases in a `try-finally`. We could even mention the change from `IDisposable` and recommend switching from `using` to `try-finally` first.

**Comment by HEskandari** [comment]
I always thought `Using` is converted to `try/finally` by the compiler, so it is all syntactical sugar, was I wrong?

**Comment by mikeminutillo** [comment]
We can do `try/finally` in both v5 and v6.
We can only do `using` in v5.

This is because the `IEndpointInstance` does not implement `IDisposable` and *that* is because `Stop()` needs to return `Task` so it doesn't match the `IDisposable.Dispose()` signature.

That's why I'd rather show parallel samples in `try/finally` because they mirror each other and make it easier to see what's changed.

**Comment by HEskandari** [comment]
Makes sense and think that'd be very useful to have in the upgrade guides. I'll update the PR tomorrow.

**Comment by SimonCropp** [comment]
fixed here https://github.com/Particular/docs.particular.net/commit/ad9b9716f94317c5fd8b10b81aa56c9a0682f9c8
