### ISSUE TITLE
Throttling guidelines and documentation section is not clear

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#1479]
A few things to note:

- The [documentation page](http://docs.particular.net/nservicebus/operations/tuning) says that throttling options are removed in v6. There's no mentioning on what's the new default. There's no link to a page with more details (e.g. Upgrade docs)

- The [upgrade doc](http://docs.particular.net/nservicebus/upgrades/5to6#throttling) says there *is* a section about custom throttling mechanism on the above documentation page but I can't find it.

- The whole section mixes concurrency with throuput trottling making it hard to understand what's removed and what's there. Updating the warning note to make it clear what parts are remove and what's still valid for v6 helps.

**Comment by SimonCropp** [comment]
ping @andreasohlund

**Comment by andreasohlund** [comment]
I have not forgotten this, will try to get to it tomorrow

**Comment by weralabaj** [comment]
ping @andreasohlund

**Comment by andreasohlund** [comment]
Wonder if we should split the tuning page into 2 new pages? (one about throttling and one about controlling concurrency)

**Comment by weralabaj** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Not sure what we are supposed to do here @weralabaj 

The person who raised it is not driving it and the person who said to drive it is away.

**Comment by weralabaj** [comment]
So should I wait for andreas to get back from holiday? Is there anybody else that could help with that?

Not sure how we'd like to handle it (creating new pages, as Andreas suggested or not), but Hadi's comments seem to be pretty clear with regards what's unclear in the docs.

**Comment by HEskandari** [comment]
I didn't want to raise and issue and start working on it without gathering feedback first. Once I know what you think and we agree on it, I can drive it.

**Comment by HEskandari** [comment]
@Particular/nservicebus-maintainers  Would you guys please review this? does it make sense? Anything missing here that should be added?

**Comment by danielmarbach** [comment]
@HEskandari sounds good for me. Although I get the best understanding if you invite me on a WIP PR.

**Comment by HEskandari** [comment]
@danielmarbach certainly :) just wanted to make sure people are happy with the direction before investing the time on it.
