### ISSUE TITLE
Azure: move partition strategies (Replica and Sharding) to samples

### ISSUE THREAD

**Issue by melkio** [Particular/docs.particular.net#1507]
Connects to https://github.com/Particular/docs.particular.net/issues/368

**Comment by melkio** [comment]
`ReplicatedNamespacePartitioning` and `ShardedNamespacePartitioning` have been removed from trasport because they need a sort of "incubation" period to understand how to improve them.

The idea was to use these strategies to show how to implement a custom strategy and how to provide it to transport, moving them to samples.

**Comment by yvesgoeleven** [comment]
ReplicatedNamespacePartitioning  is used as example, Sharded is omitted
