### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#1513]
While handling https://github.com/Particular/NServiceBus.RavenDB/pull/232 the @Particular/ravendb-persistence-maintainers found themselves in the situation where a link to doco in a log message would have been very helpful for the end user.

Obviously we perfectly agree that URL maintenance can quickly become a nightmare and should be carefully planned.

We raised the idea of introducing a `URL Shortener` to act as an anti corruption layer (this can be extended to the entire org not doco only).

Bit.ly provides support for [custom domains](http://support.bitly.com/knowledgebase/articles/76741-how-do-i-set-up-a-custom-short-domain-) meaning that all what we need is to register a domain name of our choice.

Thoughts?
(if this is the wrong place, please suggest a more appropriate one)

**Comment by SimonCropp** [comment]
>  (this can be extended to the entire org not doco only

In that case re raise it in platform dev
