### ISSUE TITLE
Document how external integration can be done reliably

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#152]
See the discussion for details

https://groups.google.com/forum/#!msg/particularsoftware/gOZA-T3982w/Ed5RIHqAqv4J

**Comment by mauroservienti** [comment]
There are a lot of discussions during these days with @danielmarbach, @sfarmar and @jdrat2000 regarding the integration story.
It is something that we need to address. We can start from here https://skillsmatter.com/skillscasts/2295-reliable-integrations-nservicebus and build content around that.

**Comment by mauroservienti** [comment]
@danielmarbach isn't this related to #226 ? should we merge?

**Comment by danielmarbach** [comment]
@mauroservienti yes go ahead and merge

**Comment by mauroservienti** [comment]
merged w/ #226, closing.
