### ISSUE TITLE
Explain API decision to not use async suffix

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#1523]
This could confuse existing and new users alike.

Content is [here in Google Groups](https://groups.google.com/forum/#!searchin/particularsoftware/async%2420suffix/particularsoftware/xrSJpgjowJQ/RWAlIxpfBgAJ) but needs to be spelled out in docs.

As @timbussmann pointed out in https://github.com/Particular/NServiceBus/issues/3726#issuecomment-217371415, because new users could be confused by this as well, upgrade guide is not the best place.

Related to Particular/NServiceBus#3726 and Particular/V6Launch#36

Some info

 * https://blogs.rocksolidknowledge.com/2015/12/02/lets-stop-the-async-suffix-bullshit/
 
Other libs that dont async suffix

 * MassTransit https://github.com/MassTransit/MassTransit/issues/314
 * Octokit

**Comment by indualagarsamy** [comment]
Discussed this issue with @SimonCropp. Assigning to @SimonCropp.
