### ISSUE TITLE
Customizing pipelines doco

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1527]
Currently there are 2 docs

1. http://docs.particular.net/nservicebus/pipeline/customizing-v5
1. http://docs.particular.net/nservicebus/pipeline/customizing-v6

and both are not under the menu. If opened through search, the related articles are not showing up because menu will be collapsed.  Should those two be sub-articles under [customizing the pipeline](http://docs.particular.net/nservicebus/pipeline/customizing)?

**Comment by SeanFeldman** [comment]
PS: customer wrote

>I’m having a hard time finding examples of pipeline behaviors.

**Comment by SimonCropp** [comment]
http://docs.particular.net/samples/pipeline/

**Comment by SeanFeldman** [comment]
Steps to repro:

1. http://docs.particular.net/search?q=pipeline
2. select "Customizing the Pipeline in NServiceBus Version 5"

context/related items are not available since menu is not linked
