### ISSUE TITLE
Long running operation sample

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1533]
Create a sample that demonstrates how to tackle a long running operation, where execution exceeds the time a normal handler would allow or violate the maximum transport message lock duration (asb/asq).

**Comment by indualagarsamy** [comment]
@yvesgoeleven @SeanFeldman - is this a duplicate of #1447? If so, can we close this issue?

**Comment by SeanFeldman** [comment]
@indualagarsamy no, it's not the same. #1447 is about extending executing time __within__ a handler leveraging new features of ASB transport. This issue is about executing __very__ long operations (hours f.e.) outside of a handler to overcome NSB limitation in this area.

**Comment by weralabaj** [comment]
@SeanFeldman given that was raised over 6 months ago, is this something we really want to do?

**Comment by SeanFeldman** [comment]
Has been completed already. Closing this issue.
