### ISSUE TITLE
Should we include a link to Target Framework Migrator in the V6 Upgrade Guide?

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#1536]
The [upgrade guide](http://docs.particular.net/nservicebus/upgrades/5to6) notes that users need to update everything to .NET 4.5.2 before getting started with a V6 upgrade. [When running through this with a customer](https://github.com/Particular/V6Launch/issues/37) I noted that the had 10s of projects that needed to be updated and in Visual Studio you need to update them one at a time.

[Target Framework Migrator](https://visualstudiogallery.msdn.microsoft.com/47bded90-80d8-42af-bc35-4736fdd8cd13) is a VS plugin designed to do this in bulk for a single solution.

Should we test this and include a link to in the upgrade guide?

**Comment by SimonCropp** [comment]
seams reasonable to me
