### ISSUE TITLE
Explain async for bus operations in upgrade guide

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#1537]
We do not explicitly say anything in the upgrade guide about the fact that Send and Publish are now async. Do we need to touch on this? 

Do we need to to describe what happens if you fail to await the response from these operations (I don't actually know but a [customer asked](https://github.com/Particular/V6Launch/issues/37))

**Comment by indualagarsamy** [comment]
@mikeminutillo - This also goes to the async naming. By naming async, it becomes very clear that these operations need to be awaited.

**Comment by indualagarsamy** [comment]
@mikeminutillo - @SimonCropp is going to be working on doco that outlines why we chose not to use `async` postfix. Maybe we can add a section in the upgrade guide and link it to the new doco once @SimonCropp is done.

**Comment by indualagarsamy** [comment]
Fixed by PR #1700
