### ISSUE TITLE
Routing section to discuss topics related to routing

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1539]
Routing doco is becoming a bit scattered. Routing in the core, message mappings in the config and topology configuration in the transport (ASB), pubsub registration message, subscription storage, scale out.

- http://docs.particular.net/nservicebus/messaging/message-owner
- http://docs.particular.net/nservicebus/scalability-and-ha/scale-out
- http://docs.particular.net/nservicebus/messaging/file-based-routing
- http://docs.particular.net/nservicebus/messaging/routing

Having a single section in the doco menu at the right would make it more obvious.

Also, you first have to read the documents to understand to what version the document applies. A V5 user should be able to see immediately that the doco does not apply.

**Comment by weralabaj** [comment]
> A V5 user should be able to see immediately that the doco does not apply.

That might be hard to do in the current state. We esentially have separate pages for v6 and everything else.  I guess it'd make sense to re-org the existing content at the same time to have a more consistent structure.

> Routing in the core, message mappings in the config and topology configuration in the transport (ASB), pubsub registration message, subscription storage, scale out.

From the user perspective why would they need to understand all aspects of routing at once? IMO it makes more sense to have separate page for scale out, core and ASB. Most likely you won't be looking into what routing is, but how to achieve a specific goal and that seems to make sense right now.

**Comment by weralabaj** [comment]
Since the discussion has died, I'm closing this one. @ramonsmits feel free to re-open if you think this is still relevant and you want to add some clarifications.
