### ISSUE TITLE
Any changes for Unobtrusive conventions when using the NServiceBus.Testing for Core V6?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#1540]
The following article talks about Versions 5 and below, but does not document what's needed for v6.
http://docs.particular.net/nservicebus/testing/#configuring-unobtrusive-message-conventions

Reported by Customer:
Relates to https://github.com/Particular/V6Launch/issues/27

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - ping.

**Comment by timbussmann** [comment]
the v6 testing framework does not need to know about unobtrusive message conventions.
added a note here: https://github.com/Particular/docs.particular.net/pull/1541

**Comment by timbussmann** [comment]
upgrade guide PR: https://github.com/Particular/docs.particular.net/pull/1546

**Comment by indualagarsamy** [comment]
Fixed as part of @timbussmann's PR. Closing this issue.
