### ISSUE TITLE
Improve message mapping / routing doco

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1543]
The documentation regarding message mappings and routing should be updated based on this discussion:

https://github.com/Particular/NServiceBus/issues/3678#issuecomment-220004165

@andreasohlund @tmasternak We cannot really remove the file based routing as it is documented as being the replacement for MessageEndpointMappings. New V6 users would be advised to use the file based mapping for physical information.

That is my interpretation after reading:
> NServiceBus had the concept of an "Owning Endpoint" for any given message type. In Version 6 this has been superseded by the more flexible routing model. The previous configuration in the form of MessageEndpointMappings configuration section is still fully respected by the Version 6 endpoints in order to provide a smoother transition experience.

and

> In previous versions NServiceBus used fixed message ownership mappings that allowed only to map the message type (or all types in an assembly or a namespace) to physical addresses (queue names). The flexible routing in Version 6 splits this mapping up into a series of individually configurable steps. NServiceBus 6 still understands the old configuration in form of message-endpoint mappings for backwards compatibility.

---

@ramonsmits we had that discussion initially in the routing TF and we decided that code-based logical routing is the way to go. The logical name of the endpoint that processes the message is the developer's concern, not the infra concern (at least that was the outcome of that discussion). 

That said, If you feel strongly that that outcome was wrong, please raise a new PlatDev issue and we can discuss it in that issue. I also think that a zoom call might be a good option. If we arrive at a different conclusion now this might be a show stopper for V6.

**Comment by SimonCropp** [comment]
@ramonsmits @SzymonPobiega @andreasohlund @tmasternak 

can one of you put a PR together to illustrate what needs to change.

**Comment by SimonCropp** [comment]
Please re raise when there is enough input to proceed
