### ISSUE TITLE
RequestTimeout 5 to 6 Notes

### ISSUE THREAD

**Issue by tekmaven** [Particular/docs.particular.net#1544]
There is no guidance in the 5 to 6 migration doc (http://docs.particular.net/nservicebus/upgrades/5to6) about Saga.RequestTimeout changes.

The signature has changed from: `RequestTimeout<T>(TimeSpan)` to `RequestTimeout<T>(IMessageHandlerContext, TimeSpan)`.

**Comment by weralabaj** [comment]
Thank you @tekmaven for catching it! We'll fix it soon.

**Comment by weralabaj** [comment]
Fixed, once again thank you!
