### ISSUE TITLE
Improve performance of docs website with more caching, reducing latency

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1553]
The docs website felt a bit sluggish from Brazil compared to from the Netherlands. We could improve the browsing experience for customers in geo regions that are not close to our docs website.

I tested latency using a VPN (private internet access) and connected to Brazil. Using the VPN is not really fair as now it also adds the latency from the Netherlands to Brazil so that probably needs to be divided by two.

http://docs.particular.net/nservicebus/testing/

using VPN exit in Brazil: 842ms
from NL: 44ms

Most things on our docs website can be cached. We could even cache a lot of pages for a minium of an hour or even hours. I see a lot of content is marked as private with the primary issue that all docs pages seem to be marked private.

This means that if we would be using a edge networking service like cloudflare that such pages cannot be cached.

**Comment by SeanFeldman** [comment]
@ramonsmits. Could you please elaborate on the reason closing the issue right after opening or link to a replacement issue if one exists? Helps to get the context and understand the decisions made. Thank you.

**Comment by ramonsmits** [comment]
@SeanFeldman You are right, I created this issue in the wrong repo. That is why I closed it.

**Comment by SeanFeldman** [comment]
@ramonsmits you could supply something like "closed in favour of [other-repo#issue-number](dont-break-the-flow)".

**Comment by SimonCropp** [comment]
It got moved here https://github.com/Particular/DocsEngine/issues/211
