### ISSUE TITLE
Sidebar navigation not showing all SI pages

### ISSUE THREAD

**Issue by sergioc** [Particular/docs.particular.net#1566]
![screenshot 2016-05-31 09 40 24](https://cloud.githubusercontent.com/assets/493451/15666957/da9f23cc-2713-11e6-8777-46707c69ea0d.png)

There's more articles dedicated to SI besides Getting Started, e.g. http://docs.particular.net/serviceinsight/sequence-diagram/

**Comment by sergioc** [comment]
Also worth checking the same for SP and SC.

**Comment by weralabaj** [comment]
@sergioc this is a section name, if you click "Getting started" other articles will be displayed.

I agree though it's not intuitive and might be worth rethinking the menu structure.

**Comment by sergioc** [comment]
@weralabaj still does not show all pages :-)

![screenshot 2016-05-31 09 55 15](https://cloud.githubusercontent.com/assets/493451/15667291/d38c143a-2715-11e6-8fec-f08b9fa8dca5.png)

**Comment by weralabaj** [comment]
hm needs like something we could do under maintainers budget

**Comment by SimonCropp** [comment]
fixed
