### ISSUE TITLE
Clicking on sidebar navigation section should only expand the section

### ISSUE THREAD

**Issue by sergioc** [Particular/docs.particular.net#1568]
The current sidebar navigation uses sections inconsistently. E.g. under NSB, clicking the text "Handlers" opens a new page and expands the section in the sidebar navigation to reveal sub-topics. Clicking around "Handlers" just opens the sections. This is really annoying when exploring the navigation by expanding and collapsing sections.

Both ways (clicking on text or area around) should only expand the section for consistency and to prevent the scroll from jumping around or the page from flashing when loading. The section page should just be the first sub-link.

Or am I missing a reason to open the section page directly?

**Comment by SimonCropp** [comment]
the text is a link. and hence is expected to navigate.

>Both ways (clicking on text or area around) should only expand the section

if that was the case how would u navigate to those links?

**Comment by sergioc** [comment]
> the text is a link. and hence is expected to navigate.

That's not always true. And if you want to ensure it's not meant to navigate, add a disclosing arrow before the text.

> if that was the case how would u navigate to those links?

Make those links the first to show in the expanded list from their respective groups

**Comment by SimonCropp** [comment]
> Make those links the first to show in the expanded list from their respective groups

we dont want to loose the vertical real estate by doing this

**Comment by sergioc** [comment]
> we dont want to loose the vertical real estate by doing this

That sounds obsessive to me. Just to be sure you understood, I'm talking about adding a link to the list that shows when a section is expanded, the same way a link would appear when a new documentation article is added under that section.

**Comment by sergioc** [comment]
One more thing. If you check the sections under ServicePulse, you'll be able to see the correct behavior for sub-sections.  Clicking on "Introduction" or "Configuration" only discloses the list of associated articles, it doesn't open a page. 

If you click on SP, however, it opens a page AND expands the SP list of sections. This is not correct. It should ONLY expand the list.

**Comment by SimonCropp** [comment]
ok i thought we could address this quickly here. but seems not. can you please re-raise in the docsengine repo and include an image/diagram of what u r proposing
