### ISSUE TITLE
on-premise Core_6 sample produces signalR websocket error

### ISSUE THREAD

**Issue by ruffzy** [Particular/docs.particular.net#1569]
Unfortunately I can't Place an order in the on-premise sample. When I start the webpage I see an error in the browser console (developer tools):

WebSocket connection to 'ws://localhost:20233/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=LGkMp2qMLDE9Kd9%2Ftwxe6LuFXb31ocAnnsCgbPU9ERmDfBzAlSpvOUbDOH8RRf4g0nxHFC%2FHLbVmajsAKrZUFrd8mQCCWCzA%2BitM%2FVE64AkbPaWPF%2BaFMLVWS%2FnRp2vZ&connectionData=%5B%7B%22name%22%3A%22ordershub%22%7D%5D&tid=1' failed: Error during WebSocket handshake: Unexpected response code: 500

The same error appears with IE (Edge 25) and Chrome 50. Also a friend tested the sample on his machine and had the same error with firefox.

**Comment by SimonCropp** [comment]
@ruffzy i was able to reproduce the WebSocket  and put a fix in for it. Can you re-download and confirm it is fixed for you

**Comment by ruffzy** [comment]
Thank you @SimonCropp for fixing this. I can confirm that it is now working fine again.

**Comment by SimonCropp** [comment]
awesome. thanks for logging the issue and getting back to me
