### ISSUE TITLE
Azure Host - how to run Cloud Service based endpoint without cloud service emulator

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1583]
Documentation doesn't contain anything about running CS-hosted endpoint locally w/o CS emulator (by using Azure Host Process). 

With `IConfigureThisEndpoint` moved into hosts (both Azure Host & NSB Host), users that used NSB Host to run endpoints w/o CS emulator will run into a [problem](https://github.com/Particular/NServiceBus/issues/3808). Documentation will help to resolve this by pointing out what to do.

**Comment by weralabaj** [comment]
That still doesn't seem to address the concern expressed in the original issue:
https://github.com/Particular/NServiceBus/issues/3808#issue-158758940

>  do appreciate the reasoning behind the changes here, but this creates a 3x increase in assemblies to accomplish what we were doing in NSB v5. I think the best solution would be to differentiate the namespaces that IConfigureThisEndpoint are using.

or am I missing something?

**Comment by SeanFeldman** [comment]
It should. Azure host process implements the Sam contract used by azure host for SC, so it allows to run in a dev environment w/o the emulator (just like @yvesgoeleven commented here https://github.com/Particular/NServiceBus/issues/3808#issuecomment-224071210).
This issue is to make sure we document the option.

**Comment by weralabaj** [comment]
@Particular/azure-maintainers can you take care of it?

**Comment by daerath** [comment]
We're in the process of upgrading and we just ran smack into this issue.  I don't see documentation detailing how to accomplish this type of split-hosted configuration that allows for non-cloud hosted (including not using the emulator) when running locally (e.g. F5 debugging) and Azure hosting when deployed as an Azure Cloud Service.

If the documentation exists can you provide the link that details how to accomplish this?

Thank you!

**Comment by adammodlin** [comment]
Agreed with @daerath , it would be great if you had any prototype or initial documentation even if it's not website ready. We've spent a considerable effort upgrading from 5 to 6 and ran into this unexpected issue right near the end of our upgrade.

**Comment by yvesgoeleven** [comment]
Thank you for confirming our initial concerns @daerath and @adammodlin sadly enough we do not have any document at this point. We'll take this into consideration for prioritizing our work.

**Comment by SeanFeldman** [comment]
@daerath @adammodlin sorry for such a delay. I'm working on the doco to ensure this is captured and documented. Meanwhile, get you going, these are the things that you can do:

1. Use [NServiceBus.Hosting.Azure.HostProcess](https://www.nuget.org/packages/NServiceBus.Hosting.Azure.HostProcess) rather than NServiceBus.Host
1. For local debugging (F5) add an external program from the package in #1. The exe file is named `NServiceBus.Hosting.Azure.HostProcess.exe` and does what a `NServiceBus.Host.exe` did in NSB v5.
1. Add `NServiceBus.Hosting.Azure.HostProcess.exe.config` with the binding redirects from your app.config to [workaround a bug](https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/74) that will be addressed in the next release of the host process.

This will allow you to run your endpoint w/o CS emulator locally as you used to be able in the past.

**Comment by adammodlin** [comment]
Thanks @SeanFeldman . Any reason why you suggest running without CS emulator?

**Comment by SeanFeldman** [comment]
@adammodlin if you need to debug your endpoint(s) locally and you need a fast startup time rather than waiting for CS emulator to spin up, this approach helps. The sole issue was raised to address it.

**Comment by adammodlin** [comment]
@SeanFeldman Ah I see, so running the CS emulator locally will not allow us to debug? We will give this a shot.

**Comment by SeanFeldman** [comment]
@adammodlin CS emulator is always a local operation. It will allow you to debug, but it takes time to spin up (ie deploy your CS endpoint, run through CS code and start it). When you need a lightweight way to spin up your CS-based service, NServiceBus.Hosting.Azure.HostProcess.exe can do it. Same approach was used with NSB v5, just then `IConfigureThisEndpoint` was a part of a shared NSB core library, so using `NServiceBus.Host.exe` for quick debugging sessions was possible where with the Azure CS host v7 it is not.

**Comment by SeanFeldman** [comment]
**Update** 
- Documentation has been updated ([link](https://docs.particular.net/nservicebus/hosting/cloud-services-host/running-without-emulator))
- [Azure host 7.0.2](https://groups.google.com/forum/#!topic/particularsoftware/oTvwJegc1eM) has been released to remove the workaround mentioned [here](https://github.com/Particular/docs.particular.net/issues/1583#issuecomment-281487250)

**Comment by daerath** [comment]
Thank you!  We have the new host .exe working.  Yay!
