### ISSUE TITLE
Add documents for saga migrations

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#1587]
There's no document around saga migration and how to manage them over time where they might evolve and how those should be tested. 

There are different approaches and pros/cons depending on the type of persistence mechanism that is used (NH vs RavenDB) that needs to be considered when writing the guide.

**Comment by SimonCropp** [comment]
we did have a sample for this for raven db https://github.com/Particular/docs.particular.net/commit/9df484c7400a863cdaf47350f60d8537ba76628d

but the @Particular/ravendb-persistence-maintainers said it was not a supported scenario so it was deleted

**Comment by indualagarsamy** [comment]
@HEskandari @Particular/ravendb-persistence-maintainers - any comments?

**Comment by HEskandari** [comment]
Maybe we need to split this into NH specific migration and RavenDB? As there is already as sample for RavenDB but as @SimonCropp said @Particular/ravendb-persistence-maintainers believed it is not supported. I haven't been involved in that conversation so can't comment.

**Comment by weralabaj** [comment]
@Particular/nhibernate-persistence-maintainers @Particular/ravendb-persistence-maintainers is that issue relevant? any ideas on how to approach it?

**Comment by MarcinHoppe** [comment]
@weralabaj From NH standpoint, I think this issue is relevant. No clear idea how to approach it yet.

I do believe that it would be a good move to split this into NH and Raven specific parts.

**Comment by weralabaj** [comment]
I think the first good step would be to clarify those three points before splitting:

> how to manage them over time where they might evolve and how those should be tested
@HEskandari do you have a specific example in mind (maybe a support case)?

> There are different approaches and pros/cons depending on the type of persistence mechanism
Example?

- Do we want to encourage people to modify/migrate sagas or rather create new ones when requirements change? In what situations the first approach is better?

@HEskandari thoughts? ☝️

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers @Particular/nhibernate-persistence-maintainers @Particular/ravendb-persistence-maintainers @Particular/sqlpersistence-maintainers 

please handle under your own maintainer budgets and submit a pr if/when you feel this is important enough
