### ISSUE TITLE
OutOfMemoryException troubleshooting

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1600]
The following section could be extended with information on possible causes and links on how to deal with such issues.

* http://docs.particular.net/nservicebus/errors/exception-caveats#outofmemoryexception
* https://groups.google.com/forum/#!msg/particularsoftware/hIqtbyW4EEM/PZMnB63SKwAJ

**Comment by SimonCropp** [comment]
is there anything we can add that is not captured by https://www.google.com.au/search?q=OutOfMemoryException

**Comment by SimonCropp** [comment]
@ramonsmits if u get time to answer the above question please re-open
