### ISSUE TITLE
Doco for how to manually manipulate subscriptions

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#161]
so this bug https://github.com/Particular/NServiceBus/issues/1925 requires people to hack their subscriptions to apply the bug fix. we need some better doco on how to do this

**Comment by SimonCropp** [comment]
@indualagarsamy did u still want to do this one?

**Comment by SimonCropp** [comment]
some text from the sqlbridge sample that may be helpfil

---


**How to add an additional entry to the existing list of subscribers?**
**If using RavenDB as the persistence:**

- To add the SqlMsmqTransportBridge as one of the subscribers, go to http://localhost:8080/raven/studio.html#/documents?database=MsmqPublisher

- Double click on the subscriptions document to open it.

- Add a new entry in the Clients section for SqlMsmqTransportBridge and press Save. For example, after adding, it would appear like this below:

```
{
  "MessageType": "Shared.SomethingHappened, Version=0.0.0.0",
  "Clients": [
    {
      "Queue": "MsmqSubscriber",
      "Machine": "MachineName"
    }, 
        {
      "Queue": "SqlMsmqTransportBridge",
      "Machine": "MachineName"
    }
  ]
}
```

**If using NHibernate as the persistence:**
Run a similar script like below to add the new entry:

```
  Use PersistenceForMsmqTransport
  Go
  
  INSERT INTO Subscription
           ([SubscriberEndpoint]
           ,[MessageType]
           ,[Version]
           ,[TypeName])
     VALUES
           ('SqlMsmqTransportBridge@MachineName',
           'Shared.SomethingHappened,0.0.0.0',
           '0.0.0.0',
           'Shared.SomethingHappened')
  GO
```
where the `SqlMsmqTransportBridge` is the name of the queue that the SqlBridge will be watching.

**Comment by weralabaj** [comment]
Anybody knows if that issue is still relevant?

**Comment by SimonCropp** [comment]
Yeah still relevant. I was planning on something like this http://docs.particular.net/nservicebus/sqlserver/operations-scripting but for NH

**Comment by SimonCropp** [comment]
given the current state of persisters i no longer think this is worthwhile
