### ISSUE TITLE
Identify and tag all the security related documentations

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#1613]
This is related to [this](https://nservicebus.desk.com/agent/case/18452) desk issue. There is no section directly related to 'Security' but there are some pages that are related to the subject. Since all the security best practices usually applies to NServiceBus, we just need to highlight the samples that would help in this respect. Samples that are related to encryption, message pipeline execution abortion, authorisation, etc. are related to this subject.

An interim solution - instead of writing how-tos and best practices - is to tag those pages with 'security' tab which then would be accessible using a tag-specific URL.

**Comment by weralabaj** [comment]
Tag how? Any context?

**Comment by HEskandari** [comment]
@weralabaj sorry for the confusion, just updated the description.

**Comment by ramonsmits** [comment]
We already have a security page: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/security/index.md

@HEskandari his suggestion add the Security

Can't we add several sections? Transports, persistence, messages? We can then point to external docs for MSMQ, RabbitMQ, RavenDB, SQL, Windows services,  etc.

That to me would be a better fit for doco like : http://docs.particular.net/nservicebus/msmq/transportconfig#configuration-queue-permissions

**Comment by HEskandari** [comment]
I also discovered that you can access them via a URL. there appears to be [direct link](http://docs.particular.net/nservicebus/security/) for "security" as well. 

I'll need to make sure all the right documentation are tagged as such.

**Comment by MarcinHoppe** [comment]
This looks like a larger effort. If there's a TF formed around this, count me in.

**Comment by ramonsmits** [comment]
Do we want to tag all Encryption page with Security? I would rather see a Security page shortly summarizing things like authentication, authorization, transport encryption, message encryption, property encryption maybe with some concepts.

From those sections you can then list all documents with the specific tag.

**Comment by ramonsmits** [comment]
@MarcinHoppe I agree, its not just writing a short document.

**Comment by SimonCropp** [comment]
do the tag first. then work on a page after

**Comment by HEskandari** [comment]
I'll send a PR and tag the right pages.

**Comment by SimonCropp** [comment]
@HEskandari so u want to be able to have md content for the tag rendered page?

**Comment by HEskandari** [comment]
@SimonCropp Yes. Is that possible?

**Comment by SimonCropp** [comment]
not atm

raise an issue in the docs engine. should be easy to do

**Comment by weralabaj** [comment]
@ramonsmits @HEskandari @MarcinHoppe seems like the original issue has been addressed, I created a new issue for dedicated page, feel free to update description according to what you have in mind and start working on it https://github.com/Particular/docs.particular.net/issues/1684.
