### ISSUE TITLE
MSMQ security link

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1623]
The following link should be put somewhere in our docs.

Administer Security for Message Queuing
*  https://technet.microsoft.com/en-us/library/cc738047.aspx

**Comment by MarcinHoppe** [comment]
It's here: http://docs.particular.net/nservicebus/msmq/transportconfig#configuration-queue-permissions.

**Comment by ramonsmits** [comment]
Maybe this should be put somewhere else or at least referenced a security guidance page like #1613

**Comment by SimonCropp** [comment]
isnt that link out of date?

isnt this the newer link https://technet.microsoft.com/en-us/library/cc771268(v=ws.10).aspx  ?

**Comment by SimonCropp** [comment]
ok i added the extra link https://github.com/Particular/docs.particular.net/commit/46df02be0b1a85903b479d32bcd1cc24251488d5

also i dont think this i worth putting too much effort into adding extra doco.  googling for "MSMQ security" will serve people better than any extra content we can provide. so closing this one.
