### ISSUE TITLE
Update NServiceBus license search order documentation

### ISSUE THREAD

**Issue by boblangley** [Particular/docs.particular.net#1647]
The doc/table that needs to be updated is located here: http://docs.particular.net/nservicebus/licensing/license-management#where-does-nservicebus-look-for-a-license

The documentation was out of date as of [this commit](https://github.com/Particular/NServiceBus/commit/6aad54401ccb0ba0b59e777a8db0cd922cc4e8d8). Now registry settings are checked before the [conventions](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Licensing/LicenseLocationConventions.cs#L13-L79) are called (which reflect what is expected in the table).

**Comment by SimonCropp** [comment]
@andreasohlund give you made the change can u update the doco

**Comment by andreasohlund** [comment]
Will do

**Comment by andreasohlund** [comment]
Pretty sure https://github.com/Particular/docs.particular.net/pull/2374 addressed this?
