### ISSUE TITLE
Update docs to renamed ScaleOut().InstanceDiscriminator() API

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#1649]
relates to https://github.com/Particular/NServiceBus/pull/3880

Moved & renamed ` ScaleOut().InstanceDiscriminator(...)` to `endpointConfig.MakeInstanceUniquelyAddressable(...)`. Multiple samples and doc pages have snippets which needs to be updated & text verified.

**Comment by indualagarsamy** [comment]
@timbussmann - I assume this is needed for V6. I am setting the milestone to v6.

**Comment by timbussmann** [comment]
looked for usages in docs and came up with the changes in https://github.com/Particular/docs.particular.net/pull/1741
is there more things we need to address as a part of this issue?

**Comment by weralabaj** [comment]
@timbussmann seems there's an overap with https://github.com/Particular/docs.particular.net/pull/1738. once we get the other merged (it waits for some changes in the docs engine), I'll make sure your changes are incorporated.

**Comment by weralabaj** [comment]
The only remaining mentions are addressed in this PR https://github.com/Particular/docs.particular.net/pull/1762, closing.
