### ISSUE TITLE
move upgrade up one level

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1654]
on disk we have this
https://github.com/Particular/docs.particular.net/tree/master/nservicebus/upgrades

which is flawed since where would a SC or SI upgrade guide go.

so propose to move upgrades up one level to the root

**Comment by SimonCropp** [comment]
@weralabaj for some later date

**Comment by weralabaj** [comment]
How about also making it a separate menu item?


IMO that would make sense given this is our concern:

> which is flawed since where would a SC or SI upgrade guide go

**Comment by SimonCropp** [comment]
@weralabaj i am having second thoughts about this. all the things currently under https://github.com/Particular/docs.particular.net/tree/master/nservicebus/upgrades actually depend on NSB. where SC, SI and SP dont. 

so i now think the current structure is good enough. ie we can, when we need, have upgrades under SC, SP and SI

**Comment by weralabaj** [comment]
that's also an option

Another would be to have a separate menu item on the same level as NSB, SP, SC, SI.

**Comment by SimonCropp** [comment]
@weralabaj i like "have a separate menu item" better. will close this
