### ISSUE TITLE
clarify ASB ConfigurationErrorsException in namespace  support

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1658]
here http://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support

there are several usages of ConfigurationErrorsException  that are ambiguous 

for example

>  When only one namespace is specified, then a ConfigurationErrorsException will be thrown at startup.

what happens then more than two are specific?

So go through each usage of ConfigurationErrorsException  and ensure they are specific

**Comment by SimonCropp** [comment]
ping @Particular/azure-service-bus-maintainers

**Comment by yvesgoeleven** [comment]
@SimonCropp The all have a specific text, isn't that what we're supposed to do? Should it be a specific exception type?

**Comment by yvesgoeleven** [comment]
I'll include all scenario's in the document as well

**Comment by melkio** [comment]
@SimonCropp I didn't get your point. What you quoted is fine, it's related to `RoundRobinPartitioningStrategy`: a user has to specify more than one namespace to configure it properly. Two or more are fine.

**Comment by SimonCropp** [comment]
@melkio sorry this one

> Exactly two namespaces have to be configured when using FailOverNamespacePartitioning strategy. When only one namespace is specified, then a ConfigurationErrorsException will be thrown at startup

**Comment by yvesgoeleven** [comment]
@SimonCropp PR https://github.com/Particular/docs.particular.net/pull/1659 with the suggested changes, is this more clear?

**Comment by SimonCropp** [comment]
yup
