### ISSUE TITLE
Duplicate step by step sample in a plain template

### ISSUE THREAD

**Issue by sergioc** [Particular/docs.particular.net#1679]
Duplicate step-by-step sample in a plain template in order to fit an [optimized first-time user guidance flow test](https://github.com/Particular/OptimizeTrialExtensions/issues/61). 

With that issue, we want to encourage users to first go to guidance before downloading anything. However, the current step-by-step sample is limited by the samples template which starts with prominent CTA buttons + NuGet package information at the top, which may encourage readers to stray away from following the guide.

Duplicating the step-by-step guide allows to choose what exactly shows at the top and we can modify the end of the guide with other calls to action.

## Plan of Attack

- [ ] Create duplicate of http://docs.particular.net/samples/step-by-step/ using a plain template
 - [ ] Title: `Step-by-step introduction`
 - [ ] Do not include "Download" or "Browse on GitHub" buttons
- [ ] Remove current "Step by step guide" link under NSB > Getting started in sidebar nav
- [ ] Add `Step-by-step introduction` under NSB > getting started in sidebar nav
- [ ] Link `Getting started` in docs home to the new page

_Note: there's no need to make this a permanent change. It is only necessary for the duration of testing an alternative getting started guide and/or until we have more guidance for first-time users._

CC // @Particular/docs-maintainers @kbaley

**Comment by SimonCropp** [comment]
how about instead we move the sample actions up with improve this doc?

as for the nuget info it is already collapsed by default. and we can make the header and contents smaller if need be

**Comment by sergioc** [comment]
> how about instead we move the sample actions up with improve this doc?

We really want to eliminate any distracting options from this page. Also, is it a good idea to make changes to the samples template layout based on the requirements for this issue which only affects a single page?

> nuget info it is already collapsed by default

It still gets in the way of reading the content. We really want to remove anything that is not the text from the guide itself.

**Comment by weralabaj** [comment]
> which may encourage readers to stray away from following the guide

I really don't understand why is that a problem and what value changing it provides. 
If somebody doesn't need the guide then why isn't it ok to skip it? 

Also take into account that many (or most?!) developers actually **prefer** exploring a new tool by looking at code first, and reading something later, so the current version shows that you understand your audience ;)

**Comment by sergioc** [comment]
> I really don't understand why is that a problem and what value changing it provides. 
If somebody doesn't need the guide then why isn't it ok to skip it?

We want to encourage people who ** need ** the guide to read through it. If the reader determines the guide isn't needed, then it's obviously not up to us to stop from skipping it.

> Also take into account that many (or most?!) developers actually prefer exploring a new tool by looking at code first, and reading something later, so the current version shows that you understand your audience

We don't want to exclude the option to download the .zip. We just want to make it less prominent. Also, preferring to look at code first doesn't mean you should look at the code first. In any case we don't want to stop people looking at the code first, we simply want to make that less likely to happen.

**Comment by SimonCropp** [comment]
You say u want to eliminate distracting options from the page but u want to keep the download option.  Those are conflicting states

**Comment by SimonCropp** [comment]
And making the "let me download the code" option too dificult to find will make developers hate us

**Comment by SimonCropp** [comment]
some history. The download button used to be standard white. We were criticised from clients that it was too hard to find. Hence the green color now

**Comment by sergioc** [comment]
> but u want to keep the download option

... as a link placed somewhere in the text.

> And making the "let me download the code" option too dificult to find will make developers hate us

We don't want to make it too hard to find, we want to make it seem less "click me before you do anything else"

> The download button used to be standard white. We were criticised from clients that it was too hard to find

That makes sense to me within the overall context of samples, not in this variation of a getting started article which is not meant to show grouped with other samples.

**Comment by DavidBoike** [comment]
I thought the whole point was to get the easiest quick win possible with the current Getting Started sample and not to change anything and everything, until Academy was ready to go. This seems over the line.

Like @weralabaj said, ROI is _really_ low here. We should only be doing the things that are so easy and so impactful that it doesn't make any sense **not** to do them.

**Comment by indualagarsamy** [comment]
I discussed this issue earlier with @kbaley today. 

It feels like we are going back and forth with this. We had really long discussions about what's the best approach, and we already had an agreement on this. i.e. it doesn't make sense for us to point to the Step by step or the docs home page. We need a getting started page. For that history, see this issue: https://github.com/Particular/PlatformDevelopment/issues/276#issuecomment-112964765

I understand that we have a getting started page, but it's not good enough as it currently stands with just the two options, ie. "step by step" and "call us". What we need to do is fix the getting started page. We agreed at one time, that what needed to be done was: https://github.com/Particular/Website.Frontend/issues/381

Let's not duplicate the sample.  Instead, let's take a little time and get the "Getting Started" page right even just for the interim until the launch pad or bootstrapper or whatever it is to be ready. 

The proposed AB test adds little or no value. Again, all the reasons for not redirecting the user straight to the step by step is all documented in the issues I have referenced. 

So a BIG HUGE, let's not do this from me.

**Comment by mikeminutillo** [comment]
As a developer wading through pages and pages of documentation I have in the past typically skim read until I found some kind of code snippet or download option. Having said that, this is not the typical sample.

For most of our samples, we assume you have some sort of knowledge of NSB and we are just showing a particular technique or API in action. For those it makes total sense that the very first option is "don't want to read our painstaking walkthrough? Download now and get the sucker running on your machine". This sample does not assume knowledge of NSB. It is meant to be the very first step in the NSB world. For this sample it makes sense that we wouldn't show you *anything* that does not directly contribute to your journey learning NServiceBus. 

I agree with @indualagarsamy though that this probably isn't as simple as the template on a single sample. We need a smoother guided experience for new users. Once we have that, it will likely replace this Step-by-Step sample.

**Comment by weralabaj** [comment]
@indualagarsamy I think the useful "Getting started" page would make sense even when the academy is ready, e.g. to provide a high level overview and guide through the articles we already have, and to point to all kinds of resources we have. 
The docs landing page is doing it too, but we could go one step further, e.g. say "Did you get stuck? Ask a question on a Google Group" and things like that, to predict the potential challenges and address them before they arise.

So... how about I close this and open a new issue for creating "Getting started" page, which won't include any "NSB content" but only serve as a map for content we already have?

**Comment by sergioc** [comment]
You seem to be missing the point.

The reason for duplicating this page is to create a slightly optimized version of the step-by-step sample to increases the chances of task completion for first-time users in our test, with the smallest possible effort. 

I don't believe the effort is high here nor should it be, because this is meant to be a SMALL test where errors are expected to be made in order to create learnings. It's not about having the magic bullet come out on the first shot with a highly optimized page that took ages to create.

> So... how about I close this and open a new issue for creating "Getting started" page, which won't include any "NSB content" but only serve as a map for content we already have?

That's not a replacement for this issue, it's a different step. Please open the issue in the initiative repo. Reg. closing this issue, close if you must.

**Comment by weralabaj** [comment]
I opened issue in the initiative repo https://github.com/Particular/OptimizeTrialExtensions/issues/89.

**Comment by indualagarsamy** [comment]
@weralabaj - I agree.
