### ISSUE TITLE
Article on how to create custom channel in gateway

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1683]
The current content is not sufficient to help somebody implement it, so as part of this article cleanup https://github.com/Particular/docs.particular.net/pull/1682 I'm moving it here for future reference and removing from the overview page. Ideally one day we'll have a more extensive "How to implement your own gateway channel" article. As it is now, it won't help much anyway.

## Custom Channel Types

The Gateway includes an HTTP/HTTPS channel implementation, but it is possible to create additional channel types by implementing the `IChannelSender` and `IChannelReceiver` interfaces.

NServiceBus will pass message data (headers and payload) to the configured `IChannelSender` which is responsible for transmitting this information over the desired channel to a receiving Gateway.

`IChannelReceiver` must accept transmissions from the incoming channel and provide the incoming data to NServiceBus through a `DataReceivedOnChannelArgs` instance that is passed to a provided `Func<DataReceivedOnChannelArgs, Task>`.

`IChannelSender` and `IChannelReceiver` implementations are not automatically registered through assembly scanning. The custom channel types must be registered using a channel factory `Func` through the `ChannelFactories` setting:

snippet: GatewayChannelFactoriesConfiguration

    void GatewayChannelFactoriesConfiguration(EndpointConfiguration endpointConfiguration)
    {
        #region GatewayChannelFactoriesConfiguration

        var gateway = endpointConfiguration.Gateway();
        gateway.ChannelFactories(
            senderFactory: channelType => new CustomChannelSender(),
            receiverFactory: channelType => new CustomChannelReceiver());

        #endregion
    }

**Comment by SimonCropp** [comment]
@weralabaj so sample is the plan?

**Comment by weralabaj** [comment]
@SimonCropp there is an issue for sample https://github.com/Particular/docs.particular.net/issues/1458, so if we don't want to have **also** an article I'll move the description there. to me it makes sense to stick to sample only.

**Comment by weralabaj** [comment]
I updated descriptoin of https://github.com/Particular/docs.particular.net/issues/1458, if we decide we can make article while/after the sample is ready.

**Comment by udidahan** [comment]
So, would you say that this was `Withdrawn` in favor of #1458 ?

**Comment by weralabaj** [comment]
@udidahan I guess you could say so, after Simon's comment I've realized it fits an existing issue better.
