### ISSUE TITLE
Create a high-level security guidance article

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1684]
From @ramonsmits:

"I would see a Security page shortly summarizing things like authentication, authorization, transport encryption, message encryption, property encryption maybe with some concepts. 
We can then point to external docs for MSMQ, RabbitMQ, RavenDB, SQL, Windows services,  etc.

From those sections you can then list all documents with the specific tag. "

We already have a security page: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/security/index.md

**Comment by weralabaj** [comment]
ping @ramonsmits @HEskandari @MarcinHoppe

**Comment by HEskandari** [comment]
Having a security guideline is both good and bad. It is easy to come off as security experts and inadvertently take the blame if (or rather when) there's a security breach.

Any thoughts on this @udidahan?

**Comment by udidahan** [comment]
The description seems to keep things well scoped to topics related to message-driven systems. Sounds good to me so far.

**Comment by HEskandari** [comment]
@weralabaj Do you want me to pick this up (if you're not working on it)?

**Comment by MarcinHoppe** [comment]
Do we have any indication that our customers are struggling with understanding how NServiceBus relates to security aspects of its downstream dependencies (mostly transports and persisters)?

What would be the value of providing such doco (concept + links)?

**Comment by HEskandari** [comment]
@MarcinHoppe AFAIR this issue got created as a result of a desk case. So to answer your question, yes, we have had a few cases struggling with this in the past year (and probably before that).

**Comment by MarcinHoppe** [comment]
Any chance of digging that original case out? I'd love to understand what the problem is.

**Comment by HEskandari** [comment]
@MarcinHoppe The initial support case is rather old and I couldn't find it anymore. Closest one I could find in SF is [this issue](https://eu1.salesforce.com/500D000001GDdxE?srPos=10&srKp=500). There are other cases asking about MSMQ permissions, security best practices, AAA and similar subjects. For some you can find a document to link to, but for others you may not find an official one, e.g. best practices, minimum security requirements, etc.

**Comment by weralabaj** [comment]
Doesn't that issue actually fit our wave theme pretty well? Maybe we should open it as a PlatDev issue, as it might require a bit more effort than the usual doco?

**Comment by MarcinHoppe** [comment]
@weralabaj I think security was one of the other theme candidates.

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers @Particular/nhibernate-persistence-maintainers @Particular/ravendb-persistence-maintainers @Particular/sqlserver-transport-maintainers @Particular/sqlpersistence-maintainers @Particular/rabbitmq-transport-maintainers @Particular/nservicebus-maintainers @Particular/servicecontrol-maintainers 

I have added a high level security page https://docs.particular.net/nservicebus/security/ please feel free to submit PRs that add/edit your specific areas.
