### ISSUE TITLE
Create a sample for SC notifications

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1699]
Every now and then somebody asks how they can send email notifications/raise alerts when something goes wrong. Even though we have doco on the subject, the sample can serve as a starting point for implementing custom logic. 

Related to https://groups.google.com/d/msgid/particularsoftware/9216cc47-1b9b-45ed-8e8a-e54301ecb4e2%40googlegroups.com?utm_medium=email&utm_source=footer.

**Comment by weralabaj** [comment]
The customer updated the thread saying they don't have a business use case for this yet, but are interested.

IMO it's worth doing, but not urgent.

**Comment by weralabaj** [comment]
Seems we have pretty good snippets for that already http://docs.particular.net/nservicebus/recoverability/subscribing-to-error-notifications. I don't think sample adds much more value.

**Comment by SimonCropp** [comment]
@weralabaj so the subscribing-to-error-notifications page is actually the "in endpoint" api. if people want to subscribe to errors from multiple endpoints via the SC aggregate they would need to subscribe to SC notifications. Based on that do u still think this should be closed?

**Comment by weralabaj** [comment]
I think I mentioned the wrong link, I had this one in mind http://docs.particular.net/servicecontrol/contracts, probably too many tabs opened ;)

Not sure, seems the implementation is trivial, yet I saw yesterday somebody asking on SO related question.

**Comment by SimonCropp** [comment]
i think the code to write is trivial. but the moving pieces to get that working and experiment with it is not. so i am +1 for a sample
