### ISSUE TITLE
As of NServiceBus Version 6, the .retries queue is no longer created

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#1701]
@Particular/nservicebus-maintainers - Please document this in the upgrade guide along with the reasons. Or ping the appropriate members of the taskforce responsible for this change. 

This is a change of behavior from Version 5.

**Comment by timbussmann** [comment]
I'm not against documenting it, but what is exactly the change of behavior here? Shouldn't we document instead that the queue should be empty when migrating to v6 or to move messages in that queue to the endpoint input queue?

**Comment by indualagarsamy** [comment]
I was talking with a customer and there was a confusion. "Wait, I thought there should be a retries queue, but i don't see one". And the fact that we did this in V5 but no longer do in V6 needs to be documented, because its a behavior change, in addition to migrating to v6 steps you describe. At the moment, there is nothing on this.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers can someone connect this with the parent issue where it was decided to deprecate the retries queue

**Comment by timbussmann** [comment]
That change must have happened over a year ago, I wasn't able to find something useful, maybe @andreasohlund or @danielmarbach may know more.

**Comment by danielmarbach** [comment]
This must have happened around when we deprecated the satellite concept. Let me dig

**Comment by danielmarbach** [comment]
Raised an issue https://github.com/Particular/V6Launch/issues/99

**Comment by indualagarsamy** [comment]
I believe this issue can now be closed as it has been addressed in the doco, as part of the PlatDev issue.
