### ISSUE TITLE
Document perf counters

### ISSUE THREAD

**Issue by synhershko** [Particular/docs.particular.net#171]
How to work with perf counters - setting up, explaining the differnt counters, what they can be used for

**Comment by SeanFeldman** [comment]
done

**Comment by SimonCropp** [comment]
@SeanFeldman the pr u reference only adds descriptions not how to set them up

**Comment by SimonCropp** [comment]
done http://docs.particular.net/nservicebus/operations/performance-counters http://docs.particular.net/samples/performance-counters/
