### ISSUE TITLE
Upgrade guide for distributor is hard to find

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#1711]
Documentation for upgrading distributor to v6 :
http://docs.particular.net/samples/scaleout/distributor-upgrade/

Was looking for this yesterday for a customer and related to a bug found. Could not find it. This morning I suddenly found it via a link here : http://docs.particular.net/nservicebus/scalability-and-ha/distributor/#distributor-configuration

It can only be found under samples. Should this not also be visible under `upgrade guides`? (http://docs.particular.net/nservicebus/upgrades/)

**Comment by tmasternak** [comment]
@dvdstelt was this one fixed? Is there any action needed?

**Comment by weralabaj** [comment]
@tmasternak now there's a link in the menu under upgrade guides to http://docs.particular.net/samples/scaleout/distributor-upgrade/. So resolved and closed :)

**Comment by dvdstelt** [comment]
Discussed it with simon, so closed this one and created pr. What triggered you to have a look at it, just for my information?
