### ISSUE TITLE
RegisterPublisher alignment with core

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1714]
[Publisher registration API](http://docs.particular.net/nservicebus/azure-service-bus/publisher-names-configuration) was changed to align with naming used in Core. Documentation needs to reflect he change.

```c#
RegisterPublisherForType() ==> RegisterPublisher()
RegisterPublisherForAssembly ==> (RegisterPublisher)
```

/cc @Particular/azure-service-bus-maintainers

**Comment by weralabaj** [comment]
@SeanFeldman Won't that be caught by updating NuGets for snippets?

**Comment by SeanFeldman** [comment]
You're right.
