### ISSUE TITLE
Describe how to do an 'assembly include' in 5 to 6 guidance

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1719]
Update 5 to 6 guidance http://docs.particular.net/nservicebus/hosting/assembly-scanning regarding the move from an assembly / type exclusion and inclusion strategy via `AllAssemblies` to an assembly exclusion only.

If customers currently rely on include logic then it would be nice if we show them how to convert that.

Include a sample or snippet that demonstrates how the user can work around this by:
- Scanning for all files (*.dll)
- Build a list of files that contain all types
- Convert that to a set of assemblies
- Create a set of assemblies / files to exclude by doing a LINQ Exclude to get all files not in use
- Pass that to `ExcludeAssemblies`

However, that workaround will not work if you want to partially include types of an assembly.
## References:

Upgrade guide
- http://docs.particular.net/nservicebus/upgrades/5to6

Assemly scanning 
- http://docs.particular.net/nservicebus/hosting/assembly-scanning

Discussion on Slack about why include was dropped
- https://particularsoftware.slack.com/archives/nservicebus/p1469558491000306

Discussion about startup performance
- https://github.com/Particular/NServiceBus/issues/3822

**Comment by weralabaj** [comment]
@ramonsmits We have this http://docs.particular.net/nservicebus/upgrades/5to6#assembly-scanning. Is that really only about creating a sample? If so then can you update the name and descritpion accordingly?

**Comment by indualagarsamy** [comment]
@ramonsmits - can you chime in on @weralabaj's question? Since we have an existing documentation, isn't pointing to the correct link sufficient? I am trying to understand what we are currently missing.

**Comment by ramonsmits** [comment]
@indualagarsamy V6 transitions to an 'exclude' model. There are likely to be customers that use the previous behavior. Have a whitelist of assemblies/types and pass those NServiceBus. We don't have guidance that shows how customers can transition to V6. We don't have any samples that show how to do this.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers Is this worth documenting? if so can u please prioritize in your todo list

**Comment by danielmarbach** [comment]
What is the idea here? Should we write a LINQ reflection sample which filters assemblies?

**Comment by timbussmann** [comment]
> If customers currently rely on include logic then it would be nice if we show them how to convert that.

I think without a more concrete story behind what exactly requires that approach it doesn't make sense to just  "reimplement" features we deprecated?

**Comment by SimonCropp** [comment]
@ramonsmits can u respond to the above?

**Comment by ramonsmits** [comment]
@timbussmann @danielmarbach @SimonCropp The idea here is to have an example where customer can easily transition from V5 to V6. In some environments it might not be easy to migrate to an exclusion model.

Take the assemblies EndpointX.dll, EndpointY.dll and EndpointZ.dll. Creating an endpoint for example with the name *EndpointX*, now the endpoint should only include EndpointX and not the others.

Using an include model makes sense. If additional assemblies are added to the folder for example EndpointU.dll, EndpointV.dll and EndpointW.dll these should automatically be excluded. 

So a single process hosting multiple endpoints is much easier to make/maintain using an include model.

That is not easy in V6 due to our exclusion API.

**Comment by timbussmann** [comment]
I don't know, afaik this capability has been removed intentionally. So giving a workaround to "reimplement" that behavior doesn't make much sense to me. If there is real value, that feature should be added again instead.

but your example sounds more like a deployment issue than an NSB concern to me. Why not use a proper deployment tool to deploy the DLLs you need instead?

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers @ramonsmits - any conclusions?

**Comment by indualagarsamy** [comment]
@SeanFeldman - Do you have any input on this since you were part of the API changes regarding assembly scanning. Can you weigh in? I agree with @timbussmann, i.e. we removed this intentionally, to provide documented workarounds seems to be in direct contradiction with the feature.

**Comment by danielmarbach** [comment]
What @timbussmann and @indualagarsamy said

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - can you weigh in on the conversion process outlined by @ramonsmits? For customers that previously used an include, now to exclude

>
Scanning for all files (*.dll)
Build a list of files that contain all types
Convert that to a set of assemblies
Create a set of assemblies / files to exclude by doing a LINQ Exclude to get all files not in use
Pass that to ExcludeAssemblies

Do you think this is worth having in the upgrade guide?

**Comment by SeanFeldman** [comment]
@indualagarsamy inclusion list has caused quite a few issues. Rather than having back and forth on possible scenarios, I would suggest to document what those are and have a focused discussion. Threads spanning weeks/months lose their steam. It looks like @SimonCropp has basically outlined what [can be done](https://github.com/Particular/docs.particular.net/issues/1719#issuecomment-249097376). So it's down to taking the scenarios, and providing some guidance/samples.

**Comment by timbussmann** [comment]
> Do you think this is worth having in the upgrade guide?

I don't think so. As already stated, in most cases there are better approaches to solve the issue (e.g. deployment) before falling back to the mentioned workaround.

**Comment by indualagarsamy** [comment]
@ramonsmits @timbussmann - can you get on a call to resolve this? cc / @SeanFeldman @Particular/nservicebus-maintainers

**Comment by indualagarsamy** [comment]
@ramonsmits @timbussmann - any conclusions on this? Atm, this is the one issue that's marked for V6 milestone that's currently still open. Can you fast-track this, because we've been discussing this async for over 3 weeks now, while the issue itself has been around since Jun 27.

**Comment by ramonsmits** [comment]
> but your example sounds more like a deployment issue than an NSB concern to me. Why not use a proper deployment tool to deploy the DLLs you need instead?

@timbussmann Not sure what you mean by that. This is a scenario where all assemblies are deployed in a single folder. Seems like a valid approach when hosting multiple endpoints in a single process.

@Particular/docs-maintainers @Particular/nservicebus-maintainers I only raise it as guidance to have for customers that have such a solution and want to migrate to V6 without the need to come up with a solution on how they could even achieve that.

It seems that I'm the only one seeing value in this and I can't seem to be able to convince the maintainers so I think the decision was already made.

**Comment by ramonsmits** [comment]
Another customer basically needing the 'include' model: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/EK2ZJ-BTO8Q/PKhmrGK6AwAJ

**Comment by danielmarbach** [comment]
@ramonsmits you are turning the truth up side down ;) They don't need it. It is perfectly valid to do it the way I described in the google group

**Comment by ramonsmits** [comment]
@danielmarbach I don't agree, if you host 10 endpoints this way then you need to work around the exclusion model by excluding the other 9 folders instead of just included the files of 1 folder per endpoint.

**Comment by SzymonPobiega** [comment]
@danielmarbach I am here with @ramonsmits . Although ideally I would get rid of this whole scanning thing from the core. When I was preparing the [data distribution sample](https://docs.particular.net/samples/routing/data-distribution/) it was a pain in the neck to configure the two endpoints in a single process:

```
var typesToExclude = AllTypes
    .Where(t => t.Namespace != "DataDistribution")
    .ToArray();
distributionConfig.ExcludeTypes(typesToExclude);
```

**Comment by danielmarbach** [comment]
When we moved to the Exclusion API only we agree that for a majority of our users it makes things simpler. If we now come to another conclusion, fine but then let's raise an issue and start discussing this independently. We are not moving anywhere with this if we continue to collaborate like we did here.

**Comment by SimonCropp** [comment]
I must be missing something... It would seem both the scenarios described here would be more complex with an include api

**Comment by SimonCropp** [comment]
is this call ever happens https://github.com/Particular/docs.particular.net/issues/1719#issuecomment-252331203 then please send a PR
