### ISSUE TITLE
Re-org routing docs

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1721]
The new versioning capabilities offered by our Docs engine can help make docs easier to follow for the users.

E.g. see http://docs.particular.net/nservicebus/messaging/routing, http://docs.particular.net/nservicebus/messaging/message-owner. 

IMO it's very hard to:
- as a user, understand what pages I need to read, depending on which version I'm using
- as a readerm, follow the text on a page, when it talks about various versions and jumps from one to another.

PoA:
- [x] review content we have
- [x] restructure #1787
- do a proper review
  - [ ] verify the content is technically true
  - [ ] do maintainers/editors review

**Comment by SzymonPobiega** [comment]
Added a restructure PR https://github.com/Particular/docs.particular.net/pull/1787
