### ISSUE TITLE
SQL DDL statements from the SQL Transport

### ISSUE THREAD

**Issue by udidahan** [Particular/docs.particular.net#1722]
I was talking to someone about our SQL Transport and they asked me how they'd get the DDL statements that would create the tables because their DBAs wouldn't agree to provide the privileges needed for NServiceBus to do that in production.

Looking quickly through the docs, I couldn't find it. Do we have that somewhere?

ping @Particular/sqlserver-transport-maintainers

**Comment by weralabaj** [comment]
I think that snippet is the closest we have http://docs.particular.net/nservicebus/sqlserver/operations-scripting#create-queues-the-create-queue-helper-methods (`CreateQueue` method).

Would that be good enough to get them started, or should we modify that section?

**Comment by udidahan** [comment]
The thing is that the DBAs would have to know which queue names to plug in there, and they wouldn't know that.

**Comment by MarcinHoppe** [comment]
This would also be dependent on endpoint configuration (timeouts, callbacks, etc.).

I'd rather see endpoint having an option to generate DDL on startup.

@udidahan is there aby chance to use your contact to gather some requirements around handling DDL by DBAs?

**Comment by weralabaj** [comment]
> The thing is that the DBAs would have to know which queue names to plug in there, and they wouldn't know that.

Is that an option that we collaborate with devs rather than DBAs to generate those scripts? I think that would be easier, as they already understand how NSB works and what it needs.

We don't have a full solution ready, but we could work with them to come up with something. 

> I'd rather see endpoint having an option to generate DDL on startup.

That's an interesting idea. 

> because their DBAs wouldn't agree to provide the privileges needed for NServiceBus to do that in production

We don't have very good guidance around deployment and managing the Platform in production (for example see https://github.com/Particular/docs.particular.net/issues/1189 and https://github.com/Particular/docs.particular.net/issues/135). I think it'll be very valueable, if we could collaborate with those people to see what should be included and create some guidance articles (even if incomplete for now).

@udidahan Do you think we should we open a Desk case for them? I can then collaborate with the person handling the case to make sure we'll document it properly.

**Comment by HEskandari** [comment]
We say developers are responsible for sending the script to the DBA...Can't they generate the script from the DB management app from the Dev/Staging environment and mailing it to the DBA? 

I'd argue that generating the script at runtime is effectively doing just that.

**Comment by tmasternak** [comment]
> I'd rather see endpoint having an option to generate DDL on startup.

Maybe we could have sql statements printed out to logs when in DEBUG? That would allow devs to start the endpoint and get all table creation DML statements we are issuing.

**Comment by udidahan** [comment]
@weralabaj this is from a partner who was passing on second-hand concerns. I don't think we can get in touch with the source in this case. Still, I think we can understand what a DBA-friendly solution might look like.

**Comment by weralabaj** [comment]
> .Can't they generate the script from the DB management app from the Dev/Staging environment and mailing it to the DBA?

@HEskandari I also thought about that, @udidahan can we check if that could be an option, and if not, then why not?

If that could work then we could create the appropriate doco describing how to do it step-by-step very quickly.

**Comment by udidahan** [comment]
> If that could work then we could create the appropriate doco describing how to do it step-by-step very quickly.

That would be a good first step - absolutely.

**Comment by HEskandari** [comment]
I have update the documentation [here](url). Is this good enough, or should we continue the conversation?

**Comment by SzymonPobiega** [comment]
@HEskandari I think the link is broken.

**Comment by HEskandari** [comment]
Sorry, link updated. Please let me know if this can be closed.

**Comment by weralabaj** [comment]
After seeing Udi's reply on Slack, I think that might be a bigger effort and would benefit from a proper TF, etc. I opened an issue in PlatDev https://github.com/Particular/PlatformDevelopment/issues/899, feel free to update description and comment.
I think we can close this one.

**Comment by SzymonPobiega** [comment]
LGTM

**Comment by HEskandari** [comment]
Closing this issue and the rest will be done as a part of Particular/PlatformDevelopment#899.
