### ISSUE TITLE
Better scale-out samples - discuss

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1729]
Right now for the sake of having "hit F5 & run" experience, we hack scale-out samples to run multiple instances on a single machine (see [example](http://docs.particular.net/samples/routing/instance-mapping-file/#code-walk-through-simulating-multiple-machines)).

Given that **some customers use samples as starting points for creating their own projects**, I have doubts if that's the best approach or if those samples only are sufficient.

Potential alternatives:
- Keep the samples as they are, plus:
   - Create step-by-step guides for scale-out in docs
   - Create additional samples that resemble real life, but don't run by hitting F5 plus info how to configure it in a standard environment (whatever that should be).
   - ...

It's not urgent, we might discuss after the V6 release.

/cc: @Particular/docs-maintainers

**Comment by ramonsmits** [comment]
Agreed, for example, the distributor sample without incrementing the maximum concurrency level on both the distributor and the worker doesn't make sense as a real life demo.

Maybe this can be aligned with the idea that we want to have an always running demo environment. That should contain a lot of features that will be used in a sort of production environment.

**Comment by SimonCropp** [comment]
Strong -1 on this

Specifically 

> Create additional samples that resemble real life, 

real life for one org will not be real life for another. so the above is not possible without creating dozens of variants per sample addressing slightly different customer requirements. 

For example one vector of routing config would be "where to store my routing information". filesystem co located with assemblies, file system on a network share, file system on a replicated local location, db, embedded resource, call a webservice, etc. Any org is likely to pick only one of those, so to target all "real life" we would need one of each. now if u r proposing "real life samples" then u either need to hit evey combination of all vectors, or u dont hit any and u make them choose them all, in which case there is very little value of that sample over simple documentation.

> Maybe this can be aligned with the idea that we want to have an always running demo environment. That should contain a lot of features that will be used in a sort of production environment.

we already have this in the showcase. feel free to add more features

**Comment by weralabaj** [comment]
OK @SimonCropp I see your point, on the other hand quite a few customers take samples, modify and that's how they start their real projects.
So would be providing additional guidance, tips&tricks, things to consider when doing X,  Z questions to ask a more appropriate approach? 
We say "this is not how you should do it, it's just for simplicity", but don't provide much detail as to go about the "real-life" approach.

**Comment by SimonCropp** [comment]
Isn't that covered here http://docs.particular.net/samples/#not-production-ready

**Comment by weralabaj** [comment]
That's a disclaimer, not "how should you do it" ;) I'm in favour of doing more hand-holding, specifically per selected samples.
On the other hand, might be better to try it on a few samples and then form conclusions if that's a viable approach.

**Comment by SimonCropp** [comment]
I think that starts to get into the launchpad space https://github.com/ParticularLabs/NServiceBus.Launchpad

**Comment by weralabaj** [comment]
Hm possibly. Good you brought it up.

**Comment by SzymonPobiega** [comment]
A scale-out launchpad thingy would be cool. I'd like to chose the transport and the number of instances etc and get a working solution.

**Comment by weralabaj** [comment]
IMO that issue answered my question, so I'm closing.
Summary: We'll keep scale-out samples as they are (hit F5 and run), once the Launchpad starts working we can consider using it for scale-out scenarios too, otherwise if people complain or we notice problems among customers around that subject, we'll expand articles to cover the confusing parts.
