### ISSUE TITLE
Add sample showing `AllInstancesDistributionStrategy`

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#1733]
because it has been removed from the core.

**Comment by weralabaj** [comment]
@SzymonPobiega is that this one https://docs.particular.net/samples/routing/data-distribution/? can we close?

**Comment by SzymonPobiega** [comment]
@weralabaj that would be a bit different but since we already have a fair-distribution sample which includes a custom distribution strategy I think we can close it.
