### ISSUE TITLE
Document HandleCurrentMessageLater

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#1753]
There is currently no doco for this feature (that puts the current message at the back of the queue)

There is talks about deprecating the feature in the future

https://github.com/Particular/NServiceBus/issues/1705#issuecomment-238496292

**Comment by weralabaj** [comment]
> There is talks about deprecating the feature in the future

So do we want to document it or not? If not sure then why open the issue in docs? Once the other issue is resolved one way or another, the outcome could be documenting. No need for issues here.

**Comment by andreasohlund** [comment]
Well its present in all released versions of NSB so until we deprecate we should have something?

I can take a stab at this later this week

**Comment by weralabaj** [comment]
OK, that sounds like a good place http://docs.particular.net/nservicebus/messaging/delayed-delivery?

**Comment by andreasohlund** [comment]
After trying to explain the use case to @weralabaj I could come up with a scenario that isn't a super bad idea for the users. I will pick @udidahan 's brain but unless we can find a good use case we'll not document it and instead make sure to deprecate the api in the next major.

Stay tuned...

**Comment by andreasohlund** [comment]
Issue raised to deprecate `HandleCurrentMessageLater`

https://github.com/Particular/NServiceBus/issues/4110

**Comment by weralabaj** [comment]
@andreasohlund updates on this?

**Comment by andreasohlund** [comment]
We can see any real good use case and will deprecate it

https://github.com/Particular/NServiceBus/issues/4110

so I'd say we close this as won't fix?

**Comment by SimonCropp** [comment]
@andreasohlund so u are happy to do the marketing statement of "we are deprecating this feature... what feature... the one that is not documented" ?

**Comment by andreasohlund** [comment]
So you're saying to document it as 

### HandleCurrentMessageLater

Shouldn't be used since its dangerous, please use bus.Defer/context.X or a custom retry policy instead. Will be deprecated in the next major version.

Should I do a PR?

**Comment by andreasohlund** [comment]
Of course fleshing out why its dangerous

**Comment by SimonCropp** [comment]
@andreasohlund sounds good

**Comment by HEskandari** [comment]
@andreasohlund Do you want me to take this off your plate? Can send you the PR to review.

**Comment by andreasohlund** [comment]
That would be awesome, please do!
