### ISSUE TITLE
IMessageMutator and IMutateTransportMessages missing from upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1800]

**Comment by SimonCropp** [comment]
@andreasohlund so is this one yours https://github.com/Particular/NServiceBus/commit/6c5a3228d03cd90f708aba911325129b040b68e4  ?

**Comment by andreasohlund** [comment]
Hmm, isn't this enough? https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/5to6.md#message-mutators

**Comment by SimonCropp** [comment]
damn i am having a shocker. i swear i searched for that.

**Comment by andreasohlund** [comment]
ha, I even started a PR branch since I was conviced I screwed up yet again :)
