### ISSUE TITLE
Document that outbox must not be used for dedupe of non transactional processing

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1803]
The current outbox documentation states: 

> On the handler level, however, the Outbox guarantees exactly-once message processing, same as working with distributed transactions. This higher guarantee level is due to the deduplication that happens on the receiving side.

Source: http://docs.particular.net/nservicebus/outbox/

This seems to suggest that handlers will not be invoked more then once which is incorrect.

The documentation must make clear that:
- Handlers can be invoked more than once if there are duplicates even in case of errors
- Cannot rely on outbox deduplication to invoke non-transactions handlers only once if no errors occur
- Exact-once semantics are only guaranteed for transactional resources that participate in  transaction scope created by the outbox behavior or that share the `IDbConnection` used by the outbox persistence.
- Don't use `Bus.Defer` when working with non-transactional handlers,  Use a saga where the saga sends a message to perform the task and send then when the saga timeout is triggered.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers can you please review the above and submit a PR to correct any problems
