### ISSUE TITLE
Azure Storage persistence doesn't mention it cannot guarantee consistency

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1810]
Azure Storage persistence (ASP) doesn't mention it cannot guarantee consistency. It not transactional and cannot participate in transaction combined with the outbox.

Shouldn't we make it very clear that ASP is non-transactional and that at-least-once message delivery can easily corrupt saga state?

Also potentially mention that this probability increases when scaling out their endpoints.

Issue created based on discussion on slack :  https://particularsoftware.slack.com/archives/azure-asp/p1472129786000008

//cc @yvesgoeleven @SeanFeldman @Scooletz

**Comment by Scooletz** [comment]
Just for sake of reference, there is a corresponding article in the `ASQ` section. I think that linking this is sufficient enough.
http://docs.particular.net/nservicebus/azure/transactions#recommendations-for-using-nservicebus-in-azure-sagas-and-compensation-logic

**Comment by yvesgoeleven** [comment]
I suggest we add a warning somewhere, that links to the transactions document. @ramonsmits where would you put the warning?

**Comment by SeanFeldman** [comment]
Perhaps that should a note that is applicable not just to ASP?
None of the Azure services are transaction (beside Azure SQL Server that is an exception when it comes to combing storage and transport).

**Comment by yvesgoeleven** [comment]
That's the same concern I have, NONE of the azure services are transactional... If users don't know that then we have bigger problems

**Comment by ramonsmits** [comment]
> where would you put the warning?

At the top :-)

> None of the Azure services are transaction 

Although they do not support transactions, most do support atomic writes and optimistic concurrency control. In most situations writes can be designed in such a way that these are consistent and cannot result in data corruption. 

This is the reason I would like to see this warning added as we don't do any effort in prevent corruption.

**Comment by yvesgoeleven** [comment]
@ramonsmits regarding 'As we don't do any effort in prevent corruption.' This isn't true, we do correct the saga data if the secondary indexes get corrupt.

**Comment by SimonCropp** [comment]
@yvesgoeleven @SeanFeldman so is this "done"?

**Comment by SeanFeldman** [comment]
I think @ramonsmits wanted to put a warning on top of the ASP page or something.

**Comment by SimonCropp** [comment]
added a warning to both pages

**Comment by SimonCropp** [comment]
https://github.com/Particular/docs.particular.net/commit/5e8161d2a50fd58d3922dd120396d10bf5ac82f9
