### ISSUE TITLE
Duplicate messages generated by the Outbox

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1816]
Outbox may generate duplicate messages if the `MarkAsDispatched` phase fails. We need to document under what circumstances this might happen.

**Comment by weralabaj** [comment]
How about adding it to the "Important design considerations"? If it needs extensive explanation we can create a subsection for it. 

Feel free to create the rough draft, I can help with editing ;)

**Comment by MarcinHoppe** [comment]
I will get to it after I'm back from vacation. If someone wants to take this on in the meantime, that's even better.
