### ISSUE TITLE
missing message mapping info

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1822]
as part of the recent routing changes the message-owner.md page got removed

it was done with this commit 
https://github.com/Particular/docs.particular.net/commit/3c20db00d872a4df19f417b97fa370e4d68b70fa

the old file is here
https://github.com/Particular/docs.particular.net/blob/433ee500d3ebdf836d8674673e194a6140ffda78/nservicebus/messaging/message-owner.md

the seems to be a fair amount of useful info in the old message-owner.md  that does not exist in the new routing doco

**Comment by SimonCropp** [comment]
ping @SzymonPobiega @andreasohlund 

thanks @SeanFeldman for highlighting the issue

**Comment by SzymonPobiega** [comment]
What content do you think is missing? The config source/provider stuff has been moved to routing extensibility. I could not find anything not covered by the new page.

**Comment by SimonCropp** [comment]
eg in the old file there was content "To register all message types defined in an assembly" i cant see that in the new content

also this content https://github.com/Particular/docs.particular.net/blob/433ee500d3ebdf836d8674673e194a6140ffda78/nservicebus/messaging/message-owner.md#filtering

**Comment by SzymonPobiega** [comment]
PR for solving this: https://github.com/Particular/docs.particular.net/pull/1826
