### ISSUE TITLE
ASQ - Multiple storage accounts mixes 2 concerns

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#1865]
[Multiple storage accounts](http://docs.particular.net/nservicebus/azure-storage-queues/multi-storageaccount-support) is mixing two topics

1. Azure Storage Scalability and Performance
1. Using aliases for connection strings

Scaling out was possible with previous versions of ASQ using "targeted" entities (entity with a specified connection string. F.e. "queue@connecitonString"). That is the focus of the document.

Aliases are new to ASQ and are only applicable to v7 of the transport.

## Suggestion

ASQ documentation to be slightly re-structure in regards to the above.

1. Rename "Multiple storage accounts" to "Cross account routing"
1. Move "Using aliases for connection strings" to a separate document called "Securing Connection Strings To Storage Accounts"

cc @Particular/azure-storage-queues-maintainers

**Comment by Scooletz** [comment]
I don't agree. I can see the reason behind having a separate section in the `Multiple storage accounts`, which is the usage of aliases changes when you're in a `Scale Out` scenario. Effectively, I prefer to read a single `Scale Out` recipe that shows how to leverage multiple accounts rather than read this page and go to another one for more information. The section in `Multiple storage accounts` is written specifically for this scenario. The default configuration page covers a standard usage of this feature.

If we moved this section though, I'd preserve its name as it is "Using aliases for connection strings". We agreed that bringing the `security` notion can be seen as being not secure by default or bringing complexity to other elements of the platform (ServiceControl).

Thoughts? @Particular/azure-storage-queues-maintainers

**Comment by SeanFeldman** [comment]
Preserving the old name for a new document is absolutely fine. I only suggested to change the name, not mandated that :wink: 

As for the document as it is right now - I still think connection strings aliases is **feature**. And as such, should have a dedicated document. Current document can reference standalone "Using aliases for connection strings" w/o a problem.

Additionally, currently the document makes it hard to understand what is available in what version. E.g: aliases are strictly v7+, where cross account routing is 7 _and_ below.

**Comment by Scooletz** [comment]
Let's sync.

**Comment by SeanFeldman** [comment]
Synced. Summary: use partials for sure and review if Aliases should reside in a separate document. 
/cc @Scooletz

**Comment by weralabaj** [comment]
@SeanFeldman @Scooletz What partials have to do with all of this? :)

Sidenote: the link http://docs.particular.net/nservicebus/azure-storage-queues/configuration#using-aliases-for-connection-strings-to-storage-accounts doesn't exist anymore (used here http://docs.particular.net/nservicebus/azure-storage-queues/multi-storageaccount-support#using-aliases-for-connection-strings-to-storage-accounts-for-scale-out)?

If aliases is a security concern, then I'm +1 for either mentioning it in http://docs.particular.net/nservicebus/azure-storage-queues/configuration#connection-strings or a dedicated page. But I'm with Szymon, when it comes to the user perspective.

We still could leave http://docs.particular.net/nservicebus/azure-storage-queues/multi-storageaccount-support#using-aliases-for-connection-strings-to-storage-accounts-for-scale-out mostly as it is, maybe just add a link to the config/dedicated page in this paragraph and also in the config/dedicated page mention that using aliases for scale-out scenario is covered in detail in this section + link to it.

Would that address all concerns?

**Comment by Scooletz** [comment]
@SeanFeldman Could we discuss the current shape of it on today's sync maybe?

**Comment by Scooletz** [comment]
> Sidenote: the link doesn't exist anymore

I'll address the dangling link.
> If aliases is a security concern, then I'm +1 for either mentioning it 

In my opinion we should not change the wording. Including `security it the description of this feature makes the previous version `not-secure`.

> We still could leave http://docs.particular.net/nservicebus/azure-storage-queues/multi-storageaccount-support#using-aliases-for-connection-strings-to-storage-accounts-for-scale-out mostly as it is, maybe just add a link to the config/dedicated page in this paragraph and also in the config/dedicated page mention that using aliases for scale-out scenario is covered in detail in this section + link to it.

We agreed with @SeanFeldman that making the scale out page multiversioned with partials is just enough to make it.

Ping @weralabaj do you agree with the above?

**Comment by weralabaj** [comment]
sounds good, just ping me on the PR then, it wasn't clear from the description what the conclusion was :)

**Comment by Scooletz** [comment]
@SeanFeldman In regards to https://github.com/Particular/docs.particular.net/pull/1926#issuecomment-248976184
Are we closing this issue, or do we need a separate menu item that, as far as I know, can't be versioned?

**Comment by SeanFeldman** [comment]
@Scooletz don't think the fact that it cannot be versioned should prevent us from having it as an item.
That section could be a partial included in both, stand-alone page that is on the menu, and the multi-storage account page.

**Comment by Scooletz** [comment]
Having that said, I'll raise another PR on Monday.

**Comment by Scooletz** [comment]
The PR has been closed.
