### ISSUE TITLE
Improve NServiceBus.SagaPersisters.Azure.DuplicatedSagaFoundException guidance

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1882]
I was hit by the following exception:

> NServiceBus.SagaPersisters.Azure.DuplicatedSagaFoundException: Sagas of type SagaData with the following identifiers '4c0331ad-8fde-4253-887b-a616013016b8', '55bab20e-57a7-4478-a38e-a61601303f09', 'f18ca47f-0c73-4fe0-bd1b-a61601305bea' are considered duplicates because of the violation of the Unique property UniqueIdentifier.

@Scooletz mentioned there is guidance on our docs where a search should return this.

The results on the the following searches aren't really helpful
- http://google.com?q=NServiceBus.SagaPersisters.Azure.DuplicatedSagaFoundException
- http://google.com?q=DuplicatedSagaFoundException
- http://google.com?q=NServiceBus+DuplicatedSagaFoundException
- http://docs.particular.net/search?q=NServiceBus.SagaPersisters.Azure.DuplicatedSagaFoundException
- http://docs.particular.net/search?q=DuplicatedSagaFoundException

Improve the doco, especially related to the critical data corruption that is resolved by ASP version 6.2.4 where its probably best to dedicate a special page for that content also for SEO purpose.

**Comment by Scooletz** [comment]
A small update. @ramonsmits mentioned that we can run into a scenario, when after the upgrade sagas that have duplicates receive no messages. Then after some period of time (a few weeks) and deployment to the production we receive this `DuplicatedSagaFoundException`. Should we proactively throw an exception if the deduplications wasn't run and mark it as run? Is this a separate issue maybe?

Pls chime in @Particular/azure-storage-persistence-maintainers

**Comment by weralabaj** [comment]
> Should we proactively throw an exception if the deduplications wasn't run and mark it as run?

How would you detect this? Is that for when the exception is actually thrown?

Would it be a challenge of ensuring that people follow the upgrade guide carefully?

**Comment by Scooletz** [comment]
@weralabaj 
> How would you detect this? Is that for when the exception is actually thrown?

We could write a marker entry in the table when it's created with high enough version of the storage or when a deduplication tool is run

> Would it be a challenge of ensuring that people follow the upgrade guide carefully?

Could you elaborate on what do you mean in `follow the upgrade guide carefully` ?

**Comment by weralabaj** [comment]
>  follow the upgrade guide carefully

That if they follow the guide then deduplication should be done, right? And thus this problem shouldn't occur. Is that right?

**Comment by Scooletz** [comment]
Yes.

**Comment by SimonCropp** [comment]
@Scooletz based on that i will close this
