### ISSUE TITLE
Sample for self hosting how to only run installer once

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1889]
Related https://github.com/Particular/NServiceBus/issues/1703

// cc @timbussmann

**Comment by SimonCropp** [comment]
dont think we need a full sample for this. should doco be enough?

**Comment by SimonCropp** [comment]
@danielmarbach thoughts?

**Comment by danielmarbach** [comment]
Somewhere here? http://docs.particular.net/nservicebus/operations/installers

**Comment by SimonCropp** [comment]
@danielmarbach LGTM

**Comment by SimonCropp** [comment]
@danielmarbach you interested in doing this doco?

**Comment by danielmarbach** [comment]
@SimonCropp should I go with the approach outlined in https://github.com/Particular/NServiceBus/issues/1703#issuecomment-245869012 ?

**Comment by SimonCropp** [comment]
i think show multiple approaches. one per endpoint

 * switch by command line
 * switch by machine name convention. eg many orgs have naming conventions for machines. eg all production machines are "machine1-PROD"
 * switch by computer AD membership (if a corp environment)
