### ISSUE TITLE
Extend testing sample

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1938]
Cover at least the same scenarios as in the https://docs.particular.net/nservicebus/testing/

https://docs.particular.net/samples/unit-testing/

**Comment by weralabaj** [comment]
From @timbussmann on testing saga timeouts and replies to originator

> There is no real way of automatically trigger timeouts with the unit testing approach. You would just have to handle the timeout message. You can verify whether a timeout has been requested by something like:

> var timeout= context.SentMessages.Containing<TimeoutMessage>().Single();
Assert.That(timeout.Options.GetDeliveryDelay(), Is.EqualTo(TimeSpan.FromMinutes(5)));
or similar. I think we could provide an extension method which checks the NServiceBus.Headers.IsSagaTimeoutMessage header. e.g. something like Where(m => m.IsSagaTimeout()). Thoughts?

> For ReplyToOriginator you would write:

> var reply = context.SentMessages.Containing<SubmitOrder>().Single();
Assert.That(reply.Options.GetDestination(), Is.EqualTo(saga.Data.Originator));

**Comment by SimonCropp** [comment]
@timbussmann @weralabaj please submit a draft PR if you still think this is required
