### ISSUE TITLE
Verify if conversation Id has to be guid and why

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1947]
https://docs.particular.net/nservicebus/messaging/third-party-integration#additional-information

**Comment by andreasohlund** [comment]
From a core perspective its just a string. cc @Particular/nservicebus-maintainers 

@Particular/servicecontrol-maintainers is SC interpreting this a GUID?

@Particular/serviceinsight-maintainers ditto?

**Comment by HEskandari** [comment]
@andreasohlund in ServiceInsight, the ConversationID is only a string as well.

**Comment by johnsimons** [comment]
ServiceControl treats conversationids as strings

**Comment by weralabaj** [comment]
OK, I adjusted the description in the doco

**Comment by weralabaj** [comment]
thanks @johnsimons @HEskandari for quick clarification!
