### ISSUE TITLE
Documentation around bus.Dispose

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#2002]
https://docs.particular.net/nservicebus/containers/#using-an-existing-container-cleanup

Should we now remove the note about diposing the bus? With the new container releases it is now safe to dispose the bus when you have an external container since the external container will not be disposed. Thoughts? @Particular/docs-maintainers @Particular/container-maintainers

**Comment by SimonCropp** [comment]
@danielmarbach agreed
