### ISSUE TITLE
Document why InsertBefore/After should be avoided

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#2022]
After a [discussion in the core](https://github.com/Particular/NServiceBus/issues/3582#issuecomment-252553006) we came to the conclusion that InsertBefore/After should be avoided if possibly. We should document this for both users and our self.

Things that users can do:
- Merge behaviors if they own both 
- Move one to a different stage if needed

Things that we would do internally: (not relevant for doco but I'll put this here fyi)
- Moving things to the connectors (eg the mutators should probably be moved)
- Merging behaviors
- Removing behaviors (eg the unit of work one)
- Add more stages

How about we add a separate "advanced" document and have https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors?version=Core_6 link to it. We should pull the "ReplaceStep" part into this new doc as well?

Thoughts?

**Comment by weralabaj** [comment]
@Particular/nservicebus-maintainers will you take care of it?

**Comment by danielmarbach** [comment]
@dbelcham or @bording would you have capacity to deal with this? I currently have none.

**Comment by weralabaj** [comment]
ping @Particular/nservicebus-maintainers do you have capacity to take care of it now?

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers feel free to submit a PR if you ever get around to this
