### ISSUE TITLE
Document supported RavenDB replica topology

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#2031]
we should clearly state which replica topology we support when using RavenDB as a persistence store for NServiceBus related data. We want to avoid users to fall into the pitfalls of master/master replica for example.

The question is: where is the best place to add this?

Subset of https://github.com/Particular/docs.particular.net/issues/787 

/cc @Particular/ravendb-persistence-maintainers

**Comment by SimonCropp** [comment]
@Particular/ravendb-persistence-maintainers is this worth doing or should we close it?

**Comment by mauroservienti** [comment]
Do we somewhere talk about SQL Server clusters when it comes to NHibernate persistence? If no, then we can close this. If #787 will be done we can talk about replicas there.

**Comment by SimonCropp** [comment]
> Do we somewhere talk about SQL Server clusters when it comes to NHibernate persistence

nope
