### ISSUE TITLE
Scalability/HA article unfairly emphasizes Distributor

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#2035]
https://docs.particular.net/nservicebus/scalability-and-ha/

The distributor is emphasized with a huge heading just because there's a subdirectory for it. The index.md file itself is just YAML so everything is generated based on walking the directory.

**Comment by SimonCropp** [comment]
@DavidBoike what do u propose?

**Comment by DavidBoike** [comment]
Using suppressRelated would probably create a maintainability problem long term. What if we moved everything but index into subdirectories to force headings that had equal importance to distributor?

**Comment by SimonCropp** [comment]
> What if we moved everything but index into subdirectories to force headings that had equal importance to distributor

Seems like a pretty big hack

Isnt the real problem here that the index.md has no content. if there was some real content there then the related links would not seem so important

**Comment by weralabaj** [comment]
> Isnt the real problem here that the index.md has no content.

True. BTW could we move all the MSMQ-specific content under MSMQ Transport and then create some content in the index page that will link to it?

Seems that https://docs.particular.net/nservicebus/scalability-and-ha/scale-out could be moved to the index page, maybe with some additions?

**Comment by weralabaj** [comment]
<img width="718" alt="capture" src="https://cloud.githubusercontent.com/assets/7335079/19922590/9a6541fc-a0e3-11e6-8932-d816d7e1d698.PNG">

@SimonCropp seems just adding text doesn't matter, still it's very prominent for sections. Should we modify the rendering template then?

**Comment by weralabaj** [comment]
Alternative - merge if you like it: https://github.com/Particular/DocsEngine/pull/267

<img width="724" alt="new" src="https://cloud.githubusercontent.com/assets/7335079/19923070/ebca52a6-a0e5-11e6-8cf9-940e59fb2fcd.PNG">
<img width="894" alt="new new" src="https://cloud.githubusercontent.com/assets/7335079/19923077/eec4467e-a0e5-11e6-8aea-9e6deef8c26a.PNG">

**Comment by SimonCropp** [comment]
fixed by @weralabaj
