### ISSUE TITLE
Create a MSMQ to ASB bridge guidance / sample 

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#2036]
We have a a MSMQ to Sql relay. We've been getting similar requests for MSMQ to Azure bridging.
Create adequate doco / sample to illustrate it:

Link to Google Group:
https://groups.google.com/forum/#!msg/particularsoftware/wk_3XOkxouk/yCQryfGrAAAJ

**Comment by SeanFeldman** [comment]
Multiple options, one of them is [NServiceBus.Raw](https://docs.particular.net/nservicebus/rawmessaging/)

**Comment by SeanFeldman** [comment]
Moved to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/504.
