### ISSUE TITLE
Feedback: Azure Cloud Services Host FAQ

### ISSUE THREAD

**Issue by tyrotoxin** [Particular/docs.particular.net#2039]
Page: [/nservicebus/hosting/cloud-services-host/faq.md
](/nservicebus/hosting/cloud-services-host/faq.md)
Question: Is there a way to do Dependency Injection while using ```NServiceBusRoleEntrypoint```?

**Comment by SeanFeldman** [comment]
pinging @Particular/azure-host-maintainers

**Comment by SeanFeldman** [comment]
This doco: https://docs.particular.net/nservicebus/hosting/cloud-services-host/

@tyrotoxin You can use `IConfigureThisEndpoint` to wire the container. Does that answer your question?

**Comment by tyrotoxin** [comment]
Thanks, that answers the question, and the answer is no, because you cannot do real DI at the root of your app and cannot inject dependencies into the ```IConfigureThisEndpoint```.

**Comment by yvesgoeleven** [comment]
@tyrotoxin can you elaborate on the use case, which part used between the host startup and endpoint configuration do you want to inject?

**Comment by tyrotoxin** [comment]
The entry point of an Azure Cloud Service is a `WorkerRole : RoleEntryPoint` class. It has method ```OnStart()``` which is the "app root" - the place where an IoC container must be created. However, it's not possible to use that container to instantiate a `IConfigureThisEndpoint`, where creating a container inside `IConfigureThisEndpoint.Customize()` is incorrect because (1) it's not an "app root" and (2) you must have the whole WorkerRole class testable. Microsoft's design does not allow to test a `WorkerRole` with DI, so in our application we have a wrapper to make it testable.

All in all the ideal solution would look like this (we use Ninject):


    // This class is just a wrapper which is the "app root" where we create
    // an IoC container and delegate calls to actual implementation.
    public class WorkerRole : RoleEntryPoint
    {
        private WorkerRoleImpl impl;
        private IKernel kernel;
        
        public IKernel CreateKernel() => new StandardKernel(...<module-list>...);
        
        public override bool OnStart()
        {
            kernel = CreateKernel();
            impl = kernel.Get<WorkerRoleImpl>();
            return impl.OnStart();
        }
        
        public override void OnStop()
        {
            impl.OnStop();
        }
        
        public override void Run()
        {
            try
            {
                impl.Run();
            }
            finally
            {
                kernel.Dispose();
                kernel = null;
                impl = null;
            }
        }
    }
    
    internal class WorkerRoleImpl
    {
        private INServiceBusRoleEntrypoint nsbRoleEntryPoint;
        
        public WorkerRoleImpl(INServiceBusRoleEntrypoint nsbRoleEntryPoint)
        {
            // We want to inject an interface INServiceBusRoleEntrypoint
            // instead of concrete implementation NServiceBusRoleEntrypoint
            // here to make this WorkerRoleImpl class testable.
            this.nsbRoleEntryPoint = nsbRoleEntryPoint;
        }
        
        public bool OnStart()
        {
            nsbRoleEntryPoint.OnStart();
            return true;
        }
        
        public void OnStop()
        {
            nsbRoleEntryPoint.OnStop();
        }
        
        public void Run()
        {
           ...
        }
    }
    
    // This class must be instantiated using the IoC container
    // instead of using reflection to support DI.
    internal class EndpointConfig : IConfigureThisEndpoint, AsA_Worker
    {
        // Custom internal interface. See comment below.
        private IConfigureNsbTransport configureNsbTransport;
        
        public EndpointConfig(IConfigureNsbTransport configureNsbTransport)
        {
            this.configureNsbTransport = configureNsbTransport;
        }
    
        public void Customize(EndpointConfiguration endpointConfiguration)
        {
            // In production we want to use let's say Azure Storage Queue,
            // but for tests we can use an in-memory transport, that's why
            // we want to inject a IConfigureNsbTransport into this class.
            configureNsbTransport.Configure(endpointConfiguration);
        }
    }

But the big problem I see here is that you cannot create an instance of `EndpointConfig` in the `NServiceBusRoleEntrypoint` implementation without having an interface of concrete IoC container/builder. But there are at least 2 solutions to that problem.

**Comment by yvesgoeleven** [comment]
@tyrotoxin I see what you want to do, in my opinion you would be better off not using the convenience roleentrypoint, but instead use the self hosting approach. This way you can configure the bus in any way you like for local dev/vs in the cloud. For the self hosting approach, refer to the web roles section: https://docs.particular.net/nservicebus/hosting/cloud-services-host/ you can use the same approach in a worker role and it would make your scenario easier.

**Comment by tyrotoxin** [comment]
Yeah, that's what we ended up with. Just was curious if it's already supported by this extension library. Thanks.

**Comment by yvesgoeleven** [comment]
@tyrotoxin probably not, there are so many hosting options in azure these days that we will guide users towards self hosting instead of this kind of convenience classes. Config has become a lot more straight forward over the years, so there is less and less need for classes like this.
