### ISSUE TITLE
The page 'Sequence Diagram' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2055]
The page [Sequence Diagram](https://docs.particular.net/serviceinsight/sequence-diagram/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/serviceinsight/sequence-diagram/index.md)

**Comment by SimonCropp** [comment]
ping @Particular/serviceinsight-maintainers

**Comment by HEskandari** [comment]
I thought @distantcam reviewed all the ServiceInsight pages. 

Something that definitely needs to be added / highlighted is that endpoints times need to be in sync for the data to show correctly in this diagram in particular.
