### ISSUE TITLE
The page 'Container Changes' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2058]
The page [Container Changes](https://docs.particular.net/nservicebus/upgrades/5to6/container) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/5to6/container.md)

**Comment by SimonCropp** [comment]
ping @Particular/container-maintainers

**Comment by danielmarbach** [comment]
@boblangley would you have capacity to do this? Assigned you in the meantime. Feel free to release it again.
