### ISSUE TITLE
The page 'Uninstall RavenDB v2.0' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2061]
The page [Uninstall RavenDB v2.0](https://docs.particular.net/nservicebus/ravendb/uninstalling-v4) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/ravendb/uninstalling-v4.md)

**Comment by SimonCropp** [comment]
ping @Particular/ravendb-persistence-maintainers

**Comment by mauroservienti** [comment]
done via https://github.com/Particular/docs.particular.net/commit/b6c023efd32aee9a716162309d2d0dcb0da9e25e
