### ISSUE TITLE
The page 'Azure Storage Queues Transport' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2062]
The page [Azure Storage Queues Transport](https://docs.particular.net/nservicebus/azure-storage-queues/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-storage-queues/index.md)

**Comment by SimonCropp** [comment]
ping @Particular/azure-storage-queues-maintainers

**Comment by Scooletz** [comment]
I'm on it.
