### ISSUE TITLE
The page 'Azure Storage Queues Transport Configuration' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2063]
The page [Azure Storage Queues Transport Configuration](https://docs.particular.net/nservicebus/azure-storage-queues/configuration) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-storage-queues/configuration.md)

**Comment by SimonCropp** [comment]
ping @Particular/azure-storage-queues-maintainers

**Comment by Scooletz** [comment]
I'm on it.

**Comment by Scooletz** [comment]
Other @Particular/azure-storage-queues-maintainers ? It looks good :)

**Comment by Scooletz** [comment]
Nothing to update @SimonCropp

**Comment by SimonCropp** [comment]
Did u set the reviewed header

**Comment by Scooletz** [comment]
No @SimonCropp as in the notes it's stated that

> Note that for minor changes (e.g. individual spelling or grammar fixes) the reviewed header should NOT be updated.

So I didn't.

**Comment by SimonCropp** [comment]
It still needs a date for the baseline

**Comment by Scooletz** [comment]
Let me put the header then. Should the notes be adjusted as well as they don't cover this scenario?

**Comment by SimonCropp** [comment]
The plan is to add it to all then the extra instructions r redundant
