### ISSUE TITLE
The page 'Frequently Asked Questions' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2064]
The page [Frequently Asked Questions](https://docs.particular.net/nservicebus/azure-storage-queues/faq) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-storage-queues/faq.md)

**Comment by SimonCropp** [comment]
ping @Particular/azure-storage-queues-maintainers

**Comment by Scooletz** [comment]
Let me handle it @SimonCropp
