### ISSUE TITLE
The page 'Azure Cloud Services Host FAQ' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2067]
The page [Azure Cloud Services Host FAQ](https://docs.particular.net/nservicebus/hosting/cloud-services-host/faq) has never been reviewed.
- [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
- [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/cloud-services-host/faq.md)

**Comment by SimonCropp** [comment]
@Particular/azure-host-maintainers

**Comment by yvesgoeleven** [comment]
@SimonCropp will take care of it

**Comment by SimonCropp** [comment]
fixed by PR
