### ISSUE TITLE
The page 'Critical Error Behavior' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2068]
The page [Critical Error Behavior](https://docs.particular.net/nservicebus/hosting/cloud-services-host/critical) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/cloud-services-host/critical.md)

**Comment by SimonCropp** [comment]
@Particular/azure-host-maintainers

**Comment by SeanFeldman** [comment]
closed by https://github.com/Particular/docs.particular.net/commit/009974b3f6d465eb26fcfca47a4d15f934b00bab
