### ISSUE TITLE
The page 'NHibernate Persistence' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2070]
The page [NHibernate Persistence](https://docs.particular.net/nservicebus/nhibernate/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/nhibernate/index.md)

**Comment by SimonCropp** [comment]
@Particular/nhibernate-persistence-maintainers

**Comment by SzymonPobiega** [comment]
Addressed by https://github.com/Particular/docs.particular.net/pull/2092. Closing.
