### ISSUE TITLE
The page 'NHibernate Persistence Saga concurrency' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2071]
The page [NHibernate Persistence Saga concurrency](https://docs.particular.net/nservicebus/nhibernate/saga-concurrency) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/nhibernate/saga-concurrency.md)

**Comment by SimonCropp** [comment]
@Particular/nhibernate-persistence-maintainers

**Comment by SzymonPobiega** [comment]
Addressed by https://github.com/Particular/docs.particular.net/pull/2092. Closing.
