### ISSUE TITLE
The page 'Configure delayed retries' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2073]
The page [Configure delayed retries](https://docs.particular.net/nservicebus/recoverability/configure-delayed-retries) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/configure-delayed-retries.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Assigned it to me and @tmasternak for now. @tmasternak can you help me out here?

**Comment by tmasternak** [comment]
@danielmarbach sure I'll handle this. If in doubt I'll ping you.
