### ISSUE TITLE
The page 'Configure immediate retries' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2075]
The page [Configure immediate retries](https://docs.particular.net/nservicebus/recoverability/configure-immediate-retries) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/configure-immediate-retries.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Assigned it to me since I was part of the recoverability changes. @tmasternak would you find time to help me out
