### ISSUE TITLE
The page 'Override host identifier' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2076]
The page [Override host identifier](https://docs.particular.net/nservicebus/hosting/override-hostid) has never been reviewed.
- [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
- [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/override-hostid.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Talked to @timbussmann and he is going to tackle this.

**Comment by SimonCropp** [comment]
fixed in PR
