### ISSUE TITLE
The page 'Installation' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2078]
The page [Installation](https://docs.particular.net/nservicebus/hosting/nservicebus-host/installation) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/installation.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Talked to @timbussmann and he is going to tackle this together with @dbelcham
