### ISSUE TITLE
The page 'Logging' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2079]
The page [Logging](https://docs.particular.net/nservicebus/hosting/nservicebus-host/logging) has never been reviewed.
- [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
- [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/logging.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
@bording can you review this? Assigned you in the meantime. Feel free to unassign yourself if you won't find time.
