### ISSUE TITLE
The page 'More On Profiles' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2080]
The page [More On Profiles](https://docs.particular.net/nservicebus/hosting/nservicebus-host/more-on-profiles) has never been reviewed.
- [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
- [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/more-on-profiles.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
@ramonsmits would you be willing to help us out here? Assigned you in the meantime, feel free to unassign yourself if you disagree.

**Comment by weralabaj** [comment]
@ramonsmits @Particular/nservicebus-maintainers ping

**Comment by andreasohlund** [comment]
I'll do a first pass

**Comment by andreasohlund** [comment]
PR opened https://github.com/Particular/docs.particular.net/pull/2151

**Comment by andreasohlund** [comment]
PR is merged
