### ISSUE TITLE
The page 'No Endpoint Configuration Found in Scanned Assemblies' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2081]
The page [No Endpoint Configuration Found in Scanned Assemblies](https://docs.particular.net/nservicebus/hosting/nservicebus-host/no-endpoint-configuration-found-in-scanned-assemblies-exception) has never been reviewed.
- [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
- [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/no-endpoint-configuration-found-in-scanned-assemblies-exception.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
@bording can you review this? Assigned you in the meantime. Feel free to unassign yourself if you won't find time.

**Comment by SimonCropp** [comment]
done
