### ISSUE TITLE
The page 'NServiceBus 32-bit (x86) Host Process' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2082]
The page [NServiceBus 32-bit (x86) Host Process](https://docs.particular.net/nservicebus/hosting/nservicebus-host/nservicebus-32-bit-x86-host-process) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/nservicebus-32-bit-x86-host-process.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
@ramonsmits would you be willing to help us out here? Assigned you in the meantime feel free to unassign yourself if you disagree.

**Comment by SimonCropp** [comment]
done in merged PR
