### ISSUE TITLE
The page 'Profiles For NServiceBus Host' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2083]
The page [Profiles For NServiceBus Host](https://docs.particular.net/nservicebus/hosting/nservicebus-host/profiles) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/profiles.md)

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Talked to @timbussmann he is going to tackle this together with @dbelcham
