### ISSUE TITLE
The page 'Custom routing' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2084]
The page [Custom routing](https://docs.particular.net/samples/routing/custom/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/samples/routing/custom/sample.md)

**Comment by SimonCropp** [comment]
ping @SzymonPobiega

**Comment by SzymonPobiega** [comment]
PR #2116 raised. Closing.
