### ISSUE TITLE
The page 'Data distribution' requires review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2085]
The page [Data distribution](https://docs.particular.net/samples/routing/data-distribution/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/samples/routing/data-distribution/sample.md)

**Comment by SimonCropp** [comment]
ping @SzymonPobiega

**Comment by SzymonPobiega** [comment]
PR #2116 raised. Closing.
