### ISSUE TITLE
Feedback: Step by Step Guide - return Task.CompletedTask won't work in 4.5.2

### ISSUE THREAD

**Issue by tmech** [Particular/docs.particular.net#2102]
Page: /samples/step-by-step/sample.md

in OrderCreatedHandler.Handle()
The guide says to use
return Task.CompletedTask;

This won't compile in .NET 4.5.2.(which is the base requirement stated at the top of the guide)
It will work in .NET 4.6+

A working .NET 4.5.2 equivalent would be
return` Task.FromResult&lt;object&gt;(null);"

**Comment by HEskandari** [comment]
Thanks for your feedback, I'll update the guide.
