### ISSUE TITLE
Feedback: Licensing

### ISSUE THREAD

**Issue by matthewcanty** [Particular/docs.particular.net#2115]
Page: /nservicebus/licensing/index.md

I tried to edit it online but the editable Gtihub page was different to what I was seeing online.

This part is misleading:

> For 64-bit operating systems the license is written to both the 32-bit and 64-bit registry. The license is stored is HKEY_LOCAL_MACHINE\Software\ParticularSoftware\License and HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\ParticularSoftware

32-bit ends in License but 64-bit ends in ParticularSoftware. I checked and they should match. Could you clean this up please to avoid confusion.

Thanks

**Comment by gbiellem** [comment]
Thanks @matthewcanty
