### ISSUE TITLE
Better document "Queue Schema" SqlServer connection string parameter

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#2124]
As part of helping a user with https://github.com/Particular/ServiceControl/issues/820 I found quite hard to find doco for "Queue Schema", in a matter of fact the only reference to it is in https://docs.particular.net/nservicebus/sqlserver/connection-settings?version=SqlServer_2#connection-configuration-via-a-named-connection-string:
![image](https://cloud.githubusercontent.com/assets/122651/19788628/d160f8b8-9cec-11e6-9ba0-ff63e2ff330c.png)

I think we need to document that parameter in isolation.

**Comment by MarcinHoppe** [comment]
@johnsimons I see it explicitly documented here for V2 of the transport:

https://docs.particular.net/nservicebus/sqlserver/connection-settings?version=SqlServer_2#custom-database-schemas

V3 has a different way of configuring it.

**Comment by johnsimons** [comment]
@MarcinHoppe I didn't see that and I guess neither the user.

**Comment by MarcinHoppe** [comment]
@johnsimons That's likely because the V3 doco is now the default and ServiceControl is on V2.
