### ISSUE TITLE
Add doco on Distributor APIs

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#2127]
Document APIs such as:
- woker availability manager
- V6 `EnlistWithLegacyDistributor`
- Explain the capacity parameter and provide doco on possible prefetch counts https://github.com/Particular/docs.particular.net/pull/2126#discussion_r85498866

**Comment by SimonCropp** [comment]
@SzymonPobiega r u working on this?

**Comment by SzymonPobiega** [comment]
@SimonCropp nope. I haven't started.

**Comment by SzymonPobiega** [comment]
Closing as PoA has been included in https://github.com/Particular/docs.particular.net/issues/2187
