### ISSUE TITLE
add NServiceBus.Serializers.SystemXml to doco

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2132]
https://github.com/ParticularLabs/NServiceBus.Serializers.SystemXml

since it is a labs projects perhaps it should sit under https://docs.particular.net/community-projects

 * [ ]  Sample
 * [ ] Doco

**Comment by SimonCropp** [comment]
ping @ramonsmits. r u working on this ?

**Comment by ramonsmits** [comment]
@SimonCropp Not on the doco, I tried to use it and it didn't work with the minimum .net framework version so I made a PR. I can make sample for it like demonstrating contract first message modeling?

So XSD -> code gen -> showing that serialization works? If you think that is a useful sample then assign me to this.

**Comment by SimonCropp** [comment]
@ramonsmits i think initially a doco page under this dir https://docs.particular.net/nservicebus/serialization/    and a sample similar to this https://docs.particular.net/samples/serializers/xml/ would be sufficient

**Comment by SimonCropp** [comment]
@ramonsmits submit a PR when you get around to this
