### ISSUE TITLE
Enlisting with the distributor doco, defaults to PushRuntimeSettings.Default.MaxConcurrency

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#2133]
@SzymonPobiega I was looking at https://docs.particular.net/samples/scaleout/distributor-upgrade/#upgrade-enlisting-with-the-distributor and I do not understand 
![image](https://cloud.githubusercontent.com/assets/122651/19846503/956c9f50-9f8b-11e6-90b7-c34408c9accf.png)

I thought in previous versions that is the same as the main queue max concurrency which is set by the user.
And looking at `PushRuntimeSettings.Default.MaxConcurrency` that is [`Math.Max(2, Environment.ProcessorCount)`](https://github.com/Particular/NServiceBus/blob/569b6ae35387382d7b479d9b159ab5ff2c994e4e/src/NServiceBus.Core/Transports/PushRuntimeSettings.cs#L15) 

Am I completely wrong ?
Wouldn't setting this to a number less then the main queue end-up bottle-necking the control queue ?

**Comment by janovesk** [comment]
In **v5 and below**(not 6 as currently stated) it was set to **MaximumConcurrencyLevel**, which had a default of **1** if you did not set an explicit value. 

So "The snippet above shows how to set it to the same value as in previous versions." is incorrect.

"The snippet above shows how to set it to the default **MaximumConcurrencyLevel** in version 6." would be more correct.

**Comment by janovesk** [comment]
The best recommendation here would be to set the capacity to whatever MaximumConcurrencyLevel you configure on the workers, no matter if you use the default or override it. That way you request as many messages from the distributors as you can process at the worker.

**Comment by SzymonPobiega** [comment]
@janovesk @johnsimons how do you like the fix in https://github.com/Particular/docs.particular.net/pull/2144 ?
