### ISSUE TITLE
corrupted-counters class hint is incorrect

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2139]
https://docs.particular.net/nservicebus/operations/performance-counters#corrupted-counters

> Sometimes an NServiceBus endpoint hangs or fails during startup while initializing the performance counters at the following location: NServiceBus.Unicast.Transport.Monitoring.ReceivedPerformanceDiagnostics.SetupCounter

So `ReceivedPerformanceDiagnostics` doesnt seem to exist anymore. so i suspect the current doco is wrong.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers @gbiellem anyone want to take this one?

**Comment by andreasohlund** [comment]
Pretty sure the v6 equivalent is https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Performance/Counters/PerformanceCounterHelper.cs#L29 ?

That said is giving the location adding enough value or should we just remove the location part?

**Comment by SimonCropp** [comment]
perhaps the error message would help more https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Performance/Counters/PerformanceCounterHelper.cs#L36

**Comment by andreasohlund** [comment]
I guess but in the cases where creating hangs forever you won't see it?

**Comment by SimonCropp** [comment]
@andreasohlund sorry yes u r correct

**Comment by andreasohlund** [comment]
Perhaps add the error and just mention that it can also "hang when trying to setup the counters" could be a good enough solution here?

**Comment by SimonCropp** [comment]
@andreasohlund do u want to make that change?

**Comment by andreasohlund** [comment]
Will do

**Comment by andreasohlund** [comment]
PR opened https://github.com/Particular/docs.particular.net/pull/2323

**Comment by andreasohlund** [comment]
Pr merged
