### ISSUE TITLE
Support hightlighting search keywords

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2146]
If you search for a keyword like 'performance' https://docs.particular.net/search?q=performance it would help if the destination page has these keywords highlighted. This means that the query attributes on the referrer url need to be used if present.

This makes it easier for the readers to find the content they are interested in.

**Comment by SimonCropp** [comment]
wrong repo ;)

**Comment by weralabaj** [comment]
Moved manually to https://github.com/Particular/DocsEngine/issues/268
