### ISSUE TITLE
Improve search result layout/design

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2148]
## Current results layout

![image](https://cloud.githubusercontent.com/assets/152998/19923972/316c4d4c-a0ea-11e6-8ff2-d542f10fa82c.png)

## Suggestions

- Remove bullet list item indicator
- Remove text *Found results in multiple versions of package NServiceBus:*
- Slightly increase font size of description
- Remove 'Version', maybe replace it with package name instead
- Versions not as a bullet list but as text:

**Comment by weralabaj** [comment]
@ramonsmits wrong repo, moved to https://github.com/Particular/DocsEngine/issues/269
