### ISSUE TITLE
Remove ASB samples which show injection of ReadonlySettings

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#2153]
Currently, we have samples like 

* [Custom partitioning strategy ](https://docs.particular.net/samples/azure/custom-partitioning-asb/#subscriber-creating-a-custom-partitioning-strategy)
* [Custom sanitization strategy ](https://docs.particular.net/nservicebus/azure-service-bus/sanitization)

which show how `ReadonlySettings` can be injected. Users should not be relying on `ReadonlySettings` being present. It is an implementation detail of the core and currently an implementation detail of ASB that it uses internally a custom container. Either the interface strategies we provide are self-contained (all envisioned parameters are passed in) or we allow users to register their instances and then they can access any settings they want in the constructor. I'll propose we remove these sample snippets.

**Update**

Currently, removing `ReadonlySettings` is not possible. We'll be addressing this in ASB tranport v8 and it will force us to redo our sample to accommodate changes in API, including removal of ``ReadonlySettings` usage.

**Comment by danielmarbach** [comment]
@Particular/azure-service-bus-maintainers please chime in

**Comment by SimonCropp** [comment]
@danielmarbach so @SeanFeldman and i had a conversation about this exact thing earlier today. he is  in the process of re-evaluating these scenarios to see if they should be promoted to real apis or removed

**Comment by SeanFeldman** [comment]
Will be done in v8.

**Comment by weralabaj** [comment]
> Will be done in v8.

@SeanFeldman can you adjust PoA or raise a new issue? I'm not sure what you decided, if that's planned to be done in v8 then probably it'd make sense to raise an issue in ASB repo with that milestone?

**Comment by SeanFeldman** [comment]
Description update and closing. Thank you @weralabaj
