### ISSUE TITLE
The page 'Configuration' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2156]
The page [Configuration](https://docs.particular.net/nservicebus/azure-service-bus/configuration/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-service-bus/configuration/index.md)

**Comment by SimonCropp** [comment]
@Particular/azure-service-bus-maintainers can u have a look at this one

**Comment by SeanFeldman** [comment]
This page will require review as we're going to clean up the public API. Please hold off on this till nsb.asb 7.1.0

**Comment by SimonCropp** [comment]
Ok. Sounds good

**Comment by SimonCropp** [comment]
@SeanFeldman @Particular/azure-maintainers 7.1 is out... ;)

**Comment by SeanFeldman** [comment]
Reviewed and ok. 
[Full configuration doco](https://docs.particular.net/nservicebus/azure-service-bus/configuration/full) on the other hand was missed out. Fixed that [here](https://github.com/Particular/docs.particular.net/commit/bfd0baa726a2a76c29a9e6d3867994fb27fe5a88#diff-b043315dae65f9aa539fedcd9252fa43).

**Comment by SimonCropp** [comment]
@SeanFeldman thanks
