### ISSUE TITLE
The page 'Configuration' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2157]
The page [Configuration](https://docs.particular.net/nservicebus/azure-storage-persistence/configuration) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-storage-persistence/configuration.md)

**Comment by SimonCropp** [comment]
@Particular/azure-storage-persistence-maintainers can u have a look at this one

**Comment by Scooletz** [comment]
I'm on it.

**Comment by SimonCropp** [comment]
pr merged
