### ISSUE TITLE
The page 'Using IBus in a Message Handler' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2158]
The page [Using IBus in a Message Handler](https://docs.particular.net/nservicebus/containers/injecting-ibus) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/containers/injecting-ibus.md)

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers what should we do with this one?

**Comment by timbussmann** [comment]
there doesn't seem to be any information which isn't already here: https://docs.particular.net/nservicebus/messaging/send-a-message?version=Core_5#inside-the-incoming-message-processing-pipeline ?

**Comment by SimonCropp** [comment]
@timbussmann happy to burn it from my perspective

**Comment by timbussmann** [comment]
happy to do that 🔥

**Comment by SimonCropp** [comment]
@timbussmann thanks
