### ISSUE TITLE
The page 'Multi-Site Deployments' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2159]
The page [Multi-Site Deployments](https://docs.particular.net/nservicebus/gateway/multi-site-deployments) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/gateway/multi-site-deployments.md)

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers who is the best person to give this a review?

**Comment by weralabaj** [comment]
@janovesk @SzymonPobiega can either of you have a look? if not, who'd be best? ☝️

**Comment by SzymonPobiega** [comment]
I don't feel competent enough for it but if nobody else volunteers I can give it a try. Assuming that devops wave has a slow start.

**Comment by janovesk** [comment]
I'll do it.

**Comment by indualagarsamy** [comment]
@janovesk - any updates?

**Comment by janovesk** [comment]
Working on this now.

**Comment by janovesk** [comment]
[PR](https://github.com/Particular/docs.particular.net/pull/2367) ready.

**Comment by janovesk** [comment]
Closed by https://github.com/Particular/docs.particular.net/pull/2367

**Comment by SimonCropp** [comment]
@janovesk thanks
