### ISSUE TITLE
The page 'Logging Profiles' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2162]
The page [Logging Profiles](https://docs.particular.net/nservicebus/hosting/nservicebus-host/logging-profiles) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/logging-profiles.md)

**Comment by SimonCropp** [comment]
@Particular/host-maintainers can u give this a review? i think it should be version split with partials for the text. let me know if u need help with the content or the split

**Comment by weralabaj** [comment]
@ramonsmits do you need a hand with this?

**Comment by SimonCropp** [comment]
done
