### ISSUE TITLE
The page 'More On Profiles' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2164]
The page [More On Profiles](https://docs.particular.net/nservicebus/hosting/nservicebus-host/more-on-profiles) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/more-on-profiles.md)

**Comment by SimonCropp** [comment]
@Particular/host-maintainers can u give this a once over?

**Comment by weralabaj** [comment]
@ramonsmits do you need a hand with this?

**Comment by SimonCropp** [comment]
done
