### ISSUE TITLE
The page 'Interface life-cycles' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2165]
The page [Interface life-cycles](https://docs.particular.net/nservicebus/lifecycle/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/lifecycle/index.md)

**Comment by SimonCropp** [comment]
@mikeminutillo give u helped with the interface doco split. can u write some landing text for that page and mark it as reviewed?

**Comment by mikeminutillo** [comment]
Do the other pages need review or just the index? I've created a [PR](https://github.com/Particular/docs.particular.net/pull/2209) to try and put some content there.

**Comment by SimonCropp** [comment]
as part of this issue just the index

**Comment by weralabaj** [comment]
Fixed in https://github.com/Particular/docs.particular.net/pull/2209
