### ISSUE TITLE
The page 'Messaging' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2166]
The page [Messaging](https://docs.particular.net/nservicebus/messaging/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/index.md)

Update page content to provide an introduction to messaging.

**Comment by SimonCropp** [comment]
@Particular/engineers  does anyone want to volunteer to write some intro content about messaging to go here?

**Comment by boblangley** [comment]
I have some bandwidth to work on this.

**Comment by sfarmar** [comment]
@boblangley can I help?

**Comment by SimonCropp** [comment]
@boblangley @sfarmar bump

**Comment by sfarmar** [comment]
@SimonCropp I'm unavailable this week, will get back to this next week.

**Comment by boblangley** [comment]
@SimonCropp I am out this week as well. I will upload my draft as a pr first thing when I get back. 

@sfarmar yes I would appreciate the help

**Comment by boblangley** [comment]
My apologies folks, I have been struggling to get back to this.

I started with @SimonCropp's request above and the summary as a guide. I think when I chatted with @SimonCropp about the approach I was taking I failed to properly convey the approach I was taking and after the review feedback and a great discussion with @indualagarsamy I would like to reset and start over.

@Particular/docs-maintainers can you help me define what we want this article to be? It is clear that what I envisioned may not be appropriate for this type of article, and I am not sure how to proceed.

**Comment by weralabaj** [comment]
@boblangley I'm not sure what were the problems you hit, but are you still interested in working on this? If so how could I help? 

I think some kind of high-level introduction to the topic, like here https://docs.particular.net/nservicebus/hosting/, or here https://docs.particular.net/nservicebus/pipeline/
is what we're after.

**Comment by SimonCropp** [comment]
updated
