### ISSUE TITLE
The page 'Discarding Old Messages' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2168]
The page [Discarding Old Messages](https://docs.particular.net/nservicebus/messaging/discard-old-messages) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/discard-old-messages.md)

**Comment by SimonCropp** [comment]
transport maintainers: can u please sign off (or fix) your sub sections in this document

 - [ ] MSMQ @Particular/nservicebus-maintainers  https://docs.particular.net/nservicebus/messaging/discard-old-messages#caveats-msmq-transport
 - [ ] SQL @Particular/sqlserver-transport-maintainers https://docs.particular.net/nservicebus/messaging/discard-old-messages#caveats-sql-transport
 - [ ] Azure @Particular/azure-storage-queues-maintainers @Particular/azure-service-bus-maintainers https://docs.particular.net/nservicebus/messaging/discard-old-messages#caveats-azure-transports
 - [ ] Rabbit @Particular/rabbitmq-transport-maintainers https://docs.particular.net/nservicebus/messaging/discard-old-messages#caveats-rabbitmq-transport

**Comment by SeanFeldman** [comment]
For ASB & ASQ info is correct.

**Comment by WojcikMike** [comment]
@bording @adamralph I read the rabbit part and it seems correct. But I will allow a second pair of eyes to read it before we tick the box

**Comment by tmasternak** [comment]
Looks good for SQL.

**Comment by andreasohlund** [comment]
MSMQ needs a few changes, will raise a PR

**Comment by MarcinHoppe** [comment]
@tmasternak This is no longer true for V6 SQL transport. We only peek and receive non-expired messages and no longer look at the TTBR value in the message pump. I'll submit a PR to clarify this in different versions.

**Comment by bording** [comment]
> @bording @adamralph I read the rabbit part and it seems correct. But I will allow a second pair of eyes to read it before we tick the box

@WojcikMike The content looks fine to me as well, but I did push up #2219 to make a couple grammar tweaks.

**Comment by andreasohlund** [comment]
PR as promised https://github.com/Particular/docs.particular.net/pull/2258

**Comment by weralabaj** [comment]
Merged PR, seems to be done.
