### ISSUE TITLE
The page 'Message forwarding' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2169]
The page [Message forwarding](https://docs.particular.net/nservicebus/messaging/forwarding) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/forwarding.md)

**Comment by SimonCropp** [comment]
@indualagarsamy give your history with audit/forward can u review this ?

**Comment by weralabaj** [comment]
@indualagarsamy ping, if you don't have time any suggestions on who could help?

**Comment by weralabaj** [comment]
ping @indualagarsamy
