### ISSUE TITLE
The page 'Messages as Interfaces' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2170]
The page [Messages as Interfaces](https://docs.particular.net/nservicebus/messaging/messages-as-interfaces) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/messages-as-interfaces.md)

**Comment by SimonCropp** [comment]
there are a few problems with this page

There are disadvantages of in

 * using the delegate interface API for publish publish negatively effects readability
 * not all serializers support interfaces as messages
 * uses more memory and CPU due to initial proxy generation (possibly negligible)
 * can make it harder to debug since if a bad exception occurs in some places the fact that u have a proxy type as a message can be confusing 
 * makes it harder to test

> One advantage of using interfaces to define messages instead of classes is that "multiple inheritance" is supported; i.e., one message can extend multiple other messages.

This is also true for classes

> The advantage of using a class is that it is possible to include validation logic in the class constructor so that clients sending these messages are not able to send invalid commands

This is problematic since 

 * most serializers need a default constructor. 
 * validation of a class should be done as a sibling class and not in the class itself. 
 * make no distinction between "valid class state validation" (like not null) and "business rule validation"
 * This can be trivially done with the pipeline.
 * seems to imply we would not want to validate message that are interfaces

> Since events represent something that occurred in the past, the importance of validation is much decreased. 

This makes not sense. both the "valid class state validation" and the "business rule validation" is just as applicable as with commands.

> Also, only the publisher of an event is the one that creates and sends the event. Subscribers cannot invalidate an event that was published. As such, the ability to put logic in the class representing a message is less relevant for events.

Subscribers can still have rules around the validity of an event and how to handle invalid ones

> Assume that in version 1 of a publisher, it exposed an event of type X. In Version 2, a new event of type Y is added. Then in Version 3, a new requirement comes along for a type of event, Z, which means that both X and Y occurred. If X, Y, and Z were implemented as interfaces, Z could inherit from both X and Y. The main advantage of this is that when Z is published, subscribers of X and Y receive the event with no changes required of them, as well as subscribers of Z, of course.

@andreasohlund since you are the only person who i have ever seen explain this can u create a sample for the above use case

**Comment by SimonCropp** [comment]
also i dont think XSD is at all relevant to this page

**Comment by andreasohlund** [comment]
>since you are the only person who i have ever seen explain this can u create a sample for the above use case

I've created a generic sample

https://github.com/Particular/docs.particular.net/tree/multi-inheritance-messages/samples/multiple-inheritance

The sample works as expected using XmlSerialization, using JSON it blows up with

```
2016-11-08 12:08:26.028 ERROR NServiceBus.RecoverabilityExecutor Moving message '3b5ce9bb-1898-4302-8b04-a6b800c811b8' to the error queue 'error' because processing failed due to an exception:
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from transport message 3b5ce9bb-1898-4302-8b04-a6b800c811b8 ---> System.Exception: Could not find metadata for 'Newtonsoft.Json.Linq.JObject'.

```

Before pursing this I want to review the sample with @udidahan in order to rename things to match some possible business use case.

Stay tuned

**Comment by andreasohlund** [comment]
I also thinks the first line

>Message schema flexibility is at the core of NServiceBus.

sets the wrong tone.

We don't want users to get fancy with their messages (polymorphic
properties, IEnumerables, complex objects etc) to avoid them getting into
trouble.

How can we reword that part?

**Comment by andreasohlund** [comment]
>also i dont think XSD is at all relevant to this page

Agreed, lets move that to
https://docs.particular.net/nservicebus/serialization/xml under a new
section called "integration with non nservicebus endpoints" ?

**Comment by weralabaj** [comment]
@andreasohlund @SimonCropp is either of you taking care of it or should we look for somebody?

**Comment by andreasohlund** [comment]
>also i dont think XSD is at all relevant to this page

This section doesn't seem to be present on https://docs.particular.net/nservicebus/messaging/messages-as-interfaces any more?

**Comment by andreasohlund** [comment]
Ah, @SimonCropp probably meant the opening line:

>Message schema flexibility is at the core of NServiceBus. Beyond just standard XSD and class serialization, NServiceBus support using interfaces as well.

Change to 

>Message schema flexibility is at the core of NServiceBus. Beyond just standard class serialization, NServiceBus support using interfaces as well.

?

**Comment by weralabaj** [comment]
@andreasohlund @SimonCropp can either of you review this page? if not, who would be a good person to chase?

**Comment by Niklas-Peter** [comment]
You removed the notes "Use classes for commands" and "Use interfaces for events". Do you not agree with this recommendation anymore? Any new recommendations?
