### ISSUE TITLE
The page 'Non-Durable Messaging' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2172]
The page [Non-Durable Messaging](https://docs.particular.net/nservicebus/messaging/non-durable-messaging) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/non-durable-messaging.md)

**Comment by SimonCropp** [comment]
transport maintainer: can u review and mark of the various part of this

 - [ ] SQL @Particular/sqlserver-transport-maintainers https://docs.particular.net/nservicebus/messaging/non-durable-messaging#effect-on-transports-sql-server
 - [ ] MSMQ @Particular/nservicebus-maintainers https://docs.particular.net/nservicebus/messaging/non-durable-messaging#effect-on-transports-msmq
 - [ ] Azure @Particular/azure-service-bus-maintainers @Particular/azure-storage-queues-maintainers  https://docs.particular.net/nservicebus/messaging/non-durable-messaging#effect-on-transports-azure If this is ignored by azure should we log an error or throw an exception when it is detected?
 - [ ] Rabbit @Particular/rabbitmq-transport-maintainers https://docs.particular.net/nservicebus/messaging/non-durable-messaging#effect-on-transports-rabbitmq

**Comment by SeanFeldman** [comment]
Updated for ASB & ASQ - info is correct

**Comment by SimonCropp** [comment]
@SeanFeldman thanks. And the error/throw question I had?

**Comment by SeanFeldman** [comment]
@SimonCropp throwing probably not, logging an error sounds like a good idea, 👍

**Comment by SimonCropp** [comment]
@SeanFeldman want me to raise an issue?

**Comment by SeanFeldman** [comment]
@SimonCropp https://github.com/Particular/NServiceBus.AzureServiceBus/issues/416

**Comment by SimonCropp** [comment]
@SeanFeldman same case for storage queues?

**Comment by SeanFeldman** [comment]
Would make sense. Could you please raise it @SimonCropp ? (need to sign off 😃)

**Comment by andreasohlund** [comment]
We recently debated this in the core

https://github.com/Particular/NServiceBus/issues/4162

and the action point decided was to

[Move support for Express/NonDurable messages down to the transport level](https://github.com/Particular/NServiceBus/issues/4252)

Is there still value to update ASB/ASQ in the interim?

**Comment by SeanFeldman** [comment]
@andreasohlund for ASB we'd need to investigate how big of a benefit that would be. See https://github.com/Particular/NServiceBus/issues/4252#issuecomment-258634202 for details.

**Comment by WojcikMike** [comment]
@Particular/rabbitmq-transport-maintainers I think we need to update Rabbit section as currently using non-durable messaging will result in removing queues and exchanges after broker restart which should be included in the description. Or we should implement https://github.com/Particular/NServiceBus.RabbitMQ/issues/167

**Comment by andreasohlund** [comment]
PR raised to clarify msmq section https://github.com/Particular/docs.particular.net/pull/2218

**Comment by bording** [comment]
@WojcikMike The RabbitMQ section needs some updates in general, because the behavior being described there is no longer correct for 4.x versions of the transport, since we've decoupled publisher confirms from message durability.

**Comment by bording** [comment]
PR opened to update the RabbitMQ section: #2220

**Comment by SimonCropp** [comment]
@bording i ticked off the rabbit parts on your behalf. thanks

**Comment by SimonCropp** [comment]
thanks everyone. Team effort FTW
