### ISSUE TITLE
The page 'Replying to a Message' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2173]
The page [Replying to a Message](https://docs.particular.net/nservicebus/messaging/reply-to-a-message) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/reply-to-a-message.md)

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers the various versions of this page look pretty good. but can u give it a once over and mark it as reviewed

**Comment by timbussmann** [comment]
I think we can close this @SimonCropp ?

**Comment by SimonCropp** [comment]
yep
