### ISSUE TITLE
The page 'Third Party Integration' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2174]
The page [Third Party Integration](https://docs.particular.net/nservicebus/messaging/third-party-integration) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/third-party-integration.md)

## PoA
- [x] Clean up grammar and wording
- [x] Verify headers listed are complete
- [ ] Include header option + serialization options in Required Information
- [x] Make version dependent page
- [x] eliminate reference to "NServiceBus 4 or lower"

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers what should we do with this page?

cc @Particular/sqlserver-transport-maintainers @Particular/azure-service-bus-maintainers @Particular/azure-storage-queues-maintainers @Particular/rabbitmq-transport-maintainers

**Comment by SeanFeldman** [comment]
It's a nice consolidated information that each transport would reference from specific samples. Currently, it only references RabbitMQ and SQL Server though.

**Comment by timbussmann** [comment]
@dbelcham and me will review this page from a core perspective.

**Comment by indualagarsamy** [comment]
@timbussmann @dbelcham - any updates?

**Comment by timbussmann** [comment]
sorry, had to backlog this a bit. Will try to tackle this next week.
