### ISSUE TITLE
The page 'Custom DataBus implementation' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2175]
The page [Custom DataBus implementation](https://docs.particular.net/nservicebus/messaging/databus/custom) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/databus/custom.md)

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers thoughts on changing this to a working sample?

**Comment by timbussmann** [comment]
sounds like a good idea to me 👍

**Comment by SimonCropp** [comment]
given the current flaws in the databus API i dont think this is worth investing time in a sample. so marked as reviewed and clsoing.
