### ISSUE TITLE
The page 'Controlling what is subscribed' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2176]
The page [Controlling what is subscribed](https://docs.particular.net/nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed.md)

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers can u handle this one

**Comment by timbussmann** [comment]
I'll take this.
