### ISSUE TITLE
The page 'MSMQ Transport Fully Qualified Domain Names' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2178]
The page [MSMQ Transport Fully Qualified Domain Names](https://docs.particular.net/nservicebus/msmq/full-qualified-domain-name) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/msmq/full-qualified-domain-name.md)

**Comment by SimonCropp** [comment]
@janovesk @SzymonPobiega can one of u give this a once over and mark it as reviewed?

**Comment by SzymonPobiega** [comment]
@SimonCropp @janovesk I have no domain knowledge about MSMQ+FQDN. Otherwise the article looks OK.

**Comment by janovesk** [comment]
I'll do it

**Comment by janovesk** [comment]
[Done](https://github.com/Particular/docs.particular.net/commit/ba8e576761d98613b7c695803a34d6843e6c777f)

**Comment by SimonCropp** [comment]
@janovesk thanks :)
