### ISSUE TITLE
The page 'Tuning endpoint message processing' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2181]
The page [Tuning endpoint message processing](https://docs.particular.net/nservicebus/operations/tuning) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/tuning.md)

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers i think this one should be version split. who is the best person to work on that?

**Comment by timbussmann** [comment]
@janovesk could you have a look at this? Feel free to unassign if you can't take this.

**Comment by timbussmann** [comment]
assigning this to myself. /cc @janovesk
