### ISSUE TITLE
The page 'Scalability and HA' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2185]
The page [Scalability and HA](https://docs.particular.net/nservicebus/scalability-and-ha/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scalability-and-ha/index.md)

**Comment by SimonCropp** [comment]
@janovesk @ramonsmits @SzymonPobiega seems one (or many) of you should have the history to write some intro content for this page?

**Comment by SzymonPobiega** [comment]
@SimonCropp I think we should 🔥 this section entirely and move the content under the transports (mostly MSMQ). I think it would be also beneficial to add a small "Scaling out" page under "Transports" that would contain links to transport-specific scaling pages and describe the logical difference between scaling on a bus and on a broker transports.

**Comment by SimonCropp** [comment]
@SzymonPobiega I am ok with that. Do u have capacity to handle that?

**Comment by SzymonPobiega** [comment]
@SimonCropp yes. Let me try.

**Comment by SzymonPobiega** [comment]
Here's a PR addressing this: https://github.com/Particular/docs.particular.net/pull/2212

**Comment by weralabaj** [comment]
@SzymonPobiega can we close or is there anything left to do?
