### ISSUE TITLE
The page 'Deploying in a Windows Failover Cluster' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2186]
The page [Deploying in a Windows Failover Cluster](https://docs.particular.net/nservicebus/scalability-and-ha/deploying-to-a-windows-failover-cluster) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scalability-and-ha/deploying-to-a-windows-failover-cluster.md)

**Comment by SimonCropp** [comment]
so this page is problematic for a few reasons

 - refers to NSB host without and mention of self hosting
 - it is confusing if the content is specific to the Distributor  or not.
 - for the content that does talk about the Distributor how would that work with the new routing
 - talks about win server 2008. does 2016 or 2008r2 change any of this. are the screen shots still correct?

@SzymonPobiega @mikeminutillo @gbiellem @janovesk @ramonsmits  all of u have experience in the various part of this. Can i ask u to meet up and form plan-of-attack to work out how to clean-up/update this page?

I suspect at the very least it should be split into more manageable pages. 

Also do a first pass to see if there is any redundant content or content we should not own. so that can be removed and make the problem smaller.

**Comment by SimonCropp** [comment]
in the above context can u also have a look at this issue  https://github.com/Particular/docs.particular.net/issues/2187  ?

**Comment by SzymonPobiega** [comment]
https://github.com/Particular/docs.particular.net/pull/2212 moves that content under msmq directly (not under distributor) because I can imagine a situation where a HA clustered queue is used for a non scaled-out endpoint.

Regarding the actual content, I don't have enough expertise to review/change it :-(

**Comment by ramonsmits** [comment]
@SimonCropp Just before the weekend I started rebuilding my lab to Windows Server 2016. If I finish that probably this or next week that I'll know if clustering has any changes.I'll assign myself to verify this.

**Comment by weralabaj** [comment]
from @ramonsmits on another issue

> Good decision to move the distributor bits under MSMQ but the fail-over guidance isn't specific to MSMQ except for the MSMQ dependency configuration although we mention MSMQ later. Should maybe this page be split in two documents? One that explains how to achieve high availability using Windows Clustering and the other about the MSMQ peculiarities?

**Comment by weralabaj** [comment]
@ramonsmits I know you've been busy with Service Control lately, do you have time now to look into it?

**Comment by indualagarsamy** [comment]
@ramonsmits - any updates?

**Comment by SimonCropp** [comment]
page deleted
