### ISSUE TITLE
The page 'Load Balancing with the Distributor' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2187]
The page [Load Balancing with the Distributor](https://docs.particular.net/nservicebus/scalability-and-ha/distributor/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scalability-and-ha/distributor/index.md)

### Plan of attack

 - [x] Move "When to use it" section to a separate general doco page on scaling-out where we describe the meaning of critical time and how it can guide scaling out
 - [x] Move "MSMQ Version 4" to https://docs.particular.net/nservicebus/msmq/scaling-out and describe why it is not a feasible alternative to SSD or Distributor
 - [x] Move "Increasing the Distributor throughput" section to general scale out doco mentioned above
 - [x] Move "Distributor configuration" and "Worker configuration" second to a separate page that is versioned (`[4.0, 4.3), [4.3, 6), [6,)`)
 - [ ] In the "Performance" section include a discussion of capacity parameter
 - [ ] Add a page on extensibility that covers woker availability manager
 - [ ] Add a link to general clustering page from the "High availability" section

**Comment by weralabaj** [comment]
@SzymonPobiega didn't you review it as part of moving distributor under MSMQ? if not who could help?

**Comment by SzymonPobiega** [comment]
@weralabaj I only moved this particular page. It is a big task on its own to go through it. Let me assign it to myself but not sure how quickly I can start working on it.

**Comment by weralabaj** [comment]
ok I can do the first round plus ask some questions, would that help?

**Comment by SzymonPobiega** [comment]
well, the thing I am not sure is if I will be able to provide the answers. Let me try to tackle it this afternoon. If I fail, I'll let you know.

**Comment by indualagarsamy** [comment]
@SzymonPobiega - any updates?

**Comment by SzymonPobiega** [comment]
@indualagarsamy haven't started it yet :(

**Comment by SzymonPobiega** [comment]
I've created a PoA and I'll start going through these points whenever I have some time.

**Comment by SimonCropp** [comment]
@SzymonPobiega given the current state of the distributor do you want to revisit the POA?

**Comment by SzymonPobiega** [comment]
@SimonCropp the PoA seems up to date but I don't have capacity to handle this right now. I'd like to first focus on SQL technologies doco.

**Comment by SimonCropp** [comment]
@Particular/msmq-transport-maintainers is it worth fixing this page or should we just delete it?

**Comment by SimonCropp** [comment]
@Particular/msmq-transport-maintainers so am i correct in interpreting a lack of response as "delete it"?

**Comment by dvdstelt** [comment]
@SimonCropp We'll discuss it Monday during maintainer sync.

**Comment by SzymonPobiega** [comment]
@dvdstelt too late. Major issues addressed here: https://github.com/Particular/docs.particular.net/pull/2652

**Comment by dvdstelt** [comment]
@SzymonPobiega Hehehehe... I personally didn't have time, so I thought we'd discuss Monday who would take this up.
If there's anything left to do, let us know here.

**Comment by weralabaj** [comment]
@SzymonPobiega is there anything left to do that wasn't addressed in your latest pr?

**Comment by SzymonPobiega** [comment]
Yep, the last three items in the PoA are not yet done.

**Comment by udidahan** [comment]
Seeing as this hasn't been touched in about 6 months, I suggest opening a new issue for the remaining work, and closing this one. Then, that new issue can be handled using the new documentation review process in PlatDev.
