### ISSUE TITLE
The page 'Licensing limitations' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2189]
The page [Licensing limitations](https://docs.particular.net/nservicebus/scalability-and-ha/distributor/licensing) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scalability-and-ha/distributor/licensing.md)

**Comment by SimonCropp** [comment]
@janovesk @SzymonPobiega @andreasohlund i think given the current state of the distributor, and the fact that if we version split this page it is effectively one line, we should just merge the content into the main distributor. thoughts?

**Comment by SzymonPobiega** [comment]
This PR attempts to address this issue too: https://github.com/Particular/docs.particular.net/pull/2212
