### ISSUE TITLE
The page 'Distributor and Publish-Subscribe' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2190]
The page [Distributor and Publish-Subscribe](https://docs.particular.net/nservicebus/scalability-and-ha/distributor/publish-subscribe) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scalability-and-ha/distributor/publish-subscribe.md)

**Comment by SimonCropp** [comment]
@SzymonPobiega can u review this?

**Comment by SzymonPobiega** [comment]
Will be addressed by https://github.com/Particular/docs.particular.net/pull/2222. Closing.
