### ISSUE TITLE
The page 'Scheduling' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2192]
The page [Scheduling](https://docs.particular.net/nservicebus/scheduling/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scheduling/index.md)

**Comment by SimonCropp** [comment]
@johnsimons give u wrote of of, and have worked on, this feature can u give this a once over and mark it as reviewed?

**Comment by johnsimons** [comment]
Done, PR sent

**Comment by SimonCropp** [comment]
pr mergd
