### ISSUE TITLE
The page 'Exposing Endpoints via WCF' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2200]
The page [Exposing Endpoints via WCF](https://docs.particular.net/nservicebus/wcf/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/wcf/index.md)

**Comment by SimonCropp** [comment]
@ramonsmits @danielmarbach both of u have WCF experience. can u give this a once over and mark it as reviewed. TBH i think it is pretty good as is but a second pare of eyes would be good

**Comment by danielmarbach** [comment]
See https://github.com/Particular/docs.particular.net/pull/2217
