### ISSUE TITLE
The page 'How to contribute' requires a review

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2201]
The page [How to contribute](https://docs.particular.net/platform/contributing) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/platform/contributing.md)

**Comment by SimonCropp** [comment]
@Particular/platform-dev-squad i think this page could do with a better guidance on how to contribute to particular pages. @adamralph given your background this might be something u could add value to? 

also should out repo README.txt s link to this?

**Comment by weralabaj** [comment]
ping @Particular/platform-dev-squad @adamralph ☝️  anybody interested in taking it?

**Comment by SimonCropp** [comment]
done https://docs.particular.net/platform/contributing
