### ISSUE TITLE
Distributor status include

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2206]
@SzymonPobiega given the current state of the distributor do u think we should put an include at the top of all the distributor pages?

**Comment by SzymonPobiega** [comment]
@SimonCropp I don't think this is necessary. At least not before we have a more complete solution that covers decommissioning of endpoint instances and flow control. Only then we can say "don't use distributor" without any footnotes

**Comment by SimonCropp** [comment]
Ok
