### ISSUE TITLE
NServiceBus 6.1 mentioned on a doco page

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#2210]
This doco page here:

https://docs.particular.net/nservicebus/messaging/discard-old-messages 

mentions NServiceBus 6.1.

@Particular/nservicebus-maintainers Is this a mistake or a feature from the future documented right now?

**Comment by timbussmann** [comment]
@MarcinHoppe it is a feature documented right now. See here: https://github.com/Particular/NServiceBus/issues/4163

**Comment by MarcinHoppe** [comment]
This looks odd to me as a doco reader. I'm reading about a feature on the official site (released) about a feature that is not available in any way (not even on MyGet, the 6.1 milestone has quite a few items open).

@Particular/docs-maintainers Do you have an opinion?

**Comment by SimonCropp** [comment]
@MarcinHoppe it is a trade off. 

 * the earlier we document the better feedback we get into the feature
 * if we leave it in a branch it reduces visibility and increases the likelihood of merge conflicts
 * if we write it in the future tense then we need to come back and fix that after the release

From my perspective I am happy with doco occasionally jumping in front of released versions. This is how 6.0 worked and no one complained.

**Comment by MarcinHoppe** [comment]
@SimonCropp If this is not a mistake and was planned, then I'm more than happy to close.
