### ISSUE TITLE
Unify MSMQ queue permission guidance

### ISSUE THREAD

**Issue by boblangley** [Particular/docs.particular.net#2227]
Both https://docs.particular.net/nservicebus/msmq/operations-scripting#create-queues and https://docs.particular.net/nservicebus/msmq/transportconfig#queue-permissions should be rewritten and changed to a shared partial.

**Comment by weralabaj** [comment]
@boblangley what's the reason for that issue? just to make sure there's no duplication?
btw you can't have shared partial, we can make an include.

**Comment by SimonCropp** [comment]
@weralabaj yeah the issue is duplication and inconsistency. so yes either an include or make one point to the other

**Comment by SimonCropp** [comment]
@boblangley @gbiellem can u too have a chat and resolve this?
