### ISSUE TITLE
ServiceControl older versions not in documentation 

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#2230]
### Issue

Although I didn't verify a lot, I was looking for the setting `<add key="ServiceControl/ExposeRavenDB" value="true" />` and it wasn't in documentation anymore.
I think we should have this around.

**Comment by dvdstelt** [comment]
I can search code history for the document and add it, but if someone can help with a quick Zoom how to properly set this up, I'd be much obliged.

**Comment by SimonCropp** [comment]
Ping @Particular/servicecontrol-maintainers

**Comment by johnsimons** [comment]
@dvdstelt we do not keep around old versions of documentation, **this is on purpose**, it ensures users that are having difficulty contact us via our support, and then we can tell them to update to latest.
So when handling ServiceControl support issues the first action is to make sure the customer updates to latest, 99% of the time we have already fixed the issue in a later version, obviously ping the _control_ channel in slack if you are stuck and need help resolving the issue.

**Comment by SimonCropp** [comment]
Seems answered ... re open if not
