### ISSUE TITLE
[ASB] Update Custom Partitioning Strategy sample

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2241]
- [ ] Existing [sample for Custom Partitioning Strategy](https://docs.particular.net/samples/azure/custom-partitioning-asb/) should be explained/renamed as "Data Replication" strategy.
- [x] Existing sample for Custom Partitioning Strategy is not linked to the documentation [Multiple Namespaces support](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support). => linked as related

**Comment by weralabaj** [comment]
@SeanFeldman if that's just a cosmetic/editing I could help

**Comment by SeanFeldman** [comment]
@weralabaj absolutely. While reviewed the sample, it became apparent that it's a data replication strategy, but the sample doesn't explain it at all.

**Comment by SeanFeldman** [comment]
Moved to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/507.
