### ISSUE TITLE
[ASB] Multiple namespaces support doco is not connected to Addressing logic

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2242]
[Multiple Namespaces support](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support) should point to the section on "Implementing a custom namespace partitioning strategy" in [Addressing Logic](https://docs.particular.net/nservicebus/azure-service-bus/addressing-logic#namespace-partitioning-implementing-a-custom-namespace-partitioning-strategy) doco.

**Comment by weralabaj** [comment]
Fixed in https://github.com/Particular/docs.particular.net/commit/3aeae80319a50da6b0af364ae30a679dd4331fb7
