### ISSUE TITLE
Feedback: Azure Cloud Services Host FAQ

### ISSUE THREAD

**Issue by philjamaica** [Particular/docs.particular.net#2257]
It would be great to see some documentation on how to use NServiceBus with Azure's Service Fabric offering.

**Comment by yvesgoeleven** [comment]
@philjamaica I'll make sure this guidance gets in

**Comment by SeanFeldman** [comment]
@philjamaica thank you for your feedback. SF hosting would be under the [self-hosting](https://docs.particular.net/nservicebus/hosting/#self-hosting) category at this point. You would create your endpoints as SF services (statefull or stateless).

There's a [labs project](https://github.com/ParticularLabs/NServiceBus.ServiceFabric) SF sample for NSB v5 to demonstrate that SF reliable collections could be used to provide a native persistence alternative. I hope that SF adoption by our customers will drive the demand and we'll be adding an official persistence package down the road. As of today, you can use the existing persisters ([Azure Storage](https://www.nuget.org/packages/NServiceBus.persistence.AzureStorage) if your cluster is on Azure) just as you'd normally do.

**Comment by philjamaica** [comment]
Thanks @yvesgoeleven  and @SeanFeldman . For a newbie like myself, building a composite app composed of a web app served by a bunch of microservices, which would be more straightforward for me to work with using NServiceBus: azure's App Service, or Service Fabric?

**Comment by SeanFeldman** [comment]
This is a great question @philjamaica. Answer is not as simple as I wish it would be: it depends. Depends on how complex is the system, what's the load you'll have, how much of a budget you have, will you be building and deploying more services on top of this solution or not.

App Services (webapps with webjobs) are powerful for solutions of small to mid minus size. Beyond that, I'd say SF is a better technology, but comes with a hefty price tag (cluster with at least 5 beefy machines. SF requires IaaS and PaaS hats to be worn all the time, where with AppServices it's pure PaaS. And so on. Even when the guidance is in place, it won't be as easy as do X or do Y 😃

**Comment by philjamaica** [comment]
@SeanFeldman I found your sample at https://github.com/Particular/docs.particular.net/tree/azure-cloud-showcase/samples/show-case/cloud-azure very helpful re how NServiceBus can work with Web App and Web Jobs.

Please bear with me with another question: in your sample all the Web Jobs are in the same VS Solution. Is this a requirement to host on Azure App Services?

I'm mystified at how you would name endpoints between different Web Apps, or between Web Jobs deployed to Azure App Services from different VS Solutions, given that the PaaS abstracts away all the infrastructure (like names of VMs).

**Comment by SeanFeldman** [comment]
This is by no means a requirement, just a convenience. Keep in mind, it's a sample application 😃 
Naming your endpoints should not be any different from what you'd do in other hosting environments. Notice that this sample is just an [on-premises sample](https://docs.particular.net/samples/show-case/on-premise/) converted to run in Azure.

**Comment by SimonCropp** [comment]
@philjamaica it seems all your questions have been answered here. i will close this one for now. Thanks for asking a question and please feel free to re-open this one of ask a new question any time in the future.
