### ISSUE TITLE
Replace current diagrams with mermeid diagrams

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#2259]
From @SimonCropp proposition for [Pipeline diagram](https://github.com/Particular/docs.particular.net/compare/docs.particular.net/nservicebus/pipeline/steps-stages-connectors?expand=1)

### outgoing

```
graph LR
UC[Initiating<br>User Code]



subgraph Outgoing Pipeline
Outgoing{Outgoing}
OP[Outgoing<br>Publish]
OS[Outgoing<br>Send]
OR[Outgoing<br>Reply]
OLM[Outgoing<br>Local<br>Message]
OPM[Outgoing<br>Physical<br>Message]
Routing[Routing]
end


subgraph Dispatch
Dispatch{Dispatch}
Transport[Transport]
BD[Batch<br>Dispatch]
ID[Immediate<br>Dispatch]
end

UC --> Outgoing
Outgoing --> OP
Outgoing --> OS
Outgoing --> OR
OP --> OLM
OS --> OLM
OR --> OLM
OLM --> OPM
OPM --> Routing
Routing --> Dispatch

ID--> Transport
Dispatch --> BD
Dispatch --> ID
BD --> Transport
```

![image](https://cloud.githubusercontent.com/assets/122666/20369985/488dcae2-acb0-11e6-81f9-17e074446308.png)

### Incoming

```
graph LR

Transport[Transport]

subgraph Incoming Pipeline
TR[Transport<br>Receive]
IH[Invoke<br>Handler]
ILM[Incoming<br>Logical<br>Message]
IPM[Incoming<br>Physical<br>Message]

subgraph Ancillary Actions
Forwarding[Forwarding]
Audit[Audit]
Dispatch
end
end

AncillaryTransport[Transport]


RUC[Receiving<br>User Code]


Transport --> TR
IPM -.-> Forwarding
IPM -.-> Audit
ILM --> IH
IPM --> ILM
TR --> IPM
IH --> RUC

Dispatch --> AncillaryTransport
Audit--> Dispatch
Forwarding --> Dispatch
```

![image](https://cloud.githubusercontent.com/assets/122666/20370019/68aa426a-acb0-11e6-93e4-b863c71d4081.png)

also mermaid give us the ability to make the nodes links to actual doco

@mikeminutillo thoughts seeing as u did the initial diagram?

**Comment by weralabaj** [comment]
@mikeminutillo since you're the author, would you rather keep it as is, or ok to update for the sake of having a single tool and consistency in docs?

**Comment by mikeminutillo** [comment]
:+1: to make it consistent.

**Comment by weralabaj** [comment]
fixed in https://github.com/Particular/docs.particular.net/pull/2278
