### ISSUE TITLE
NSB from other apps content

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#226]
> describing how to go about integrating with Java, as well as useful for sales/support scenarios.
> For example see http://github.com/danielmarbach/Transport.Transport

**Comment by SimonCropp** [comment]
@danielmarbach thoughts on this??

Should it be a sample https://github.com/Particular/docs.particular.net#samples or perhaps multiple samples?

Or would we be better served making it a stand alone repository?

Also r u interested in working on this one?

**Comment by danielmarbach** [comment]
The integration and transport/transport samples itself could be huge. Showing it for different languages, transport technologies and more. My gut feeling tells me we should use a stand alone repo.  

Are we focusing first on java only?

@SimonCropp of course I'm willing/interested to do that. Have you already envisioned a specific repo or folder structure? In my transport transport sample I used the name of the topic (here introduction to nservicebus) plus the specific transport as the name of the folder. I think it is important that each samples tackles only one specific set of problems

**Comment by mauroservienti** [comment]
See also this discussion: https://groups.google.com/forum/#!msg/particularsoftware/gOZA-T3982w/Ed5RIHqAqv4J

**Comment by sfarmar** [comment]
I built this sample a while back to support this kind of questions https://github.com/sfarmar/Samples/tree/master/WebServiceIntegration

I'd be very happy to help...

**Comment by SimonCropp** [comment]
@danielmarbach if we r going to ship something i think we should to it in a repo. So we would  get versioning, issue tracking etc.

But i think in the first cut we should just do doco and or sample. This would be very low friction for us but also less effort to build and maintain. We dont need to worry about a build, deployment, packaging etc. and we can always escalate to a shipped "thing" at a later point. 

Thoughts?

**Comment by SimonCropp** [comment]
@danielmarbach considering the following 

 * all the moving pieces we need to create this and verify it. 
 * the fact that is it unbound in the possible list of languages (java, node, ruby)
 * it is not really core to our platform so we dont need to show examples of every messaging scenario

i am lean more towards one sample that shows all of these. ie instead of having it in the main docs. thoughts on this? shall we have a call to workshop it?

**Comment by mauroservienti** [comment]
I love the idea of having samples that demo those things. I also strongly think that samples in thus space without any high level guidance on the integration topic have the high risk if leading to an amazing spaghetti architecture.

**Comment by danielmarbach** [comment]
Unassigned myself. Not high prio now.

**Comment by SimonCropp** [comment]
already have operation scripting code for various transports. so closing this
