### ISSUE TITLE
Document Transport/Core seam

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2261]
Document transport seam with Core (API expected by core from transports) to go along with the [sample transport](https://docs.particular.net/samples/custom-transport/). 

Content location: [Transports page](https://docs.particular.net/nservicebus/transports/)

This should help community transport creators/maintainers understand better expectations set by NSB Core.

**Comment by SimonCropp** [comment]
@SeanFeldman @Particular/nservicebus-maintainers feel free to submit a PR if you ever get around to this
