### ISSUE TITLE
broken link in 5to6/distributor

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2263]
so the text "Configure it to enlist it with the distributor" here
https://docs.particular.net/nservicebus/upgrades/5to6/distributor#general-upgrade-scenario

links to https://docs.particular.net/nservicebus/upgrades/5to6/distributor#enlist-version-6-endpoints-with-a-distributor which does not exist on that page. 

The only similar reference is here https://docs.particular.net/samples/scaleout/distributor-upgrade/#upgrade-enlisting-with-the-distributor.

so was that a document splitting problem?

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers @SzymonPobiega

**Comment by weralabaj** [comment]
seems so

**Comment by weralabaj** [comment]
I'll work on anchor links checking today, that should help :)

**Comment by SzymonPobiega** [comment]
@timbussmann can you take a look at that link? I am not sure what it should be linking to (if anything).
