### ISSUE TITLE
Configure Delayed Retries needs to be clarified

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#2272]
- The section about "Legacy .Retries message receiver" is not quite clear when creating a new endpoint. 
- The suggested method `DisableLegacyRetriesSatellite` is already obsolete in version 6. Need to clarify how to disable the warn/error.
- In version 6.1 the method is not obsolete anymore (which makes more sense) but means we can't remove it in v7 anymore and if disabling warn/errors is not an option, need to recommend upgrading to 6.1.

**Comment by weralabaj** [comment]
ping @Particular/nservicebus-maintainers ☝️ can you take care of it?

**Comment by timbussmann** [comment]
> but means we can't remove it in v7 anymore and if disabling warn/errors is not an option

I don't see why we can't remove it in v7 as we can do major breaking changes.

> The suggested method DisableLegacyRetriesSatellite is already obsolete in version 6.

we agreed that this was not the best option and therefore removed the obsolete again.

**Comment by danielmarbach** [comment]
@HEskandari like @timbussmann stated we can obsolete the method in the time frame of v7 and don't see any problems with that. As soon as 6.1 is out we can advise customers to upgrade, correct

**Comment by HEskandari** [comment]
@danielmarbach @timbussmann Maybe it's just the wording that's incorrect:

> This API will be obsoleted and removed in Version 7.

Don't think you can obsolete it *and* remove it in version 7.

**Comment by weralabaj** [comment]
So:

"This API will be obsoleted in Version 6.1 and removed in Version 7."?

**Comment by HEskandari** [comment]
@weralabaj Definitely not. In fact the reverse! 

This API is being *un-obsoleted* in version 6.1 and I'm not sure about the plan to make it obsolete again when it will be removed.

**Comment by danielmarbach** [comment]
@HEskandari It will be obsoleted with error. Which means you can't use it after v7

**Comment by HEskandari** [comment]
@danielmarbach so this will be correct then:

"This API will be obsoleted in Version 7 and removed afterwards."

**Comment by danielmarbach** [comment]
@HEskandari yes
