### ISSUE TITLE
Create Video Store sample which runs on ASQ

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#2276]
Connects to https://github.com/Particular/V6Launch/issues/83

In order to demo cloud with NSB we would like to create the video store sample running on ASQ transport and web jobs. The would be demoed with a real connection string. If meetup attendees try it out it should run with storage emulator locally.

http://docs.particular.net/samples/show-case/on-premise/?version=core_6

## Plan of Attack

- [x] Duplicate On-Premise Showcase within docs as Azure Cloud Showcase @mikeminutillo 
- [x] Switch Azure Cloud Showcase to run on top of Azure Storage Queues (using local Storage Emulator) @mikeminutillo
- [x] Convert non-web projects to webjobs @mikeminutillo
- [ ] Add "instance stamp" onto the generated web pages to show scaling out
- [ ] Introduce SignalR Backplane (SQL Server) to enable proper scaling
- [ ] Write instructions from running locally and deploying to azure

Migrated from https://github.com/Particular/V6Launch/issues/102

**Comment by weralabaj** [comment]
@andreasohlund does that issue have a task force? can you add them?

**Comment by andreasohlund** [comment]
Not sure, don't think anyone is working on it. Perhaps @SeanFeldman ?

**Comment by weralabaj** [comment]
so why some PoA checkboxes are ticked? :) who's done that?

**Comment by SeanFeldman** [comment]
Looks like assignees from the original issue were not moved here:
![image](https://cloud.githubusercontent.com/assets/1309622/20677338/fc5678b0-b54f-11e6-8f98-f934e642a2a0.png) (@andreasohlund taking you off, but if you're still interested, please re-add yourself).

Both @mikeminutillo and myself worked on this. I've updated PoA with names to indicate who worked on what. 

Next step we should discuss this sample. It's not quite the same as the rest of the sample we have. There's a competing interest: running on premises with F5 under Storage emulator vs running it in Azure with scale-out. We need to decide what this sample is going to be as the rest of the action items depends on that decision.

**Comment by SeanFeldman** [comment]
Should we get on a call and figure it out?
I feel that we're missing a connector between NA and AU :)

**Comment by SeanFeldman** [comment]
We need to resolve the discussion in PR associated with this issue ( #2143 )
