### ISSUE TITLE
Core V5 performance counter link not pointing to correct results

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2293]
V5 contains the following link:

- http://docs.particular.net/search?q=PerformanceCounters

This doesn't result any results that point to the following document:

- https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/performance-counters.md

I would like to add the keyword `PerformanceCounters` to the page so that it will be listed in the results but I don't see any documents that have a keyword headers but I do see that the *Tags* are listed in the page keywords.

Maybe we can add an additional header called keywords that are also searched or maybe we can extend the tags with character so that the tag isn't shown in the page but is written in the keywords section.

Maybe there is an alternative to this to still return the correct results.

**Comment by weralabaj** [comment]
it works if you do that https://docs.particular.net/search?q=performance+counters

**Comment by weralabaj** [comment]
the result
<img width="1271" alt="search" src="https://cloud.githubusercontent.com/assets/7335079/20827680/c517f64a-b873-11e6-80ee-0fd83f2da30a.png">

So IMO the solution is updating the link, it's incorrect. From the search perspective we can't know how to break spaces to find any possible combination of two words that is meaningful.

**Comment by SimonCropp** [comment]
agreed not a problem we can solve in docs
