### ISSUE TITLE
Multiple-instance support for SQL Server Transport

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#230]
https://github.com/Particular/NServiceBus.SqlServer/issues/22#issuecomment-35568257

Also refer to support / Guidance meeting recording from March 3rd for in-depth discussion on when to use and why.

**Comment by mauroservienti** [comment]
Seems to be fixed by [this](https://github.com/ramonsmits/docs.particular.net/commit/bd736f2658ff9e4987da312352b483fe8046838e), @ramonsmits please reopen if required.

**Comment by SzymonPobiega** [comment]
@mauroservienti I don't think this is published.

@ramonsmits in SQLServer 2.1 we're going to add programmatic configuration. See https://github.com/Particular/docs.particular.net/compare/multi-db-2 and this milestone https://github.com/Particular/NServiceBus.SqlServer/issues?q=milestone%3A2.1.0+is%3Aclosed

**Comment by ramonsmits** [comment]
@mauroservienti it is not merged yet. The article contains too much info and since the article there have been a couple of changes regarding the sql transport.
