### ISSUE TITLE
Do we need to clarify MaximumConcurrencyLevel and MaximumMessageThroughputPerSecond

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#2307]
In the context of v5 distributor and worker 
[reading this](https://docs.particular.net/nservicebus/operations/tuning?version=core_5) didn't quiet make it clear...

* How can I set the number messages a worker will receive from the distributor at one batch?

**Comment by indualagarsamy** [comment]
@sfarmar - is the information you're after covered as part of the distributor documentation? Or is it completely missing?
