### ISSUE TITLE
Better document that the optional NHibernate properties can be used with NServiceBus

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#231]
https://groups.google.com/forum/#!msg/particularsoftware/cvnC9DIbDNo/CHE8ywvH_0IJ

**Comment by SimonCropp** [comment]
@andreasohlund u still working on this ?

**Comment by andreasohlund** [comment]
No

**Comment by SimonCropp** [comment]
@andreasohlund @johnsimons since both of you interacted on this group can one of you please add the required content to the docs. if this is not required in our doco then please close this issue
