### ISSUE TITLE
Feedback: Using NServiceBus in an ASP.NET Core WebAPI Application

### ISSUE THREAD

**Issue by dasjestyr** [Particular/docs.particular.net#2310]
Page: /samples/web/send-from-aspnetcore-webapi/sample.md

So, creating a new .net core application with the webapi template, and then pulling down the NServiceBus package from nuget immediately breaks the project due to incompatible dependencies. Perhaps some clarification on how to get this to work?

Doesn't targetting the full .net framework make it NOT .net core? This article says that this will work with ASP.net core applications so long as they're targetting the full framework, but the compiler is saying that asp.net core is not compatible with 4.6.1, for example.

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "NServiceBus": "6.0.4"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

```

**Comment by SimonCropp** [comment]
@dasjestyr i added some more content around .net core https://docs.particular.net/samples/web/send-from-aspnetcore-webapi/#converting-to-the-full-net-runtime

does that answer your questions?

**Comment by dasjestyr** [comment]
Yes and no, I think. Correct me if I'm mistaken, but this says that you'll be talking to NSB from an  ASP.Net core application but then you remove the core dependencies and target the full framework which I think is misleading. By doing so, aren't you making the ASP.Net core project into a plain ASP.Net project that may or may not have references to .net core libraries? That seems to be something completely different.  It may be more forthcoming to plainly state that NSB doesn't currently work with .net core projects.

Where the technicality might play off as the project *type* is still .net core, I can't run it in a linux docker container, for example because it's not actually .net core application. Am I splitting hairs?

As for the changes in the docs, I think they are still helpful in some respect.

**Comment by SimonCropp** [comment]
> remove the core dependencies and target the full framework which I think is misleading

The core dependencies are not removed. you can see them here https://github.com/Particular/docs.particular.net/blob/master/samples/web/send-from-aspnetcore-webapi/Core_6/WebApplication/project.json

> ASP.Net core project into a plain ASP.Net project

no. this sample still uses the ASP.Net core libraries

>  It may be more forthcoming to plainly state that NSB doesn't currently work with .net core projects.

that is stated in the callout at the top  "So while .NET Core dependencies can be consumed in the .NET runtime, the .NET Core runtime is not currently supported"

>Where the technicality might play off as the project type is still .net core

The technical payoff is that you can use the new versions of asp.net core libraries (mvc web api etc). these versions have better performance, new/different features and are considered "the current stable" versions of those tools

> I can't run it in a linux docker container, for example because it's not actually .net core application. Am I splitting hairs?

No you are not splitting hairs. this is not possible. and we realize many people want this. the current status of NSB and .net core is currently captured here https://particular.net/blog/nservicebus-on-net-core-why-not

**Comment by dasjestyr** [comment]
Ok, fair enough. Thanks!

**Comment by SimonCropp** [comment]
and again sorry the the current NSB .net core story is painful

thanks for the feedback. i think it helped drive that sample to be of a higher quality

will close this one. but please call out any other issues you see in our doco. it is always appreciated.
