### ISSUE TITLE
Targeted SignalR sample

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#2319]
Only use of SignalR in our doco is currently the on-premise sample, where SignalR is far from being the focus.

Sample should show:

* Vanilla JS app, no Angular or anything
* Text field for input
* Button to send text input in message, via WebAPI call, to Server endpoint
* Web app shows "Processing task <input>" with a spinner gif, similar to Azure portal
* Server does 5s Task.Delay and then publishes event
* WebAPI has subscriber for event, pushes to SignalR hub
* JS app receives notification and updates message box to "Task <input> complete".

**Comment by MarcinHoppe** [comment]
@DavidBoike We have this webinar sample project that seems like a good starting point:

https://github.com/particular/webinar.signalr

I'd be happy to strip it down, move on-prem and turn into a sample.

**Comment by DavidBoike** [comment]
@MarcinHoppe That would be awesome if you have bandwidth.

This is also another "promotable" sample we could add to the [Twitter campaign to promote doco/samples](https://github.com/Particular/DeveloperEducation/issues/722).

**Comment by MarcinHoppe** [comment]
@DavidBoike I have some bandwidth and I'll give it a go. Is there a deadline, given the Twitter promotion plan?

**Comment by DavidBoike** [comment]
Nope we can add more tweets to the queue at any time.

**Comment by MarcinHoppe** [comment]
Cool. Assigned to myself and will work on it soon-ish.

**Comment by MarcinHoppe** [comment]
Realistically I will not be able to make any progress on it before the holiday break. I will unassign myself from this issue for now.

**Comment by SimonCropp** [comment]
if anyone wants to claim this then please submit a PR
