### ISSUE TITLE
Document how to host nsb in service fabric

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#2328]
http://stackoverflow.com/questions/41122390/is-it-possible-to-use-nservicebus-with-azure-service-fabric

**Comment by ktheeten** [comment]
Any update on this?  I'm very interested to see this explained.

**Comment by SeanFeldman** [comment]
We're working on it.

From NSB point of view, there are a few routes:

1. "Traditional" approach (running multiple stateless instances of a service with external persistence)
1. Statefull approach, where services are partitioned and data is sharded.
1. Guest executables

For `#1` statefull services can be using self-hosted approach. Endpoint initialization, start, and stop would happen in a [`ICommunicationListener`](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication) that serves as a bootstrapper and endpoint controller.

For `#2` we're going to provide a sample (still [work in progress](https://github.com/Particular/docs.particular.net/tree/service-fabric-routing-sample)) for routing first and later native persistence based on SF Reliable Collections.

`#3` Hosting existing endpoints ['as-is'](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-existing-app)

**Comment by ChristianJensen** [comment]
We are running #1 and it works great so far. 

One question though: Is it possible to start/stop a logical NServiceBus endpoint running on multiple nodes in an Azure Service Fabric cluster? There is not way to do this using the Azure Service Fabric Cluster Manager. We would like to take a logical NServiceBus endpoint (Gateway service)  offline while doing maintenance on backend systems to temporarily stop processing of messages for that endpoint.

**Comment by SeanFeldman** [comment]
@ChristianJensen good question. Optimally, this would be done via invocation of `ICommunicationListener` on all instances. This would make a great SF feature. For NSB it would be a question of "aside from SF, is this a feature that could be used with the platform as a whole". Assuming you have a ServiceControl, would you be able to perform the same action with endpoints running on SF (or anywhere else for that matter).

**Comment by SeanFeldman** [comment]
That request has already been made :) https://feedback.azure.com/forums/293901-service-fabric/suggestions/13714473-ability-to-stop-disable-services-without-removing

**Comment by ChristianJensen** [comment]
@SeanFeldman Would it be recommendable to host a management NSB endpoint in the same process as our Gateway service NSB endpoint and send control messages to this management NSB endpoint to start/stop the Gateway NSB endpoints across all nodes in our SF cluster? How would we guarantee all management NSB endpoints would receive the control messages across all nodes?

**Comment by SeanFeldman** [comment]
@ChristianJensen hosting the management in the same process as another endpoint could lead to the  management going down as a result of processing endpoint shutting down due to a critical error.

**Comment by ChristianJensen** [comment]
@SeanFeldman Yeah, good point. Is there any recommended approach to solving this challenge with the current stacks and tool sets?

**Comment by SeanFeldman** [comment]
@ChristianJensen probably not under this issue as it would solely focus on hosting NSB with SB (BTW, partially addressed with a sample for Stateful services [here](https://docs.particular.net/samples/azure/azure-service-fabric-routing/)). And this would probably be something on the platform level, not just a specific technology.

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers this would seem to be covered by https://docs.particular.net/samples/azure/azure-service-fabric-routing/

**Comment by SeanFeldman** [comment]
Not quite @SimonCropp 
The mentioned sample represents 1 out of 3 possible options.

**Comment by SimonCropp** [comment]
@SeanFeldman cool. can you find someone in the @Particular/azure-maintainers to submit a PR

**Comment by SeanFeldman** [comment]
👍

**Comment by SimonCropp** [comment]
@SeanFeldman who will be working on this?

**Comment by SeanFeldman** [comment]
It will be worked by the SF task force (part of the https://github.com/Particular/PlatformDevelopment/issues/1112).

**Comment by SimonCropp** [comment]
closing this since it is already tracked in plat dev
