### ISSUE TITLE
Feedback: Heartbeat Plugin

### ISSUE THREAD

**Issue by stimms** [Particular/docs.particular.net#2329]
Page: /servicecontrol/plugins/heartbeat.md

Documentation correctly warns about not installing an old version of the plugin but the correct name of the nuget package (ServiceControl.Plugin.Nsb5.Heartbeat) is not apparent without looking in the page version drop down.

**Comment by gbiellem** [comment]
Thanks @stimms  - good point. 
We'll add a table showing the correct nuget to use by NSB version in that section
