### ISSUE TITLE
Feedback: Centralized file-based routing - FileBasedRouting

### ISSUE THREAD

**Issue by joseph991229** [Particular/docs.particular.net#2350]
Page: https://docs.particular.net/nservicebus/messaging/file-based-routing

So, filebaserouting do not support "Message"?

**Comment by SzymonPobiega** [comment]
@Joseph991229 do you refer to the note that this feature is not fully supported?

**Comment by SimonCropp** [comment]
@joseph991229 hoping you could clarify you question a little. see @SzymonPobiega question above
