### ISSUE TITLE
Custom routing sample active/inactive routes not working properly

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2352]
The custom routing sample is not working properly: https://docs.particular.net/samples/routing/custom/

### Inactive route still used

* Start all instances
* Exit sales-1
* Send multiple commands via Client
* Messages are still send round robin

Expected sending only to active route.

### When no active routes sending command fails:

* Start and stop all instances so that subscriptions are configured
* Start Client
* Send command
* Failure because no there are instances

Expected round robin between inactive routes

Active/passive logic must be fixed or removed.

//cc: @SzymonPobiega

**Comment by vahid8261** [comment]
I am suing this sample to use automatic routing. No subscriber is receiving events they subscribe to when using this sample code for automatic routing.  Please let me know how can we fix this ?

**Comment by weralabaj** [comment]
@ramonsmits @SzymonPobiega is that issue still relevant or has it been addressed?

**Comment by ramonsmits** [comment]
@weralabaj Not sure, I see that @SzymonPobiega made this commit 2616eb8309e5ec98f98d050cbdc6c101e66ec7e5 so probably it is.

**Comment by weralabaj** [comment]
@ramonsmits just run the sample now

> When no active routes sending command fails:

After starting Sales-1 and Sales-2 seems the messages are handled in the round-robin fashion. 

> Inactive route still used

Behaves as you described. Some messages are queued for sales-2 and get picked up by it after restarting. However, isn't that the expected behaviour?

**Comment by SzymonPobiega** [comment]
I removed the failure detection to make the sample more clear and focused: https://github.com/Particular/docs.particular.net/pull/2503
