### ISSUE TITLE
There's no migration guide for IWantQueuesCreated 

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#2355]
This interface was obsoleted in v6 but there's no migration guide for it.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers can u chime in here?

**Comment by danielmarbach** [comment]
We currently have https://docs.particular.net/nservicebus/upgrades/5to6/extension-seams#queue-creation which is indeed very scarce. I'll send in a PR
