### ISSUE TITLE
Feedback: Step by Step Sample - NServiceBus Samples

### ISSUE THREAD

**Issue by wyldebill** [Particular/docs.particular.net#2361]
Page: https://docs.particular.net/samples/step-by-step/?

For version 6.x of this page, under the Server section, there appears to be some copy from the version 5.x documentation.  The line that contains "The dependency injection system (which supports constructor or property injection) injects the IBus instance" is incorrect as version 6.x uses the new IMessageHandlerContext instead of the IBus property.

**Comment by ramonsmits** [comment]
Thanks for the feedback @wyldebill
