### ISSUE TITLE
Typo error: Management using PowerShell - NServiceBus

### ISSUE THREAD

**Issue by nfdias** [Particular/docs.particular.net#2370]
Page: https://docs.particular.net/nservicebus/operations/management-using-powershell#usage

There seems to be a typo here:

_If the module isn't available a restart the Windows session may be required for this change to to take effect._

I'm not an English native speaker but I believe the following is correct:

_If the module isn't available a restart to the Windows session may be required for this change to take effect._

Regards

**Comment by ramonsmits** [comment]
@nfdias thanks for reporting, it will be corrected via https://github.com/Particular/docs.particular.net/pull/2371

**Comment by nfdias** [comment]
There is still a typo in the end where it says:

for this change **to to** take effect.
