### ISSUE TITLE
RabbitMQ: what guide?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2373]
this page
https://docs.particular.net/nservicebus/rabbitmq/cluster

has 

> This capability was removed in Version 3.0 for the reasons stated in the guide. 

and 

> This approach is recommended when using the NServiceBus RabbitMQ transport. For more details, see the guide.

what "guide". can we have a link?

**Comment by SimonCropp** [comment]
ping @Particular/rabbitmq-transport-maintainers

**Comment by adamralph** [comment]
@SimonCropp both references to the guide refer to the link at the beginning of the page:

![image](https://cloud.githubusercontent.com/assets/677704/21939601/716d697e-d9b8-11e6-9268-03192f5ffddc.png)

Should we repeat the hyperlink?
