### ISSUE TITLE
Using Data Distribution using NServiceBus

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#2375]
In a discussion earlier today with @DavidBoike and @udidahan and others in the unconference session, @udidahan mentioned that Data Distribution is a different style of architecture. 

Step 1: Add a disclaimer in the sample: 
https://docs.particular.net/samples/routing/data-distribution/
https://docs.particular.net/nservicebus/azure/data-distribution

~~Step 2: Come up with a general guidance for the comparison on both.~~ *Covered by #2410*

cc / @SzymonPobiega

**Comment by SzymonPobiega** [comment]
@indualagarsamy @udidahan here's the issue where we discussed the subject: https://github.com/Particular/NServiceBus/issues/3495#issuecomment-197751542. TL;DR is that in Azure transports for NSB 5 there was a possibility of doing data distribution. The sample is there to show how the same thing can be done when they upgrade to NSB 6. The https://docs.particular.net/nservicebus/azure/data-distribution page already mentions that NSB's not a data distribution tool but I agree we can make this disclaimer more explicit and add it also to the sample.

**Comment by udidahan** [comment]
I suggest opening up a new issue to cover the creation of the architectural guidance.

**Comment by DavidBoike** [comment]
Raised #2410 to cover the data distribution guidance.

**Comment by DavidBoike** [comment]
Raised #2411 to review the content of the Azure data distribution article.
