### ISSUE TITLE
Feedback: Managing Instances via PowerShell - ServiceControl

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/docs.particular.net#2376]
Page: https://docs.particular.net/servicecontrol/installation-powershell

This documentation is very poor. I thought, OK, perhaps loading the module into a PowerShell session and performing a `get-help -Full <ServiceControl_cmdlet>` would get me more detailed information. Alas, no, it's even more scant than what's available on the website. And what's worse is the website doesn't even detail all the available parameters for the various cmdlets; so I'm left to wondering exactly what all those various parameters are, and then when performing `get-help -Full`, how they might all be used.

For an enterprise-class product, there's really no excuse for this. I don't have time to go reverse engineering source code (if that's even possible in this case--I haven't looked) to discover how these scripts work. As a paying customer, I shouldn't have to do this. If this software were FOSS, well, I wouldn't have a leg to stand on; but I have work to do. (I'm not completely obtuse--I can translate a lot of these parameters back to what I've seen in the UI and various configuration files--but if I were a new user or DevOps engineer and new to deploying ServiceControl, I would be in trouble.)

**Comment by weralabaj** [comment]
Hi @fourpastmidnight, thank you for taking the time to provide this feedback. It's really useful for us!

As for addressing your concerns. I was considering listing all parameters in the documentation, but that might get outdated and become confusing pretty quickly. On the other hand we make sure that all the parameters have descriptions and other required metadata in code, so seems using built-in PS functions makes more sense.

Do you think it'll be enough to provide tips in the documentation on how to obtain the data you mentioned? Please, see here https://github.com/Particular/docs.particular.net/pull/2378 and let me know how that works for you.

**Comment by fourpastmidnight** [comment]
I agree documentation _could_ get out of date on the website, but I would counter that 1) this is the nature of software and 2) since this software is paid software, I expect things like this to be documented. Now, I do have a few suggestions that might help.

First, `sc-help`, I believe, already does what you suggest in #2378. But, when looking at the help for individual PowerShell cmdlets, little to no help was provided. Parameter descriptions are missing; enum parameters do not document the allowable values, no examples of use, etc.

When I write PowerShell scripts to be used by others, I use PowerShell Doc Comments to document my scripts and script modules. Now, I think you guys are using actual cmdlets written in C# in Dll's loaded by the PowerShell environment via `import-module`. If that's the case, then see [this MSDN article](https://msdn.microsoft.com/en-us/library/bb525433(v=vs.85).aspx) about how to create an XML cmdlet help file for documenting cmdlets. I'm sure you could write an XSLT or use some other mechanism to take this file and display it nicely on your website, too, killing two birds with one stone. No one likes to write documentation; _I_ don't like writing documentation; but I do it. Because sooner or later, I'm the same person who needs help. Oh, and I like to think I'm being a professional about what I deliver to my colleagues. I expect nothing less from software that I (or my organization) pays for. (BTW, MS has gotten pretty bad at this, too (worse than ever before, since ASP.Net Core has arrived on the scene), but I don't believe that's an excuse nor a model to be followed.)

I hope that I can expect to see better, more helpful and complete descriptions for using the cmdlets in the near future.

**Comment by weralabaj** [comment]
> First, sc-help, I believe, already does what you suggest in #2378. 

Just to clarify, are you referring to my comment in the PR or did you also have a look at [the changes in files](https://github.com/Particular/docs.particular.net/pull/2378/files#diff-d2d3f21194d6108972a7c66fe5231c4eR50)?

Either way my thinking was that `get-help [ServiceControl Management command]` gives you high-level info on what parameters are available (including possible enum values, which you mentioned are missing):
<img width="643" alt="ex1" src="https://cloud.githubusercontent.com/assets/7335079/21983076/9a4e3ede-dbef-11e6-9d98-940d38a9502b.PNG">

and `get-help [ServiceControl Management command] -parameter *` gives you description, etc.:
<img width="653" alt="ex2" src="https://cloud.githubusercontent.com/assets/7335079/21983080/9fe51188-dbef-11e6-88ee-80b195164a22.PNG">

so I just wanted to point readers to those two commands specifically.


> But, when looking at the help for individual PowerShell cmdlets, little to no help was provided. Parameter descriptions are missing; enum parameters do not document the allowable values, no examples of use, etc.

Examples of use are described in more detail in the [following section](https://docs.particular.net/servicecontrol/installation-powershell#cmdlets-and-aliases-examples) of the same article.

It'd be really helpful if you could say what commands you executed (did you try those mentioned above?), and what information is missing (e.g. are we missing descriptions to only some of the commands? do we need more examples of usage? would another documentation format be easier to read?).

**Comment by fourpastmidnight** [comment]
I apologize, naming the offending cmdlet would've been helpful. The offending cmdlet is `New-ServiceControlInstance`. I also need to look more closely at the commits behind #2378, I didn't have a chance to fully review it this morning.

I just discovered something that may be the problem! I was using the Windows PowerShell ISE to view the help content in a window. When viewing the help in the ISE window (equivalent to `get-help -showwindow`' the detailed information is not being displayed. Running `get-help -full <cmdlet>` displays most of the information I expected to see (except possible enum values are still not displayed, e.g. for `-Transport`).

I expect to see full help displayed when viewing it in the window in the PowerShell ISE as other cmdlets do. Also, this command is invalid: `get-help -full -showwindow` because the parameters belong to different parameter sets.

I do appreciate you looking into this!! Thank you.

**Comment by fourpastmidnight** [comment]
I also now see the enum values in the general syntax above....it's really hard to see (which explains why I keep missing it) and it would be more helpful to have that information in the parameter description, too (e.g. for `-Transport`).

**Comment by gbiellem** [comment]
@fourpastmidnight thanks for pointing this out.  Seems you have uncovered a bug for us. We do have an external XML help file for the PS module but it is not being included in the MSI install.  I'll correct that and also review the PS help content

**Comment by fourpastmidnight** [comment]
Awesome, thanks so much!!

**Comment by gbiellem** [comment]
@fourpastmidnight ServiceControl 1.34 has been released. It contain the updated help files

**Comment by fourpastmidnight** [comment]
@gbiellem Wow, that looks great. I especially found illuminating, the acceptable range of ports for ServiceControl. I expected it to be 0 - 65535 (in lieu of any documentation)--granted, 0 doesn't make must sense, but not being able to specify a port above 49151 was not expected; and so it's great that this documentation is readily available via the PowerShell help.

Thanks so much for getting these changes in place!!
