### ISSUE TITLE
Inconsistent behaviour of top level menus

### ISSUE THREAD

**Issue by adamralph** [Particular/docs.particular.net#2380]
I'm not sure exactly which click sequences do what, but the expanding/collapsing behaviour seems inconsistent. Note how sometimes only the menu item being clicked expands, leaving other menu items expanded, and sometimes it collapses the other menu items.

<img src="https://cloud.githubusercontent.com/assets/677704/22012471/7966c97a-dc94-11e6-847b-bb2cb425db2a.gif" width="268" />

**Comment by SimonCropp** [comment]
@adamralph this should be in the docsengine repo

**Comment by SimonCropp** [comment]
duplicate of https://github.com/Particular/DocsEngine/issues/213
