### ISSUE TITLE
Align top level menu items across SI, SP, and SC

### ISSUE THREAD

**Issue by adamralph** [Particular/docs.particular.net#2381]
*From https://github.com/Particular/OptimizeTrialExtensions/issues/127#issuecomment-273045215*

<img src="https://cloud.githubusercontent.com/assets/677704/22011989/22375f7c-dc92-11e6-985c-97e2708b850d.png" width=146 />

<img src="https://cloud.githubusercontent.com/assets/677704/22012002/31a469aa-dc92-11e6-855e-b5bf2561f9e5.png" width="130" />

<img src="https://cloud.githubusercontent.com/assets/677704/22012013/4091a824-dc92-11e6-9e54-e727f408bafb.png" width="129" />

---

For reference, these are the items below to the top level in each:

<img src="https://cloud.githubusercontent.com/assets/677704/22012732/e608d4a0-dc95-11e6-85c6-8cc28e75c3db.png" width="209" />

<img src="https://cloud.githubusercontent.com/assets/677704/22012741/f25cf5e2-dc95-11e6-952a-b2a00ac0684c.png" width="224" />

**Comment by adamralph** [comment]
@Particular/serviceinsight-maintainers @Particular/servicecontrol-maintainers thoughts?

**Comment by WojcikMike** [comment]
I think that being more consistent might make the experience better. I like the change

**Comment by mikeminutillo** [comment]
I agree with the problem statement. What does the solution look like? We don't really have intro content for SC.

**Comment by adamralph** [comment]
SP's "Introduction" node looks shaky. It has "Installation" under it, where SC has "Installation" under "Configuration".

Perhaps we should put all the third level (e.g. "Installation") and fourth level nodes into a single list, group them into appropriate second level nodes (e.g. "Configuration") and then pull them apart again into the top level nodes (i.e. SI/SP/SC)?

**Comment by WilliamBZA** [comment]
Is this big enough to require a TF?

**Comment by SimonCropp** [comment]
from my perspective "the best menu structure for the given product context" trumps "we want it to be consistent". having said that i dont think much thought went into the current structure for the products so i am happy for @Particular/servicecontrol-maintainers and @Particular/serviceinsight-maintainers to restructure on what they think is the best menu and if they happen to be consistent that is good as well.

@WilliamBZA no i dont think it needs a TF

**Comment by HEskandari** [comment]
Generalizing everything under Installation, Introduction and Configuration, here's how it will look. Note that I have moved the pages onto appropriate sections as I saw fit. Please modify as you seem fit.

The 'Getting started' in SI is the same page as the product landing page. All the other products also have a similar page that contain an overview of the product.

### ServiceInsight
  - Installation
    - License information
  - Introduction
    - Managing Errors and Retries
	- Sequence Diagram
	- Application Invocation
	- Logging
	- Data not available
	
### ServicePulse
  - Installation
    - Installation
	- Install in IIS
  - Introduction
    - Endpoints and Heartbeats
	- Failed Messages
	- Retrying Failed Messages
	- Archived Messages
	- Pending Retries
	- Custom Checks
	- Redirects
	- Events
  - Configuration
    - Hosting
	- Monitoring Endpoints
	- Troubleshooting
	
### ServiceControl
  - Installation
    - Installation
	- Installing Silently
	- Managing via Powershell
	- Cluster Deployment
  - Introduction
    - Data Expiration
	- Capacity Planning
  - Configuration
    - Settings
	  - Overriding the host identifier
	  - RavenDB Location
	  - Configure the URI
	  - Logging
	  - Forwarding Queues
	- Integration
	  - Using ServiceControl Events
	  - Heartbeat Plugin
	  - CustomChecks Plugin
	  - SagaAudit Plugin
	- Troubleshooting
    - Security
	- Optimizing use in different environments
	- Expose Data via RavenDB Studio 
	- Non-Priviledged Account
	- Compacting RavenDB

The 'Getting started' in SI is the same page as the product landing page. All the other products also have a similar page that contain an overview of the product. Also note that SI at the moment doesn't have a Configuration section, but we might add that in future.

**Comment by adamralph** [comment]
A couple of observations:

- I'm not sure that "Introduction" is the best term for the top level section. Introduction to what? Perhaps "Usage"?
- I'm not sure everything under the previous SC "Management" should go into "Configuration". E.g. compacting RavenDB doesn't sound like configuration.

I'm finding it quite nice to play around with the levels in this spreadsheet, which allows you to sort by any of the columns: https://docs.google.com/spreadsheets/d/16N9bDzfBQO1ofnQejTalkjWfooCz30pRjofd3qWq7xY/edit#gid=0

**Comment by weralabaj** [comment]
We could use "overview" instead of "introduction"? that would be consistend with other sections

@HEskandari do you want to take care of it?

**Comment by distantcam** [comment]
"Features"?

**Comment by HEskandari** [comment]
@distantcam "Feature" could be applied to some, but not all of what's under SI, e.g. "Data not available" is not really a feature, unless moved/changed.

**Comment by adamralph** [comment]
We discussed this in the @Particular/serviceinsight-maintainers sync this morning and we think it may be better to withdraw this since the value of aligning the menu structure across the three products seems to be low. We would like to improve the SI menu structure but we can take care of that separately. Any objections?

**Comment by weralabaj** [comment]
not on my side :)
