### ISSUE TITLE
Create doco and sample for native ASQ integration

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#2389]
Since this soon will be possible:

https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/160

**Comment by weralabaj** [comment]
@Particular/azure-maintainers is that issue relevant? can you take care of it in the near future?

**Comment by andreasohlund** [comment]
I'll try to get this done next week

**Comment by Scooletz** [comment]
FYI The ASQ `7.1` has been staged for release and it's highly likely that it'll be published next week @andreasohlund

**Comment by andreasohlund** [comment]
The doco PR is merged and I'm starting to think that a sample is overkill?

To demo you would just use the code snippet in the docs and "paste a JSON string in the message body in Storage Explorer".

**Comment by SeanFeldman** [comment]
Can be converted into doco 😉

**Comment by weralabaj** [comment]
@andreasohlund is that much simpler than ASB (https://docs.particular.net/samples/azure/native-integration-asb/ and https://docs.particular.net/nservicebus/azure-service-bus/native-integration)?
If similar, then might make sense to have a sample, for the sake of consistency if nothing else ;)

**Comment by andreasohlund** [comment]
It would be a bit simpler, just a single "receiver" project that has the custom unwrapper configured, then just a instruction to:

1. Open ServiceBus Explorer or you toll of choise
2. Paste this JSON in as a new message and notice how the endpoint process the message

That said I agree that it make sense to have a sample for consistency. Will send a PR

**Comment by SimonCropp** [comment]
@andreasohlund not worth a sample
