### ISSUE TITLE
Guidance on data distribution

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#2410]
In a [Lisbon unconference session](https://github.com/Particular/Lisbon2017.Unconference/issues/24), we talked about data distribution being a different style of architecture that is not best handled using asynchronous messaging, and adjusting our docs site to make that clear.

#2375 covers adding a warning disclaimer.

This issue revolves around developing general guidance for the comparison of messaging and data distribution, which could be used as a link target within the disclaimers created by #2375.

**Comment by SimonCropp** [comment]
@DavidBoike this would seem larger than what can be worked on under docs alone. please raise a plat dev issue
