### ISSUE TITLE
Azure "data distribution" article has issues

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#2411]
The Azure section contains an article called [Data distribution](https://docs.particular.net/nservicebus/azure/data-distribution) but it's got some issues:

* The [V6 version](https://docs.particular.net/nservicebus/azure/data-distribution), which is (currently) default, doesn't really say much _at all_ and then links to the other sample, which is not even an Azure sample. As it stands now, the V6 version of the page doesn't provide much value and is pretty confusing to someone searching for this type of content.
* The [V5 version](https://docs.particular.net/nservicebus/azure/data-distribution?version=core_5) has two small code snippets, that do not use the Azure NuGet packages at all. It's unclear what would lead you to do this.

Moreover, the content does not address the hidden context behind why it should exist, which was raised in comments by @yvesgoeleven (https://github.com/Particular/docs.particular.net/pull/2407#issuecomment-277432827) and @SeanFeldman (https://github.com/Particular/docs.particular.net/pull/2407#issuecomment-277470603) when I proposed deleting it. If that context is valid, it should be added to the article.

Also ping @SzymonPobiega @indualagarsamy

**Comment by SeanFeldman** [comment]
A warning has been added to the content.
Need to review this doco.

**Comment by SeanFeldman** [comment]
Moved to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/503.
