### ISSUE TITLE
Feedback: Custom Recoverability Policy - NServiceBus

### ISSUE THREAD

**Issue by outofcoolnames** [Particular/docs.particular.net#2412]
Page: https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy
Hi,
There is a spelling error on the tooltip text on the DelayedDeliveriesPerformed property of NServiceBus.Transport.ErrorContext
![tooltip text on delaydeliveriesperformed](https://cloud.githubusercontent.com/assets/6042780/22701081/8eab2954-ed54-11e6-97cb-744570bb16d1.jpg)
Class definition:
`// Summary:
        //     Number of delayed deliveries performed so fat.
        public int DelayedDeliveriesPerformed { get; }`
I'm guessing this should be "Number of delayed deliveries performed so far."

**Comment by DavidBoike** [comment]
Hi @outofcoolnames, thanks for reporting this! I raised a pull request to fix this in the NServiceBus core here: https://github.com/Particular/NServiceBus/pull/4462
