### ISSUE TITLE
Document how we handle connections to SC from endpoints

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#242]
* What happens if SC can be contacted 

* How to change the default address

https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl.Plugin.Shared/ServiceControlBackend.cs#L60

**Comment by mauroservienti** [comment]
@andreasohlund 

> What happens if SC can be contacted

Do you mean "can't"?
What does the `circuitBreaker.Failure(ex);` does?

> How to change the default address

add a setting called: `ServiceControl/Queue`, correct? is documented here: http://docs.particular.net/servicecontrol/plugins#how-the-location-of-servicecontrol-queue-location-is-determined

**Comment by andreasohlund** [comment]
Yes can't

> What does the circuitBreaker.Failure(ex); does?

It will trigger the circuit breaker and if a .Success hasn't been invoked within X seconds it will trigger and perform the registered action (killing the endpoint IFAIK)

>add a setting called: ServiceControl/Queue, correct? is documented here:

Correct

**Comment by mauroservienti** [comment]
> It will trigger the circuit breaker and if a .Success hasn't been invoked within X seconds it will trigger and perform the registered action (killing the endpoint IFAIK)

so this is the only thing we need to add doco for.

**Comment by andreasohlund** [comment]
Seems like it

**Comment by mauroservienti** [comment]
done, don't know who and when :-), but done.
