### ISSUE TITLE
Clarify requirements of SagaAudit plugin

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#2423]
Saga Audit requires on audit queue. There's no mentioning of it in the documentation page and the snippet shown [here](https://docs.particular.net/servicecontrol/plugins/saga-audit).

Connects to Particular/ServiceControl.Plugin.Nsb6.SagaAudit#22

**Comment by weralabaj** [comment]
@HEskandari can you address this issue? Seems to me that simply adding a Note/Warning with one or two sentences should be enough?

**Comment by HEskandari** [comment]
I think it depends on the outcome of the referenced SagaAudit issue. At the moment it is silently ignored, but it will change based on the agreement in Particular/ServiceControl.Plugin.Nsb6.SagaAudit#22

**Comment by weralabaj** [comment]
Awesome, could you make a note in the https://github.com/Particular/ServiceControl.Plugin.Nsb6.SagaAudit/issues/22 to update docs once it's decided one way or another?

**Comment by SimonCropp** [comment]
@Particular/servicecontrol-maintainers please submit a PR if you still feel this is important
