### ISSUE TITLE
Add doco for Transaction settings such as DoNotWrapHandlersExecutionInATransactionScope

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#243]
Currently we have a few settings around controlling transactions:
- Turning Distributed Transactions on / off
- The ability to turn off having a transaction scope for message handlers
- The ability to turn transactions off

```c#
Configure.Transactions.Advanced(t =>
            {
                t.DisableDistributedTransactions();
                t.DoNotWrapHandlersExecutionInATransactionScope();
            });      
Configure.Transactions.Disable();
```

**Related Posts:**
https://groups.google.com/forum/#!topic/particularsoftware/SoxeC4RwLlg
http://stackoverflow.com/questions/22334782/nservicebus-4-0-duplicate-messages/22431951#22431951

also reference https://nservicebus.desk.com/agent/case/3795

**Related issue:** https://github.com/Particular/NServiceBus/issues/1863

**Comment by mauroservienti** [comment]
@johnsimons I agree, fixing the API should be the way to go, but it is a long process, should we document the above while we discuss the API changes?

**Comment by SimonCropp** [comment]
seems to be done here http://docs.particular.net/nservicebus/messaging/transactions
