### ISSUE TITLE
"Avoiding partial updates" section of Transport Transaction page in the wrong place

### ISSUE THREAD

**Issue by bording** [Particular/docs.particular.net#2446]
The "Avoiding partial updates" section of the core v5 [Transport Transactions](https://docs.particular.net/nservicebus/transports/transactions?version=core_5#avoiding-partial-updates) page shouldn't be a top-level section, because it is only relevant for the "Transport transaction" mode. In fact, the text even says "In this mode there is a risk of partial updates", which makes me believe this was moved out at some point without revising the text.

This should be moved back under the Transport Transactions mode section, and the notes about not being relevant TransactionScope mode become redundant.

**Comment by SzymonPobiega** [comment]
@bording It is applicable to all levels below TransactionScope, so it is similar (in scope of applicability) to the outbox. That's why it is a top level item. But I agree that the intro sentence is probably effect of bling copy-paste. I'll fix it.

**Comment by SzymonPobiega** [comment]
@bording addressed by https://github.com/Particular/docs.particular.net/pull/2454

**Comment by bording** [comment]
@SzymonPobiega The only level below TransportTransaction is "Transactions Disabled" so I don't really see how that's relevant there. 

Also, if you look at the snippet's showing TransportTransaction mode.
