### ISSUE TITLE
Verification of smoke tests

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2448]
Currently, any maintainer group that releases one of the packages also submits a documentation PR.

@Particular/azure-maintainers group assumes that doco PR work also includes smoke testing. 

Questions:

1. How does it work for other maintainer groups?
1. How can we improve the process to ensure smoke testing is addressed w/o the need of @Particular/docs-maintainers to chaise other maintainers to get the answer?

**Comment by weralabaj** [comment]
@SeanFeldman not sure what you're after here. Generally, when reviewing PRs for upgrading packages we ask if smoke testing has been done, from time to time we remind people to do it, some remember about it, some not ;) 

> How can we improve the process to ensure smoke testing is addressed w/o the need of @Particular/docs-maintainers to chase other maintainers to get the answer?

I think it's a matter of habit, and after a few reminders people remember to do this without intervention.

Does that answer your question?

**Comment by SeanFeldman** [comment]
Azure maintainers took a different approach. We decided that our doco updates always assume smoke testing. Not sure about other groups.

**Comment by weralabaj** [comment]
@SeanFeldman we'll get there one day, I hope, with everybody :D
