### ISSUE TITLE
Update Powershell cmdlets parameters data

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#246]
from @udidahan - 

> I also don’t know what parameter to pass to Get-NServiceBusMSMQMessage to make it work. Documentation is lacking:
> http://docs.particular.net/NServiceBus/managing-nservicebus-using-powershell
>  
>    “Get-NServiceBusMSMQMessage -  Displays all messages in a queue

**Comment by mauroservienti** [comment]
@dannycohen given:

> Get-NServiceBusMSMQMessage is also not interesting since we now have SC.

Can we close this one?

**Comment by mauroservienti** [comment]
closing, re-open if necessary
