### ISSUE TITLE
Core settings

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2464]
One of the ways NSB Core communicates information with downstream projects is via SettingsHolder, a.k.a. `Settings`. Settings are accessible via `Features` and public APIs such as transports. We don't have any documentation on what "public" information is available via `Settings`.

Some examples:

```c#
settings.EndpointName()
Settings.LogicalAddress()
settings.InstanceSpecificQueue()
settings.GetOrCreate<EndpointInstances>()
```

Would it help if the settings / settings keys would be documented @Particular/nservicebus-maintainers ?

**Comment by timbussmann** [comment]
strongly against documenting the settings-keys, that would be terrible from an API versioning perspective. The extension method could be documented though.

**Comment by SeanFeldman** [comment]
@timbussmann I'll clarify it - the intent is for all the extension methods that are already public, but only available if you happened to know those. Suggested documenting relates to those.

**Comment by weralabaj** [comment]
@timbussmann have you just volunteered for this work? :)

**Comment by timbussmann** [comment]
@weralabaj nope, I already got enough doc issues on my plate.

**Comment by danielmarbach** [comment]
@weralabaj If you help me to find a good location to put the doco I'm happy to do it

**Comment by weralabaj** [comment]
@danielmarbach Looking at it now, and I'm having a hard time coming up with something sensible. Various settings could be used in completely different contexts, so IMO it doesn't make much sense to have them all in one place. 

We could just go over the settings and ensure they are documented somewhere, as some are not mentioned at all. So it'd probably make the most sense to decide on a case by case basis? That way when somebody discovers a method they can at least search for it in doco?

e.g. settings.EndpointName() should be mentioned here https://docs.particular.net/nservicebus/endpoints/specify-endpoint-name
settings.InstanceSpecificQueue() in building custom transport?
settings.LogicalAddress()... no idea, honestly, custom features?

**Comment by SeanFeldman** [comment]
Settings are often used for to extend NSB or with downstream to get information from the Core.
Having these sprinkled in various documents doesn't sound like a good approach imo.

**Comment by weralabaj** [comment]
@SeanFeldman given that they're related to so many different areas, and also some are declared as extension methods IMO it doesn't make sense to bundle them together either. also some of them are relevant only for people creating custom transport, persistence, some are more relevant for the "wider" public

If you could propose a specific draft, then it'd be easier to come up with something sensible.

**Comment by SeanFeldman** [comment]
@weralabaj what's the point of a draft if there's no agreement on the way of grouping the doco?
My point was that it's all going to be scattered in various documents. So when looking at the `Settings` and asking "what can I get out of it" when implementing X", it will not be helpful that individual methods are covered by N various documents.

**Comment by weralabaj** [comment]
@SeanFeldman the point of having a draft is to see what you're proposing. IMO if we have everything in one place, then some settings will be hard to understand as there's no context in which they'll be used. One setting is for persistence, another for transport, yet another for endpoint name.

But I'm happy to be proven wrong, hence the idea of having a draft.

**Comment by SeanFeldman** [comment]
Sounds like you've outlined a possible structure - a page for those settings broken down by categories settings are used in. Either way, I don't have the capacity right now, but can give it a shot a bit later.

**Comment by SimonCropp** [comment]
this cant be on a single page since there is no way to properly version the content when we mix downstreams

**Comment by SimonCropp** [comment]
please submit a PR when u sort out the issues and decide on a structure
