### ISSUE TITLE
Document lack of support for MSMQ Public Queues

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#2470]
We had a customer asking about MSMQ Public Queue Support. Looking through the code it looks as if we do not support this as we always translate addresses so that they contain `\private$\`. When I searched for this on the doco site I couldn't find reference to it. I don't know if [Remote Queues](https://docs.particular.net/nservicebus/msmq/#remote-queues) are the same thing as Public Queues?

On V5:
- Converting an address to an MSMQ path is done with [MsmqUtilities.GetFullPath()](https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs#L24)
- Which calls in to [MsmqQueueCreator.GetFullPathWithoutPrefix()](https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Transports/Msmq/MsmqQueueCreator.cs#L76) which adds the `\private$\` section to the path

On V6:
- This all happens in the [MsmsqAddress.FullPath](https://github.com/Particular/NServiceBus/blob/support-6.0/src/NServiceBus.Core/Transports/Msmq/MsmqAddress.cs#L82) property.

**Comment by mikeminutillo** [comment]
Can the @Particular/nservicebus-maintainers take a look at where to document this please?

**Comment by indualagarsamy** [comment]
@mikeminutillo - Public Queues require Active Directory. Also there are additional constraints on the domain controller as well for public queues to be working right. We have never had support for public queues, since the original days of NServiceBus.

**Comment by andreasohlund** [comment]
>This https://docs.particular.net/nservicebus/msmq/ would be a good place to document the limitation.

👍 

Question is what reason do we state for not supporting?

In the past the reason was that MSMQ didn't support remote transactional receives but that is no longer true since MSMQ 4.0. So what reason do we give?

**Comment by SzymonPobiega** [comment]
@andreasohlund some time ago I tried to setup remote receives on AWS but failed with DTC problems. Remote receives require DTC instances on both ends. 

As for public queues, I don't have any experience.

**Comment by andreasohlund** [comment]
>Remote receives require DTC instances on both ends.

Agreed, but we require DTC anyway for the default MSMQ+SqlServer combo so this would not be a reason to not support public/remote queues?

**Comment by SzymonPobiega** [comment]
@andreasohlund I am not saying we should not support it. I think it would actually be a great thing to do in my opinion (if it worked). Just saying I tried and failed.

In fact this would be an amazing tool for DevOps because it would allow easier endpoint decommissioning.

**Comment by timbussmann** [comment]
should we raise an issue in nsb/pdev to investigate this?

**Comment by weralabaj** [comment]
@andreasohlund @timbussmann @SzymonPobiega can you decide on the PoA for this issue? does that belong here or should be moved to PlatDev?

**Comment by andreasohlund** [comment]
Adding the doco section seems to be the immediate action? (The question still stands regarding what reason to give)

@timbussmann go ahead and raise a platdev issue if you feel strongly for the centralized queue idea

**Comment by weralabaj** [comment]
> The question still stands regarding what reason to give

Easiest would be to not give any, just say it works like this ;)

**Comment by weralabaj** [comment]
Fixed in https://github.com/Particular/docs.particular.net/pull/2516
