### ISSUE TITLE
Add session ID message to distributor doco to make it SEO discoverable and add info from GG post to it

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2472]
>I wrote a simple application following the sample of nServiceBus standalone Distributor , where I have one sender, one distributor, and two workers. The application works as charm when sending messages until suddenly I start seeing errors in log file saying then the distributor stops dispatching messages to handlers.

    NServiceBus.ReadyMessageSender SKIPPED Ready message for message with id 3c226a0e-8b8a-4b0b-a29d-a72200a04815 because of sessionId mismatch. MessageSessionId 3d2f76fc-f969-4d8e-b2df-322c67b174c4, WorkerSessionId 7ba4cff7-5040-4a33-bcb0-1029e248049c

> If I run the same code with one of the workers , all goes fine, and no interrupt when handling messages.
any advice ?

https://groups.google.com/forum/#!topic/particularsoftware/x-hEX1_UgjY

> If you look at the log level of the log event then you will see that it either is level DEBUG or INFO. These messages can safely be ignored.
> This happens when the distributor and worker are out of sync due to a restart. When a worker starts it lets the master know its capacity so that the master only sends as many work items as it can concurrently process.

**Comment by weralabaj** [comment]
@ramonsmits can you handle this as you have all the context?

**Comment by SimonCropp** [comment]
@ramonsmits please submit a draft PR with the above
