### ISSUE TITLE
Feedback: DataBus - NServiceBus

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2475]
Page: https://docs.particular.net/nservicebus/messaging/databus/

You should mention which data types are allowed for the DataBus property (only `byte[]`, I think) and refer to https://docs.particular.net/samples/pipeline/stream-properties/ for transmitting larger amounts of data using a stream, i.e., without having to keep all the data in the memory.

**Comment by weralabaj** [comment]
Thank you @Niklas-Peter for your feedback, I'll try to address your comments asap.

**Comment by SimonCropp** [comment]
@Niklas-Peter this should now be addressed

**Comment by Niklas-Peter** [comment]
Yes, it is. Thanks
