### ISSUE TITLE
Feedback: Profiles For NServiceBus Host - NServiceBus Host

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2477]
Page: https://docs.particular.net/nservicebus/hosting/nservicebus-host/profiles

Section "Dependent profile behaviors": Is there a mismatch between the description and the sample code? The description mentions `IWantTheEndpointConfig`, but it is not in the code. In general, maybe you can improve the understandability of this section.

Section "Persistence": There are words in the table, which do not represent profile names.

**Comment by indualagarsamy** [comment]
Hi @Niklas-Peter - Thanks for letting us know. Yes, you're right. We will get this addressed.

**Comment by sfarmar** [comment]
@weralabaj has a pull request in progress for this https://github.com/Particular/docs.particular.net/pull/2496

**Comment by weralabaj** [comment]
@Niklas-Peter I've made a series of updates to the whole NServiceBus Host section, please see if now it's more reader-friendly and accurate. Once again, thank you for your feedback!

**Comment by Niklas-Peter** [comment]
In https://docs.particular.net/nservicebus/hosting/nservicebus-host/ `AsA_Server` is still used.

**Comment by sfarmar** [comment]
@Niklas-Peter Can I ask what is the issue with that?

**Comment by Niklas-Peter** [comment]
@sfarmar Nowhere in the documentation is mentioned what it means.

**Comment by sfarmar** [comment]
@Niklas-Peter got it, I'll create a PR to fix it

**Comment by indualagarsamy** [comment]
@seanfarmar - any updates on this?

**Comment by seanfarmar** [comment]
@indualagarsamy I've dropped the ball on this, will get this done in the next couple of days

**Comment by seanfarmar** [comment]
Update: I'm investigating why the Roles API was not made obsolete

**Comment by weralabaj** [comment]
@seanfarmar any updates?

**Comment by seanfarmar** [comment]
Had a call with @andreasohlund yesterday and the outcome is:
- Roles need to be obsoleted (I'l create a PR in the host for that)
- Remove any references to AsA_Server and AsA_Client from our documentation 
- Add a comment in the documentation about send only endpoints.

**Comment by seanfarmar** [comment]
Docs [PR(https://github.com/Particular/docs.particular.net/pull/2680)

**Comment by seanfarmar** [comment]
[Docs PR](https://github.com/Particular/docs.particular.net/pull/2680) merged.

@Niklas-Peter can I ask you to review please? :-)

**Comment by Niklas-Peter** [comment]
Should be OK. The aspects I criticized are fixed.
