### ISSUE TITLE
Feedback: Transport Transactions - NServiceBus

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2482]
Page: https://docs.particular.net/nservicebus/transports/transactions

Section "Transport transaction - Receive Only"
> Distributed transactions do not guarantee atomicity for an outside observer. For example outgoing messages might be dispatched and processed by some other endpoint before changes to the database get committed.

Which transport does that apply to? As far as I know, MSMQ will only really send the messages when committing the transaction. Or do you refer to failures during commit, that are not considered by 2PC, or the delay during commit of a distributed transaction, because some resources will commit faster than others?

**Comment by indualagarsamy** [comment]
@Niklas-Peter -  Thank you for your feedback. 

That statement you mentioned is in the "Consistency Guarantees" in the "Transaction scope (Distributed transaction)" and not "Transport transaction - Receive Only". 
This mode is only applicable for MSMQ and SqlTransport. See: [table for the transports' supported transaction modes](https://docs.particular.net/nservicebus/transports/transactions#transactions-transaction-levels-supported-by-nservicebus-transports).

However, when using DTC in MSMQ, you are absolutely right, the explanation is confusing from a MSMQ transport perspective. You are right, MSMQ will only send the messages when committing the transaction. Let me check this with @Particular/sqlserver-transport-maintainers and see if this was added to address a concern when using Sql Server transport.

**Comment by Niklas-Peter** [comment]
Yes, of course, I copied the wrong headline.

**Comment by MarcinHoppe** [comment]
This paragraph tries to convey an inconvenient truth about distributed systems in general and applies to both MSMQ and SQL Server transports running with the DTC:

Under the DTC consuming the incoming message, writing data to the data store and sending outgoing messages are atomic **from perspective of the message handler**. For external endpoints (e.g. endpoints that consume these outgoing messages) operations may not appear atomic. For example, the outgoing messages may be delivered to their respective input queues later than the moment in time when written data is available for reading in a shared data store.

I agree we should probably make this paragraph clearer. I will keep this issue open and will come up with an example to better illustrate the concept.

**Comment by tmasternak** [comment]
@MarcinHoppe AFIK one of the production scenarios that comes to my mind is:
 1. We have two endpoints A and B, both using MSMQ and SqlServer for persistence
 2. Endpoint A uses DTC to
  a. Process incoming message `m_a`
  b. Create a saga instance `s`
  c. Publish an event `e`
 3. On transaction commit we have no control over order and delays between commits in resource managers (MSMQ and SqlServer in our case) i.e. there is not atomic visibility of changes
 4. Let's assume that MSMQ commits first. Than it is possible that
 5. Endpoint B subscribed to `e` receives it and immediately sends `m_b` to Endpoint A that tries to modify `s`
 6. The `s` does not exist yet (or to be more precise the transaction creating it is `Prepared` but not yet `Committed`). Here the exact behavior will vary based on transaction isolation level and (might?) on the resource manager used. E.g. SqlServer in `Read Committed` isolation level will block the read `s` transaction until the pending `s` is committed. In Oracle with `Snapshot` read `s` will return null instead. 

NOTE: in this case a retry mechanism in NSB can be used to cater for the scenario described above i.e. delay the `m_b` processing.

**Comment by weralabaj** [comment]
@MarcinHoppe @tmasternak do you have time to look into that?

**Comment by MarcinHoppe** [comment]
I will have a look at it this week.

**Comment by MarcinHoppe** [comment]
I took a stab at explaining this with #2688.

**Comment by MarcinHoppe** [comment]
Resolved by #2688
