### ISSUE TITLE
Feedback: MSMQ Transport Configuration - MSMQ Transport

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2484]
Page: https://docs.particular.net/nservicebus/msmq/transportconfig

> If all the logical data stores (transport, user data, saga data) use the same physical store there is no escalation to Distributed Transaction Coordinator (DTC).

vs.

https://docs.particular.net/nservicebus/transports/transactions
> MSMQ will escalate to a distributed transaction right away since it doesn't support promotable transaction enlistments.

**Comment by SzymonPobiega** [comment]
Thanks @Niklas-Peter! Fixed.

**Comment by Niklas-Peter** [comment]
Do you have a source for this statement:

> MSMQ will escalate to a distributed transaction right away since it doesn't support promotable transaction enlistments.

**Comment by SzymonPobiega** [comment]
@andreasohlund do you know the source?

**Comment by andreasohlund** [comment]
http://stackoverflow.com/questions/12462321/why-is-this-simple-msmq-transaction-escalated-to-dtc
