### ISSUE TITLE
Feedback: Routing topology - RabbitMQ Transport

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2486]
Page: https://docs.particular.net/nservicebus/rabbitmq/routing-topology

> Bindings are created to ensure that base type events also are moved to the exchanges for the derived types when they are published.

Is it not the other way around? derived types events also are moved to the exchanges for the base types

In section "Publishing using Direct Routing Topology" it is not mentioned at all how polymorphic dispatch is realized.

**Comment by WojcikMike** [comment]
@Particular/rabbitmq-transport-maintainers please respond

**Comment by bording** [comment]
@Niklas-Peter Looks like you've identified a couple problems with that page. You're correct that the relationship between the exchanges is the other way around.

Regarding the direct routing topology, it does support polymorphic dispatch through how the routing key is constructed (with the already mentioned on the page caveat with interfaces), so the page should mention that as well.

While looking over that I've identified a few other things that could be improved, so we'll try and get that fixed up ASAP.

Thanks for the feedback!

**Comment by weralabaj** [comment]
@bording have those issues been addressed?

**Comment by bording** [comment]
I've started working on my revision to the page that will address this in #2669, but I haven't had time yet to get back and finish it up. I hope to have that done this week though.
