### ISSUE TITLE
Feedback: Accessing data via NHibernate persistence - NHibernate Persistence

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2488]
Page: https://docs.particular.net/nservicebus/nhibernate/accessing-data

I am not familiar with NHibernate. 
When accessing `context.SynchronizedStorageSession.Session()`: Which connection string is this session based on, because you can provide multiple connection strings, one per storage type?

**Comment by SzymonPobiega** [comment]
@Niklas-Peter this API uses the saga connection string.

**Comment by indualagarsamy** [comment]
@SzymonPobiega - is there anything in the document that we can add to clarify this better?

**Comment by SzymonPobiega** [comment]
@indualagarsamy I reviewed the page but could not find a better way to express this.

**Comment by weralabaj** [comment]
added as a note in https://docs.particular.net/nservicebus/nhibernate/accessing-data, thanks @Niklas-Peter for your feedback, really appreciated!
