### ISSUE TITLE
Feedback: Child Containers - NServiceBus

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2492]
Page: https://docs.particular.net/nservicebus/containers/child-containers?

Does the sample code in this article really belong to the text in the article?

UPDATE:
OK, probably the documentation is correct. However, the configured component in the sample code will only be scoped to a unit of work if it is resolved during message processing (not anywhere outside handlers/sagas), because NServiceBus automatically creates the child container / unit of work when starting message processing. Right?

UPDATE 2:
However, if the child container is automatically created for message processing and if `InstancePerCall` makes the object a singleton inside the child container, why does `InstancePerUnitOfWork` exist?

**Comment by indualagarsamy** [comment]
@Niklas-Peter - Thank you for all your feedback regarding our documentation. 

@Particular/container-maintainers - Can you have a look and see how we can clarify this better?

**Comment by boblangley** [comment]
@Niklas-Peter Thanks for raising this. You are correct, the sample code was not showing the intended `DependencyLifeCycle` for the the article. It should be `InstancePerUnitOfWork`.
