### ISSUE TITLE
Feedback: ServiceControl Endpoint Plugins - ServiceControl

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2495]
Page: https://docs.particular.net/servicecontrol/plugins/

> Endpoint with plugins installed that cannot communicate to ServiceControl will shut down.

Maybe you should clarify, that ServiceControl must not be running all the time. Instead, only the queues must exist. Else it would destroy a lot of a bus architecture's robustness.

**Comment by indualagarsamy** [comment]
@Niklas-Peter - you are right. When the service control queue isn't configured but the plugins are installed, the code will throw the following exception:

"You have ServiceControl plugins installed in your endpoint, however, the Particular ServiceControl queue is not specified.
Please ensure that the Particular ServiceControl queue is specified either via code (config.HeartbeatPlugin(servicecontrolQueue)) or AppSettings (eg. <add key=""ServiceControl/Queue"" value=""particular.servicecontrol@machine""/>)."

We can make the note more clear for sure.

**Comment by boblangley** [comment]
I have updated the wording of the document's warning to be:

> Endpoint with plugins installed will shut down when the ServiceControl queue setting has not been set or when the plugin is unable to communicate with the configured ServiceControl queue.
