### ISSUE TITLE
Feedback: Steps, Stages and Connectors - NServiceBus

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2508]
Page: https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors

> There currently is no way to provide custom Pipelines, Stages, Fork Connectors, or Stage Connectors. The existing elements can be customized. The examples below are included here for completeness.

Does it mean that the code listings on this page, e.g., for `CustomStageConnector :  StageConnector<IOutgoingLogicalMessageContext, IOutgoingPhysicalMessageContext>` are valid, but would not do anything, because they can not be registered? 

> The existing elements can be customized.
How?

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers  - can you review this documentation and see if it can be improved?

**Comment by danielmarbach** [comment]
Hi @Niklas-Peter 

Right now you can only replace existing elements. I will update the doco to make that clearer and ping you on this issue. Thanks for the feedback

Daniel

**Comment by indualagarsamy** [comment]
@Niklas-Peter - Thanks again for your feedback. @danielmarbach has addressed this and the documentation is now updated to reflect that.
