### ISSUE TITLE
Doco on transports and persistence isn't structured the same

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2512]
The transports are having their own heading. SHouldn't they be structure the same as the other components?

![image](https://cloud.githubusercontent.com/assets/152998/23546261/0cbea318-ffff-11e6-9f20-64a191528d9d.png)

**Comment by weralabaj** [comment]
@ramonsmits the problem is that there's much more content on transports and we don't support that much nesting in menu to make it readable

**Comment by SimonCropp** [comment]
this is by design since the each transport has enough content and depth pertaining to it that they warrant a higher level menu

**Comment by ramonsmits** [comment]
It still feels incorrect imho. It looks as if it incorrectly categorized but is this is all intensional then feel free to close this issue.

**Comment by SimonCropp** [comment]
@weralabaj  thinking some more about this i think we should move the persistences up. i think the current doco in persistence is fairly poor. and if we properly backfilled all the content it would be worth moving up one level. i know i intend to add significantly more doco to the sql persistence.

i also think the selection persistence, like transports, is significant decision that has long term repercussions on the system design and possible technical debt. this makes them more important than container, logging and serializer selection.

so with https://github.com/Particular/DocsEngine/issues/297 in mind i think after it is done we do the same for persistences

**Comment by weralabaj** [comment]
fair enough, although it should look differently than current main menu items (organized around products)

**Comment by SimonCropp** [comment]
@weralabaj yeah my OCD doesnt like that either but i think it results in a better menu structure. and the result wont be ambiguous

**Comment by SimonCropp** [comment]
will be handled in the docs engine
