### ISSUE TITLE
Review setting up SC with SI doco experience

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#2531]
We had a customer go through this and a number of things were not obvious fro reading the existing doco. 

From the [GG post](https://groups.google.com/d/msg/particularsoftware/Nlf9o_8OMlU/MejTASpjDwAJ):

- If audits aren't enabled, SC will show no endpoints because it uses the contents of the queues to populate rather than the existence of the queues.So if the queues are empty, it looks like there are no endpoints. 
- The docs say that every endpoint gets a built in audit log. Apparently that's not true, it's not per endpoint, and it's not by default.
- The docs say that a central audit log is 'also' required. Apparently, this is the same audit queue that every endpoint should be configured to use. 
- The audit queue is actually 'consumed' by ServiceControl which means it will be removed from the audit queue and stored in service control in what seems to be a raven database, and deleted after so much time.

**Comment by boblangley** [comment]
Added a PR to address these observations: #2653, awaiting @mikeminutillo's review/refinement.

**Comment by weralabaj** [comment]
@boblangley since the PR was merged I believe this issues has been addressed. If something is missing, please reopen.
