### ISSUE TITLE
How to add reply redirect sample to docs?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2537]
@Particular/docs-maintainers The following class demonstrates how to override the host when doing a `context.Reply`. Is this something we want to add as a sample on docs? If so, any suggestions on how to position this? Rationale behind it is that you can have message in the error queue, that get retried via ServicePulse. During processing the Reply is using an obsolete host. Instead of the message being stuck in the outgoing queue the message will now be send to a new host.

/cc: @danielmarbach 

```c#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using NServiceBus;
using NServiceBus.Logging;
using NServiceBus.Pipeline;
using NServiceBus.Transport;

/// <example>
/// Register this via:
/// 
///    var pipeline = endpointConfiguration.Pipeline;
///    pipeline.Register( behavior: new ReplyRedirectBehavior(), description: "Maps a reply to address to a different machine.");
/// 
/// </example>
public class ReplyRedirectHostBehavior : IBehavior<IOutgoingReplyContext, IOutgoingReplyContext>
{
    static readonly ILog Log = LogManager.GetLogger<ReplyRedirectHostBehavior>();

    readonly Dictionary<string, string> HostMappings = new Dictionary<string, string>
    {
        {"ZOLDER", "HOSTB"}
    };

    public Task Invoke(IOutgoingReplyContext context, Func<IOutgoingReplyContext, Task> next)
    {
        IncomingMessage incoming;
        if (context.TryGetIncomingPhysicalMessage(out incoming))
        {
            var headers = incoming.Headers;
            if (headers.ContainsKey(Headers.ReplyToAddress))
            {
                var replyToAddress = headers[Headers.ReplyToAddress];

                var address = replyToAddress.Split('@');
                string newHost;

                if (address.Length > 1 && HostMappings.TryGetValue(address[1], out newHost))
                {
                    address[1] = newHost;
                    var newReplyToAddress = string.Join("@", address);
                    Log.WarnFormat("Mapping reply address from {0} to {1}.", replyToAddress, newReplyToAddress);
                    headers[Headers.ReplyToAddress] = newReplyToAddress;
                }
            }
        }
        return next(context);
    }
}
```

**Comment by indualagarsamy** [comment]
@ramonsmits - If the main premise of this code is the following:

>Rationale behind it is that you can have message in the error queue, that get retried via ServicePulse. During processing the Reply is using an obsolete host. Instead of the message being stuck in the outgoing queue the message will now be send to a new host.

then it can be achieved by using the redirects feature in ServicePulse. See https://docs.particular.net/servicepulse/redirect

**Comment by danielmarbach** [comment]
@indualagarsamy I think there is a misunderstanding here. Redirect feature would need the messages to fail first, being processed by SC and then redirected. The approach above reroutes replies when you do a reply.

**Comment by SimonCropp** [comment]
does it need to be a new sample? or will a single doco page suffice?

**Comment by SimonCropp** [comment]
bump

**Comment by SimonCropp** [comment]
please submit a PR if u ever resolve the above questions

**Comment by ramonsmits** [comment]
@indualagarsamy What @danielmarbach said, it needs to fail first. In the current form the reply ends up in the TDLQ.

Or is ServiceControl/Pulse editing the `NServiceBus.ReplyToAddress` too? While thinking about this maybe this should result in a feature for ServicePulse/Control.

@SimonCropp I don't understand your question.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers given this would fall under your ownership what are your thoughts? do u want this as a sample?

**Comment by timbussmann** [comment]
not sure why this specific behavior would qualify for a sample? I think in most user related scenarios, you would just send to a specific address instead of using this.

**Comment by ramonsmits** [comment]
@timbussmann 

> Rationale behind it is that you can have a message in the error queue, that gets retried via ServicePulse. During processing the Reply is using an obsolete host. Instead of the message being stuck in the outgoing queue the message will now be sent to a new host.

So the issue here is that SC isn't patching the reply address that is obsolete and not routable. These end up in the TDLQ, as we currently don't ingest TDLQ with SC.

> I think in most user related scenarios, you would just send to a specific address instead of using this.

Not sure how I should interpret this statement/question.

**Comment by timbussmann** [comment]
> So the issue here is that SC isn't patching the reply address that is obsolete and not routable. These end up in the TDLQ, as we currently don't ingest TDLQ with SC.

still don't see how the sample alone improves this situation for users?

> Not sure how I should interpret this statement/question.

as user, I think you would be unstuck much easier to just use session.Send with a given option.RouteToDestination(<hardcoded or computed value>) instead?

**Comment by ramonsmits** [comment]
@timbussmann so, you would want to change the handlers that does the `context.Reply(..)` to `context.Send(message, options)` when you use some kind of dictionary to make the handler now responsible to determine which if the reply needs to go to a different queue? And you want to do this on all handlers that might do a reply?

That is not the responsibility of the handler but part of the infrastructure thus part of the pipeline.

This sample makes sure that messages JIT rerouted to the correct host even though the information on the message received contains obsolete information.

**Comment by timbussmann** [comment]
@ramonsmits I'm concerned about the scenario this sample solves, not the implementation itself.
You're pointing towards a bug in SC which should be fixed in SC and users should not have to use such behaviors for the correct behavior. For users not affected by this SC bug, this sample doesn't seem to add any value and that's why I'm questioning this issue. I'm happy to propose this as a workaround for affected users, but there must be a better way than having this just as an arbitrary sample.

For every other scenario where you would want to override the host when replying, I'm saying that you most likely already know where the reply should go and direct send seems to be more straight forward. Besides the SC bug, this just seems like a very niche scenario.

**Comment by ramonsmits** [comment]
@timbussmann It is not a bug in SC at all. I'll close this as this is leading nowhere and I'll put it on my blog.
