### ISSUE TITLE
Feedback: 'DataBus'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2538]
Feedback for 'DataBus' https://docs.particular.net/nservicebus/messaging/databus/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/databus/index.md

ping @Particular/nservicebus-maintainers 

> If the outbox feature in NServiceBus is enabled, the message will be removed from the incoming queue, but it might not have been processed yet.

If I look especially at the updated Outbox pattern image, I do not know how this could happen.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers any update on this?

**Comment by timbussmann** [comment]
Yeah that statement seems to be a bit weird. Maybe @dvdstelt can give us some insight as he wrote this? Currently, I'd prefer to just remove that bullet point.

**Comment by dvdstelt** [comment]
The text changed over time in the PR, but I'm not really sure where my thoughts were atm. Created PR for it.

**Comment by SimonCropp** [comment]
@Niklas-Peter thanks for the feedback. @dvdstelt removed the questionable doco
