### ISSUE TITLE
Feedback: 'Configure delayed retries'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2541]
Feedback for 'Configure delayed retries' https://docs.particular.net/nservicebus/recoverability/configure-delayed-retries

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/configure-delayed-retries.md

ping @Particular/nservicebus-maintainers 

Merge section Custom Retry Policy with https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy.

In https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy I think you can remove the section beginning with, because it contains not more information than the preceding sections:

> If the Default Recoverability Policy just needs to be tweaked for MyBusinessException then a policy might look like:

**Comment by indualagarsamy** [comment]
@Niklas-Peter - thanks for your comment. Yes, I agree. It's good idea to link the section to the custom recoverability policy section.

**Comment by SimonCropp** [comment]
@danielmarbach do u have capacity to handle this one?

**Comment by danielmarbach** [comment]
@SimonCropp I started looking into this. I see one major drawback of consolidating this. https://docs.particular.net/nservicebus/recoverability/configure-delayed-retries is for all NSB Versions while https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy is only for v6 and later. By consolidating it we make the custom recoverability page unnecessary complex with partials. I'd vote for closing this unless someone has a good idea how to move forward.

**Comment by SimonCropp** [comment]
@danielmarbach agreed on that point.

thoughts on this one?

> In https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy I think you can remove the section beginning with, because it contains not more information than the preceding sections:

**Comment by danielmarbach** [comment]
@Niklas-Peter thanks for your valuable feedback. We restructured slightly the custom recoverability page in https://github.com/Particular/docs.particular.net/pull/2649. Hope know it is a bit clearer
