### ISSUE TITLE
Feedback: 'NHibernate Persistence Saga concurrency'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2543]
Feedback for 'NHibernate Persistence Saga concurrency' https://docs.particular.net/nservicebus/nhibernate/saga-concurrency

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/nhibernate/saga-concurrency.md

ping @Particular/nhibernate-persistence-maintainers

> A lock is created when fetching the saga instance from the database and is held till the end of the transaction blocking other threads that try fetching that particular saga.

If the row is locked anyway, why is additional optimistic locking needed at all?
Is it possible to switch to pessimistic-only locking for a saga?

**Comment by SzymonPobiega** [comment]
@Niklas-Peter Thanks for the feedback! I've added a section on customizing (or switching off) the optimistic concurrency: https://docs.particular.net/nservicebus/nhibernate/saga-concurrency#customizing-the-optimistic-concurrency-handling

**Comment by Niklas-Peter** [comment]
@SzymonPobiega Thanks.

Can you answer my first question, too?

**Comment by SzymonPobiega** [comment]
> If the row is locked anyway, why is additional optimistic locking needed at all?

It is not strictly necessary but since the cost is so small it is better to keep a single code path and not treat it as a special case in the persister.
