### ISSUE TITLE
Feedback: 'Child Containers'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2544]
Feedback for 'Child Containers' https://docs.particular.net/nservicebus/containers/child-containers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/containers/child-containers.md

ping @Particular/container-maintainers 
> remembering that transport messages can contain multiple "user defined messages"

After reading the link below I believed that a transport message contains exactly 1 logical message or is a "user defined message" not a logical message?
 
https://docs.particular.net/nservicebus/upgrades/4to5#obsolete-the-serializationsettings-properties-wrapsinglemessages-and-dontwrapsinglemessages

**Comment by mikeminutillo** [comment]
@Niklas-Peter you are correct that an endpoint running Version 5 and above will not send a transport message containing more than one logical message (which is the same thing as a "user defined message" in this context). 

These endpoints _can_ receive a transport message containing more than one logical message. This allows newer endpoints to integrate with endpoints running on NServiceBus Version 4 and below which can send multiple logical messages in a single transport message.
