### ISSUE TITLE
Feedback: 'Complex saga finding logic'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2546]
Feedback for 'Complex saga finding logic' https://docs.particular.net/nservicebus/sagas/saga-finding

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sagas/saga-finding.md

ping @Particular/nservicebus-maintainers 

You should refer to this note from https://docs.particular.net/samples/nhibernate/custom-mappings/
I had to learn it the hard way right now.

> Not adding a unique constraint can result in duplicate saga entities as the second insert will not fail when inserting the same value when multiple messages are processed concurrently referencing the same saga instance.

Is there a best practice for where to setup the custom constraints (not limited to UNIQUE constraints, but e.g., CHECK constraints, even if they might be slow) on a table generated by NServiceBus using NHibernate? I can not simply put in in an installer, because I have to make sure NServiceBus has already created the table when adding the custom constraint.

**Comment by mikeminutillo** [comment]
> Is there a best practice for where to setup the custom constraints (not limited to UNIQUE constraints, but e.g., CHECK constraints, even if they might be slow) on a table generated by NServiceBus using NHibernate? I can not simply put in in an installer, because I have to make sure NServiceBus has already created the table when adding the custom constraint.

I think the best place to put this code will be in a [feature startup task](https://docs.particular.net/nservicebus/pipeline/features#feature-startup-tasks). These are executed after the installers have run (so your tables should exist) but before the endpoint is started.

**Comment by mikeminutillo** [comment]
@Niklas-Peter did you end up creating a feature startup task for this?
