### ISSUE TITLE
Modify samples to use ESC to stop instead of any key

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2550]
Very often I run a sample and unintentionally the instance exits cause I pressed a key or the wrong key. It would be nice if we would choose to press the Escape key instead to exit the samples.

**Comment by SimonCropp** [comment]
@ramonsmits sounds good. submit a PR

**Comment by SimonCropp** [comment]
@ramonsmits no need for the issue. raise a PR when u get around to it
