### ISSUE TITLE
Feedback: 'Callback Changes in Version 6'

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2561]
Feedback for 'Callback Changes in Version 6' https://docs.particular.net/nservicebus/upgrades/5to6/callbacks

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/5to6/callbacks.md

ping @Particular/nservicebus-maintainers

> In Version 6 the callback handling on broker transports is no longer based on the machine host name. In order to continue using callbacks when using a broker transport, the endpoint needs to be uniquely addressable

When I read this paragraph, I assumed that all this (and the required configuration with `MakeInstanceUniquelyAddressable`) does not apply to MSMQ since MSMQ is not a broker transport. But it seems like this is not the case. If `MakeInstanceUniquelyAddressable` is not called on a MSMQ endpoint, trying to start the endpoint throws an exception with the following message:

> In order to use the callbacks feature you need to specify an endpoint instance ID via EndpointConfiguration.MakeInstanceUniquelyAddressable(string discriminator)

**Comment by danielmarbach** [comment]
@cremor I clarified the doco in https://github.com/Particular/docs.particular.net/issues/2569. Thanks again for raising it!
