### ISSUE TITLE
Feedback: 'Client side Callbacks'

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2562]
Feedback for 'Client side Callbacks' https://docs.particular.net/nservicebus/messaging/callbacks

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/callbacks.md

ping @Particular/nservicebus-maintainers

I think it would be good if this page would mention in what cases the NServiceBus.Callbacks package has to be referenced. The section "Prerequisites for callback functionality" would be good for this. Maybe even just copy the following paragraph from the [Callback Changes in Version 6](https://docs.particular.net/nservicebus/upgrades/5to6/callbacks) page:

> The NServiceBus.Callbacks package has to be referenced only by the requesting endpoint. The responding endpoint only need NServiceBus.Callbacks if it replies with int or enum types.

**Comment by timbussmann** [comment]
thanks for the feedback @cremor ! We changed the page in PR #2593 and I hope this addresses your comments. I'm going to close this but feel free to reopen in case you think I've missed something.
