### ISSUE TITLE
Feedback: 'ServiceControl Endpoint Plugins'

### ISSUE THREAD

**Issue by trygvelo** [Particular/docs.particular.net#2565]
Feedback for 'ServiceControl Endpoint Plugins' https://docs.particular.net/servicecontrol/plugins/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/plugins/index.md

When reading the "Connecting to ServiceControl" paragraph, I get the understanding that I MUST configure the "ServiceControl/Queue" in appSettings or (in code for version >= 6). Further down I read this:

"If ServiceControl is installed with a Windows Service name other than the default name then the convention based detection does not apply. In this scenario the configuration setting ServiceControl/Queue must be set to the correct queue name."

Ie. if defaults are used, no config has to be done since it will find the ServiceControl queue based on convention. I think this should be emphasized so that in many cases we don't have to add any config at all.

By the way, I just tested this in version 6 and it MUST be configured there to work. In version 5 it works without any config (code or appsettings) and it must use the default servicecontrol queue name by convention.

**Comment by SimonCropp** [comment]
@Particular/servicecontrol-maintainers can you have a look at this one?

**Comment by mikeminutillo** [comment]
@trygvelo thanks for your feedback.

As you have noted, we have intentionally moved away from the convention-based approach in V6 in favor of an explicit code API. I believe this is the only remaining section of documentation that talks about the convention based approach. I will remove this section and make it clear that the config-file approach doesn't work with V6.

**Comment by mikeminutillo** [comment]
This was updated when https://github.com/Particular/docs.particular.net/issues/2565 was merged. 

The updated version no longer refers to the zero-config approach.

https://docs.particular.net/servicecontrol/plugins/
