### ISSUE TITLE
Should this behavior that is writing message body to temp file in case of failure be added to the doco?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2579]
The following behavior writes the message body to a temp file in case pushing the message to the transport fails and the log level is set to DEBUG.

Example of what is logged:

> 2017-03-24 14:47:14.191 DEBUG WriteBodyToTempFolderOnTransmitFailureBehavior Transmit to transport failed. Body stored at: C:\Users\ramon\AppData\Local\Temp\tmp512C.tmp (4,194,334 bytes)

We currently have https://docs.particular.net/nservicebus/logging/message-contents but that isn't really useful as a generic way of doing diagnostics, required overiding the ToString and logs all messages not only the failed.

Would it have any value in adding this as a sample?

## Behavior

```c#
public class WriteBodyToTempFolderOnTransmitFailureBehavior : IBehavior<IOutgoingPhysicalMessageContext, IOutgoingPhysicalMessageContext>
{
    static readonly ILog Log = LogManager.GetLogger<WriteBodyToTempFolderOnTransmitFailureBehavior>();
    static readonly bool IsDebugEnabled = Log.IsDebugEnabled;

    public async Task Invoke(IOutgoingPhysicalMessageContext context, Func<IOutgoingPhysicalMessageContext, Task> next)
    {
        try
        {
            await next(context).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            if (IsDebugEnabled)
            {
                var path = Path.GetTempFileName();

                using (var writer = File.CreateText(path))
                {
                    await writer.WriteAsync("Example text as string").ConfigureAwait(false);
                }

                Log.Debug($"Transmit to transport failed. Body stored at: {path} ({context.Body.Length:N0} bytes)", ex);
            }
            throw;
        }
    }
}
```

## Registration

```c#
endpointConfiguration.Pipeline.Register(new WriteBodyToTempFolderOnTransmitFailureBehavior(), "Logs body in case of error");
```

**Comment by SimonCropp** [comment]
what value does this approach add over https://docs.particular.net/nservicebus/recoverability/subscribing-to-error-notifications  ?

**Comment by SimonCropp** [comment]
@ramonsmits see above comment

**Comment by ramonsmits** [comment]
@SimonCropp Isn't that the message that is received? This is writing the body of the message that is being send.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers thoughts on this since you would own this doco

**Comment by bording** [comment]
@ramonsmits What scenario are you thinking of where this would be useful? Seems like it would a lot of trouble to add a behavior and turn on DEBUG logging to catch a send failure. What would you be able to do with the message body at that point anyway?

**Comment by weralabaj** [comment]
@ramonsmits @Particular/nservicebus-maintainers can you please sync and make a decision regarding this?

**Comment by timbussmann** [comment]
I'm with @bording here. Not sure why you would want to log outgoing messages? This scenario is handled by retries quite well I'd say? Also this won't work reliably e.g. when you're trying to send two messages and the first one succeeds while the second fails. This would write the second outgoing message but not the first.

This sounds like a far too specific behavior to be something we should demo to users.

**Comment by weralabaj** [comment]
@ramonsmits based on the feedback, I think the correct location would be personal/company blog rather than official doco. If you disagree and want to discuss this further, please reopen the issue.
