### ISSUE TITLE
IAAS: Guidance on persistence technologies deployed on IAAS

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#258]
To start: I have limited experience in this space as it is mostly about understanding the products and less about azure. But I think it would be interesting to learn how supported persistence tech behaves in a large virtual environment (no DTC probably main challenge)

- SQL, Oracle, Raven, Mongo all come to mind here

**Comment by SimonCropp** [comment]
seems this one is dead. if you want to have a go at in the future please add some sample content to a PR that we can evolve
