### ISSUE TITLE
Are Transport/Persistence upgrade guides at the wrong top-level section?

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#2595]
dedicated categories have been introduced for persistence and transport options. But the upgrade guide for the specific packages are located under NServiceBus/Upgrade Guides which seems inconsistent.

**Comment by SimonCropp** [comment]
@timbussmann sounds good. @Particular/docs-maintainers any objectiosn or r we ok with @timbussmann doing a PR?

**Comment by SimonCropp** [comment]
@timbussmann please submit a PR. no need for this issue anymore

**Comment by timbussmann** [comment]
@SimonCropp an open issue would help me to track this work item as I won't be able to raise a PR right away.
