### ISSUE TITLE
Transactions outside handlers - Feedback: 'Transport Transactions'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2608]
Feedback for 'Transport Transactions' https://docs.particular.net/nservicebus/transports/transactions

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/transports/transactions.md

ping @Particular/nservicebus-maintainers

1. MSMQ supports transactions for outgoing messages, e.g., for sending multiple messages. What is about RabbitMQ? It does not support atomic sends with receive, but that does not imply that it does not support a separate transaction only for the outgoing messages.

2. Is it possible to get transactionality for outgoing messages sent outside a handler, i.e., anyhwere in the application using IMessageSession? Using the MSMQ API directly, that should be possible, but how to do that using NServiceBus? Just wrap the send operations in a TransactionScope?

**Comment by mikeminutillo** [comment]
Hi @Niklas-Peter,

I'll get one of the @Particular/rabbitmq-transport-maintainers to chime in on your first question.

On the second one, you can wrap multiple NSB operations in a `TransactionScope` against MSMQ outside of a handler. Be sure to set `TransactionScopeAsyncFlowOption` to `Enabled` otherwise later operations may not be captured by the transaction scope.

**Comment by bording** [comment]
@Niklas-Peter RabbitMQ does not support any sort of transactional send behavior for multiple messages.  There is no way to roll back a successfully sent message in the event of a later failure. This is why the RabbitMQ transport doesn't support the `TransactionScope` or `SendsAtomicWithReceive` transaction modes. 

The approach @mikeminutillo mentioned that does work with MSMQ will not work for RabbitMQ. The send operations cannot enlist in the transaction, so If you roll back the `TransactionScope`, the messages will still have been sent.

**Comment by Niklas-Peter** [comment]
@bording @mikeminutillo 
> The approach @mikeminutillo mentioned that does work with MSMQ

Does this approach require TransportTransactionMode.TransactionScope in the configuration or can I use a lower setting and only use the explicit TransactionScope for the sending operations outside a handler?

**Comment by mikeminutillo** [comment]
@Niklas-Peter 

1. I believe this should work with a lower setting. The TransportTransactionMode affects the message receive behavior and it adds context that is utilized by the message dispatcher. In the case of MSMQ, if there is an ambient transaction scope during dispatch and you haven't explicitly requested Isolated Dispatch, the dispatch operation will enlist in the ambient transaction.

2. I haven't tried this but you could probably do it if you needed to. When a message is dispatched, NServiceBus will try to find a `TransportTransaction` object to pair it up with or create a new one if one is not found. This object is a container for whatever your native transport transaction type is. For MSMQ that would be `MsmqTransaction`. If you already have an `MsmqTransaction` instance you would create a `TransportTransaction`, add your MSMQ transaction to it, create a `SendOptions`, add the `TransportTransaction` to it, send the message with the send-options. 

I would advise against doing this though. It's much cleaner to use a transaction scope and it doesn't litter your code with MSMQ details (which is one of the advantages of using an abstraction like NSB in the first place). Additionally, if we change the way transactions are handled by the transport internally, your code will appear to work, even though the outgoing messages aren't getting enlisted in the transaction as expected.

**Comment by mikeminutillo** [comment]
@Niklas-Peter I believe the above comment answers your questions so I will close this issue. If you have any further questions, feel free to re-open this issue or better yet, raise them in our [Discussion Group](https://groups.google.com/forum/#!forum/particularsoftware)
