### ISSUE TITLE
Where is the assembly scanner?

### ISSUE THREAD

**Issue by dasjestyr** [Particular/docs.particular.net#2623]
Feedback for 'Assembly scanning' https://docs.particular.net/nservicebus/hosting/assembly-scanning

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/assembly-scanning.md

ping @Particular/nservicebus-maintainers

![image](https://cloud.githubusercontent.com/assets/3200529/24776315/0f3906ce-1ad5-11e7-99d3-54c781a2edbb.png)

This method seems to not exist. I did install the ravendb package. Using NSB 6.0

**Comment by mikeminutillo** [comment]
@dasjestyr this extension was added in 6.2 here https://github.com/Particular/NServiceBus/pull/4485

It was released about 2 weeks ago.

**Comment by dasjestyr** [comment]
Oh did I just completely gloss over those notes on the doc? My bad! Thanks
