### ISSUE TITLE
Feedback: 'Upgrade Version 6 to 6.2'

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2627]
Feedback for 'Upgrade Version 6 to 6.2' https://docs.particular.net/nservicebus/upgrades/6to6.2

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/6to6.2.md

ping @Particular/nservicebus-maintainers

Not really important, but to be complete you might mention that `EndpointConfiguration.ExcludeAssemblies()` is obsolete since 6.2.

Not related to this page, but if you want to change it in one push, the following pages still use the now obsolete API:
https://docs.particular.net/nservicebus/upgrades/5to6/assembly-scanning
https://docs.particular.net/nservicebus/lifecycle/ineedinitialization
https://docs.particular.net/nservicebus/hosting/assembly-scanning (only the second mention in "Exclude assemblies by wildcard")

**Comment by weralabaj** [comment]
@boblangley Do you have time to address it or should I look for replacement? ;)
