### ISSUE TITLE
Explain error when transport is in TransactionScope mode but database does not handle TransactionScopes

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#2638]
In SQL persistence, if the database does not support TransactionScopes but the transport has been configured to use TransactionScope mode the syncrhonized storage session adapter will throw an exception from the Enlist method.

This behavior needs to be documented.

**Comment by weralabaj** [comment]
@SzymonPobiega any context (e.g. link to the relevant discussion)? or is that only placeholder for yourself?

**Comment by SzymonPobiega** [comment]
Thanks @weralabaj . Yeah I created it as a reminder for myself but forgot the context already. Fortunately I managed to recall it.
