### ISSUE TITLE
Feedback: 'Azure Service Bus Transport'

### ISSUE THREAD

**Issue by qujck** [Particular/docs.particular.net#2640]
Feedback for 'Azure Service Bus Transport' https://docs.particular.net/samples/azure/azure-service-bus/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/azure/azure-service-bus/sample.md

ping @Particular/azure-maintainers

Hi, I don't mean to complain but the text on this page does not match the code - and as it's all new to me I can't fix it sorry.

**Comment by SeanFeldman** [comment]
Thank you @qujck
`UseSingleBrokerQueue` is irrelevant for the version 7 of the transport.
The `The Data in Azure Storage` section is plain wrong and should be "queues used in the sample".
Ironically, since creation of this sample, the portal has changed and that section makes no longer sense.

**Comment by SeanFeldman** [comment]
@qujck [this PR](https://github.com/Particular/docs.particular.net/pull/2646) should address the issue
