### ISSUE TITLE
Feedback: 'Azure Storage Persistence'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2642]
Feedback for 'Azure Storage Persistence' https://docs.particular.net/nservicebus/azure-storage-persistence/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-storage-persistence/index.md

ping @Particular/azure-maintainers 

 * [x] mentions `[Unique]` which is now obsolete https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/obsoletes.cs#L1328
 * [x] use a partial for the nuget content https://docs.particular.net/nservicebus/azure-storage-persistence/#enable-azure-storage-persistence

**Comment by Scooletz** [comment]
@SimonCropp When asking for

> use a partial for the nuget content

Do you meant the paragraph?

> First add a reference to the assembly that contains the Azure storage persisters. When working with NServiceBus Version 5 or lower this is done by adding a NuGet package reference to NServiceBus.Azure. For NServiceBus Version 6 and above the NuGet package reference is NServiceBus.Persistence.AzureStorage.

Do you propose that it should be written as two partials targetting different NSB versions?

**Comment by SimonCropp** [comment]
> targetting different NSB versions

Not exactly. targeting two different Azure Storage Persistence versions (ranges)

**Comment by Scooletz** [comment]
Thx for clarification.

**Comment by Scooletz** [comment]
Fixed by #2651
