### ISSUE TITLE
Feedback: 'Message routing'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2658]
Feedback for 'Message routing' https://docs.particular.net/nservicebus/messaging/routing#event-routing-native

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/routing.md

The section about event routing is misleading.
While multi-cast transport have native support for pub/sub, with core v6 changes, the legacy topology for ASB that was in the past capable of getting the information from the core, is now cannot access the info and subscribers **have to** [provide the publishers information using the routing API](https://docs.particular.net/nservicebus/azure-service-bus/publisher-names-configuration).

ping @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
@seanfarmar that sounds like the documentation is correct regarding v6 and should be adjusted for v5?

> subscribers have to provide the publishers information using the routing API.

(it's the transport specific routing api extension, not the general routing api)

> In this case the subscriber uses the APIs of the transport to create a route for a given subscribed message type.

**Comment by SeanFeldman** [comment]
Not sure what @seanfarmar would do, I would suggest to make a general comment to always look if a specific chosen transport has any special requirements 😃 

For example: from the ASB's 2 topologies, only one requires extra info.

**Comment by timbussmann** [comment]
oops, wrong github handle.

how about adding links to the transport specific doco pages which provide a custom API in that section?

**Comment by weralabaj** [comment]
> For example: from the ASB's 2 topologies, only one requires extra info.

@SeanFeldman I don't think core maintainers will always catch such nuances, so seems it'd make more sense to ensure downstream maintainers also review "general" pages from time to time?

**Comment by SeanFeldman** [comment]
@weralabaj no doubt about that. It does require coordination to ensure that there's a mutual understanding. For example, core's internal API that allowed ASB old topology to retrieve all subscribers was intentionally removed in v6 of Core and that's when probably doco needed to be updated. Who knows,  maybe after this discussion that decision will be reviewed 😉 

I'll update the doco.
