### ISSUE TITLE
Cloud / Azure navigation on Index and Menu

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#266]
1. Add a topic to the NServiceBus Index page for "Cloud hosting" (http://docs.particular.net/nservicebus)
* Add the topic to the menu as well (under NServiceBus)
* I suggest locating it under "Hosting"

![image](https://cloud.githubusercontent.com/assets/3889023/2535822/aa479508-b594-11e3-86aa-28bb8e109f3e.png)

Related to https://github.com/Particular/docs.particular.net/issues/156

**Comment by SimonCropp** [comment]
@yvesgoeleven @dannycohen are either of you going to do this?

**Comment by yvesgoeleven** [comment]
@SimonCropp I actualy thought I did, I'll look into it
