### ISSUE TITLE
Feedback: 'Using NServiceBus in an ASP.NET Core WebAPI Application'

### ISSUE THREAD

**Issue by ncarandini** [Particular/docs.particular.net#2662]
Feedback for 'Using NServiceBus in an ASP.NET Core WebAPI Application' https://docs.particular.net/samples/web/send-from-aspnetcore-webapi/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/send-from-aspnetcore-webapi/sample.md

ping @Particular/nservicebus-maintainers 

I think this page should be updated to .csproj

**Comment by MarcinHoppe** [comment]
The PR is ready for review: #2685.

**Comment by SimonCropp** [comment]
@ncarandini thanks for the feedback. this is now done
