### ISSUE TITLE
Sample: moving NHibernate persistence between environments

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#2677]
Our documentation about moving NH persister data between environments is very sparse:

> ### Generating scripts for deployment
> To create scripts, for execution in production without using the installers, run an install in a lower environment and then export the SQL structure. This structure can then be migrated to production.

We need a sample that would walk users through:

  1. Creating the database structure on development box using installers
  1. Scripting this database using tools like Visual Studio Schema Compare or Red Gate SQL Compare
  1. Deploying the database schema to a staging environment
  1. Adjusting endpoint configuration to run with reduced privileges and without installers
  1. Moving database schema and possibly migrating some data (subscriptions?) from staging to production

**Comment by MarcinHoppe** [comment]
One of the goals is to address pain points identified in #2473.

**Comment by SzymonPobiega** [comment]
Here's another way to approach it https://github.com/Particular/NServiceBus.NHibernate/pull/285

**Comment by SimonCropp** [comment]
@Particular/nhibernate-persistence-maintainers still working on this?

**Comment by MarcinHoppe** [comment]
Not at the moment.

**Comment by SimonCropp** [comment]
so given the current state of NH being considered legacy, is it worth investing time in?

**Comment by MarcinHoppe** [comment]
This would benefit our existing NH customers, too. Frankly, I have not seen a lot of demand for this (e.g. in support).

I am fine with closing this if other maintainers agree. /cc @Particular/nhibernate-persistence-maintainers

**Comment by SzymonPobiega** [comment]
I have no strong opinion either way.

**Comment by MarcinHoppe** [comment]
We have no shortage of bigger fish to fry. Closing for now.
