### ISSUE TITLE
Feedback: 'Understanding internal transactions and delivery guarantees'

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#2679]
Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/525

Feedback for 'Understanding internal transactions and delivery guarantees' https://docs.particular.net/nservicebus/azure-service-bus/understanding-transactions-and-delivery-guarantees

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-service-bus/understanding-transactions-and-delivery-guarantees.md

ping @Particular/azure-maintainers

I received feedback from an Italian prospective customer that this page is very hard to understand. Content wise is strategic and should be explained better.

**Comment by danielmarbach** [comment]
@mauroservienti please chime in here https://github.com/Particular/docs.particular.net/pull/2660

**Comment by SeanFeldman** [comment]
Considering there's an already opened issue for this documentation (issue https://github.com/Particular/NServiceBus.AzureServiceBus/issues/525), I'm going to close this one as a duplicate. Please see [PR](https://github.com/Particular/docs.particular.net/pull/2660) and comment there.

Thank you @mauroservienti
