### ISSUE TITLE
Feedback: 'Service Fabric Persistence Transaction Sharing'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2683]
Feedback for 'Service Fabric Persistence Transaction Sharing' https://docs.particular.net/nservicebus/service-fabric/transaction-sharing

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/service-fabric/transaction-sharing.md

ping @Particular/service-fabric-maintainers

It is not clear from the text why would a user create a custom transaction. Perhaps to highlight the significance of **not** enlisting into the existing transaction?

**Comment by SeanFeldman** [comment]
ping @Particular/azure-maintainers

**Comment by danielmarbach** [comment]
We state the following:

> When data needs to be persisted to a custom collection during handler or
saga execution, a new transaction should be created using the
StateManager property
of the incoming session.


Not clear enough?

**Comment by SeanFeldman** [comment]
In this case not really. Yes the doco says "When data needs to be persisted to a custom collection during handler or saga execution". It doesn't explain **why** a new tx needs to be created rather than participating in the existing one.

**Comment by danielmarbach** [comment]
By why you are referring to the fact that transactions should be short lived in SF? Do you think we should document that and back it up with external reading material?

**Comment by SeanFeldman** [comment]
Worth it IMO. This is not trivial material and even if we do MSFT's work, we'll do a giant favor to our customers.

**Comment by weralabaj** [comment]
@SeanFeldman @danielmarbach wouldn't it be easier to track if it was opened in one of the azure repos? otherwise, who I should contact re: this issue?

**Comment by SeanFeldman** [comment]
@weralabaj we'll discuss this in our maintainers call tomorrow and decide what to do with this one.

**Comment by SeanFeldman** [comment]
@Particular/azure-maintainers maintainers will handle it by slightly changing this doco

**Comment by SeanFeldman** [comment]
With the PR merged (https://github.com/Particular/docs.particular.net/commit/021473f2fd892e86a8af98d0399e84644b0eca09), closing this.
