### ISSUE TITLE
Feedback: 'Message routing'

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#2687]
Feedback for 'Message routing' https://docs.particular.net/nservicebus/messaging/routing

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/routing.md

ping @Particular/nservicebus-maintainers

Feedback from a user:
"The demo code using the routing API on this page:
https://docs.particular.net/nservicebus/messaging/routing

Shows that you can get a routing object by calling transportExtensions.Routing();
What's not clear to me is where the transportExtensions object comes from.
Can you please point me in the right direction?"

@SzymonPobiega can we modify snippets to make it clearer?

**Comment by SzymonPobiega** [comment]
I've extended the snippets to include `UseTransport`
