### ISSUE TITLE
Feedback: 'SQL Persistence' Pros/Cons vs NHibernate

### ISSUE THREAD

**Issue by boblangley** [Particular/docs.particular.net#2699]
@markgould wrote:

>Is there a document / write up about why one might want to use this over the NHibernate persistence? I like the idea of this as I'm not using NHibernate for anything else. It would be nice to see a pro/con list of why you should choose one over the other.

See https://github.com/Particular/NServiceBus.Persistence.Sql/issues/88

Feedback for 'SQL Persistence' https://docs.particular.net/nservicebus/sql-persistence/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sql-persistence/index.md

ping @Particular/sqlpersistence-maintainers

**Comment by weralabaj** [comment]
@boblangley seems like it's part of the [There is no documentation on how to make and educated choice for transport and persistence](https://github.com/Particular/PlatformDevelopment/issues/1252) issue, should we copy comment from here?

**Comment by weralabaj** [comment]
Copied comment to the existing issue.
