### ISSUE TITLE
Should all pages be listed as ones that need to be reviewed?

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2704]
Some pages do not change over time: upgrade guides.
Do they really need to appear in the [list of pages for review](https://docs.particular.net/review)?

![image](https://cloud.githubusercontent.com/assets/1309622/25735088/eb020c12-3125-11e7-8f43-ce5241a5a9a6.png)

@Particular/docs-maintainers thoughts?

**Comment by SzymonPobiega** [comment]
I think they should. Each time I read a piece of doco, I find ways to make them better, even if the changes are minor.

**Comment by SeanFeldman** [comment]
At some point polishing will stop, but the document will be ranked as not
updated for a long time. Almost as if there should be a way to exclude
specific documents from that list.

**Comment by weralabaj** [comment]
You can simply update the reviewed date, or ignore. Not sure what's the problem here?
