### ISSUE TITLE
Feedback: 'Configuring endpoints for monitoring'

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2716]
Feedback for 'Configuring endpoints for monitoring' https://docs.particular.net/servicepulse/how-to-configure-endpoints-for-monitoring

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicepulse/how-to-configure-endpoints-for-monitoring.md

ping @Particular/servicepulse-maintainers

This page should be updated for core version 6.

**Comment by boblangley** [comment]
@cremor Thanks, updates applied in https://github.com/Particular/docs.particular.net/commit/8053fccb6886993795228ee07e56187281a815e8#diff-e464ca61c8dda10aacf915b2089995a5
