### ISSUE TITLE
Document the 'PurgeOnStartup' configuration option

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2722]
I recently found the the `endpointConfiguration.PurgeOnStartup(true)` API. Since I implemented the same functionality for MSMQ using a `FeatureStartupTask` I was very happy to see this because it allows me to simplify my code.

But I wondered why I hadn't known about this API before, so I searched for it in your documentation. Seems like it is only mentioned in context of Azure Storage Queues and when building your own transport. Since this is a general configuration option that can be used with all transports, shouldn't it be documented somewhere that applies to all transports?

**Comment by weralabaj** [comment]
Thanks @cremor for catching this. I'll look into it and try to find a good place to mention.

**Comment by weralabaj** [comment]
I think one reason why we don't advertise it, is that's only for development environment, if you use that in production, you're asking for trouble ;)
Any idea where mentioning it would make sense then? In what scenario did you use it @cremor ?

**Comment by cremor** [comment]
I'm using it only for client endpoints which receive no other messages than change notifications. Since all data is reloaded on startup anyway I don't need to process all old change notification messages.

Initially I wanted to use `TimeToBeReceived` for this, but I wasn't able to because I'm using MSMQ in Transaction Scope mode.

**Comment by weralabaj** [comment]
@cremor see if you think this https://github.com/Particular/docs.particular.net/pull/2735 is a good place to mention it

**Comment by cremor** [comment]
LGTM
