### ISSUE TITLE
Feedback: 'Heartbeat Plugin'

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2723]
Feedback for 'Heartbeat Plugin' https://docs.particular.net/servicecontrol/plugins/heartbeat

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/plugins/heartbeat.md

ping @Particular/servicecontrol-maintainers 

Is the section "[Expired heartbeat messages forwarded to Dead letter queue](https://docs.particular.net/servicecontrol/plugins/heartbeat#expired-heartbeat-messages-forwarded-to-dead-letter-queue)" still relevant? Because according to [Upgrade Version 6 to 6.2](https://docs.particular.net/nservicebus/upgrades/6to6.2) this was changed in 6.2

**Comment by indualagarsamy** [comment]
Hi @cremor - you are right. The documentation needs to be updated to add the new behavior for TTBR messages.

**Comment by SzymonPobiega** [comment]
@Particular/msmq-transport-maintainers could you please take a look at this? I don't have enough context to be able to update the doco.

**Comment by indualagarsamy** [comment]
@SzymonPobiega - I'll have a go and create a PR for this.

**Comment by indualagarsamy** [comment]
@cremor - once again, thanks for your feedback on this. Sorry, it took a little while longer than expected to get to this. Hope the new clarifications help. Cheers.
