### ISSUE TITLE
Feedback: 'Introduction to NServiceBus: Sending a command'

### ISSUE THREAD

**Issue by zagnut999** [Particular/docs.particular.net#2729]
Feedback for 'Introduction to NServiceBus: Sending a command' https://docs.particular.net/tutorials/intro-to-nservicebus/2-sending-a-command/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/intro-to-nservicebus/2-sending-a-command/tutorial.md

```Also, it is a good practice to instantiate collection properties from a default parameterless constructor as shown above, so that you never have to deal with a potentially null collection.```
Should probably read something like this:
```Also, it is a good practice to instantiate collection properties from a default auto property as shown above, so that you never have to deal with a potentially null collection.```

**Comment by weralabaj** [comment]
Thanks @zagnut999 for your feedback ! We applied changes here https://github.com/Particular/docs.particular.net/pull/2732
