### ISSUE TITLE
Improve documentation for ServiceControl queue configuration with remote MSMQ

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2734]
I recently configured a project to use ServiceControl for error, audit and heartbeats. It was well documented how to configure everything for local queues, so I had no problem implementing it on my development machine. Thanks so far 👍 

But then I tried to deploy it on our testing environment. Since all of the **code** configuration samples for [errors](https://docs.particular.net/nservicebus/recoverability/configure-error-handling#configure-the-error-queue-address-using-code), [audit](https://docs.particular.net/nservicebus/operations/auditing#configuring-auditing-using-code) and [heartbeats](https://docs.particular.net/servicecontrol/plugins/heartbeat#configuration-servicecontrol-queue) only showed a queue name, I thought that I could just use the normal [MSMQ physical routing](https://docs.particular.net/nservicebus/msmq/routing) to define the machine name.

As this didn't work as expected, I then searched the documentation some more. The **app.config** configuration samples on the previously linked pages for errors and heartbeats show a queue name in the format "queue@machine" so I tried this using code configuration and it indeed worked. And even though the audit documentation for app.config configuration doesn't show this format, it worked there too.

I think this could be greatly improved.

**Comment by weralabaj** [comment]
@cremor thanks for your feedback!

@Particular/servicecontrol-maintainers can you have a look?

**Comment by WilliamBZA** [comment]
Thanks @cremor.

The Heartbeat documentation already includes the remote queue format but there's definitely a need to be more explicit in the audit and errors queue name sections.

**Comment by weralabaj** [comment]
I believe the concern was addressed in https://github.com/Particular/docs.particular.net/pull/2745, in case more changes are needed please reopen :)
