### ISSUE TITLE
Feedback: 'Introduction to NServiceBus: Retrying errors'

### ISSUE THREAD

**Issue by zagnut999** [Particular/docs.particular.net#2737]
Feedback for 'Introduction to NServiceBus: Retrying errors' https://docs.particular.net/tutorials/intro-to-nservicebus/5-retrying-errors/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/intro-to-nservicebus/5-retrying-errors/tutorial.md

```Now, we're ready to create and start the service:
1 Click the Add button to install the ServiceControl instance as a Windows service.
2 When complete, the ServiceControl Management tool will display the high-level details of the ServiceControl instance, but the instance will be in the Stopped state.
3 In the upper-right corner of the ServiceControl instance details, click the Start button (the button with the Play icon) to start the service. You can also start the service from the Windows Services manager.```

The service was started after (1).  Not sure if this is typical, but you may be able to remove (3) and update (2) accordingly.

**Comment by mikeminutillo** [comment]
Thanks @zagnut999. You are correct, the Management Utility always starts the newly created instance. I have updated the documentation page and you can see the new version at https://docs.particular.net/tutorials/intro-to-nservicebus/5-retrying-errors/
