### ISSUE TITLE
Feedback: 'Batching'

### ISSUE THREAD

**Issue by dasjestyr** [Particular/docs.particular.net#2742]
Feedback for 'Batching' https://docs.particular.net/nservicebus/azure-service-bus/batching

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure-service-bus/batching.md

ping @Particular/azure-maintainers 

I'm very confused. So the problem that I'm running into is that I have a handler that is spawning several thousand messages but it's apparently batching them in batches that far exceed Azure Service Bus's 100 message limit. 

My messages are relatively small, so used service insight to get a rough idea of the message size and then set the padding according to the charts listed here. No effect. I still get `TransactionContainsTooManyMessages `. Then as an apparent aside, the last thing on the doc says that setting the transaction mode to `SendsAtomicWithReceive` will limit it to 100 messages. But I'm still getting the same exception. It says that if I want to send more than 100 messages, that I should lower send mode. Does that mean more than 100 messages total, or more than 100 messages at a time? I feel like it's the former because the only thing I've been able to succeed with is `TransportTransactioMode.None` but folks on the google groups are raising an eyebrow at it.

This document talks about a few different things, but it seems to be a couple different factors and I can't tell what is related to what, and I still cannot seem to find the correct setting to limit the number of messages in a single batch.  I feel like I don't care about the message size; they're small. I just need to limit the number of actual *messages*

**Comment by weralabaj** [comment]
@dasjestyr thanks for the feedback, we'll review the page, as for the exception - did you raise it in any other place? e.g. on google group or support? sounds like something that should be addressed outside of doco update

**Comment by dasjestyr** [comment]
I brought it up in the google group and was referred to doco (https://groups.google.com/forum/#!topic/particularsoftware/kGx5ze9O2tA)

In short, I was troubleshooting something else and in the middle of it, I was asked why I set the transaction mode to 'none'. I said i was because of this issue (too many messages) and I couldn't figure out the config because the doc was vague.

**Comment by weralabaj** [comment]
thanks!

**Comment by SeanFeldman** [comment]
@dasjestyr before I tweak the doco, let me see if I get the confusing part right:

You're asking about the connection between the transport transaction mode `None` and batching. Why the mode needs to be `None` to be able to send more than 100 messages from a handler correct?

Documentation is broken out into features. One of them is [batching](https://docs.particular.net/nservicebus/azure-service-bus/batching) another one is NSB.ASB supported [transport transactions](https://docs.particular.net/nservicebus/azure-service-bus/transaction-support). 

The confusion might be the result of the necessity to keep in mind what limitations are enforced by the native ASB service when using one or another transport transaction mode. In this case, when `SendsAtomicWithReceive` is used, all outgoing messages must participate in an atomic operation. That implies batch size no more than 100 messages _and_ total size under whatever the maximum size for the service tier being used.

> When TransportTransactionMode.SendsAtomicWithReceive is used, Azure Service Bus limits number of outgoing operations from a handler context to 100

To be able to send more than 100 messages from a handler, TransportTransactionMode needs to be lowered. Meaning we can't guarantee message delivery anymore.

Could you please indicate what part of the document was confusing and what from my explanation could make it easier? 

Thank you 🙂

**Comment by dasjestyr** [comment]
@SeanFeldman hard to articulate, really. I think the doco lacks context. Just by reading it (as having been directed to read the doc), I can't tell how or what applies to me or why I would want to try this over that, etc. In my particular case, when it says that batched messages are "limited" I assume that it means it'll stop at 100, send the batch and then continue. Instead, if you have 101, it'll throw. It says in the doco that if it is exceeded, then it'll throw, but with my understanding the time I thought that was a fail safe, not a behavior. The context is hazy to me.

In terms of behavior, it seems odd to me that it would throw instead of just sending the buffered batch and then continue which is why I had assumed that it would. As for improvements, I guess the only thing I could suggest is context, scenarios, etc.

**Comment by SeanFeldman** [comment]
@dasjestyr I've made some change to the document to state clearly under the "Batching messages sent from a handler" section that it's the total size *and* number of messages that affecting batches. Also pulled the warning from the bottom of the document to the relevant location to make it more discoverable and in the right place.

Not sure how much of the context and scenarios we can add here. MSFT documentation is not the best, and we try to document the important parts to help our customers understand how things works. With the warning about exception that will be thrown if there are more than 100 messages - there's no "fail safe". It's an exception that is being thrown, period 🙂 

There's is a complexity associated with the fact that `TransportTransactionMode` influenced batching as well. Hence why the document recommends to to lower transaction mode. I wonder if that was weak spot. 

Thank you so much for the feedback. If you find more documents that would benefit from clarification, please let us know. Thank you.

**Comment by dasjestyr** [comment]
Should I bring up the issue of flushing the buffer/batch somewhere else? Or is that addressed in 7.x?

**Comment by SeanFeldman** [comment]
> the issue of flushing the buffer/batch

Not sure I fully understand. If you're referring to the limit of 100 messages _while_ using `TransportTransactionMode.SendsAtomicWithReceive`, that would be the native ASB client limitation imposed by the service. Otherwise you'd have to elaborate on what do you mean. BTW, feel free to send more details to my direct email sean.feldman@particular.net if you want to set up a call to go over details. Thank you.
