### ISSUE TITLE
 Remove MessageEndpointMappings from all v6 samples since it now logs an error

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2743]
Ok most of these are done. I need a bit of help from some maintainers for the following

### SqlTransport samples

ping @Particular/sqlserver-transport-maintainers 

 * \samples\sqltransport-nhpersistence\SqlServer_3\
 * \samples\sqltransport-sqlpersistence\SqlServer_3\
 * \samples\sqltransport\store-and-forward\SqlServer_3\

### ServiceControl Samples - ALL DONE

ping @Particular/servicecontrol-maintainers 

 * \samples\servicecontrol\events-subscription\ServiceControlContracts_1\

### Azure Samples

@Particular/azure-maintainers can you please remove the use of MessageEndpointMappings  from all azure samples that target v6 of NSB

**Comment by Scooletz** [comment]
[Azure hat on]

I've found only one usage of this in `shared-host\CloudServicesHost_6` which targets v5 of the CORE. As far as I see, there's nothing to remove.

**Comment by SimonCropp** [comment]
@Scooletz so this one is not relevant https://github.com/Particular/docs.particular.net/blob/master/samples/azure/polymorphic-events-asb/ASB_7/Subscriber/app.config#L7  ?

**Comment by Scooletz** [comment]
Oh my, my bad @SimonCropp . Reviewing it again then

**Comment by SeanFeldman** [comment]
@SimonCropp that one is not relevant - it's a left over that needed to be removed. Will do it.

**Comment by SeanFeldman** [comment]
custom-sanitization-asb and polymorphic-events-asb had MEM that was not needed.
Raised a PR  #2783

**Comment by SimonCropp** [comment]
Looks all done
