### ISSUE TITLE
Split descriptions of metrics into sub-pages

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#2758]
The [Metrics captured](https://docs.particular.net/nservicebus/operations/metrics#metrics-captured) section should be split into sub-pages (one per metric).

When we have that, we can expand on the following aspects of each metric:

- Does it describe a logical endpoint?
- Does it describe a physical endpoint instance?
- How to interpret it in different scale-out modes (competing consumers, MSMQ distributor, MSMQ sender-side distribution).

/cc @SzymonPobiega @Scooletz

**Comment by Scooletz** [comment]
@Particular/docs-maintainers what do you think?

**Comment by weralabaj** [comment]
is there anything preventing us from mentioning those aspects currently on a single page?
or are you concerned there'll be too much text?

if we start having more metrics then I don't mind splitting, just raise a PR ;)

**Comment by Scooletz** [comment]
I am concerned that there'll be too much text and that in cases of some of them, stating about logical/physical affinity might have no sense.

**Comment by weralabaj** [comment]
ok, then we could have a section in menu for metrics and desribe each one separately. let's try and see how it works

**Comment by ramonsmits** [comment]
Queue lenght seems currently broken for sender side distribution.

**Comment by weralabaj** [comment]
> Queue lenght seems currently broken for sender side distribution.

@ramonsmits ??? Is that regarding docs content or the functionality?

**Comment by ramonsmits** [comment]
@weralabaj In regards to behavior/logic. THat is a comment based on 

> How to interpret it in different scale-out modes (competing consumers, MSMQ distributor, MSMQ sender-side distribution).

**Comment by SimonCropp** [comment]
@MarcinHoppe @Scooletz i would suggest adding the new content on the same page and see how it looks. and only then split when u have confirmed that it is "too much information"

**Comment by Scooletz** [comment]
I don't know if I can drive it. @MarcinHoppe can you take it?

**Comment by MarcinHoppe** [comment]
Not this week, I am afraid.

**Comment by Scooletz** [comment]
Addressed with https://github.com/Particular/docs.particular.net/pull/3451
