### ISSUE TITLE
Feedback: 'Native integration'

### ISSUE THREAD

**Issue by udidahan** [Particular/docs.particular.net#2763]
Feedback for 'Native integration' https://docs.particular.net/samples/sqltransport/native-integration/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/sqltransport/native-integration/sample.md

ping @Particular/sqlserver-transport-maintainers

It would be better if this had some kind of opening paragraph describing what the sample is about.

**Comment by weralabaj** [comment]
fixed
