### ISSUE TITLE
Feedback: 'Using adapter to centralize monitoring of multi-instance SQL Server'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2771]
Feedback for 'Using adapter to centralize monitoring of multi-instance SQL Server' https://docs.particular.net/samples/servicecontrol/adapter-sqlserver/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/servicecontrol/adapter-sqlserver/sample.md

Cannot navigate from the sample to the documentation.

ping @Particular/servicecontrol-maintainers

**Comment by boblangley** [comment]
Added related link to transport adapter doco in commit https://github.com/Particular/docs.particular.net/commit/a8d61bebf805b582da89fdbecda3ea3cb7d3fc1e
