### ISSUE TITLE
Feedback: 'ServiceControl Transport Adapter'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2772]
Feedback for 'ServiceControl Transport Adapter' https://docs.particular.net/servicecontrol/transport-adapter/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/transport-adapter/index.md

Should [the sample](https://docs.particular.net/samples/servicecontrol/adapter-sqlserver/) be listed under this doco?

ping @Particular/servicecontrol-maintainers

**Comment by boblangley** [comment]
Added sample as related  item in commit https://github.com/Particular/docs.particular.net/commit/4661582bcfff1bc1099a6506fb593739c464dc79
