### ISSUE TITLE
Samples to NSB 7

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2778]
## Samples migrated to V7

 * [x] [azure/azure-service-bus](https://docs.particular.net/samples/azure/azure-service-bus) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/azure-service-bus))
 * [x] [azure/azure-service-bus-long-running](https://docs.particular.net/samples/azure/azure-service-bus-long-running) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/azure-service-bus-long-running))
 * [x] [azure/azure-service-fabric-routing](https://docs.particular.net/samples/azure/azure-service-fabric-routing) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/azure-service-fabric-routing)) 
 * [x] [azure/blob-storage-databus](https://docs.particular.net/samples/azure/blob-storage-databus) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/blob-storage-databus)) 
 * [x] [azure/custom-partitioning-asb](https://docs.particular.net/samples/azure/custom-partitioning-asb) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/custom-partitioning-asb))
 * [x] [azure/custom-sanitization-asb](https://docs.particular.net/samples/azure/custom-sanitization-asb) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/custom-sanitization-asb))
 * [x] [azure/native-integration-asb](https://docs.particular.net/samples/azure/native-integration-asb) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/native-integration-asb))
 * [x] [azure/performance-tuning-asb](https://docs.particular.net/samples/azure/performance-tuning-asb) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/performance-tuning-asb))
 * [x] [azure/polymorphic-events-asb](https://docs.particular.net/samples/azure/polymorphic-events-asb) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/polymorphic-events-asb))
 * [x] [azure/shared-host](https://docs.particular.net/samples/azure/shared-host) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/shared-host)) 
 * [x] [azure/storage-persistence](https://docs.particular.net/samples/azure/storage-persistence) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/storage-persistence)) 
 * [x] [azure/storage-queues](https://docs.particular.net/samples/azure/storage-queues) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/storage-queues)) 
 * [x] [callbacks](https://docs.particular.net/samples/callbacks) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/callbacks)) 
 * [x] [consumer-driven-contracts](https://docs.particular.net/samples/consumer-driven-contracts) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/consumer-driven-contracts)) 
 * [x] [containers/autofac](https://docs.particular.net/samples/containers/autofac) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/containers/autofac)) 
 * [x] [containers/castle](https://docs.particular.net/samples/containers/castle) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/containers/castle)) 
 * [x] [containers/ninject](https://docs.particular.net/samples/containers/ninject) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/containers/ninject)) 
 * [ ] [containers/simpleinjector](https://docs.particular.net/samples/containers/simpleinjector) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/containers/simpleinjector)) 
 * [x] [containers/spring](https://docs.particular.net/samples/containers/spring) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/containers/spring)) 
 * [x] [containers/structuremap](https://docs.particular.net/samples/containers/structuremap) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/containers/structuremap)) 
 * [x] [containers/unity](https://docs.particular.net/samples/containers/unity) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/containers/unity)) 
 * [ ] [custom-checks/monitoring3rdparty](https://docs.particular.net/samples/custom-checks/monitoring3rdparty) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/custom-checks/monitoring3rdparty)) 
 * [x] [custom-transport](https://docs.particular.net/samples/custom-transport) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/custom-transport)) 
 * [x] [delayed-delivery](https://docs.particular.net/samples/delayed-delivery) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/delayed-delivery)) 
 * [x] [encryption/basic-encryption](https://docs.particular.net/samples/encryption/basic-encryption) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/encryption/basic-encryption)) 
 * [x] [encryption/message-body-encryption](https://docs.particular.net/samples/encryption/message-body-encryption) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/encryption/message-body-encryption)) 
 * [x] [endpoint-configuration](https://docs.particular.net/samples/endpoint-configuration) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/endpoint-configuration)) 
 * [x] [entity-framework](https://docs.particular.net/samples/entity-framework) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/entity-framework)) 
 * [x] [errorhandling](https://docs.particular.net/samples/errorhandling) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/errorhandling)) 
 * [x] [faulttolerance](https://docs.particular.net/samples/faulttolerance) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/faulttolerance)) 
 * [x] [feature](https://docs.particular.net/samples/feature) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/feature)) 
 * [x] [file-share-databus](https://docs.particular.net/samples/file-share-databus) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/file-share-databus)) 
 * [x] [fullduplex](https://docs.particular.net/samples/fullduplex) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/fullduplex)) 
 * [x] [gateway](https://docs.particular.net/samples/gateway) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/gateway)) 
 * [x] [handler-ordering-by-interface](https://docs.particular.net/samples/handler-ordering-by-interface) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/handler-ordering-by-interface)) 
 * [x] [header-manipulation](https://docs.particular.net/samples/header-manipulation) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/header-manipulation)) 
 * [x] [hosting/multi-hosting](https://docs.particular.net/samples/hosting/multi-hosting) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/hosting/multi-hosting)) 
 * [x] [hosting/nservicebus-host](https://docs.particular.net/samples/hosting/nservicebus-host) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/hosting/nservicebus-host)) 
 * [x] [hosting/self-hosting](https://docs.particular.net/samples/hosting/self-hosting) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/hosting/self-hosting)) 
 * [x] [hosting/windows-service](https://docs.particular.net/samples/hosting/windows-service) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/hosting/windows-service)) 
 * [ ] [kafka](https://docs.particular.net/samples/kafka) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/kafka)) 
 * [x] [learning-transport](https://docs.particular.net/samples/learning-transport) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/learning-transport)) 
 * [ ] [logging/anotar](https://docs.particular.net/samples/logging/anotar) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/anotar)) 
 * [x] [logging/commonlogging](https://docs.particular.net/samples/logging/commonlogging) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/commonlogging)) 
 * [x] [logging/custom-factory](https://docs.particular.net/samples/logging/custom-factory) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/custom-factory)) 
 * [x] [logging/default](https://docs.particular.net/samples/logging/default) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/default)) 
 * [x] [logging/eventsourcelogging](https://docs.particular.net/samples/logging/eventsourcelogging) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/eventsourcelogging)) 
 * [x] [logging/hostcustom](https://docs.particular.net/samples/logging/hostcustom) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostcustom)) 
 * [x] [logging/hostdefault](https://docs.particular.net/samples/logging/hostdefault) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostdefault)) 
 * [x] [logging/hostprofiles](https://docs.particular.net/samples/logging/hostprofiles) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostprofiles)) 
 * [x] [logging/log4net-custom](https://docs.particular.net/samples/logging/log4net-custom) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/log4net-custom)) 
 * [x] [logging/nlog-custom](https://docs.particular.net/samples/logging/nlog-custom) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/nlog-custom)) 
 * [x] [logging/notifications](https://docs.particular.net/samples/logging/notifications) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/notifications)) 
 * [x] [logging/serilog-custom](https://docs.particular.net/samples/logging/serilog-custom) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/serilog-custom)) 
 * [x] [logging/serilog-seq](https://docs.particular.net/samples/logging/serilog-seq) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/serilog-seq)) 
 * [x] [logging/stack-trace-cleaning](https://docs.particular.net/samples/logging/stack-trace-cleaning) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/stack-trace-cleaning)) 
 * [x] [mailer](https://docs.particular.net/samples/mailer) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/mailer)) 
 * [x] [message-error-handling](https://docs.particular.net/samples/message-error-handling) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/message-error-handling)) 
 * [x] [messagemutators](https://docs.particular.net/samples/messagemutators) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/messagemutators)) 
 * [x] [metrics/tracing](https://docs.particular.net/samples/metrics/tracing) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/metrics/tracing)) 
 * [ ] [mongodb](https://docs.particular.net/samples/mongodb) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/mongodb)) 
 * [ ] [mongodb-databus](https://docs.particular.net/samples/mongodb-databus) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/mongodb-databus)) 
 * [x] [msmqtosqlrelay](https://docs.particular.net/samples/msmqtosqlrelay) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/msmqtosqlrelay)) 
 * [x] [near-realtime-clients](https://docs.particular.net/samples/near-realtime-clients) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/near-realtime-clients)) 
 * [x] [nhibernate/custom-mappings](https://docs.particular.net/samples/nhibernate/custom-mappings) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/nhibernate/custom-mappings)) 
 * [x] [nhibernate/simple](https://docs.particular.net/samples/nhibernate/simple) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/nhibernate/simple)) 
 * [x] [non-durable-messaging](https://docs.particular.net/samples/non-durable-messaging) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/non-durable-messaging)) 
 * [x] [outbox/multi-tenant](https://docs.particular.net/samples/outbox/multi-tenant) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/outbox/multi-tenant)) 
 * [x] [outbox/sql](https://docs.particular.net/samples/outbox/sql) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/outbox/sql))
 * [x] [performance-counters](https://docs.particular.net/samples/performance-counters) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/performance-counters)) 
 * [x] [pipeline/audit-filtering](https://docs.particular.net/samples/pipeline/audit-filtering) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/pipeline/audit-filtering)) 
 * [x] [pipeline/handler-timer](https://docs.particular.net/samples/pipeline/handler-timer) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/pipeline/handler-timer)) 
 * [x] [pipeline/multi-serializer](https://docs.particular.net/samples/pipeline/multi-serializer) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/pipeline/multi-serializer)) 
 * [x] [pipeline/stream-properties](https://docs.particular.net/samples/pipeline/stream-properties) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/pipeline/stream-properties)) 
 * [x] [pipeline/unit-of-work](https://docs.particular.net/samples/pipeline/unit-of-work) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/pipeline/unit-of-work)) 
 * [x] [plugin-based-config](https://docs.particular.net/samples/plugin-based-config) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/plugin-based-config)) 
 * [x] [pubsub](https://docs.particular.net/samples/pubsub) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/pubsub)) 
 * [x] [rabbitmq/native-integration](https://docs.particular.net/samples/rabbitmq/native-integration) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/rabbitmq/native-integration)) 
 * [x] [rabbitmq/simple](https://docs.particular.net/samples/rabbitmq/simple) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/rabbitmq/simple)) 
 * [x] [ravendb/simple](https://docs.particular.net/samples/ravendb/simple) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/ravendb/simple)) 
 * [x] [routing/custom](https://docs.particular.net/samples/routing/custom) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/routing/custom)) 
 * [x] [routing/data-distribution](https://docs.particular.net/samples/routing/data-distribution) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/routing/data-distribution)) 
 * [x] [routing/fair-distribution](https://docs.particular.net/samples/routing/fair-distribution) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/routing/fair-distribution)) 
 * [x] [routing/file-based-routing](https://docs.particular.net/samples/routing/file-based-routing) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/routing/file-based-routing)) 
 * [x] [routing/instance-mapping-file](https://docs.particular.net/samples/routing/instance-mapping-file) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/routing/instance-mapping-file)) 
 * [ ] [routing-slips](https://docs.particular.net/samples/routing-slips) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/routing-slips)) 
 * [x] [saga/migration](https://docs.particular.net/samples/saga/migration) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/saga/migration)) 
 * [x] [saga/nh-custom-sagafinder](https://docs.particular.net/samples/saga/nh-custom-sagafinder) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/saga/nh-custom-sagafinder)) 
 * [x] [saga/ravendb-custom-sagafinder](https://docs.particular.net/samples/saga/ravendb-custom-sagafinder) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/saga/ravendb-custom-sagafinder)) 
 * [x] [saga/simple](https://docs.particular.net/samples/saga/simple) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/saga/simple)) 
 * [x] [saga/sql-sagafinder](https://docs.particular.net/samples/saga/sql-sagafinder) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/saga/sql-sagafinder)) 
 * ~[scaleout/distributor](https://docs.particular.net/samples/scaleout/distributor) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/scaleout/distributor))~ 
 * ~[scaleout/distributor-upgrade](https://docs.particular.net/samples/scaleout/distributor-upgrade) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/scaleout/distributor-upgrade))~ 
 * [x] [scaleout/senderside](https://docs.particular.net/samples/scaleout/senderside) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/scaleout/senderside)) 
 * [x] [scaleout/senderside-and-distributor](https://docs.particular.net/samples/scaleout/senderside-and-distributor) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/scaleout/senderside-and-distributor)) 
 * [x] [scheduling](https://docs.particular.net/samples/scheduling) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/scheduling)) 
 * ~~[serializers/binary](https://docs.particular.net/samples/serializers/binary) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/binary))~~
 * [x] [serializers/bond](https://docs.particular.net/samples/serializers/bond) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/bond)) 
 * ~~[serializers/bson](https://docs.particular.net/samples/serializers/bson) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/bson))~~ 
 * [x] [serializers/jil](https://docs.particular.net/samples/serializers/jil) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/jil)) 
 * [x] [serializers/json](https://docs.particular.net/samples/serializers/json) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/json)) 
 * [x] [serializers/hyperion](https://docs.particular.net/nservicebus/serialization/hyperion) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/hyperion)) 
 * [x] [serializers/message-pack](https://docs.particular.net/samples/serializers/message-pack) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/message-pack)) 
 * [x] [serializers/multiple-deserializers](https://docs.particular.net/samples/serializers/multiple-deserializers) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/multiple-deserializers)) 
 * [x] [serializers/newtonsoft](https://docs.particular.net/samples/serializers/newtonsoft) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/newtonsoft)) 
 * [x] [serializers/newtonsoft-bson](https://docs.particular.net/samples/serializers/newtonsoft-bson) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/newtonsoft-bson)) 
 * [x] [serializers/protobufgoogle](https://docs.particular.net/samples/serializers/protobufgoogle) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/protobufgoogle)) 
 * [x] [serializers/protobufnet](https://docs.particular.net/samples/serializers/protobufnet) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/protobufnet)) 
 * [x] [serializers/transitioning-formats](https://docs.particular.net/samples/serializers/transitioning-formats) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/transitioning-formats)) 
 * [x] [serializers/wire](https://docs.particular.net/samples/serializers/wire) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/wire)) 
 * [x] [serializers/xml](https://docs.particular.net/samples/serializers/xml) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/xml)) 
 * [x] [serializers/zeroformatter](https://docs.particular.net/samples/serializers/zeroformatter) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/serializers/zeroformatter)) 
 * ~[servicecontrol/events-subscription](https://docs.particular.net/samples/servicecontrol/events-subscription) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/servicecontrol/events-subscription))~ no ref on v7 
 * [x] [show-case/cloud-azure](https://docs.particular.net/samples/show-case/cloud-azure) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/show-case/cloud-azure)) 
 * [x] [show-case/on-premise](https://docs.particular.net/samples/show-case/on-premise) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/show-case/on-premise)) 
 * ~[sql-bridge](https://docs.particular.net/samples/sql-bridge) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sql-bridge))~ deprecated 
 * [x] [sql-persistence/saga-rename](https://docs.particular.net/samples/sql-persistence/saga-rename) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sql-persistence/saga-rename)) 
 * [x] [sql-persistence/simple](https://docs.particular.net/samples/sql-persistence/simple) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sql-persistence/simple)) 
 * [x] [sql-persistence/transitioning-correlation-ids](https://docs.particular.net/samples/sql-persistence/transitioning-correlation-ids) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sql-persistence/transitioning-correlation-ids)) 
 * [x] [sqltransport/multi-instance](https://docs.particular.net/samples/sqltransport/multi-instance) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqltransport/multi-instance)) 
 * [x] [sqltransport/native-integration](https://docs.particular.net/samples/sqltransport/native-integration) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqltransport/native-integration)) 
 * [x] [sqltransport/native-timeout-migration](https://docs.particular.net/samples/sqltransport/native-timeout-migration) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqltransport/native-timeout-migration)) 
 * [x] [sqltransport/simple](https://docs.particular.net/samples/sqltransport/simple) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqltransport/simple)) 
 * [x] [sqltransport/store-and-forward](https://docs.particular.net/samples/sqltransport/store-and-forward) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqltransport/store-and-forward)) 
 * [x] [sqltransport-nhpersistence](https://docs.particular.net/samples/sqltransport-nhpersistence) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqltransport-nhpersistence)) 
 * [x] [sqltransport-sqlpersistence](https://docs.particular.net/samples/sqltransport-sqlpersistence) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqltransport-sqlpersistence)) 
 * [x] [startup-shutdown-sequence](https://docs.particular.net/samples/startup-shutdown-sequence) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/startup-shutdown-sequence)) 
 * [x] [step-by-step](https://docs.particular.net/samples/step-by-step) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/step-by-step)) 
 * [x] [throttling](https://docs.particular.net/samples/throttling) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/throttling)) 
 * [x] [unit-of-work](https://docs.particular.net/samples/unit-of-work) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/unit-of-work)) 
 * [x] [unit-testing](https://docs.particular.net/samples/unit-testing) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/unit-testing)) 
 * [x] [unobtrusive](https://docs.particular.net/samples/unobtrusive) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/unobtrusive)) 
 * [x] [username-header](https://docs.particular.net/samples/username-header) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/username-header)) 
 * [x] [versioning](https://docs.particular.net/samples/versioning) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/versioning)) 
 * [x] [web/asp-mvc-application](https://docs.particular.net/samples/web/asp-mvc-application) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/web/asp-mvc-application)) 
 * [x] [web/asp-web-application](https://docs.particular.net/samples/web/asp-web-application) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/web/asp-web-application)) 
 * [x] [web/owin-pass-through](https://docs.particular.net/samples/web/owin-pass-through) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/web/owin-pass-through)) 
 * [x] [web/send-from-aspnetcore-webapi](https://docs.particular.net/samples/web/send-from-aspnetcore-webapi) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/web/send-from-aspnetcore-webapi)) 
 * [x] [web/send-from-mvc-controller](https://docs.particular.net/samples/web/send-from-mvc-controller) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/web/send-from-mvc-controller)) 
 * [x] [web/wcf-callbacks](https://docs.particular.net/samples/web/wcf-callbacks) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/web/wcf-callbacks)) 
 * [x] [sqs](https://docs.particular.net/samples/sqs/simple/) ([GH](https://github.com/Particular/docs.particular.net/tree/master/samples/sqs/simple))

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers eta on https://docs.particular.net/samples/azure/shared-host being moved to target nsb v7?

**Comment by danielmarbach** [comment]
@SimonCropp see https://github.com/Particular/DotNetCoreLaunch/issues/40 the hotfix and yak shaving around the build had prio. Will start moving things again today and tomorrow

**Comment by danielmarbach** [comment]
Sent in a PR to move the Routing slip to NSB v7 https://github.com/jbogard/NServiceBus.MessageRouting/pull/6

**Comment by danielmarbach** [comment]
Sent in a PR for MongoDB to NSB v7. Struggling quite a bit with NU1605 errors at the moment though https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/pull/24

**Comment by gbiellem** [comment]
@SimonCropp Just a heads up  the Saga migration sample needs fixing. The  [context.Context](https://github.com/Particular/docs.particular.net/blob/cd558e459ca5b122f3cb982df6e11422d967254b/samples/saga/migration/Core_7/Server.New/DrainTempQueueSatelliteFeature.cs#L56)  here was obsolete in V6 and has been removed in V7.  I assume this hasn't been picked up as the class is being excluded by a directive.

**Comment by SimonCropp** [comment]
@gbiellem thanks. we have this tracked to do as part of the NSB v7 release

**Comment by weralabaj** [comment]
@SimonCropp Should we have a separate issue that is "smoke testing" with the same list of samples once we announce the freeze?

I fixed the issue Greg mentioned, but there was another problem with this sample. Impossible to find unless you actually go through the scenario, so smoke testing is a must, but seems hasn't been done yet (and with some samples it's not clear whose responsibility it is, so may fall through the cracks :/).

**Comment by SimonCropp** [comment]
@weralabaj this issue is not about smoke testing. Just the upgrade and compile. Smoke testing should be done by the responsible maintainer group at whatever intervals they feel is necessary

**Comment by SimonCropp** [comment]
As for "another issue to track smoke testing" i am not sure it is necessary?

**Comment by weralabaj** [comment]
> Smoke testing should be done by the responsible maintainer group at whatever intervals they feel is necessary

This is where my concern is :) If you have a sample that's using a few packages, then the responsiblity is not clear and without any bad intentions, we may miss it. Saga migration is an example (NHibernate vs SQL Persistence), I admit I didn't have it on my list of "SQL persistence samples", but woudln't mind verifying it if I knew it wasn't tested.

**Comment by SimonCropp** [comment]
no longer up to date
