### ISSUE TITLE
Feedback: 'ServiceControl Transport Adapter'

### ISSUE THREAD

**Issue by Bishbulb** [Particular/docs.particular.net#2782]
I am finding it hard to understand from the documentation how the SC Transport Adapter should be hosted. In my system, there are primarily MSMQ endpoints with two AzureServiceBus endpoints. Should this adapter be installed inside both of the AzureServiceBus endpoints, or does it need to run in a separate process? If the adapter is supposed to run in a separate process, how should it be hosted?

Also, the docs are currently very focused on the parameters of the `TransportAdapterConfig`, but there is nothing illustrating how to actually use that config object. Once I looked in the `SqlServerTransportAdapter` sample, I saw that there was a method `TransportAdapter.Create()`, but it would have been nice to have that available in the docs.

Thanks!
 
Feedback for 'ServiceControl Transport Adapter' https://docs.particular.net/servicecontrol/transport-adapter/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/transport-adapter/index.md

ping @Particular/servicecontrol-maintainers

**Comment by SzymonPobiega** [comment]
Thanks for your feedback @Bishbulb . I've created issues #2789 with a plan of action to address the problems you pointed out.

**Comment by SzymonPobiega** [comment]
@Bishbulb if you don't mind I'll close this issue and keep the #2789 open. You can track our progress there. If you don't agree with the action items there feel free to re-open this one.
