### ISSUE TITLE
Improve Transport Adapter doco

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#2789]
Based on customer's feedback captured in https://github.com/Particular/docs.particular.net/issues/2782

### Plan of attack

 - [x] Add hosting section to the doco - #2797 
 - [x] Add lifecycle (start/stop) section to the doco - #2797 
 - [x] Move the scenarios to samples
     - [x] Mixed transports (MSMQ/RabbitMQ)
     - [x] Azure

**Comment by weralabaj** [comment]
@SzymonPobiega I see we have samples for ASB https://docs.particular.net/samples/servicecontrol/adapter-asb-multi-namespace/  and mixed transports https://docs.particular.net/samples/servicecontrol/adapter-mixed-transports/, so this issue has been addressed, correct?

if something is missing, feel free to reopen ;)
