### ISSUE TITLE
Moving MSMQ tranport out of core - docs verification

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#2802]
https://github.com/Particular/docs.particular.net/pull/2798 and https://github.com/Particular/docs.particular.net/pull/2796 contain a number of changes, but still some issues need to be resolved/verified.

To review:
- [x] All appropriate page versions exist (e.g. v6, v7, or v6, v1)
- [x] V6 i V7/V1 content is the same (or different on purpose)
- [x] All snippets are in appropriate (supported) versions

Pages to review:
- [x] https://docs.particular.net/nservicebus/msmq/transportconfig  - @andreasohlund 
- [ ] https://docs.particular.net/nservicebus/msmq/full-qualified-domain-name  - @weralabaj - needs fixing (no version 1)
- [x] https://docs.particular.net/nservicebus/msmq/routing - @andreasohlund
- [ ] https://docs.particular.net/nservicebus/msmq/sender-side-distribution @weralabaj - needs fixing (no version 1)
- [x] https://docs.particular.net/nservicebus/messaging/routing-extensibility @weralabaj
- [x] https://docs.particular.net/nservicebus/msmq/dead-letter-queues @andreasohlund

**Comment by andreasohlund** [comment]
I'll help out @weralabaj , converted the poa items to checkboxes can you tick the ones that you''ve done
