### ISSUE TITLE
Feedback: 'Sending metrics data to trace log'

### ISSUE THREAD

**Issue by tmasternak** [Particular/docs.particular.net#2804]
When running the samples the metrics report is showing up in `Debug` window of Visual Studio 2017 and not in console as other log entries. 

Is that by design?

ping @Particular/metrics-maintainers

**Comment by kbaley** [comment]
@tmasternak Which sample are you running?

The location of the log depends on how you configure the metrics. The [only sample](https://docs.particular.net/samples/metrics/tracing/) we have in metrics at the moment is one that is specifically designed to write to the `Trace` window with `.EnableMetricTracing`. Not sure if we are enabling metrics in any other samples though.

**Comment by tmasternak** [comment]
@kbaley I got confused about the configuration of the sample you mentioned. All is good.
