### ISSUE TITLE
Feedback: 'Using NServiceBus with ASP.NET MVC'

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2830]
Feedback for 'Using NServiceBus with ASP.NET MVC' https://docs.particular.net/samples/web/asp-mvc-application/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/asp-mvc-application/sample.md

ping @Particular/nservicebus-maintainers @Particular/container-maintainers 

The V6 init code is broken. The V5 code is correct, the container is shared between both MVC and NServiceBus but the V6 doesn't achieve the same. In the V6 sample, both MVC and NServiceBus have their own container instance meaning singletons cannot be shared between for example controllers and handlers.

- DependencyResolver.SetResolver is invoked more than once
- RegisterControllers is invoked more than once

I have not been able to resolve these issues as it seems as a chicken/egg order issue as V6 does not register the IEndpointInstance in the passed container.

**Comment by timbussmann** [comment]
@ramonsmits raised a proposal here: https://github.com/Particular/docs.particular.net/pull/2834

**Comment by ramonsmits** [comment]
Closing this as the PR will fix this.
