### ISSUE TITLE
Microsoft.WindowsAzure.Storage 8.1.4 version redirect error

### ISSUE THREAD

**Issue by SteveWinward** [Particular/docs.particular.net#2839]
The Microsoft.WindowsAzure.Storage nuget version 8.1.4 is installed in the solution, however the assembly redirect is only redirecting to 8.1.3.0.  This is causing the sender/receiver services to fail to start with local F5 debugging.

The current configuration is below,

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.1.3.0" newVersion="8.1.3.0" />
      </dependentAssembly>

The redirects should be fixed as follows,

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.1.4.0" newVersion="8.1.4.0" />
      </dependentAssembly>

**Comment by SeanFeldman** [comment]
@SteveWinward what sample is this? Thank you.

**Comment by SteveWinward** [comment]
This issue is for the /samples/azure/shared-host/CloudServicesHost_7 project.

**Comment by boblangley** [comment]
PR #2837 updated the assembly redirects and updated to the just release version of the host.
