### ISSUE TITLE
Assembly Redirect Warnings in NServiceBus.Hosting.Azure.HostProcess.exe

### ISSUE THREAD

**Issue by SteveWinward** [Particular/docs.particular.net#2840]
This issue is for the /samples/azure/shared-host/CloudServicesHost_7 project.

I'm seeing an issue with the NServiceBus.Hosting.Azure.HostProcess.  When I run the Sender or Receiver project locally I see the following warnings in the console,

```
2017-06-12 15:08:57.015 WARN  NServiceBus.Hosting.Helpers.AssemblyScanner Could not enumerate all types for 'NServiceBus.Azure.Transports.WindowsAzureStorageQueues, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
It looks like you may be missing binding redirects in the config file for the following assemblies:
Microsoft.WindowsAzure.Storage, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
For more information see http://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.100).aspx

2017-06-12 15:08:57.187 WARN  NServiceBus.Hosting.Helpers.AssemblyScanner Could not enumerate all types for 'NServiceBus.Persistence.AzureStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
It looks like you may be missing binding redirects in the config file for the following assemblies:
Microsoft.WindowsAzure.Storage, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
For more information see http://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.100).aspx

```
I can fix these warnings by copying the app.config file and renaming it to NServiceBus.Hosting.Azure.HostProcess.exe.config.  I created a postbuild event with this,

`copy "$(ProjectDir)app.config" "$(TargetDir)NServiceBus.Hosting.Azure.HostProcess.exe.config" /Y`

However, I then get prompted to install .NET 3.5.  Does anyone know why this happens?

Also, I created a separate issue about the assembly redirect version of Microsoft.WindowsAzure.Storage being the wrong version number #2839 .  You can't get the current services to run locally until that is fixed.

**Comment by SteveWinward** [comment]
Forgot to include this the first time.  This issue is for the /samples/azure/shared-host/CloudServicesHost_7 project.

**Comment by yvesgoeleven** [comment]
@SteveWinward thanks for reporting, we'll fix the binding redirects.

the .net 3.5 prompt is really weird, I guess it has to do with additional config being applied to the exe by copying the app.config; A better way is to just create a file called NServiceBus.Hosting.Azure.HostProcess.exe.config and only add the binding redirects to it, instead of copying all sections

**Comment by SteveWinward** [comment]
@yvesgoeleven Thanks for looking into the binding redirect warnings.  It appears that because NServiceBus.Hosting.Azure.HostProcess is only using Microsoft.WindowsAzure.Storage version 8.0.0 and the sample is using 8.1.4, this is why the redirect warning is showing up.

https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/7.1.3/src/NServiceBus.Hosting.Azure.HostProcess/packages.config

https://github.com/Particular/docs.particular.net/blob/master/samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config

However, if I create the NServiceBus.Hosting.Azure.HostProcess.exe.config as you mentioned and only include the Microsoft.WindowsAzure.Storage redirect, I still get prompted with the .NET 3.5 install.  I'm running this on a Windows 10 image version 1703 if that helps.

**Comment by yvesgoeleven** [comment]
@SteveWinward I don't have the problem of being prompted, probably because it is installed on my machine.

I assume it will be fixed when you explictly add the supported runtime to the exe.config as well, this way it is forced to use 4 and not 3.5

<startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1"/>
  </startup>

I will update the sample accordingly

**Comment by SteveWinward** [comment]
Thanks @yvesgoeleven .  Unfortunately even with the supportedRuntime element in the config file, I'm still getting prompted for the .NET 3.5 install.  If I remove the NSerivceBus.Hosting.Azure.HostProcess.exe.config file altogether the redirect warnings show up again, however the .NET 3.5 install prompt goes away.  It appears .NET is treating something differently when it has a NSerivceBus.Hosting.Azure.HostProcess.exe.config file.

**Comment by yvesgoeleven** [comment]
@SteveWinward this is really weird, I checked my machine and don't have 3.5 installed either, yet it doesn't prompt. I'll ask my colleagues if anyone has an idea, I can't explain it

**Comment by yvesgoeleven** [comment]
@SteveWinward as a safety check, can you run the same version that I ran, from this pr ? https://github.com/Particular/docs.particular.net/pull/2854/files

**Comment by yvesgoeleven** [comment]
@SteveWinward it has a square in it yes, so partially installed. I'll see if I can find a machine without it
