### ISSUE TITLE
Explicitly mention that ServiceControl API is for internal use

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#2843]
Related to https://github.com/Particular/CustomerSuccess/issues/533

We need to explicitly mention that SC API is not for public use despite being a public API and add a warning message where necessary.

**Comment by weralabaj** [comment]
@HEskandari I remember Mike added it recently here https://docs.particular.net/servicecontrol/servicecontrol-instances/, should we copy that note to more pages or does that address the concern?

**Comment by HEskandari** [comment]
That's exactly what I had in mind @weralabaj. Withdrawing the issue.
