### ISSUE TITLE
Author an article on error queue management using the SqlTransport

### ISSUE THREAD

**Issue by udidahan** [Particular/docs.particular.net#286]
Older users have experience with the ReturnToSourceQueue.exe tool but don't know what's available for the SqlTransport - with and without the use of ServiceControl

**Comment by mauroservienti** [comment]
@ramonsmits do you want to take a stab at it?

**Comment by ramonsmits** [comment]
@mauroservienti Yes, shouldn't be that hard. Do we need to apply a label?

**Comment by mauroservienti** [comment]
@ramonsmits I removed the "Needs Triage" one, move it to the in progress state when you star working on it.

**Comment by SimonCropp** [comment]
no longer relevant https://github.com/ParticularLabs/MsmqReturnToSourceQueue
