### ISSUE TITLE
Should we document how to monitor MSMQ outgoing queues?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#2863]
[I helped a user](https://groups.google.com/d/msg/particularsoftware/2Zx85uMH0Mo/ay-pMb_dAQAJ) with [some sample code to monitor outgoing msmq queues](https://gist.github.com/andreasohlund/1c3b8471521fbfc1f3ab8c40f2fde75c) today.

Is this something we want to add to our docs? 

Perhaps here - https://docs.particular.net/nservicebus/msmq/dead-letter-queues#monitoring-dlq

@Particular/msmq-transport-maintainers thoughts?

**Comment by dvdstelt** [comment]
I definitely see value in it, as a lot of customers aren't even aware of the DLQ.

I know there has been a lot of conversation about monitoring DLQ. Is this something each transport needs to pick up themselves? Did others do this already? Is there an initiative from the DevOps wave?
Do we just want to document this or should we create a custom check for ServiceControl/ServicePulse to demo how you could do this?

**Comment by andreasohlund** [comment]
>I know there has been a lot of conversation about monitoring DLQ. Is this something each transport needs to pick up themselves?

Yes this is IMO something transport specific, some won't even have a DLQ.

> Did others do this already? 

Pretty sure that no one has done that

>Is there an initiative from the DevOps wave?

@SzymonPobiega do you know?

>Do we just want to document this or should we create a custom check for ServiceControl/ServicePulse to demo how you could do this?

You could definitely do that but my concern is if real production endpoints would/should have the permissions needed for this type of "msmq wide" querying. @SzymonPobiega I have a faint memory that you researched this a while back?  (since the custom checks runs within the endpoint process)

**Comment by dvdstelt** [comment]
> endpoints would/should have the permissions needed for this type of "msmq wide" querying.

Hmmm, good point. We might end up with 20 endpoints all sending information about the DLQ, which seems a bit overkill. Let's not do that.

**Comment by andreasohlund** [comment]
This is IMO a good use case for a "Particular Admin/Watchdog/Whatever" process that would be able to run with elevated privileges in order to perform things like this

**Comment by dvdstelt** [comment]
Could be a tool that even non-NServiceBus users might have use for? But with NServiceBus endpoints enabled, it could provide even more awesomeness!? 👍 
What other features could it incorporate?

**Comment by SzymonPobiega** [comment]
@andreasohlund @dvdstelt 

AFAIK DLQ can be monitored using regular permissions. It is the outgoing queues that require elevated privileges.

There was a spike done by @Scooletz related to monitoring DLQ. Some doubts were raised related to the fact that DLQ is shared and endpoint don't know it if contains "their" messages. This is why I proposed to use dedicated DLQs for each endpoint. This way we can control and manage the DLQs in a proper way.

**Comment by andreasohlund** [comment]
>This is why I proposed to use dedicated DLQs for each endpoint

Didn't even think that was possible? (link?)

**Comment by SzymonPobiega** [comment]
@andreasohlund  https://github.com/Particular/NServiceBus/issues/4223#issuecomment-272166132

[WCF can do this](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.msmqbindingbase.customdeadletterqueue?view=netframework-4.7) so we should not be worse.

**Comment by SimonCropp** [comment]
given this doco would not have anything to do with specifically to NSB. shouldnt this be a PR to the MS docs?

**Comment by andreasohlund** [comment]
Talked to @szymonpobiega and he convinced me that there should be no need for this type of monitoring since messages ends up in the dlq if delivery fails and we should view outgoing queues as msmq's "delayed retries". This highligts how msmq default of 4days for TTRQ is problematic for users since that's way to long for the majority of them.

Will raise a separate issue in the msmq repo to discuss that

**Comment by dvdstelt** [comment]
> Talked to @SzymonPobiega and he convinced me that there should be no need for this type of monitoring

Care to explain in this issue? Or when you create the other issue, reference this one, so we can follow the discussion?
