### ISSUE TITLE
give persistence and transports their own dir

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2864]
So we can 

 * have nicer urls with `https://docs.particular.net/transports` and `https://docs.particular.net/persistence/`
 * split the upgrade guides by persistence and transports. making this page and menu more manageable https://docs.particular.net/nservicebus/upgrades/
 * have urls map better to the menu structure
 * make the dir tree structure more evenly balanced. ie not havign so many pages and dirs under here https://github.com/Particular/docs.particular.net/tree/master/nservicebus
 * minimize the bloat in this page https://docs.particular.net/nservicebus/ since it renders all pages under https://github.com/Particular/docs.particular.net/tree/master/nservicebus

**Comment by SimonCropp** [comment]
@Particular/docs-maintainers thoughts?

**Comment by weralabaj** [comment]
@andreasohlund would that be a good first task to test the new plat dev process?

**Comment by weralabaj** [comment]
I think that it's worth doing, even though the menu structure has been improved a lot, finding the location of the specific article may be harder because of this. and nservicebus directory indeed is giant.

**Comment by weralabaj** [comment]
issue to be done under maintainers budget
