### ISSUE TITLE
Feedback: 'MSMQ Subscription Persistence'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2872]
Feedback for 'MSMQ Subscription Persistence' ~~https://docs.particular.net/nservicebus/msmq/subscription-persistence~~ https://docs.particular.net/persistence/msmq/subscription

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/msmq/subscription-persistence.md

ping @Particular/msmq-transport-maintainers

Subscription duplicates are created over time and not cleaned up. What's the guidance on keeping those under control and tidy? Any scripts that could be applied?

**Comment by SimonCropp** [comment]
ping @Particular/msmq-transport-maintainers

**Comment by andreasohlund** [comment]
@timbussmann didn't we fix this to "purge" on every endpoint startup?

**Comment by timbussmann** [comment]
yeah outdated subscriptions should be removed on startup.

**Comment by SeanFeldman** [comment]
Is that taking place as of certain version?

**Comment by timbussmann** [comment]
should be part of 6.0

**Comment by SeanFeldman** [comment]
Shouldn't there be a note to clarify the difference in behavior? I didn't see anything for version 5 and below.

**Comment by andreasohlund** [comment]
👍 to add a note

**Comment by SeanFeldman** [comment]
@Particular/msmq-transport-maintainers ☝️

**Comment by indualagarsamy** [comment]
So the behavior in v6 and above is that duplicates will not be created at all in the first place as @timbussmann pointed out in:
https://github.com/Particular/NServiceBus.Transport.Msmq/blob/develop/src/NServiceBus.Transport.Msmq/Persistence/SubscriptionStorage/MsmqSubscriptionStorage.cs#L52

@timbussmann @andreasohlund - What exactly do we need to the docs for Version 5? 
I do see this for v5:
https://github.com/Particular/NServiceBus/blob/5.2.24/src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs#L192

So what note do we want to specifically address V5?

**Comment by weralabaj** [comment]
> So what note do we want to specifically address V5?

Seems that @andreasohlund had some proposition?

**Comment by timbussmann** [comment]
> So the behavior in v6 and above is that duplicates will not be created at all in the first place as 

not exactly true. Duplicates can be created during endpoint runtime. The cleanup mechanism is only run at endpoint startup.

**Comment by andreasohlund** [comment]
Looking at this again I'd say that v6 is good since a restart of the endpoint will cleanup any duplicates.

v5 has no cleanup so entries will be building up when:

* [Subscribers change address](https://github.com/Particular/NServiceBus/blob/5.2.24/src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs#L87)
* Subsribers are decommisioned

Would we see this as something we need to patch due to startup getting slow or running out of disk?

My hunch is no since I can't see how you can change your topology so much that this would be an issue.

Would it be enough to tell users to "Use queue explorer etc and remove entries that contains addresses no longer used"

@SeanFeldman how did you stumble across this?

**Comment by SeanFeldman** [comment]
> @SeanFeldman how did you stumble across this?

Customer had an issue with it and I helped them.

**Comment by andreasohlund** [comment]
What was the issue? Slow startup? Disk space usage?

**Comment by SeanFeldman** [comment]
IIRC, it was about duplicate subscriptions that were not removed properly.

**Comment by andreasohlund** [comment]
Ok, but wat issues where those duplicates causing for the user? (Where they
trying to decommision a subscriber?)

**Comment by SeanFeldman** [comment]
They were bothered by the growing records w/o cleanup.

**Comment by indualagarsamy** [comment]
@SeanFeldman - can you add the support case number to the issue description? Thanks.

**Comment by andreasohlund** [comment]
@SeanFeldman given https://github.com/Particular/NServiceBus/blob/5.2.24/src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs#L87 can we conclude that the reason for the build up of duplicates was due to them moving subscribers around? but that would not really be duplicates but rather invalid subscriptions? (ie messages would be sent out to those invalid subscriber addresses?)

**Comment by janovesk** [comment]
These are not duplicates. They are old, outdated subscriptions when you move subscribers to a different endpoint/queue.

Just add a line saying old subscriptions must be cleaned up with Queue Explorer if you don't decommission endpoints correctly.

**Comment by indualagarsamy** [comment]
@janovesk - I agree. However, I am thinking, there's got to be a better way to clean up. I am wondering why not a powershell clean up command let that they can run so the subscriptions are removed. Don't we have a similar concept when we decommission a worker? In this case it should be simple, they just run the script and it removes the entry. Thoughts?

**Comment by andreasohlund** [comment]
Perhaps one script to list entries and one to "remove by id", those scripts
would be useful for all versions and not just v5?

**Comment by indualagarsamy** [comment]
@andreasohlund - Yes. That would make it more helpful.

**Comment by andreasohlund** [comment]
We could probably tweak
https://docs.particular.net/transports/msmq/operations-scripting?version=msmqtransport_1#return-message-to-source-queue-the-retry-helper-methods-in-powershell
pretty
easily to do a peek instead of a receive?

**Comment by indualagarsamy** [comment]
@andreasohlund - Yes, that's what I was thinking. We can add to our scripting docs.

**Comment by indualagarsamy** [comment]
And add a note in the documentation saying that it's the user responsibility to clean up subscriptions and point them to the script.

**Comment by SeanFeldman** [comment]
> can you add the support case number to the issue description? Thanks.

I couldn't locate the case and don't remember the customer name.

**Comment by andreasohlund** [comment]
So to summarize, action points are:

* Create a "list subscriptions" script for v5 and up
* Create a "remove subscription by id" script for v5 and up
* Make sure to link to those scripts from relevant places
* Add a note to the v5 version of https://github.com/Particular/docs.particular.net/blob/master/nservicebus/msmq/subscription-persistence.md to state that there can be duplicates and guide towards the scripts to deal with them

Did I get it right?

**Comment by weralabaj** [comment]
ping

**Comment by andreasohlund** [comment]
@indualagarsamy I remember that you and me talked about this, should we raise a new issue for the action points?

**Comment by mauroservienti** [comment]
in an attempt to understand where this issue stands:

- v5 is out of regular support now
- a note has been added describing the transport behavior in case of duplicate subscriptions

Do we need to do anything else or can this issue be closed?

**Comment by andreasohlund** [comment]
Since v6 auto removed duplicates I'd say we can close this
