### ISSUE TITLE
Feedback: 'Entity Framework caveats'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2875]
Feedback for 'Entity Framework caveats' https://docs.particular.net/nservicebus/sqlserver/entity-framework

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sqlserver/entity-framework.md

ping @Particular/sqlserver-transport-maintainers

Needs to be updated to EF Core

**Comment by SimonCropp** [comment]
actually give EDMX is no longer supported i think we should kill that page https://stackoverflow.com/a/39601869/53158

**Comment by MarcinHoppe** [comment]
I don't think it is a good idea to rush with retiring this content. There are a lot of people who are married to EF 6 for a long time. This content is still valuable for them.
