### ISSUE TITLE
Feedback: 'Scripting'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2880]
Isnt the transaction redundant here given it is one operation? https://docs.particular.net/nservicebus/sqlserver/operations-scripting#native-send-the-native-send-helper-methods-in-c

Feedback for 'Scripting' https://docs.particular.net/nservicebus/sqlserver/operations-scripting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sqlserver/operations-scripting.md

ping @Particular/sqlserver-transport-maintainers

**Comment by SimonCropp** [comment]
also isnt ` command.CommandType = CommandType.Text;` the default?

**Comment by tmasternak** [comment]
I think that tscope is even worse it runs in Serializable Isolation Level which can result in table lock.
CommandType.Text is default.

**Comment by SimonCropp** [comment]
fixed by https://github.com/Particular/docs.particular.net/commit/86e0fcc62fc2964e02b3c10bf1c7c92471104cab
