### ISSUE TITLE
Performance Counters enabled by default

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#2884]
Documentation on performance counters for the new package mentions the counters aren't enabled by default.
However because old perfcounters are still in NSB Core, 3 of the counters are still enabled by default.

We should update documentation to reflect this.

/cc @Particular/metrics-maintainers

**Comment by SimonCropp** [comment]
ping @Particular/metrics-maintainers

**Comment by seanfarmar** [comment]
After chatting to @Scooletz here are our thoughts:

It does not matter to the user/ops admin, as after they run the script all the required perf counters will be created and backwards compatible...

Thoughts?

**Comment by tmasternak** [comment]
> Documentation on performance counters for the new package mentions the counters aren't enabled by default.

@dvdstelt do you mean [this](https://docs.particular.net/nservicebus/operations/performance-counters#counters) in doco?

By `enabled` we mean that performance counter has been created?

**Comment by dvdstelt** [comment]
@tmasternak No, I mean that perfcounters in NSB6 are enabled by default. Because in core they are marked obsolete, but they are still activated by default because of backwards compatibility.

**Comment by dvdstelt** [comment]
PR merged
