### ISSUE TITLE
Feedback: 'Multiple storage accounts'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2889]
Feedback for 'Multiple storage accounts' https://docs.particular.net/nservicebus/azure-storage-queues/multi-storageaccount-support

Location in GitHub: https://github.com/Particular/docs.particular.net/edit/master/transports/azure-storage-queues/multi-storageaccount-support.md

This document only show how to add an additional storage account, but not how to send a message to that account.

ping @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
To add details: with `MessageEndpointMapping`s it was possible specify destination endpoint using "queue@connectionstring" convention. With Routing API, it doesn't seem to be possible and instead one has to do the following:

```c#
var accountRouting = transport.AccountRouting();
accountRouting.AddAccount("anotherAccount", "connectionstring");
//...
var sendOptions = new SendOptions(); 
sendOptions.SetDestination("queue@anotherAccount");
await endpoint.Send(new RecordingEvent(), sendOptions);
```

**Comment by yvesgoeleven** [comment]
Same for subscribing, today you cannot subscribe to events coming from another namespace anymore

**Comment by weralabaj** [comment]
@SeanFeldman @yvesgoeleven It's been a while since that issue was raised, do you want to address it quickly here or move to one of the Azure repos for tracking?

**Comment by yvesgoeleven** [comment]
@weralabaj I am working on this as we speak ;)

**Comment by weralabaj** [comment]
ping?

**Comment by yvesgoeleven** [comment]
@weralabaj This can be closed, forgot to close after the update (about a month ago)
