### ISSUE TITLE
Feedback: 'Using the In-Memory Bus'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2892]
Given 4.6 is no longer supported i think we should delete this page

Feedback for 'Using the In-Memory Bus' https://docs.particular.net/nservicebus/messaging/memory-transport

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/memory-transport.md

**Comment by weralabaj** [comment]
We still have pages for version 3 and 4 though, why this one should be an exception?

**Comment by SimonCropp** [comment]
@weralabaj we dont want people using it even if they are on 3 or 4

**Comment by weralabaj** [comment]
OK then let's just 🔥 it
