### ISSUE TITLE
Feedback: 'NHibernate Persistence'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2893]
Feedback for 'NHibernate Persistence' https://docs.particular.net/persistence/nhibernate/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/nhibernate/index.md

What versions of SQL Server are supported? There's mentioning in a [sample](https://docs.particular.net/samples/outbox/sqltransport-nhpersistence/#how-it-works):

> SQL Server 2008 and later

But no clear list in the doco. Thanks.

ping @Particular/nhibernate-persistence-maintainers

**Comment by MarcinHoppe** [comment]
Isn't this enough:

https://docs.particular.net/persistence/nhibernate/#supported-database-engines

?

**Comment by SeanFeldman** [comment]
Thanks @MarcinHoppe, I'm blind.
So we've got discrepancy between supported versions for SQL Server persistence and NHibernate persistence looks like. NHibernate supports version 2012 and up and do is [SQL persistence](https://docs.particular.net/persistence/sql/) , but talks about 2008 and up in samples. Will raise a seriousness issue.

**Comment by MarcinHoppe** [comment]
We should probably remove mentions of 2008 as it is out of mainstream support. A separate issue would work best.

**Comment by SeanFeldman** [comment]
Issue raised: https://github.com/Particular/docs.particular.net/issues/2894
