### ISSUE TITLE
Feedback: 'Outbox - SQL Transport and NHibernate'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#2894]
Feedback for 'Outbox - SQL Transport and NHibernate' https://docs.particular.net/samples/outbox/sqltransport-nhpersistence/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/outbox/sqltransport-nhpersistence/sample.md

With supported version 2012 and up, 2008 reference should be removed.

ping @Particular/sqlserver-transport-maintainers

**Comment by SzymonPobiega** [comment]
@SeanFeldman I still think is correct. We don't say we support 2008. This is just a pice of technical information about SQL Server itself. If we omit the version number it would not be correct.

**Comment by SeanFeldman** [comment]
@SzymonPobiega would it be less accurate if written in the following form:

> All the data manipulations happen atomically with supported versions of SQL Server, allowing multiple (but not overlapping) instances of SqlConnection to enlist in a single TransactionScope without the need to escalate to DTC.

**Comment by SzymonPobiega** [comment]
@SeanFeldman yeah, that might work.

**Comment by SzymonPobiega** [comment]
@seanfarmar done.
