### ISSUE TITLE
Feedback: 'Simple RavenDB Persistence Usage'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2897]
Tried running and got

```
System.Exception: Correlating on saga properties not marked as unique is not safe due to the
 high risk for stale results. Please add a [Unique] attribute to the 'OrderId' property on your
 'OrderSagaData' saga data class. If you still want to allow this please add
 .UsePersistence<RavenDBPersistence>().AllowStaleSagaReads() to your config
```

Feedback for 'Simple RavenDB Persistence Usage' https://docs.particular.net/samples/ravendb/simple/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/ravendb/simple/sample.md

ping @Particular/ravendb-persistence-maintainers

**Comment by DavidBoike** [comment]
@SimonCropp The NSB.Raven V3 or V4 version? Assuming V3? I just smoke-tested the V4 one a few days ago.

**Comment by SimonCropp** [comment]
sorry yes v3

**Comment by SimonCropp** [comment]
also shouldnt v3 use https://www.nuget.org/packages/RavenDB.Client.UniqueConstraints/3.5.3

**Comment by mauroservienti** [comment]
I just downloaded the V3 sample and it worked as expected, any more info @SimonCropp?

And no the `Unique Constraints` bundle is not needed, we have our own Unique documents mechanism, exactly to avoid that customers needs to deal with RavenDB bundles setup.

**Comment by SimonCropp** [comment]
ok. i cant repo. so no idea what happened there. will close this one for now
