### ISSUE TITLE
for all SQL samples create required DB and schema at startup

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2909]
as is done here https://docs.particular.net/samples/sqltransport-sqlpersistence/#prerequisites

 * [x] https://docs.particular.net/samples/routing/custom/
 * [x] https://docs.particular.net/samples/entity-framework/
 * [x] https://docs.particular.net/samples/outbox/multi-tenant/
 * [x] https://docs.particular.net/samples/outbox/sql/
 * [x] https://docs.particular.net/samples/saga/nh-custom-sagafinder/
 * [x] https://docs.particular.net/samples/saga/migration/
 * [x] https://docs.particular.net/samples/saga/sql-sagafinder/
 * [x] https://docs.particular.net/samples/sqltransport-nhpersistence/
 * [x] https://docs.particular.net/samples/sqltransport-sqlpersistence/
 * [x] https://docs.particular.net/samples/sql-persistence/simple/
 * [x] https://docs.particular.net/samples/sql-persistence/saga-rename/
 * [x] https://docs.particular.net/samples/sql-persistence/transitioning-correlation-ids/
 * [x] https://docs.particular.net/samples/sqltransport/native-timeout-migration/
 * [x] https://docs.particular.net/samples/sqltransport/multi-instance/
 * [x] https://docs.particular.net/samples/sqltransport/native-integration/
 * [x] https://docs.particular.net/samples/sqltransport/simple/
 * [x] https://docs.particular.net/samples/sqltransport/store-and-forward/

**Comment by SimonCropp** [comment]
@SzymonPobiega so we really need all 3 outbox samples showing the same scenario? and does ef add any value when we have this https://docs.particular.net/samples/sqltransport-sqlpersistence/#receiver-project-accessing-the-ambient-database-details

I was thinking of consolidating them to one "outbox with sql" sample that uses sql transports and persistences. and remove the ef and point to the non-outbox ef code

cc @Particular/nhibernate-persistence-maintainers @Particular/sqlpersistence-maintainers

**Comment by SzymonPobiega** [comment]
@SimonCropp makes sense.

**Comment by SzymonPobiega** [comment]
@SimonCropp do you want me to take care of it?

**Comment by SimonCropp** [comment]
@SzymonPobiega nah doing it now
