### ISSUE TITLE
mandatory UseTransport needs to be in the upgrade guide for v7

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2929]
https://docs.particular.net/nservicebus/upgrades/6to7/

**Comment by bording** [comment]
Actually, looks like this is already in there: https://docs.particular.net/nservicebus/upgrades/6to7/#default-transport

**Comment by SimonCropp** [comment]
perhaps we need the code `UseTransport` in there? given that is what i searched for

**Comment by bording** [comment]
@SimonCropp I see the changes you made here. Considering that there's an MSMQ section right above the "Default Transport" section, it seems a bit redundant.

**Comment by SimonCropp** [comment]
@bording i still want the UseTransport  in there for search-ability. do u want to have a go at an alternative PR. I also think it would be good to have the text of the runtime exception, when there is no transport defined, so that if people google it they will hit this page

**Comment by bording** [comment]
@SimonCropp I was thinking about it a bit more, and having a bit of redundancy probably isn't a bad thing anyway, since consuming the entire document from top to bottom isn't the only way it can be used, as you've mentioned, searching for an error that you've into is another way.

**Comment by bording** [comment]
Having the exception info in there as well seems like a good idea too
