### ISSUE TITLE
Scripting tag or an overview

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2932]
We have alot of doco/guidance on scripting but it is not really discoverable it would help if atleast all pages related to scripting would have the tag *Scripting* or even better. A scripting page mentioning all components supporting scripting things like: none, manual guidance or full script generation.

**Comment by SimonCropp** [comment]
-1 for a tag. very few customers would ever want to view a list of all scripting pages for all transports and persistences. 

re "a scripting page" isnt this pretty much that https://docs.particular.net/nservicebus/operations/  ?

**Comment by SimonCropp** [comment]
@ramonsmits thoughts?

**Comment by ramonsmits** [comment]
@SimonCropp yes, seems like a good overview and better that a tag.  Is there an easy way to get higher into the hierarchy to get to that page. It is like a TOC that should be in the right menu? Maybe we can improve the discoverability of that page? When I search for "Scripting" that currently is not the top result.

**Comment by SimonCropp** [comment]
>  Is there an easy way to get higher into the hierarchy to get to that page

I dont understand this statement

> It is like a TOC that should be in the right menu

it is in the menu

> Maybe we can improve the discoverability of that page? When I search for "Scripting" that currently is not the top result.

currently no there is not a way to tweak search results for a single page

**Comment by ramonsmits** [comment]
@SimonCropp What I meant is that if you landed on one scripting page, it is likely the viewer is interested in other scripting pages to. As the page is part of a persister or transport and not part of scripting or operations there is no easy path to other guidance related to scripting.

**Comment by SimonCropp** [comment]
> What I meant is that if you landed on one scripting page, it is likely the viewer is interested in other scripting pages to

add a related to each of the scripting pages that links back to the index?

**Comment by SimonCropp** [comment]
i added a link back operations on all of the relevant pages
