### ISSUE TITLE
Improve ServiceControl Information Architecture

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#2935]
Currently the ServiceControl documentation is split up into Configuration and Management sections. As the number of different components under the ServiceControl umbrella increases (Management Utility, ServiceControl instance, Monitoring instance, Transport Adapter), this way of organizing the docs is getting more and more confusing.

I think the menu structure needs to be reviewed for ServiceControl. 

## Plan of Attack
- [x] Come up with a high-level structure
- [x] Rearrange menu (without moving content)
- [x] Move content to match menu (requires adding redirects)

**Comment by mikeminutillo** [comment]
Proposed new structure:

- **index**: overview of ServiceControl. Lists all of the components and how they relate to the rest of the platform
- **ServiceControl Instance**
  - **index**: high level overview of what the ServiceControl instances are and how they fit into a solution
  - **Planning**: things to consider before installation. Capacity management, Security advice, etc.
  - **Installation**: the process of how to install. Maybe sub-sections for different settings, for Powershell
  - **Management**: Common tasks like backing up
  - **Troubleshooting**: what to do when things go wrong, where are the log files, etc.
- As above for Monitoring instances (when they are released)
- As above for Transport Adapters
- **Integration**
  - **index**: overview of all of the integration options
  - **Heartbeats**: plugin and associated integration events
  - **Custom Checks**: plugin and associated integration events
  - **Saga Audit**: should this be documented in ServiceControl at all or just in ServiceInsight?
  - **Metrics**: plugin

**Comment by mikeminutillo** [comment]
@Particular/servicecontrol-maintainers ☝️ thoughts?

**Comment by mikeminutillo** [comment]
Created a PR with the updated structure https://github.com/Particular/docs.particular.net/pull/2936

**Comment by mikeminutillo** [comment]
Updated to fill in some gaps. It now looks like this:

- [ServiceControl](https://docs.particular.net/servicecontrol)
  - [ServiceControl instances](https://docs.particular.net/servicecontrol/servicecontrol-instances)
    - [Planning](https://docs.particular.net/servicecontrol/servicecontrol-in-practice)
      - [Capacity Planning](https://docs.particular.net/servicecontrol/capacity-and-planning)
      - [Security](https://docs.particular.net/servicecontrol/securing-servicecontrol)
      - [Non-Priveleged Accounts](https://docs.particular.net/servicecontrol/configure-non-privileged-service-account)
    - [Installation](https://docs.particular.net/servicecontrol/installation)
      - [Installing Silently](https://docs.particular.net/servicecontrol/installation-silent)
      - [Managing via PowerShell](https://docs.particular.net/servicecontrol/installation-powershell)
      - [Cluster Deployment](https://docs.particular.net/servicecontrol/deploying-servicecontrol-in-a-cluster)
      - [Licensing](https://docs.particular.net/servicecontrol/license)
      - [Settings](https://docs.particular.net/servicecontrol/creating-config-file)
      - [Overriding the host identifier](https://docs.particular.net/nservicebus/hosting/override-hostid)
      - [RavenDB Location](https://docs.particular.net/servicecontrol/configure-ravendb-location)
      - [Configure the URI](https://docs.particular.net/servicecontrol/setting-custom-hostname)
      - [Logging](https://docs.particular.net/servicecontrol/logging)
      - [Forwarding Queues](https://docs.particular.net/servicecontrol/errorlog-auditlog-behavior)
      - [Configuring MSMQ](https://docs.particular.net/servicecontrol/configuring-msmq)
    - Management
      - [Data Expiration](https://docs.particular.net/servicecontrol/how-purge-expired-data)
      - [Backup](https://docs.particular.net/servicecontrol/backup-sc-database)
      - [Compacting database](https://docs.particular.net/servicecontrol/db-compaction)
    - [Troubleshooting](https://docs.particular.net/servicecontrol/troubleshooting)
      - [Expose internal database](https://docs.particular.net/servicecontrol/use-ravendb-studio)
  - [Integration](https://docs.particular.net/servicecontrol/integration)
    - [Plugins](https://docs.particular.net/servicecontrol/plugins)
      - [Heartbeats](https://docs.particular.net/servicecontrol/plugins/heartbeat)
      - [Custom checks](https://docs.particular.net/servicecontrol/plugins/custom-checks)
      - [Saga audits](https://docs.particular.net/servicecontrol/plugins/saga-audit)
    - [Integration events](https://docs.particular.net/servicecontrol/contracts)
    - [Transport adapter](https://docs.particular.net/servicecontrol/transport-adapter)
      - [Incompatible transport features](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features)
      - [dotnet new Template](https://docs.particular.net/servicecontrol/transport-adapter/template)

**Comment by weralabaj** [comment]
@mikeminutillo seems we forgot to close this issue, [PR has been merged](https://github.com/Particular/docs.particular.net/pull/2936). If anything else is left to change, feel free to reopen.
