### ISSUE TITLE
Feedback: 'Performance Tuning'

### ISSUE THREAD

**Issue by dasjestyr** [Particular/docs.particular.net#2939]
Feedback for 'Performance Tuning' https://docs.particular.net/transports/azure-service-bus/performance-tuning

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/performance-tuning.md

ping @Particular/azure-maintainers 

The doc talks about `MessagingFactories().NumberOfMessagingFactoriesPerNamespace()` and `NumberOfClientsPerEntity()` in two different contexts (send and receive) but have different recommendations on `MessagingFactories().NumberOfMessagingFactoriesPerNamespace()` values. I'm assuming these are the same configuration methods, but if the endpoint is set up to send and receive, then what's the recommendation? The higher one? The lower one? Something else? I'm a little confused. 

Also, it has recommendations of `desired concurrency per receiver * number of recievers` but does not define (or link to definition) of a "receiver". I'm assuming this is the number of instances  of this endpoint that are running? Some clarification would help.

**Comment by dasjestyr** [comment]
It appears that there is a little more explanation in the code examples, but I never would have thought to look there for high level documentation. I'd suggest at least moving or copying it to this doc.

**Comment by weralabaj** [comment]
ping @Particular/azure-maintainers ☝️ 

Maybe linking would be a good first step?

**Comment by danielmarbach** [comment]
@weralabaj thanks for pinging @Particular/azure-maintainers @yvesgoeleven originally wrote this page. We have currently limited availability. We'll see what we can do.

**Comment by danielmarbach** [comment]
@dasjestyr Thanks for your very valuable input. Especially documentation like the one you commented on can be really tricky to follow. Do you think the proposed changes in https://github.com/Particular/docs.particular.net/pull/2951 would clarify it?
