### ISSUE TITLE
Feedback: 'In Memory Persistence'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2940]
Feedback for 'In Memory Persistence' https://docs.particular.net/persistence/in-memory

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/in-memory.md

ping @Particular/nservicebus-maintainers

This is problematic

> Because there is no clustering / replication happening between NServiceBus instances, when a process is down, all the information stored in the InMemory persistence of that process is lost.

"all the information stored in the InMemory persistence of that process is lost" is true, but it is not "because of no clustering / replication"

**Comment by timbussmann** [comment]
@SimonCropp yeah that seems to be an overcomplicated statement, how about: `All information stored in the InMemory persistence is discarded when the process ends`?

**Comment by SimonCropp** [comment]
@timbussmann LGTM
