### ISSUE TITLE
Feedback: 'Configuration Settings'

### ISSUE THREAD

**Issue by GooDVim** [Particular/docs.particular.net#2962]
Feedback for 'Configuration Settings' https://docs.particular.net/servicecontrol/creating-config-file

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/creating-config-file.md

> ServiceControl/MaxBodySizeToStore
>This setting exists in Version 1.6 and above. It allows the upper limit on body size to be configured.
>In Version 1.5.x and below ServiceControl only stores bodies of audit messages that are smaller than 100Kb.

The most recent version of ServiceControl is v1.41.2 (https://particular.net/downloads). It's a bit confusing which version is mention here.

**Comment by SimonCropp** [comment]
ping @Particular/servicecontrol-maintainers thoughts?

**Comment by WilliamBZA** [comment]
@goodvim the documentation refers to version 1.6 and 1.5, while the current is 1.42.2. Is the confusion around the new patch version (i.e. the `.2` part), or does it just seem odd since 1.6 is so far away from 1.42?

**Comment by GooDVim** [comment]
@WilliamBZA, the latest one. I tried to use the setting and it works but our version is less than 1.6 because it can't be 1.6 because current version is 1.42.2 and we downloaded ServiceControl some time ago.

**Comment by WilliamBZA** [comment]
`1.6.0` was released in August 2015, a very, _very_, long time ago. The current version is 42, which is much higher than 6, so I would expect the setting to work.

Can you perhaps rephrase your confusion? I'm struggling to understand how to change the documentation so that it makes more sense, perhaps if you explain which part is confusing in a different way I'll be able to understand.

**Comment by GooDVim** [comment]
Sorry, I read it initially not like 1.41.2 but as 1.4.12. May be because all other versions (ServiceInsight, ServicePulse) relatively small. Anyway it's definitely my fault.

**Comment by WilliamBZA** [comment]
I think there's some learnings here for the @Particular/servicecontrol-maintainers. Perhaps we need to standardise version schemes across SI, SC, and SP.
