### ISSUE TITLE
Windows performance documentation does not seem to be correct.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2992]
The Windows performance documentation does not seem to be correct.

 - https://docs.particular.net/nservicebus/operations/performance-counters?#counters

It now is missing the Windows Performence counters explanations which is present in the previous version (https://docs.particular.net/nservicebus/operations/performance-counters?version=perfcounters_1). If you follow the link to https://docs.particular.net/nservicebus/operations/metrics you also don't get any documentation about the guidance.

It is also a bit strange that we link to the metrics doco. All the doco about windows performance counters should be presented under that topic.

**Comment by ramonsmits** [comment]
@Particular/metrics-maintainers

**Comment by Scooletz** [comment]
For the record, this is the PR that introduced this split: https://github.com/Particular/docs.particular.net/pull/2644

**Comment by ramonsmits** [comment]
Metrics owns the probe (generator of a stream of values) but not what the performance counter package does with the probes like generating the actual metric of average counters and current counters.

Each has their own set of documentation and are not interchangeable.

**Comment by Scooletz** [comment]
@Particular/docs-maintainers Could you help "triage" this? What's the preferable approach?

**Comment by DavidBoike** [comment]
Perhaps there could be a 3rd page that is concerned only with what critical time, SLA violation, etc. are from an educational standpoint, using each one as a header, thus providing the ability to deep link.

Optionally, each concept could have a first paragraph "executive summary" of what that concept means be provided by an include.

Then each page could have a UL of the counters offered that deep-links to the concept page, and/or use the include to offer a short description, depending upon what's appropriate for each actual metric-related component.

**Comment by weralabaj** [comment]
@Particular/metrics-maintainers Do you need a hand, or are you happy with @DavidBoike 's suggestion?

**Comment by Scooletz** [comment]
I'm happy with the suggestion, but I can tackle this as soon as we release cohort of Metrics related packages.

**Comment by Scooletz** [comment]
Addressed with https://github.com/Particular/docs.particular.net/pull/3451
