### ISSUE TITLE
Feedback: 'Multi-Site Deployments'

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#3000]
Feedback for 'Multi-Site Deployments' https://docs.particular.net/nservicebus/gateway/multi-site-deployments

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/gateway/multi-site-deployments.md

ping @Particular/nservicebus-maintainers

### Publish-subscribe in the gateway

All we currently state wrt pub/sub over the gateway is:

> All cross-site interactions are performed internally to a service, so publish and subscribe are not supported across gateways.

It would be good to elaborate why pub/sub over the gateway is not a good idea and why NServiceBus does not support it.

**Comment by weralabaj** [comment]
@janovesk Since you're an expert, can you add a short paragraph?

**Comment by weralabaj** [comment]
That has been addressed in https://github.com/Particular/docs.particular.net/pull/3480
