### ISSUE TITLE
Feedback: 'OWIN HTTP Message Pass Through'

### ISSUE THREAD

**Issue by pingcrosby** [Particular/docs.particular.net#3003]
Feedback for 'OWIN HTTP Message Pass Through' https://docs.particular.net/samples/web/owin-pass-through/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/owin-pass-through/sample.md

ping @Particular/nservicebus-maintainers

**The sample omits how to return a Response to the client** - can you show how we can send back a valid HTTP status

**Comment by mikeminutillo** [comment]
@pingcrosby by default the response status code will be set to 200 if everything runs without exception. If you need to set some other status code, I believe you just need to set the `owin.ResponseStatusCode` key in the environment dictionary to an integer value that matches the HTTP status code.

**Comment by mikeminutillo** [comment]
@pingcrosby I have verified that setting `owin.ResponseStatusCode` works. You can see this in action in a Pull Request here https://github.com/Particular/docs.particular.net/issues/3009

**Comment by SimonCropp** [comment]
@mikeminutillo thanks

@pingcrosby good catch
