### ISSUE TITLE
Feedback: 'Type Not Registered in the Serializer'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3004]
Feedback for 'Type Not Registered in the Serializer' https://docs.particular.net/nservicebus/serialization/type-was-not-registered

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/serialization/type-was-not-registered.md

@Particular/nservicebus-maintainers i dont think this page needs to exist anymore??

**Comment by bording** [comment]
The page certainly seems a bit out of place. Do we have any history about why the page was added? Were we getting a lot of people having that issue?

**Comment by SimonCropp** [comment]
i dont think we have had that issue since early v5 days https://groups.google.com/forum/#!searchin/particularsoftware/%22Not$20Registered$20in$20the$20Serializer%22%7Csort:date

**Comment by bording** [comment]
Based on that, I think it would be safe to get rid of.
