### ISSUE TITLE
Feedback: 'Monitor 3rd party systems with custom checks'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3031]
Feedback for 'Monitor 3rd party systems with custom checks' https://docs.particular.net/samples/servicecontrol/monitoring3rdparty/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/servicecontrol/monitoring3rdparty/sample.md

ping @Particular/servicecontrol-maintainers

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by WilliamBZA** [comment]
PR Submitted

**Comment by SimonCropp** [comment]
thanks @WilliamBZA
