### ISSUE TITLE
Feedback: add learning transport to 'Transport Transactions'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3044]
Feedback for 'Transport Transactions' https://docs.particular.net/transports/transactions#transactions-transaction-levels-supported-by-nservicebus-transports

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/transactions.md

ping @Particular/nservicebus-maintainers

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
Should now be covered by https://github.com/Particular/docs.particular.net/pull/3121
