### ISSUE TITLE
Feedback: 'Azure Storage Persistence'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3052]
Feedback for 'Azure Storage Persistence' https://docs.particular.net/persistence/azure-storage/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/azure-storage/index.md

Need to add a comment about limitations on values Partition and Row keys can have to avoid user surprises. More details here: https://groups.google.com/forum/m/#!topic/particularsoftware/5PyZSTlk7BE

ping @Particular/azure-maintainers

**Comment by weralabaj** [comment]
@SeanFeldman Seems to be a while - do you want to get it done quickly here or move to the ASP repo for tracking?

**Comment by SeanFeldman** [comment]
Can just add a note with a link to the MSFT doco (https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model, "Characters Disallowed in Key Fields" section).

**Comment by weralabaj** [comment]
Ok so why not just do it? ;)

**Comment by SeanFeldman** [comment]
![image](https://user-images.githubusercontent.com/1309622/31357720-2473487a-ad00-11e7-8520-3ef4de69456f.png)
