### ISSUE TITLE
Conflicting NServiceBus.Host logging advice

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3054]
this https://docs.particular.net/nservicebus/logging/#when-to-configure-logging

> When to configure logging: At the start of the constructor of the class that implements IConfigureThisEndpoint when using NServiceBus.Host.

seems to conflict with this https://docs.particular.net/nservicebus/hosting/nservicebus-host/logging-configuration#logging-configuration-via-endpoint-configuration

```c#
public class YourProfileLoggingHandler :
    NServiceBus.Hosting.Profiles.IConfigureLoggingForProfile<YourProfile>
{
    public void Configure(IConfigureThisEndpoint specifier)
    {
        // setup logging infrastructure
        LogManager.Use<Log4NetFactory>();
    }
}
```

ping @Particular/host-maintainers

**Comment by SimonCropp** [comment]
ping @Particular/host-maintainers

**Comment by SimonCropp** [comment]
@Particular/host-maintainers any interest in fixing this?

**Comment by SimonCropp** [comment]
ping @Particular/host-maintainers

**Comment by seanfarmar** [comment]
I'll take that

**Comment by seanfarmar** [comment]
https://github.com/Particular/docs.particular.net/pull/3181

**Comment by seanfarmar** [comment]
Should we remove this sample for the host v7 and above?

https://docs.particular.net/samples/logging/hostprofiles/

**Comment by weralabaj** [comment]
@seanfarmar so has the issue been resolved? can we close? or there are still some things to change left?

**Comment by seanfarmar** [comment]
@weralabaj I think we can close this, thanks

**Comment by SimonCropp** [comment]
@Particular/host-maintainers  just to be clear the Conflicting logging advice still exists. if you are happy to leave incorrect doco in place because "the host is being deprecated" that is fine. but if that is the case can u please communicate to everyone that "no host doco will be fixed moving forward" and how people should handle communications with customers when they make decisions based on this incorrect doco.

**Comment by seanfarmar** [comment]
@SimonCropp can you help with more details please, and point out what needs to be changed?

**Comment by SimonCropp** [comment]
well if i follow "configure logging in the  constructor of the class that implements IConfigureThisEndpoint" then i cannot use IConfigureLoggingForProfile.

**Comment by seanfarmar** [comment]
@ramonsmits and me are working on this
