### ISSUE TITLE
Feedback: 'Configuring RavenDB DTC' how to dispose

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3055]
Feedback for 'Configuring RavenDB DTC' https://docs.particular.net/persistence/ravendb/manual-dtc-settings#configuration-by-convention

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/ravendb/manual-dtc-settings.md

ping @Particular/ravendb-persistence-maintainers

one more for "store should be disposed". how should a dangling store be clean up when it is created in INeedInitialization

**Comment by DavidBoike** [comment]
That's an interesting one for sure. Perhaps we should punt on this pending https://github.com/Particular/PlatformDevelopment/issues/686?

Do we have any hook for endpoint shutdown other than a FeatureStartupTask?

**Comment by mauroservienti** [comment]
If using the [Host](https://docs.particular.net/nservicebus/hosting/nservicebus-host/#when-endpoint-instance-starts-and-stops) there is `IWantToRunWhenEndpointStartsAndStops`, otherwise it depends on where the DocStore is created, it can be stored in the IoC container and then disposed from there.

**Comment by DavidBoike** [comment]
Added a reminder for @mauroservienti and I to discuss this when he returns Sept 18.

**Comment by DavidBoike** [comment]
Fixed with #3227
