### ISSUE TITLE
Feedback: 'Using Wormhole to send messages between distributed sites'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3068]
Feedback for 'Using Wormhole to send messages between distributed sites' https://docs.particular.net/samples/wormhole/ping-pong/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/wormhole/ping-pong/sample.md

ping @SzymonPobiega 

use an admin manifest to make the below unecessary

> Open the solution in Visual Studio running as Administrator because the gateways need to register the listening URL, or add the registrations manually:

**Comment by SzymonPobiega** [comment]
I've configured the manifests files you added in https://github.com/Particular/docs.particular.net/pull/3074 but it does not solve the problem. The only thing it does is shows the prompts to restart VS. So I still think it makes sense to include that note in the description to save users the restart. The manifest will just prevent them running into permissions-related exception when starting up.

**Comment by SimonCropp** [comment]
ok
