### ISSUE TITLE
update azure samples to the new project system

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3072]
related to https://github.com/Particular/PlatformDevelopment/issues/1414

@Particular/azure-maintainers  so this will mean we no longer manually have to run the nuget.linq script. and no longer need to handle redirects

The majority of other samples are done. but i was not sure how i should update the azure samples. do you want me to do a PR which is my "best guess" or would you like to handle it yourselves?

Samples
- [x] azure-service-bus NSB v6 @SeanFeldman
- [x] azure-service-bus-long-running NSB v6 @SeanFeldman
- [x] blob-storage-databus NSB v6 @SeanFeldman
- [x] custom-sanitization-asb NSB v6 @SeanFeldman
- [x] native-integration-asb NSB v6 @SeanFeldman
- [x] polymorphic-events-asb NSB v6 @SeanFeldman
- [x] storage-queues NSB v6 @SeanFeldman
- [x] azure-service-fabric-routing @danielmarbach
- [x] custom-partitioning-asb @danielmarbach
- [x] performance-tuning-asb @danielmarbach
- ~[ ] shared-host @danielmarbach~ Due to outdated msbuild targets of the cloud services it is not possible to upgrade to new csproj
- [x] storage-persistence @danielmarbach
- [x] azure-service-bus NSB v5 @seanfeldman
- [x] blob-storage-databus NSB v5 @seanfeldman
- [x] native-integration-asb NSB v5 @seanfeldman
- [x] polymorphic-events-asb NSB v5 @seanfeldman
- [x] storage-queues NSB v5 @seanfeldman

**What is needed to be done**
- Remove binding redirects
- Remove package.config files
- Remove inferred packages

**Comment by yvesgoeleven** [comment]
@SimonCropp PR is fine, I can pick it up on wednesday

**Comment by SeanFeldman** [comment]
I've started with the changes @SimonCropp 
Will push a PR when have it all or need to hand over.
Loving removing app.config files 😺

**Comment by SeanFeldman** [comment]
I've listed all Azure samples in the general description.

**Comment by SeanFeldman** [comment]
**Update**

[7/12](https://github.com/Particular/docs.particular.net/issues/3072#issue-250000419) are converted and smoke tested.

**Comment by SimonCropp** [comment]
@SeanFeldman awesome. need any help?

**Comment by SeanFeldman** [comment]
I've pinged @Particular/azure-maintainers to help to complete this task. It takes time and we should smoke test each sample to make sure they are not broken. If you have spare cycles, I've listed the remaining samples in the general description.

**Comment by danielmarbach** [comment]
Cannot migrate v5 cloud host sample. I get

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project 'C:\p\docs.particular.net\samples\azure\shared-host\CloudServicesHost_6\HostWorker\HostWorker.csproj' targets '.NETFramework,Version=v4.6.1'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'.	HostCloudService	C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets	87

**Comment by danielmarbach** [comment]
Interesting with verbose output I can see that the framework moniker is detected properly

```
3>Target "AssignProjectConfiguration" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" from project "C:\p\docs.particular.net\samples\azure\shared-host\CloudServicesHost_6\HostCloudService\HostCloudService.ccproj" (target "ResolveReferences" depends on it):
3>	Set Property: OnlyReferenceAndBuildProjectsEnabledInSolutionConfiguration=true
3>	Set Property: ShouldUnsetParentConfigurationAndPlatform=true
3>	Task "AssignProjectConfiguration"
3>		Task Parameter:
3>    ProjectReferences=
3>        ..\HostWorker\HostWorker.csproj
3>                Name=HostWorker
3>                OutputItemType=
3>                Private=True
3>                Project={07fdac8f-a69d-4a5c-aba1-daec52a649fb}
3>                ReferenceSourceTarget=ProjectReference
3>                RoleName=HostWorker
3>                RoleTargetFrameworkMoniker=net461
3>                RoleType=Worker
3>                Targets=
3>                UpdateDiagnosticsConnectionStringOnPublish=True
3>		Task Parameter:CurrentProject=C:\p\docs.particular.net\samples\azure\shared-host\CloudServicesHost_6\HostCloudService\HostCloudService.ccproj
3>		Task Parameter:CurrentProjectConfiguration=Debug
3>		Task Parameter:CurrentProjectPlatform=AnyCPU
3>		Task Parameter:OutputType=Library
3>		Task Parameter:ResolveConfigurationPlatformUsingMappings=False
3>		Task Parameter:SolutionConfigurationContents=<SolutionConfiguration>
```

**Comment by danielmarbach** [comment]
Really strange the second build always work but still shows the error. Then if you rebuild again it fails. I tried adding

      <RoleTargetFramework>v4.6</RoleTargetFramework>

and 

      <RoleTargetFrameworkMoniker>net461</RoleTargetFrameworkMoniker>

but that didn't help

**Comment by danielmarbach** [comment]
@SimonCropp do you have any ideas? Should we just leave it as is?

**Comment by SeanFeldman** [comment]
I've updated NSB v5 versions of all the samples that have upgraded (missed those out).
Once @danielmarbach is done, we're good to merge PR and close this issue.

**Comment by SimonCropp** [comment]
@danielmarbach 

>do you have any ideas? Should we just leave it as is?

i looked into it. it looks like under the covers the msbuild imports + referencing logic for cloud services conflicts with the target framework version checking in the new csproj system. TBH i am not sure what to do here. azure cloud services are on the way out, i doubt that project system will be fixed any time soon if at all.

so we cant update those samples to the new project system now. which results in a bit of a maintenance debt. my suggestion (IMO) would be for the @Particular/azure-maintainers to, as soon as possible, deprecate that sample, and possible any of the underlying nuget that target cloud services.

**Comment by SeanFeldman** [comment]
Agreed.

I'm in favour of leaving that sample as-is until we can deprecate and
retire the package.

**Comment by danielmarbach** [comment]
I'm good with that because investing more time here would be a wasted effort. I already lost some serious hair over this :) Will strikethrough the checkbox and work on the last item

**Comment by SimonCropp** [comment]
@SeanFeldman @danielmarbach thank heaps

**Comment by danielmarbach** [comment]
Thank you @SimonCropp for your help

**Comment by SeanFeldman** [comment]
👍 to all
