### ISSUE TITLE
Update web sample projects to new VS 2017 system

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3078]
* [ ]  \web\asp-mvc-application\
 * [ ]  \web\asp-web-application\
 * [ ]  \web\owin-pass-through\
 * [ ]  \web\send-from-mvc-controller\
 * [ ]  \web\wcf-callbacks\
 * [ ] \callbacks\
 * [ ] \show-case\on-premise

**Comment by mauroservienti** [comment]
I'll take these. Is the goal to update everything to .NET Core, and also to ASP.Net / MVC Core?

**Comment by SimonCropp** [comment]
still net 461. but using the new csproj system

**Comment by mauroservienti** [comment]
I played a little bit with the first one, `asp-mvc-application`, and it sounds like it cannot be upgraded to the new project system without changing everything to `.NET Core`.

* the new project system has no concept of "web projects"
* they are just console apps that create and run a `WebHostBuilder` instance
* `WebHostBuilder` is `ASP.Net Core`
* `WebHostBuilder` starts from the assumption that there is a `Startup` class and not the `Global.asax` file


it seems that changing web app project type to the new project system requires also to bring in the whole ASP.Net Core stack for web apps (still hosted and run on full fx) with all the changes required to the way samples are designed. Is this what we want?

**Comment by MarcinHoppe** [comment]
If we go with porting to ASP.NET Core 2.0 on the full framework, we also need to look into recommending hosting NServiceBus endpoints as `IHostedService`s.

**Comment by SimonCropp** [comment]
ASP.NET Core has been out for 6 months. i am happy updating all sample to it

**Comment by mikedevbo** [comment]
Official support for AspNet.Mvc.5.* and new csproj format won't be so quickly:
- long story -> https://github.com/dotnet/project-system/issues/2670
- short story -> https://github.com/dotnet/project-system/blob/master/docs/repo/roadmap.md (Release 16.0)

There is a workaround -> https://github.com/aspnet/Home/issues/1978#issuecomment-330894604.
I converted **send-from-mvc-controller** sample and it works quite well. The only difference is to manual run URL in browser after iss express starts:
- https://github.com/mikedevbo/docs.particular.net/blob/mikedevbo-samples-web-newcsproj/samples/web/send-from-mvc-controller/Core_6/WebApplication/WebApplication.csproj

I can convert other web samples and versions and send pull request. Let me know what you think ?

**Comment by mauroservienti** [comment]
hey @mikedevbo thanks for the links and the sample. One question: isn't https://github.com/aspnet/Home/issues/1978#issuecomment-355378614 a blocker?

> The biggest problem (at least for me) is that Visual Studio selects the wrong Razore editor (ASP.NET Core instead of ASP.NET), which makes editing "classic" .cshtml stuff quite impossible. And I've still no idea how to change that...

If I get it correctly that will make editing or evolving samples, or even playing with them for users, much harder.

**Comment by mikedevbo** [comment]
hi @mauroservienti 
Yes you're right. It's a blocker. Additionally even though build is successful and application starts there are error messages in error list tab about missing type or namespace name 'AspNetCore' so this is another blocker I think. Sorry I didn't look carefully.

**Comment by bharathpbk** [comment]
unable to debug global.asax file in Vs2017 with Loca lIIS

**Comment by mauroservienti** [comment]
hi @bharathpbk,

> unable to debug global.asax file in Vs2017 with Loca lIIS

is this an issue you're facing with a specific sample? if that's the case, which one?

**Comment by weralabaj** [comment]
@mauroservienti Since you were involved in this issue, can you advise on what should be done here?

**Comment by mauroservienti** [comment]
nothing really can be done, we cannot use the new project system on non-NET Core web application. The only option is to migrate samples to NET Core, but I don't think we should. We should this samples as they are, on the old project system, and craft new samples for NET Core

**Comment by weralabaj** [comment]
OK https://github.com/Particular/docs.particular.net/issues/3770
