### ISSUE TITLE
Feedback: 'Using NServiceBus in an ASP.NET Core WebAPI Application'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3086]
Feedback for 'Using NServiceBus in an ASP.NET Core WebAPI Application' https://docs.particular.net/samples/web/send-from-aspnetcore-webapi/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/send-from-aspnetcore-webapi/sample.md

ping @Particular/nservicebus-maintainers

update to AspNetCore.Mvc 2 https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/

**Comment by timbussmann** [comment]
should that be part of the .net core release project?

**Comment by MarcinHoppe** [comment]
👍 for managing doco work under the same umbrella as everything else related to .NET Core.

**Comment by SimonCropp** [comment]
nope this is not about net core. it is just updating the nuget but still running on net461

**Comment by MarcinHoppe** [comment]
OK, got it.

**Comment by mikedevbo** [comment]
Is this issue to close ? I see references to newest packages:
`<PackageReference Include="Microsoft.AspNetCore" Version="2.*" />`
`<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.*" />`

**Comment by weralabaj** [comment]
yes, seems so, thanks @mikedevbo
