### ISSUE TITLE
move EnableLegacyMultiInstanceMode to upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3105]
@Particular/sqlserver-transport-maintainers when adding snippets for sql v4 i hit a build error for EnableLegacyMultiInstanceMode

so i excluded that file for now https://github.com/Particular/docs.particular.net/blob/master/Snippets/SqlTransport/SqlTransport_4/SqlTransport_4.csproj#L8

Can you move that to an upgrade guide.

**Comment by SzymonPobiega** [comment]
I think this is because I removed it prematurely for the .net core build. We haven't decided if we want to keep it or remove it in V4. It definitely can't go to the .net core binaries because the core does not support DTC and multi-instance relies on it. I guess we need to remove it also from the full .net build to stay consistent.

**Comment by SzymonPobiega** [comment]
@tmasternak @MarcinHoppe ☝️

**Comment by MarcinHoppe** [comment]
I think we need to bite the bullet and remove it.

**Comment by SzymonPobiega** [comment]
I was looking for bullet emoji but didn't find it :( 😞

**Comment by tmasternak** [comment]
As I understand it there is other option. So let's 🔥 it.

**Comment by SzymonPobiega** [comment]
Who's going to prepare a transition plan?

**Comment by SimonCropp** [comment]
@Particular/sqlserver-transport-maintainers bump. given we r in public beta this should really be done asap

**Comment by MarcinHoppe** [comment]
I will not have the capacity to work on this at least until the end of this week.

@SzymonPobiega @tmasternak Any chance you can take care of this?

**Comment by tmasternak** [comment]
I can work on this no sooner than Friday. I think that @SzymonPobiega is in the same boat - we deliver workshop on Thursday.

**Comment by SzymonPobiega** [comment]
I'll handle this today.

**Comment by SzymonPobiega** [comment]
Fixed via https://github.com/Particular/docs.particular.net/pull/3266
