### ISSUE TITLE
Add sample for MSMQ persistence

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3110]
ping @Particular/msmq-transport-maintainers

**Comment by andreasohlund** [comment]
How about just modifying the existing MSMQ simple sample to use msmq for substorage?

https://github.com/Particular/docs.particular.net/blob/master/samples/msmq/simple/MsmqTransport_1/Sample/Program.cs#L23

**Comment by indualagarsamy** [comment]
@andreasohlund - I am on the fence on adding it to the simple sample. If no one else has any objections let's go for it. My thoughts are, I don't want users to automatically assume and think that the MSMQ persistence is the right persistence to use for MSMQ transport without even considering other persistence choices.

**Comment by andreasohlund** [comment]
Fair point but right now it uses InMemory with is even worse from a
production readiness standpoint?

**Comment by indualagarsamy** [comment]
@andreasohlund - Samples are not meant to be production ready. https://docs.particular.net/samples/#not-production-ready

InMemory makes that even more clear that its not production ready making the user think about persistence, on the contrary, MSMQ persistence might seem that it is and might not get further thought.

**Comment by SimonCropp** [comment]
@andreasohlund i dont see what we gain by mixing them. it is pretty easy to create a new sample

**Comment by andreasohlund** [comment]
Talked to @SimonCropp about this, will create a separate sample

**Comment by andreasohlund** [comment]
PR raised https://github.com/Particular/docs.particular.net/pull/3237
