### ISSUE TITLE
Add doco about Legacy changes for MSMQ persistence

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3111]
* When and why it was made Legacy
 * Why it is now no longer legacy
 * caveats about when / "when not to" use it

## Plan of attack

- [x] Check if there are any public types in the legacy namespace- [yes](https://github.com/Particular/NServiceBus/blob/6.4.0/src/NServiceBus.Core/Persistence/Msmq/MsmqPersistence.cs)
- [x] Add obsolete attributes on public types in old namespaces - https://github.com/Particular/NServiceBus/pull/4945 and https://github.com/Particular/NServiceBus.Transport.Msmq/pull/42
- [x] Update upgrade guide accordingly. - https://github.com/Particular/docs.particular.net/pull/3203

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers @Particular/msmq-transport-maintainers

**Comment by andreasohlund** [comment]
@Particular/msmq-transport-maintainers will take this on

**Comment by SimonCropp** [comment]
someone on the msmq call said "other packages that got externalised do not have upgrade guides"

 * https://docs.particular.net/nservicebus/upgrades/azure-deprecation
 * https://docs.particular.net/nservicebus/upgrades/absdatabus-6to1
 * https://docs.particular.net/nservicebus/upgrades/externalize-perfcounters
 * https://docs.particular.net/nservicebus/upgrades/externalize-encryption

**Comment by SimonCropp** [comment]
re

> Check if there are any public types in the legacy namespace

https://github.com/Particular/NServiceBus/blob/6.4.0/src/NServiceBus.Core/Persistence/Msmq/MsmqPersistence.cs

**Comment by andreasohlund** [comment]
>someone on the msmq call said "other packages that got externalised do not have upgrade guides"

I was on the call and pretty sure @dvdstelt meant "all other packages that has been split has had a upgrade guide , lets use those as inspiration for the msmq one"

>Check if there are any public types in the legacy namespace

That was concluded in the call and we will add proper obsoletes

**Comment by janovesk** [comment]
Done
