### ISSUE TITLE
Run snippets tests as part of CI

### ISSUE THREAD

**Issue by adamralph** [Particular/docs.particular.net#3125]
Some snippets, e.g. those for RabbitMQ, contain NUnit tests. For one reason or another, they don't run as part of CI. They are marked as explicit currently. I'm not sure if simply removing that attribute will cause them to be run as part of CI or not.

Since they don't run as part of CI, they are often not run after making changes (I'd hazard a guess that this happens the vast majority of the time). I only became aware of the existence of these tests after @SimonCropp [pointed them out to me today](https://github.com/Particular/docs.particular.net/pull/3120#issuecomment-324275948).

Clearly no-one had run these tests for some time, because they were failing on master. It took me a while to figure out [how to fix them](https://github.com/Particular/docs.particular.net/pull/3124).

**Comment by SimonCropp** [comment]
@adamralph unless someone from the @Particular/rabbitmq-transport-maintainers want to work on this i suggest u close it.

**Comment by WojcikMike** [comment]
@SimonCropp do I understand it correctly that you have nothing against including those tests into current CI build assuming that we will do the change?

**Comment by SimonCropp** [comment]
@WojcikMike i would prefer not to. i do not think the effort justifies the result. you could equally argue that all samples should have tests that pass, but is it just not worth the effort to write, maintain, and execute those tests. also those "tests" in question are not tests. they are only using test attribute as a helper to be able to smoke test the doco it targets. in the same way that many samples use a console to execute other "doco". bus as i am not a @Particular/rabbitmq-transport-maintainers or a @Particular/docs-maintainers the above is only IMO.

**Comment by WojcikMike** [comment]
@SimonCropp let us discuss it on the rabbit maintainer sync tomorrow then. My approach would be to either include them in the CI or to remove them. But let us wait for other opinions. Thanks for clarifying your point of view.

**Comment by SimonCropp** [comment]
if u remove them u have no way to verify those scripts if u need to change them in the future

**Comment by DavidBoike** [comment]
In this particular instance for RabbitMQ, what do those tests do anyway?

**Comment by SimonCropp** [comment]
@DavidBoike smoke tests these https://docs.particular.net/transports/rabbitmq/operations-scripting

**Comment by DavidBoike** [comment]
So, I'm making some assumptions here. Are these correct?

* Desire to run tests during CI stems from the fact that these things need to be executed (at least sometimes, more often than they are now) and it's unlikely we'll remember to do so manually.
* Doing so globally would take an already long build and make it much longer just searching for tests to execute. In many cases there would be no tests and so it would just be an utter waste of time.

Is there a way we cut through the dissonance there by having one centralized solution that brings in compiled artifacts from other projects on an opt-in basis and runs the tests only there? If so, are there other benefits we could get from that? One thing that springs to mind are the SQL Persistence scripts (like [MS SQL Server Scripts](https://docs.particular.net/persistence/sql/sqlserver-scripts)) that are also generated manually by running a test.

**Comment by SimonCropp** [comment]
> Is there a way we cut through the dissonance there by having one centralized solution that brings in compiled artifacts from other projects on an opt-in basis and runs the tests only there

possibly but i dont think it is worth the value. in the world of CI and unit tests eventually u reach diminishing returns due to the effort of running tests and the effort in writing them in a way that can be run. take the snippets for example, ideally it would be nice to have them executable (not just compiled), but the effort in automating that, the cost in running them, the infrastructure required, and the additional effort of writing snippets that are testable means it is not worth it. if the @Particular/rabbitmq-transport-maintainers feel that the scenarios executed in rabbitmq/operations-scripting are valuable and should be verified, then they should be added as extra tests in the rabbit repo. this way they can be verified and maintained with very little effort

**Comment by adamralph** [comment]
>  if the @Particular/rabbitmq-transport-maintainers feel that the scenarios executed in rabbitmq/operations-scripting are valuable and should be verified, then they should be added as extra tests in the rabbit repo. this way they can be verified and maintained with very little effort

That would work, but does that mean that we'd have to mirror the scripts between the RabbitMQ and docs repos? I see that getting easily out of sync.

Having thought about this, I think this issue should be withdrawn and running these tests should become part of our manual smoke testing for new versions of the RabbitMQ client. Currently, we update the snippets solution and then compile. It's easy to change that to: update the solution, run the tests.

@Particular/rabbitmq-transport-maintainers any objection?

**Comment by adamralph** [comment]
FYI https://github.com/Particular/NServiceBus.RabbitMQ/pull/438
