### ISSUE TITLE
Feedback: 'Windows Service Hosting'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3135]
Feedback for 'Windows Service Hosting' https://docs.particular.net/nservicebus/hosting/windows-service#bootstrapping-nuget-in-memory-persistence

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/windows-service.md

ping @Particular/nservicebus-maintainers

we are no longer "in memory persistence"

**Comment by andreasohlund** [comment]
Tried to address this in https://github.com/Particular/docs.particular.net/pull/3152
