### ISSUE TITLE
Gateway v3 Config upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3139]
I had to [disable the gateway snippets build](https://github.com/Particular/docs.particular.net/commit/92939d0ee01f83c30482c6ae5512c86b688a93fa) since it make heavy use of `IProvideConfiguration` and `CustomConfigurationSource` and i could not find an alternative API to do an upgrade guide

**Comment by SimonCropp** [comment]
ping @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
Already on my todo list, assigned my self

**Comment by andreasohlund** [comment]
Fixed in #67
