### ISSUE TITLE
BLOCKED: cleanup System.ServiceProcess.ServiceController unstable

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3141]
Several places use an unstable version of `System.ServiceProcess.ServiceController`. When version 4.5 is released come back and clean up the unstable. Subscribe to be notified about release here https://libraries.io/nuget/System.ServiceProcess.ServiceController.

Places to cleanup

 *  ~~delete https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/windows-service/Core_7/nuget.config~~
 * ~~delete https://github.com/Particular/docs.particular.net/blob/master/samples/endpoint-configuration/Core_7/nuget.config~~
 * change to stable https://github.com/Particular/docs.particular.net/blob/master/samples/endpoint-configuration/Core_7/Sample/Sample.Core.csproj#L14
 * change to stable https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/windows-service/Core_7/Sample/Sample.Core.csproj#L10
 * ~~cleanup this content https://docs.particular.net/samples/hosting/windows-service/?version=core_7#net-core-system-serviceprocess-servicecontroller~~
 * ~~https://github.com/Particular/docs.particular.net/blob/master/Snippets/MsLogging/nuget.config~~
 * double-check if any other places need to be cleaned up

**Comment by SimonCropp** [comment]
https://www.nuget.org/packages/System.ServiceProcess.ServiceController/4.5.0-preview1-25914-04 So this can now be partially done

**Comment by weralabaj** [comment]
@Particular/docs-maintainers Can one of you subscribe to updates and complete once the stable is released?

**Comment by SzymonPobiega** [comment]
+1

**Comment by weralabaj** [comment]
Two days ago they released RC, I set up a reminder for myself to check this in a few days.

**Comment by SimonCropp** [comment]
2 PRs pending
