### ISSUE TITLE
Host upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3158]
* `PerformanceCounters` removed. see https://docs.particular.net/nservicebus/upgrades/externalize-perfcounters and obsolete on PerformanceCounters profile in host codebase
 * removal of ConfigureLoggingForProfile. instead configure in the constructor of `IConfigureThisEndpoint`

**Comment by ramonsmits** [comment]
@SimonCropp I'll try address this next week.

**Comment by weralabaj** [comment]
@ramonsmits @seanfarmar Do you have capacity to address this soon?

**Comment by ramonsmits** [comment]
@weralabaj We have a workslot scheduled for tomorrow to work on this.

**Comment by SimonCropp** [comment]
@Particular/host-maintainers can u please add links to the original issues that managed those changes. and re-open them given that until the doco is done they are not "done"

**Comment by weralabaj** [comment]
@ramonsmits @seanfarmar Do you recall if that issue was addressed? I don't see any linked PRs.

**Comment by seanfarmar** [comment]
@weralabaj I can't recall, we need to review this 

//CC @ramonsmits

**Comment by SimonCropp** [comment]
i no longer need this done
