### ISSUE TITLE
Provide sample for NServiceBus.WCF

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3162]
We don't have a sample for the NServiceBus.WCF package.

I have some faint memory that @danielmarbach tried to create a sample but ended up not doing it but I couldn't find any info in docs about this. Maybe @SimonCropp remembers as well?

**Comment by SimonCropp** [comment]
@timbussmann i suspect it used to be in the NSB host sample.

**Comment by timbussmann** [comment]
@SimonCropp https://docs.particular.net/samples/hosting/nservicebus-host/ doesn't seem to reference it. Note that we have a WCF sample (https://docs.particular.net/samples/web/wcf-callbacks/) but that sample depends on callbacks and doesn't reference the WCF package.

**Comment by SimonCropp** [comment]
@tim "**used** to be in the NSB host sample". ie when the host stopped supporting wcf then it was removed from the sample

**Comment by danielmarbach** [comment]
Correct we don't have a sample. One of the reasons was already outlined by @SimonCropp. Another reason is that we weren't really sure if there is a benefit for the WCF lib when we worked on v6. I went on and just did it at the time to be able to support existing customers.

**Comment by danielmarbach** [comment]
Do we see value in a sample? If yes I could work on it

**Comment by timbussmann** [comment]
> Do we see value in a sample? If yes I could work on it

Can't really judge that. I just wanted to have a documented reason why there is no sample so far. It might have value from the perspective of smoke tests. If there is not much effort to do, I think we should add it.

**Comment by andreasohlund** [comment]
Since we have a supported WCF package it seems obvious that we should have a sample? That would be great for smoke testing releases
