### ISSUE TITLE
Feedback: 'SQL Server Transport Upgrade Version 2 to 3'

### ISSUE THREAD

**Issue by psandler** [Particular/docs.particular.net#3163]
Is this warning still valid?  It looks like SQL Server Transport has been out of beta for a while.

"This page targets a pre-release version and is subject to change prior to the final release."

Feedback for 'SQL Server Transport Upgrade Version 2 to 3' https://docs.particular.net/transports/upgrades/sqlserver-2to3

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/upgrades/sqlserver-2to3.md

ping @Particular/sqlserver-transport-maintainers

**Comment by SimonCropp** [comment]
@psandler no that is not correct. i will fix it and let u know

**Comment by SimonCropp** [comment]
@psandler this should now be fixed. sorry for the confusion
