### ISSUE TITLE
Feedback: 'NServiceBus Mailer'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3170]
Add it to the menu

Feedback for 'NServiceBus Mailer' https://docs.particular.net/nservicebus/mailer/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/mailer/index.md

ping @HEskandari

**Comment by HEskandari** [comment]
Where in the menu exactly? I don't see a suitable place for it.

**Comment by SimonCropp** [comment]
after this https://docs.particular.net/nservicebus/wormhole/
