### ISSUE TITLE
Feedback: 'Windows Service Hosting'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3185]
Feedback for 'Windows Service Hosting' https://docs.particular.net/nservicebus/hosting/windows-service

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/windows-service.md

ping @Particular/nservicebus-maintainers

update to reflect this discussion https://groups.google.com/forum/#!topic/particularsoftware/giGjXrGn-TM

**Comment by andreasohlund** [comment]
Just to make sure I get this, we should add a note in https://docs.particular.net/nservicebus/hosting/windows-service to make user aware that Environment.UserInteractive doesn't work on netcore right?

**Comment by andreasohlund** [comment]
@SimonCropp I guess https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/GenericHost.cs#L91 can stay since the host won't be targeting netstandard?

**Comment by SimonCropp** [comment]
i guess and "people are free to use Environment.UserInteractive" as long as they remember when they move to core

**Comment by SimonCropp** [comment]
> can stay since the host won't be targeting netstandard

yes

**Comment by andreasohlund** [comment]
Raised https://github.com/Particular/docs.particular.net/pull/3205 to address this
