### ISSUE TITLE
Feedback: 'Native integration'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3186]
Feedback for 'Native integration' https://docs.particular.net/samples/sqltransport/native-integration/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/sqltransport/native-integration/sample.md

ping @Particular/sqlserver-transport-maintainers

Fix serializer section to point to the newtonsoft serilizer

**Comment by SzymonPobiega** [comment]
Fixed via https://github.com/Particular/docs.particular.net/commit/dd8f6a33d523598c15b9d7b2cac14f3cb2b8705f#diff-eb34489ec6815af8e9380b9f86d5a2f3
