### ISSUE TITLE
revert CurrentCulture to US hack

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3190]
when this https://github.com/dotnet/coreclr/issues/12668 is deployed revert this https://github.com/Particular/docs.particular.net/commit/ac688854976eceab992934807123e43b72c66f75

**Comment by weralabaj** [comment]
@SimonCropp seems it's ready to go? or do we need to wait for sth more?

**Comment by SimonCropp** [comment]
@weralabaj https://github.com/dotnet/coreclr/issues/12668 is not deployed yet

**Comment by weralabaj** [comment]
Sorry, my mistake, I saw it's been merged, but didn't look at the milestone.

**Comment by bording** [comment]
FYI, the 2.0.3 release of .NET Core that came out today includes the fix for https://github.com/dotnet/coreclr/issues/12668.
