### ISSUE TITLE
Problematic 'Performance Counters' doco

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3191]
ping @Particular/metrics-maintainers

this https://docs.particular.net/nservicebus/operations/performance-counters?version=perfcounters_1 uses the language from when the perf coutners was still in the core. eg "Critical Time Added in: Version 3" but i am looking at the version 1 page. so what is version 3?

version 1 explains the counters https://docs.particular.net/nservicebus/operations/performance-counters?version=perfcounters_1#sla-violation-countdown  but version 1.1 does not https://docs.particular.net/nservicebus/operations/performance-counters?

**Comment by weralabaj** [comment]
the simple fix could be to change to "Added in NServiceBus Version 3", or instead of using the "Added" convention, just list available perf counters for each version

**Comment by SimonCropp** [comment]
@weralabaj but those sections are not showing up in the newest doco

**Comment by weralabaj** [comment]
I commented only on the first part of the issue, either way I can help with this if needed.

**Comment by SimonCropp** [comment]
@weralabaj i would rather the @Particular/metrics-maintainers own it and only pull u in if they need help

**Comment by dvdstelt** [comment]
Can't we just lose the version 3 & version 4 references? Those are in versions that are not supported in any case. It's really outdated information.
Then we'd only need specific information for NSB 6 and "version" 1 or higher details.

**Comment by SimonCropp** [comment]
> Can't we just lose the version 3 & version 4 references

@dvdstelt until this is decided we cannot burn old doco https://github.com/Particular/CustomerSuccess/issues/548

**Comment by weralabaj** [comment]
ping @Particular/metrics-maintainers any comments?

**Comment by dvdstelt** [comment]
I will pick this up

**Comment by weralabaj** [comment]
Ping @dvdstelt ;)

**Comment by dvdstelt** [comment]
This can be closed, it has become irrelevant after the recent changes. I was waiting for that PR to be merged! :-)
