### ISSUE TITLE
Navigating from pre-released doco to samples breaks

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3194]
When navigating from a pre-released documentation (which is shown by default) to the samples, the context of pre-released version is not preserved and one version earlier samples are displayed.

E.g: navigating from https://docs.particular.net/transports/azure-storage-queues/sanitization to sample:

![image](https://user-images.githubusercontent.com/1309622/30216702-1c82ad56-9471-11e7-9809-bf8d7e823ea4.png)

Sample is presented for last stable version, not pre-release

![image](https://user-images.githubusercontent.com/1309622/30216731-3772efe0-9471-11e7-865c-bc732ddc9f94.png)

Quite confusing if you don't pay attention to the currently selected version.

ping @Particular/docs-maintainers

**Comment by SimonCropp** [comment]
> When navigating from a pre-released documentation (which is shown by default) to the samples

what prerelease doco is show by default?

and isnt this the same problem as here https://github.com/Particular/DocsEngine/issues/217  ?

**Comment by SeanFeldman** [comment]
New doco @SimonCropp. E.g: https://docs.particular.net/transports/azure-storage-queues/sanitization

Yes, #217 is similar, just a year old 😃

**Comment by DavidBoike** [comment]
This really has nothing to do with docs content, it concerns how the engine works. So I'm going to close this one and enhance the description of https://github.com/Particular/DocsEngine/issues/217.
