### ISSUE TITLE
Allow large snippet to render collapsed with a few lines of preview

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3195]
Some snippets are very long and take a lot of vertical space. The entire snippet is not critical to be presented, but just a few first lines. Would be nice to be able to have large snippets collapsed showing maybe a few first lines and and option to expand it should one want to see the whole snippt.

Example: https://docs.particular.net/samples/azure/storage-queues/?version=asq_8#sanitizer-source-code

This is how I'd envision this working:

![image](https://user-images.githubusercontent.com/1309622/30217221-bdee1e7c-9472-11e7-9dc0-718130d34a85.png)

**Comment by weralabaj** [comment]
@SeanFeldman seems like something to raise in DocsEngine repo I guess?

**Comment by SeanFeldman** [comment]
😄 oh snap. Yep. Moving.

**Comment by SeanFeldman** [comment]
Replaced with https://github.com/Particular/DocsEngine/issues/339
