### ISSUE TITLE
re-add sql v4 store and forward

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3200]
@Particular/sqlserver-transport-maintainers given there i no upgrade guide for sql v4, and the store and forward sample had a breaking change, i took the liberty of removing it. feel free to re-add 
https://github.com/Particular/docs.particular.net/pull/3196/commits/506200cecf6b6506cc075abd679c7758220b9d2f

cc @DavidBoike

**Comment by SzymonPobiega** [comment]
In V4 it could be done by a bridge but currently the bridge does not have an effective back-off strategy. The idea of store-and-forward was that if a destination DB is down, messages will nicely queue up and be forwarded when it is back again. 

The current bridge will do 5 FLRs and move the messages to the endpoint queue by default which is not what we want. But if we had an effective recoverability policy...

**Comment by weralabaj** [comment]
@SzymonPobiega I'm not clear what should be done here, do we want to get that sample back at some point, but need some coding changes first, or is this issue not relevant, we bury the sample forever and can close the issue?

**Comment by SzymonPobiega** [comment]
@weralabaj yeah, I need to put on my community hat and add this feature to the NSB.Bridge. Than I can create a sample for this.

**Comment by MarcinHoppe** [comment]
I don't have the capacity to drive this issue forward now and I am removing my assignment here.

**Comment by weralabaj** [comment]
@SzymonPobiega I propose we create an issue for the feature in nsb.bridge and there add "TODO" item to revert that sample and close this issue, ok?

**Comment by SzymonPobiega** [comment]
I was finally able to implement the feature and add the doco PR: https://github.com/Particular/docs.particular.net/pull/3573
