### ISSUE TITLE
Feedback: 'Azure Service Bus Transport Upgrade Version 7 to 8'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3202]
Feedback for 'Azure Service Bus Transport Upgrade Version 7 to 8' https://docs.particular.net/transports/upgrades/asb-7to8

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/upgrades/asb-7to8.md

ping @Particular/azure-maintainers

incorrectly show v6 snippets

**Comment by yvesgoeleven** [comment]
@SimonCropp why would the engine do that?  we just reference the snippet

snippet: asb-incoming-message-convention

and the right versions

upgradeGuideCoreVersions:
 - 7
 - 8

**Comment by SimonCropp** [comment]
`upgradeGuideCoreVersions` is for the NSB version.

**Comment by SimonCropp** [comment]
upgrade guides need specifically versioned snippets. eg https://github.com/Particular/docs.particular.net/blob/master/Snippets/SqlPersistence/SqlPersistence_3/UpgradeGuides/2to3/Upgrade2to3.cs#L8

**Comment by SeanFeldman** [comment]
[That](https://github.com/Particular/docs.particular.net/issues/3202#issuecomment-328512593) should probably be mentioned in the [readme.md](https://github.com/Particular/docs.particular.net/#upgradeguides)
