### ISSUE TITLE
Feedback: 'MSMQ Dead Letter Queue Custom Check'

### ISSUE THREAD

**Issue by udidahan** [Particular/docs.particular.net#3216]
Feedback for 'MSMQ Dead Letter Queue Custom Check' https://docs.particular.net/samples/msmq/dlq-customcheck/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/msmq/dlq-customcheck/sample.md

ping @Particular/msmq-transport-maintainers

It would be great if there was a screenshot from ServicePulse that showed what it looks like when the CustomCheck fails.

**Comment by indualagarsamy** [comment]
@udidahan - Can you explain the feedback received on the article as it stands? Is adding the screenshot the feedback or was there more to it? Rather than add screen shot in this docs, it would be better if the custom checks documentation in ServicePulse has it.

**Comment by mikeminutillo** [comment]
@indualagarsamy I think this is a specific example. Is there a reason you would prefer the screenshot in the Pulse documentation as opposed to in this sample?

How's this? It's a full page shot so it shows the little error notification badge as well.

![image](https://user-images.githubusercontent.com/124014/30418211-cdf459fc-9964-11e7-8d23-ee24317d2d32.png)

Alternatively we can zoom in on it

![image](https://user-images.githubusercontent.com/124014/30418288-0b935ad8-9965-11e7-9e5d-e938f469d108.png)

Or even closer

![image](https://user-images.githubusercontent.com/124014/30418316-1d0c5d46-9965-11e7-8292-09e3d6e3a356.png)

**Comment by indualagarsamy** [comment]
@mikeminutillo @udidahan 

Adding screenshots to the article has some level of maintainability that it adds to the @Particular/servicepulse-maintainers . For example, if the pulse UI changes, this article needs to be updated. Which is why, it's much easier if the screen shot is part of the ServicePulse article on the custom checks itself. In the custom checks article you can have examples, and even link or relate the DLQ check. That would make it much more easier to maintain when UI changes occur IMO. But I defer the decision of whether to add screen shots or not to the @Particular/servicepulse-maintainers to chime in.

**Comment by udidahan** [comment]
Wouldn't the maintainability issue be handled by using the snippet/include functionality in docs?

**Comment by udidahan** [comment]
@indualagarsamy the purpose of the screenshot is to make it clearer to the reader what the end-result would be. For someone who had never used a custom check before, it isn't at all clear how they would help them monitor the DLQ.

**Comment by indualagarsamy** [comment]
@udidahan - I can see your point.  I am going to defer this to @Particular/servicepulse-maintainers.  @mikeminutillo - I think the 3rd option would be good IMO.

**Comment by mikeminutillo** [comment]
The screenshot has been added to the live version (might require a page refresh to see it).

@udidahan if you're happy with the result, please close this issue.

**Comment by weralabaj** [comment]
I wasn't following all the discussions apparently, but Simon pointed out that we had a conflicting decision here https://github.com/Particular/docs.particular.net/issues/3197. I merged the PR. @Particular/msmq-transport-maintainers I'm closing the other issue, as is no longer relevant, if you feel the screenshot shouldn't be here, please, raise a PR.

**Comment by udidahan** [comment]
Yup. Closing.
