### ISSUE TITLE
Feedback: 'Unit Testing NServiceBus'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3220]
The doco is missing information about `TestableEndpointInstance` testing.
[SO question](https://stackoverflow.com/questions/46226952/how-to-mock-out-iendpointinstance-of-nservicebus) brought this up.

Feedback for 'Unit Testing NServiceBus' https://docs.particular.net/samples/unit-testing/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/unit-testing/sample.md

ping @Particular/nservicebus-maintainers

**Comment by SimonCropp** [comment]
i also replied to the SO
