### ISSUE TITLE
Cloud services: fix binding redirects.

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#3222]
The same issue that @danielmarbach ran into with his self hosting sample, is applicable to other cloudservices samples. Binding redirects are generated after the package is created, so they are not in the packange and must be manually fixed :(

POA
- review all cloud service hosted samples
- enable auto generate binding redirects
- update nugets
- copy binding redirects into dll.config & mark as copy always

**Comment by yvesgoeleven** [comment]
This feature is broken for websites as well, it doesn't modify web.config, instead it modifies the website.dll.config

**Comment by yvesgoeleven** [comment]
Cloud show case fix https://github.com/Particular/docs.particular.net/pull/3223

**Comment by SimonCropp** [comment]
@yvesgoeleven can this be closed ?

**Comment by yvesgoeleven** [comment]
@SimonCropp not yet, still need to review the other samples, to see if they are affected

**Comment by yvesgoeleven** [comment]
Reviewed, no other cloud or website projects except those included in https://github.com/Particular/docs.particular.net/pull/3212, closing
