### ISSUE TITLE
Feedback: 'Shared Hosting in Azure Cloud Services'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3232]
Feedback for 'Shared Hosting in Azure Cloud Services' https://docs.particular.net/samples/azure/shared-host/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/azure/shared-host/sample.md

ping @Particular/azure-maintainers

change timestamp to be non-ambiguous. ie anything other than US format

**Comment by danielmarbach** [comment]
@SimonCropp the timestamp is generated by the storage, see

![image](https://user-images.githubusercontent.com/174258/30582503-369743f8-9d24-11e7-9fb8-6570120d2a06.png)

I don not think we can influence that

**Comment by SimonCropp** [comment]
fixed by https://github.com/Particular/docs.particular.net/commit/91ac0affc860e486945d0a39320ec829c9e82783
