### ISSUE TITLE
Feedback: 'Why Use SQS?'

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#3238]
Feedback for 'Why Use SQS?' https://docs.particular.net/transports/sqs/why-use-sqs

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sqs/why-use-sqs.md

ping @Particular/aws-maintainers 

Arguably the `AWS Auto-Scaling Doesn't Play Nice With Local MSMQ` section is more relevant for MSMQ users than SQS users. This section should be moved to MSMQ doco or at least referenced there.

**Comment by MarcinHoppe** [comment]
Also, @Particular/msmq-transport-maintainers should be interested.

**Comment by mauroservienti** [comment]
At least I'd move it down as the 3rd paragraph

**Comment by danielmarbach** [comment]
Applied @mauroservienti proposal. https://github.com/Particular/docs.particular.net/commit/5b2bf8f21b59e2053a3d41f164473c2aa90b291d

**Comment by MarcinHoppe** [comment]
It's a good change but it does not solve the problem of having info targeted primarily at MSMQ users buried in SQS doco.

**Comment by mauroservienti** [comment]
@MarcinHoppe where do you suggest to add the link in the MSMQ doco? /cc @Particular/msmq-transport-maintainers

**Comment by MarcinHoppe** [comment]
I thought about having a page about how MSMQ in any environment where the local storage (outgoing queues) can go bust at an arbitrary point in time is not a good idea. One such environment is auto-scale in EC2.

**Comment by danielmarbach** [comment]
Same problem with Service Fabric btw.

**Comment by MarcinHoppe** [comment]
@danielmarbach Is it realistic that somebody will run MSMQ transport from a Service Fabric cluster?

**Comment by danielmarbach** [comment]
@MarcinHoppe it is tempting. Service Fabric runs on linux and windows. If you let it run on windows coming from the old on-premise world might get you thinking to just use the resources on the local node. Which of course has serious problems if you try do do so
