### ISSUE TITLE
Configure NHibernate for Sql Azure

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#324]
Main purpose is to make clear why a specific driver is advised NHibernate.SqlAzure.SqlAzureClientDriver, NHibernate.SqlAzure

**Comment by SimonCropp** [comment]
@yvesgoeleven so it has been 12 months. is this still necessary?

**Comment by yvesgoeleven** [comment]
@SimonCropp fixed: http://docs.particular.net/nservicebus/nhibernate/sql-azure
