### ISSUE TITLE
Feedback: 'ServiceControl'

### ISSUE THREAD

**Issue by LiamFeldman** [Particular/docs.particular.net#3243]
Feedback for 'ServiceControl' https://docs.particular.net/servicecontrol/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/index.md

ping @Particular/servicecontrol-maintainers

The connection between SC and SC Instances is not explained on the SC landing page. Confusing for new users.

**Comment by weralabaj** [comment]
@mikeminutillo do you still want to work on it or should I look for somebody else?

**Comment by mikeminutillo** [comment]
There is some work happening in the background to try and make the difference between ServiceControl and ServiceControl Instances happening in the background. Once that has been sorted out, it will make updating the docs much clearer.

**Comment by weralabaj** [comment]
@mikeminutillo what do you think about simply adding such a paragraph for now https://github.com/Particular/docs.particular.net/pull/3338? not sure what background work is happening, but still I think that info would be useful to have there.

**Comment by weralabaj** [comment]
@LiamFeldman Mike clarified that relationship in this PR https://github.com/Particular/docs.particular.net/issues/3243. If you think there's still something to improve, please, let us know!

And thanks again for suggesting the improvement :)
