### ISSUE TITLE
Feedback: 'Azure Blob Storage DataBus'

### ISSUE THREAD

**Issue by LiamFeldman** [Particular/docs.particular.net#3246]
Feedback for 'Azure Blob Storage DataBus' https://docs.particular.net/nservicebus/messaging/databus/azure-blob-storage

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/databus/azure-blob-storage.md

ping @Particular/azure-maintainers

The default for `NumberOfIOThreads` have changed from 5 to 1 in version 2.0.
https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/blob/5a1da647e95d076b21fe61ef2cde1ff1ca5ec722/src/DataBus/DataBusSettings.cs#L10

**Comment by SeanFeldman** [comment]
done in https://github.com/Particular/docs.particular.net/commit/fc9d192ac3947b9044677f6cac09aaad5ff027fd

**Comment by SeanFeldman** [comment]
Thanks son! 😆
