### ISSUE TITLE
add hangfire scheduler usage 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3249]
basically a hangfire equivalent of this https://docs.particular.net/samples/scheduling/quartz/

**Comment by janovesk** [comment]
I'll do it

**Comment by janovesk** [comment]
https://github.com/Particular/docs.particular.net/pull/3250

**Comment by weralabaj** [comment]
Done in https://github.com/Particular/docs.particular.net/pull/3250
