### ISSUE TITLE
store and forward article is MSMQ specific

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#325]
when this feature is supported by other transpoerts such as Rabbit and Azure 
https://github.com/Particular/docs.particular.net/blob/master/Content/NServiceBus/how-do-i-specify-store-forward-for-a-message.md
So needs some re-wording to make it transport agnostic, or perhaps list the transports that support it.

**Comment by mauroservienti** [comment]
the original page is not available anymore, at least I cannot find it, can we close this?
