### ISSUE TITLE
Wrong sanitization logic in ASQ upgrade guide

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#3255]
In https://docs.particular.net/transports/upgrades/asq-7to8

The logic here is wrong, it would not produce guids when the name is too longe etc. Please provide the original code here (as well), including the length checks etc...

```
transport.SanitizeQueueNamesWith(queueName => queueName.Replace(".", "-"));
```

**Comment by weralabaj** [comment]
@yvesgoeleven you mean that we should update the snippet to use the actual NSB.ASQ 8 code?

**Comment by SeanFeldman** [comment]
It _looks_ like v8 of the transport is compatible with v6. But there's a difference between v6 and v7 🙁
Will have to investigate a bit more to address both, doco and possibly release a fix. Stand by.
