### ISSUE TITLE
add support warning/suggestions

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3257]
In the sql persistence doco there is this https://docs.particular.net/persistence/sql/#supported-sql-implementations

> Although this persistence will run on the free version of the above engines, i.e. SQL Server Express, MySQL Community Edition, and Oracle XE, it is strongly recommended to use commercial versions for any production system. It is also recommended to ensure that support agreements are in place from either Microsoft Premier Support, MySQL support, Oracle Support, or another third party support provider.

Should equivalent warnings be added to other transport/persistence pages?

**Comment by weralabaj** [comment]
I see that nhibernate has that warning in place https://docs.particular.net/persistence/nhibernate/#supported-database-engines, I added a smilar note for sql transport https://github.com/Particular/docs.particular.net/commit/9fcab6ff6de153af30b33d2c58ef30674df11999.
