### ISSUE TITLE
Improve or remove incompatibility with nuget

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#3260]
@SimonCropp raised a concern that this description needs to be improved or removed

https://docs.particular.net/nservicebus/upgrades/host-7to8#installation-incompatible-with-nuget
https://docs.particular.net/nservicebus/upgrades/acs-host-7to8#installation-incompatible-with-nuget

// cc @andreasohlund

**Comment by andreasohlund** [comment]
So the issues are

1. NuGet won't allow us to adjust the csproj to startup the host exe
2. NuGet won't allow us to add/modify the EndpointConfig.cs to add the boilerplate `EndpointConfiguration`

@SimonCropp I remember you saying that there is some issues with the new project format as well?

**Comment by SimonCropp** [comment]
@andreasohlund my understanding was 1 and 2 were only issues in the new project system? and also project,json

**Comment by andreasohlund** [comment]
Would users be able to hand craft the new csprojs to get this working?

**Comment by SimonCropp** [comment]
@andreasohlund not sure what u mean? "hand craft the new csprojs to get it working with the nsb host"?

**Comment by weralabaj** [comment]
@SimonCropp not sure exactly what is the requested "improvement", would be the solution to quote what Andreas said in the 1st comment, i.e. give more details? Or what is the issue here?

**Comment by SimonCropp** [comment]
specifically

> NuGet no longer support packages adding source files and modifying project files.

in incorrect. it only applies to new the sdk style pf csproj

**Comment by weralabaj** [comment]
That should address the concnern I hope https://github.com/Particular/docs.particular.net/pull/3323
