### ISSUE TITLE
Feedback: 'Routing system extensibility points'

### ISSUE THREAD

**Issue by LiamFeldman** [Particular/docs.particular.net#3263]
Feedback for 'Routing system extensibility points - Event Routing' https://docs.particular.net/nservicebus/messaging/routing-extensibility?version=core_7#routing-apis-event-routing

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/routing-extensibility.md

ping @Particular/nservicebus-maintainers

Event routing doesn't show _how_ to register an event publisher. It is mentioned in the [upgrade guide](https://docs.particular.net/nservicebus/upgrades/6to7/#config-endpoint-mappings-event-routing), but shouldn't it be the other way around?

**Comment by timbussmann** [comment]
ping @SeanFeldman

**Comment by SeanFeldman** [comment]
TBH, the search for "event routing" brings both pages. It just happens that Routing Extensibility comes first and when you dive into it, there's [Event Routing section](https://docs.particular.net/nservicebus/messaging/routing-extensibility?version=core_7#routing-apis-event-routing)  which is **rightfully** talks about **extensibility**, but offers no link or info on how register a publisher. I wonder if a link to [Message Routing page, Event routing section](https://docs.particular.net/nservicebus/messaging/routing#event-routing) would suffice.

**Comment by weralabaj** [comment]
I added links to the page here https://github.com/Particular/docs.particular.net/commit/5e9d0e559091351400deb9cba668f039651055db and here https://github.com/Particular/docs.particular.net/commit/ef202c5e8b9aad5baeca7ce7d949cdd10e02bab9.

I hope that addresses the problem. If not, please reopen the issue with more details and we'll improve further :)
