### ISSUE TITLE
Feedback: 'Hosting endpoints in Docker Linux containers'

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#3278]
Feedback for 'Hosting endpoints in Docker Linux containers' https://docs.particular.net/samples/hosting/docker/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/docker/sample.md

ping @Particular/nservicebus-maintainers 

Should we show, maybe in a different sample, how to externalize configurations settings into the Docker compose file? So not to embed, for example, things like connection string?

Nice work 😄

**Comment by MarcinHoppe** [comment]
Good idea, moving us more towards the 12 factor model (i.e. settings stored in env vars).

**Comment by weralabaj** [comment]
@mauroservienti @MarcinHoppe Seems like a nice idea, but given we didn't get to it in 2 months I don't think it'll be addressed anytime soon. Feel free to reopen if you want to work on this.
