### ISSUE TITLE
Rename sample category “containers” to “IoC Conatimers” or “DI Containers” to avoid confusion with Docker containers 

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#3279]
I was looking for the Docker sample and I immediately clicked on the Containers category in samples, just to realize that it’s the IOC Containers category.

Ping @Particular/docs-maintainers 
ping @Particular/container-maintainers

**Comment by SzymonPobiega** [comment]
@mauroservienti Take a look at #3281

**Comment by mauroservienti** [comment]
Cool, thanks @SzymonPobiega
