### ISSUE TITLE
Feedback: The SQL Usage section does not mention the required subscriptions settings

### ISSUE THREAD

**Issue by janpieterz** [Particular/docs.particular.net#3287]
Was just following along and got an exception on startup. Might be nice to add a link to the subscription settings or to all three SQL options add a 'default'.

https://docs.particular.net/persistence/sql/?version=sqlpersistence_3#usage

Let me know what you'd like (if anything). More than happy to make the edit.

**Comment by weralabaj** [comment]
@janpieterz You mean you could submit a PR to docs? That would be more than welcome, please do! :)

**Comment by janpieterz** [comment]
@weralabaj I created a pull request, went for the option to add it to all 'usage examples'. Let me know if you'd like it changed.

https://github.com/Particular/docs.particular.net/pull/3297
