### ISSUE TITLE
Feedback: 'Scripting'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3305]
Feedback for 'Scripting' https://docs.particular.net/transports/msmq/operations-scripting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/msmq/operations-scripting.md

ping @Particular/msmq-transport-maintainers

add a note that all ps scripts that target msmsq require 
```
Add-Type -AssemblyName System.Messaging
```

**Comment by indualagarsamy** [comment]
@SimonCropp - Can I just add the `Add-Type - AssemblyName System.Messaging` into the script, similar to what the DeleteQueues script does. While this is like an using statement in C#, I think its much more easier to have it be part of the script that's visible than to add a warning that's easy to miss. Thoughts?

**Comment by SimonCropp** [comment]
@indualagarsamy how would that work in this file where we have smaller snippet regions https://github.com/Particular/docs.particular.net/blob/master/Snippets/MsmqTransport/MsmqTransport_All/QueueCreation/QueueCreation.ps1  ?

**Comment by weralabaj** [comment]
@indualagarsamy I merged the PR but I"m not sure if that's enough, I think note is good, but given how long the page is, it may be easy to
