### ISSUE TITLE
Doco for the new conversation id override strategy

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#3311]
For the sample we'll likely suggest a custom attribute to flag the ID fields.

```
    class PlaceOrder   

        [BusinessId] //user defined attribute
        string OrderId;
```

Me and @weralabaj could come up with the following options that we can mention as well:

### Hardcode aka "Wall of code"

```
   if(context.Message is PlaceOrder)
       id = context.Message.OrderId;
```

### Marker interface aka "categorized wall of code"
```
interface IOrderRelatedMessage
    string OrderId;

interface ICustomerRelatedMessage
    string CustomerId;
```
### Convention on names + reflection aka "Magic"
```
    if(context.Message.IsCommand)
    {
        string entity = ParseEntityName(context.Message.Type);

        id = CachedReflectionInvoked(context.Message,$"{entity}Id")

        return true;
    }
  ```

**Comment by weralabaj** [comment]
@andreasohlund not sure why we need to

> Record demo

where do you want to post it?

**Comment by andreasohlund** [comment]
I was going to post in our demo slack channel?

**Comment by weralabaj** [comment]
Ah ok, since it's a public repo I wasn't sure if you want to include it in the doco page or sth ;)

**Comment by andreasohlund** [comment]
PR merged, will start with this shortly

**Comment by weralabaj** [comment]
ping @andreasohlund

**Comment by andreasohlund** [comment]
I was planning to do this as soon as https://github.com/Particular/docs.particular.net/pull/3447 is in

**Comment by andreasohlund** [comment]
Doco PR raised https://github.com/Particular/docs.particular.net/pull/3615

**Comment by andreasohlund** [comment]
Doco is merged, no longer convinced that we need a sample, closing this as done
