### ISSUE TITLE
Feedback: 'MSMQ Transport'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3334]
Feedback for 'MSMQ Transport' https://docs.particular.net/transports/msmq/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/msmq/index.md

ping @Particular/msmq-transport-maintainers

MSMQ landing page should give some getting started code

**Comment by indualagarsamy** [comment]
@SimonCropp - Thanks. Will add the configuration code similar to other transports. Also will fix this page to mention that its now a new nuget package.

**Comment by SimonCropp** [comment]
> Also will fix this page to mention that its now a new nuget package.

this is not necessary. when u add a snippet the target nuget will appear in the header
