### ISSUE TITLE
Improve TimeoutManager documentation when the distributor is in place

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#334]
Issue raised in the following Google Group thread: https://groups.google.com/forum/#!topic/particularsoftware/fsSCqAF72YU

**Comment by mauroservienti** [comment]
@sfarmar given that you are the distributor master do you want to give it a shot? :-)

**Comment by SimonCropp** [comment]
given the current status of the distributor moving forward i am closing this one. please feel free to open a PR if u think it is still work doing
