### ISSUE TITLE
Feedback: 'EntityFramework integration'

### ISSUE THREAD

**Issue by wleader** [Particular/docs.particular.net#3351]
Feedback for 'EntityFramework integration' https://docs.particular.net/samples/entity-framework/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/entity-framework/sample.md

ping @Particular/nhibernate-persistence-maintainers

The sample solution files don't open in VS 2015. Not all of us have 2017 you know.

**Comment by HEskandari** [comment]
@wleader Thanks for your feedback. Unfortunately, that is true for all our samples. With the amount of work that goes into our documentation and samples, have decided to update them to VS2017. Other than being the latest and greatest, the new project format makes our job a lot easier.

**Comment by weralabaj** [comment]
@wleader Is it possible for you to use the free community version of VS2017? We assumed that since the free version is available the samples should be accessible for anybody. Is there anything we missed in making that assumption?
