### ISSUE TITLE
Add scatter-gather sample

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#3360]
## POA

- TODO
- [ ] Notify atulpatel.mca@gmail.com when sample available

**Comment by DavidBoike** [comment]
One challenge here is that the user who really needs this sample may not even know what they're doing is called "scatter gather".

**Comment by weralabaj** [comment]
Better names are welcome :) We can also use appropriate/alternative names/keywords in the description so it can be returned by search results.

**Comment by indualagarsamy** [comment]
Scatter/Gather is a well known messaging pattern listed in the enterprise integration patterns book. That's one of the first patterns I tried implementing when trying out different ESBs. Maybe call it as "Scatter Gather Design Pattern Sample"?

**Comment by weralabaj** [comment]
I think after such a long delay, this won't be relevant for the person asking.
