### ISSUE TITLE
Feedback: 'Startup diagnostics'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3367]
Feedback for 'Startup diagnostics' https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/index.md

ping @Particular/nservicebus-maintainers

needs a warning along the lines of 

> the structure of the json produced should not be considered stable. Nodes may be added, removed or moved in minor and patch versions

**Comment by andreasohlund** [comment]
Agreed, raised https://github.com/Particular/docs.particular.net/pull/3368
