### ISSUE TITLE
Feedback: 'Asp.NET Core Dependency Injection Integration'

### ISSUE THREAD

**Issue by dasjestyr** [Particular/docs.particular.net#3375]
Feedback for 'Asp.NET Core Dependency Injection Integration' https://docs.particular.net/samples/dependency-injection/aspnetcore/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/dependency-injection/aspnetcore/sample.md

ping @Particular/nservicebus-maintainers

the `.Populate(services)` method doesn't seem to be present on ContainerBuilder. Is there some other reference that I'm not seeing?

**Comment by dasjestyr** [comment]
Nevermind. Found it in an extensions library. Might be worth noting. Leaving open so that it is seen. Feel free to close.

**Comment by weralabaj** [comment]
@dasjestyr Given that this is a code sample and you can explore the code and navigate to the definition, I'm not sure we need to do anything to highlight it.
If you have any suggestions though, please, reopen.

**Comment by dasjestyr** [comment]
Not necessarily highlight it. I think `using` directives at the top of the file would have been more than adequate :)

**Comment by HEskandari** [comment]
@dasjestyr I think you mean this?

![image](https://user-images.githubusercontent.com/132117/32034083-2db90db6-ba5c-11e7-80c5-ba775d676428.png)

**Comment by dasjestyr** [comment]
Ha! Interesting. I didn't even know those were there. Thanks :)

**Comment by weralabaj** [comment]
Hm may be a good thing to make this button more visible. Raised it https://github.com/Particular/DocsEngine/issues/345
