### ISSUE TITLE
Feedback: 'Hosting'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3382]
Feedback for 'Hosting' https://docs.particular.net/nservicebus/hosting/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/index.md

ping @Particular/nservicebus-maintainers 

The document [refers to a hosting sample](https://docs.particular.net/nservicebus/hosting/?version=core_4#self-hosting), but the sample is provided for core version 5 and up only.

![image](https://user-images.githubusercontent.com/1309622/32078467-3d55d012-ba64-11e7-9c44-22263333a75b.png)

**Comment by timbussmann** [comment]
@SeanFeldman what are you proposing?

**Comment by SeanFeldman** [comment]
To remove link to the sample for version 3 and 4, as it's misleading (no sample for that version is available). 
Or, alternatively, provide a sample for version 4 as it's still supported?

**Comment by timbussmann** [comment]
> provide a sample for version 4 as it's still supported?

v4 is not supported.

I could see us removing the sample link for v3 and v4, but given that those versions are so old, is there really any damage by having them linking to a v5 sample to justify the effort of versioned partials? (imho no)

**Comment by weralabaj** [comment]
ping

**Comment by timbussmann** [comment]
I'll stay with my previous comment. Closing this as I don't think this is important enough to be addressed atm. Feel free to reopen if you disagree.
