### ISSUE TITLE
Feedback: 'Outbox'

### ISSUE THREAD

**Issue by bording** [Particular/docs.particular.net#3383]
Feedback for 'Outbox' https://docs.particular.net/nservicebus/outbox/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/outbox/index.md

ping @Particular/nservicebus-maintainers

This page lists specific persistence pages, but that makes it appear as if only those options support the Outbox. SQL Persistence also supports Outbox, so we should do something to include it here as well. It doesn't appear that it has a dedicated Outbox page like the others do, though.

**Comment by weralabaj** [comment]
@Particular/sqlpersistence-maintainers Seems we're missing similar configuration settings for outbox cleaner, IMO would make sense to add them (i.e. frequency to run clean up task and deduplication record lifespan limit). And of course, then we have to document them.

**Comment by SzymonPobiega** [comment]
Yeah, it makes sense @weralabaj

**Comment by indualagarsamy** [comment]
@Particular/sqlpersistence-maintainers - any updates on this? I was going to suggest SqlPersistence as one of the options for someone evaluating, but it appears as if that SqlPersitence isn't an option from the looks of it.

**Comment by weralabaj** [comment]
@indualagarsamy there's a pr adding config settings, that will go in 4.1 release https://github.com/Particular/NServiceBus.Persistence.Sql/pull/238, until then I'll add a "placeholder" page that covers what we currently have in place now.

**Comment by udidahan** [comment]
If this bit gets moved to a separate issue:

> Seems we're missing similar configuration settings for outbox cleaner as other persistences have, IMO would make sense to add them (i.e. frequency to run clean up task and deduplication record lifespan limit). And of course, then we have to document them.

What would be left to finish this?

**Comment by SzymonPobiega** [comment]
@udidahan I've checked and somebody did add the link in the outbox doco page without updating this issue. Given the configuration APIs have a PR in the SQL repo I think that this one is actually done.
