### ISSUE TITLE
provide guidance on how to setup/share bug repro

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#340]
We should provide some guidance on what we expect when we ask OP/Customers to provide us with a bug repro, and we should also define some well known and easy to manage way of sharing the repro.

**Comment by weralabaj** [comment]
I guess documenting what we're currently doing should take no more than 30 min of work. Any ideas where should that live? Also who I should ping to get relevant info to get it done?

**Comment by SimonCropp** [comment]
@weralabaj it should be here https://docs.particular.net/platform/contributing

**Comment by weralabaj** [comment]
Hm that looks more like a support issue? How about I move it to https://github.com/Particular/Support? I know we have a few more or less "standard" ways we use, so it's just a matter of documenting.

**Comment by SimonCropp** [comment]
Sounds good. Feel free to move it

**Comment by weralabaj** [comment]
raised as https://github.com/Particular/Support/issues/32
