### ISSUE TITLE
Document breaking behavior for SendLocal for send-local endpoint instances for upgrade guide 6 to 7

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#3402]
V7 does not allow a SendOnly endpoint to use SendLocal. This is a behavioral change and thus not detected at compile time.

You will get the following exception when you do:

```
System.InvalidOperationException: Cannot route to instances of this endpoint since it's configured to be in send-only mode.
```

**Comment by weralabaj** [comment]
@Particular/nservicebus-maintainers ping

**Comment by andreasohlund** [comment]
I will add this
