### ISSUE TITLE
Feedback: 'Asp.NET Core Dependency Injection Integration'

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3420]
Feedback for 'Asp.NET Core Dependency Injection Integration' https://docs.particular.net/samples/dependency-injection/aspnetcore/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/dependency-injection/aspnetcore/sample.md

ping @Particular/nservicebus-maintainers

The sample code requires the `Autofac.Extensions.DependencyInjection` nuget package to compile which isn't mentioned on the page. Is there any reason to not mention this package?

(also, shouldn't this sample be managed by @Particular/container-maintainers ?)

**Comment by weralabaj** [comment]
>  shouldn't this sample be managed by @Particular/container-maintainers?

the component listed in the page meta header is core, that's why core maintainers are pinged ;)

As for the package, if you open the sample code or copy usings (using "actions" dropdown in the top right corner of the snippet) then that package is listed. Is there anything about this package that makes it special and we need to highlight it more?

Note, this may actually help, if so, please comment on that issue https://github.com/Particular/DocsEngine/issues/345, thx!

**Comment by timbussmann** [comment]
> As for the package, if you open the sample code or copy usings (using "actions" dropdown in the top right corner of the snippet) then that package is listed.

I don't think that assuming namespaces == nuget packages is a fair assumption to make. While in this case this holds true, for example many of our downstreams place their config extension methods in the root namespace, e.g. https://github.com/Particular/NServiceBus.Newtonsoft.Json/blob/develop/src/NServiceBus.Newtonsoft.Json/NewtonsoftSerializer.cs or https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ/RabbitMQTransport.cs ), so there won't be a corresponding namespace to point at the related packages.

**Comment by WilliamBZA** [comment]
Thanks @timbussman, I'll add the package to the documentation page

**Comment by mauroservienti** [comment]
Why do we need to list that package specifically? It's an implementation details, as we mention early in the doc:

> Note: While this sample illustrates the scenario using Autofac, the same can be achieved by using most other DI libraries.

**Comment by timbussmann** [comment]
@mauroservienti I think it makes sense to note that there might be additional packages required in such cases and to name the one used for autofac. When copying the snippet and trying to resolve the compilation errors, it's not immediately obvious that you need an additional package or what the name of that package is (because `Autofac.Extensions.DependencyInjection` is not a good name imho)

**Comment by WilliamBZA** [comment]
PR submitted

**Comment by WilliamBZA** [comment]
Thanks @weralabaj!!
