### ISSUE TITLE
Feedback: 'Using NServiceBus with ASP.NET MVC'

### ISSUE THREAD

**Issue by robvon** [Particular/docs.particular.net#3429]
Feedback for 'Using NServiceBus with ASP.NET MVC' https://docs.particular.net/samples/web/asp-mvc-application/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/asp-mvc-application/sample.md

ping @Particular/nservicebus-maintainers

**Comment by robvon** [comment]
quote: "The controller is referencing its IBus"

Yeah right.!.. 

Perhaps you don't have version specific doco. Could be misleading though

Regards

Rob

**Comment by weralabaj** [comment]
Thanks @robvon, we'll clarify it.

**Comment by weralabaj** [comment]
Fixed in https://github.com/Particular/docs.particular.net/commit/1cf40b447ad6800d304dab487b4c3e3cab7e7835
