### ISSUE TITLE
Remember selected version across pages

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#3440]
### Problem statement

If I'm on NServiceBus v5, Every single time I follow a link on our documentation site, I have to select the correct version. This is quite annoying since you might forget and are looking for APIs that are not available in your version.

### Solution

Please do not change all the links in documentation to have version number in querystring. Rather remember it in some session or whatever.
Also try to obtain NServiceBus version for downstream packages. Like for Performance Counters, NServiceBus v6 doco is here 👍 

- NServiceBus v6 doco : https://docs.particular.net/nservicebus/operations/performance-counters?version=core_6
- NServiceBus v7 / Performance Counters v2 doco : https://docs.particular.net/nservicebus/operations/performance-counters?version=perfcounters_2

**Comment by weralabaj** [comment]
We have an issue for it here https://github.com/Particular/DocsEngine/issues/217, a while ago @HEskandari started working on this, I don't remember what was the status.

But Docs maintainers always welcome PRs! :D

**Comment by HEskandari** [comment]
The (over?)simplified solution that was using cookies to track the version did not work well as per comments in Particular/DocsEngine#217 so I have left it at that.
