### ISSUE TITLE
Remove version in querystring in search results

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#3441]
It looks like we add the latest active version to the querystring in the search results.

For example searching for "metrics" results in this url : https://docs.particular.net/nservicebus/operations/metrics?version=metrics_3

I copy this url multiple times a day in emails to customers, livechat, etc, etc. I always need to remove the version. Can we please remove it from search results?

**Comment by weralabaj** [comment]
That's if you click on the link on the v7 tab, correct?

So is the suggestion to make another tab the default?

**Comment by weralabaj** [comment]
BTW if sharing the link with a customer, we tend to give answer for a specific version, i.e. the one they're using, as there may be differences in content. So doesn't having some kind of a version actually make more sense?

Asking, since I believe that was the assumption made when the current search results design was decided on.

**Comment by dvdstelt** [comment]
When providing info for a specific version, I make sure the info is in the querystring.
More often I don't know which version it concerns (or other reasons) and I want a clean url. The change was only recent (afaik) to include the version in querystring.

**Comment by dvdstelt** [comment]
> That's if you click on the link on the v7 tab, correct?

No, it's actually in the search results. It basically decides for me which version I'm using and I constantly have to remove it.

**Comment by weralabaj** [comment]
I think the issue was addressed by changing the default tab selected in search results. @dvdstelt reopen if that needs further attention ;)
