### ISSUE TITLE
Feedback: 'Metrics'

### ISSUE THREAD

**Issue by mykevelli** [Particular/docs.particular.net#3445]
Feedback for 'Metrics' https://docs.particular.net/nservicebus/operations/metrics

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/metrics.md

ping @Particular/metrics-maintainers

~~The top of this article says that it targets NSB Version 7.x but the Metrics plugin works on version 5 or higher.  That could cause confusion.~~ Scratch that.  I just noticed that by default the version of metrics on the page is 3, which is only on NSB 7.x.  If you select Metrics version 1 the required version of NSB is reduced.

**Comment by ramonsmits** [comment]
@mykevelli Is the version information at the top clear enough or would you ideas on improving it?

**Comment by mykevelli** [comment]
I don't know what kind of flexibility you have but it did seem unclear to me what all versions of NServiceBus were supported my the metrics feature as a whole (rather than just this document).  If it wasn't for the fact that I read the FAQ on the announcement page (https://particular.net/real-time-monitoring) first I would have thought the metrics feature would only work on 7.x.  

Regarding ideas for improving the clarity, maybe making it clear that although some of the content within the document (like code samples) may only apply to higher versions of the plugin, the feature itself supports NSB back to version 5.  This is probably isolated to documentation that's a starter for the entire feature though and it could probably be dealt with with simple text at the top of the documentation content rather than having to redesign the entire Supported Version system within your documentation builder.

**Comment by ramonsmits** [comment]
@mykevelli Thanks for that feedback. So you would like to immediately want to see somewhere what the supported NServiceBus major versions are?

For example: NServiceBus 3.0 - 7.x

@Particular/docs-maintainers I also think having that information would be really convenient. What do you think?

**Comment by DavidBoike** [comment]
*Does it support NServiceBus 5?* As you switch versions on that page, the earliest (1.x) targets NServiceBus 6.

It would seem that component information box would be the place to display that information. Do you have any UX suggestions for how to surface it?

**Comment by mykevelli** [comment]
I also noticed that the documentation page states that the earliest version targets NSB 6.  I said 5 because that's what is listed in the FAQ on the [feature announcement page](https://particular.net/real-time-monitoring).

**Comment by Scooletz** [comment]
The page has been reorganized, and now, the plugin for SC has a separate page: https://docs.particular.net/monitoring/metrics/install-plugin with all the versions included. Also, notice that for v5 of the core there is no `NServiceBus.Metrics` package, just `NServiceBus.Metrics.ServiceControl`.

**Comment by weralabaj** [comment]
@mykevelli Seems this issue has stalled, apologies for not getting back to you sooner. I'm not quite sure if the original concern has been addressed, but seems it should, at least partially.
If there's anything left, please, reopen this issue or open a new one and I'll take it from there.
