### ISSUE TITLE
Improve 'How to handle exceptions' page adding SC into the mix

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#345]
http://docs.particular.net/nservicebus/how-do-i-handle-exceptions
Customer feedback:
   "I realize I have gone around and around regarding the exception handling.  
    But one of my struggles is addressing our development culture regarding traditional exception handling.  While having an extension point in SC to grab these errors hypothetically and proactively email the team is a pretty cool concept.  However, it requires that our developers/managers let go of the old ways we approached software.  We are not in distributed messaging ecosystem and our processes need to change accordingly.  I can hear it now, “But what if SC is not running”, “But what if SC hiccups or the extension point to send the email throws an exception”.  They are going to want to gravitate back to the way they comfortable handling the exceptions.  I will need to keep pushing, I suppose.
 
Are you hearing similar stories from other customers “How to handle exceptions”.  ***I think a page on your site that goes over a few different use cases and the proposed solution, would be beneficial***."

**Comment by SimonCropp** [comment]
reviewed and updated
