### ISSUE TITLE
Feedback: 'Monitoring instances'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3453]
Feedback for 'Monitoring instances' https://docs.particular.net/servicecontrol/monitoring-instances/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/monitoring-instances/index.md

Unline SC Instance, Monitoring instance is absent from the right side menu.

ping @Particular/servicecontrol-maintainers

![image](https://user-images.githubusercontent.com/1309622/33089604-60992afc-ceae-11e7-8801-3ac1b04d01f3.png)

**Comment by boblangley** [comment]
@Particular/devops-launch-wave-squad I believe this is intentional while the product is in beta, can you confirm?

**Comment by SzymonPobiega** [comment]
@Particular/devops-launch-wave-squad given we're live now, we should add it, right?

**Comment by tmasternak** [comment]
👍 for adding it
