### ISSUE TITLE
Feedback: 'Serialization'

### ISSUE THREAD

**Issue by janpieterz** [Particular/docs.particular.net#3455]
Feedback for 'Serialization' https://docs.particular.net/nservicebus/serialization/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/serialization/index.md

Looks like the `configuration.UseSerialization<XmlSerializer>();` is required now? Migrating an endpoint and it complained until I added above.

ping @Particular/nservicebus-maintainers

**Comment by mikeminutillo** [comment]
Hi @janpieterz, can you tell me which version you are migrating from and to. 

I don't think you should have to specify a serializer. Even the [most recent build of V7 still has `XmlSerializer` as the default](https://github.com/Particular/NServiceBus/blob/7.0.0-alpha32/src/NServiceBus.Core/Serialization/SerializationSettingsExtensions.cs#L44).

**Comment by janpieterz** [comment]
Sure, these are the NServiceBus dependencies:
```
<package id="NServiceBus" version="7.0.0-beta0012" targetFramework="net471" />
<package id="NServiceBus.Autofac" version="7.0.0-beta0003" targetFramework="net47" />
<package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="8.0.0-beta0004" targetFramework="net47" />
<package id="NServiceBus.Persistence.Sql" version="4.0.0-beta0001" targetFramework="net47" />
<package id="NServiceBus.Persistence.Sql.MsBuild" version="4.0.0-beta0001" targetFramework="net47" developmentDependency="true" />
```
When removing the line: `configuration.UseSerialization<XmlSerializer>();`
I get this exception:
```
System.Exception: 'Use 'endpointConfiguration.UseSerialization<T>();' to select a serializer. If you are upgrading, install the `NServiceBus.Newtonsoft.Json` NuGet package and consult the upgrade guide for further information.'
```

**Comment by mikeminutillo** [comment]
Ah, this is caused by the transport and is in the upgrade guide here: https://docs.particular.net/transports/upgrades/asb-7to8#serialization-is-mandatory

You are correct, for Azure Service Bus transport versions 8 and above, selecting a serializer is mandatory.

**Comment by janpieterz** [comment]
Ah, apologies, didn't look there 😄
