### ISSUE TITLE
Service control does not support SQS transport

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#3467]
The fact that SC does not work out of the box with SQS transport is not documented. It should.

**Comment by indualagarsamy** [comment]
cc / @SeanFeldman @Particular/aws-maintainers @Particular/servicecontrol-maintainers

**Comment by mauroservienti** [comment]
A transport adapter sample should be created as well, https://docs.particular.net/servicecontrol/transport-adapter/?version=sctransportadapter_2

**Comment by SeanFeldman** [comment]
Suggestion I had was to have a table with "SC" support. Similar to how we show [what transport transaction modes are supported by the various transports](https://docs.particular.net/transports/transactions?version=core_7#transactions-transaction-levels-supported-by-nservicebus-transports). It's a quick documentation update, though needs to be somewhere where it's easy to spot in the context of SC. Currently, the [info we have](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features) is quite "buried".

A sketch:

|Transport | Supported | May Require</br> Transport Adapter |
|:-:|:-:|:-:|
|ASB| ✔️ | [details](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features#azure-service-bus)  | |
|ASQ| ✔️ | [details](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features#azure-storage-queues) | |
|MSMQ| ✔️ | not required |
|RabbitMQ| ✔️ | [details](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features#rabbitmq-transport) |
|SQL| ✔️ | [details](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features#sql-server-transport)  | |
|SQS| ❌ | [details](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features#amazon-sqs) |
|Learning| N/A | N/A |

**Comment by weralabaj** [comment]
ping, what should we do with this issue?

**Comment by andreasohlund** [comment]
We're about to make it "supported" by providing docker containers that have everything needed (MSMQ/some other tranport + adapter) to run SC on AWS as part of the upcoming launch. So in essense we need to put a green tick on the docs once done?

cc @kbaley @dbelcham @bording

**Comment by kbaley** [comment]
@andreasohlund I'm okay with that approach but I think it will be a few weeks before it's finished. So we need to be okay with this gap in the documentation until then.

**Comment by weralabaj** [comment]
OK, since you're tracking this already, there's no need to keep this issue open.
