### ISSUE TITLE
Feedback: 'Accessing and modifying data'

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#3468]
Feedback for 'Accessing and modifying data' https://docs.particular.net/nservicebus/handlers/accessing-data#without-using-nservicebus-persistence-transport-in-native-transaction-mode

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/handlers/accessing-data.md

ping @Particular/nservicebus-maintainers

In [this snippet](https://github.com/Particular/docs.particular.net/blob/master/Snippets/Core/Core_6/Handlers/DataAccess/Managed.cs#L17) it's not really clear that `MessageHasAlreadyBeenProcessed` (which has a [hidden implementation that throws not implemented here](https://github.com/Particular/docs.particular.net/blob/master/Snippets/Core/Core_6/Handlers/DataAccess/MyOrmExtensions.cs#L13-L16) is something the user would have to implement themselves. I chatted with a user who assumed it must be a framework method.

**Comment by andreasohlund** [comment]
PR raised to address this https://github.com/Particular/docs.particular.net/pull/3477
