### ISSUE TITLE
Azure: configuring to work with SC

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#347]
Related to 
* https://nservicebus.desk.com/agent/case/5649
* https://nservicebus.desk.com/agent/case/6809

@yvesgoeleven wrote:

>   The process for custom transports is to manual & the doco http://docs.particular.net/servicecontrol/multi-transport-support isn’t detailed enough for ASB, especially since multiple binding redirects are required, which differ for each version of the transport/plugin combination

**Comment by mauroservienti** [comment]
Any way we can solve this?

**Comment by yvesgoeleven** [comment]
There is some hint at how to do this at the bottom of the document, without much detail though (was initially there as well, but got removed to simplify the article)... given that the team is working on automating this now, we should not expect the user to do any manual tasks like this in the future, I suggest we leave it as is.

**Comment by SimonCropp** [comment]
manual config of transports will be made obsolete by the new installer
