### ISSUE TITLE
Feedback: 'Consumer Driven Contracts'

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#3479]
Feedback for 'Consumer Driven Contracts' https://docs.particular.net/samples/consumer-driven-contracts/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/consumer-driven-contracts/sample.md

A customer asked me if it is possible to achieve Consumer Driven Contracts with the JsonSerializer. It is actually possible when you modify the enclosed message type header to allow duck typing. See 

```
    class MagicToEnableDuckTyping  : IBehavior<IOutgoingPhysicalMessageContext, IOutgoingPhysicalMessageContext>
    {
        public Task Invoke(IOutgoingPhysicalMessageContext context, Func<IOutgoingPhysicalMessageContext, Task> next)
        {
            var types = context.Headers[Headers.EnclosedMessageTypes];
            var name = typeof(AnyOfTheContractTypes).Assembly.FullName;
            var replaced = types.Replace($", {name}", string.Empty);
            context.Headers[Headers.EnclosedMessageTypes] = replaced;
            return next(context);
        }
    }
```

[cdc_json.zip](https://github.com/Particular/docs.particular.net/files/1519484/cdc_json.zip)

Should we include this on the doco page?

ping @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
Yes we did fix the bug in 6.3 https://github.com/Particular/NServiceBus/issues/4567

So you changed the the sample to use JSON and added that behavior => and it worked?

**Comment by danielmarbach** [comment]
Correct

Am 01.12.2017 08:42 schrieb "Andreas Öhlund" <notifications@github.com>:

**Comment by andreasohlund** [comment]
Would we need a new sample for json or would it be enought to say "if you want to use the json serializer please add this behavior" ?

Side note: We should make the core able to "do not include assembly info in the enclosed message types header" as an opt in.

https://github.com/Particular/NServiceBus/issues/1610

Or should we modify the json serializer to be able to handle this?

**Comment by danielmarbach** [comment]
> Side note: We should make the core able to "do not include assembly info in the enclosed message types header" as an opt-in.

I do think that in the world of integration the fully qualified assembly name is pretty much always useless and the full name would be enough. So I'd rather see this as a core flag on the serializer settings applied for all serializers.

I do think for now we could change the doco to show this behavior. In the future when the core has that flag we can replace it with the flag settings.

**Comment by andreasohlund** [comment]
>I do think that in the world of integration the fully qualified assembly name is pretty much always useless and the full name would be enough. So I'd rather see this as a core flag on the serializer settings applied for all serializers.

Agreed , side note, it would be a core only thing since the serializers isn't involved in creating the header
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Outgoing/SerializeMessageConnector.cs#L51

>I do think for now we could change the doco to show this behavior.

Ok, are you saying to add this as a note to this sample? 

"Support for consumer driven contracts relies on serializers being able to support multiple inheritance. At this time this means either the XML or the Newtonsoft serializer.

Note: The Newtonsoft serializer reguires bla bla bla"

**Comment by danielmarbach** [comment]
For me the SerializeMessageConnector closely belonged to the serialization part of the core, that's why I was thinking that:

```
configuration.UseSerialization<T>(fullNamesOnly : true)
```

or something like that would make most sense

**Comment by andreasohlund** [comment]
Yea, happy with that approach
