### ISSUE TITLE
How to disable heartbeat feature in Dev environment 

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#348]
Google discussion: https://groups.google.com/forum/#!msg/particularsoftware/AUa4OVxtKqM/0d5t4aSFFE4J

> Is it possible to disable the ServiceControl heartbeat functionality in an endpoint through config? I would like ServiceControl to be an optional component for developers on their local machine.
> Right now if you don't have SC installed the plug-in throws a fatal exception and the endpoint is shutdown.

**Comment by mauroservienti** [comment]
I'll close this one since we moved to the requirements stage
