### ISSUE TITLE
Feedback: 'Understanding internal transactions and delivery guarantees'

### ISSUE THREAD

**Issue by ElasticCoder** [Particular/docs.particular.net#3484]
Hi the link on the page doesn't resolve any longer. The link on the page resolves to:
https://github.com/Azure-Samples/azure-servicebus-messaging-samples/tree/master/AtomicTransactions

---------------------------------------------------

Feedback for 'Understanding internal transactions and delivery guarantees' https://docs.particular.net/transports/azure-service-bus/understanding-transactions-and-delivery-guarantees

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/understanding-transactions-and-delivery-guarantees.md

ping @Particular/azure-maintainers

**Comment by SzymonPobiega** [comment]
@Particular/azure-maintainers can you take a look? I don't know where to look for the content if it was moved somewhere else.

**Comment by yvesgoeleven** [comment]
Looks like MS moved it's sample to https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/AtomicTransactions, will update the link

**Comment by yvesgoeleven** [comment]
PR up https://github.com/Particular/docs.particular.net/pull/3492

**Comment by SeanFeldman** [comment]
Hmm, poor naming IMO. The old client is not `Microsoft.ServiceBus.Messaging`, but `WindowsAzure.ServiceBus`. They should have separate samples by the client name.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/docs.particular.net/commit/bcaeca043e68abedfb5cdc17cf87ad5d47c04bf9

Thanks @ElasticCoder
