### ISSUE TITLE
Samples: send from Nancy proposition

### ISSUE THREAD

**Issue by mikedevbo** [Particular/docs.particular.net#3487]
Hi,

I start playing a little bit with http://nancyfx.org framework so maybe it's a good idea to add some samples with description to https://docs.particular.net/samples/web/ 

I prepared some code based on existing web samples: https://github.com/mikedevbo/docs.particular.net/tree/mikedevbo-samples-nancy/samples/web/send-from-nancy/Core_6

I can prepare code for Core_5 and Core_7 and samples description.

Let me know what you think ?

**Comment by SzymonPobiega** [comment]
Sounds great! If you could also prepare a short descriptions similar to the one in the MVC sample https://docs.particular.net/samples/web/send-from-mvc-controller/ it would be awesome. Just created a pull request from your fork and I'll merge it.

❤️

**Comment by SzymonPobiega** [comment]
@mikedevbo Thanks so much! Sorry for delay in merging. Here is it, live https://docs.particular.net/samples/web/send-from-nancy-module/
