### ISSUE TITLE
Add documentation for the new external raven support

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#350]
* No raven suppor in the core anymore
* New assembly targeting raven 2.5
* New config api `config.UsePersistence<RavenDB>()
* No outbox at this stage
* Supports a shared session for sagas
* Better sharing of document stores

**Comment by mauroservienti** [comment]
Regarding:

> No raven suppor in the core anymore
New assembly targeting raven 2.5

is this enough? http://docs.particular.net/nservicebus/ravendb/version-compatibility

**Comment by SimonCropp** [comment]
@mauroservienti yes i think that is enough
