### ISSUE TITLE
Feedback: 'NServiceBus Host Upgrade': missing v4 to v5 upgrade guide

### ISSUE THREAD

**Issue by janv8000** [Particular/docs.particular.net#3506]
> Feedback for 'NServiceBus Host Upgrade Version 7 to 8' https://docs.particular.net/nservicebus/upgrades/host-7to8
> Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/host-7to8.md

Upgrading from NSB Host 4 to 5 made some types obsolete (https://docs.particular.net/nservicebus/hosting/nservicebus-host/?version=host_5#roles-built-in-configurations) .
An upgrade guide similar to  'NServiceBus Host Upgrade Version 7 to 8' would be very helpful.

ping @Particular/host-maintainers

**Comment by ramonsmits** [comment]
@jan Thanks for this feedback, you are right. We should have this. Have you been able to complete your upgrade?

**Comment by ramonsmits** [comment]
Added guidance, closing this
