### ISSUE TITLE
The page 'Load Balancing with the Distributor' requires some love

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#3518]
The page [Load Balancing with the Distributor](https://docs.particular.net/nservicebus/scalability-and-ha/distributor/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * ~[Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scalability-and-ha/distributor/index.md)~ [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/transports/msmq/distributor/index.md)

### Plan of attack

 - [ ] In the "Performance" section include a discussion of capacity parameter
 - [ ] Add a page on extensibility that covers woker availability manager
 - [ ] Add a link to general clustering page from the "High availability" section

**Comment by SzymonPobiega** [comment]
@Particular/platform-dev-squad, @udidahan has suggested this should go through new PlatDev processes for updating old documentation. This issue has been created based on #2187

**Comment by kbaley** [comment]
Ping @Particular/editors. I'm off the next couple of weeks so I can't take this at the moment. Any volunteers?

**Comment by weralabaj** [comment]
ping, what should we do with this issue?

**Comment by kbaley** [comment]
Unless it's urgent, I suggest closing this issue. There are well over 100 pages that haven't been reviewed in almost two years and we're getting to them slowly but steadily.

**Comment by weralabaj** [comment]
So how do we address the changes that @SzymonPobiega outlined in the PoA? How will the reviewer know about those things?

**Comment by danielmarbach** [comment]
The page has been reviewed in April 2019. Given that we generally recommend and push people towards the sender side distribution seam I'm closing this one for now.
