### ISSUE TITLE
Feedback: 'Subscription Persister'

### ISSUE THREAD

**Issue by MeTitus** [Particular/docs.particular.net#3524]
Feedback for 'Subscription Persister' https://docs.particular.net/persistence/sql/subscriptions

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/sql/subscriptions.md

ping @Particular/sqlpersistence-maintainers

Would it be possible for you guys to give a brief on why you would want to disable caching? Thanks

**Comment by WilliamBZA** [comment]
@Particular/sqlpersistence-maintainers Seems like a good idea

**Comment by SzymonPobiega** [comment]
@MeTitus I've added some trade off discussion to that page. Thanks for the feedback!
