### ISSUE TITLE
Feedback: 'Upgrade from ServiceControl.Plugin.NsbX.Heartbeat to NServiceBus.Heartbeat'

### ISSUE THREAD

**Issue by odelljl** [Particular/docs.particular.net#3527]
Feedback for 'Upgrade from ServiceControl.Plugin.NsbX.Heartbeat to NServiceBus.Heartbeat' https://docs.particular.net/nservicebus/upgrades/nservicebus.heartbeat

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/nservicebus.heartbeat.md

ping @Particular/servicecontrol-maintainers

Along with the requirement for explicit configuration is the removal of "Heartbeats" as an accessible Feature subclass.  So code like this has to be removed:

                    if (!shouldSendHeartbeat)
                        configuration.DisableFeature<Heartbeats>();

This could be included in the conversion docs as well.

**Comment by mikeminutillo** [comment]
Thanks for the feedback @odelljl 

I'll update the docs to show this.
