### ISSUE TITLE
Feedback: 'Amazon SQS Transport' Getting Started section is confusing

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3533]
Feedback for 'Amazon SQS Transport' https://docs.particular.net/transports/sqs/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sqs/index.md

The snippet in `Getting Started` is lacking a bit of context. The section states what environment variables are used for the access key and the secret. Directly afterwards is a snippet containing `var s3Configuration = transport.S3("myBucketName", "my/key/prefix");` without stating any information on why that configuration is required.

Also, a link to https://docs.particular.net/transports/sqs/configuration-options would probably be helpful. According to the configuration options page, the `Region` setting is mandatory although the `Getting Started` snippet does not contain any region configuration?

ping @Particular/aws-maintainers

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/docs.particular.net/pull/3551
