### ISSUE TITLE
Feedback: 'Configuration Options'

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3534]
Feedback for 'Configuration Options' https://docs.particular.net/transports/sqs/configuration-options

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sqs/configuration-options.md

How can I use the ` endpointConfiguration.UseTransport<SqsTransport>() .ConnectionString(...)` API to configure the SQS transport? There is no mentioning of the ConnectionString layout in the documentation.

ping @Particular/aws-maintainers

**Comment by mauroservienti** [comment]
As stated here

https://github.com/Particular/NServiceBus.AmazonSQS/blob/832d542657e110cada5cc0c9a4c632c47730fbf0/src/NServiceBus.AmazonSQS/Configure/SqsTransport.cs#L22-L25

A connection string is not supported. The `.ConnectionString(...)` extension method comes from Core.

Should we simply add a note stating that it's not supported?

**Comment by timbussmann** [comment]
I don't think the runtime exception is super helpful as people will see the `ConnectionString` API and try to figure out how the connection string has to look like. There should be a corresponding docs section at least.

wouldn't it even make sense to implement some connection string support instead of enforcing env-vars? What do I have to configure on linux machines?

**Comment by danielmarbach** [comment]
@timbussmann By looking at the AWS ecosystem the environment variable approach is pretty much defacto standard there when it comes to configuring the SDK. It would be definitely possible to implement connection string support. I can raise a feature in the SQS repo and a corresponding plat dev issue. 

I raised an issue for the note https://github.com/Particular/docs.particular.net/pull/3547
Raised SQS issue for ConnectionString https://github.com/Particular/NServiceBus.AmazonSQS/issues/188 and https://github.com/Particular/PlatformDevelopment/issues/1633

**Comment by timbussmann** [comment]
> By looking at the AWS ecosystem the environment variable approach is pretty much defacto standard there when it comes to configuring the SDK

+1 for raising the issue to discuss this as a potential feature. In general I don't mind if the ConnectionString approach isn't supported, but I'd like to avoid anyone struggling to find out how this APIs works or running into runtime exceptions.

people familiar with AWS might have no issue with that, users trying AWS the first time might struggle to figure out how to configure everything correctly.

**Comment by danielmarbach** [comment]
Note about the connection string not being supported added. Closing
