### ISSUE TITLE
Callbacks upgrade guide

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#3546]
We are missing an upgrade guide for Callbacks going from v1 to v2.

Known changes:
- v2 requires being explicitly enabled whereas v1 is enabled by default

**Comment by danielmarbach** [comment]
@mikeminutillo 

![image](https://user-images.githubusercontent.com/174258/34670259-cdd52296-f475-11e7-8db0-13144af75848.png)


https://docs.particular.net/nservicebus/upgrades/callbacks-1to2

**Comment by andreasohlund** [comment]
Good catch @danielmarbach !

@mikeminutillo was this what you had in mind?

**Comment by mikeminutillo** [comment]
It is. Not sure how I missed it. Sorry for the confusion.
