### ISSUE TITLE
Feedback: 'Configuration Options'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3577]
Feedback for 'Configuration Options: S3BucketForLargeMessages' https://docs.particular.net/transports/sqs/configuration-options#s3bucketforlargemessages

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sqs/configuration-options.md

ping @Particular/aws-maintainers

It is not clear from the sample code where exactly a bucket name `nsb-sqs-messages` is coming from. The snippet shows no use of that name and the bucket name specified is `ap-southeast-2`, which is a region name.

![image](https://user-images.githubusercontent.com/1309622/34974700-b18e5662-fa4b-11e7-85d5-8e0dc7551e26.png)

**Comment by danielmarbach** [comment]
Sent in https://github.com/Particular/docs.particular.net/pull/3578
