### ISSUE TITLE
Feedback: 'Endpoint configuration choices'

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#3586]
Current section text seems incorrect for v6 and v7.

Feedback for 'Endpoint configuration choices' https://docs.particular.net/samples/endpoint-configuration/#shut-down-the-endpoint

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/endpoint-configuration/sample.md

ping @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
seems like one sentence which is contained in the version specific partials wasn't removed from the main document. Should be fixed with https://github.com/Particular/docs.particular.net/pull/3587
Thanks @ramonsmits
