### ISSUE TITLE
Feedback: 'Heartbeat Plugin' project hosting link broken

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3596]
Feedback for 'Heartbeat Plugin' https://docs.particular.net/servicecontrol/plugins/heartbeat

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/plugins/heartbeat.md

The "project hosting" link directs to `https://github.com/Particular/?query=Heartbeat` but it seems this doesn't yield any useful result. Other packages seem to link directly to their specific repository (e.g. file based routing).

ping @Particular/servicecontrol-maintainers

**Comment by SzymonPobiega** [comment]
@timbussmann I think this is now fixed after merging the monitoring menu PR. Can you check?

**Comment by WilliamBZA** [comment]
The query should be `https://github.com/Particular/?q=heartbeat` instead of `https://github.com/Particular/?query=Heartbeat`

We'll have to update the components.yaml file.

**Comment by SzymonPobiega** [comment]
Hmmm I can't find that link :(

**Comment by WilliamBZA** [comment]
https://github.com/Particular/docs.particular.net/blob/master/components/components.yaml#L277

**Comment by WilliamBZA** [comment]
I'll do a PR

**Comment by mikeminutillo** [comment]
I assume this fixed after the #3598 was closed?

If not, please re-open.
