### ISSUE TITLE
Feedback: 'Third Party Integration'

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3597]
Feedback for 'Third Party Integration' https://docs.particular.net/nservicebus/messaging/third-party-integration

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/third-party-integration.md

I was searching for "3rd party integration" and was only able to find some other doco pages but not this one, as it uses "Third party" in the title. It feels like this page should show up on that search as well?

ping @Particular/nservicebus-maintainers @Particular/docs-maintainers

**Comment by DavidBoike** [comment]
I’ve thought for awhile that the docs engine should support an “additional search terms” metadata field, which would be useful for stuff like this.

**Comment by timbussmann** [comment]
I know this is not the right place to really bring this up, but I'm quite unhappy with the search in general (especially about ranking the search results though). It feels like this is a page which would show up when using a more sophisticated search engine (e.g. beacuse of "party" and "integration" keywords)?

**Comment by timbussmann** [comment]
I've also raised this in pdev as I think it's a larger issue with the current search engine.

**Comment by weralabaj** [comment]
@timbussmann I think this issue should be raised either in plat dev or docs engine repos, since you raised it in the first one, I'm closing.
