### ISSUE TITLE
Feedback: 'NServiceBus features requiring usage of Transport Adapter'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3599]
Feedback for 'NServiceBus features requiring usage of Transport Adapter' https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/transport-adapter/incompatible-features.md

Looks like doco is outdated. With the recent SC update ([announcement](https://discuss.particular.net/t/servicecontrol-1-46-0-minor-release-available/320)) SQS is supported by SC.

**Comment by danielmarbach** [comment]
@SeanFeldman SQS is still not supported by SC. The monitoring instance supports SQS but not the audit/recoverability instance.

> Currently only monitoring of endpoints using NServiceBus v6 and higher is supported. For additional capabilities such as recoverability and auditing provided by Service Control a Transport Adapter is required.

**Comment by SeanFeldman** [comment]
SC Monitoring Instance vs SC Instance - not confusing at all 😃
