### ISSUE TITLE
Update the RavenDB connection/persistence API documentation

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#360]
* http://docs.particular.net/nservicebus/using-ravendb-in-nservicebus-connecting
* http://docs.particular.net/search?q=ravendb
* http://docs.particular.net/nservicebus/upgradeguides/4to5
* http://docs.particular.net/nservicebus/ravendb/versioncompatibility

**Comment by SimonCropp** [comment]
@mauroservienti is this done?

**Comment by SimonCropp** [comment]
@mauroservienti no response so i am assuming this is done. please re-raise new issue for anything outstanding
