### ISSUE TITLE
Ninject Sample dependencies

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3606]
The dependencies for the ninject sample seem to be a bit conflicting:

* We're referencing the latest nsb.ninject package, which itself brings the dependencies to 
  * ContextPreservation 3.3.1
    * Ninject 3.3.4
  * NamedScope 3.3.0
    * Ninject 3.3.4

but then the sample additionally references
* NamedScope 3.* (=3.3.0)
* ContextPreservation 3.* (=3.3.1)
* ChildKernel 3.* **( =3.2 !)**
  * ChildKernel 3.2 has the following Ninject dependency range: (>= 3.2.0 && < 3.3.0), therefore it doesn't match with the other packages.

so:
* Do we need the ChildKernel package at all? Removing it doesn't seem to cause any issues to the sample.
* Do we need to explicitly reference the Ninject and extensions packages, as those are already pulled in as transitive dependencies by the nsb.ninject package?
* if both of the above would be yes: should we downgrade to the 3.2.x to make the compiler warning go away?

ping @Particular/container-maintainers
cc @bording

**Comment by bording** [comment]
I suspect the ChildKernel package reference can be removed entirely.

As far as the sample having direct references to packages being referenced transitively, the idea for the samples is to use the direct reference with a wildcard to pull in the latest version of the package vs. relying on just the transitive reference, which resolves the lowest the matches the version range.

You'll see that pattern used throughout the docs samples. In this case, if we're following the pattern, I'd expect to see references in the sample to Ninject, NamedScope, and ContextPreservation.

**Comment by weralabaj** [comment]
ping, what should we do about this issue?

**Comment by danielmarbach** [comment]
The ChildKernel package is removed. As of the rest we seem to follow the docs sample conventions. Closing this for now
