### ISSUE TITLE
Feedback: 'Simple SQL Persistence Usage'

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3617]
Feedback for 'Simple SQL Persistence Usage' https://docs.particular.net/samples/sql-persistence/simple/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/sql-persistence/simple/sample.md

The sample is quite confusing to run as by default all "server" options are enabled to run and endpoints will blow up if not every configuration is available (e.g. environment variables for the mysql or postgres endpoints). Some description at the beginning would be helpful to help to configure the startup projects so that it only includes the endpoints the users wants to run against.

ping @Particular/sqlpersistence-maintainers

**Comment by DavidBoike** [comment]
Agree

**Comment by SzymonPobiega** [comment]
How do we go about prioritizing this?

**Comment by weralabaj** [comment]
Fixed in https://github.com/Particular/docs.particular.net/commit/55a5b16bcaf386f4a112856a5de9980b245443fb
