### ISSUE TITLE
Host Profiles for logging - sample missing

### ISSUE THREAD

**Issue by Scooletz** [Particular/docs.particular.net#3632]
The logging sample for host profiles has not been upgraded to the recent version. Also the update guide does not cover all the changes that have been applied to the public API, for instance it doesn't mention `IConfigureLoggingForProfile` and a few others. The best way to track the missing info is to try migrating the sample

- sample: https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostprofiles
- upgrade guide: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/host-7to8.md

**Comment by weralabaj** [comment]
ping, what should we do with this since related issue has been closed?

**Comment by weralabaj** [comment]
Seems like we don't think it's worth the effort, so I'm closing.
