### ISSUE TITLE
Feedback: 'Message lock renewal'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3643]
Feedback for 'Message lock renewal' https://docs.particular.net/transports/azure-service-bus/message-lock-renewal

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/message-lock-renewal.md

There's no explanation how `LockLostException` relates to `AutoRenewTimeout` and `PrefetchCount` that can affect it.

ping @Particular/azure-maintainers

**Comment by weralabaj** [comment]
ping @Particular/azure-maintainers

**Comment by danielmarbach** [comment]
@weralabaj as far as I remember @SeanFeldman volunteered to add the necessary addition to the doco page. It seems he has the most context.

**Comment by SeanFeldman** [comment]
I dropped the ball on this one, my bad.
PR sent: #3767
