### ISSUE TITLE
Feedback: 'Client-Side Callbacks'

### ISSUE THREAD

**Issue by dasjestyr** [Particular/docs.particular.net#3647]
Feedback for 'Client-Side Callbacks' https://docs.particular.net/nservicebus/messaging/callbacks

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/callbacks.md

ping @Particular/nservicebus-maintainers

> "This means that callbacks require the endpoint to configure a unique instance Id"

> "To avoid creating an excessive number of queues, the Id needs to be kept stable. For example, it may be retrieved from a configuration file or from the environment (e.g. role Id in Azure or machine name for on-premises deployments)."

I feel like these two concepts conflict with each other. How can I get an ID from a static configuration file _and_ have it be instance unique at the same time?

I've opened a discussion here as well:  https://discuss.particular.net/t/callbacks-uniquely-identifiable-endpoint-concerns-when-deployed-in-docker/424

**Comment by timbussmann** [comment]
@danielmarbach @mauroservienti based on the conversation in discourse, do you feel there is something worth adding to the documentation?

**Comment by mauroservienti** [comment]
I'll add a review of that page to my to do list @timbussmann

**Comment by weralabaj** [comment]
ping

**Comment by weralabaj** [comment]
@dasjestyr Seems like the discussion addressed the issue? If I missed something, please, feel free to reopen and I'll look into this in more depth.
