### ISSUE TITLE
Feedback: 'MSMQ Transport' should mention server 2016

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3648]
Feedback for 'MSMQ Transport' https://docs.particular.net/transports/msmq/#msmq-configuration-windows-2012

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/msmq/index.md

ping @Particular/msmq-transport-maintainers

**Comment by indualagarsamy** [comment]
Thanks @SimonCropp for your feedback. Will ping you once this is fixed.

**Comment by danielmarbach** [comment]
ping @Particular/msmq-transport-maintainers

**Comment by SimonCropp** [comment]
btw u should make the maintainer teams public so external people can reference them

**Comment by weralabaj** [comment]
Seems to be addressed now so I'm closing https://docs.particular.net/transports/msmq/#msmq-configuration-windows-2012-and-2016

**Comment by andreasohlund** [comment]
@SimonCropp regarding

>btw u should make the maintainer teams public so external people can reference them


Can you clarify? eg @Particular/nservicebus-maintainers is already visible

Or do you mean adding all the teams to the `CONTRIBUTORS` file in order to request reviews from them on PR's?

**Comment by SimonCropp** [comment]
It is only visible for particular org members

**Comment by andreasohlund** [comment]
Hmm, can’t find any other setting in the GH ui, do you know how to make
this happen?

**Comment by weralabaj** [comment]
https://twitter.com/shiftkey/status/997053353497509894 Maybe we should raise feature request with GH.

**Comment by weralabaj** [comment]
BTW I contacted their support, I'll let you know what I've learned.
