### ISSUE TITLE
corrupted performance counters

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#365]
This has  happened to enough people that we should have some official doco for it

eg
https://groups.google.com/forum/#!topic/particularsoftware/sX1bl2k7ExY

**Comment by ramonsmits** [comment]
I'll make a document that explicitly mentions this problem and do a cross reference with the following document https://github.com/Particular/docs.particular.net/blob/75fbd9f8ef3039204df6f0f184e42b40659588b4/nservicebus/monitoring-nservicebus-endpoints.md

**Comment by ramonsmits** [comment]
I created a pull request but somehow this issue is not referenced from it.
