### ISSUE TITLE
Feedback: 'Message routing'

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3650]
Feedback for 'Message routing' https://docs.particular.net/nservicebus/messaging/routing

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/routing.md

I can't find any description on how to use the config section based message mappings anymore.
@SzymonPobiega according to github you've been redesigning the routing doco, is there any missing background on that?

edit: for clarification, the description does not show a sample or further description on how the xml based config should have to look like.

ping @Particular/nservicebus-maintainers

**Comment by SzymonPobiega** [comment]
@timbussmann it is in that page e.g.

> Command routing can also be configured in a configuration section...

It does not contain any examples/snippets of such config though.

**Comment by timbussmann** [comment]
yeah that's what I meant @SzymonPobiega. Does the issue description need some clarification?

**Comment by timbussmann** [comment]
> and we never had them

is that true?

**Comment by SzymonPobiega** [comment]
Yes. Here's the file when I removed it: https://github.com/Particular/docs.particular.net/pull/1787/files#diff-5243694901daef66ed38c8a37d236da4.
