### ISSUE TITLE
Feedback: 'Control of serialization via the pipeline'

### ISSUE THREAD

**Issue by siimv** [Particular/docs.particular.net#3657]
Hi,

I was unable to replace the existing connector with the key `NServiceBus.SerializeMessageConnector` and had to use `SerializeMessageConnector` instead. This was the only way to get my custom connector to work.

Is the sample out of date or I am missing something else?

I'm using v6.4.3 and also using bridge for ASB-MSMQ (although this should not affect it).
And I'm aware of UserSerializer() and AddDeserializer() methods, but unfortunately I cannot change (currently) the other side of the bridge.

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/pipeline/multi-serializer/sample.md

ping @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
Hey @siimv 

Thanks for raising this issue. You're absolutely right, the StepId is just `SerializeMessageConnector` without any Namespaces in it. I'll fix the sample to use the correct step id. It would be nice if NServiceBus would throw an exception if you're trying to override a behavior which doesn't exist though.

**Comment by siimv** [comment]
Throwing an exception would be a good idea, it would save a lot of time when debugging similar issues.

Also I noticed that it didn't throw any exceptions when I tried to delete some non-existent key from the pipeline.
