### ISSUE TITLE
expand on the differences between audit and forwarding

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#366]
Atm there is no difference. And that's the issue, we want to transition forwarding to mean:
"Forward the processed message untouched to X other queues" (note the untouched and X)
The current audit/forward actually modifies/adds headers to the message.

A possible scenario is:

"As a devop I'm moving a service from endpoint A to endpoint B and I do not want to be required to update immediately/at the same time all the senders to the new configuration so I want to configure endpoint A to forward all messages of type XYZ to endpoint B so to be able to gradually update senders configuration or simply to temporarily move something transparently."

--

related to #327

**Comment by mauroservienti** [comment]
backlogged until there is a difference.

**Comment by weralabaj** [comment]
@mauroservienti is that still relevant? can we close?

**Comment by mauroservienti** [comment]
If my last statement, there is no difference yet, is still true, then I see no reason to keep this open.

**Comment by weralabaj** [comment]
Confirmed with Andreas that there's a difference now. Need to investigate the details.
