### ISSUE TITLE
Azure: How to use multiple servicebus namespaces

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#368]
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

**Comment by mauroservienti** [comment]
Has this been merged with #361? can we close this?

**Comment by SeanFeldman** [comment]
@yvesgoeleven what do you think? Should we have a separate issue (and doco) for ASB or not?

**Comment by yvesgoeleven** [comment]
I suggest incorporating it in the existing document, at least until the client side routing and new topology is released, than it should move into that documentation

**Comment by mauroservienti** [comment]
> I suggest incorporating it in the existing document, at least until the client side routing and new topology is released, than it should move into that documentation

@yvesgoeleven which existing document?

**Comment by yvesgoeleven** [comment]
This one http://docs.particular.net/nservicebus/using-multiple-azure-storage-accounts-for-scaleout

**Comment by yvesgoeleven** [comment]
In v7 we have extended the number of options here, ensure to include these are included:
- scaleout
- HA
- georeplication
- sharding

**Comment by indualagarsamy** [comment]
@SeanFeldman  - any updates on this?

**Comment by SeanFeldman** [comment]
@indualagarsamy will be coming as part of v7 doco.

**Comment by weralabaj** [comment]
Are all aspects addressed by @melkio's PR? Can we close?

**Comment by melkio** [comment]
IMO yes. Everything transport can do related to this topic is covered by my PR

@Particular/azure-service-bus-maintainers thoughts?

**Comment by SeanFeldman** [comment]
:+1:

**Comment by yvesgoeleven** [comment]
yeah we can close this
