### ISSUE TITLE
Feedback: 'Transactions and Message Processing'

### ISSUE THREAD

**Issue by mikesigs** [Particular/docs.particular.net#3682]
Feedback for 'Transactions and Message Processing' https://docs.particular.net/nservicebus/operations/transactions-message-processing

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/transactions-message-processing.md

> By default, the transaction timeout limit is set to 10 minutes. See the Override the System.Transactions default timeout of 10 minutes article to learn how to adjust that value.

I believe this documentation is inaccurate. The default **Maximum** timeout for Transactions is 10 minutes. The actual default timeout itself is only 1 minute.

**Comment by andreasohlund** [comment]
Thank you so much @mikesigs , I've raised a PR to address this, https://github.com/Particular/docs.particular.net/pull/3690, can you take a look?
