### ISSUE TITLE
Feedback: 'Installer Workflow'

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#3685]
Feedback for 'Installer Workflow' https://docs.particular.net/persistence/sql/installer-workflow

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/sql/installer-workflow.md

ping @Particular/sqlpersistence-maintainers 

On netcore app the path is /bin/debug/netcoreapp2.0 should we update to mention that?

I have a user that needs to copy the output over to the project that is hosting the endpoint. Do we need a section to cover that?

**Comment by andreasohlund** [comment]
Cc @ramonsmits

**Comment by SzymonPobiega** [comment]
@andreasohlund so the actual path depends on the VS project type, right? If I use the old type I get `\bin\debug\` and if I get the new SDK type I get `\bin\debug\{target}`?

**Comment by andreasohlund** [comment]
Yes that seems to be correct

**Comment by weralabaj** [comment]
Fixed in https://github.com/Particular/docs.particular.net/commit/ca6a8fc4533dc05df0f5caef8b8d0b82010c9ebf
