### ISSUE TITLE
how to perform multiple transactional raw message sends?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3689]
can [this page](https://docs.particular.net/nservicebus/rawmessaging/) be updated to illustrate doing multiple message sends inside the same transaction? specifically a sql transaction.

**Comment by mikeminutillo** [comment]
For transports that can participate in transaction scopes you could probably get away with:

```csharp
using(var scope = new TransactionScope(TransactionScopeOption.RequiresNew, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
{
  var transportTransaction = new TransportTransaction();
  transportTransaction.Set(Transaction.Current);

  // ... create an array of TransportOperation instances (one for each message), as in article

  await sender.Dispatch(
        outgoingMessages: new TransportOperations(operations),
        transaction: transportTransaction,
        context: new ContextBag())
    .ConfigureAwait(false);

  scope.Complete();
}
```

**Comment by mikeminutillo** [comment]
If you _need_ to do it with a native SQL Transaction then you can add the connection and native transaction objects to the `TransportTransaction` bag. [Here is how the transport does it](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/ProcessWithNativeTransaction.cs#L66).

In either case, the message dispatcher will pull out the transaction details and use them in dispatching the transport operations.

**Comment by mikeminutillo** [comment]
@SimonCropp does my answer help to address your question? Does it make sense to add this to the sample?

It's a shame we can't ask the transport to provide a `TransportTransaction` object (or at least fill one in on request). Then we could abstract it away again.

**Comment by SimonCropp** [comment]
@mikeminutillo i felt it was a little convoluted to work through NSB raw. i ended up going full native


        using (var connection = await OpenSqlConnection().ConfigureAwait(false))
        using (var transaction = connection.BeginTransaction())
        {
            foreach (var attachment in attachments)
            {
                await persister.SaveBytes(connection, transaction, messageId.ToString(), attachment.Key, DateTime.UtcNow.AddDays(10), attachment.Value, cancellation).ConfigureAwait(false);
            }

            using (var command = new SqlCommand(insertSql, connection))
            {
                command.Transaction = transaction;
                var parameters = command.Parameters;
                parameters.Add("Id", SqlDbType.UniqueIdentifier).Value = messageId;
                parameters.Add("Headers", SqlDbType.VarChar).Value = GetHeaders(type, user);
                parameters.Add("Body", SqlDbType.VarBinary).Value = bytes;
                parameters.Add("Recoverable", SqlDbType.Bit).Value = true;
                await command.ExecuteNonQueryAsync(cancellation).ConfigureAwait(false);
            }

            if (cancellation.IsCancellationRequested)
            {
                transaction.Rollback();
            }
            else
            {
                transaction.Commit();
            }
        }

this ended up resulting in less overall code (since i didnt need send only endpoint to pass to NSB raw) and allowed me to have 4 fewer nuget package dependencies.

so will close this
