### ISSUE TITLE
Inconsistent documentation / advice around availability & scale out

### ISSUE THREAD

**Issue by roycornelissen** [Particular/docs.particular.net#369]
In conference calls and public presentations, Particular usually advises to set up a scale out scenario (with MSMQ) in such a way that you can benefit from virtualization. I.e. create a VM for the Distributor/Master node, put the queue data on a SAN and have a simple setup. This way you can avoid setting up a complex and expensive clustering environment.

However, the docs site now contains an article (originally written by David Boike) that states that you need to run NSB in a Windows Failover Cluster in order to benefit from the reliability features in NSB.

See http://docs.particular.net/nservicebus/deploying-nservicebus-in-a-windows-failover-cluster

This is seems somewhat inconsistent.

It would be better to have an article that explains that there are two options, and also explains the former option.

**Comment by mauroservienti** [comment]
@sfarmar #395 seems to be the tracker for this, can we close this one?

**Comment by SimonCropp** [comment]
@DavidBoike since u now work for us can u have a look at this one :)

**Comment by sfarmar** [comment]
@DavidBoike I'd be glad to help

**Comment by SimonCropp** [comment]
given the current status of the distributor moving forward i am closing this one. please feel free to open a PR if u think it is still work doing
