### ISSUE TITLE
Add doco for ExposeRavenDB setting

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3700]
https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/Settings/Settings.cs#L89

so, when debugging, users dont need to troll through the SC code base to reverese engineer

**Comment by boblangley** [comment]
@SimonCropp The setting's documentation is now available here: https://docs.particular.net/servicecontrol/creating-config-file#troubleshooting-servicecontrolexposeravendb

**Comment by SimonCropp** [comment]
@boblangley thanks
