### ISSUE TITLE
Feedback: 'Publish-Subscribe'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3717]
Feedback for 'Publish-Subscribe' https://docs.particular.net/nservicebus/messaging/publish-subscribe/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/publish-subscribe/index.md

There's nothing about polymorthic dispatching.
The only information available is a [7yo post](http://udidahan.com/2011/01/13/polymorphism-and-messaging/) from @udidahan.

**Comment by weralabaj** [comment]
@SeanFeldman We also have a couple of paragraphs here https://docs.particular.net/nservicebus/messaging/messages-as-interfaces, not sure how close/far this is to/from what you have in mind?

**Comment by SeanFeldman** [comment]
I've looked at that documantation page @weralabaj and have to admit it's rather confusing, and not even remotely as nice as the 7yo blog post. We've built a [sample](https://docs.particular.net/samples/azure/polymorphic-events-asb/) for one of the ASB topologies. Would be nice if doco would be a little more detailed.

**Comment by weralabaj** [comment]
OK, so maybe the solution would be to take Udi's post and paraphrase for doco purposes.

**Comment by SeanFeldman** [comment]
That does sound appealing. I'm not sure why we haven't done that before tbh 🙂

**Comment by kbaley** [comment]
[PR under review](https://github.com/Particular/docs.particular.net/pull/6538)

**Comment by kbaley** [comment]
PR merged. Closing
