### ISSUE TITLE
How to disable SLR for a given exception

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#372]
Some users are asking how to control SLR on a per exception basis. We have no guidance for this.

We need to change http://docs.particular.net/nservicebus/second-level-retries to mention how to do this.

Here's the code (need to be checked that it still works) :+1: 

http://andreasohlund.net/2012/09/26/disabling-second-level-retries-for-specific-exceptions/

**Comment by mauroservienti** [comment]
@SimonCropp @sfarmar can't we simply add a note on [this](http://docs.particular.net/nservicebus/second-level-retries) to highlight that in the `CustomRetryPolicy` we can also check the headers to inspect the exception type?

**Comment by SimonCropp** [comment]
@mauroservienti think this might be better as a sample. thoughts?

**Comment by mauroservienti** [comment]
+1, and we can link the sample from the article

**Comment by andreasohlund** [comment]
Awesome!

**Comment by sfarmar** [comment]
So what are we doing?

**Comment by mauroservienti** [comment]
@sfarmar setup the sample? do you want to take it?

**Comment by sfarmar** [comment]
Yup!
So I'm going to take http://andreasohlund.net/2012/09/26/disabling-second-level-retries-for-specific-exceptions/

and build a sample for v3, 4, 5 on a branch.

**Comment by mauroservienti** [comment]
@sfarmar basically yes, snippets are [already in place](http://docs.particular.net/nservicebus/second-level-retries) they need:

* to be extracted from the above page into a dedicated sample;
* to the above snippets one that shows how to manage exceptions needs to be added;

**Comment by SimonCropp** [comment]
http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries-custom-retry-policy-exception-based-policy
