### ISSUE TITLE
Feedback: 'Sagas'; MarkAsComplete is poorly documented

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3727]
Feedback for 'Sagas' https://docs.particular.net/nservicebus/sagas/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sagas/index.md

`MarkAsComplete` is very poorly documented in the Saga doco. It does barely mention what behavior to epxect once a saga is completed.

ping @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
Yea, the whole paragraph needs some love. Will take a stab at it
