### ISSUE TITLE
Feedback: 'Install ServicePulse in IIS'

### ISSUE THREAD

**Issue by flymason** [Particular/docs.particular.net#3729]
- Step 1 of the Advanced configuration says to install Application Request Routing when instead it should have you install the URL Rewrite as a prerequisite to step 7. (https://www.iis.net/downloads/microsoft/url-rewrite)
- Setp 4 of the Advanced configuration should specify that the location of app.constants.js is under the js directory.
- Under Basic setup, the blue tip "ServicePulse.Host.exe can be found..." and the following paragraph: "Once the ServicePulse files are successfully extracted..." should both be moved up so that they are adjacent to the extract command code (ServicePulse.Host.exe --extract --outPath="C:\inetpub\websites\ServicePulse). The netsh instructions split these up and causes confusion.

Feedback for 'Install ServicePulse in IIS' https://docs.particular.net/servicepulse/install-servicepulse-in-iis

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicepulse/install-servicepulse-in-iis.md

ping @Particular/servicepulse-maintainers

**Comment by weralabaj** [comment]
@WilliamBZA are you working on this?

**Comment by weralabaj** [comment]
ping @WilliamBZA

**Comment by weralabaj** [comment]
Thanks 💯
