### ISSUE TITLE
Feedback: 'Installers'

### ISSUE THREAD

**Issue by rnwood** [Particular/docs.particular.net#3737]
Feedback for 'Installers' https://docs.particular.net/nservicebus/operations/installers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/installers.md

ping @Particular/nservicebus-maintainers

> By default, installers are only run when the application starts with a debugger attached. This includes applications being debugged remotely.

I just wanted to feed back that I found this choice of behaviour very suprising and spent some frustrating time trying to explain why my application was behaving differently inside/outside the debugger before I found this documentation.

My opinion is that installers should never be run automatically. To ensure that people are aware during early development (presumably the reason you have this behaviour?), you could enforce that either `EnableInstallers()` or `DisableInstallers()` is called before the endpoint is started with a clear error message if ommitted.

**Comment by weralabaj** [comment]
Thanks @rnwood for sharing this, I'll make sure we persist that opinion and discuss how/when we can make this feature less confusing. I think the explicit opt-in you suggested makes indeed more sense.

**Comment by timbussmann** [comment]
@rnwood agreed, we were also unhappy with that behavior. It's intention was to provide a good development experience out of the box, as it would automatically create required queues. But it also caused quite a bit of confusion and therefore version 7 changes the default behavior to no longer call installers unless explicitly enbled using `EnableInstallers()`, see the v7 documentation: https://docs.particular.net/nservicebus/operations/installers?version=core_7

it sounds like that new behavior is aligned with your expectations?

**Comment by rnwood** [comment]
@timbussmann Yes the new v7 behaviour is much more reasonable.  Thanks for reviewing this feedback.
