### ISSUE TITLE
Feedback: 'SagaAudit Plugin'

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#3739]
Feedback for 'SagaAudit Plugin' https://docs.particular.net/servicecontrol/plugins/saga-audit

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/plugins/saga-audit.md

ping @Particular/servicecontrol-maintainers 

Should the code sample also use `particular.servicecontrol` as the example queue name? 

Seems like the current name confused this user https://discuss.particular.net/t/heartbeat-configuration/497/2

**Comment by boblangley** [comment]
@andreasohlund I fixed this via PR #3747
