### ISSUE TITLE
add doco for "applicative header"

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3752]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Headers.cs#L20

> This header is considered an applicative header.

https://docs.particular.net/search?q=applicative

**Comment by weralabaj** [comment]
@Particular/nservicebus-maintainers Can you fix this?

**Comment by timbussmann** [comment]
I think it makes more sense to remove the comments instead. Raised a PR here: https://github.com/Particular/NServiceBus/pull/5149

It might make sense to document the gateway's mechanism on prefixing original headers. Maybe some gateway expert might be able to help us with that.

**Comment by timbussmann** [comment]
addressed here: https://github.com/Particular/NServiceBus/pull/5149
Thanks for the feedback @SimonCropp 👍
