### ISSUE TITLE
Feedback: 'OWIN HTTP Message Pass Through'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3759]
Feedback for 'OWIN HTTP Message Pass Through' https://docs.particular.net/samples/web/owin-pass-through/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/owin-pass-through/sample.md

ping @Particular/nservicebus-maintainers

More customers would get value out of a variant of this sample that is build on the aspnet core stack. this way they can leverage existing aspnet core extensions (like authentication and authorisation ) and can also co-host with an existing web app.

**Comment by SimonCropp** [comment]
i ask since to had to create a asp core implementation today for the reasons listed above

**Comment by weralabaj** [comment]
Covered in https://github.com/Particular/docs.particular.net/issues/3770

**Comment by WojcikMike** [comment]
@SimonCropp do I understand correctly that what you ask for is changing OWIN host project to use aspnet core instead of being console app. So in the sample there would be 2 web sites: one with html + js calling owin. and the second hosting owin. Is that correct or did I miss something

**Comment by SimonCropp** [comment]
@WojcikMike have a look at how this sample is put together https://docs.particular.net/samples/web/sql-http-passthrough/
