### ISSUE TITLE
Generate design ideas for presenting content specific to Dev-Ops 

### ISSUE THREAD

**Issue by jdrat2000** [Particular/docs.particular.net#376]
Generate some ideas as to how we might modify the docs landing page to more efficiently serve the Dev/Ops visitor and person.   This ideas has been discussed in a handful of emails and is related to the following issues:

https://github.com/Particular/docs.particular.net/issues/370
https://github.com/Particular/docs.particular.net/issues/369
https://github.com/Particular/docs.particular.net/issues/287

The current documentation structure is primarily product centric.  All documents are firstly organized by product and generally only indexed within the context of the product with occasional exceptions. 

New and Existing content related to dev-ops categories could be linked to from pages in an alternative structure and indexing the same content within another taxonomy.

**Comment by SimonCropp** [comment]
this is happening as part of other issues http://docs.particular.net/search?q=scripting
