### ISSUE TITLE
Feedback: 'SQL Server Transport SQL statements'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3760]
Feedback for 'SQL Server Transport SQL statements' https://docs.particular.net/transports/sql/sql-statements#runtime-send-message

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sql/sql-statements.md

ping @Particular/sqlserver-transport-maintainers

this page needs to explain (or link to) the relationship between the `CorrelationId` and `ReplyToAddress` columns and the serialized headers. do they need to be duplicated in both? can they exist only in the columns? what happens if they mismatch? does the sql transport validate and throw?

**Comment by weralabaj** [comment]
ping @Particular/sqlserver-transport-maintainers (since the automatic one doesn't work) ;)

**Comment by SzymonPobiega** [comment]
I think we should mark it for the next maintenance release of SQLT. @tmasternak ?

**Comment by SzymonPobiega** [comment]
Attempt to fix this: https://github.com/Particular/docs.particular.net/pull/3766
