### ISSUE TITLE
Feedback: 'OWIN HTTP Message Pass Through'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3764]
Feedback for 'OWIN HTTP Message Pass Through' https://docs.particular.net/samples/web/owin-pass-through/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/owin-pass-through/sample.md

ping @Particular/nservicebus-maintainers

this sample should address how to do dedup if the web client is using a retry mechanism

**Comment by weralabaj** [comment]
ping @Particular/nservicebus-maintainers
