### ISSUE TITLE
Create new web sample projects on .NET core

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#3770]
* [x]  \web\asp-mvc-application\
 * [x]  \web\asp-web-application\
 * [ ]  ~~\web\owin-pass-through\~~ https://github.com/Particular/docs.particular.net/issues/3759
 * [x]  \web\send-from-mvc-controller\
 * [x] \callbacks\
 * [x] \show-case\on-premise

As per Mauro's advice [here](https://github.com/Particular/docs.particular.net/issues/3078#issuecomment-387407463).

**Comment by weralabaj** [comment]
This will be tracked as part of .NET core launch.

**Comment by SimonCropp** [comment]
@weralabaj give i raised the original issue. Where is a replacement issue i can track?

**Comment by weralabaj** [comment]
Reopening to provide visibility into progress for people tracking this.

**Comment by SimonCropp** [comment]
@weralabaj thanks

**Comment by WojcikMike** [comment]
At the moment I will exclude the owin sample from this issue, as it is potentially changing the sample rather than just modifying it to use .net core. I reopened original Simon's issue for now, I will get more clarification and prepare a plan for moving it forward.
