### ISSUE TITLE
Feedback: 'SQLServer Transport Scripting'

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#3778]
Feedback for 'SQLServer Transport Scripting' https://docs.particular.net/transports/sql/operations-scripting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sql/operations-scripting.md

ping @Particular/sqlserver-transport-maintainers 

Should we add some comments saying that the timeout queues are optional now?

https://docs.particular.net/transports/sql/operations-scripting?version=sqltransport_4#create-queues-creating-queues-for-an-endpoint

**Comment by SzymonPobiega** [comment]
@andreasohlund does this https://github.com/Particular/docs.particular.net/pull/3803 address your concern?

**Comment by andreasohlund** [comment]
Yep
