### ISSUE TITLE
Feedback: 'Metric definitions'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3784]
Feedback for 'Metric definitions' https://docs.particular.net/monitoring/metrics/definitions

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/monitoring/metrics/definitions.md

[Known Limitations section](https://docs.particular.net/monitoring/metrics/definitions#metrics-captured-queue-length-known-limitations) has a bullet point about sender-side distribution with non-identical receiving instances, but doesn't actually spell out what the limitation is.

![image](https://user-images.githubusercontent.com/1309622/40206119-f7855fd0-59eb-11e8-8784-7f5718ee90a3.png)

**Comment by weralabaj** [comment]
This section has been removed as part of providing [native queue length implementations](https://github.com/Particular/docs.particular.net/commit/e1ac020a83ac399f28e4d7555781b2dd2a75ade5#diff-d676156d6401c1b5b2e4df1811dc86ad) I think, so no longer relevant.
