### ISSUE TITLE
Improve 'Unit Testing' to cover what assemblies are used for testing

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#379]
Based on user feedback:
> The setup is that I have one unit test project which references several different DLLs, each of which will be hosted by different instances of NServiceBus.Host.exe, as well as another share library with a lot of common logic.

>I found a way that I was able to limit which DLLs get scanned in the unit test project by passing only the types I wanted scanned into NServiceBus.Testing.Test.Initialize(typeof(RunBeforeConfiguration));

>**The existence and purpose of this constructor argument could be better documented by being mentioned on http://docs.particular.net/nservicebus/unit-testing, instead of having to scour the rest of the internet to find it.**

**Comment by mauroservienti** [comment]
Fixed, closing.
