### ISSUE TITLE
Feedback: 'NServiceBus Testing Upgrade Version 6 to 7'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3809]
newer upgrade guides should be sorted higher in the menu

Feedback for 'NServiceBus Testing Upgrade Version 6 to 7' https://docs.particular.net/nservicebus/upgrades/testing-6to7

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/testing-6to7.md

ping @Particular/nservicebus-maintainers

**Comment by kbaley** [comment]
Thanks @SimonCropp. Menu has been updated. I didn't see any others that were out of order.

**Comment by SimonCropp** [comment]
@kbaley thanks
