### ISSUE TITLE
Feedback: 'Configuration Settings'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3812]
Feedback for 'Configuration Settings' https://docs.particular.net/servicecontrol/creating-config-file

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/creating-config-file.md

The transport used by SC can be influenced by using .config file-based configuration. This information is not documented.

**Comment by danielmarbach** [comment]
The `TransportType` is mentioned. I added an additional note about the assembly needing to be present in the directory.

https://github.com/Particular/docs.particular.net/commit/036a738904bb4f45ef74e1d71b118af137c06820
https://github.com/Particular/docs.particular.net/commit/b24369d5d8fa80ac9a92e8aff0a07f8e75dbceae

if you feel further information like what types of transports are available need to be added fell free to document those. Closing for now
