### ISSUE TITLE
Feedback: 'Queue Length Metric Troubleshooting'

### ISSUE THREAD

**Issue by progorovics** [Particular/docs.particular.net#3832]
Hi,
I'm on NServiceBus 7.0.1
when trying to upgrade to NServiceBus.Metrics.ServiceControl.Msmq 2.0.2 I face the following constraint validation error:
NServiceBus 7.0.1' is not compatible with 'NServiceBus.Metrics.ServiceControl.Msmq 2.0.2 constraint: NServiceBus (>= 6.2.0 && < 7.0.0)'
Will there be an update soon?
regards
Andreas

**Comment by tmasternak** [comment]
@progorovics we are working on it. Please watch for updates when it's available.

**Comment by progorovics** [comment]
Ok thanks will do so.

**Comment by tmasternak** [comment]
Version 3.0.1 is out https://www.nuget.org/packages/NServiceBus.Metrics.ServiceControl/3.0.1
