### ISSUE TITLE
startup-diagnostics deserves its own page (IMO)

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3837]
Feedback for 'Hosting' https://docs.particular.net/nservicebus/hosting/#startup-diagnostics

it is enough content, and i always have trouble finding it. would be nice to have it as a page so is shows in the menu and its own row in the search results.

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/index.md

ping @Particular/nservicebus-maintainers

**Comment by HEskandari** [comment]
@Particular/docs-maintainers discussed and agreed that it can be split into its own page.
