### ISSUE TITLE
Startup projects not working for web samples

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3839]
Feedback for 'Using NServiceBus in an ASP.NET Core WebAPI Application' https://docs.particular.net/samples/web/send-from-aspnetcore-webapi/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/web/send-from-aspnetcore-webapi/sample.md

Downloaded sample does not set the webApplication project as a startup project

![image](https://user-images.githubusercontent.com/122666/41031951-6267c778-69c5-11e8-8df8-784eccea5c6e.png)

**Comment by HEskandari** [comment]
Verified. I've opened an internal issue to sort this out.

**Comment by HEskandari** [comment]
Update: I have a PR in place to upgrade NServiceBus.Mailer. Hoping to convince Simon to review / merge soon (as in a few days)

**Comment by HEskandari** [comment]
Nothing secret, it seems this work is aligned to what .NET Core launch would need to prioritize so I have opened an issue there (currently next in line).

**Comment by SimonCropp** [comment]
please try SetStartupProjects 1.5.2

**Comment by DavidBoike** [comment]
Fixed.

@SimonCropp was there a reason you revved the SetStartupProjects TFM to 4.7.1? I thought it was to support taking on OpenMcdf (which I totally get) but after I finished the work to get the Azure Guest OS to download install net472 if it didn't already have it (the Guest OS only has 4.6) I realized OpenMcdf only requires net40.
