### ISSUE TITLE
Update docs site to allow direct navigation to the ServiceControl content. 

### ISSUE THREAD

**Issue by jdrat2000** [Particular/docs.particular.net#384]
Based on email chain with @gbiellem 

I think the docs site home page needs tweaking to make Service Control articles a bit more discoverable.
I raised this with Simon who said I should take it up with you.

The issues is this - There is no easy  way from the docs home page to get to the ServiceControl index.md

**Comment by SimonCropp** [comment]
@sergioc any progress on this?

**Comment by sergioc** [comment]
@simoncropp can we do together on a zoom call next week?

Sergio

**Comment by SimonCropp** [comment]
@sergioc what do you need from me?

**Comment by sergioc** [comment]
Need to change 3-column layout for SM, SI and SP, to 2-column layout for SM, SI, SP and SC.

![servicecontrol](https://cloud.githubusercontent.com/assets/493451/6001322/cf5540b2-aae8-11e4-926d-ecee2fdebeab.png)

**Comment by SimonCropp** [comment]
@sergioc 

> let me know when you have a preview

You dont need me to do this. The html is here https://github.com/Particular/docs.particular.net/blob/master/home/home.md 

And you can take a local copy of the html and experiment on your local machine, or just edit in-line with your browser, to ensure your changes are correct.

Then you can edit the page directly here https://github.com/Particular/docs.particular.net/edit/master/home/home.md and save or send a pull request if you want someone to review it

**Comment by sergioc** [comment]
@jdrat2000 we will add a section for SC in the docs home. Each capability currently links to 3 "top" articles. 

![2015-02-09 at 19 58](https://cloud.githubusercontent.com/assets/493451/6113260/2aafd41a-b096-11e4-8734-de524d32379a.png)

Can you identify the 3 featured articles to show in docs home for SC?

**Comment by mauroservienti** [comment]
Web are currently missing a "getting started / introduction" article that I think we need and that needs to be in the above list.

**Comment by mauroservienti** [comment]
It is the #278

**Comment by SimonCropp** [comment]
this is done
