### ISSUE TITLE
ServiceControl LogPath default value

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#385]
Default log paths in [setting-custom-log-location.md](http://docs.particular.net/servicecontrol/setting-custom-log-location) and [creating-config-file.md](http://docs.particular.net/servicecontrol/creating-config-file) are inconsistent.
Suggestion: consolidate these documents with a note related to possible LogPath differences.

**Comment by mauroservienti** [comment]
Is this a bug and there is space for improvement or is it ok and leave as is?
