### ISSUE TITLE
Feedback: 'Physical routing with MSMQ'

### ISSUE THREAD

**Issue by emirhosseini** [Particular/docs.particular.net#3856]
Feedback for 'Physical routing with MSMQ' https://docs.particular.net/transports/msmq/routing

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/msmq/routing.md

ping @Particular/msmq-transport-maintainers

Can you update this for NSB Version 7 as well? This doesn't seem to be relevant for V7 as "routing.InstanceMappingFile" does NOT exist.

**Comment by ramonsmits** [comment]
@emirhosseini That API does exist for NSrrviceBus 7, but not as part of the core package. It is part of the new MSMQ package called `NServiceBus.Transport.Msmq`. This package is also mentioned at the top of the documentation.

Please verify if you have referenced this package.
