### ISSUE TITLE
Feedback: 'Configuration'

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#3858]
Feedback for 'Configuration' https://docs.particular.net/transports/azure-service-bus/configuration/

It isn't mentioned what the default transaction mode is. That the default transaction mode uses a TransactionScope that can conflict with any storage actions and how to deal with this.

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/configuration/index.md

ping @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
Should mention it.
Though the default is sends atomic with receive. Transaction scope is not
supported.

>

**Comment by danielmarbach** [comment]
Recently added

> If the above prerequisites are not given (for example when multiple namespaces are used) the transport transaction mode is automatically lowered to TransportTransactionMode.ReceiveOnly.

to the [note](https://docs.particular.net/transports/azure-service-bus/transaction-support). This should be good enough. Closing
