### ISSUE TITLE
Feedback: Connection behavior of SQLP+SQLT combo for transaction modes should be clarified

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#3868]
Connection behavior of SQLP+SQLT combo for transaction modes should be clarified.

* SQLT+SQLP+TransactionScope => Independant connection + MSDTC
* SQLT+SQLP+SendsAtomicWithReceive => Connection builders of SQLP is ignored even it that has a different transaction string
* SQLT+SQLP+SendsAtomicWithReceive+Outbox  => Connection builders of SQLP is used

For the SQLT+SQLP+SendsAtomicWithReceive combo to work correctly the same connection string MUST be used for it to operate correctly otherwise the location where sagas and outbox get created is not clear.

@DavidBoike states that this is an unsupported configuration for SQLP. It is not supported to store queue data on server X and saga data on server Y without using Outbox. 

This is not clear on the following pages:

* SQLP+SQLT sample https://docs.particular.net/samples/sqltransport-sqlpersistence
* SQLP doco: https://docs.particular.net/persistence/sql/

The SQLP doco is missing a section/page about connection sharing/transaction behavior.

**Comment by danielmarbach** [comment]
We have

https://docs.particular.net/persistence/sql/accessing-data

that also states

![image](https://user-images.githubusercontent.com/174258/71256510-3e12a380-2331-11ea-8693-75a759c49de1.png)

plus https://docs.particular.net/samples/sqltransport-sqlpersistence/

![image](https://user-images.githubusercontent.com/174258/71256542-54206400-2331-11ea-91c7-a7943b9f9fed.png)

This seems to be good enough for now. If you think it is required to mention the connection string needs to be the same I'd propose to do a PR to clarify it.
