### ISSUE TITLE
ServicePulse installer fails during upgrade

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#387]
Udi Dahan: This would make an awesome addition to our guidance.

To: particularsoftware@googlegroups.com
Subject: [particularsoftware] Re: ServicePulse installer fails during upgrade
 
Greg,
 
  Thank you for these very detailed instructions!  I followed them and now have all three services updated to the 1.1.0 release of ServicePulse.  Thank you for your help!
 
Adam Jones

On Thursday, August 21, 2014 10:02:47 PM UTC-4, Greg Bielleman wrote:
Hi Adam
 
I managed to replicate the issue you've experienced with ServicePulse, and we'll work on the installer to fix this in a future release.
I've documented below how I got around the install faiiure and also how you can extract the files out of the installer if you don't wish to use the MSI
 
1. Cleanup, Uninstall and Reinstall Method
In my setup I assumed the Dev instance was originally installed via the installer and you've then copied them and registered the additioanl services using the command line switches for ServicePulse.Host.Exe
 
 
So what I did was:
 
- Stop all service pulse services 
- Uninstall servicepulse from control panel
- Delete the folder under the program files(x86) for dev 
- Remove the URLACL for Dev if it still exis
 
            To find URLACLs if there is a URLACL for port 9090  Run this from powershell 
 
            netsh http show urlacl  | Select-String -Pattern Reserved.*:9090    
 
            If there is a URLACL for 9090 remove it -  (assuming it returned http://+:9090/)
 
            e.g. netsh http delete urlacl url=http://+:9090/ 
 
- Checked that no service had the logical name of Particular.ServicePulse
 
            e.g.      Get-Service *pulse* | Select Name
           
            in my case I had just changed the displayname of the dev service 
            Deleted the service with that name 
 
            e.g. SC Delete Particular.ServicePulse  
           
 
- Run the Service Pulse 1.1 install - Specifying  Dev folder as the destination
 
- The install will create a service called Particular.ServicePulse as mentioned above:
 
- Deleted the freshly created service  
 
            e.g. SC.exe Delete Particular.ServicePulse
 
- Put back a service named "Dev" 
           
            From the dev Folder I ran     
             
            ServicePulse.Host.exe --install --serviceName="Particular.ServicePulse.DEV" --displayName="Service Pulse DEV"  --description="Service Pulse for DEV" --url=http://localhost:9090 --serviceControlUrl=http://localhost:33333/api --autostart
 
 
2.  Extract Files from Installer and Replace
 
Make a temp directory and copy the ServicePulse Installer into that directory To Extract files do this:
 
            .\Particular.ServicePulse-1.1.0.exe /extract 
            mkdir ServicePulse
            cd ServicePulse
            C:\Windows\System32\extrac32.exe ..\disk1.cab *.*
 
Now you can stop your existing services and copy over the files in the servicepulse directory over the top of you existing files but don't clobber the app folder,
it contains the config.js which is where the servicecontrol URL is configured
 
Regards
Greg Bielleman

**Comment by mauroservienti** [comment]
Isn't the above a good companion of http://docs.particular.net/platform/installer/offline ?
Given that we have manual installation steps do you think we should also add manual uninstall steps?
For the entire platform?

**Comment by mauroservienti** [comment]
Or we can add a troubleshooting section and split the paragraphs [here](http://docs.particular.net/servicepulse/troubleshooting) into troubleshooting articles adding this one too.

Thoughts?

**Comment by SimonCropp** [comment]
closing this. spoke with @gbiellem and that was a very specific use case and not worth documenting
