### ISSUE TITLE
Feedback: 'Message Throughput Throttling'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3871]
Feedback for 'Message Throughput Throttling' https://docs.particular.net/samples/throttling/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/throttling/sample.md

ping @Particular/nservicebus-maintainers 

This sample does not have a need in registering custom behaviour with a specific ordering within a stage in the pipeline. Therefore, the sample should prefer registration using [`endpointConfiguration.Pipeline.Register()`](https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors#add-a-new-step) that allows to register an instance rather than `RegisterStep`.

In addition to that, the suggested overload allows to pass in arguments into behaviour constructor.

**Comment by andreasohlund** [comment]
PR raised to address this 

https://github.com/Particular/docs.particular.net/pull/3908
