### ISSUE TITLE
Feedback: 'Windows Service Hosting: bootstrapping-nuget'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3879]
Feedback for 'Windows Service Hosting' https://docs.particular.net/nservicebus/hosting/windows-service#bootstrapping-nuget

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/windows-service.md

isnt the bootstrapping-nuget obsolete, and hence this doco should point to https://docs.particular.net/nservicebus/dotnet-templates

**Comment by timbussmann** [comment]
good catch, seems like this page needs some better handling of different versions.

**Comment by weralabaj** [comment]
Fixed in https://github.com/Particular/docs.particular.net/pull/3920
