### ISSUE TITLE
perhaps add link to audit-filter on  'Optimizing ServiceControl for use in different environments'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3881]
Feedback for 'Optimizing ServiceControl for use in different environments' https://docs.particular.net/servicecontrol/servicecontrol-in-practice

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/servicecontrol-in-practice.md

Perhaps link to https://docs.particular.net/nservicebus/audit-filter/ as one option for tweaking message load??

**Comment by WilliamBZA** [comment]
Good suggestion!
