### ISSUE TITLE
Feedback: 'Timeout Manager'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3884]
Feedback for 'Timeout Manager' https://docs.particular.net/nservicebus/messaging/timeout-manager

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/timeout-manager.md

ping @Particular/nservicebus-maintainers

> NServiceBus provides a delayed-delivery implementation for transports that don't support it natively.

How can one see what are those w/o going through all the transports?

**Comment by bording** [comment]
As of the latest versions of all the transports, I think all of them do now, except for MSMQ.

**Comment by SeanFeldman** [comment]
👍
In that case it should be called out.
-- 

*Sean Feldman*
*Solutions Architect, Particular Software*

Email*:*  sean.feldman@particular.net
Web:    www.particular.net
