### ISSUE TITLE
Allow disabling “leave a message”

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3885]
Especially on mobile where it obscures too much of the usable screen area

Also it is noise for most of the long term users of nsb

**Comment by mikeminutillo** [comment]
For reference, this is what it looks like on my device:

![image](https://user-images.githubusercontent.com/124014/42143592-894da22c-7de8-11e8-95d3-073f54b17373.png)

**Comment by SimonCropp** [comment]
here it is on mine. note it also obscures the "scroll to top" button

![image](https://user-images.githubusercontent.com/122666/42143679-c1cc1a00-7df9-11e8-8b4d-0ff117b3a9e6.png)

**Comment by SimonCropp** [comment]
and uses a larger % in landscape

![image](https://user-images.githubusercontent.com/122666/42143728-18d7f77e-7dfa-11e8-90db-a8d922a20796.png)

**Comment by mikeminutillo** [comment]
I spoke to the team. Re-evaluating the chat on mobile is in the backlog but it's not top of the priority list just yet.

**Comment by SimonCropp** [comment]
@mikeminutillo thanks for following up on this. can u let the team know i found a workaround that is a satisfactory fix for me. i added `http://cdn.livechatinc.com/` to the list of blocked sites in 1blocker https://1blocker.com/ (although any other blocker would also work).

so feel free to ignore, or put in a proper fix, at you leisure. for now i will close this since i have my screen real estate back.

**Comment by mikeminutillo** [comment]
Thanks @SimonCropp

**Comment by DavidBoike** [comment]
@SimonCropp FYI it's now hidden with a CSS media query < 768px.
