### ISSUE TITLE
Feedback: 'Azure Service Bus .NET Standard Transport'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3906]
Feedback for 'Azure Service Bus .NET Standard Transport' https://docs.particular.net/transports/azure-service-bus-netstandard/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus-netstandard/index.md

ping @Particular/azure-maintainers

Add a link to sample: https://docs.particular.net/samples/azure-service-bus-netstandard/send-reply/

**Comment by danielmarbach** [comment]
The samples are present

![image](https://user-images.githubusercontent.com/174258/71256659-b6796480-2331-11ea-801c-516e1cc52b72.png)

https://docs.particular.net/transports/azure-service-bus/

Closing.
