### ISSUE TITLE
"Scheduling with NServiceBus" doesn't really give any guidance on where that code should go in a project

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#392]
Based on feedback from a user in the mailing list:
> I saw that article, and it shows how to schedule a task, but it doesn't really give any guidance on where that code should go in a project, how it should be called, or anything else like that.

User is referring to http://docs.particular.net/nservicebus/scheduling-with-nservicebus

**Comment by SimonCropp** [comment]
i am closing this one. there is really no definitive advice we can give out to use on where to put this code. they can do it from a handler,a saga, bus startup, or from some timer. this is a non trivial piece of advice that could be applicable to most of our API surface area and cannot be answered without understanding the business/use case.

**Comment by mauroservienti** [comment]
I agree that there isn't a "this is the correct place", but can't we simply add some samples? if a user has the concern expressed at the beginning of the topic I'd say that the article is not clear enough.
