### ISSUE TITLE
Metrics documentation is confusing and hard to navigate

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#3927]
We don't distinguish well between NServiceBus.Metrics, ServiceControl metrics, etc. For example, this page doesn't mention which Nuget package it describes https://docs.particular.net/monitoring/metrics/definitions, and this https://docs.particular.net/monitoring/metrics/install-plugin surprisingly is about sending metrics to service control with another nuget package.

I think we need to review documentation around metrics and ensure it's easy to understand and use by people not familiar with the topic. I can help with that.

ping @Particular/metrics-maintainers

**Comment by tmasternak** [comment]
@weralabaj just some context on the current state. The documents that you linked are under `Monitoring`->`Perfromance Metrics`. As a result the articles are focused on the setting up performance monitoring for your solution. So it's not that much about packages but more about scenarios the users follow e.g. install plugin to send data to monitoring instance.

That's the current context I wanted to share before the discussion happens.

**Comment by danielmarbach** [comment]
We recently edited the pages as well as the names of the links in the menu structure. Closing this for now.
