### ISSUE TITLE
Feedback: 'Outbox with NHibernate persistence'

### ISSUE THREAD

**Issue by danielp37** [Particular/docs.particular.net#3928]
Feedback for 'Outbox with NHibernate persistence' https://docs.particular.net/persistence/nhibernate/outbox

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/nhibernate/outbox.md

ping @Particular/nhibernate-persistence-maintainers

The proper format string for -1 millisecond is "-00:00:00.001" What you have throws an argument out of range exception.

**Comment by weralabaj** [comment]
@danielp37 thanks for catching this!

@ramonsmits Since you're the author of that part, can you please have a look and update?

**Comment by ramonsmits** [comment]
Thanks for spotting @danielp37 , I've corrected the value.
