### ISSUE TITLE
Feedback: 'dotnet new Templates'

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#3933]
Feedback for 'dotnet new Templates' https://docs.particular.net/nservicebus/dotnet-templates

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/dotnet-templates.md

ping @Particular/host-maintainers 

IMO It'd be better to move https://docs.particular.net/nservicebus/dotnet-templates#dotnet-new-information section to the top of the page. People who know what they're looking for dont' need it and those that are not sure what they're looking for probably would stop reading before getting to that section.

**Comment by mauroservienti** [comment]
Agreed @weralabaj, raised #3934 to fix this. Please review.
