### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Getting started'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3939]
Feedback for 'NServiceBus Step-by-step: Getting started' https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md

I do not feel comfortable (yet) to write PRs, so please allow me to just point out a few things:

1. The section **[Configure an endpoint](https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/#exercise-configure-an-endpoint)** (or itsC# 7.0) alternative should include the definitions for **`using`** statements - or at least warn the user to accept the "offer" from the "bulb".

2. The highlighted note 

![image](https://user-images.githubusercontent.com/2712405/43558821-5822fb3a-95d9-11e8-8c8c-70c36038b851.png)

begs for more explanations as at this initial level one would expect that the novice user (I am a good example, regardless of my actual experience) would be confused with "capturing and restoring the SynchronizationContext" .

**Comment by adamralph** [comment]
@adriatic thanks for the feedback!

Regarding the second point, I agree that this leaves the reader stranded if they don't know about the nuances of `ConfigureAwait(false)`. The note should link to something which explains it. I've raised #3941 to address this problem.

> The section Configure an endpoint (or itsC# 7.0) alternative should include the definitions for using statements - or at least warn the user to accept the "offer" from the "bulb".

I agree that it's not immedatiely obvious that the dropdown should be used instead of highlighting the code manually and copying it. Perhaps we should consider renaming the dropdown from `Actions` to something like `Copy/Edit`? @Particular/docs-maintainers thoughts?

**Comment by SzymonPobiega** [comment]
👍 for `Copy/Edit`

**Comment by DavidBoike** [comment]
Thanks @adriatic!

1. Hopefully you saw @adamralph's note about ConfigureAwait above.
1. I added a blue INFO box in https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/#exercise-configure-an-endpoint right after the first code snippet where a using is required (for `Task`).
1. We renamed the "Actions" dropdown on snippets to "Copy/Edit" for clarity about what's actually IN there.

**Comment by adriatic** [comment]
Wow - you guys are not joking. The changes you made are terrific (from my viewpoint, which is till mostly the viewpoint of a newbied, regardless of the fact that million years ago, I briefly worked at the messaging poineer (Fiorano). 

I am mentioning this to point out how my lack of deeper understanding of your product might be a good asset in the process of "vetting" your docs - which are **genuinely terrific**.

**Comment by adamralph** [comment]
@adriatic thank you for your kind words. It is indeed valuable for us to have feedback from users with all levels of experience. It helps us keep the docs useful for both newcomers and those have used our products before. 👍
