### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Sending a command'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3942]
Feedback for 'NServiceBus Step-by-step: Sending a command' https://docs.particular.net/tutorials/nservicebus-step-by-step/2-sending-a-command/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md

Quote from the section **[What is a message](https://docs.particular.net/tutorials/nservicebus-step-by-step/2-sending-a-command/#what-is-a-message)**:

> The marker interface has no implementation, but lets NServiceBus know that the class is a command so that it can build up some metadata about the message type when the endpoint starts up

From the standpoint of the purist the "marker interface" is really just an interface, and as such it does not have an interface. The above quote hints that the "marker" interface is some special kind of interface.

**Comment by SzymonPobiega** [comment]
@adriatic thanks. I've created a PR to address this https://github.com/Particular/docs.particular.net/pull/3944

**Comment by adamralph** [comment]
Thanks again for the feedback @adriatic - the document has been changed.

**Comment by adriatic** [comment]
Adam, I apologize for the typo in my sentence  

> From the standpoint of the purist the "marker interface" is really just an interface, and as such it does not have an ~~interface~~ **implementation**.

This is almost a Freudian slip projected into a geek's context 😏
