### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Sending a command'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3943]
Feedback for 'NServiceBus Step-by-step: Sending a command' https://docs.particular.net/tutorials/nservicebus-step-by-step/2-sending-a-command/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md. **[Processing messages](https://docs.particular.net/tutorials/nservicebus-step-by-step/2-sending-a-command/#processing-messages)**

Quote:
> When NServiceBus starts up, it will find all of these message handler classes and automatically wire them up, so that they will be invoked when messages arrive. There's no special setup or configuration needed.

This is not pointed out strongly enough - as such feature is seldom available; developer is most often required to register handlers, so I would expect that a newbie would look around where to do such registration.

___Out of curiosity: how is this automatic registration achieved? By searching for classes that inherit from `IHandleMessages<type>.` interface?___

**Comment by DavidBoike** [comment]
@adriatic I think this new commit https://github.com/Particular/docs.particular.net/commit/3704519bce68f434df8268079d6f2d7dd0b04f65#diff-7cded419a30950d86d2cb9e9fbd7120b will both fix the issue and answer most of your question.

The rest of the answer is the [Type.IsAssignableFrom method](https://msdn.microsoft.com/en-us/library/system.type.isassignablefrom(v=vs.110).aspx).
