### ISSUE TITLE
Headers documentation for failed messages

### ISSUE THREAD

**Issue by staylr** [Particular/docs.particular.net#3945]
In [https://docs.particular.net/nservicebus/messaging/headers](https://docs.particular.net/nservicebus/messaging/headers), the "Example Error Headers" section contains two copies of the incoming message headers. Only the documentation for NServiceBus 5.x contains the correct error headers.

**Comment by danielmarbach** [comment]
I did some research and unfortunately the tests that where used to generate those examples where never really capturing the correct output. They used an extension mechanism that captures the exception messages plus the headers of the original message and not the actual headers of the copy of the message that is sent to the error queue. I see if I can fix those and then create a correct example
