### ISSUE TITLE
Add a document to describe HA using VM and VMotion

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#395]
Maybe have a lab to show the setup?

**Comment by mauroservienti** [comment]
We just discussed that :-) to me it is a +1.

**Comment by pablocastilla** [comment]
+1+1+1 !!! :)

**Comment by mauroservienti** [comment]
#369 is richer in description and this one seems to be a duplicate, I'll close this one. Re-open if needed.
