### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Multiple endpoints'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3951]
The point of this issue is simply: **Make sure to set the Language version to C# latest minor version**. As the project Sales was added at a later time, it would be good to make this specific warning in the tutorial text at **[this](https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/#exercise-creating-a-new-endpoint)** location.

Please check the enumeration of 5 attributes on the "Build" form screenshot below to determine whether any of them needs to be set by the reader of this tutorial.

***

Feedback for 'NServiceBus Step-by-step: Multiple endpoints' https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md

When adding the Sales project after the ClientUI and Messages exists and the solution works as it should, the Properties of the Sales project are not the same as the properties of the identical Sales project that is the part of the **[Quick Start](https://docs.particular.net/tutorials/quickstart/)** tutorial that contains all projects (Billing, ClientUI, Messages and Sales)) already. Specifically, I had to add the following 5 items:

![image](https://user-images.githubusercontent.com/2712405/43677610-d37c515a-97d2-11e8-805f-43492863c4a3.png)

Even after making these changes, I cannot build this sample once the Sales project was added - I keep getting this error

![image](https://user-images.githubusercontent.com/2712405/43677654-8e7a3f08-97d3-11e8-8a80-9fe1415c447c.png)

where the CSC file is at `StepByStep/Sales/CSC`  (do not see any such file or folder??)

It ought to be that I am missing some other setting - as the source for the project Sales, file `Program.cs` is what it should be
```
using System;
using System.Threading.Tasks;
using NServiceBus;



namespace Sales
{
    class Program
    {
        static async Task Main()
        {
            Console.Title = "Sales";

            var endpointConfiguration = new EndpointConfiguration("Sales");

            endpointConfiguration.UseTransport<LearningTransport>();

            var endpointInstance = await Endpoint.Start(endpointConfiguration)
                .ConfigureAwait(false);

            Console.WriteLine("Press Enter to exit.");
            Console.ReadLine();

            await endpointInstance.Stop()
                .ConfigureAwait(false);
        }
    }
}
```

I stored this whole project at https://github.com/adriatic/NSB-tests/tree/master/StepByStep - if you want to see things I did not mention above.

**Comment by mikeminutillo** [comment]
@adriatic thank you for this detailed feedback. 

To resolve the last error you need to click the Advanced... button at the bottom of the Build tab and change the Language version drop down.

![minor-version](https://user-images.githubusercontent.com/124014/43695798-53dcd27a-996d-11e8-94f9-bb28e82f17ec.png)

**Comment by adriatic** [comment]
Hi, MIke

Please check my **[first paragraph above](https://github.com/Particular/docs.particular.net/issues/3951#issue-347625235)** where I am suggesting to add this advice:

> click the Advanced... button at the bottom of the Build tab and change the Language version drop down.>

to the tutorial document :-)

**Comment by mauroservienti** [comment]
Thanks @adriatic, I raised https://github.com/Particular/docs.particular.net/pull/3959 to fix this.

**Comment by mauroservienti** [comment]
@adriatic it's fixed, thanks for the feedback.

**Comment by adriatic** [comment]
I just love your view where no issue is too small and your efficiency in addressing such issues
