### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Publishing events'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3954]
Feedback for 'NServiceBus Step-by-step: Publishing events' https://docs.particular.net/tutorials/nservicebus-step-by-step/4-publishing-events/

Location in GitHub: https://docs.particular.net/tutorials/nservicebus-step-by-step/4-publishing-events/#exercise-create-another-subscriber

My comment to the section:
> This is also a good opportunity to check your understanding. If you can complete these steps without looking back at previous steps or previous lessons, you can be sure you have a good understanding of everything we've covered so far. (Don't worry, you can always check your work against the solution.)

In order to be fair to the "newbie", I would mention here the **`context.Publish`** API that is needed in order to do "In Billing, publish the OrderBilled event at the end of the OrderPlacedHandler":

```c#
public class OrderPlacedHandler :
    IHandleMessages<OrderPlaced>
{
    static ILog log = LogManager.GetLogger<OrderPlacedHandler>();

    public Task Handle(OrderPlaced message, IMessageHandlerContext context)
    {
        log.Info($"Received OrderPlaced, OrderId = {message.OrderId} - Charging credit card...");

        var orderBilled = new OrderBilled
        {
            OrderId = message.OrderId
        };

        return context.Publish(orderBilled);
    }
}
```

This API was never mentioned in any of the samples so far.

**Comment by adamralph** [comment]
@adriatic the API is introduced in the previous section ["Publish an event"](https://docs.particular.net/tutorials/nservicebus-step-by-step/4-publishing-events/#exercise-publish-an-event). I would expect the reader to be familiar with it by the time they get to this section. Thoughts?

**Comment by adriatic** [comment]
@adamralph - you are correct, this API is indeed shown here: https://docs.particular.net/tutorials/nservicebus-step-by-step/4-publishing-events/#exercise-publish-an-event.

Sorry for the false alarm 😢 - I am closing this issue.
