### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Retrying errors'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3955]
Feedback for 'NServiceBus Step-by-step: Retrying errors' https://docs.particular.net/tutorials/nservicebus-step-by-step/5-retrying-errors/

Location in GitHub: https://docs.particular.net/tutorials/nservicebus-step-by-step/5-retrying-errors/#causes-of-errors

> In systems programming, where connectivity is a major concern, there are generally three broad categories of exceptions:

I would remove the word "systems" in the above sentence. It is mostly used to address the operating systems components programming - this is not the case here.

**Comment by adamralph** [comment]
Thanks @adriatic. I've raised #3958 to address this.

**Comment by adamralph** [comment]
The change has been published. Thanks again @adriatic.
