### ISSUE TITLE
Feedback: 'Installers'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3956]
Feedback for 'Installers' https://docs.particular.net/nservicebus/operations/installers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/installers.md

ping @Particular/nservicebus-maintainers

The sentence 

> Consider running the installers only during the initial setup using elevated permissions

surprised me as it is seldom the case that the application can change permission levels. Is the user advised to make platform dependent system service calls, or does NServiceBus offer a platform independent abstraction for that? Consequently, a reference to some text explaining how this is being done would be helpful.

**Comment by timbussmann** [comment]
Hey @adriatic 

>  or does NServiceBus offer a platform independent abstraction for that?

Unfortunately, NServiceBus currently doesn't provide any abstractions for that and it's the user's responsibility to define an appropriate way in order setup required resources. Other approaches we see working well so far:
* Starting the endpoint manually as administrator/elevated user to run the installers before installing it as a service.
* Creating required resources (e.g. queues) manually upfront and not using the installers at all. SQL Persistence for example provides you with all required scripts to run, independently whether you want to execute them via installer or via scripts.

Given the different resources (transports, persistence, operating systems, ...) which can be combined, it's quite difficult to come up with a reasonable way to make the installation experience working better out of the box, but it's definitely a topic we are very aware of.

With that in mind, do you have any suggestions regarding a better documentation about the installers? Would it help if the options as described in this comment would be listed somehow?

**Comment by adriatic** [comment]
Hello @timbussmann 
ping @adamralph 

While I did not expect that NServiceBus would abstract the topic we are discussing here, I am very happy with the fact that you responded to my question and even more with the content of your response:

> Given the different resources (transports, persistence, operating systems, ...) which can be combined, it's quite difficult to come up with a reasonable way to make the installation experience working better out of the box, but it's definitely a topic we are very aware of.

It would certainly be great to add the two bullet points you mention above as additional information provided in the document https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/installers.md

In addition, there ought to be code samples (for as many different cases OS/Transport/... you can afford).

By the way, it seems that the existing section on **[Running installers](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/installers.md#running-installers) is ill-formatted:

![image](https://user-images.githubusercontent.com/2712405/43961649-9046ad80-9c83-11e8-9681-2b712691558d.png)

**Comment by adriatic** [comment]
The **[above comments](https://github.com/Particular/docs.particular.net/issue_comments#issuecomment-412089812)** I just wrote made me realize to ask the question:

Would Particular me interested in tutorials and related docs, created as "community contribution"? If so, I would offer the "integration" with universal authentication & authorization platform, starting with **[Auth0](https://auth0.com/)**, which I used a lot and where I am working as a "guest author" already. 

If this idea resonates with the team, I could extend it to include all other Identity Management PaaS solutions.

**Comment by timbussmann** [comment]
thanks for your feedback @adriatic , I'll try to add the described options somehow to this doco page.

I'm not sure I understand your last comments though. We definitely accept and appreciate PRs to our doco from the community. That all works via this GitHub repository and does not need any further authentication. Our [doco readme](https://github.com/Particular/docs.particular.net/blob/master/README.md) should contain all the information required in case you're interested.

> y the way, it seems that the existing section on Running installers is ill-formatted:

which part do you think is ill-formatted on the linked page?

**Comment by adriatic** [comment]
Check the section **[above](https://github.com/Particular/docs.particular.net/issues/3956#issuecomment-412089812)** - the image embedded in the text (created the image solely for the purpose of identifying the section of the text that is ill-formatted in my opinion.

**Comment by timbussmann** [comment]
@adriatic that's how the raw doco content is shown in guthub. Our doco engine is built on top of reading markdown files and provdes some additional capabilities like partial includes, partial includes and snippets. Those cannot be rendered correctly by githubs markdown rendering but they will be compiles into valid html and then shown on the doco page. Do you see any formatting issues on the actual doco page?

**Comment by timbussmann** [comment]
@adriatic I might have misread your comment:
> If so, I would offer the "integration" with universal authentication & authorization platform, starting with Auth0, which I used a lot and where I am working as a "guest author" already.

in case you'd like to write a doco article about integrating NServiceBus with Auth0, that would certainly be an interesting topic. However, I'd suggest to write a blog post about this topic as a first step. We would very happily share this blog post via our community channels. I think a blog post would be a good start in this case as doco pages and samples require very active maintenance which might not be necessary for more general tutorials. Thoughts on that?

**Comment by adriatic** [comment]
### My comment to **[your text above](https://github.com/Particular/docs.particular.net/issues/3956#issuecomment-412427568)**, rendered as a screenshot to hopefully be more clear:

![image](https://user-images.githubusercontent.com/2712405/44038572-0e72ddba-9ee5-11e8-8965-56f4cc651463.png)

I am trying to suggest that the whole section I **[initially supplied as a screenshot](https://github.com/Particular/docs.particular.net/issues/3956#issuecomment-412089812)**, looks more like the notes, author wrote for himself, to remember how to flesh out this document, by sharing some code snippets than the document to be read by your customer.

If this does not make sense, it is likely that I have a brain-defect and you should ignore this, since my intent was to help -- not to waste your time trying to understand something not explained sufficiently well.

**Comment by danielmarbach** [comment]
@adriatic when you see

`partial: keyword` or `snippet: keyword`

then you are probably looking at the documentation in our github repository. Behind the scenes, we have a custom rendering engine that collects information from additional markdown files and snippet solutions and renders them on the website under https://docs.particular.net 

So the screenshot you made from the markdown looks in reality on the website like

![image](https://user-images.githubusercontent.com/174258/44039501-7e51664a-9f19-11e8-80f2-d534da37327e.png)


At least on my machine. @timbussmann was trying to understand whether you see some kind of weird rendering issue on the actual doc site under https://docs.particular.net/nservicebus/operations/installers

**Comment by adriatic** [comment]
### My comment to the idea of writing the document on using Auth0 services with NServiceBus:

I understand the complexity of your document processing setup (I dealt with several variants of such system). So, I completely agree with your proposal to write that document as a blog.

I have "met" a few members of your team (Adam Ralph and David Boike), so could you tell me who would be my best contact for making sure that my blog hits the Particular's "sweet spot"?

Should I create the **`Particular - Auth0`** GitHub issue to manage this?

Ping @adamralph @DavidBoike

**Comment by adriatic** [comment]
@danielmarbach Thank you for the complete explanation - I am happy to see that all is fine. I a not sure why did I switch from your exposed docs to their "raw" version at GitHub; clearly I was not aware that I made that switch, most likely as a consequence of creating a few issues for your docs.

**Comment by timbussmann** [comment]
I'm glad that Daniel's explanation helped to clear things up 👍 (this can happen if you use the edit buttons on our doc site, which will point you towards these "raw" markdown files).

If you'd like to discuss a blog post idea, I'm sure that @DavidBoike or @adamralph would both the excellent contacts to talk to.

**Comment by adamralph** [comment]
I've raised #3980 in attempt to address this.

**Comment by adamralph** [comment]
This was addressed by #3980. Thanks again @adriatic for this feedback!
