### ISSUE TITLE
Feedback: 'Monitoring instances'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3964]
Feedback for 'Monitoring instances' https://docs.particular.net/servicecontrol/monitoring-instances/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/monitoring-instances/index.md

ping @Particular/servicecontrol-maintainers 

Documentation doesn't mention starting from what version of SC Monitoring functionality is available.
Please add this information to assist customers that are on the older versions and trying to get monitoring enabled following our doco. Thanks.

**Comment by WilliamBZA** [comment]
Also pinging @Particular/monitoring-maintainers

**Comment by boblangley** [comment]
I took a stab at in in #3970
