### ISSUE TITLE
Feedback: 'NServiceBus Host'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3966]
Feedback for 'NServiceBus Host' https://docs.particular.net/nservicebus/hosting/nservicebus-host/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/index.md

ping @Particular/host-maintainers 

When creating a project from a scratch targetting Host v7 and later, it doesn't update Project's debug settings to set the NServiceBus.Host.exe as a debug startup application. Would be nice if documentation could mention that. Even an entry such as "to debug in VS, update project Debug settings pointing to NServiceBus.Host.exe in the output folder. E.g.: $(solutiondir)\<project-name>\bin\Debug\<TFM>\NServiceBus.Host.exe".

**Comment by mauroservienti** [comment]
Thanks @SeanFeldman, I’ll have a look later today.

**Comment by mauroservienti** [comment]
@Particular/host-maintainers in doco we state:

> To use the host, create a new C# class library and reference the NServiceBus.Host NuGet package. _The package will automatically create a sample endpoint configuration and will set the NServiceBus.Host.exe as the endpoint's startup project._

(_emphasis is mine_)

It doesn't work. I suppose it's related to the fact that on latest nuget versions powershell scripts were not anymore supported. Shall we drop the above sentence or rephrase to make it clear that is VS2015 only?

We should also document how to manually create the endpoint skeleton and set the `NServiceBus.Host.exe` as the startup executable.

**Comment by bording** [comment]
This is one of the reasons that we're deprecating the hosts. We should be pointing people to the Windows Service template: https://docs.particular.net/nservicebus/dotnet-templates#nservicebus-windows-service

**Comment by seanfarmar** [comment]
So what do we do here? add a note for v7?

**Comment by mauroservienti** [comment]
that page for VS 2017 is completely wrong, since we cannot add partials based on VS version, I suggest we add a note at the beginning stating what's the VS 2017 behavior and pointing users to the link @bording  mentioned

**Comment by danielmarbach** [comment]
It looks like with latest visual studio not even the class implementing IConfigureThisEndpoint is created anymore. Given that the host is deprecated I think the most reasonable thing to do would be:

- Remove "To use the host, create a new C# class library and reference the NServiceBus.Host NuGet package. The package will automatically create a sample endpoint configuration and will set the NServiceBus.Host.exe as the endpoint's startup project."
- Add a snippet for a sample configuration
- Explain how to setup the start project manually

or leave as is

Any thoughts @bording @mauroservienti @SeanFeldman ?

Happy to do the changes if needed. Just wanted to double check the direction.

**Comment by SeanFeldman** [comment]
If it's breaking so badly, it cannot be as-is. What @danielmarbach suggested makes sense. I also wish we'd have the deprecation note would be stronger and point out NServiceBus version. The host version is not helping those that look at the host and potentially consider it.

**Comment by mauroservienti** [comment]
I agree with the proposed changes. And also with:

> I also wish we'd have the deprecation note would be stronger and point out NServiceBus version. The host version is not helping those that look at the host and potentially consider it.

**Comment by danielmarbach** [comment]
@mauroservienti @SeanFeldman I did create https://github.com/Particular/docs.particular.net/pull/4667. I hope this is good enough for now. Would appreciate some feedback on the wording so that we can wrap this up
