### ISSUE TITLE
Feedback: 'SQL Persistence saga concurrency'

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#3968]
Feedback for 'SQL Persistence saga concurrency' https://docs.particular.net/persistence/sql/saga-concurrency

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/sql/saga-concurrency.md

Reading the update lock part

>However, to avoid excessive conflicts for highly congested sagas, the persister uses pessimistic concurrency for querying and updating saga information. The pessimistic concurrency is implemented using a SELECT ... FOR UPDATE construct or its dialect-specific equivalent.

seems to conflict with the blue box that states

>This means that the relevant Handle method on the saga will be invoked, even though the message might be later rolled back. Hence it is important to ensure not to perform any work in saga handlers that can't roll back together with the message. This also means that should there be high levels of concurrency there will be N-1 rollbacks where N is the number of concurrent messages. This can cause throughput issues and might require design changes.

This seems to conflict given that `FOR UPDATE` will wait until the upgrade lock can be taken? (Or am I missing something?)

ping @Particular/sqlpersistence-maintainers

**Comment by SzymonPobiega** [comment]
Handled in https://github.com/Particular/docs.particular.net/pull/3969
