### ISSUE TITLE
Feedback: 'Unit Testing NServiceBus'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3971]
document all the testable type 

![image](https://user-images.githubusercontent.com/122666/44011239-ccde6f70-9efa-11e8-9419-1ee619a6356c.png)

**Comment by dbelcham** [comment]
@SimonCropp what kind of documentation are you thinking is required for these types?

**Comment by andreasohlund** [comment]
For the `TestableXYZContext` we could add a generic section to https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors that talks about "Testing your custom behaviors"?

Not 100% sure what the TestableLoggerFactory is meant to provide tho

**Comment by SimonCropp** [comment]
@dbelcham 

> what kind of documentation are you thinking is required for these types?

documentation of their existence and usage. 

@andreasohlund 

> Not 100% sure what the TestableLoggerFactory is meant to provide tho

well i am hoping it will be the answer to this https://github.com/NServiceBusExtensions/NServiceBus.Serilog/issues/18#issuecomment-412000989

**Comment by SimonCropp** [comment]
as far as i can tell, of the above types, only `TestableMessageHandlerContext`, `TestableOutgoingLogicalMessageContext` are documented

**Comment by andreasohlund** [comment]
>as far as i can tell, of the above types, only TestableMessageHandlerContext, TestableOutgoingLogicalMessageContext are documented

If we had the section mentioned in https://github.com/Particular/docs.particular.net/issues/3971#issuecomment-412543323 would you say its enough to have a generic "and all the varous behaviour contexts have a `Testable`  counterpart"?

**Comment by andreasohlund** [comment]
>If all of them were used the same way, i would say yes. 

All the context one are, will work up a PR for those

> take the logging for example, its use would be completely different from the one listed in /nservicebus/testing/.

Agreed, lets do that as a separate PR as well.

>BTW where are the tests for these fakes to ensure they work as expected?

@timbussmann do you remember if we made a conscious decision to skip tests for this?

**Comment by andreasohlund** [comment]
Raised https://github.com/Particular/docs.particular.net/pull/3974 to cover the testable pipeline contexts. Thoughts on this approach @SimonCropp ?

**Comment by andreasohlund** [comment]
There is also the `TestableEndpointInstance` that needs to be documented. I'll go through the list and see if I can find more

**Comment by SimonCropp** [comment]
@andreasohlund IMO i dont think #3974 is sufficient as it wont be discoverable. eg searches like `"IIncomingLogicalMessageContext" unit testing` and `"IIncomingLogicalMessageContext" mocking` will not find it

**Comment by SimonCropp** [comment]
i would prefer to see "how to test feature x" co-located with "how to use feature x". so eg the snippets for testing behaviours would be located here https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors or on a co-located page

**Comment by andreasohlund** [comment]
>as it wont be discoverable. eg searches like "IIncomingLogicalMessageContext" unit testing and "IIncomingLogicalMessageContext" mocking

True that, will see what I can do

> would prefer to see "how to test feature x" co-located with "how to use feature x"

I like that. That would pretty much make https://docs.particular.net/nservicebus/testing/ go away? or just be a short "The NServiceBus.Testing nuget contains unit testing support for NServiceBus" kind of page.

@Particular/nservicebus-maintainers thoughts?

**Comment by timbussmann** [comment]
the testable message session is tested here: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core.Tests/Fakes/TestableMessageHandlerContextTests.cs

The other testable contexts are not tested as their implementation is quite trivial (and the effort to patch the testing package is low).

I think some doco on how to unit test a behavior using a testable context should be sufficient, the same principle then applies to all the other contexts. The testable loggingfactory could use dedicated docs.

**Comment by andreasohlund** [comment]
>would prefer to see "how to test feature x" co-located with "how to use feature x"

@Particular/nservicebus-maintainers  Thoughts on this?

It would mean that:

* https://docs.particular.net/nservicebus/testing/#testing-a-handler moves to https://docs.particular.net/nservicebus/handlers

* https://docs.particular.net/nservicebus/testing/#testing-a-saga moves to https://docs.particular.net/nservicebus/sagas/

* https://docs.particular.net/nservicebus/testing/#testing-a-behavior moves to https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors

We would leave the /testing page to just talk about the package and that it's used for "Unit testing NServiceBus"

**Comment by dbelcham** [comment]
I think we would want this pattern to be consistent across the entire documentation if we were to implement it. A "How to test" section on Core pages, Transport pages, Persistence, etc. Wouldn't this be a bigger decision than just Core maintainers then?

**Comment by timbussmann** [comment]
I'm voting to keep the unit testing pages dedicated pages. This keeps doco pages in smaller sizes and more focused. Maybe add links between the related pages?

**Comment by andreasohlund** [comment]
>I'm voting to keep the unit testing pages dedicated pages.

Are you saying to not collocate testing doco with various features but rather have them as separate pages under /testing?  (and link to them)

Ie https://docs.particular.net/nservicebus/testing/ would be come the index page and we would move the sections on the current page to new sub pages?

**Comment by timbussmann** [comment]
@andreasohlund yeah I would prefer that I think

**Comment by timbussmann** [comment]
imo yes.

**Comment by andreasohlund** [comment]
PR to document the `TestableLoggingFactory` - https://github.com/Particular/docs.particular.net/pull/4016

**Comment by andreasohlund** [comment]
PR to document the `TestableMessageSession` - https://github.com/Particular/docs.particular.net/pull/4021

**Comment by andreasohlund** [comment]
@SimonCropp given https://github.com/Particular/docs.particular.net/pull/4021 I think we have all action points raised here covered?

**Comment by SimonCropp** [comment]
Lgtm. Thanks

**Comment by andreasohlund** [comment]
All PR's merged

**Comment by udidahan** [comment]
What would be so bad to ALSO have a link/include of "how to test" in the docs about the thing itself?

**Comment by udidahan** [comment]
OK, but what about the other places you mentioned?

https://docs.particular.net/nservicebus/handlers
https://docs.particular.net/nservicebus/sagas/
https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors

**Comment by andreasohlund** [comment]
Good point, I will go through all testing docs we have and make sure we
link to it from relevant pages.

WIP PR: https://github.com/Particular/docs.particular.net/pull/4038
