### ISSUE TITLE
Create new docu for licensing under continaers and hosts

### ISSUE THREAD

**Issue by willie-levy** [Particular/docs.particular.net#3975]
Currently we are getting more and more questions regarding how to license when deploying with containers.
We have this internal doc: https://github.com/Particular/CustomerSuccess/blob/master/Licensing/containers.md
It would be helpful to have a public docu we can share with customers.
cc @ryansteinparticular @codyjparticular @KimberlyA

**Comment by KimberlyA** [comment]
@willie-levy Going over github notifications from when I was away and came across this - who is responsible for this repo?

**Comment by willie-levy** [comment]
@kbaley - If we are interested in a new docu to be created, is this the correct place to open the issue?

**Comment by kbaley** [comment]
Moved to Customer Success
