### ISSUE TITLE
Feedback: 'Asp.NET Core Dependency Injection Integration'

### ISSUE THREAD

**Issue by twenzel** [Particular/docs.particular.net#3992]
Feedback for 'Asp.NET Core Dependency Injection Integration' https://docs.particular.net/samples/dependency-injection/aspnetcore/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/dependency-injection/aspnetcore/sample.md

ping @Particular/nservicebus-maintainers

I want to promote my [NServiceBus.MSDependencyInjection](https://github.com/twenzel/NServiceBus.MSDependencyInjection) extension for native ASP.Net Core DI support. Maybe you can give it a try.

**Comment by mauroservienti** [comment]
Ping @Particular/container-maintainers 
@Particular/docs-maintainers what’s the process to add a community package to the docs website?

**Comment by DavidBoike** [comment]
I believe this was addressed/fixed by https://github.com/Particular/docs.particular.net/pull/3997
