### ISSUE TITLE
Feedback: 'Stack Trace Cleaning'

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#4004]
Feedback for 'Stack Trace Cleaning' https://docs.particular.net/samples/logging/stack-trace-cleaning/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/logging/stack-trace-cleaning/sample.md

ping @Particular/docs-maintainers @Particular/nservicebus-maintainers 

.NET Core 2.1 includes [a fix to the bloated async stack traces](https://github.com/dotnet/corefx/issues/24627) which makes this article less on-point. What should we do about that?

**Comment by timbussmann** [comment]
Sounds like we should add a note that .NET Core 2.1 already handles this and this sample is only intended when targeting the .NET Framework or .NET Core < 2.1 ?
