### ISSUE TITLE
Feedback: 'Message Headers'

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#4008]
Feedback for 'Message Headers' https://docs.particular.net/nservicebus/messaging/headers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/headers.md

ping @welshdave Particular/nservicebus-maintainers

NServiceBus.FLRetries was removed in v6, we need to adjust the docs

**Comment by danielmarbach** [comment]
Dock seems to be up to date. Closing
