### ISSUE TITLE
Feedback: 'Installing Silently'

### ISSUE THREAD

**Issue by OffColour** [Particular/docs.particular.net#4024]
Feedback for 'Installing Silently' https://docs.particular.net/servicecontrol/installation-silent

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/installation-silent.md

Documentation still refers to using an unattend file which has been deprecated.
Is there still a method of installing servicecontrol and monitoring instances during setup?

**Comment by mauroservienti** [comment]
@Particular/servicecontrol-maintainers @Particular/monitoring-maintainers please advice.

**Comment by WilliamBZA** [comment]
Thanks @OffColour.

You can still install service control via powershell commandlet, it's just the unattended install that accepts a file that is no longer supported.

As an example:

`New-ServiceControlInstance -Name ServiceControl -InstallPath c:/servicecontrol -DBPath c:/temp/db -LogPath c:/temp/logs -DatabaseMaintenancePort 33334 -Port 33333 -ErrorQueue error -AuditQueue audit -ErrorLogQueue errorlog -AuditLogQueue auditlog -Transport SQLServer -ForwardAuditMessages:$false -ForwardErrorMessages:$false -ConnectionString 'Data Source=.; Database=LoadTest; User Id=sa; Password=asdf1234!;' -AuditRetentionPeriod 01:00:00 -HostName * -ErrorRetentionPeriod 10:00:00:00;`

**Comment by OffColour** [comment]
Thanks. I'll see if I can work that into my DSC script.
