### ISSUE TITLE
Feedback: 'MSMQ Transport Scripting'

### ISSUE THREAD

**Issue by ezmani** [Particular/docs.particular.net#4039]
Just as a followup of my chat today. I was able to create queues for my endpoints as a part of our octopus deploy steps by doing the following...

After deploying your NServiceBus application, add a powershell script step. with the following commands.

`
. $InstallPath\bin\CreateQueues.ps1
CreateQueuesForEndpoint -EndpointName $AppName -Account $AppAccount
`
the **. (period)** in front of the $InstallPath\bin\CreateQueues.ps1 was crucial to load the functions...

Thanks for your help today!
Mani

Feedback for 'MSMQ Transport Scripting' https://docs.particular.net/transports/msmq/operations-scripting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/msmq/operations-scripting.md

ping @Particular/msmq-transport-maintainers

**Comment by seanfarmar** [comment]
Thanks @ezmani
