### ISSUE TITLE
Suggested v7 Critical API is obsolete

### ISSUE THREAD

**Issue by HEskandari** [Particular/docs.particular.net#4052]
On the page here https://docs.particular.net/nservicebus/hosting/critical-errors#custom-handling

The prescribed approach of using `endpointConfiguration.DefineCriticalErrorAction(OnCriticalError);` is obsolete on v7.

**Comment by danielmarbach** [comment]
The documentation was recently updated and points to https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/CriticalError/ConfigureCriticalErrorAction.cs#L16 which is not obsolete. Closing for now
