### ISSUE TITLE
Feedback: 'Configuration order for persistence'

### ISSUE THREAD

**Issue by stevebroshar** [Particular/docs.particular.net#4069]
Feedback for 'Configuration order for persistence' https://docs.particular.net/persistence/order

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/order.md

ping @Particular/nservicebus-maintainers

The three examples are not well written, not clear and seem contradictory. 

Example 1 says "the last configuration option will override all previous options" which is basically what it says above "The last-configured persistence option will be the one used by the endpoint." An example should be VERY specific -- more specific than other info. It should say something like: raven persistence will be used and the nhibernate and in-memory persistence calls will be ignored.

Example 2 talks about 'explicit', but this is about overwriting. I'm confused that this one talks about 'explicit'. Does it mean that in this example, there is no overwriting? if so, then I'm VERY confused. Why doesn't the last call overwrite the others ... like the rules says?

Example 3: Totally confused what this is trying to show me.

**Comment by timbussmann** [comment]
That page definitely needs a makeover. Thanks for your feedback @stevebroshar 👍 

> Why doesn't the last call overwrite the others ... like the rules says?

all the configurations in sample 2 are scoped to a specific storage type. the last line is configuring only the persistence to use for timeouts. This example indeed doesn't show no overwriting and that needs to be stated better indeed.

example 3 tried to show a better approach to customize persistence for specific storage types without the need to define every single storage type as in example 2. It has the same "output" as example 2.
