### ISSUE TITLE
Feedback: 'SQL Server Native Delayed Delivery'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4073]
Feedback for 'SQL Server Native Delayed Delivery' https://docs.particular.net/transports/sql/native-delayed-delivery

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sql/native-delayed-delivery.md

ping @Particular/sqlserver-transport-maintainers 

Documentation doesn't say that Native Delayed delivery is impacted and endpoints will not work when configured in send-only.

**Comment by SzymonPobiega** [comment]
Addressed by https://github.com/Particular/docs.particular.net/pull/4109
