### ISSUE TITLE
Feedback: 'Controlling What Is Subscribed'

### ISSUE THREAD

**Issue by stevebroshar** [Particular/docs.particular.net#4077]
Feedback for 'Controlling What Is Subscribed' https://docs.particular.net/nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed.md

ping @Particular/nservicebus-maintainers

WRT "When a subscriber stops or uninstalls
A subscriber will not unsubscribe when it stops; it will remain registered at the publisher to receive events. The publisher still sends events to the queue of the stopped subscriber. When the subscriber is started, it will consume the messages from its queue. The subscriber will never lose an event."

I think this is somewhat misleading. Sounds like it always a good thing that messages are queued. But, it's only good if the subscriber is going to come back up soon. If it's being uninstalled (or down for along time), then queuing is bad ... messages will pile up. Eventually the queue will fill up and break ... as we've seen with msmq.

**Comment by danielmarbach** [comment]
Hi @stevebroshar 

Thanks for your input. What you are describing is inherently something you have to deal with when doing queuing. Let me give you an example. Messaging is a good fit for things that are of fire & forget nature or business requests that you can answer with "thank you very much we got your request and will ping you back once we are done". You could apply messaging and queuing in memory within the same process that issues the request. But when you are bound to the resources of that process as well as the availability of that process. With reliable queuing, we are switching essentially to storage backed queues thus offloading that problem to a storage. With the storage, the sender of the request and the receiver of the request are decoupled an no longer share the same process resources. Than can differ in versions, capacity and more. As soon as you move to storage backed queues though you have to start doing capacity planning. The capacity planning involves many things like the expected peak load and sustainable load over time, payload and header size, expected receive throughput of the receiver to fulfill the business SLAs and more. A subscriber has to do the same for the events it is interested in. If that's not done at some point in time you run out of storage/capacity and then you lose all the benefits that you were betting on by buying into messaging. 


Regards
Daniel

**Comment by danielmarbach** [comment]
The guidance as we have today is in my view good enough. Closing for now
