### ISSUE TITLE
Feedback: 'Using ServiceControl Events'

### ISSUE THREAD

**Issue by dasjestyr** [Particular/docs.particular.net#4078]
Feedback for 'Using ServiceControl Events' https://docs.particular.net/servicecontrol/contracts

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/contracts.md

ping @Particular/servicecontrol-maintainers

How would you do the mappings in netcore? There is no app.config. Is there a way to do it in code perhaps?

**Comment by danielmarbach** [comment]
@dasjestyr I seem to remember you use Azure Service Bus. If you are using the forwarding topology then no mapping is required. If you are using the endpoint oriented topology then you need to use the [`RegisterPublisher` API](https://docs.particular.net/transports/azure-service-bus/publisher-names-configuration). But definitely, this documentation requires an update. Thanks for pointing out

**Comment by dasjestyr** [comment]
Good memory! We actually switched to rabbitmq a while back. Any difference there?

**Comment by danielmarbach** [comment]
Nope. You don't need to do anything there. The existence of a handler is enough for rabbitmq transport to derive the infrastructure it needs to set up so that messages will be routed to the subscriber.

**Comment by dasjestyr** [comment]
Haha I wasn't :). Sounds good though, thanks!

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/docs.particular.net/pull/4090
