### ISSUE TITLE
Feedback: 'Error notifications'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4080]
Feedback for 'Error notifications' https://docs.particular.net/nservicebus/recoverability/subscribing-to-error-notifications

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/subscribing-to-error-notifications.md

ping @Particular/nservicebus-maintainers

An attempt to retrieve `Notifications` from container will always throw.
Instead, it's only possible to get it via `Settings`.

**Comment by timbussmann** [comment]
@SeanFeldman `Notifications` is accessible via the configuration as shown in the sample, not via DI. Maybe I missed it but where did you see documentation that Notifications would be available from the DI container?

**Comment by SeanFeldman** [comment]
@timbussmann a customer needed to have access to `Notifications` from a feature and our documentation indicated that it's resolvable via container. It's right in the article this issue is for.
![image](https://user-images.githubusercontent.com/1309622/47516436-b7ecf100-d842-11e8-9122-1c94875dfe60.png)

**Comment by SeanFeldman** [comment]
I've raised a [PR](https://github.com/Particular/docs.particular.net) to remove this info. It has been merged, so that could be the reason it's not showing up for you now.

**Comment by timbussmann** [comment]
@SeanFeldman the link to the PR is not working.

I found [this line in the InitializableEndpoint](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L59) which indicates that it should be available via DI. A fist test also confirms that I can indeed inject `Notifications` into a handler (although that doesn't seem like a good idea).

**Comment by SeanFeldman** [comment]
You _can_ inject, not that it is found in container, right?
Customer needed to access container from a feature, not handler.

**Comment by SeanFeldman** [comment]
Do you mean `FeatureStartupTask`?
Not sure how that would work as `FeatureStartupTask` has no container exposed. Just methods with `IMessageSession`.
While `Feature` does have a container exposed via `FeatureConfigurationContext`.

**Comment by andreasohlund** [comment]
You can control how tasks are created using:

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/FeatureConfigurationContext.cs#L92

and there you have access to the `IBuilder`.

Side note: We should document this here https://docs.particular.net/nservicebus/pipeline/features#feature-startup-tasks

**Comment by timbussmann** [comment]
> While Feature does have a container exposed via FeatureConfigurationContext.

that container property cannot resolve instances but allows to register custom services in the DI container. It is of type `IConfigureComponents`. You cannot inject dependencies into `Features`.

However, `FeatureStartupTasks`  are built from the DI container, therefore you can inject dependencies (like `Notifications`) into it.

As said, `Notifications` are definitely available to be injected via DI. See https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L59 so the changes made are incorrect. I agree that the docs around this could be improved though.

**Comment by SeanFeldman** [comment]
> You can control how tasks are created using:
> 
> https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/FeatureConfigurationContext.cs#L92

@andreasohlund did you see the remark?

> Should only be used when really necessary. Usually a design smell.

😂 

> that container property cannot resolve instances but allows to register custom services in the DI container. It is of type `IConfigureComponents`. You cannot inject dependencies into `Features`.

That's a good point @timbussmann. The name `Container` is a really poor name as it's misleading on what it can do.

> As said, `Notifications` are definitely available to be injected via D

In that case, if `Notifications` object is found in DI container, what is the right way of accessing `Notifications`?

**Comment by andreasohlund** [comment]
>ideally the new notifications API would be available on the feature configuration context but unfortunately, we never got to do that. Maybe something to consider for a maintenance release?

👍

**Comment by timbussmann** [comment]
I feel like we can close this issue. Any objections?

**Comment by timbussmann** [comment]
issue raised here: https://github.com/Particular/NServiceBus/issues/5293

**Comment by andreasohlund** [comment]
Do we need to revert https://github.com/Particular/docs.particular.net/pull/4079 ?

**Comment by timbussmann** [comment]
technically yes.
