### ISSUE TITLE
Feedback: 'Critical Errors'

### ISSUE THREAD

**Issue by stevebroshar** [Particular/docs.particular.net#4087]
Feedback for 'Critical Errors' https://docs.particular.net/nservicebus/hosting/critical-errors

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/critical-errors.md

ping @Particular/nservicebus-maintainers

WRT: 
"Critical Errors are logged inside the critical error action. This means that if replacing the Critical Error in these versions ensure to write the log entry.

 var logger = LogManager.GetLogger("NServiceBus");
logger.Fatal(errorMessage, exception);"

LogManager is not accessible (internal). Is the doc wrong? Or am I doing something wrong?

I'm on nsb 6.2.1

decompiled code:
using NServiceBus.Logging;
using System;

internal static class LogManager
{
  public static ILog GetLogger<T>()
  {
    Type type = typeof (T);
    if (type.Namespace == null)
      return NServiceBus.Logging.LogManager.GetLogger(string.Format("NServiceBus.Persistence.Sql.{0}", (object) type.Name));
    return NServiceBus.Logging.LogManager.GetLogger(type);
  }
}

**Comment by HEskandari** [comment]
I think the point here was to log a Fatal message so that your operations team would understand what has happened (and take necessary actions like Environment.FailFast). 

The `LogManager.GetLogger` could still hold true, e.g. if you use NLog, but I understand how this could be confusing.

**Comment by danielmarbach** [comment]
We have reworked the guidance quite a bit recently. Closing this for now since the guidance should be more clear.
