### ISSUE TITLE
Feedback: 'Discarding Old Messages'

### ISSUE THREAD

**Issue by stevebroshar** [Particular/docs.particular.net#4099]
Feedback for 'Discarding Old Messages' https://docs.particular.net/nservicebus/messaging/discard-old-messages

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/discard-old-messages.md

WRT:
To discard old messages at startup: endpointConfiguration.PurgeOnStartup(true);

Is that for the sending endpoint or the receiving one? I'm thinking ICommand endpoints.

**Comment by ramonsmits** [comment]
@stevebroshar This is about messages waiting to be processed by that specific endpoint so any messages in its incoming queues. The endpoint is not in control of purging any messages that it has send in the past.

**Comment by ramonsmits** [comment]
I have created a documentation improvement, see #4102 and close this.
