### ISSUE TITLE
what to do with NSB.serilog in 'Scheduling Samples'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#4105]
i note the quartz and hangfire samples use NSB.serilog. Since i dont really consider them "NSB.serilog samples" i havnt been updating them. So should NSB.serilog be removed from those samples?

Feedback for 'Scheduling Samples' https://docs.particular.net/samples/scheduling/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/scheduling/index.md

**Comment by mikeminutillo** [comment]
In both cases, this was explicitly added to show integration with LibLog. Is that still relevant?

**Comment by SimonCropp** [comment]
no idea. but if it is couldnt the same be achieved with nlog?
