### ISSUE TITLE
Feedback: 'NServiceBus Router'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4129]
Feedback for 'NServiceBus Router' https://docs.particular.net/nservicebus/router/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/router/index.md

https://docs.particular.net/nservicebus/router/#topologies-bridge section is called Bridge, but this article is about router, no?

**Comment by danielmarbach** [comment]
The page has been overhauled and it looks like the issue doesn't exist anymore.
