### ISSUE TITLE
Feedback: 'Hosting endpoints in Docker Linux containers'

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#4137]
Feedback for 'Hosting endpoints in Docker Linux containers' https://docs.particular.net/samples/hosting/docker/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/docker/sample.md

The sample should be updated to .NET Core 2.1

**Comment by danielmarbach** [comment]
Updated to Netcore App 3.1

https://github.com/Particular/docs.particular.net/pull/4625
