### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Getting started'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4138]
Feedback for 'NServiceBus Step-by-step: Getting started' https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md

If code is copied as-is will result in error:

```
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	
```

Tutorial should indicate it requires certain [C# language version](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) or to be set to the latest.

**Comment by SeanFeldman** [comment]
Another [LiveChat visitor](https://my.livechatinc.com/tickets/ZXV56) had exactly the same issue.

**Comment by danielmarbach** [comment]
The tutorial mentions the language version if the async main is used

![image](https://user-images.githubusercontent.com/174258/75153160-fd595100-570a-11ea-8639-c8c792a41a25.png)
