### ISSUE TITLE
Feedback: 'Particular Service Platform Overview'

### ISSUE THREAD

**Issue by Thoemmeli** [Particular/docs.particular.net#4139]
Feedback for 'Particular Service Platform Overview' https://docs.particular.net/platform/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/platform/index.md

The picture on the page above is confusing in my opinion. NServiceBus is described as the heart of the system, but does not show up in the picture. In the picture the ServiceControl is very prominently displayed. As a newby to NServiceBus, I'd like to get a quick overview of the possible integration capabilities of the components and that I don't get from this page.
For me it is also not clear what "Endpoint" means in the picture.
Additionally it would be good to see dominant persistency integrations of NServiceBus.

Kind regards
Thomas

**Comment by kbaley** [comment]
Hi Thomas,

Looking over that page and I agree it could be clearer. Let me see what I can do in the coming days and I'll ping you on the PR.

**Comment by kbaley** [comment]
@Thoemmeli Kind of jumped the gun and merged already. How does this look now? https://docs.particular.net/platform/

**Comment by kbaley** [comment]
Going to close this as resolved. @Thoemmeli let me know if you have any further suggestions and I can re-open as necessary.
