### ISSUE TITLE
add doco on how to make auto binding redirects work with the NSB host 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#4143]
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

**Comment by ramonsmits** [comment]
@SimonCropp thanks for this, I'm going to research this feature and see how I can adjust the doco

**Comment by SimonCropp** [comment]
Thanks ramon
