### ISSUE TITLE
Feedback: 'NServiceBus and Azure'

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#4150]
Feedback for 'NServiceBus and Azure' https://docs.particular.net/nservicebus/azure/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/azure/index.md

This is a weird article that brings together different Azure pieces for some reason. Most are just signposts, but the "related links" under this directory are included in various places in other sections in the menu and should probably be moved there as well.

**Comment by danielmarbach** [comment]
@DavidBoike I looked at this as part of the 30 min process and couldn't figure out what you wanted to achieve base on the issue description. More than happy to give it a stab if you can explain to me what would make more sense in your regard

**Comment by DavidBoike** [comment]
This probably doesn't look the same as when I opened the issue, but…

Look at the Related Links section. (Avoiding transactions, data distribution, understanding transactions). Those are "related links" because they're generated based on the directory structure. So the first one is `/nservicebus/azure/ways-to-live-without-transactions`. But then link to it (and the other two)  and you'll see they're linked in the menu to random spots in the ASB (Legacy) doco. Oh, and ASQ apparently - both are expanded and have a "current" node highlighted. But not the new ASB. Super confusing.

**Comment by danielmarbach** [comment]
I tried to rearrange a bit the menu structure and hopefully that addresses what you mentioned. See https://github.com/Particular/docs.particular.net/pull/4712
