### ISSUE TITLE
Feedback: 'Upgrade Version 6 to 7'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4156]
Feedback for 'Upgrade Version 6 to 7' https://docs.particular.net/nservicebus/upgrades/6to7/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/6to7/index.md

The upgrade guide doesn't say anything about change to the underlying default DI container and the fact that it's immutable. A customer ran into an issue with this and it wasn't obvious until switched to AutoFac(to mimic Core v6). Support case: https://c.eu1.visual.force.com/apex/Case?num=00040910

**Comment by danielmarbach** [comment]
Fixed via https://github.com/Particular/docs.particular.net/commit/9cc646ca9bd229078bcd3ed40186d24502d6755a
