### ISSUE TITLE
Feedback: 'Configure delayed retries'

### ISSUE THREAD

**Issue by colindooley11** [Particular/docs.particular.net#4159]
Feedback for 'Configure delayed retries' https://docs.particular.net/nservicebus/recoverability/configure-delayed-retries

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/configure-delayed-retries.md

In the section quoted below it is unclear whether the delayed.TimeIncrease is a backoff or not
I'm pretty sure in older versions of Nsb this was a back off.    
Here, however our findings show that the delay doesnt increase per retry, but rather it is set intervals.
 
That is, every retry occurs at delay interval.   There is no increase in the delay interval, it is static. 

Wouldnt 
`delayed.TimeIncrease()`

Perhaps read better as:

`delayed.Interval()`

If the true intention is not to back off?

> Configuring delayed retries
TimeIncrease: Specified as a TimeSpan. Specifies the delay interval for each retry attempt. This delay increases by the same timespan with each delayed delivery. For example, if the specified value is ten seconds, i.e. 00:00:10, then the first delayed retry will be at ten seconds, the subsequent delayed retry will be twenty seconds, and so on.
NumberOfRetries: Number of times delayed retries are performed. Default: 3.
 var recoverability = endpointConfiguration.Recoverability();
recoverability.Delayed(
    delayed =>
    {
        delayed.NumberOfRetries(2);
        delayed.TimeIncrease(TimeSpan.FromMinutes(5));
    });

**Comment by andreasohlund** [comment]
This sounds like a bug to me. I tried to repro this with our Fault Tolerance sample and in it worked fine in default mode. 

https://docs.particular.net/samples/faulttolerance/ (I ran the V7 version) 

Also tried a custom policy with a 5s backoff and it gave the expected 5s, 10s, 15s retry sequence.

```
  var recoverability = endpointConfiguration.Recoverability();
        recoverability.Delayed(settings =>
        {
            settings.NumberOfRetries(3);
            settings.TimeIncrease(TimeSpan.FromSeconds(5));
        })
            .Immediate(c=>c.NumberOfRetries(0));
```

Can you run the sample and see if it work as intended on your end?

**Comment by colindooley11** [comment]
I re-ran some tests with the help of a better tool to observe behaviour.  I believe the first set of tests were running interleaved message retries, that is more than 1 message being retried at once,which I think threw everyone.  

I can confirm after a number of tests that, as you say, this works as the document and API indicates.
