### ISSUE TITLE
ServiceControl instance log location wrong

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#4166]
The log location specified here(https://docs.particular.net/servicecontrol/logging) is incorrect.  It says logs live

```
%PROFILEPATH%\AppData\Local\Particular\ServiceControl\logs
```
OR

```
%WINDIR%\System32\config\systemprofile\AppData\Local\Particular\ServiceControl\logs
```

It looks like the instance name is left out of the log path because below is where my logs are located at

```
C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl.prod\Logs
```

/cc @WilliamBZA

**Comment by adamralph** [comment]
Hi @TraGicCode. Which version of ServiceControl are you using?

**Comment by TraGicCode** [comment]
Hey @adamralph ,

We are using the latest version currently.

**Comment by adamralph** [comment]
@TraGicCode thanks. We'll get back to you ASAP.

**Comment by mikeminutillo** [comment]
There's a few different things going on here and it's making it much more complicated that it probably needs to be. We should simplify it and clean up this doco.

1. The log path can be specified in the config file [If it is, then this is the path that is used](https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Infrastructure/Settings/LoggingSettings.cs#L14)
2. The ServiceControl Management utility always specifies a path for new instances. [By default](https://github.com/Particular/ServiceControl/blob/6881be203b5e7ab274715abe60bb6bb148e457a6/src/ServiceControl.Config/UI/InstanceAdd/ServiceControlAddViewModel.cs#L105), this is going to be `%CommonAppData%\Particular\ServiceControl\<InstanceName>\Logs`
3. If you skip the Management Utility and use Powershell, you must specify a log location. [It is mandatory](https://github.com/Particular/ServiceControl/blob/6881be203b5e7ab274715abe60bb6bb148e457a6/src/ServiceControlInstaller.PowerShell/Cmdlets/ServiceControlInstances/NewServiceControlInstance.cs#L33)
4. If nothing is specified in the config file then the instance will fall back to a [default log location](https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Infrastructure/Settings/LoggingSettings.cs#L41-L49). This location depends on the instance name and goes in the `%LocalAppData%\Particular\<InstanceName>\Logs`. To add to the weirdness, if the ServiceControl instance name is `Particular.ServiceControl` then the instance name is switched to `ServiceControl` in the log path.
