### ISSUE TITLE
Elaborate on costs associated with DynamicHost (shared host) with Azure Cloud Services

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#417]
Azure Cloud Services have a fairly steep learning curve and expensive deployment model out of the box (OOTB default mechanism would be a cloud service instance/VM per end point). For those who are interested to take NServiceBus from on premises into Azure w/o knowing about Dynamic host, how it works, and what it costs, this might be a point giving up on Azure or NServiceBus (depending on what stage they are in). In addition to that, there's a perception that combination of Azure Web Sites and Web Jobs should do the same as Cloud Services, but for a fraction of Cloud Service expense.

We should address these concerns and make Dynamic Host stand out more to be obvious. 
Also, we should discuss how to address Azure Web Sites and Web Jobs question.

//cc @yvesgoeleven @dannycohen

**Comment by SimonCropp** [comment]
@SeanFeldman i dont think there is value in scheduling docs issues. they will always be placed under bugs and features. so if u think this is worth doing just set aside a small amount of time over a few days and get it done.

**Comment by SeanFeldman** [comment]
@SimonCropp this should be updates - would be a good blog post, not a doco change.

**Comment by SimonCropp** [comment]
Ok closing
