### ISSUE TITLE
3rd party Integration site is incomplete

### ISSUE THREAD

**Issue by WojcikMike** [Particular/docs.particular.net#4174]
The following site:
https://docs.particular.net/nservicebus/messaging/third-party-integration

Does not contain all the information that is required by ServiceControl. In this issue, Simon identified a few other information that needs to be included. This should be reviewed and filled out

**Comment by danielmarbach** [comment]
> Simon identified a few other information that needs to be included

Where is that information? If you can point me to it I can validate it and add it. If the information is lost I vote to close this one for now
