### ISSUE TITLE
Saga guidance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#418]
Following up a conversation @ NSBCon: provide more guidance on Saga, from an architectural point of view, high level.
When to use, when not, performance considerations, etc..

**Comment by mauroservienti** [comment]
Do you see any value in converting this in a blog post or in adding also a blog post?

* blog post: the what and the why from an architectural POV;
* Guidance: When to use, when not, performance considerations, tech details, reply-to-originator, etc..

**Comment by SimonCropp** [comment]
@mauroservienti no objection to this being a blog post. but it should be doco first.

**Comment by SzymonPobiega** [comment]
I would add information about how to design saga data properly. The one generated by default by SM (people would assume SM enforces good practices) includes all received messages in 1:1 mapping which is not supported by NH persister.

**Comment by SimonCropp** [comment]
if anyone wants to get around to this please submit a PR
