### ISSUE TITLE
Feedback: 'dotnet new Templates'

### ISSUE THREAD

**Issue by Fer-Diaz** [Particular/docs.particular.net#4188]
Feedback for 'dotnet new Templates' https://docs.particular.net/nservicebus/dotnet-templates

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/dotnet-templates.md

This template "dotnet new nsbwinservice" not matched

**Comment by DavidBoike** [comment]
Hi @Fer-Diaz,

Did you install the template package first?

```
dotnet new --install ParticularTemplates
```

**Comment by danielmarbach** [comment]
I have verified that using the templates work after you have installed the particular templates like @DavidBoike mentioned. Closing
