### ISSUE TITLE
ServicePulse Installation doco lacks Monitoring configuration info

### ISSUE THREAD

**Issue by tmasternak** [Particular/docs.particular.net#4192]
On the SerciePulse installation page https://docs.particular.net/servicepulse/installation#configuring-servicepulse we show how to configure SC url but we don't show how to configure Monitoring url.

In addition, we don't link to Monitoring configuration page.

**Comment by danielmarbach** [comment]
@tmasternak I raised https://github.com/Particular/docs.particular.net/pull/4702 as an attempt to close this. Please have a look
