### ISSUE TITLE
IMHO: you should use continue insteadof return.

### ISSUE THREAD

**Issue by JSCProjects** [Particular/docs.particular.net#4194]
https://github.com/Particular/docs.particular.net/blob/f9ec8f1fcf68fdbc269918c2a34727b7f9551ce6/samples/azure/blob-storage-databus-cleanup-function/ABSDataBus_2/DataBusBlobCleanupFunctions/DataBusOrchestrateExistingBlobs.cs#L38

**Comment by SeanFeldman** [comment]
Thank you @JSCProjects!
Will be fixed via #4196
