### ISSUE TITLE
Feedback: 'Transaction support'

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#4199]
Feedback for 'Transaction support' https://docs.particular.net/transports/sql/transactions

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sql/transactions.md

Didn't netcore2.1 fix the transactionscope issue?

https://stackify.com/new-in-net-core-2-1/

cc @bording @Particular/sqlserver-transport-maintainers

**Comment by bording** [comment]
@andreasohlund Yes it was resolved by the System.Data.SqlClient 4.5.0 package, which was released as part of .NET Core 2.1.

However, even though it does support TransactionScopes, you still can't promote to DTC.

**Comment by andreasohlund** [comment]
Ah ok, I will fix the sample still since the ifdef is broken

**Comment by andreasohlund** [comment]
PR raised to remove the uneeded ifdef https://github.com/Particular/docs.particular.net/pull/4214
