### ISSUE TITLE
Visual language for documentation

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#421]
We need a consistent "visual language" to describe concepts and elements for NServiceBus (endpoint, handler, saga, queue, command, event, etc). It would be good to have something similar to stencils/icons  collection we could use in our documentation and presentations.

/cc @sergioc @dannycohen

**Comment by sergioc** [comment]
@SeanFeldman Option 2 is best, possibly with addition of my time for revision for each diagram.

ETA possibly in 1 - 1,5 months.

**Comment by sergioc** [comment]
@ramonsmits That's possible, but that stencil template would need to match the visual language we use in products.

**Comment by sergioc** [comment]
Here's an initial proposal. There's 2 sets of stencils, one has labeled stencils, the other doesn't.

![screenshot 2015-02-26 16 18 56](https://cloud.githubusercontent.com/assets/493451/6394772/20f92868-bdd4-11e4-8b53-0288816806fd.png)

I'll probably need to further refine the set (e.g. possibly with color) by working on an example application - maybe on one of the next documentation articles.

**Comment by SeanFeldman** [comment]
@sergioc a few questions as a result of looking on the stencils on the left only

1. Endpoint Rx vs Tx - could those be arrows indicating in vs out?
2. Timeout message - could it combine a message with something to indicate time (sand clock)?

**Comment by sergioc** [comment]
@SeanFeldman 

1. Those endpoint icons are based on what we used in the products. Adding arrows would increase detail and make it more difficult to scale down the standard icon.
2. That's the standard icon we use in SI. But I'm intrigued by your suggestion - why a sand clock instead?

**Comment by SeanFeldman** [comment]
Sand clock has less details and you always know that time is running out, nothing else :)

**Comment by sergioc** [comment]
I do agree that the sand clock simplifies the visual!

I think the alarm clock better exemplifies time that "ran out", while sand clock better represents time that is "running out" - which concept applies best to represent a Timeout message - time that "ran out" or time that is "running out"?

Also note that the sand clock icon is a classic representation of "wait" - in the old progress/wait cursor indicator from Windows - not sure whether that could cause confusion.

Can someone else comment on @SeanFeldman's suggestion for a timeout icon?

**Comment by SeanFeldman** [comment]
Very good point on classical representation. There was a [good post from Hanselman](http://www.hanselman.com/blog/TheFloppyDiskMeansSaveAnd14OtherOldPeopleIconsThatDontMakeSenseAnymore.aspx) on this.

**Comment by SimonCropp** [comment]
Few questions

1. how will this be distributed to people? some custom visio stencil package? or leverage some online tool like https://www.lucidchart.com/personahomepage?
2. When the stencils evolve how all the existing diagrams be updated?

**Comment by sergioc** [comment]
@SimonCropp 

1. distribution yet to be decided - ideally use a collaborative platform (like LucidChart) that supports real stencils (with support for renaming labels, for example. I'll investigate further.
2. This can be approached in 3 ways:
    - Avoid changing existing stencils to minimise disruption
    - Whenever I update the stencils, I'll notify everyone in guidance (let me know if more needed) via email, to allow docs authors to see if existing diagrams need to be updated.
    - Lucid chart support dynamic image linking, i.e. you define an area of the diagram for exporting as an image, generate image URL, and whenever the diagram is updated, the linked image is updated automatically.

**Comment by SimonCropp** [comment]
@sergioc cool. glad you are thinking about it

**Comment by sergioc** [comment]
Here's a link to a Lucidchart document where you can find the stencils ready for copy-pasting: https://www.lucidchart.com/invitations/accept/bf3c8af7-eabf-4d5b-9961-228a00b5ae11

A couple of remarks:
1) If you want you can [follow these instruction to have all shapes in a shape library](http://support.lucidchart.com/entries/23132309-Create-Custom-Shapes). Only issue with this is that you have to manage that library whenever the stencils are updated.
2) When a shape is resized, the size of the labels are not resized. If needed I can supply an extra set of sizes, though you can always control final size of diagram on export.

Let me know when you have a document created with theses shapes for me to check or if you need any help.

**Comment by SimonCropp** [comment]
so this seems to be done

**Comment by carlbm** [comment]
@sergioc  Are these for public consumption? If so the lucidchart link has expired.
It would be great to get hold of an updated copy.

**Comment by sergioc** [comment]
@carlbm we're not promoting the use of these stencils at the moment since they haven't been tested yet, but we won't prevent anyone from using. I've updated my previous comment with a valid share link.

In case you decide to use the stencils, we'd love to hear about any feedback or limitations found in your intended usage.

**Comment by carlbm** [comment]
Thank you. 
Some initial feedback (and I'm being very picky here, it's a great resource so thank you again!)

- Have a visio stencil to use out the box would be useful for those of us that use visio.
- Having a set with inverted colours would be useful for those of us who like light backgrounds (assuming this doesn't work against any of your guidelines.

**Comment by carlbm** [comment]
[NSB.zip](https://github.com/Particular/docs.particular.net/files/437109/NSB.zip)

I used your stencil to create a visio stencil which I've attached in case anyone else is interested. I haven't actually used it yet :smile: but I'll feedback once I have.

**Comment by sergioc** [comment]
@carlbm thanks. I assume you exported to Visio from LucidChart. That should cover the issue you mentioned above.

> Having a set with inverted colours would be useful for those of us who like light backgrounds 

The stencils were originally meant to be used on light backgrounds. Did you mean to say that you'd prefer a lighter stencil background to make the contrast between stencils and canvas less pronounced?
