### ISSUE TITLE
Feedback: 'Multiple namespace support'

### ISSUE THREAD

**Issue by janpieterz** [Particular/docs.particular.net#4222]
Azure Service Bus doesn't support SendsAtomicWithReceive when using multiple namespaces, but this doesn't seem to be documented.

Feedback for 'Multiple namespace support' https://docs.particular.net/transports/azure-service-bus/legacy/multiple-namespaces-support

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/legacy/multiple-namespaces-support.md

**Comment by HEskandari** [comment]
Pinging @Particular/azure-maintainers.

**Comment by yvesgoeleven** [comment]
It is documented here : https://docs.particular.net/transports/azure-service-bus/legacy/understanding-transactions-and-delivery-guarantees

**Comment by SeanFeldman** [comment]
"Understanding internal transactions and delivery guarantees" article explains how SendsAtomicWithReceive is working with ASB, transactional scope, how to use suppression scope, warns about satellites, but it doesn't state anything about multiple namespaces and downgrading transactional guarantees @yvesgoeleven.

**Comment by yvesgoeleven** [comment]
>  It requires destination and receive queues to be in the same namespace. 

It does, but we can repeat

**Comment by janpieterz** [comment]
I'd appreciate the repeat, it's quite a big difference. Maybe it's also on this page besides the multiple namespaces one https://docs.particular.net/transports/azure-service-bus/legacy/transaction-support ?

**Comment by SeanFeldman** [comment]
> TransportTransactionMode.SendsAtomicWithReceive level is only supported in Versions 7 and above of the Azure Service Bus transport. It requires destination and receive queues to be in the same namespace

Maybe I'm off, but reading this, it does not jump out at me as a warning where we'd explicitly spell out that "endpoint's transactional guarantees **will be lowered** when multiple namespace are used". I think this is what @janpieterz is looking for. 

I myself read the doco and didn't see the obvious 😊
