### ISSUE TITLE
ServiceControl: Add supported platforms documentation

### ISSUE THREAD

**Issue by seanfarmar** [Particular/docs.particular.net#4257]
we have hardware requirements, no OS compatibility 

https://docs.particular.net/servicecontrol/servicecontrol-instances/hardware

**Comment by dvdstelt** [comment]
@seanfarmar Is it possible to open a PR and document it?

**Comment by seanfarmar** [comment]
I'm not sure what are the requirements....

**Comment by dvdstelt** [comment]
Which requirements? I mean, why did you open the issue? We could theoretically state which .NET Framework is needed and direct to .NET Framework OS compatibility. Would that be enough?

**Comment by sergioc** [comment]
@seanfarmar the only software requirement is here https://docs.particular.net/servicecontrol/installation#prerequisites

Would that be enough?

**Comment by HEskandari** [comment]
We discussed and believe the specified .NET Framework version on the issue is enough. Any OS supporting that version would work.
