### ISSUE TITLE
Feedback: 'Metrics'

### ISSUE THREAD

**Issue by michjuh** [Particular/docs.particular.net#4264]
Feedback for 'Metrics' https://docs.particular.net/monitoring/metrics/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/monitoring/metrics/index.md

Hi, 
Could you add a paragraph on why metrics are not supported in 'sendonly' endpoint configurations? It would warn users and I'm also curious why this is? I'm assuming because the metrics captured are centered around the receiving end? 

👍👍

**Comment by timbussmann** [comment]
Hey @michjuh thanks for the feedback 👍 

tbh that's a very good question. I'm not sure how much sense it makes to enable metrics from an endpoint which can't really provide any of the metrics as they are all based on the incoming messages but I'm not sure why this feature throws at startup. @Particular/metrics-maintainers do you have any background info on this?

**Comment by timbussmann** [comment]
I've raised #4270 to make a note about send-only endpoints. Furthermore I've raised https://github.com/Particular/NServiceBus.Metrics.ServiceControl/issues/60 in the plugin repository to further discuss the current behavior of throwing exceptions.

Is there a specific reason you want to use metrics on a send-only endpoint  @michjuh ?

**Comment by michjuh** [comment]
Hello, we planned to enable metrics on all of our active endpoints just to be thorough and were surprised to see it throw on startup. So no there's no specific reason to have this, just curious. Thanks for the efforts :)

**Comment by timbussmann** [comment]
Thanks for the explanation @michjuh 👍 
The docs should now represent the behavior you've noticed better due to #4270. Please feel free to reopen this issue if you feel there is still something missing. Thanks again for the feedback, highly appreciated!
