### ISSUE TITLE
Feedback: 'Installers'

### ISSUE THREAD

**Issue by philippdolder** [Particular/docs.particular.net#4269]
Feedback for 'Installers' https://docs.particular.net/nservicebus/operations/installers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/operations/installers.md

Overall the guidance regarding the use of installers in production is slightly contradictory. In the above referenced doc it appears that running installers on first start in a production environment is an acceptable approach.
Other resources like https://docs.particular.net/persistence/sql/installer-workflow or https://docs.particular.net/persistence/sql/install explicitly state installers should not be used outside of developer machines' context

My take from what I've read so far is to not rely on installers at all, and make sure the deployment process is taking care of everything that is required.

**Comment by danielmarbach** [comment]
I reread the latest updates to the linked pages and to my biased viewpoint it looks like we are using suggestive language only and leave it up to the reader to find their own ways. Whether they want to use installers during development and deployment only or all the time or never and script everything there is no explicit preference mentioned in the docs. Closing this
