### ISSUE TITLE
Feedback: 'MSMQ Subscription Persistence'

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#4285]
Feedback for 'MSMQ Subscription Persistence' https://docs.particular.net/persistence/msmq/subscription

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/msmq/subscription.md

The page mentions `InMemoryPersistence` which is misleading for the users who copy the code to their own solutions.

**Comment by danielmarbach** [comment]
I looked at this and came to the conclusion that it is ok to show InMemoryPersistence as an example for different storage types. I slightly reworded the sentence that introduces this sample to make it less confusing

https://github.com/Particular/docs.particular.net/pull/4703
