### ISSUE TITLE
Feedback: 'Message replay tutorial'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4289]
Feedback for 'Message replay tutorial' https://docs.particular.net/tutorials/message-replay/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/message-replay/tutorial.md

With the option to distribute Platform Tools along with the code, should the sample be update to make it simpler to run?

/cc @Particular/developer-education-squad

**Comment by DavidBoike** [comment]
Opened a DevEd issue and will prioritize.
