### ISSUE TITLE
SP Using Events for Custom notification & Alerting

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#431]
1. Author an article that explains how to subscribe to SC failure events 
* Cover: 
   * Failed Messages
   * Failed Endpoints
   * Failed Custom Checks
* Reference sample code

Replaces article requirements for #234

**Comment by SimonCropp** [comment]
@sfarmar can u add a link to the relevant docs page and close this

**Comment by SimonCropp** [comment]
@sfarmar @dannycohen ok guys lacking any other context i am assuming this is done. please re-open if this is not the case
