### ISSUE TITLE
Feedback: 'Hosting' not clear that snippets need additional configuration

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#4328]
Feedback for 'Hosting' https://docs.particular.net/nservicebus/hosting/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/index.md

Based on a livechat.

The code snippets to new users look like that configuration is all that is needed which results in confusion as the snippets require additional configuration of options like the transport and/or persistence.

**Comment by danielmarbach** [comment]
Raised as a simple and quick improvement https://github.com/Particular/docs.particular.net/pull/4704
