### ISSUE TITLE
Feedback: 'Configuring Hosting'

### ISSUE THREAD

**Issue by robbaman** [Particular/docs.particular.net#4378]
Feedback for 'Configuring Hosting' https://docs.particular.net/servicepulse/host-config

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicepulse/host-config.md

Note that when changing the URL using this method you (sometimes) must also allow the use of the new port using:

netsh http add urlacl url=http://+:9099/ user=Everyone

For me this wasn't immediately obvious.

**Comment by HEskandari** [comment]
@robbaman thanks for reporting it. I think it makes sense to clarify it. I'll add it to my todo list to update the doco.

**Comment by HEskandari** [comment]
@robbaman thanks for the suggestion. I have incorporated your feedback into that page.
