### ISSUE TITLE
Better visibility for code snippet actions

### ISSUE THREAD

**Issue by stimms** [Particular/docs.particular.net#4384]
Feedback for 'NServiceBus Step-by-step: Sending a command' https://docs.particular.net/tutorials/nservicebus-step-by-step/2-sending-a-command/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md

Hello, 

This is a general sort of comment for the code snippets on the site. I was looking at the code samples and found it frustrating that the using statements are not shown. @SeanFeldman was kind enough to point out that the copy dropdown has an option to copy the using statement. 

However, this has super low discoverability - I would never have thought to look there for it. It would be very helpful to people if the usings were surfaced. I realize it adds noise but perhaps hiding it by default like this

![image](https://user-images.githubusercontent.com/153912/58904992-f8a8c480-86c5-11e9-9bab-af6418dc9547.png)

And allow users to expand it might increase discoverability without cluttering up the interface.

**Comment by dvdstelt** [comment]
Hi @stimms,

Thanks for the feedback, we value that a lot. Looking at it this way, I agree currently it's not as clear as it should be.

We would need to think and possible test the best solution. Just thinking out loud, maybe a first step could be to replace `Copy/Edit` with `Options`. That might be a quick(er) solution, before we start changing the actual UI of every snippet on our website?

**Comment by dvdstelt** [comment]
@stimms, we think we fixed it, by providing links instead of a pulldown menu and always showing the header. What do you say?!
