### ISSUE TITLE
Feedback: 'Persistence'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4459]
Feedback for 'Persistence' https://docs.particular.net/persistence/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/index.md

Should [MongoDB](https://docs.particular.net/persistence/mongodb/) be listed as well?

**Comment by mauroservienti** [comment]
MongoDB has been added to the list of supported persister.
![image](https://user-images.githubusercontent.com/1325611/67005759-a059e880-f0e3-11e9-8870-5e1c881526c0.png)

And in the [selection](https://docs.particular.net/persistence/selecting) chart as well.
