### ISSUE TITLE
Feedback: 'Selecting a persister'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4460]
Feedback for 'Selecting a persister' https://docs.particular.net/persistence/selecting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/selecting.md

Should [MongoDB](https://docs.particular.net/persistence/mongodb/) be listed here as well?

**Comment by mauroservienti** [comment]
It's now available in the [section chart](https://docs.particular.net/persistence/selecting#persister-decision-chart)
