### ISSUE TITLE
Feedback: 'NServiceBus Packages Versions'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4488]
Feedback for 'NServiceBus Packages Versions' https://docs.particular.net/nservicebus/upgrades/all-versions

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/all-versions.md

This file (the include it's using) is auto-generated and doesn't really require `reviewed` metadata.
Consider removing `reviewed` metadata from the file, assuming docs engine can support that.

**Comment by danielmarbach** [comment]
I did a quick draft PR and removed the date https://github.com/Particular/docs.particular.net/pull/4632/files

Seems to pass validation but I do not know what the consequences are.

**Comment by danielmarbach** [comment]
It seems if no review date is present we use `DateTime.MinValue` see https://github.com/Particular/DocsEngine/blob/master/src/ParticularDocsCore/Reviewed/ReviewedRenderer.cs#L42

which then renders as `Never`

![image](https://user-images.githubusercontent.com/174258/71180777-2543b880-2273-11ea-8d86-7ed75693dea1.png)

@DavidBoike would it make sense to introduce a hard requirement to have a review date as a integrity test and then have another metadata that allows a page to be marked as `mostly-auto-generated` or something similar?

**Comment by danielmarbach** [comment]
or is it not worth the hassle?

**Comment by DavidBoike** [comment]
You could also make reviewed required so that content generation test fails.

**Comment by danielmarbach** [comment]
@DavidBoike I did execute your suggestion as a PR against the docs engine. Added you as a reviewer

**Comment by danielmarbach** [comment]
PR merged. Review date is now mandatory. This seems to be enough. Closing
