### ISSUE TITLE
Saga-audit article fix required

### ISSUE THREAD

**Issue by aleksandr-samila** [Particular/docs.particular.net#4491]
Related to [Weekly legacy doco review - 2019-09-09](https://github.com/Particular/DeveloperExperience/issues/531)
and to https://docs.particular.net/servicecontrol/plugins/saga-audit article.

This headers duplication
![image](https://user-images.githubusercontent.com/5980232/64562218-30727880-d355-11e9-9eab-28134f57a3b9.png)
looks a bit weird

**Comment by aleksandr-samila** [comment]
PR with a possible fix was created

**Comment by SeanFeldman** [comment]
Alternative PR: https://github.com/Particular/docs.particular.net/pull/4493

**Comment by SeanFeldman** [comment]
Fix deployed
![image](https://user-images.githubusercontent.com/1309622/64565876-f2079a00-d311-11e9-9a43-f8a1215f37d5.png)
