### ISSUE TITLE
Last modified date is calculated incorrectly

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#4494]
Feedback for 'Configure the ServiceControl URI' https://docs.particular.net/servicecontrol/setting-custom-hostname

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/setting-custom-hostname.md

The document stated the last update was made 2 months ago. The `reviewed` date did not agree with that statement. Last update was on 2017-11-09. Is there an issue with the docs engine?

**Comment by danielmarbach** [comment]
I just rechecked

The review date says `reviewed: 2019-09-09` and the doco page says `Last modified 3 months ago` which is correct. Maybe a caching issue. At least it seems to work on my end. Closing for now
