### ISSUE TITLE
Feedback: 'Managing ServiceControl Audit instances via PowerShell' Wrong parameter name

### ISSUE THREAD

**Issue by eliasgrueninger** [Particular/docs.particular.net#4500]
Feedback for 'Managing ServiceControl Audit instances via PowerShell' https://docs.particular.net/servicecontrol/audit-instances/installation-powershell

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/audit-instances/installation-powershell.md

The parameter 'RemoteAddress' on Add-ServiceControlRemote is wrong. It sould be 'RemoteInstanceAddress' dependent on Get-Help Add-ServiceControlRemote

**Comment by DavidBoike** [comment]
@eliasgrueninger 	I talked to @mikeminutillo 	and he thinks you are probably correct, but he will double-check when he returns to the office later this week.

Thanks for the catch!

**Comment by mikeminutillo** [comment]
Fixed in https://github.com/Particular/docs.particular.net/commit/7ccc0b45b62a39a48817b2038322dd27390183ba

This file was the only one where this parameter was incorrect

Thanks @eliasgrueninger
