### ISSUE TITLE
Feedback: 'Message signing using the pipeline'

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#4535]
Feedback for 'Message signing using the pipeline' https://docs.particular.net/samples/pipeline/message-signing/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/pipeline/message-signing/sample.md

- Why is that sample discarding messages that are deemed to have an incorrect signature. When there is a misconfiguration you now have data loss
- Second, yes, this is signing but this is not signing to verify the originator. Its only use is to verify the body hasn't been tampered.
- I think the line ` in order to validate that a sender of a message is valid.` can be improved.
- Signing isn't including header data.

**Comment by danielmarbach** [comment]
The first bullet is addressed with this warning

> Consuming the message in this manner effectively deletes it. If an upstream message source were to begin accidentally signing messages incorrectly, the message would still be consumed, which would result in message loss. It is probably a good idea to audit these messages in some way.


> Second, yes, this is signing but this is not signing to verify the originator. Its only use is to verify the body hasn't been tampered.

ok so what is your suggestion then? Change the title of the page? Something else

> in order to validate that a sender of a message is valid.

any suggestions?

> Signing isn't including header data.

Yes and that could be ok given that samples are not complete and are here to demonstrate a point but can't be directly used for prod. So we either make it more clear that only the body is "signed" or we change the sample to also show the header being taken into account

Happy to give it as stab if needed

**Comment by ramonsmits** [comment]
The only thing is that I don't like calling this "signing" as described here https://en.wikipedia.org/wiki/Digital_signature

This is only a checksum to validate if the body is either partially or incorrectly send/received not to validate the authenticity.

Regarding the headers, I think it should be a warning at the top of the document that contains the sample its limitations.

Its hard to include the headers unless there is some. Get all keys+values and get a signature from that and add that the header collection. That would be the only transport agnostic way of adding a signature from the headers.

**Comment by danielmarbach** [comment]
I'm not an expert on this topic and still if you do some googling you stumble over https://tools.ietf.org/id/draft-cavage-http-signatures-10.html which seems to indicate that even HTTP uses signing in relation to signatures as the lingo. So this article doesn't seem a contradiction to that.

I do believe this sample has the necessary warnings and caveats listed well enough to not indicate or sell this as a perfect approach to achieve things. I don't believe adding another warning to the top of the page helps in any way. I'm closing this issue
