### ISSUE TITLE
Adding a section about using puppet for automating installation and configuration of servicecontrol

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#4539]
Would it be possible to add a section about this puppet module ( https://forge.puppet.com/tragiccode/nservicebusservicecontrol ) which can be used to automate the installation and configuration of servicecontrol?

**Comment by dvdstelt** [comment]
Hi @TraGicCode. Do you mean a paragraph on [this page](https://docs.particular.net/servicecontrol/installation), for example?

**Comment by TraGicCode** [comment]
That seems like a reasonable place to put it.  Just some indication that there is an open source puppet module that automates the installation and configuration of service control for companies using puppet and wanting to reduce the effort and overhead associated with setting up and maintaining servicecontrol across their enterprise

**Comment by mauroservienti** [comment]
Raised https://github.com/Particular/docs.particular.net/pull/4586 to tackle this.
