### ISSUE TITLE
Feedback: 'ASP.NET Core Dependency Injection Integration'

### ISSUE THREAD

**Issue by valeriob** [Particular/docs.particular.net#4576]
Feedback for 'ASP.NET Core Dependency Injection Integration' https://docs.particular.net/samples/dependency-injection/aspnetcore/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/dependency-injection/aspnetcore/sample.md

Without downloading the source code it's not clear that some more code is needed as glue between nservicebus and microsoft DI, in particular the project NServiceBus.Extensions.DependencyInjection 
How is it supposed to be used ? copy pasted on every project, mantaining a custom library ?
Why is'nt itself a nuget package ?

Thanks

**Comment by SeanFeldman** [comment]
@valeriob it's going to be a package.
The sample will be changed accordingly once the package work is finalized.
WIP: https://github.com/Particular/docs.particular.net/pull/4575

**Comment by valeriob** [comment]
awesome !

**Comment by SeanFeldman** [comment]
`NServiceBus.Extentions.Hosting` 1.0.0 is released. Please see [announcement](https://discuss.particular.net/t/nservicebus-extensions-hosting-1-0-0-major-release-available/1481) post.
