### ISSUE TITLE
sample for NServiceBus.Extensions.Hosting ?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#4600]
Feedback for 'NServiceBus.Extensions.Hosting' https://docs.particular.net/nservicebus/hosting/extensions-hosting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/extensions-hosting.md

**Comment by SimonCropp** [comment]
idealy one for web and one for windows service

**Comment by WilliamBZA** [comment]
Thanks @SimonCropp. We've got a sample ready to go in [this](https://github.com/Particular/docs.particular.net/tree/netcore-3-for-di-sample) branch, but our build infrastructure doesn't let us build it yet.

**Comment by SimonCropp** [comment]
@WilliamBZA why are you blocked? https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices and https://www.nuget.org/packages/NServiceBus.Extensions.Hosting both target netstandard 2.0. so you shouldnt need netcore3 or VS2019

**Comment by SimonCropp** [comment]
shouldnt this be removed https://github.com/Particular/docs.particular.net/tree/15089a24d0467fb276af57e4dc7cbe7f05185dfd/samples/dependency-injection/aspnetcore/Core_7.2/NServiceBus.Extensions.DependencyInjection  ? and replaced with the NServiceBus.Extensions.Hosting package

**Comment by timbussmann** [comment]
@SimonCropp the main goal of the `NServiceBus.Extensions.Hosting` package is to provide NServiceBus integration with ASP.NET Core 3 and unfortunately, our build infrastructure isn't able to handle this as of now (but it's in the pipeline). Since the hosting package doesn't work with ASP.NET Core 2, we still need to document DI integration somehow.

While the generic host can be used for other scenarios too, that hasn't been the main focus and therefore there are no samples for those uses cases provided yet. That's certainly something which is in our backlog but it requires a bit more time to verify and test those usage scenarios (and provide samples along with that).

**Comment by SimonCropp** [comment]
> the main goal of the NServiceBus.Extensions.Hosting package is to provide NServiceBus integration with ASP.NET Core 3 

That may have been the goal. but arguably is is just as valuable to provide support for the `Microsoft.Extensions.Hosting.WindowsServices` package. since every endpoint hosted as a windows service could leverage this approach. and this package does no depend on netcore3

**Comment by timbussmann** [comment]
that is true but these use cases haven't been a priority so far (as hosting NSB in a windows service isn't blocked by not supporting the generic host). I expect more samples for the extensions.hosting package to come up over time.

**Comment by TraGicCode** [comment]
@WilliamBZA @timbussmann @SimonCropp 

I had no issues running NServiceBus 7.x in .NET Core 3.x using the Microsoft.Extensions.Hosting.WindowsService nuget package.  Definitely worth getting prioritized as most NServiceBus users ( or .net users in general ) are wanting to take baby steps on getting to containers and this is that necessary baby step


Program.cs
```
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Nest;
using NLog.Extensions.Hosting;
using NServiceBus;


public static class Program
{
    public static async Task Main()
    {
        // Works windows services
        await CreateHostBuilder().Build().RunAsync();
 

    }


    public static IHostBuilder CreateHostBuilder() =>
        Host.CreateDefaultBuilder()
            .UseWindowsService()
            .ConfigureLogging(logging =>
            {
                logging.ClearProviders();
                logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
            })
            .UseNLog()
            .UseMicrosoftLogFactoryLogging()
            .ConfigureServices(ConfigureServices)
            .UseNServiceBus(ctx =>
            {
                var endpointConfiguration = new EndpointConfiguration("ProductCatalog.Host");
                
                // Configure endpoint here....

                return endpointConfiguration;
            });

    private static void ConfigureServices(HostBuilderContext hostBuilderContext, IServiceCollection services)
    {
        services.AddNPoco();
    }
}
```

csproj
```
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.0" />
    <PackageReference Include="NLog.Extensions.Hosting" Version="1.6.1" />
    <PackageReference Include="NServiceBus.Extensions.Hosting" Version="1.0.0" />
    <PackageReference Include="NServiceBus.MicrosoftLogging.Hosting" Version="1.3.0" />
  </ItemGroup>


  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

```

**Comment by SimonCropp** [comment]
no longer need this

**Comment by danielmarbach** [comment]
We have recently created a sample that shows how to leverage the GenericHost with Windows Service and console lifetime

https://docs.particular.net/samples/hosting/generic-host/
