### ISSUE TITLE
NServiceBus.Extensions.Hosting: how to do a publish at startup

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#4601]
it is not clear how to get access to the  `IMessageSession` or `IEndpoitnInstance` at startup. For example to do a publish

Using `IMessageSession` in an `IHostedService` gives 

> The message session can only be used after the endpoint is started.'

Using `IEndpoitnInstance` in an `IHostedService` gives 

> Unable to resolve service for type 'NServiceBus.IEndpointInstance' 

Feedback for 'NServiceBus.Extensions.Hosting' https://docs.particular.net/nservicebus/hosting/extensions-hosting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/extensions-hosting.md

**Comment by WilliamBZA** [comment]
https://github.com/Particular/docs.particular.net/pull/4598 has been merged, does that make it clearer or do you think we should add something more explicit?

**Comment by SimonCropp** [comment]
@WilliamBZA not really. since we are in a windows service and there is no `ConfigureWebHostDefaults`

**Comment by WilliamBZA** [comment]
`ConfigureWebHostDefaults` is being used as an example there. The key point is that the order of the `UseX` calls are sensitive to ordering, so `UseNServiceBus` must be called before any other services that require an instance of `IMessageSession`.

**Comment by SimonCropp** [comment]
@WilliamBZA so back to the specific use case: how do i do a publish at startup?

**Comment by WilliamBZA** [comment]
Inject an `IMessageSession` inside an `IHostedService` after making sure that `UseNServiceBus` is called before the `UseX` that contains the `IHostedService` that you're trying to publish within.

**Comment by SimonCropp** [comment]
@WilliamBZA that doesnt seem to work for me. can you point me to the sample you are using to verify these scenarios, and i will modify to to try and narrow down the problem

**Comment by SimonCropp** [comment]
here is what i have hacked together https://github.com/SimonCropp/NsbHostingRaceCondition

**Comment by andreasohlund** [comment]
I think I have found the issue https://github.com/SimonCropp/NsbHostingRaceCondition/pull/1 

In short: I think all hosted services are created and then started so injecting the session won't work, instead I resolved it from `IServiceProvider`

**Comment by timbussmann** [comment]
The problem is that the generic host resolves all `IHostedService` implementations together before starting them up one after another. This means that the `IMessageSession` available yet as the NServiceBus hosted service hasn't been started yet.

Resolving the message session from the service provider at within `Start` seems to be the workaround for now (as shown in @andreasohlund linked PR to your repro). I'm not sure there is a decent solution for this generic host limitation available. Any ideas?

**Comment by mauroservienti** [comment]
Hi @SimonCropp 

one option is to use the `IHostApplicationLifetime` interface. Take a look at the following snippet:

```
var host = new HostBuilder()
    .UseNServiceBus(hostBuilder => 
    {
        var config = new EndpointConfiguration("ConsoleSample");
        config.UseTransport<LearningTransport>();
        config.SendFailedMessagesTo("error");

        return config;
    })
    .Build();

var hostApplicationLifetime = (IHostApplicationLifetime)host.Services.GetService(typeof(IHostApplicationLifetime));
hostApplicationLifetime.ApplicationStarted.Register(() => 
{
    var messageSession = (IMessageSession)host.Services.GetService(typeof(IMessageSession));
    messageSession.SendLocal(new AMessage()).GetAwaiter().GetResult();
});

await host.StartAsync();
``` 

Unfortunately the application startup events do not support async/await hence the code gets ugly pretty quickly,

**Comment by SimonCropp** [comment]
thanks for the workarounds people. looks like that avoiding some kind iof hacky service lookup is unavoidable. i will close this

**Comment by timbussmann** [comment]
@SimonCropp yes, unfortunately, some manual service provider access is hard to avoid at the moment. If you definitely want to use ctor injection, you can try an approach like used here: https://github.com/timbussmann/Community.NServiceBus.WebHost/blob/master/src/Community.NServiceBus.WebHost/WebHostCompatibleMessageSession.cs just without the blocking logic (that could cause a deadlock) but that also doesn't feel like a good solution either.
