### ISSUE TITLE
Register multiple instances of same type with NServiceBus built in container

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#4608]
It looks like this is not possible but figured i would ask here.  How can i user the NServiceBus built in container in order to register multiple instances of the same type in the container ( also known as named instances )?

**Comment by mauroservienti** [comment]
@TraGicCode as far as i can tell there is no way as you don't have direct access to the internal default container, other then through the `IBuilder` interface that doesn't expose that functionality.

One option could be to configure the endpoint to use a different container, with support for named registrations, and directly register into the container those components.

**Comment by udidahan** [comment]
Could you explain a bit more about what you were trying to achieve?
It would be interesting to hear the back-story.

Thanks!
