### ISSUE TITLE
Feedback: 'Multi-Site Deployments'

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#4685]
Feedback for 'Multi-Site Deployments' https://docs.particular.net/nservicebus/gateway/multi-site-deployments

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/gateway/multi-site-deployments.md

The page still contains Gateway configuration snippets that rely on XML configuration files.

**Comment by danielmarbach** [comment]
@mauroservienti I raised https://github.com/Particular/docs.particular.net/pull/4710 to hopefully address this feedback. Technically the app.config approach is still supported but deprecated. In the interest of moving customers towards the code first approach I remove the XML samples as you suggested
