### ISSUE TITLE
Feedback: 'NServiceBus.Extensions.Hosting'

### ISSUE THREAD

**Issue by StevenLiekens** [Particular/docs.particular.net#4686]
Feedback for 'NServiceBus.Extensions.Hosting' https://docs.particular.net/nservicebus/hosting/extensions-hosting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/extensions-hosting.md

Please add instructions for configuring NServiceBus to use ILoggerFactory (Microsoft.Extensions.Logging) in .NET Core projects.

``` csharp
var host = Host.CreateDefaultBuilder()
    .UseNServiceBus(hostBuilderContext =>
    {
        var endpointConfiguration = new EndpointConfiguration("MyEndpoint");
        // insert logging instructions here
        return endpointConfiguration;
    })
    .Build();
```

**Comment by danielmarbach** [comment]
Hi Steven

The logging integration is currently still part of NServiceBus Extensions managed by the community. See https://github.com/NServiceBusExtensions/NServiceBus.MicrosoftLogging

The sample shows how to use it

https://github.com/NServiceBusExtensions/NServiceBus.MicrosoftLogging/blob/master/src/Sample.Hosting/Program.cs#L37

I would recommend to use that for now. Does that help?

**Comment by StevenLiekens** [comment]
Thanks Daniel

I had a few problems getting this to work. I couldn't find the `UseMicrosoftLogFactoryLogging` extension method after installing the _MicrosoftLogging_ package. It turns out there is an additional package that needs to be installed.

> dotnet add package NServiceBus.MicrosoftLogging --version 1.3.1
> **dotnet add package NServiceBus.MicrosoftLogging.Hosting --version 1.3.1**

This was not very obvious from the readme or sample code. After installing both packages, the sample works fine in my app.

**Comment by danielmarbach** [comment]
@StevenLiekens I took the liberty to slightly increase the community package doco by sending in https://github.com/NServiceBusExtensions/NServiceBus.MicrosoftLogging/pull/129

**Comment by StevenLiekens** [comment]
Thanks again, closing as resolved.
