### ISSUE TITLE
Feedback: SqlTransport

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#4689]
From @gbiellem 

The upgrade guide for SQL Transport 5.x to 6.x is great . I do think the main SQL Transport page needs some tweaking though, in the upgrade guide it recommends using NServiceBus.Transport.SqlServer for new projects. That's not clear here: https://docs.particular.net/transports/sql/ and the nuget ref at the top is to the old package only

**Comment by bording** [comment]
This should be addressed now. The 6.x pages point to NServiceBus.Transport.SqlServer, and the previous versions continue to point to NServiceBus.SqlServer.

**Comment by gbiellem** [comment]
Thanks @bording  and @danielmarbach

**Comment by danielmarbach** [comment]
All the honor belongs to @DavidBoike and @bording 

My only contribution comes from my amazing delegation skills ;)
