### ISSUE TITLE
Feedback: 'Message Mutators'

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#4694]
Feedback for 'Message Mutators' https://docs.particular.net/samples/messagemutators/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/messagemutators/sample.md

Seems `RegisterMessageMutator` is not present in 6.0.0 but introduced in a later version. The doco is not reflecting the minimal requires 6.x version.

That is probably due to the `csproj` using 6.* and not 6.0.*

- https://github.com/Particular/docs.particular.net/blob/master/samples/messagemutators/Core_6/Sample/Sample.csproj#L9

**Comment by danielmarbach** [comment]
According to https://docs.particular.net/nservicebus/upgrades/supported-versions#nservicebus only the 6.5 version of the 6.x version is still supported. 6 is going to be in extended support soon. I see no reason to further clarify things on that doco page under that light. Closing.
