### ISSUE TITLE
Feedback: 'Architectural Principles'

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#4696]
Feedback for 'Architectural Principles' https://docs.particular.net/nservicebus/architecture/principles

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/architecture/principles.md

Video under "How NServiceBus aligns with SOA", from Vimeo, looks like this:

![image](https://user-images.githubusercontent.com/427110/74885585-8f441100-533b-11ea-9866-c8dfd9830513.png)

**Comment by danielmarbach** [comment]
Works in Europe

![image](https://user-images.githubusercontent.com/174258/75167948-6c906e80-5726-11ea-98e8-b00c0cef4fb5.png)

I proxied to the US and it seems to work there as well. Maybe a temporary glitch?

**Comment by danielmarbach** [comment]
Verified with @DavidBoike seems to work now
