### ISSUE TITLE
Feedback: 'Azure Blob Storage Data Bus' - Support Azure.Identity

### ISSUE THREAD

**Issue by kwaazaar** [Particular/docs.particular.net#4698]
Feedback for 'Azure Blob Storage Data Bus' https://docs.particular.net/nservicebus/messaging/databus/azure-blob-storage

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/databus/azure-blob-storage.md

Databus should support Azure.Identity and accept a TokenCredential, instead of a connectionstring, so we can use it with managed service identities (aadpodidentity on AKS).

**Comment by SeanFeldman** [comment]
Are you referring to this feature request? https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/61

**Comment by SeanFeldman** [comment]
Closing in favour of https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/61
