### ISSUE TITLE
Document missing NHibernate concepts

### ISSUE THREAD

**Issue by rosieks** [Particular/docs.particular.net#471]
NHibernate persistence create automatically tables in database. It would be nice to have more documentation about this feature:

* When this structure is created (eg. when start from VS, during installation of NServiceBus.Host)
* How it can be disabled: https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/SharedConfig.cs#L26
* How to generate script to alter tables in case when I have changed structure of Saga
* How to provide custom mappings and various attributes: TableName, LockMode, RowVersion.

**Comment by SimonCropp** [comment]
addressed in  

 * http://docs.particular.net/nservicebus/nhibernate/#controlling-schema
 * http://docs.particular.net/samples/nhibernate/custom-mappings/
