### ISSUE TITLE
Feedback: 'NServiceBus.Extensions.Logging'

### ISSUE THREAD

**Issue by nikolic-bojan** [Particular/docs.particular.net#4765]
Feedback for 'NServiceBus.Extensions.Logging' https://docs.particular.net/nservicebus/logging/extensions-logging

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/logging/extensions-logging.md

Hi, is it possible to have some sample app setup for Worker Service in Core 3.1?

You gave a sample setup 
```NServiceBus.Logging.LogManager.UseFactory(new ExtensionsLoggerFactory(extensionsLoggingFactory));```

Where did that ```extensionsLoggingFactory``` came from?
Do you setup this in Program.cs? How?

I feel like I am missing the obvious.
Any kind of hint would be great. Thank you!

**Comment by ramonsmits** [comment]
@nikolic-bojan Please see the referenced sample to see where it originates: https://docs.particular.net/samples/logging/extensions-logging/

In the sample it is using the NLog factory but it can also be the Microsoft.Extensions.Logging provider:

```c#
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder
        .AddFilter("Microsoft", LogLevel.Warning)
        .AddFilter("System", LogLevel.Warning)
        .AddFilter("LoggingConsoleApp.Program", LogLevel.Debug)
        .AddConsole()
        .AddEventLog();
});
ILogger logger = loggerFactory.CreateLogger<Program>();
logger.LogInformation("Example log message");
```

**Comment by nikolic-bojan** [comment]
@ramonsmits 
Thank you!
I missed the obvious part as it is somewhat different between 2.x and 3.x.
