### ISSUE TITLE
Feedback: 'Simple AmazonSQS Transport usage'

### ISSUE THREAD

**Issue by jkodroff** [Particular/docs.particular.net#4791]
Feedback for 'Simple AmazonSQS Transport usage' https://docs.particular.net/samples/sqs/simple/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/sqs/simple/sample.md

You probably don't want to encourage the use of access keys for programmatic access since it's bad security practice.  Most AWS users will have enough context to understand how the AWS SDK credentials chain works.

Instead, I think the user should be referred here: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html

For a similar example from another product (which used the AWS Go SDK, but same principles apply): https://www.terraform.io/docs/providers/aws/index.html#authentication

**Comment by ramonsmits** [comment]
@jkodroff To better understand your feedback you are suggestion we should modify those samples to use credential files instead?

**Comment by jkodroff** [comment]
@ramonsmits My apologies - I thought the page I was reading were the _general directions_ on how to use SQS transport, but it's not - it's a sample project.  Closing this case - sorry to waste your time.
