### ISSUE TITLE
Idempotent Handlers: Inform the user idempotency also means resending any possilbly already sent messages

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#4795]
Feedback for 'Accessing and modifying data from a message handler' https://docs.particular.net/nservicebus/handlers/accessing-data

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/handlers/accessing-data.md

I'm not sure if this page is the best place to put this but i think it would be really helpful to make sure people understand that when it comes to making a handler idempotent this also means ensuring messages that might or might not have already been sent get sent again.

**Comment by SzymonPobiega** [comment]
@TraGicCode Thanks for pointing this out. I'll take a stab at reorganizing this page.

**Comment by TraGicCode** [comment]
> @TraGicCode Thanks for pointing this out. I'll take a stab at reorganizing this page.

No rush take your time. Thanks!
