### ISSUE TITLE
Using NServiceBus in a ASP.NET Web Application

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#48]
http://www.particular.net/articles/using-nservicebus-in-a-asp.net-web-application

http://particular.net/Admin/Contents/Edit/243
http://particular.net/Contents/Item/Preview/243

- [ ] Review content
- [x] Update code snippets
- [ ] Refresh Images
- [ ] We should add some comments about the problems that can be faced when hosting under IIS

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/web/asp-web-application/

re 

> We should add some comments about the problems that can be faced when hosting under IIS

Nope. this is a sample page. IIS complexities would span any sample that relates to IIS so as to avoid duplication that should be in its own page. Feel free to raise a different issue to track that.
