### ISSUE TITLE
Unobtrusive Mode vs Message Conventions

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#480]
Documentation makes reference to "unobtrusive mode".
Need to clarify that there's nothing that is unobtrusive. There are message conventions feature and there is `INeedInitialization` feature, that allows drop-in changes instead of config changes.

Documents such as 
- [How to Centralize All Unobtrusive Declarations FAQ](http://docs.particular.net/nservicebus/how-do-i-centralize-all-unobtrusive-declarations)
- [Unobtrusive Sample](http://docs.particular.net/nservicebus/unobtrusive-sample)
- [InvalidOperationException in Unobtrusive Mode](http://docs.particular.net/nservicebus/invalidoperationexception-in-unobtrusive-mode)

**Comment by mauroservienti** [comment]
@SeanFeldman @johnsimons given that:

> Agree to stop using unobtrusive mode definition and refer to it for what it is, conventions

is a deep change that touches a lot of things should we move this to requirements? I agree with the general idea.

**Comment by SeanFeldman** [comment]
It's already there, but no details. This will be redundant if idea of removing message convention all together is a go: https://github.com/Particular/Requirements/issues/165

**Comment by mauroservienti** [comment]
I'd say leave this as is in the backlog waiting for the requirement.

**Comment by SimonCropp** [comment]
done
