### ISSUE TITLE
Feedback: 'Report metrics to Azure Monitor Application Insights'

### ISSUE THREAD

**Issue by robertregnier** [Particular/docs.particular.net#4806]
Feedback for 'Report metrics to Azure Monitor Application Insights' https://docs.particular.net/samples/logging/application-insights/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/logging/application-insights/sample.md

This sample is out of date as I am getting warnings that TelemetryClient() is obsolete.  Please update to version 2.13 of Microsoft.ApplicationInsights and update the sample.

**Comment by mikeminutillo** [comment]
Thanks @robertregnier. I'll take a look.

**Comment by mikeminutillo** [comment]
Updated. Please take a look @robertregnier

**Comment by robertregnier** [comment]
Looking better now with no more code warnings, thanks Mike.   Although I am able to view in application insights the Trace messages that I put in, I am also seeing Custom Event messages from the probe.  The sample description describes how to view the metrics collected by the probe in app insights Metrics but I have not been able to see these metrics anywhere.  Any guidance here would be appreciated.

**Comment by robertregnier** [comment]
> Looking better now with no more code warnings, thanks Mike. Although I am able to view in application insights the Trace messages that I put in, I am also seeing Custom Event messages from the probe. The sample description describes how to view the metrics collected by the probe in app insights Metrics but I have not been able to see these metrics anywhere. Any guidance here would be appreciated.

Actually, things are looking good now on my end after a logic tweak.  All good :-)
