### ISSUE TITLE
Restructure ServiceMatrix documentation into stand-alone topics

### ISSUE THREAD

**Issue by dprothero** [Particular/docs.particular.net#482]
@indualagarsamy and I discussed shortening the Getting Started tutorial and then taking the other topics and making them stand-alone topics rather than part of the tutorial (requiring the user to have built the entire sample solution leading up to the next topic).

The basic plan is to leave Installation under the Getting Started heading.

Then take "Send and Receive with ServiceMatrix V2.X" and pare it down to a good introductory sample  and orientation on how to work with SM. Leave it under the Getting Started heading and re-title it something like "Introduction to ServiceMatrix". Pull out any advanced topics (e.g. Selecting Persistence) into stand-alone topics to be put under the "Using ServiceMatrix" heading.

Take the remaining topics currently under Getting Started and move them under Using ServiceMatrix. Re-work them them to be stand alone so they don't require the user to have gone through the entire tutorial.

So the basic outline will probably end up something like this:

#### Licensing ServiceMatrix

@dannycohen FYI

**Comment by SimonCropp** [comment]
closing this in the light of https://github.com/Particular/Requirements/issues/212
