### ISSUE TITLE
'Using NServiceBus in Azure Functions' : upgrade and republish to nuget.

### ISSUE THREAD

**Issue by grleachman** [Particular/docs.particular.net#4858]
Feedback for 'Using NServiceBus in Azure Functions' https://docs.particular.net/samples/azure/functions/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/azure/functions/index.md

We are writing some code that is almost ready to use.
We are about to put this into production, but I'd like to know if you are able to 
1. add back your pre-release version of NServiceBus.AzureFunctions.ServiceBus onto NuGet.
1. update the package to reference NServiceBus.Transport.AzureServiceBus 1.4.0 or later..

This would help resolve a package conflict with Microsoft.Azure.ServiceBus 4.1.1

Currently NServiceBus.Transport.AzureServiceBus 1.2.1 which is in the package, required Microsoft.Azure.ServiceBus < 4.0.0

**Comment by SeanFeldman** [comment]
@grleachman, thank you for your interest in Azure Functions.

The packages used in the sample are experimental packages and are not intended for production use.
We are going to launch a public preview of Azure Functions with production support and if you're interested in that, could you please contact support with the reference to this issue? Thank you.

**Comment by SeanFeldman** [comment]
@grleachman regarding NuGet question

> 1. add back your pre-release version of NServiceBus.AzureFunctions.ServiceBus onto NuGet.

This package has never been published to nuget and it will not be as it's not intended for production use. It will be replaced by the preview package I've referred to in my previous comment.

**Comment by grleachman** [comment]
I definitely have a dll .. 0.1.1 sha e8b7a732, dated 23/09/2019 22:00 
https://docs.particular.net/samples/azure/functions/service-bus/
points to
https://www.nuget.org/packages/NServiceBus.AzureFunctions.ServiceBus/
but clearly it's not there.

perhaps we built it locally. which has inspired me to just download and see if I can compile it locally with the upgraded package :) thanks.

@SeanFeldman very much hope that will come out soon (weeks rather than months)

**Comment by SeanFeldman** [comment]
@grleachman, the package was only published to MyGet public feed, which was included in the sample project you could have downloaded. That could be cached on your machine and resolved. NuGet feed never had that package 🙂

The preview will take some time. I cannot comment on wherever it will be weeks or months. A month is a few weeks. So are a few months. But we're working on it and that's why I've suggested raising a support case to have the account information on the list of the interested customers.

Thank you for the demonstrated interest and enthusiasm. It's really great to see customers are looking forward to this addition. You won't be disappointed.

**Comment by grleachman** [comment]
Grand. yes, and as it happens was just going to give the correction, I found the reference to MyGet.
Looking forward to a release, and support case raised.

**Comment by grleachman** [comment]
I don't suppose you'd be willing to push a 0.1.2 
on myget 
with a reference to NServiceBus.Transport.AzureServiceBus 1.4.0
:)

**Comment by SeanFeldman** [comment]
Love the persistence 🙂
Let's switch to a support channel to get more details. Unless you're OK to share all the info here.

**Comment by SeanFeldman** [comment]
Closing this issue as an experimental package will not be updated. Instead, we'll be releasing a package with support. For details, please monitor the announcements on the [public forum](https://discuss.particular.net/).

Anyone interested in more information about the soon upcoming support for Azure Functions can [contact support](https://particular.net/support) for more details. Thank you.
