### ISSUE TITLE
list reasons why the distributor and workers need to be on separate machines

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#486]
@andreasohlund since you know these very well, can you please at least do a v1 of this article

**Comment by andreasohlund** [comment]
@janovesk would you like to take a stab at this one?

**Comment by janovesk** [comment]
Sure.

**Comment by SimonCropp** [comment]
given the current status of the distributor moving forward i am closing this one. please feel free to open a PR if u think it is still work doing
