### ISSUE TITLE
Feedback: 'Tutorial Saga Timeouts'

### ISSUE THREAD

**Issue by mikedevbo** [Particular/docs.particular.net#4865]
Feedback for 'Tutorial Saga Timeouts':
https://docs.particular.net/tutorials/nservicebus-sagas/2-timeouts/:

Location in GitHub:
https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-sagas/2-timeouts/Snippets/Core_7/BuyersRemorseTimeoutHandling/BuyersRemorseTimeoutHandling.cs

Should the comment be in this place?
https://github.com/Particular/docs.particular.net/blob/2a29879050eac8146dd10d20895c20754fb4db0f/tutorials/nservicebus-sagas/2-timeouts/Snippets/Core_7/BuyersRemorseTimeoutHandling/BuyersRemorseTimeoutHandling.cs#L28

It's visible in doc site:
https://docs.particular.net/tutorials/nservicebus-sagas/2-timeouts/

It's may suggest to do use database directly in Saga logic.

It does not occur in solution implementation:
https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-sagas/2-timeouts/Solution/Sales/BuyersRemorsePolicy.cs

**Comment by dvdstelt** [comment]
@mikedevbo Again, you are on 🔥 

Thanks for noticing and reporting this. The very descriptive issue really helps!
One should never store state in the database unless it's in the saga state. And you're right, it's not included in the solution implementation itself. So I decided to remove it.

Can you review the PR and tell me if this would fix your issue, or if you'd like to see something else? And note the branch name! ;-)

**Comment by mikedevbo** [comment]
Done :smile: The branch name :point_right: :muscle: :smile:
