### ISSUE TITLE
[Express] is not relevant if endpoint == non durable

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#487]
Update http://docs.particular.net/nservicebus/how-do-i-specify-store-forward-for-a-message to state that [Express] is not relevant if endpoint == non durable

**Comment by mauroservienti** [comment]
@johnsimons is this somewhat related to #546?
/cc @ramonsmits

**Comment by andreasohlund** [comment]
Yes, seems to be exactly that. Perhaps also link to http://docs.particular.net/nservicebus/connection-strings-samples#msmq since that explains how to tweak the connection string in msmq to have the endpoint use non tx queues

**Comment by mauroservienti** [comment]
Thanks @andreasohlund, I'll close this one since the PR is merged and merge the relevant information with #546
