### ISSUE TITLE
Possible outdated documentation

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#4887]
https://docs.particular.net/nservicebus/hosting/

There is a call out of the following.

![image](https://user-images.githubusercontent.com/6224270/85191010-ea065e80-b282-11ea-8ce5-4811d15f5bb2.png)

If i'm not mistaken this is no longer correct.  Can someone confirm this?

**Comment by danielmarbach** [comment]
@TraGicCode you are correct. I remove the 

> By default...

part. See https://github.com/Particular/docs.particular.net/pull/4890

Thanks for bringing this up!
