### ISSUE TITLE
Injecting the Bus into ASP.NET MVC Controller

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#49]
http://www.particular.net/articles/injecting-the-bus-into-asp.net-mvc-controller

http://particular.net/Admin/Contents/Edit/300
http://particular.net/Contents/Item/Preview/300

- [ ] Review content
- [ ] Update code snippets
- [ ] Sample still refers to MVC3 
- [ ] we need a full article on IoC concepts especially to help people integrate their own IoC container with NSB

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/web/asp-mvc-injecting-bus/
