### ISSUE TITLE
Mention SubscriptionNameShortener on the Azure Service Bus Transport page

### ISSUE THREAD

**Issue by Jmaharman** [Particular/docs.particular.net#4911]
I think that there should be a call out in the documentation of NServiceBus somewhere that Azure has a limit of 50 characters and that you should call SubscriptionNameShortener to resolve this issue for names that are over 50 characters.

https://docs.particular.net/transports/azure-service-bus/

I found an implementation that hashes the name by searching through the organisations code and used that.

https://github.com/Particular/docs.particular.net/blob/master/Snippets/ASBS/ASBS_1/Usage.cs

**Comment by SeanFeldman** [comment]
@Jmaharman it's documented here https://docs.particular.net/transports/azure-service-bus/configuration#entity-creation for both subscriptions (`SubscriptionNameShortener()`) and rules (`RuleNameShortener()`).

**Comment by Jmaharman** [comment]
That's great as a top level, but while I was reading the documentation to see how to implement events, I was seeing warnings regarding the Azure Service Bus Legacy implementation, and needing to configure certain things for that. Where as the newer version seemed to be mentioned as if "it just works", which it does as long as your full type names aren't longer than 50 characters.

If you don't agree that's fine, feel free to close the comment.

**Comment by SeanFeldman** [comment]
The legacy transport used to validate everything prior to passing it to the broker and when a subscription/rule name longer than 50 characters or with invalid entries was found, a custom exception was thrown. With a custom exception in place, it was possible to point to the specific configuration API. The current transport doesn't pre-validate entity name length and characters. Rather, the name is used as-is and the broker throws an exception. Configuration API exposes very few options amongst which shortening APIs as well. Compared to the [legacy API](https://docs.particular.net/transports/azure-service-bus/legacy/configuration/full) where finding a single option was quite a challenge, the new transport configuration API has a small surface area and easy to navigate.

The title of the issues says "Mention SubscriptionNameShortener on the Azure Service Bus Transport page". Which is handled on the [configuration page](https://docs.particular.net/transports/azure-service-bus/configuration) of the transport. Calling out entity naming rules falls out of the transport documentation responsibility, but we do have links to the official Microsoft documentation that has changed over time. With invalid names being on the exception side and not the common scenario and explicit design not to catch/evaluate/throw new exceptions, what would you suggest to help with this issue? Thank you.

**Comment by Jmaharman** [comment]
No-one else seems to be having the problem of realising this, so I guess it's not a problem for others.
