### ISSUE TITLE
Feedback: Mention logging package for .NET Core

### ISSUE THREAD

**Issue by jbogard** [Particular/docs.particular.net#4928]
The .NET Core 3.1 documentation shows hosting and DI, but does not mention how to set up the MS Logging extensions. The sample code does, however.

I think this should be called out even if it's a 3rd-party package from @SimonCropp since it's the only way to get that working today.

**Comment by DavidBoike** [comment]
@jbogard Which page are you talking about?

**Comment by jbogard** [comment]
https://docs.particular.net/samples/netcore-reference/

**Comment by SzymonPobiega** [comment]
The logging integration is mentioned in the https://docs.particular.net/samples/hosting/generic-host/ sample. Although I am not sure if we actually need both of these samples?

**Comment by HEskandari** [comment]
I have noted the usage of the community package on the two samples.

**Comment by HEskandari** [comment]
@SzymonPobiega the second sample was created more as a showcase of NetCore WebApi (for our recently published blog post).

**Comment by DavidBoike** [comment]
I think that resolves this issue. Please reopen if I'm wrong.
