### ISSUE TITLE
Feedback: 'Endpoints multi hosting'

### ISSUE THREAD

**Issue by mwilliams963** [Particular/docs.particular.net#4932]
Feedback for 'Endpoints multi hosting' https://docs.particular.net/samples/hosting/multi-hosting/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/multi-hosting/sample.md

Hello, I am looking to execute Endpoint Multi-Hosting in an ASP.NET CORE 3.x web application.  I have already set up multiple ASP.NET CORE 3.x web applications hosting single endpoints with communication set up by routing to each endpoint.  

**My current setup is as follows:**
https://docs.particular.net/samples/web/send-from-aspnetcore-webapi/
------------------------------------------------

var host = Host.CreateDefaultBuilder()
.UseNServiceBus(context =>
{
var endpointConfiguration = new EndpointConfiguration("Samples.ASPNETCore.Sender");
var transport = endpointConfiguration.UseTransport<LearningTransport>();
transport.Routing().RouteToEndpoint(assembly: typeof(MyMessage).Assembly, destination: "Samples.ASPNETCore.Endpoint");

return endpointConfiguration;
})
.ConfigureWebHostDefaults(c => c.UseStartup<Startup>())
.Build();

However, Multi-Endpoint hosting is addressed as follows:
https://docs.particular.net/samples/hosting/multi-hosting/
------------------------------------------------
IEndpointInstance endpoint1 = null;
IEndpointInstance endpoint2 = null;
try
{
endpoint1 = await StartInstance1().ConfigureAwait(false);
endpoint2 = await StartInstance2().ConfigureAwait(false);

Console.WriteLine("Press '1' to send a message from Instance1 to Instance2");
Console.WriteLine("Press '2' to send a message from Instance2 to Instance1");
Console.WriteLine("Press any key to exit");

while (true)
{
var key = Console.ReadKey();
Console.WriteLine();
var message = new MyMessage();
if (key.Key == ConsoleKey.D1)
{
await endpoint1.Send("Samples.MultiHosting.Instance2", message).ConfigureAwait(false);
continue;
}
if (key.Key == ConsoleKey.D2)
{
await endpoint2.Send("Samples.MultiHosting.Instance1", message).ConfigureAwait(false);
continue;
}
return;
}
}
finally
{
if (endpoint1 != null)
{
await endpoint1.Stop().ConfigureAwait(false);
}
if (endpoint2 != null)
{
await endpoint2.Stop().ConfigureAwait(false);
}
}

------------------------------------------------

I am looking for a way to have a second endpoint constructed and running following the specifications of an ASP.NET CORE 3.x web application.

Please advise. 

Thanks,
Marc Williams

**Comment by kbaley** [comment]
@mwilliams963 For now the NServiceBus.Extensions.Hosting package supports only a single endpoint. There are some suggestions for workarounds [mentioned here](https://github.com/Particular/NServiceBus.Extensions.Hosting/issues/27)
