### ISSUE TITLE
Feedback: 'Hosting endpoints in Docker Linux containers' - deprecated depends_on argument is used

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#4959]
Feedback for 'Hosting endpoints in Docker Linux containers' https://docs.particular.net/samples/hosting/docker/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/docker/sample.md

Docker v3 [no longer supports conditions for `depends_on`](https://docs.docker.com/compose/compose-file/#depends_on) so our docker compose needs to change.

The recommendation is to [do the checking our self in the container or use tools like `wait-for-it`, `dockerize`, or sh-compatible `wait-for`](https://docs.docker.com/compose/startup-order/).

How should we proceed?

**Comment by andreasohlund** [comment]
@danielmarbach proposed a hosted service like shown here https://github.com/Particular/NServiceBus.Extensions.Hosting/pull/73

**Comment by andreasohlund** [comment]
Restart on failure have also been proposed https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y but would work so nicely when running tests though

**Comment by timbussmann** [comment]
given that our transports/persistences are resilient to outages after starting up successfully initially, shouldn't this be a potential new feature to disable the "availability" requirement at endpoint startup time and let the endpoint start without checking transport/persistence connections (should probably be opt-in given that this can also lead to easily miss configuration issues)
