### ISSUE TITLE
Feedback: 'SQL Server Transport Upgrade Version 4 to 5'

### ISSUE THREAD

**Issue by iappert** [Particular/docs.particular.net#4993]
Feedback for 'SQL Server Transport Upgrade Version 4 to 5' https://docs.particular.net/transports/upgrades/sqlserver-4to5

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/upgrades/sqlserver-4to5.md

The template script for creating the `Subscriptions` table is misleading:
The definition of the column `Endpoint` suggests that you can create this column as `Nullable`. Since it is used in a primary key, this does not work for MS Sql Server, tested on 15. When you create the primary key, the column is automatically migrated to `NOT NULL`. 
I would suggest to change the template script, accordingly.

**Comment by DavidBoike** [comment]
@iappert In your view, does #5001 fix the issue? I tried it myself in SSMS and verified that it SQL understands the column to be non-null even though not declared that way in the DDL.

**Comment by iappert** [comment]
@DavidBoike perfect. Thank you
