### ISSUE TITLE
Using NServiceBus with ASP.NET MVC

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#50]
http://www.particular.net/articles/using-nservicebus-with-asp.net-mvc

http://particular.net/Admin/Contents/Edit/243
http://particular.net/Contents/Item/Preview/243

KB? FAQ?
- [ ] Review content
- [ ] Update code snippets
- [ ] Refresh Images
- [ ] Still on MVC3
- [ ] missing a part where we explain why it is a risky operation to host NSB in IIS and how to survive

**Comment by SimonCropp** [comment]
done 

re

> missing a part where we explain why it is a risky operation to host NSB in IIS and how to survive

nope. that info would span any sample talking about IIS and hance should exist in it own page. feel free to raise a different issue to track that
