### ISSUE TITLE
A wrong link to components from custom serializers page

### ISSUE THREAD

**Issue by Scooletz** [Particular/docs.particular.net#5022]
When looking at https://github.com/Particular/docs.particular.net/blob/master/nservicebus/serialization/custom-serializer.md#create-a-custom-serializer I followed the link from 

>  In order to see sample implementations, refer to the community-maintained serializers.

that points to https://docs.particular.net/components/#serializers only to find that the header on the linked page is anchored with https://docs.particular.net/components/#derializers instead of serializers.

I can't remember whether a person outside of Particular can change the header in https://docs.particular.net/components but wanted to let you know anyway.

**Comment by kbaley** [comment]
Thanks @Scooletz. Notwithstanding the typo in the anchor tag, I've fixed up the link.
