### ISSUE TITLE
Feedback: 'Dependency Injection changes'

### ISSUE THREAD

**Issue by gbiellem** [Particular/docs.particular.net#5029]
Feedback for 'Dependency Injection changes' https://docs.particular.net/nservicebus/upgrades/7to8/dependency-injection

The "offical documentation" link in the sentence "Other supported DI containers are listed in the official documentation."  goes to a 404 page at MS

**Comment by HEskandari** [comment]
@gbiellem Thanks Greg! I've updated the link.
