### ISSUE TITLE
Feedback: 'SQL Server Transport Upgrade Version 4 to 5'

### ISSUE THREAD

**Issue by iappert** [Particular/docs.particular.net#5035]
Feedback for 'SQL Server Transport Upgrade Version 4 to 5' https://docs.particular.net/transports/upgrades/sqlserver-4to5

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/upgrades/sqlserver-4to5.md

Hi there

Is my assumption that you can drop the previously needed subsciption table in the persistence endpoints after upgrading all endpoints to 5 correct? If so, wouldn't it be helpful to mention that? 

Cheers

**Comment by tmasternak** [comment]
@iappert I've added a note in #5041. Please have a look.

**Comment by adamralph** [comment]
Closing based on #5041. @iappert if there's still something missing please feel free to chime in again/re-open.

**Comment by iappert** [comment]
Thanks
