### ISSUE TITLE
Add guidance around message contracts

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#517]
Following this case https://nservicebus.desk.com/agent/case/8165

"I can’t find anywhere in the documentation saying that you should not use domain objects in messages (i.e. when we are updating an Employee, we are sending an IEmployee on the message). And since IEmployee defines methods that will fail.

Maybe this is just something that needs documenting, or maybe it is a bug. If I knew of this limitation earlier I definitely would have estimated much more time for the upgrade, and I would have changed messages before upgrading (so we could test that the changed messages worked as expected)."

"I think the guidance is a good start, perhaps the method could throw a more specific error (wrapping the type exception) as well? Knowing what the problem is for this exception might be helpful if anyone else makes this same mistake."

- [x] Document structs are not supported

**Comment by ramonsmits** [comment]
It mentions that is fails but how? Does it raise a serialization exception?

What would be the recommendation? To use DTO's as is usually the recommended approach for transport level contracts?

**Comment by SimonCropp** [comment]
@ramonsmits usually what happens is someone passes in a domain object that does lazy loading. as part of serialization all properties are walked. resulting in the whole domain model being serialized.

**Comment by andreasohlund** [comment]
I'd also mention SRP, a message contract should have one reason to change, the data that needs to be shared. Passing domain objects clearly violates this since a change to the domain model now would affect the message contract

**Comment by DavidBoike** [comment]
Need to include making messages simple. Classes should not have only parameter-laden constructors and non-public setters.

/cc @mikeminutillo

**Comment by ramonsmits** [comment]
@SimonCropp In that lazy loading scenario serialization needs to take place before the ORM its session is stopped. With NHibernate you can query an object and eager load it. It can lead to issues like loading the complete domain model. 

Looks like CRUD on top of messaging.

Agreed with @DavidBoike classes should be simple POCO's but when using NHibernate you can also use POCO's in your ORM mappings. 

So better so state not to use your entity POCO's in or as your message contracts. Still, how to map to/from them?

You can state alternatives like:

- Use NHibernate projections or SetResultTransformer to map your ORM model to your message type
- Use [AutoMapper its LINQ projection feature](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions)
- Use super leight-weight mappings using Dapper or its alternatives

**Comment by mikeminutillo** [comment]
Had a case yesterday where the customer wanted to use `struct` messages. I do not know if that is supposed to be supported or not but it currently does not work. I raised https://github.com/Particular/NServiceBus/issues/3650 to track it.

If it is decided that `struct` messages are not supported then this should be included in the guidance as well.

**Comment by SimonCropp** [comment]
People should not be using persistence models a communication models. They are, in the majority, conflicting requirements
