### ISSUE TITLE
Feedback: 'Upgrade ServiceControl from version 1 to version 2'

### ISSUE THREAD

**Issue by rudibelt** [Particular/docs.particular.net#5191]
Feedback for 'Upgrade ServiceControl from version 1 to version 2' https://docs.particular.net/servicecontrol/upgrades/1to2

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/upgrades/1to2.md

Side by Side:
I disabled the old ServiceControl by the !disable queue settings, this works but the old instance still reads the heartbeat messages (ServiceControl name is the default one cannot change this,its in al the endpoints cofigured). Am I missing heartbeat messages in the new ServiceControl instance?

**Comment by yvesgoeleven** [comment]
@rudibelt sounds like a problem indeed. I will raise it to the right people internally. Note that version 2 isn't supported either anymore. I suggest to expedite upgrade to the latest version.

**Comment by yvesgoeleven** [comment]
@rudibelt looks like you can get into this situation when installing an instance with the exact same name as the original on a different machine, the second instance should have been named differently. If this is an issue in development or test you can uninstall the second instance and reinstall it with a new name. If this is an issue in production, you can raise a support request  at https://particular.net/support
