### ISSUE TITLE
de-prioritise StackOverflow on the home page

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#520]
### Reorder "Community Help"

Move "Discussion group" above "StackOverflow". 
### we cant control the conversation.

We know what the correct answer is and dont want to have incorrect or misleading answers being voted above ours.
### StackOverflow wants to own the content

If you just post a link to answer a question this is actually an invalid answer from a SO perspective. Many answers get closed or downvoted since they do not contain enough information. So to avoid the downvote we need to copy a non-trivial amount of information into that answer. This is duplicate effort when we would rather just have the content in our docs. It also results in content degradation over time since we are not going to come back and update this content over time.

**Comment by malkinservicebus** [comment]
@andreasohlund @dannycohen @udidahan based on this issue,  is it OK to remove the links leading to stackoverflow from the sales and support templates ?

**Comment by udidahan** [comment]
I think it may be suitable to mention it in a sales-type template as the existence of many questions/answers on Stackoverflow can be considered a kind of selling point. Do you have a link to the sales template @malkinservicebus ?
