### ISSUE TITLE
Feedback: 'Sending messages'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#5268]
Feedback for 'Sending messages' https://docs.particular.net/nservicebus/messaging/send-a-message

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/send-a-message.md

The [note](https://docs.particular.net/nservicebus/messaging/send-a-message#outside-a-message-handler) for sending outside a message handler says

>  When the invocation ends, it does not mean that the message has actually been sent.

This doesn't sound right. The only transport that would not send immediately to the destination would be MSMQ as it's a store and forward mechanism. Would be good to clarify that note and adjust it to eliminate the [confusion it causes](https://discuss.particular.net/t/sending-or-publishing-from-api-controller/2327/3?u=seanfeldman).

**Comment by SeanFeldman** [comment]
The note appears to be in the [`batch-sends-performance` partial](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/send-a-message_batch-sends-performance_core_%5B6%2C).partial.md). Which hints that this is not applicable to sending outside of a message context.

**Comment by SeanFeldman** [comment]
The [original note](https://github.com/Particular/docs.particular.net/commit/d6ca7710bde4e2b07aade272d16cc1921c8a476b) was about performance. As of now, it's not about performance, and hence the sentence is wrong.

**Comment by SeanFeldman** [comment]
Re-examining the note and the article, I'm now leaning towards moving that note out of the "Outside a message handler" section into the "Inside the incoming message processing pipeline" section. Then it describes accurately what's happening in the context of a handler and also points to the correct sample (Writing Async Handlers).

**Comment by andreasohlund** [comment]
Agreed, that note should be moved like you suggests
