### ISSUE TITLE
Configuring timeout polling interval in V5

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#529]
[Current documentation](http://docs.particular.net/nservicebus/configure-timeout-polling-interval) shows V4, in V5 `TimeoutPersisterReceiver` is internalized and sample code doesn't apply.

**Comment by SimonCropp** [comment]
@johnsimons so should we remove the page from the docs site?

**Comment by johnsimons** [comment]
@SimonCropp see my previous https://github.com/Particular/docs.particular.net/issues/529#issuecomment-67258872
