### ISSUE TITLE
Add code samples for v5

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#531]
https://github.com/Particular/docs.particular.net/edit/master/nservicebus/injecting-the-bus-into-asp.net-mvc-controller.md

[Raised by a customer in Desk](https://nservicebus.desk.com/agent/case/8252)

**Comment by mauroservienti** [comment]
The code sample is tight to MVC, my proposal is:

* [ ] move the code to snippets;
* [ ] refactor the article to include also WebAPI and not only MVC;
* [ ] add code samples for V5;

@sfarmar thoughts?

**Comment by mauroservienti** [comment]
I'm facing some issues :-|

1. in order to setup a dependency resolver (both in MVC and WebAPI) we need an instance of the current builder, if we are not setting our own container there is no way to access the default one without an ugly cast to UnicastBus:

    ```csharp
    var configuration = new BusConfiguration();
    configuration.UsePersistence<InMemoryPersistence>();

    var busInstance = Bus.Create( configuration ).Start();
    var builder = ( ( NServiceBus.Unicast.UnicastBus )busInstance ).Builder;
    ```

2. in a dependency resolver we need to know if a component is registered or not **before** trying to resolve it, thus we need to access the current `IConfigureComponents` instance, even in this case there seems to be no way other than this ugly code:

    ```csharp
    var configuration = new BusConfiguration();
    configuration.UsePersistence<InMemoryPersistence>();

    IConfigureComponents configurer = null;
    configuration.RegisterComponents( r => 
    {
        configurer = r;
    } );
   //use the configurer here.
    ```

Obviously if we are injecting our own container there are no issues at all, we have control over the entire process.
 
@andreasohlund am I missing something? don't we need to supply a better API in this scenario?

**Comment by mauroservienti** [comment]
One more question: given a `IBuilder` instance what should I do to explicitly force the creation of a new scope? `CreateChildBuilder` does the trick?

**Comment by andreasohlund** [comment]
If I remember correctly we can't use our internal builder since it will leak instances? @johnsimons @indualagarsamy do you remember?(that's why matrix is using AutoFac)

**Comment by mauroservienti** [comment]
Isn't AutoFac the default if nothing is configured?

Sent from my Amazing not anymore Yellow Lumia, typos are guaranteed ;-)

-----Original Message-----

**Comment by andreasohlund** [comment]
Yes, but you need to use the external one + the AF mvc integration dll to avoid leaking controller instances:

https://www.nuget.org/packages/Autofac.Mvc5/

**Comment by sfarmar** [comment]
:+1: @mauroservienti, glad to help...

**Comment by SeanFeldman** [comment]
@mauroservienti, here's an [example](https://github.com/Particular/ServiceMatrix.Samples/blob/191ae15b0e2a825530cf12dea6778280cd0e35d8/OnlineSalesV5/OnlineSalesV5.eCommerce/Infrastructure/WebGlobalInitialization.cs)

I think the idea is that you use _container_.MVC5/WebAPI integration nuget as well as NSB._container_ integration package and this will give you the desired result - same container used by both MVC5/WebAPI and NSB.

**Comment by SimonCropp** [comment]
make it two different samples. one for MVC5 and one for webapi

**Comment by mauroservienti** [comment]
@SimonCropp yes.

@SeanFeldman Same approach I use with Windsor all the time, what I question is that to me it seems we are using a buggy container if we need to complicates things in order to void leaking controller instances, that's it.

I'll outline the scenario in the sample and in the doc.

**Comment by andreasohlund** [comment]
>a buggy container if we need to complicates things in order to void
leaking controller instances

I wouldn't say buggy, AF works as expected if you set it up according to
their guidelines (is use the MVC/WebApi integration asm) it works. And
that's why the internal autofac we use can't be used for resolving
controllers.

Thoughts?

**Comment by SimonCropp** [comment]
our builder API is "the minimum api that we can safely expose across multiple container implementations". It is an abstraction. With any abstraction that targets multiple libraries you should expect a loss of detail in the resulting API. 

I fully expect that any non-trivial application should need to use an external container so as to expose the full power of that api, but also to properly integrate with other libraries in this case https://www.nuget.org/packages/Autofac.Mvc5/

It is a very similar case we have with our built in logging functionality and our built in Json serializer functionality.

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/web/asp-mvc-injecting-bus/
