### ISSUE TITLE
Document deprecation of ISatellite and IAdvancedSatellite in the Upgrade Guide.

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#532]
Update the upgrade guide for moving away from both ISatellite and IAdvancedSatellite

--
Original notes from the issue: 
- is it a supported feature?

if yes, I'd say:

- what they are;
- how to write a satellite;
- when to write a satellite;

**Comment by mauroservienti** [comment]
@Particular/engineers thoughts? especially:

> is it a supported feature?

**Comment by indualagarsamy** [comment]
@mauroservienti - we use it internally :) for things like the timeout dispatcher, etc. I've used it as a mechanism to poll Queues (in SqlBridge - MSMQ to SQL bridge) 
@andreasohlund thoughts?

**Comment by mauroservienti** [comment]
I know they are used internally, I used them a couple of times at customers too. They are powerful but building one is a challenge for the end users, if they know they exist.

**Comment by SzymonPobiega** [comment]
> With great power comes great responsibility

:+1: for documenting since it is a public API (in the sense there is nothing in the code that prevents me from creating and using it). I mentioned this term a few times in the low-level SQL transport docs

**Comment by indualagarsamy** [comment]
Ok! I can have a shot at it.

**Comment by indualagarsamy** [comment]
Discussed with @SimonCropp and we are not going to add documentation for this. Instead, we are going to:
- [ ] Update the upgrade guide for moving away from both ISatellite and IAdvancedSatellite
- [ ] Change the SqlBridge current implementation to what's the better approach in v6.

**Comment by indualagarsamy** [comment]
This issue is blocked until https://github.com/Particular/NServiceBus/issues/3505 is resolved.

**Comment by SimonCropp** [comment]
@indualagarsamy so this is unblocked now?

**Comment by indualagarsamy** [comment]
@SimonCropp - I have all the info I need for documenting ISatellites. I am working on IAdvancedSatellite and wanted to have some decent doco on that well. I need to sync with @SzymonPobiega or @timbussmann. Hoping to do that tomorrow.

**Comment by mauroservienti** [comment]
Are `ISatellite` and `IAdvancedSatellite` still a thing? I mean isn't V6 deprecating them in favor of the `satellite pipeline`?

**Comment by indualagarsamy** [comment]
@mauroservienti - They are deprecated. What I am doing is trying to capture enough information for people already using them in v5 to how they can achieve the same behavior in v6 without Satellites.

**Comment by indualagarsamy** [comment]
@mauroservienti - I've updated the title of the issue to reflect this.

**Comment by indualagarsamy** [comment]
I was trying to show usage of changing the fault manager in IAdvancedSatellite and ran into this:
https://github.com/Particular/NServiceBus/issues/3563

**Comment by indualagarsamy** [comment]
My Satellite conversion sample is here. I was trying to show an usage of IAdvancedSatellite which replaces the custom fault manager (similar to what ServiceControl does). 
https://github.com/indualagarsamy/NSBSatelliteMigration/blob/master/v5/MyAdvancedSatellite.cs#L31
Waiting to get the CustomFaultManager sample working.
