### ISSUE TITLE
Publish better release notes

### ISSUE THREAD

**Issue by rosieks** [Particular/docs.particular.net#537]
Release notes published on GitHub are ordered by release date and it makes difficult to compare what changed between wider range of versions (especially for older version).
It would be nice to have page that is ordered by version number rather than release date.

Additionally font size also could be smaller

**Comment by mauroservienti** [comment]
This is not relevant here, the docu repo does not publish any release note. We are already investigating a better approach for NServiceBus and the transports.

I'll close this one.
