### ISSUE TITLE
Full Duplex Sample using NServiceBus V3

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#54]
http://www.particular.net/articles/full-duplex-sample-v3

http://particular.net/Admin/Contents/Edit/239
http://particular.net/Contents/Item/Preview/239

- [ ] Review content
- [x] Update code snippets
- [ ] Create an article for v4??
- [ ] I think is important so underline that request/response *can* be an anti-pattern

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/fullduplex/
