### ISSUE TITLE
Document extension interfaces and the execution order

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#540]
Feedback: "Is there currently a list of available Extension Point Marker Interfaces for NSB v5?
EX: INeedInitiailization,  WantToRunBeforeConfigurationIsFinalized.... etc...

Is there documentation on the order of execution of all of these and also the examples of use cases for each of these?"

**Comment by mauroservienti** [comment]
@SimonCropp I'd like to have this for v3, v4 and v5. The goal is not API docu but guidance on how to interact with the NServiceBus initialization and bootstrap process:

* INeedInitialization (all versions)
* IWantToRunBeforeConfigurationIsFinalized (v3, v4)
* IWantToRunWhenBusStartsAndStops (v4, v5 IIRC)
* IWantCustomInitialization
* IWantToRunBeforeConfiguration

And I'm pretty sure I'm missing at least one related to start/stop in v3.

Thoughts?

**Comment by SimonCropp** [comment]
yeah i think that would be valuable. but would be good to also include the steps in between those like when bus starts/strop, assembly scan, feature config etc

**Comment by mauroservienti** [comment]
@SimonCropp as you asked on Slack, sorry for getting back to this so late, yes [this sample](http://docs.particular.net/samples/startup-shutdown-sequence/) perfectly fits this.

Closing this as fixed, if we think that we need to add also a docu page we can raise another issue.
