### ISSUE TITLE
Feedback: 'Operational Scripting' - Needs Examples

### ISSUE THREAD

**Issue by Smoles** [Particular/docs.particular.net#5410]
Feedback for 'Operational Scripting' https://docs.particular.net/transports/azure-service-bus/operational-scripting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/operational-scripting.md

This page could use some usage examples. It's not obvious how some of the inputs should be constructed. For example on the endpoint subscribe, is the 'event-type' parameter suppose to be the fully qualified name of the C# class or just the class name?

**Comment by SeanFeldman** [comment]
Hi @Smoles,

Good suggestion. I'll raise a PR. Meanwhile, to get you going here's an example of the most complicated part - subscribing to an event

```
asb-transport endpoint subscribe Full.Namespace.With.Event.Name.MyEvent Full.Namespace.With.Event.Name.MyEvent -r MyEvent -c "<connection-string>"
```

What it does is subscribes to an event `Full.Namespace.With.Event.Name.MyEvent Full.Namespace.With.Event.Name.MyEvent` and trims the rule name to be just `MyEvent` for clarity or follow a convention. This takes care of the length of the rule name and prevents 50 characters limitation error.

**Comment by bording** [comment]
@Smoles I just merged the PR that @SeanFeldman raised to add some examples, and that closed this feedback issue. Feel free to re-open the issue, or open a new feedback issue, if you think this does not fully address your feedback!
