### ISSUE TITLE
Improve the transport connection string doco

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#542]
Current page is a mess.

 http://docs.particular.net/nservicebus/connection-strings-samples

Rabbit already has better doco here:

http://docs.particular.net/nservicebus/rabbitmq/configuration-api

### Plan of attack

* Create a landing page for transports
* Add the cluster doco in http://docs.particular.net/nservicebus/connection-strings-samples to  http://docs.particular.net/nservicebus/rabbitmq/configuration-api 
* Move the msmq parts to a new msmq section
* Create a generic page that talk about the code first api: https://github.com/Particular/NServiceBus/blob/def31db15977a6017737f134c15d1698edff97e0/src/NServiceBus.Core/Unicast/Transport/Config/TransportExtensions.cs#L26
* Move the sql parts to http://docs.particular.net/nservicebus/sqlserver/configuration
* remove  http://docs.particular.net/nservicebus/connection-strings-samples and redirect to new landing page

**Comment by SimonCropp** [comment]
BTW I dont think there is any value placing connections strings for different transports on the same page. 

Should also link to the external doco for each. eg for Microsoft Azure Service Bus https://msdn.microsoft.com/en-us/library/azure/jj149830.aspx

**Comment by andreasohlund** [comment]
Agree, connection string should be documented under each transport

**Comment by SimonCropp** [comment]
done
