### ISSUE TITLE
Possible duplicate content on SC external integrations

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#543]
I think we have duplicate context for SC external integrations:
 * [First](https://github.com/Particular/docs.particular.net/blob/master/servicepulse/custom-notification-and-alerting-using-servicecontol-events.md)
 * [Second](https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/external-integrations.md)

cc @indualagarsamy

**Comment by sfarmar** [comment]
I wrote the first one...

**Comment by mauroservienti** [comment]
reading both of them they are not the same, the first one is a high level discussion on the concepts and the second one describes how to technically get notifications.

@sfarmar da you see some value in cross linking them and maybe strip out from the second one the introduction that is a duplicate?

**Comment by indualagarsamy** [comment]
@mauroservienti - I modified the first article in Cyprus and it feels like it contains most of what's on the 2nd article: 
http://docs.particular.net/servicepulse/custom-notification-and-alerting-using-servicecontol-events
Can we add the relevant section out of the second article and then delete the 2nd article?
I agree with @SzymonPobiega - it looks like a duplicate to me. 
It should be easy with the redirect tag. To properly delete the article, we'd need to add the doc name of the 2nd article in the redirects tag of the first article

**Comment by mauroservienti** [comment]
@indualagarsamy good point, merging is a good option. @sfarmar since you wrote originally the first one, would you like to take the merge too?
