### ISSUE TITLE
Update MSMQ documentation that Express messages cannot be send to transactional queues.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#546]
https://groups.google.com/forum/#!msg/particularsoftware/Inf1rjZdD00/-r8rblR7wCQJ

Msmq does not support sending Express messages to transactional queues.

That said, I don't see any documentation explaining this anywhere... the samples showing Express message may be misleading.

**Comment by mauroservienti** [comment]
@ramonsmits is this the article that needs update? http://docs.particular.net/nservicebus/express-messages

**Comment by ramonsmits** [comment]
Yes I think that would be a good location.

**Comment by mauroservienti** [comment]
ok, go for it :-)

**Comment by mauroservienti** [comment]
@ramonsmits please refer to @andreasohlund last comment on https://github.com/Particular/docs.particular.net/issues/487#issuecomment-75584645 to a couple of things to integrate.

**Comment by SimonCropp** [comment]
@ramonsmits  Ok I am a little confused. r u saying that if a person adds `[Express]` to a message it should fail to send over a transactional queue?

**Comment by andreasohlund** [comment]
Ifaik the target queue must to set to non transactional for Express to work.

And that's the tricky part since as a sender you can't know that

**Comment by andreasohlund** [comment]
We need to test but I think it will just not be express if the target q is not marked as non tx.

If the sender is requesting a TX send and the queue is non tx the message will go into the DLQ

**Comment by weralabaj** [comment]
That seems to be covered already in the docs, especially http://docs.particular.net/nservicebus/messaging/non-durable-messaging#effect-on-transports-msmq-extra-config-for-msmq.
