### ISSUE TITLE
Publish/Subscribe sample refers to CreateInstance that is deprecated in v5

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#550]
Here: http://docs.particular.net/nservicebus/publish-subscribe-sample#creating-and-publishing-messages

"The first message is constructed using the provided factory function Bus.CreateInstance(<messagetype>), which creates a message that implements a specified interface or a specific type."

--

Related to: #186

**Comment by SimonCropp** [comment]
fixed here http://docs.particular.net/samples/pubsub/
