### ISSUE TITLE
Document overprovisioning

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#5511]
Feedback for 'Azure Functions with Azure Service Bus' https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/azure-functions-service-bus/index.md

see https://github.com/Azure/Azure-Functions/issues/715 and https://discuss.particular.net/t/scheduled-messages-eg-saga-timeouts-causes-over-scale-on-azure-function-consumption-plan/2751

**Comment by WilliamBZA** [comment]
:+1: We'll capture this in our documentation somewhere.
