### ISSUE TITLE
Document that SC database folder(s) needs to be excluded by AV scan

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#553]
Raised by @ramonsmits following up a case with a customer (8573)

**Comment by ramonsmits** [comment]
Also, not only AV but also other file related things like system backups and file/folder security. Mention the exception `Microsoft.Isam.Esent.Interop.EsentInstanceUnavailableException` which occurred in the desk case.

**Comment by mauroservienti** [comment]
@ramonsmits what about add the above as a new section here: http://docs.particular.net/servicecontrol/troubleshooting, or much better a new page in "management" section such as "ServiceControl Antivirus Configration"

**Comment by SimonCropp** [comment]
@mauroservienti  i think http://docs.particular.net/servicecontrol/troubleshooting is good enough
