### ISSUE TITLE
Review Platform landing page

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#554]
Platform landing page: http://docs.particular.net/platform/

* [ ] Information architecture and concept design with @jdrat2000 and @sergioc
* [ ] Define minimum acceptable look&feel with @sergioc 

--

Related to: https://github.com/Particular/Requirements/issues/78

**Comment by SimonCropp** [comment]
why the effort to improve this page? where is it linked to from?

**Comment by mauroservienti** [comment]
well, it is simply horrible :-)
if it is not linked anywhere why has it been created?

@dannycohen: since you raised the source requirement, do we need it?

**Comment by dannycohen** [comment]
Given recent changes in roadmap - this is redundant. Closing.
