### ISSUE TITLE
ServiceControl Audit and Error instance missing EnableFullTextSearchOnBodies from settings section

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#5548]
EnableFullTextSearchOnBodies is missing as a documented setting in the servicecontrol audit and error instance settings sections.

https://docs.particular.net/servicecontrol/creating-config-file
https://docs.particular.net/servicecontrol/audit-instances/creating-config-file

**Comment by danielmarbach** [comment]
Thank you very much for the heads-up! Added the necessary documentation
