### ISSUE TITLE
Should we add a page listing community extensions?

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#555]
Such as, but not only, https://github.com/ahofman/NServiceBus.AmazonSQS

**Comment by SimonCropp** [comment]
@udidahan @brittking what should be the name of this?

 * "External integrations"
 * "3rd party integrations"
 * "Community contributions"

??

**Comment by brittking** [comment]
@mauroservienti how many community-built transports are there to promote?
@SimonCropp it seems to fall under 'community contributions' but are there community contributions beyond transports to promote as well? If yes, we should categorize on a community page at the very least.

**Comment by mauroservienti** [comment]
@brittking as far as I know currently 2:

* https://github.com/ParticularLabs/NServiceBus.WebSphereMQ
* https://github.com/ahofman/NServiceBus.AmazonSQS

and I customer I talked to last week is in the process of building one to support ActiveMQ.

**Comment by SimonCropp** [comment]
it is not just transports.

https://github.com/SimonCropp/NServiceBus.Mailer

**Comment by SimonCropp** [comment]
it is not just transports.


- https://github.com/KenBerg75/NServiceBus.SLR
- https://github.com/rosieks/NServiceBus.OracleAQ
- https://github.com/SimonCropp/NServiceBus.Jil
- https://github.com/sbmako/NServiceBus.MongoDB
- https://github.com/ahofman/NServiceBus.AmazonSQS
- https://github.com/SimonCropp/NServiceBus.ProtoBuf
- https://github.com/volak/Aggregates.NET
- https://github.com/feinoujc/NServiceBus.Mandrill
- https://github.com/fhalim/NServiceBus.PostgreSQL
- https://github.com/SimonCropp/NServiceBus.MessagePack
- https://github.com/SimonCropp/NServiceBus.Newtonsoft.Json
- https://github.com/tekmaven/NServiceBus.Persistence.MongoDb
- https://github.com/jbogard/NServiceBus.MessageRouting
- https://github.com/fhalim/NServiceBus.Serializers.SystemXml
- https://github.com/SimonCropp/NServiceBus.Mailer
- https://github.com/SimonCropp/NServiceBus.Serilog
- https://github.com/SimonCropp/HandlerOrdering
- https://github.com/synhershko/NServiceBus.DocumentDB
- https://github.com/roycornelissen/SignalR.NServiceBus
- https://github.com/SzymonPobiega/NServiceBus.FoundationDB

there may also be commercial products we could list here

**Comment by SimonCropp** [comment]
if no one comes up with anything better i am going with "community contributions"

**Comment by SimonCropp** [comment]
first draft here http://docs.particular.net/platform/extensions

Should we link to it from the front page?

**Comment by mauroservienti** [comment]
I don't like that supported and official things are mixed with community things, it give to the reader the sense that we are supporting AmazonSQS for example.

**Comment by brittking** [comment]
What if we split the page between Community and Particular, similar to the
London / New York City sections here: http://particular.net/nsbcon-2014

I like having all extensions available in one place.

**Comment by SimonCropp** [comment]
@mauroservienti the purpose of this page is several-fold

1. encourage community involvement
2. publicise community involvement
3. let people know of all the things that they can use to extend NSB

Any effort to publicise "what is supported" and hence "highlight what is not supported" seems counter productive to 1 and 2.

Even emphasising "what is supported by particular" seems a bit disingenuous to the people we r trying to give credit and publicity too. Also we want to optimise for "more people extending NSB in open source projects" any implication that "if it not from Particular it is not worth looking at" defeats the purpose and we may as well not have this page.

Also we should give clients more credit to clients and trust them to do appropriate research when choosing technologies.

**Comment by udidahan** [comment]
I wouldn't consider MSMQ or RabbitMQ as extensions to the platform. Same goes for XML/JSON serialization, the distributor and gateway, etc.

In other words, if we support it - it's part of the platform, not an extension and as such, shouldn't appear on this page.

**Comment by SimonCropp** [comment]
@udidahan yes but not listing them seems a poorer option. "what i can serialize with protobuf but not json". i made the call that that it was better, for completeness to keep them there

**Comment by indualagarsamy** [comment]
@SimonCropp - wouldn't it be easier to just list the community contributions that'll address all the points you mentioned? I don't quite understand what your argument against not listing the supported serializers. If people are interested in protobuf, wouldn't they click the link to that repository to get more info, which should a proper readme? I don't get how not listing Xml or Json is a problem. Can you clarify?

**Comment by udidahan** [comment]
There seem to be too many concerns being mixed into this page.

Could be we need a Serialization page that talks about (or links to) what is supported, how to write a custom serializer, and community contributions.

And, of course, similar pages for the other topics - transports, persistence, etc.

**Comment by indualagarsamy** [comment]
@udidahan - the only downside i see to that approach is that, we lose out from a marketing perspective - when a new user goes to that page, its nice to see a *lot* of community contribution. Its like a show case page of how others use our stuff and build on it.

**Comment by udidahan** [comment]
@indualagarsamy I'm not saying not to have this page but, for example, in the serialization section of the page which shows only the community contributions, we could have a link to the official serialization page.

**Comment by indualagarsamy** [comment]
@udidahan - Thanks for the clarification. I agree with @SimonCropp in that, this new page is more of a show case of the users in the community, highlighting their contributions. What we support should be available and be very obvious from our docs page and if it isn't already than that's a different problem, one we need to address. In this page that highlights the user, why pop a link in that talks about us? This is a page for them.

**Comment by SimonCropp** [comment]
I think "supported things" should be a page co located with our licensing and pricing

**Comment by sergioc** [comment]
> first draft here http://docs.particular.net/platform/extensions

Cool!

> Should we link to it from the front page? 

@SimonCropp That'd be great to make immediately clear which 3rd party projects can be integrated. No need for digging further around, and it'll probably help with convincing a potential opportunity.

The current title should be simplified and more to the point, simply use something like "Extensions". The main purpose of the page is to list integrations with 3rd parties. If you want to highlight community contributions, consider replacing the "Particular run project" label with "Community" or "Community contribution" or "Community project". That'd also explain why that specific extension links to an external Github page, instead of a docs.particular.net page.

**Comment by udidahan** [comment]
@indualagarsamy 

> and if it isn't already than that's a different problem

This is all we have on serialization: http://docs.particular.net/tags/serialization/

Please check if there are other areas that are weak and resolve them as well.
