### ISSUE TITLE
Add "definitions" as guidance?

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#556]
As discussed with @SimonCropp and @andreasohlund should we add definitions as guidance in the doco?

A sample can be this one: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/7zOHHOOqDi4/Gcjlnl0becMJ

**Comment by SimonCropp** [comment]
http://docs.particular.net/nservicebus/concept-overview
