### ISSUE TITLE
Feedback: 'Migrating from timeout manager to native delivery'

### ISSUE THREAD

**Issue by mortenn** [Particular/docs.particular.net#5590]
Feedback for 'Migrating from timeout manager to native delivery' https://docs.particular.net/nservicebus/tools/migrate-to-native-delivery

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/tools/migrate-to-native-delivery.md

There is no information on how to deal with the timeout table not being in the default "dbo" schema when using sqlp as source
The sqlp source does not support the --schema switch that the sqlt target has.

**Comment by andreasohlund** [comment]
Hi @mortenn , sorry for the delay.

We don't currently support non-default schemas and I have raised https://github.com/Particular/TimeoutMigrationTool/issues/319 to track adding support for it. What is your timeline for the migration?

As a workaround would you be able to manually copy the `[{endpointName}_TimeoutData]` table to the `dbo` schema before running the migration?

**Comment by mortenn** [comment]
The migration was done over christmas and I've just dropped the timeouts as there weren't that many and they weren't important either.

**Comment by andreasohlund** [comment]
Glad you got unstuck.

I'll close this issue since https://github.com/Particular/TimeoutMigrationTool/issues/319 covers adding the feature
