### ISSUE TITLE
ServiceControl audit instance missing documentation DisableRavenDBPerformanceCounters setting

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#5618]
ServiceControl audit instance missing documentation DisableRavenDBPerformanceCounters setting

https://github.com/Particular/ServiceControl/blob/336bf49cce41e794e9783be2ea480a1799bece61/src/ServiceControl.Audit/Infrastructure/Settings/Settings.cs#L40

**Comment by soujay** [comment]
@TraGicCode - DisableRavenDBPerformanceCounters setting has been removed as it is no longer used. Thank you for bringing it to our attention.
