### ISSUE TITLE
Feedback: 'Configuration'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#5645]
Feedback for 'Configuration' https://docs.particular.net/transports/azure-service-bus/configuration

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/configuration.md

The link to MSFT docs for `SubscriptionNamingConvention(Func<string, string>)` is a wrong link.
_Could_ be the same as for `SubscriptionRuleNamingConvention(Func<Type, string>)`.

**Comment by mauroservienti** [comment]
Thanks @SeanFeldman. Not sure I'm following. Are you suggesting that we should be linking to https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas instead of to https://docs.microsoft.com/en-us/rest/api/servicebus/create-subscription?

**Comment by SeanFeldman** [comment]
Correct.

**Comment by mauroservienti** [comment]
@SeanFeldman would you mind a quick review https://github.com/Particular/docs.particular.net/pull/5650?

Do you think the same change should be done for [versions prior to 1.8](https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/configuration_subscription-rule-customization_asbs_%5B1.0%2C1.7%5D.partial.md)?

Thanks.

**Comment by SeanFeldman** [comment]
It would be the same for any version as ASB quotas and rules have not changed for any version for this transport.
