### ISSUE TITLE
Guidance for Security of encrypted information across the platform

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#566]
This is the guidance split-out of https://github.com/Particular/Requirements/issues/148.

**Comment by SimonCropp** [comment]
ok i am closing this. 

I cant think of any content that we could possibly write that is specific enough to our products that would justify it existing in our documentation.

If anyone can come up with some real content to illustrate why we should pursue this issue then please open a pull request with some content.
