### ISSUE TITLE
Guidance how to use Windows Scheduler together with NServiceBus

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#567]
Write a sample and guidance which shows how to do scheduling with the windows scheduler.

**Comment by SimonCropp** [comment]
So what is the intent here? Call an exe that puts something on a queue? Any reference links .

**Comment by SimonCropp** [comment]
@danielmarbach still see this as important?

**Comment by danielmarbach** [comment]
If I remember correctly this was brought up in TAM discussions. We argued that Windows Scheduler is still the defacto standard on windows OS for scheduling. As it stands right now we don't have anything to offer on the documentation site. But I can't say I feel strongly about it.

**Comment by SimonCropp** [comment]
just "work shopping"   would u have the Windows Scheduler spin up a exe, with a send only endpoint, to send a message?

**Comment by danielmarbach** [comment]
Yeah for example.

**Comment by SimonCropp** [comment]
so u would see this as a sample?

**Comment by danielmarbach** [comment]
I think that is the best way to move forward. Since we don't want to explain how the windows scheduler works but do a show case.
