### ISSUE TITLE
Capture the cursor in the search field

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#568]
Almost always when I go to the docs page I use the search box to search for content. Would be nice to automatically set the cursor focus to the search box and maybe also visually highlight the search box.

// cc @sergioc

**Comment by mauroservienti** [comment]
Yes +1

Sent from my Amazing not anymore Yellow Lumia, typos are guaranteed ;-)

-----Original Message-----

**Comment by SimonCropp** [comment]
@danielmarbach this is for content. Operations.DocsWeb repo is for functionality changes. can you please re-raise this in that repo

**Comment by johnsimons** [comment]
How about we add a shortcut key? Same as github.

**Comment by johnsimons** [comment]
@synhershko was also suggesting adding autocomplete to it

**Comment by danielmarbach** [comment]
@SimonCropp how much effort would it have been for you to raise it in the right repo right after you closed this one?
