### ISSUE TITLE
Feedback: 'Handlers'

### ISSUE THREAD

**Issue by victorcassel** [Particular/docs.particular.net#5687]
Feedback for 'Handlers' https://docs.particular.net/nservicebus/handlers/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/handlers/index.md

The structure in the page with the headers is not very clear: 
Too small differences in header styles, first of all.
Then that Multiple handlers is talking about error behaviour and their solutions further down is only understood if you read the page very concentrated in one sitting, you won't get the bigger context  from the header text och styles alone, and can't jump straight in.
Example:
<h2>Behavior when there is no handler for a message
<h2>Multiple handlers for a single message
<h3>Alternatives
<h4>Events
<h4>Other messages

**Comment by ramonsmits** [comment]
@victorcassel Thanks for taking the opportunity to provide feedback. I would like to improve this page, would you have one of more suggestions on restructuring or point to a piece of text that must be easier to discover? 

Is there a missing section or do you expect a section to be split?

**Comment by soujay** [comment]
@victorcassel : Thank you for your feedback and patience. The page has been improved based on your feedback.
