### ISSUE TITLE
Improve guidance on communication with client side

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#572]
The [how-do-i-handle-responses-on-the-client-side](http://docs.particular.net/nservicebus/how-do-i-handle-responses-on-the-client-side) document is not providing enough guidance for users how to handle responses on the client side, pushing them into callback as the only option (despite warning associated with it).

Add guidance for other approaches and consider splitting callback documentation in its own document targeting scenarios where callbacks are appropriate:

> The recommended cases for callbacks are for legacy projects and integration with 3rd parties expecting synchronous calls. It is usually associated with a scenario when back-end processing can take time, but front-end (such as IIS) still has to process requests. To mitigate that, messaging with callbacks help to achieve the goal while allowing web server to continue servicing new requests.

**Comment by SimonCropp** [comment]
@SeanFeldman if u still see this as required can u submit a draft PR
