### ISSUE TITLE
Remove redundant calls to ConfigureAwait in samples

### ISSUE THREAD

**Issue by adamralph** [Particular/docs.particular.net#5747]
We've changed our guidelines to [omit redundant calls to ConfigureAwait in samples](https://github.com/Particular/docs.particular.net/pull/5746) but many of our samples still have those calls. They should be removed.

POA 

- [x] Review Resources:
  - https://github.com/Particular/docs.particular.net/blob/master/samples/index.md#configureawait
  - https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007
  - https://www.gabescode.com/dotnet/2022/02/04/dont-use-configureawait.html
  - https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f
  - https://blog.stephencleary.com/2023/11/configureawait-in-net-8.html
- [ ] Update samples to remove `ConfigureAwait(bool)` unless it is explicitly required

**Comment by kbaley** [comment]
This was [done today](https://github.com/Particular/docs.particular.net/pull/6491)
