### ISSUE TITLE
Create sample that show how to use EF with NServiceBus

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#576]
In summary, users want to use EF with the current impl of outbox, but because the outbox uses NH, it is confusing how to integrate both technologies.

See discussion in https://groups.google.com/d/msg/particularsoftware/rWFqN7D3Xks/Gk_CpfGhS7oJ

**Comment by SzymonPobiega** [comment]
Done here http://docs.particular.net/samples/sqltransport-nhpersistence-outbox-ef/ but the code won't work until we release SQL Server 2.1 and new NHibernate

**Comment by Maqster6** [comment]
The link is broken :(
Time frame for SQL Server 2.1 release?

**Comment by SzymonPobiega** [comment]
Just fixed it. 2.1 is released, samples are already using it. Sorry for the delay.

**Comment by Maqster6** [comment]
Thanks Szymon, that's like music to my ears :)
