### ISSUE TITLE
Create a sample which show how to marshal from handler to UI components

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#577]
Whould it be useful to have a sample showing how to synchronize event to a view model with event aggregators or similar mechanism from a handler? Here is a quick example from a desk case:

It is absolutely appropriate to use the ESB to implement pub-sub to the desktop. Let me give you an example from another business domain we have been using NServiceBus both to send commands into the system from rich clients but also to receive event driven updates on the client side.

We have been building an automated guidance system for milling machines, wire-cut and sinking EDM machines, linear robots and more. The customer facing application was a WPF application which interacted with several distributed components (machine controllers and more). The controllers implemented the statemachine logic to control the machines, the job scheduling engines etc. One important part of the user experience of the rich client was to visualize the cell state at any given time. The cell state was represented by the linear robot moving from machine to machine and back to the magazines, machines constantly pushing their internal state (tool breakage, liquid temperatures, emergency stops…) to any subscriber interested. Of course the rich client also needed to interact with these components like starting and stopping a single machine, unloading chucks etc. Long story short let me explain according to this domain how a combination of publish/subscribe (events) and requests (commands) were used.

For simplicity we assume there is a single view model representing a physical machine (in reality it was a tree of view models) called MachineViewModel. I’ll throw in some pseudo code (assuming WPF, but the same applies using Winforms except the implementation details are a bit different)

Client side

	public class StartMachine
	{
		public Guid MachineId { get; set; }
	}
	
	public class MachineStarted
	{
		public Guid MachineId { get; set; }
	}
	
	public class MachineViewModel : ViewModelBase
	{
		public Guid MachineId { get; set; }
	
		public IBus Bus { get; set; }
	
		public void Start() 
		{
			Bus.Send(new StartMachine { MachineId = this.MachineId });	
		}
	}

Controller side

	public class StartMachineHandler : IHandleMessage<StartMachine>
	{
		public void Handle(StartMachine machine)
		{
			// select controller
			// asynchronously dispatch on state machine
			controller.Fire(startMachine);	
		}
	}

	public class SomewhereInTheControllerStateMachine
	{
		private void OnMachineStarted()
		{
			Bus.Publish(new MachineStarted { MachineId = machineId });
		}
	}

The tricky part
Here comes the tricky part on the client side

	public class MachineStartedHandler : IHandleMessages<MachineStarted>
	{
		public EventAggregator Aggregator { get; set; }
	
		// this is fired on a message consumer thread which doesn’t know anything about
		// UI threads. You need to somehow dispatch an event to the view model taking care of that machine. For that purpose we used an event aggregator
		public void Handle(MachineStarted message) 
		{
			Aggregator.Fire(“topic://MachineStarted/” + message.MachineId);
		}
	}

	public class MachineViewModel : ViewModelBase
	{
		public Guid MachineId { get; set; }
	
		public EventAggregator Aggregator { get; set; }
	
		public MachineViewModel() 
		{
			Aggregator.Register(“topic://MachineStarted/” + message.MachineId", this);
		}

		[Subscriber]
		public void HandleMachineStarted(object sender, EventArgs e) 
		{
			// Update view model on UI thread	
		}
	}

This is the basic mechanics behind it. Seems like a lot of code at the beginning. But most of it can be fairly easy componentized and automated as cross cutting concerns.

As you can see with this example data flows both ways. From the rich client to the controller components in the distributed system but also event driven from the controllers to the subscribers.

**Comment by distantcam** [comment]
EventAggregators have a major problem in that they're a simple pub/sub implementation that is not composable. 

Beyond just doing UI operations on the UI thread, you also have to consider merging multiple streams of data, sampling the data to avoid flooding the UI with updates, etc.

Reactive has always been the way to go with that. I think the guidance should be to push the messages onto a Reactive stream, and then you can compose your query over them like you would compose a query over some data using LINQ.

    public class MachineStartedHandler : IHandleMessages<MachineStarted>
    {
        public ISubject<MachineStarted> MachineStarts { get; set; }

        public void Handle(MachineStarted message)
        {
            MachineStarts.OnNext(message);
        }
    }

The `Messages` object can be hosted anywhere, so long as both the handlers and the ViewModels can access it.

Now, you can do some fancy things. Let's make sure our subscriber logic runs on the UI thread, and sample it every half second to avoid swamping the UI with work. That way we can have a million messages a second and it won't matter.

    MachineStarts
        .ObserveOnDispatcher() // Run the subscription with the WPF Dispatcher
        .Sample(TimeSpan.FromMilliseconds(500))
        .Subscribe(message => { /* Update UI with message data */ });

Let's say we have a `MachineStarted` and a `MachineStopped` and we want to stream those together into a single on/off value on the UI.

    MachineStarts.Select(_ => true) // MachineStarts are true
        .Merge(MachineStops.Select(_ => false)) // MachineStops are false
        .ObserveOnDispatcher()
        .Sample(TimeSpan.FromMilliseconds(500))
        .Subscribe(b => { 
            if (b) 
                machine.Background = Colors.Green;
            else
                machine.Foreground = Colors.Red;
        });

The problem with events is that they are not composable. Reactive objects are composable.

I highly recommend watching this video by Joe Albahari about "Becoming a C# Time Lord".

http://channel9.msdn.com/Events/TechEd/Australia/2013/DEV422

(Events break the 4th law of time.)

**Comment by danielmarbach** [comment]
Perfect input. Therefore I’m going to write the sample with Reactive.

Besides the implementation detail ;) Do you think it would be good to have
such a sample?

**Comment by distantcam** [comment]
Yes, I think an example would really show how to cleanly and easily do this sort of thing with Reactive.

Let me know if you need any help.

**Comment by SimonCropp** [comment]
@danielmarbach @distantcam you still working on this?

**Comment by danielmarbach** [comment]
I started once and let it go because of other things. If you feel like take
it

Am Dienstag, 23. Juni 2015 schrieb Simon Cropp :

**Comment by SimonCropp** [comment]
closing for now. feel free to reopen if u get time
