### ISSUE TITLE
Document usages of XElement or XDocument options in xml serialization

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#579]
Mostly already done by @danielmarbach in http://www.planetgeek.ch/2013/01/20/nservicebus-embedding-raw-xml-into-messages/

**Comment by danielmarbach** [comment]
@johnsimons should I bring part of this blogpost over?

**Comment by johnsimons** [comment]
:+1:

**Comment by mauroservienti** [comment]
+1

On Tue, Mar 24, 2015 at 9:36 AM, John Simons <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/docs.particular.net/issues/579#issuecomment-85399177>
> .
>



-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by danielmarbach** [comment]
As a sample or documentation on the XmlSerializer?

**Comment by mauroservienti** [comment]
an integration sample would be great, we can add guidance later if
required. Thoughts?

On Tue, Mar 24, 2015 at 9:44 AM, Daniel Marbach <notifications@github.com>
wrote:

> As a sample or documentation on the XmlSerializer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/docs.particular.net/issues/579#issuecomment-85404091>
> .
>



-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by danielmarbach** [comment]
Done as part of #644
