### ISSUE TITLE
Describe how to create a custom PersistenceDefinition

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#580]
Describe how to:
- create a PersistenceDefinition;
- Register it given a supported storage type;
- Create the related Feature
## 

Related to https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/Hk8ikaUSDVA/-rngh8e8ZrMJ

**Comment by weralabaj** [comment]
@mauroservienti is that still relevant? I'm thinking about replacing this issue with reviewing/updating this page https://docs.particular.net/nservicebus/persistence/authoring-custom, would that address your concern?

**Comment by mauroservienti** [comment]
yes, that would address the main concern. Feel free to close this one.
