### ISSUE TITLE
Document how to bulk remove inactive endpoints from ServicePulse

### ISSUE THREAD

**Issue by kbaley** [Particular/docs.particular.net#5803]
We don't have an automated way of removing inactive endpoints from ServicePulse and they can pile up depending on how they are deployed.

There's [an issue](https://github.com/Particular/ServicePulse/issues/468) to provide housekeeping in ServicePulse to remove these based on rules but until then, we have a script to remove them directly from RavenDB but it hasn't been fully vetted. We should review it and create some documentation to allow others to do this manually if they desire.

**Comment by PhilBastian** [comment]
functionality built in to SP 1.42.1 and SC 5.9.1. [Documentation](https://docs.particular.net/monitoring/heartbeats/in-servicepulse) has been updated
