### ISSUE TITLE
Feedback: 'Customizing Error Handling'

### ISSUE THREAD

**Issue by nbarnwell** [Particular/docs.particular.net#5921]
Feedback for 'Customizing Error Handling' https://docs.particular.net/nservicebus/pipeline/customizing-error-handling

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/pipeline/customizing-error-handling.md

Something is amiss. There are two nearly identical code examples, but a "warning" yellow block after each that suggests conflicting behaviour for what amounts to the same thing. E.g.:

> **Throwing the exception in the catch block will immediately forward the message to the error queue**. If a message fails due to a MessageDeserializationException the message won't be retried. If that's not desired, remove the throw from the catch block to indicate that the message has been successfully processed.

vs a little further down:

> **Throwing the exception in the catch block will forward the message to the error queue after all the configured retry attempts**. If that's not desired, remove the throw from the catch block to indicate that the message has been successfully processed.

I **think** the difference is that NServiceBus is specifically checking for serialization exceptions being thrown from behaviours as opposed to any other kind of exception, and that's what makes the difference here. However that's not really clear from the text on this page as it's written.

**Comment by ramonsmits** [comment]
@nbarnwell Thanks for raising this. I tried to improve the guidance:

- https://github.com/Particular/docs.particular.net/pull/5927

Your feedback on it is much appreciated.
