### ISSUE TITLE
Feedback: 'Using NServiceBus in Azure Functions (in-process)'

### ISSUE THREAD

**Issue by franknesse** [Particular/docs.particular.net#5951]
Feedback for 'Using NServiceBus in Azure Functions (in-process)' https://docs.particular.net/samples/azure-functions/service-bus/

Running the sample throws the following Exeption:

System.Exception: 'Could not load 'C:\Users\fn\Downloads\service-bus_asbfunctions_4\AzureFunctions.ASBTrigger.FunctionsHostBuilder\bin\Debug\net6.0\bin\Microsoft.Identity.Client.dll'. Consider excluding that assembly from the scanning.'

How to resolve this?

**Comment by tmasternak** [comment]
Hi @franknesse,

we are currently working on the fix. We will let you know once this is solved.
