### ISSUE TITLE
Update SQL Transport docs with partial DTC suppport in .NET 7

### ISSUE THREAD

**Issue by MarcWils** [Particular/docs.particular.net#5978]
As of .NET 7 distributed transactions are supported on Windows (https://github.com/dotnet/runtime/issues/715).

Docs could be updated on this part.
https://github.com/Particular/docs.particular.net/blob/fe58f43821438408e72ccec211bc3f59e892cb77/transports/sql/transactions_ambient-core-warning_sqltransport_%5B6%2C).partial.md?plain=1#L13

**Comment by bording** [comment]
Hi @MarcWils,

Thanks for the suggestion.

We've got some work to do before we'd want to make changes to the docs, so I've gone ahead and opened https://github.com/Particular/NServiceBus.SqlServer/issues/1145 to track that work.

Feel free to watch that issue for progress. I'm going to go ahead and close this issue for now.
