### ISSUE TITLE
Feedback: 'Custom Recoverability Policy'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#5983]
Feedback for 'Custom Recoverability Policy' https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/custom-recoverability-policy.md

`RecoverabilityAction.Discard` should have an XML documentation to elaborate on the outcomes of this action. Ideally, the API would be a bit more explicit. E.g. `RecoverabilityAction.SkipErrorQueue`. Which would be on par with `MoveToError`.

**Comment by DavidBoike** [comment]
@SeanFeldman are you talking about the docs or the type in Core?

**Comment by SeanFeldman** [comment]
Type in Core.
