### ISSUE TITLE
Feedback: 'NServiceBus Quick Start: Extending the system'

### ISSUE THREAD

**Issue by moehoward003** [Particular/docs.particular.net#5994]
Feedback for 'NServiceBus Quick Start: Extending the system' https://docs.particular.net/tutorials/quickstart/tutorial-extending-the-system

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/quickstart/tutorial-extending-the-system.md

When adding the "Shipping" endpoint/class, the instructions note to use .NET Core 3.1:

`dotnet new console --name Shipping --framework netcoreapp3.1`

this generates this project settings:

```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
```

And the download tutorial targets .NET 6.0, as such we get this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package NServiceBus.Extensions.Hosting does not support .NET versions older than 6.0. Please use a newer version.	Shipping	C:\Users\XXXXX\.nuget\packages\nservicebus.extensions.hosting\2.0.0\build\netcoreapp2.0\NServiceBus.Extensions.Hosting.targets	4	
```
Manually copying the following section from another project and using that addressed the issue (guessing the, 'dotnet new console --name Shipping '   command needs updating?):

```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
	<LangVersion>8.0</LangVersion>
  </PropertyGroup>
```

Also, the instructions for setting up step the Shipping handler is missing but referenced in this line:

`4. Within the Handle method, use`

 But this isn't so much of an issue as you provide the complete code for the Shipping class in the subsequent section.
 
 Thank you.

**Comment by DavidBoike** [comment]
Hi @moehoward003, thanks for the feedback! Are you trying out NServiceBus for the first time?

I did a quick fix on the tutorial. We missed the mention of `netcoreapp3.1` in the text of the tutorial when we went through and updated all of our samples and snippets to support `net6.0`.

As far as your comment on the Shipping handler, in step 2 where it says to "implement the `IHandleMessages<OrderPlaced>` interface", typically implementing an interface means not just adding the interface name to the class declaration, but also adding all the members that the interface requires.

**Comment by moehoward003** [comment]
Thanks for the follow-up. I've used NServiceBus previously and just getting refamiliarized with it.  It's very well implemented and a feature rich extension of Azure Service Bus. I especially like the ServicePulse interface. Thanks for the information.
