### ISSUE TITLE
Feedback: 'NServiceBus Quick Start: Extending the system'

### ISSUE THREAD

**Issue by moehoward003** [Particular/docs.particular.net#5996]
Feedback for 'NServiceBus Quick Start: Extending the system' https://docs.particular.net/tutorials/quickstart/tutorial-extending-the-system

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/quickstart/tutorial-extending-the-system.md
Hello, Had a question about concurrency and this Quick Start tutorial, well NServiceBus in general. I was attempting to simulate concurrent/replicated nodes and wasn't sure if my attempts truly represent a replicated instance of a node. What I did was simply launch the RetailDemo (CTRL+F5) and then launched a new instance of the "Shipping" node via "Debug=>Start New Instance" at which point two instances of "Shipping" were running. If I was to place some orders, one instance would randomly pick up the order from the topic/queue/endpoint and the two would alternate processing the shipping message. However, if I place orders enough times (every 5~10 or so orders), I get the following error noted below. The shipping message does get processed/handled fine by they other running node but the error reported for the other Shipping instances isn't noted in ServicePulse (should it be?). Is there some mechanism we need to incorporate to avoid this error or is this related to the, "LearningTransport"?

```
fail: NServiceBus.LearningTransportMessagePump[0]
      Message processing failed.
      System.IO.FileNotFoundException: Could not find file 'C:\Azure\tutorials-quickstart\.learningtransport\Shipping\.pending\de7b3eb0-a23d-4f9f-ad8e-d9fe731ae22e\bd9e3ba3-b925-4df4-bf94-e972dbe98800.metadata.txt'.
      File name: 'C:\Azure\tutorials-quickstart\.learningtransport\Shipping\.pending\de7b3eb0-a23d-4f9f-ad8e-d9fe731ae22e\bd9e3ba3-b925-4df4-bf94-e972dbe98800.metadata.txt'
         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
         at NServiceBus.AsyncFile.ReadText(String filePath, CancellationToken cancellationToken) in /_/src/NServiceBus.Core/Transports/Learning/AsyncFile.cs:line 79
         at NServiceBus.LearningTransportMessagePump.ProcessFile(ILearningTransportTransaction transaction, String messageId, CancellationToken messageProcessingCancellationToken) in /_/src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs:line 301
         at NServiceBus.LearningTransportMessagePump.ProcessFileAndComplete(ILearningTransportTransaction transaction, String filePath, String messageId, CancellationToken messageProcessingCancellationToken) in /_/src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs:line 276
         at NServiceBus.LearningTransportMessagePump.ProcessMessageSwallowExceptionsAndReleaseConcurrencyLimiter(ILearningTransportTransaction transaction, String filePath, String messageId, CancellationToken messageProcessingCancellationToken) in /_/src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs:line 256 
```

**Comment by moehoward003** [comment]
I did another silly test, I ran the same concurrency type of test, as noted in the original post, but using a demo project which implements the "native" Azure Service Bus pub/sub code and logic and it didn't throw any exceptions, where as the NServiceBus implementation noted in the original post did throw exceptions. This is the tutorial/demo project in question that didn't throw exceptions for the noted concurrency test: 
https://docs.particular.net/samples/azure-service-bus-netstandard/native-integration-pub-sub/

I was hoping to get a sense of what the underlying issue was and perhaps get consistent behavior between the two projects when conducting my test, but seems there may be a robustness issue of some sort.

**Comment by DavidBoike** [comment]
Correct. The [Azure Service Bus Pub/Sub Native Integration sample](https://docs.particular.net/samples/azure-service-bus-netstandard/native-integration-pub-sub/) didn't throw exceptions because it uses Azure Service Bus, which is a real message transport. This is still an NServiceBus implementation, so I don't really understand what you're trying to say here.

The [QuickStart tutorial code](https://docs.particular.net/tutorials/quickstart/tutorial-extending-the-system) uses the Learning Transport which is _**only**_ designed for _**learning**_. You can't assume the Learning Transport will work like Azure Service Bus does. So I would not try to conduct any "robustness" type tests with it.

**Comment by DavidBoike** [comment]
Hey @moehoward003 after seeing your comment in https://github.com/Particular/docs.particular.net/issues/5998 I'm actually now worried that I've offended you in some way due to the way you keep stressing the word "silly." I understand what you were trying to do in your test, in fact I'm pretty sure I remember attempting something similar long ago. I only meant to point out that in a production system, there would be no reason to do that, and to point out the correct way to scale "up" on one machine rather than "out" to different machines.

**Comment by moehoward003** [comment]
No worries @DavidBoike, not offended, I am just trying to better understand what is going on when I see any errors in exploring code behavior. Actually, it's my fault for not connecting the dots in that the, "LeanringTransport" strictly uses local files to conduct messaging and such (for some strange reason, I assumed it would use some remote Particular resources for this). Based on your initial reply, I figured regardless of which transport mechanism used some file sharing were being used but based on further reading, just the learning transport has this behavior and file sharing/contention isn't an issue with using other transport mechanisms. No sense in addressing the original noted error message given this isn't used beyond simple demos/POCs.
