### ISSUE TITLE
Feedback: 'Azure Service Bus Transport'

### ISSUE THREAD

**Issue by moehoward003** [Particular/docs.particular.net#5997]
Feedback for 'Azure Service Bus Transport' https://docs.particular.net/transports/azure-service-bus/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/index.md

Typo:

[Azure Service Bus Hierarchy Migration Sample](https://docs.particular.net/samples/azure-service-bus-netstandard/hierarchy-migration/)
Demonstrates how to **life** migrate an endpoint from one topic to another.

**Comment by kbaley** [comment]
Thanks for reporting. We've updated the page to remove the typo.
