### ISSUE TITLE
Feedback: 'Azure Service Bus Pub/Sub Native Integration'

### ISSUE THREAD

**Issue by moehoward003** [Particular/docs.particular.net#5998]
Feedback for 'Azure Service Bus Pub/Sub Native Integration' https://docs.particular.net/samples/azure-service-bus-netstandard/native-integration-pub-sub/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/azure-service-bus-netstandard/native-integration-pub-sub/sample.md

Running this example, I got the following error:

`The incoming request is not recognized as a namespace policy put request`
The note about, "Execute Publisher first to ensure that the topic is created", didn't address the issue when ensuring this started up first within solution=>properties=>Multiple Startup Projects and specifying Publish to run first.

The issue was that the topic didn't exist. So tutorial needs to be updated to include additional, "prerequisite" that details that the, "bundle-1" topic should be created first or the following Sleep() call to the, "TopologyManager" class:
  
```
   //Not sure why but adding a Sleep() seems to resolve this issue. 
   //Guessing by the time the, "ServiceBusAdministrationClient" is created,
   //the default topic name takes a bit of time to get established? 
   Thread.Sleep(3000); 

   await client.CreateSubscriptionAsync(new CreateSubscriptionOptions(topicPath, subscriptionName)
   {
     . . .
   }
```

Or am I doing something silly again : ) ?

**Comment by DavidBoike** [comment]
The fact that prerequisite / how-to-run type information wasn't listed until the absolute bottom of that sample was……not good.

I've fixed it in https://github.com/Particular/docs.particular.net/commit/56d3634b41659b36891c6838ef0a38ed195b7ae5.

Thank you!
