### ISSUE TITLE
Feedback: 'Azure Service Bus Hierarchy Migration Sample' (404 - 'forwardTo-bundle-to-subscribe-to')

### ISSUE THREAD

**Issue by moehoward003** [Particular/docs.particular.net#5999]
Feedback for 'Azure Service Bus Hierarchy Migration Sample' https://docs.particular.net/samples/azure-service-bus-netstandard/hierarchy-migration/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/azure-service-bus-netstandard/hierarchy-migration/sample.md

Hello,

Have two questions:

1) Any idea why I am getting this exception noted below?
When trying to run the sample code, the message exchange between the two endpoints work fine, but I get the following exception during the migration process (and Endpoint1 and Endpoint2 were not running):

```
---------------------------------- The 'bundle-to-subscribe-to' topic has been setup -----------------------------------Topics
├── bundle-to-publish-to
│   ├── Samples.ASBS.HierarchyMigration.Endpoint1
│   │   ├── $default: 1=0
│   │   ├── Event2: [NServiceBus.EnclosedMessageTypes] LIKE '%Event2%'
│   │   └── samples.asbs.hierarchymigration.endpoint1
│   └── Samples.ASBS.HierarchyMigration.Endpoint2
│       ├── $default: 1=0
│       ├── Event1: [NServiceBus.EnclosedMessageTypes] LIKE '%Event1%'
│       └── samples.asbs.hierarchymigration.endpoint2
└── bundle-to-subscribe-to
Queues
├── samples.asbs.hierarchymigration.endpoint1
└── samples.asbs.hierarchymigration.endpoint2
Unhandled exception. Azure.Messaging.ServiceBus.ServiceBusException: The incoming request is not recognized as a namespace policy put request. To know more visit https://aka.ms/sbResourceMgrExceptions. TrackingId:616741ef-047b-4093-be97-13a9c671727a_G14, SystemTracker:myservicebusnamespace001.servicebus.windows.net:bundle-to-publish-to/Subscriptions/forwardTo-bundle-to-subscribe-to, Timestamp:2023-02-08T00:02:21
Status: 404 (Not Found)

Content:
<Error><Code>404</Code><Detail>The incoming request is not recognized as a namespace policy put request. To know more visit https://aka.ms/sbResourceMgrExceptions. TrackingId:716741ef-047b-4093-be97-13a9c671727a_X14, SystemTracker:myservicebusnamespace00X.servicebus.windows.net:bundle-to-publish-to/Subscriptions/forwardTo-bundle-to-subscribe-to, Timestamp:2023-02-08T00:02:21</Detail></Error>

Headers:
Transfer-Encoding: chunked
Server: Microsoft-HTTPAPI/2.0
Strict-Transport-Security: REDACTED
Date: Wed, 08 Feb 2023 00:02:20 GMT
Content-Type: application/xml; charset=utf-8
 (MessagingEntityNotFound). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
 ---> Azure.RequestFailedException: The incoming request is not recognized as a namespace policy put request. To know more visit https://aka.ms/sbResourceMgrExceptions. TrackingId:716741ef-047b-4093-be97-13a9c671727a_X14, SystemTracker:myservicebusnamespace00X.servicebus.windows.net:bundle-to-publish-to/Subscriptions/forwardTo-bundle-to-subscribe-to, Timestamp:2023-02-08T00:02:21
Status: 404 (Not Found)
```
2) The Code walk-through states:

`This sample demonstrates how an endpoint can be migrated live and without any downtime from one topic to another`

Yet when running the migration, we were instructed to not have Endpoint1 and Endpoint2 running.  Or am I misunderstanding what, "without any downtime" is referring to?

Thanks.

**Comment by danielmarbach** [comment]
Hi @moehoward003 

The exception happens when the endpoints are not running. When they never ran they also haven't setup anything in terms of bundles, subscriptions etc that the migration approach tries to migrate. This then leads to the exception you are seeing. 

> Yet when running the migration, we were instructed to not have Endpoint1 and Endpoint2 running. Or am I misunderstanding what, "without any downtime" is referring to?

If you look at the instruction of the output it looks like the following:

```bash
----- Endpoints should be stopped ------
⚠ Make sure 'Endpoint1' and 'Endpoint2' are not running
```

For every sample run we want to make sure we start with a clean slate for demo purposes. That's why it instructs you to stop the endpoints.

Then after the cleanup is run it shows the following

```bash
----- Endpoints should be running ------
⚠ Start 'Endpoint1' and 'Endpoint2' and wait a bit until some messages are published.
```

The endpoints need to be running during the migration process. It is an online migration while the endpoints are fully functional (up and running)

I'll see if I can improve the sample a bit

**Comment by danielmarbach** [comment]
Here we go https://github.com/Particular/docs.particular.net/pull/6009

**Comment by danielmarbach** [comment]
I'm closing the issue. Should you have more questions, feel free to reopen.

Thanks
