### ISSUE TITLE
Feedback: 'Azure Service Bus lock renewal' - Output (and behavioral?) differences running locally

### ISSUE THREAD

**Issue by moehoward003** [Particular/docs.particular.net#6000]
Feedback for 'Azure Service Bus lock renewal' https://docs.particular.net/samples/azure-service-bus-netstandard/lock-renewal/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/azure-service-bus-netstandard/lock-renewal/sample.md
Hello,

Running this tutorial/sample on my local machine, I get the following output (removed timestamp for comparison):

```
Press any key to exit
INFO  --- Received a message with processing duration of 00:00:45
INFO  f2a4b624-a5cf-4ac0-a6e1-67e0872689ae: Lock renewed until 2023-02-08T17:20:15Z.
INFO  f2a4b624-a5cf-4ac0-a6e1-67e0872689ae: Lock renewed until 2023-02-08T17:20:33Z.
INFO  --- Processing completed
```

However, the output noted on the site has the output as:

```
Press any key to exit
INFO  LockRenewalBehavior Incoming message ID: 940e9a1f-fd8e-4e48-96b7-4604a544d8f2
INFO  LockRenewalBehavior Lock will be renewed in 00:00:25
INFO  LongProcessingMessageHandler --- Received a message with processing duration of 00:00:45
INFO  LockRenewalBehavior Lock renewed till 2021-02-22 05:47:40 UTC / 2021-02-21 22:47:40 local
INFO  LockRenewalBehavior Lock will be renewed in 00:00:25
INFO  LongProcessingMessageHandler --- Processing completed
INFO  LockRenewalBehavior Cancelling renewal task for incoming message ID: 940e9a1f-fd8e-4e48-96b7-4604a544d8f2
INFO  LockRenewalBehavior Lock renewal task for incoming message ID: 940e9a1f-fd8e-4e48-96b7-4604a544d8f2 was cancelled.
```
I realize the site notes that, "Running the sample produces output **similar** to the following:" but just wanted to confirm that based on my output and what is noted on the site, is this expected? Aside from the logging, the number of lock renewals differ which is what I am more concerned about. 

Thanks

**Comment by ramonsmits** [comment]
@moehoward003 As a sidenode what version of NServiceBus are you using? Instead of relying on the sample I highly recommend upgrading as the sample isn't needed any more on the latest version.

> In version 3 and higher of the Azure Service Bus transport, [lock renewal is built into the transport](https://docs.particular.net/transports/azure-service-bus/configuration#lock-renewal), and custom lock renewal is no longer required. This sample will be removed in the future.

**Comment by moehoward003** [comment]
> @moehoward003 As a sidenode what version of NServiceBus are you using? Instead of relying on the sample I highly recommend upgrading as the sample isn't needed any more on the latest version.
> 
> > In version 3 and higher of the Azure Service Bus transport, [lock renewal is built into the transport](https://docs.particular.net/transports/azure-service-bus/configuration#lock-renewal), and custom lock renewal is no longer required. This sample will be removed in the future.

I was using the latest version offered on the date of the original post. And your notes make sense and we can mark this as resolved. Thanks.
