### ISSUE TITLE
Feedback: 'Non-Durable Messaging'

### ISSUE THREAD

**Issue by mstavrev** [Particular/docs.particular.net#6018]
Feedback for 'Non-Durable Messaging' https://docs.particular.net/nservicebus/messaging/non-durable-messaging

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/non-durable-messaging.md

There is no guidelines for RabbitMQ on how to change existing code that used either DisableDurableMessages() on endpoint configuration or via convention using Conventions().DefiningExpressMessagesAs(...).

**Comment by DavidBoike** [comment]
Hi @mstavrev,

I just added a link in https://docs.particular.net/nservicebus/messaging/non-durable-messaging#effect-on-transports-rabbitmq to https://docs.particular.net/transports/rabbitmq/#controlling-delivery-mode which I believe connects the dots that need to be connected.

Does that help?
