### ISSUE TITLE
Feedback: 'Transport configuration changes'

### ISSUE THREAD

**Issue by mstavrev** [Particular/docs.particular.net#6022]
Feedback for 'Transport configuration changes' https://docs.particular.net/nservicebus/upgrades/7to8/transport

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/7to8/transport.md

There is no hint on how to address the now dropped EndpointConfiguration.DoNotCreateQueues() functionality. I am not aware of the other transports, but using RabbitMQ there  are many real life cases, where a queue may already exist on the broker and would have different definition (for example in terms of maximum size or expiration settings) than the one used for the default queue creation logic.

**Comment by mstavrev** [comment]
I've looked at the v8 code changes. Looks like now queue creation (for RabbitMQ) is controlled by EnableInstallers(). Can you, please confirm and augment the documentation?

**Comment by danielmarbach** [comment]
Hi @mstavrev 

Thanks for the feedback. I think the documentation that we have today should indeed be improved a bit. Some of the obsoletes we have in place seem to indicate that there is no relationship to installers, while in fact queue creation is now tied to the installers in v8.

So in case you want to get queue creation back up you need to call `EnableInstallers`.

I will clarify a few things internally with the people involved in the changes so that we can improve our documentation.

**Comment by timbussmann** [comment]
> I've looked at the v8 code changes. Looks like now queue creation (for RabbitMQ) is controlled by EnableInstallers().

Yes that's correct. With RabbitMQ, queue creation was always enabled by default and could be opted-out with `DoNotCreateQueues`. Now, queues are created if installers are enabled with `EnableInstallers`.

> but using RabbitMQ there are many real life cases, where a queue may already exist on the broker and would have different definition (for example in terms of maximum size or expiration settings) than the one used for the default queue creation logic.

If the queue already exists, the existing queue shouldn't be modified even if installers are enabled.

I'll try to clarify the documentation on this a bit further, especially the approach for queue creation when using RabbitMQ.

**Comment by timbussmann** [comment]
@mstavrev I've raised this small PR to point towards the installers API which contains more details about how to influence installation behavior: https://github.com/Particular/docs.particular.net/pull/6028. Do you have any additional suggestions about helpful additions to the documentation?

**Comment by mstavrev** [comment]
Thanks for the confirmation. I've adjusted my implementation accordingly and indeed it works as specified.
You may close the case. Thank you.
