### ISSUE TITLE
Feedback: 'Manage ServiceControl instances via PowerShell'

### ISSUE THREAD

**Issue by Jamie-Clayton** [Particular/docs.particular.net#6025]
Feedback for 'Manage ServiceControl instances via PowerShell' https://docs.particular.net/servicecontrol/installation-powershell

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/installation-powershell.md

Please add the following examples for removing an existing Service Control Endpoint via Powershell. 
I found adding a new one and then trying to rename it (fat fingers), can be harder than expected.

``` Powershell
Get-UrlAcls | ? Port -eq 33333 | Remove-UrlAcl
Get-UrlAcls | ? Port -eq 33334 | Remove-UrlAcl
Get-UrlAcls | ? Port -eq 44444 | Remove-UrlAcl
Get-UrlAcls | ? Port -eq 44445 | Remove-UrlAcl
```

**Comment by andreasohlund** [comment]
Thanks for the feedback, just to make sure I understand. 

You installed a new instance but made an error and then tried to manually rename it? 

>Please add the following examples for removing an existing Service Control Endpoint via Powershell.

We automatically remove the urlacls when using the [remove instance command](https://docs.particular.net/servicecontrol/installation-powershell#servicecontrol-instance-cmdlets-and-aliases-removing-an-instance) did you run that command?

**Comment by Jamie-Clayton** [comment]
**Background**
I inherited a Production Server with some very old instances of NServicebus Control not running. 
It looks like someone had tried to re-install editions in the past but tried lots of different ports to make it work. I suspect some manual service stopping and folder deleting.
I think some newer editions of Service control were installed along the way, both manually and via Chocolatey + Powershell Core. 
Basically, the server was in an unhealthy state, which I'm trying to repair via the GUI, but found it was easier to run the Powershell commands to do the job.

**CICD**
* We are looking to automate the deployment of Service Control (Audit and Monitoring) with the Service Pulse Web site onto windows servicer with Powershell.
* Next we will deploy the Docker container version of these Tools into our AWS Fargate services, once I work out how to manage the persistence of RavenDB through an upgrade cycle.
* Determine how to restrict the Service Pulse website monitoring for our software engineers
* Integrate any Rest API features, logs, and metrics from these great tools, into our monitoring tools (in our case DataDog), so we are back to a single monitoring UI.
