### ISSUE TITLE
Feedback: 'ServiceControl Audit instances'

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/docs.particular.net#6029]
Feedback for 'ServiceControl Audit instances' https://docs.particular.net/servicecontrol/audit-instances/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/audit-instances/index.md

Isn't the Audit instance now _required_ with ServiceControl v4.x if you are monitoring your NServiceBus messages? The documentation states:

> A single ServiceControl instance can have zero or more ServiceControl Audit secondary instances attached to it.

But this statement seems misleading, if not actually correct. Should it better be stated:

> When auditing messages in your NServiceBus applicaton, a single ServiceControl instance must have at least one ServiceControl audit instance. A ServiceControl instance can optionally have zero or more ServiceControl Audit remote instances attoched to it, should additional capacity be needed for processing these messages in an application where there is a high volume of auditable messages.

Overall, I find the documentation quite unclear, inconsistent, and not defining the terminology used (or at least, usages of terminology that are not defined in the context in which it is encountered, but in some other seemingly distant and unrelated area of the documentation) or inconsistent uses of terminology in many areas. In addition, the fact that the documentation is not "versioned" by ServiceControl version makes it hard to compare documentation for the current supported version and previous versions for those who are upgrading.

I've literally had to read _everything_ at least 3 times to gain a clear(er) picture of a ServiceControl 4 environment (coming from a ServiceControl 1.x environment). This is no easy task because the information is not well organized, scattered throughout many disparate topical areas.

**Comment by fourpastmidnight** [comment]
@andreasohlund Thank you for updating the documentation with my suggested feedback. That looks a lot clearer with respect to ServiceControl v4.x!

I look forward to seeing better documentation that leads implementers on a journey through defining the different components of the solution, the required deployment topology of ServiceControl, with a section on the optional components, the general requirements for the different components (e.g., do Monitoring Instances really require the same resources as the Primary and Audit instances?), and then sections on implementing both a new installation as well as upgrading. I realize that a lot of this content is already there, it just needs better organization and clarification.

I look forward to these updates.

**Comment by andreasohlund** [comment]
With https://github.com/Particular/docs.particular.net/pull/6032 merged I'll close this one as done. Feel free to subscribe to the mentioned issues if you want to be in the loop regarding our restructuring of the docs for ServiceControl.

Thanks again for the feedback!
