### ISSUE TITLE
Feedback: 'Installing ServiceControl'

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/docs.particular.net#6040]
Feedback for 'Installing ServiceControl' https://docs.particular.net/servicecontrol/installation

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/installation.md

There is no documentation on how to unattended install the ServiceControl Management Utility, specifically, what command-line switches are available.

I had this working for ServiceControl 1.x, 2.x and 3.x, but it seems not to be working in 4.x. That's _not_ to say there's something wrong with 4.x&mdash;it very well could be me since I've had to significantly update my deployment scripts for SC 4 vs. previous versions. BUT, still, it should be documented what command-line switches are available for the main EXE installer that's provided on your Releases page.

**Comment by fourpastmidnight** [comment]
OK, I was able to execute the installer with `/?` and get the available parameters. And my install failing to work properly is _definitely_ me 😉 &mdash;I forgot that SC 4 requires .NET 4.7.2 😄 

Instead of listing out the available switches, though, you could at least reference that getting help for unattended install can be done by executing the installer with `/?`. (I've run into bad EXE "wrapper" installers that provide _NO_ help...and that' a real pain, so this is why I sought out docs in the first place. I'm _very happy_ that this information is being provided. Of course, I also know you guys use WiX, but I conveniently forgot that momentarily 😜  Sorry.)

**Comment by fourpastmidnight** [comment]
And actually, the set of parameters to the installer _did_ change. But that's neither here nor there right now, my VM doesn't meet the pre-reqs for SC 4. But it would be great to have that documented 😄

**Comment by dvdstelt** [comment]
@fourpastmidnight

Can you let me know if there's currently an open question or expectation?
Also, can you let me know why you're using the (Wix) installer unattended? If you have the Powershell module that you referred to in another issue, why would you still want to install this unattended?

**Comment by fourpastmidnight** [comment]
That, indeed is a  good question that I _immediately_ asked myself after creating this issue! 😉 The way I was doing this in previous versions, is I would unattended install/upgrade the ServiceControl Management Utility, which puts the ServiceControl Management module onto my VM. Then I would use the module to install/upgrade the instances. This is "just the way I did it".

But when I started running into problems running the installer unattended, then I asked myself, why? Why am I trying to install the SCMU? I'm not using the management utility for _anything else_! So I just downloaded your Zip archive and discovered it contains the bare minimum of what I need. And so now I'm no longer using the SCMU installer. 😄 Mind you, my previous deployment scripts have been running flawlessly for 5 years. But, with this upgrade, everything changed, and consequently, I reevaluated my choices 😄  Sometimes, you're too close to the trees to see the forest! ALso, 5 years ago, I _really_ didn't know ServiceControl that well. I'm nearly an expert now 😆  J/k, I'm sure there's loads more I still don't know!

Thanks for responding back to me.

**Comment by dvdstelt** [comment]
Hehehe, no worries, we know the feeling. Sometimes our users provide us with insights that surprise ourselves. So _thank you_ for providing feedback and asking questions. We value the contributions you make so we can improve our documentation and way we think about stuff. 👍🏻

**Comment by fourpastmidnight** [comment]
I left this open in case you guys were opening a PR for any documentation changes. If you are not, please feel free to close this, as this issue no longer affects me since I'm using the ZIP distribution. And thanks again for your replies!

**Comment by dvdstelt** [comment]
We now have the Powershell cmdlets and we've never had the question for SCMU before, afaik. I registered it internally, so if someone asks for it, we'll have an answer. But for now we won't update the documentation, so I'll close the issue.
