### ISSUE TITLE
All samples should have a list of prerequisites  

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#609]
raven,msmq,perfcounters etc. whatever the sample needs to run

**Comment by hmemcpy** [comment]
Should this be put in the page header and generated with the backend, or add this to the markdown body directly?

**Comment by weralabaj** [comment]
@SimonCropp isn't that addressed by listing used NuGets? Can we close?

**Comment by SimonCropp** [comment]
Not really. Some need sqlexpress. Some need rabbit. Some need azure. I have not worked out a way to do this consistently

**Comment by SimonCropp** [comment]
moved to https://github.com/Particular/DocsEngine/issues/300
