### ISSUE TITLE
Feedback: 'Install ServicePulse in IIS'

### ISSUE THREAD

**Issue by AntonSigur** [Particular/docs.particular.net#6116]
Feedback for 'Install ServicePulse in IIS' https://docs.particular.net/servicepulse/install-servicepulse-in-iis

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicepulse/install-servicepulse-in-iis.md

Missing information in documentation that you are required to install and enable requestRouter_amd64 for the rewrite / reverse proxy for service control. E.g. install the package:

https://www.microsoft.com/en-us/download/confirmation.aspx?id=47333

In the IIS management, enable the feature "Enable proxy" checkbox.

See MS documentation: https://learn.microsoft.com/en-us/iis/extensions/url-rewrite-module/reverse-proxy-with-url-rewrite-v2-and-application-request-routing

**Comment by soujay** [comment]
@AntonSigur - Thank you for your feedback. We will review and update any missing information.
