### ISSUE TITLE
Azure samples

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#612]
[Current Azure samples](https://github.com/Particular/nservicebus.azure.samples/) are more of a showcase than actual samples. Replace Azure samples with appropriate ones following current samples conventions and make https://github.com/Particular/nservicebus.azure.samples/ private repo until can be retired.

Sample to build:
- [x] [Azure storage based databus](https://github.com/Particular/docs.particular.net/pull/629)
- [x] [Azure cloudservices dynamic hosting](https://github.com/Particular/docs.particular.net/pull/640)
- [ ] Queues on separate accounts/namespaces
- [x] Azure storage based pub/sub
- [x] Azure storage based saga
- [x] Azure storage based timeout
- [x] Azure storage queue transport
- [x] Azure servicebus transport
- [ ] Azure cloudservices hosting
- [ ] Azure cloudservices configuration source (.cscfg)
- [ ] Configured for long running tasks (batch size)

**Comment by SimonCropp** [comment]
cant all the storages be used in one sample?

**Comment by SimonCropp** [comment]
"Configured for long running tasks" sounds more like a docs page. is there some kind of special value in that as a sample?

**Comment by SimonCropp** [comment]
ok i added a few more samples that cover most of this http://docs.particular.net/samples/azure/

if u feel strongly about any of the others please add a PR

**Comment by SeanFeldman** [comment]
Thank you @SimonCropp 
I'll keep this issue on my list, a few more things would be nice to add.
