### ISSUE TITLE
Guide users to use a behavior/custom substorage implementation instead of IAuthorizeSubscriptions 

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#613]
Related to https://github.com/Particular/NServiceBus/issues/2725

**Comment by danielmarbach** [comment]
@johnsimons how about you write that guidance? ;)

**Comment by johnsimons** [comment]
@danielmarbach any pointers what to do here ?
So this guindance would be only for msmq users right ?

So I write a behaviour that intercepts a subscribe/unsubscribe message and authorizes it against some security table, is that what we go with ?

**Comment by danielmarbach** [comment]
I think @simoncropp has more context
