### ISSUE TITLE
Feedback: 'Recoverability'

### ISSUE THREAD

**Issue by shirin-monzavi** [Particular/docs.particular.net#6131]
Feedback for 'Recoverability' https://docs.particular.net/nservicebus/recoverability/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/index.md

Dear sir or madam,

I am one of your fan and I need to use recoverability approach.
what does it mean an endpoint is scaled-out?
it means we can have multiple instance of an endpoint?
"
If an endpoint is scaled-out the number of processing attempts increase if instances are retrieving messages from the same queue and the transport does not have a native delivery counter."

your faithfully

**Comment by soujay** [comment]
Hi @shirin72,


> what does it mean an endpoint is scaled-out? it means we can have multiple instance of an endpoint?

One of the ways to scale out is by  deploying multiple instances of an endpoint. Please see the document on [Scaling with NServiceBus](https://docs.particular.net/nservicebus/architecture/scaling) for more details.

> If an endpoint is scaled out, the number of processing attempts increase if instances are retrieving messages from the same queue and the transport does not have a native delivery counter.

Yes, that's true for transports that do not provide a native delivery counter. But if you use transports like Azure Service Bus, which provides a native delivery counter, the counter gets incremented once an endpoint instance fetches a message from the queue. That way, the number of retry attempts remain the same irrespective of the scaling of the endpoint.
