### ISSUE TITLE
Gateway Sample throws an exception when price updated from Webclient

### ISSUE THREAD

**Issue by soujay** [Particular/docs.particular.net#6144]
[Geteway Sample](https://docs.particular.net/samples/gateway/)  throws the following exception while trying to deserialize the message.

**Steps to reproduce:**
1) Download and run the [Geteway Sample](https://docs.particular.net/samples/gateway/) from docs site.
2) The sample launches 2 console windows and one browser window at http://[localhost:31639](http://localhost:31639/)/
3) On the browser window, Click the button to make a JSONP request to the nservicebus gateway
4) The following exception is received in the "Headquaters" console window.

**Exception:**
```
 ERROR Moving message 'fabed38c-f858-4549-8316-f3c4a9eca595' to the error queue 'error' because processing failed due to an exception:
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message.
 at NServiceBus.Serializers.SystemJson.JsonMessageSerializer.Deserialize(ReadOnlyMemory`1 body, IList`1 messageTypes) in \Particular\NServiceBus\src\NServiceBus.Core\Serializers\SystemJson\JsonMessageSerializer.cs:line 41
```

![image](https://github.com/Particular/docs.particular.net/assets/88632084/476334d7-af53-4e07-a1cf-0a6b33f7b11e)

**Comment by WilliamBZA** [comment]
The exception is because the website is sending the message serialized as XML whereas the endpoints are configured to use JSON.
