### ISSUE TITLE
Feedback: 'Message type detection'

### ISSUE THREAD

**Issue by rlerch** [Particular/docs.particular.net#6160]
Feedback for 'Message type detection' https://docs.particular.net/nservicebus/messaging/message-type-detection

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/message-type-detection.md

This doesn't seem to be exactly the case. Using the System.Text.Json serializer the NServiceBus.EnclosedMessageTypes header is the fully qualified type name with assembly information including version. NServiceBus seems to be able to detect the correct message types by using only the FullName since I am able to subscribe to the message using a copy of the class in a different assembly provided that the namespace and class name match the original. 

In this case it seems that the NSerivceBus.EncludedMessageTypes header is ignored which is contrary to the documentation. 

Thanks!

**Comment by danielmarbach** [comment]
@rlerch thanks for reaching out. I have a few clarification questions

- Are you using NServiceBus 8.1.x with the System.Text.Json serializer or another version with the previous community serializer?
- Have you enabled or disabled type [dynamic type loading](https://docs.particular.net/nservicebus/serialization/#security-dynamic-type-loading)?
- Have you enabled or disabled [message type inference](https://docs.particular.net/nservicebus/serialization/#security-message-type-inference)?
- Was the message type that was specified in the `NServiceBus.EnclosedMessageTypes` header available locally somewhere in the assembly references? Or was it not?
- Do you have any behaviors that might modify the `NServiceBus.EnclosedMessageTypes` header?

Thanks
Daniel

**Comment by rlerch** [comment]
> @rlerch thanks for reaching out. I have a few clarification questions
> 
> * Are you using NServiceBus 8.1.x with the System.Text.Json serializer or another version with the previous community serializer?
> * Have you enabled or disabled type [dynamic type loading](https://docs.particular.net/nservicebus/serialization/#security-dynamic-type-loading)?
> * Have you enabled or disabled [message type inference](https://docs.particular.net/nservicebus/serialization/#security-message-type-inference)?
> * Was the message type that was specified in the `NServiceBus.EnclosedMessageTypes` header available locally somewhere in the assembly references? Or was it not?
> * Do you have any behaviors that might modify the `NServiceBus.EnclosedMessageTypes` header?
> 
> Thanks Daniel

Hi Daniel,

- We are using NServiceBus 7.8.2 with the NServiceBus.Json community serializer, soon to update to NServicebus 8.1.x with the official System.Text.Json Serializer
- We did not enable or disable dynamic type loading
- We did not enable or disable message type inference
- The assembly type specified in the `NServiceBus.EnclosedMessageTypes` was not available locally to the receiving application
- No behaviors were required to get it to use the FullName to resolve the type

**Comment by danielmarbach** [comment]
@rlerch thanks for the update. Wow you even went further digging into the NServiceBus codebase :bow: (FYI I'm showing my appreciation but nobody would expect you to do that ;) )

Automatically falling back to use the full type name has apparently been introduced into NServiceBus 7.4 as part of https://github.com/Particular/NServiceBus/pull/5696 addressing the following issue https://github.com/Particular/NServiceBus/issues/5276 but the feature introduced doesn't seem to be mentioned in the documentation which was probably an oversight. I will do some more digging and then try to update the relevant documentation while getting a review from the people involved at the time.

**Comment by rlerch** [comment]
Thanks very much @danielmarbach !
-- Ryan.

**Comment by danielmarbach** [comment]
@rlerch What do you think about these small improvements? https://github.com/Particular/docs.particular.net/pull/6169

**Comment by danielmarbach** [comment]
@rlerch I have merged a few improvements. Thanks for your input!
