### ISSUE TITLE
Feedback: 'Scaling with NServiceBus'

### ISSUE THREAD

**Issue by shirin-monzavi** [Particular/docs.particular.net#6175]
Feedback for 'Scaling with NServiceBus' https://docs.particular.net/nservicebus/architecture/scaling

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/architecture/scaling.md

Dear sir/madam,
I Have read your article but have some issues with it.
In part of high availability, it is stated that we need to use versioning and it is perfectly fine. after that, it is stated the stages of it:
first phase: upgrade one node to a new version includes: endpoints and its messages.
second phase: the old node is still processing messages and it is great.
third phase: what does it mean? Bring the upgraded version of Finance back up so it can start processing version 1 messages. It means, that I need to get a backup from the new version? and why when I get a back up I can process the old version of the message?
Then I have to upgrade the old version to a new one and finally upgrade the sale endpoint. 
best regards,
shirin monzavi

**Comment by abparticular** [comment]
Hello @shirin-monzavi ,

The documentation you are referring to describes how to use the Competing Consumer pattern to upgrade a logical endpoint without interrupting message processing.  The example shown uses two instances of the logical Finance endpoint - let's call them Instance A and Instance B

In the second phase, the documentation mentions to "take down" one endpoint instance of Finance (e.g. Instance A) and upgrade it to version 2 of the message assembly Finance.Messages.  So Instance A is now offline and being upgraded, but Instance B is still processing version 1 messages.

Phase 3 involves bringing the upgraded instance of Finance "back up".  Said another way, this means bringing Instance A back online.  After it has been upgraded, Instance A can process both version 1 and version 2 messages.

Phase 4 repeats the process of upgrading a Finance endpoint, but this time Instance B is the one that is taken offline, upgraded, and then brought back online.

After both instances of the Finance endpoint have been upgraded, the Sales endpoint can be safely upgraded to publish version 2 messages.

Does that make sense?

**Comment by shirin-monzavi** [comment]
Dear MR, Abparticular,
I really appreciate you I thought that Back up means that I have to get a backup from instance1. 
Now it makes sense. 
Wish you all the best,
Shirin Monzavi
