### ISSUE TITLE
Remove all Raven/Esent related settings for ServiceControl.Audit Instance settings

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#6217]
Since RavenDB 5, the following Esent related settings are no longer applicable:

- Raven/Esent/LogsPath
- Raven/Esent/MaxVerPages

**Comment by awright18** [comment]
Thanks for opening this issue. 

Could you provide the context of why you opened this issue?

**Comment by TraGicCode** [comment]
Hey @awright18 ,

The RavenDB Audit Instance no longer utilizes RavenDB 3.x, and consequently, it no longer relies on ESent but instead utilizes Voron.  I'm wanting to fix up the documentation to either mention this or to remove it all together. I maintain an open-source puppet module to install and configure servicecontrol and alot of times the documentation is outdated or missing information.  This causes me to have to dive into the sourcecode and sometimes ask on slack or in a github issue.

**Comment by ramonsmits** [comment]
The RavenDB 3.5 storage engine still exists and our documentation also exists for older versions that are still supported according to our support policy.

**Comment by kbaley** [comment]
@TraGicCode I'll close this as not planned since we still need the settings documented. We added [some clarification](https://github.com/Particular/docs.particular.net/pull/6220) to the docs to indicate the settings apply only to RavenDB 3.5 instances
