### ISSUE TITLE
Incorrect SQS S3BucketForLargeMessages documentation

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#6230]
Feedback for 'S3BucketForLargeMessages' https://docs.particular.net/transports/sqs/configuration-options#s3bucketforlargemessages

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sqs/configuration-options.md

Several issues with that section:
1. The title doesn't really match the current configuration API name. It should be updated or use some more readable title to indicate what this setting is about.
2. The [KeyPrefix subsection](https://docs.particular.net/transports/sqs/configuration-options#s3bucketforlargemessages-s3keyprefix) indicates that the parameter is optional, which it doesn't seem to be given the [settings validation code](https://github.com/Particular/NServiceBus.AmazonSQS/blob/master/src/NServiceBus.Transport.SQS/Configure/S3Settings.cs#L28).

**Comment by SzymonPobiega** [comment]
Going to be addressed in https://github.com/Particular/docs.particular.net/pull/6252
