### ISSUE TITLE
Feedback: 'Using TransactionalSession with Entity Framework and ASP.NET Core'

### ISSUE THREAD

**Issue by bosjaH** [Particular/docs.particular.net#6239]
Feedback for 'Using TransactionalSession with Entity Framework and ASP.NET Core' https://docs.particular.net/samples/transactional-session/aspnetcore-webapi/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/transactional-session/aspnetcore-webapi/sample.md

The .NET 7 sample will always commit the transactional session, even when an exception is thrown in the controller. Unlike with middleware, the result needs to be explicitly checked when using filters. The change below should make it behave the same as the middleware based sample.

```
    public async Task OnResourceExecutionAsync(ResourceExecutingContext context, ResourceExecutionDelegate next)
    {
        if (context.ActionDescriptor.Parameters.Any(p => p.ParameterType == typeof(ITransactionalSession)))
        {
            var session = context.HttpContext.RequestServices.GetRequiredService<ITransactionalSession>();
            await session.Open(new SqlPersistenceOpenSessionOptions());

            var result = await next();

            if (result.Exception != null)
            {
                await session.Commit();
            }
        }
        else
        {
            await next();
        }
    }
```

**Comment by cquirosj** [comment]
@bosjaH, good catch; thanks for the feedback! Would you consider creating a PR?

**Comment by awright18** [comment]
@bosjaH Thank you for your contribution. The [sample](https://docs.particular.net/samples/transactional-session/aspnetcore-webapi/) docs and downloadable code that you pointed to has been updated.
