### ISSUE TITLE
Feedback: 'Building endpoints with ASP.NET Core' & 'NServiceBus.Extensions.Hosting'

### ISSUE THREAD

**Issue by bbrandt** [Particular/docs.particular.net#6240]
The statements on these 2 pages seem to be in conflict.  Do you know which is correct?  Do we need to manually configure NServiceBus logging to route to .NET Logging when using `NServiceBus.Extensions.Hosting` v2 or higher?

----

Feedback for 'Building endpoints with ASP.NET Core' https://docs.particular.net/samples/netcore-reference/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/netcore-reference/sample.md

This page says:
> The NServiceBus.MicrosoftLogging community NuGet package should be installed to use the Microsoft.Extensions.Logging library.

----
Feedback for 'NServiceBus.Extensions.Hosting' https://docs.particular.net/nservicebus/hosting/extensions-hosting

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/extensions-hosting.md

But this page says:
> NServiceBus logging is automatically configured to use the [logging configured](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging) for the [generic host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host); no NServiceBus specific logging configuration is needed.

**Comment by cquirosj** [comment]
@bbrandt, you are correct, you don't need to manually configure NServiceBus logging when you are using NServiceBus.Extensions.Hosting. It does it for you. Good catch, the sample needs to be updated.

**Comment by cquirosj** [comment]
This [PR](https://github.com/Particular/docs.particular.net/pull/6247) fixes the sample. Closing.
