### ISSUE TITLE
Feedback: 'Third party integration'

### ISSUE THREAD

**Issue by Jokelab** [Particular/docs.particular.net#6246]
This page shows that the [NServiceBus.EnclosedMessageTypes header](https://docs.particular.net/nservicebus/messaging/headers#serialization-headers-nservicebus-enclosedmessagetypes) can be omitted, starting from NSB 7.4:
https://docs.particular.net/nservicebus/messaging/third-party-integration

While this page says that you need to provide either the NServiceBus.EnclosedMessageTypes header or specify the type through a $type or a root node, depending on the serializer:
https://docs.particular.net/nservicebus/messaging/message-type-detection

Besides that, I tried to use the sample on this page: https://docs.particular.net/samples/azure-service-bus-netstandard/native-integration/
When the NServiceBus.EnclosedMessageTypes is omitted, the sample doesn't work anymore. Am I doing something wrong there?

**Comment by cquirosj** [comment]
@Jokelab, I will review the samples you mentioned and check whether they need an update. I will also reproduce the issue you ran into with the sample and get back to you. Thanks for reporting this.

**Comment by cquirosj** [comment]
@Jokelab, the following text from https://docs.particular.net/nservicebus/messaging/third-party-integration states that the attribute is automatically populated when the attribute is missing, [but the value used to populate NServiceBus.EnclosedMessageTypes](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Incoming/InferredMessageTypeEnricherBehavior.cs#L13C59-L13C59), is reliant on other means to determine the type, like, for example, specifying the type through a $type or a root node, depending on the serializer. I agree that this text can be improved to clarify that.
> Starting from NServiceBus version 7.4, the [NServiceBus.EnclosedMessageTypes header](https://docs.particular.net/nservicebus/messaging/headers#serialization-headers-nservicebus-enclosedmessagetypes) is automatically populated when missing. When using NServiceBus version 7.3 and below, the sender should set that header.

Here is the sample where you removed the line for NServiceBus.EnclosedMessageTypes but with modifications to make the serialzier add $type.
- https://github.com/Particular/docs.particular.net/pull/6270

**Comment by Jokelab** [comment]
Thank you for clearing that up for me! I interpreted it as if the type would be automatically inferred when the NServiceBus.EnclosedMessageTypes header is missing.

**Comment by cquirosj** [comment]
Closing with [this change](https://github.com/Particular/docs.particular.net/pull/6276) addressing the feedback.
