### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Multiple Endpoints'

### ISSUE THREAD

**Issue by jazuraff** [Particular/docs.particular.net#6346]
Feedback for 'NServiceBus Step-by-step: Multiple Endpoints' https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md

in section https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/#exercise-sending-to-another-endpoint:
- its not specified to make sure to add UseSerialization<SystemJsonSerializer>() so they will receive runtime exceptions when the consumer tries to deserialize.

i did notice the warning above but it doesnt explicitly note to make sure you add it
"For example, if the ClientUI endpoint used .UseSerialization<XmlSerializer>() while the Sales endpoint used .UseSerialization<JsonSerializer>(), the Sales endpoint would not be able to understand the XML-serialized messages it received from ClientUI since it would be expecting JSON."

**Comment by soujay** [comment]
@jazuraff : The page has been [updated](https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/#exercise-sending-to-another-endpoint) based on your feedback
