### ISSUE TITLE
Update ServiceControl powershell docs to indicate powershell 7.2 requirement

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#6360]
There should be a callout here indicating that powershell 7.2 and above is required.

https://docs.particular.net/servicecontrol/powershell

**Comment by ramonsmits** [comment]
@TraGicCode that is correct, version 5+ requires Powershell 7.2+. We mentioned it at https://docs.particular.net/servicecontrol/upgrades/4to5/ but not here.

Thanks!
