### ISSUE TITLE
Feedback: 'NServiceBus Quick Start' fails in Chrome

### ISSUE THREAD

**Issue by NNPhilJordan** [Particular/docs.particular.net#6381]
Same error occurs in both non-secure(:5000) and secure(:49205) windows. Looking for advice.
VS info: 
Microsoft Visual Studio Professional 2022
Version 17.8.3
VisualStudio.17.Release/17.8.3+34330.188
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ASP.NET and Web Tools   17.8.358.6298
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.8.358.6298
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.8.358.6298
Azure Functions and Web Jobs Tools

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.8.3.2358002+8c7fb27bf8e8d4f9ff8080b624b35bca5e812e97
Provides languages services for ASP.NET Core Razor.

SonarLint for Visual Studio   7.4.0.80741
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   17.8.119.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20920.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23475.2+10f956e631a1efc0f7f5e49c626c494cd32b1f50
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Feedback for 'NServiceBus Quick Start' https://docs.particular.net/tutorials/quickstart/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/quickstart/tutorial.md
![image](https://github.com/Particular/docs.particular.net/assets/84084931/e4ded052-e36e-4bba-bb41-9da6157781e7)

**Comment by mauroservienti** [comment]
Thanks for raising this, @NNPhilJordan.

I can reproduce the problem on my macOS Sonoma using Rider and Microsoft Edge.

<img width="538" alt="Screenshot 2023-12-29 at 10 24 45" src="https://github.com/Particular/docs.particular.net/assets/1325611/8207c7bb-0c4b-44b7-b325-c25f6b2a1e97">

Interestingly, if I create and launch an empty web application project, it works as expected. Soon after that, the quick start works. But if I restart the quick start webserver, it stops working again.

I'll further investigate.

**Comment by mauroservienti** [comment]
Changing the port in the ClientUI `launchSettings.json` configuration file from 5000 to 5001 fixed the issue on my machine. Let me know if the workaround works for you as well.

**Comment by mauroservienti** [comment]
Digging deeper, I discovered that port 5000 is used on macOS by AirPlay (ControlCE process/app), and that prevents the IDE web server from binding to that port, causing the above error.

Can you also check on your Windows machine if port 5000 is in use?

(`netstat -a -n -p tcp -o` should list ports in use on Windows)

**Comment by NNPhilJordan** [comment]
**Thanks Mauro for your replies!** No luck with any of the proposed solutions. Ports 5000, 5001 are not in use at anytime or when app is running. Windows network diagnostics is no help - just fails in troubleshooter. Chasing through some other options at this time.

**Comment by mauroservienti** [comment]
Please try the following:

- create a new web application project
- run it
- if it works as expected:
  - stop the project
  - look at the `launchSettings.json` configuration file and copy the port set there
- apply the same value to the quick start ClientUI `launchSettings.json` file, replacing the default `5000`
- try the quick start again

We have a bigger issue if the sample web application doesn't work. Otherwise, the issue is confined to port 5000.

Let me know what happens.

**Comment by NNPhilJordan** [comment]
Hi! Went and created a WebApp as you suggested - success! Then I went and re-ran the NService demo and the app is now working! Thanks!

**Comment by NNPhilJordan** [comment]
Mauro - Thanks for your patience on my slow reply!
