### ISSUE TITLE
Guidance for receiving messages in web applications

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#641]
Similar to #638 Publishing from Web Applications. Actually came out of review of that article. Here is some content that got cut out to eventually go here. This content is not organized in any way. Just a dump of "already written words."

**Web App Recycling** - Prior to IIS 7.5 introducing the AlwaysRunning feature (AKA AlwaysOn), web applications not receiving could be recycled or idled at any time, which would result in incoming messages building up in an input queue, without an application actively processing them.
- With IIS 7.5 and later, IIS supports AlwaysRunning mode.
- IIS is no longer the only way to host web applications, which can now be hosted by [OWIN](http://owin.org/)/[Katana](http://www.asp.net/aspnet/overview/owin-and-katana), [NancyFx](http://nancyfx.org/), [FubuMVC](http://mvc.fubu-project.org/), and others. This largely removes the concern over web application recycling.

**Comment by DavidBoike** [comment]
From Andreas: "web applications not receiving" doesn't read well for me. Change to "Idle web applications could be shutdown or recycled at any time" ?

**Comment by SimonCropp** [comment]
if anyone wants to get around to this please submit a PR
