### ISSUE TITLE
Feedback: 'dotnet new Templates'

### ISSUE THREAD

**Issue by philippdolder** [Particular/docs.particular.net#6421]
Feedback for 'dotnet new Templates' https://docs.particular.net/nservicebus/dotnet-templates/

would be nice to have the `net8.0` option available. It seems it's available in the template [repository](https://github.com/Particular/ParticularTemplates/blob/master/src/ParticularTemplates/NServiceBusEndpoint/.template.config/template.json#L26). But the template I installed today using `dotnet new install ParticularTemplates` tells me
```
Error: Invalid option(s):
-f net8.0
   'net8.0' is not a valid value for -f. The possible values are:
      net472   - Target net472
      net48    - Target net48
      net6.0   - Target net6.0
      net7.0   - Target net7.0```

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/dotnet-templates/index.md

**Comment by DavidBoike** [comment]
Hi Phillipp,

The link you used for the master branch has been advanced for the release of a new major version, which will be released as part of NServiceBus 9.

I don't actually know if we're planning to release an update to the NServiceBus 8 templates (Templates V5) to also have a .NET 8 option. I will find out.

But in the short term, the shortest path to success is to execute the template with net7.0 and then edit the csproj file to change the 7 to an 8. That's going to be the only visible change.

**Comment by DavidBoike** [comment]
To follow-up, it sounds like we will be updating that as part of the sweep of all repos to update our internal tests to include the net8.0 target framework.

**Comment by DavidBoike** [comment]
By the way, this is now updated in version 5.0.1: https://discuss.particular.net/t/particulartemplates-5-0-1-patch-release-available/3886
