### ISSUE TITLE
Feedback: 'New persistence format'

### ISSUE THREAD

**Issue by janv8000** [Particular/docs.particular.net#6438]
Feedback for 'New persistence format' https://docs.particular.net/servicecontrol/upgrades/new-persistence

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/upgrades/new-persistence.md

> If the value is RavenDB **5** then the instance is using the new persistence format and does not require upgrading.
If the value is RavenDB **3.5** then the instance is using the old persistence format and should follow the instructions above to migrate to the new persistence format.

Please note that the docs mention a version in both cases.

The ServiceControl management tool and Powershell outputs differ making this page harder to understand.

## Tool
Current:
![image](https://github.com/Particular/docs.particular.net/assets/1412705/c7b4d8eb-31bd-4ccd-a122-61cd0672f051)
Legacy:
![image](https://github.com/Particular/docs.particular.net/assets/1412705/580e62b1-46e0-4797-9c52-076cdf27e546)

## Powershell
Current
`PersistencePackageName       : RavenDB`

Legacy
`PersistencePackageName       : RavenDB 3.5 (Legacy)`

My personal preference is to be explicit about versions etc..., so I would prefer the toolings to be aligned with the docs ...

**Comment by ramonsmits** [comment]
@janv8000 thanks for mentioning. We did as for example, currently the we support RavenDB5 but RavenDB 6 is already out. At the moment it seems migrating to RavenDB6 can be done seamles and we thought that it would provide us a bit more freedom by not mentioning the version for "latest".

It seems the docs you are referencing can be slightly improved so I created:

- https://github.com/Particular/docs.particular.net/pull/6439
