### ISSUE TITLE
Feedback: 'Upgrade NServiceBus pipeline extensions from Version 7 to 8'

### ISSUE THREAD

**Issue by simonfox** [Particular/docs.particular.net#6523]
Feedback for 'Upgrade NServiceBus pipeline extensions from Version 7 to 8' https://docs.particular.net/nservicebus/upgrades/7to8/pipeline

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/7to8/pipeline.md

We are in the process of upgrading from 7 to 8.1 and are have noticed behaviour that contradicts this documentation.  Specifically the statement in regards to message mutator registration - _In version 8 only the dedicated API is supported. Mutators registered in the container are ignored._ We noticed that mutators registered via container are still being invoked, we will move to the dedicated API as prescribed however just wondering if what we are seeing is expected?

**Comment by mikeminutillo** [comment]
Thanks for pointing this out @simonfox. We will investigate and get back to you. For now, your approach of switching to the dedicated API is the safest thing to do.

**Comment by simonfox** [comment]
@mikeminutillo sounds good. For context, we are using Lamar and the generic host.
