### ISSUE TITLE
Feedback: 'ServiceControl persistence' - RavenDb version

### ISSUE THREAD

**Issue by bbrandt** [Particular/docs.particular.net#6537]
Feedback for 'ServiceControl persistence' https://docs.particular.net/servicecontrol/persistence

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/persistence.md

Update to say RavenDB v5?

**Comment by boblangley** [comment]
Thanks for the catch. The page has been updated.
