### ISSUE TITLE
Feedback: 'Monitoring NServiceBus endpoints with Prometheus and Grafana' - Sample Grafana Does Not Match Code

### ISSUE THREAD

**Issue by bbrandt** [Particular/docs.particular.net#6577]
[The sample Grafana dashboard](https://docs.particular.net/samples/open-telemetry/prometheus-grafana/grafana-endpoints-dashboard.json) uses metric names that do not match the code examples.

Example:
In the code examples, `nservicebus.messaging.retries` was changed to `nservicebus.recoverability.retries`.  
--
Feedback for 'Monitoring NServiceBus endpoints with Prometheus and Grafana' https://docs.particular.net/samples/open-telemetry/prometheus-grafana/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/open-telemetry/prometheus-grafana/sample.md

**Comment by kentdr** [comment]
Hi @bbrandt 👋.   Thank you for the feedback!  I have fixed the sample with PR #6578.
