### ISSUE TITLE
Create Version 3 to Version 4 upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#658]
For reference see teh V4 to V5 http://docs.particular.net/nservicebus/upgrades/4to5

Plan of attack is 

 * [ ] copy the V3 snippets and samples and go through the motions of upgrading those to version 4 documenting each change required
 * [ ] Smoke test for any changes in the persistence. So store a saga/timeout/subscription etc in V3 and ensure they work after an upgrade to V4

**Comment by sfarmar** [comment]
@SimonCropp I'de be happy to help if is can

**Comment by SimonCropp** [comment]
@sfarmar happy for you to take this on. do you need anything from me (or anyone else) to make this happen?

**Comment by SimonCropp** [comment]
http://docs.particular.net/nservicebus/upgrades/3to4
