### ISSUE TITLE
Add native send for MSMQ

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#661]
to go here http://docs.particular.net/nservicebus/msmq/operations-scripting

- [x] PowerShell 
- [x] C#

should be located here https://github.com/Particular/docs.particular.net/tree/master/Snippets/Operations/Msmq

**Comment by gbiellem** [comment]
I'll take it @SimonCropp  ... Powershell FTW!

**Comment by gbiellem** [comment]
PR was merged so closing
