### ISSUE TITLE
Feedback: 'Message Correlation'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#6620]
Feedback for 'Message Correlation' https://docs.particular.net/nservicebus/sagas/message-correlation

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sagas/message-correlation.md

It is worth mentioning that correlation property is case-sensitive. In some systems where a GUID is used, serialized GUID value could be either lower or upper case, causing saga not to be found.

**Comment by lailabougria** [comment]
Thanks for the feedback @SeanFeldman: raised a PR with the suggestion here: https://github.com/Particular/docs.particular.net/pull/6624
