### ISSUE TITLE
Feedback: 'Endpoint configuration choices' - Not Updated for version 9

### ISSUE THREAD

**Issue by manuel-esteves** [Particular/docs.particular.net#6635]
Feedback for 'Endpoint configuration choices' https://docs.particular.net/samples/endpoint-configuration/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/endpoint-configuration/sample.md

**Comment by andreasohlund** [comment]
Hi @manuel-esteves , the sample is obsolete and therefore haven't been updated to either v8 or v9. As mentioned on that docs page we suggest that you use the .NET Generic Host instead. See https://docs.particular.net/samples/hosting/generic-host/ for more details.

Hope this helps!
