### ISSUE TITLE
Feedback: Update samples to use Microsoft.Extensions.Hosting instead of  host builders to run endpoints

### ISSUE THREAD

**Issue by soujay** [Particular/docs.particular.net#6651]
Samples are not using Microsoft.Extensions.Hosting and use host builders to run endpoints. Update the samples and any tutorial to use Microsoft.Extensions.Hosting and use the latest `IHostApplicationBuilder` variation introduced in .NET 8

```c#
var builder = Host.CreateApplicationBuilder(args);
```

**Comment by PhilBastian** [comment]
done in #6771
