### ISSUE TITLE
Recoverability logging category name is not up-to-date

### ISSUE THREAD

**Issue by MarcWils** [Particular/docs.particular.net#6693]
Feedback for 'Recoverability' https://docs.particular.net/nservicebus/recoverability/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/recoverability/index.md

The documentation states the **NServiceBus.RecoverabilityExecutor** category name is used for recoverability logging. This used to be true. But the RecoverabilityExecutor class seems to be removed in this commit: https://github.com/Particular/NServiceBus/commit/7044043421b31193d0c5421f102d41d8c89a58a5#diff-4a616aaf2b93c518049298e287220ae23f5c943e0f9bbbe111b8572848a88784

As we have specific logging configuration to always log immediate retries, we're now missing these in our logging. For immediate retries, the new category name seems to be **NServiceBus.ImmediateRetry** (https://github.com/Particular/NServiceBus/blob/fbf2b2c201d2890d541e3cc038f7d43be7c4ca89/src/NServiceBus.Core/Recoverability/ImmediateRetry.cs#L32).

**Comment by ramonsmits** [comment]
Thanks @MarcWils , will be fixed via:

- https://github.com/Particular/docs.particular.net/pull/6694
