### ISSUE TITLE
Feedback: 'Amazon SQS Transport'

### ISSUE THREAD

**Issue by mikesigs** [Particular/docs.particular.net#6750]
Feedback for 'Amazon SQS Transport' https://docs.particular.net/transports/sqs/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sqs/index.md

Missing `sns:Publish` permission.

**Comment by NChaganlal** [comment]
@mikesigs, we have now updated documentation to reflect the permissions needed including `SNS:Publish`
Thank you for bringing this to our attention.
