### ISSUE TITLE
Document how to use IgnoreDataMemberAttribute to tweak Json serialization

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#682]
When using the SagaAudit plugin, since we ILMerge the Json.net library, the user cannot decorate SagaData classes with attributes to ignore properties at serialization time, but the `IgnoreDataMemberAttribute` works because Json.net honors it.

@SimonCropp what do you think is the best place to put this?

**Comment by SimonCropp** [comment]
the saga aduti doco should just say "uses the built in json serializer" with a link. and that should go here http://docs.particular.net/servicecontrol/plugins#sagaaudit-plugin

the doco for IgnoreDataMemberAttribute... we should add a new page for json serializer doco and link from here http://docs.particular.net/nservicebus/serialization/#json
