### ISSUE TITLE
Feedback: 'Transaction support'

### ISSUE THREAD

**Issue by Abrissirba** [Particular/docs.particular.net#6876]
Feedback for 'Transaction support' https://docs.particular.net/transports/sql/transactions

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sql/transactions.md

It is a bit confusing wheter Distributed Transactions are supported or not. First it says that it is not supported and later that distributed transactions requires Azure SQL Elastic Transaction. 

We are using Azure SQL and a container app running on Linux. We use TransactionScope for the outbox. We open our own connections in our handler which will cause a distributed transaction.

My experience is that this works, because the dtc is handled by Azure SQL Elastic Transaction.

**Comment by andreasohlund** [comment]
Thanks for the feedback, when you say

>It is a bit confusing wheter Distributed Transactions are supported or not. First it says that it is not supported

do you refer to the warning that states

>Microsoft SQL Server does not support DTC transactions in all deployment models (such as database mirroring or Always On configurations) and support differs between versions of SQL Server

?

**Comment by Abrissirba** [comment]
Not sure at which place I read this anymore. Reading the docs on that page now again it is pretty clear that Azure SQL Elastic transactions is supported. You can close this

**Comment by andreasohlund** [comment]
Thanks @Abrissirba
