### ISSUE TITLE
Feedback: 'NServiceBus sagas: Saga basics'

### ISSUE THREAD

**Issue by BenHughesTPR** [Particular/docs.particular.net#6893]
Feedback for 'NServiceBus sagas: Saga basics' https://docs.particular.net/tutorials/nservicebus-sagas/1-saga-basics/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-sagas/1-saga-basics/tutorial.md

Small inconsistency in the "Orders processing and saga completion" section - it states:

>First, in the Messages project, create a ShipOrder command:

However when following on from the first tutorial at "https://docs.particular.net/tutorials/nservicebus-step-by-step/" at this point we have both a `Billing.Messages` and a `Sales.Messages` projects, but not a `Messages` project.

**Comment by andreasohlund** [comment]
Good catch I have addressed this in https://github.com/Particular/docs.particular.net/pull/6898 as well!
