### ISSUE TITLE
Feedback: 'NServiceBus sagas: Timeouts'

### ISSUE THREAD

**Issue by BenHughesTPR** [Particular/docs.particular.net#6895]
Feedback for 'NServiceBus sagas: Timeouts' https://docs.particular.net/tutorials/nservicebus-sagas/2-timeouts/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-sagas/2-timeouts/tutorial.md

Inconsistency: previous step of tutorial (https://docs.particular.net/tutorials/nservicebus-sagas/1-saga-basics/#exercise-saga-state) suggests naming of Saga / SagaData as:

- `ShippingPolicy`
- `ShippingPolicyData`

But this step suggests:

- `BuyersRemorsePolicy`
- `BuyersRemorseState`

Is there a preferred convention between these?

**Comment by andreasohlund** [comment]
I've updated https://github.com/Particular/docs.particular.net/pull/6898/ to include aligning all naming to use "Data" as the suffix since the property on the actual saga is `.Data`
