### ISSUE TITLE
Pre-release notification false positives

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#697]
![image](https://cloud.githubusercontent.com/assets/174258/8596154/c4e6168e-264d-11e5-97f2-a8bd8e832449.png)

For example

http://docs.particular.net/nservicebus/upgrades/4to5

**Comment by SimonCropp** [comment]
@danielmarbach the warning is correct http://docs.particular.net/nservicebus/upgrades/4to5#make-configurehowtofindsaga-abstract
