### ISSUE TITLE
Document that MSMQ Timeout persistence is not supported

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#702]
* [ ] http://docs.particular.net/nservicebus/persistence/
* [ ] http://docs.particular.net/nservicebus/upgrades/4to5
* [ ] http://docs.particular.net/nservicebus/msmq/ (not sure if here is needed)

**Comment by andreasohlund** [comment]
Raised by the user here:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/particularsoftware/yoHSZQjwUQE

Should we consider a better exception as well?

**Comment by weralabaj** [comment]
In terms of docs this issue was fixed by Tim https://github.com/Particular/docs.particular.net/pull/1605. The topic of better error messages is outstanding issue in NSB repo.
