### ISSUE TITLE
When not to use NServiceBus

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#710]
There was a question in the google groups asking if NServiceBus was a good candidate to replace a highly complex ETL solution. NServiceBus is not intended to be used for ETL. We need doco that mentions why.

This document can also mention other areas where it is maybe better to use other implementations. Maybe like very low latency messaging or maybe this is already a more 'gray' area.

- ETL
- Queries
- Low latency messaging
- Replication

**Comment by DavidBoike** [comment]
ETL is a big one. Queries would be another.

There have to be more.

I think an article like this in doco would be a huge credibility booster and hopefully prevent some support cases too.

**Comment by danielmarbach** [comment]
Let's start simple. Document the answer to the google group question and ship it

**Comment by DavidBoike** [comment]
@danielmarbach you're no fun, but you're right.

**Comment by ramonsmits** [comment]
@danielmarbach That was already done before this, but due that question we discussed on slack that such an article would be very helpful.

**Comment by SimonCropp** [comment]
i dont think this is a good for documentation . the list of things that are not good for NSB is unbound and cannot be definitively captured. suggest this is better as a blog post to show some specific examples

**Comment by DavidBoike** [comment]
Mathematicaly, of course, you're correct. But aren't there "common misuse" scenarios that could be outlined and would be valuable as doco?

**Comment by SimonCropp** [comment]
i dont think so. many of those are "it depends"

eg 

 * Low latency is a relative term. 
 * I have successfully used NSB + databus for replication on several occasions

Seems like this documentation would read "NSB is not a DB, NSB is not a query engine, NSB is not etc etc"

**Comment by SimonCropp** [comment]
also there are many other docs issues that are much higher priority than this.

**Comment by DavidBoike** [comment]
I disagree on the first point, but agree on priority. In that case, can we agree to sit on this / backlog it, and not close outright?

**Comment by gbiellem** [comment]
I agree with @SimonCropp  on prio.   Although I do think the common misuse idea would make a good blog article

**Comment by SimonCropp** [comment]
sorry i am closing this. documenting "what something isnt" gets us into a very messy area of unbound+never ending content and way too many "it depends on your specific case". 

Take ETL

 * you need a non trivial amount of content to explain what ETL is 
 * many people will disagree on our definition
 * the are many simplistic uses of ETL that NSB would perform perfectly well at

Take Low latency messaging. even having the term "low" is too relative to have documentation on. We should focus on the real performance stats of NSB and let the consumer decide.

Take Replication. I have on several projects successfully uses NSB for Replication.
