### ISSUE TITLE
Fix showcase project event subscriptions

### ISSUE THREAD

**Issue by wolfbyte** [Particular/docs.particular.net#725]
Out of the box, the `ClientBecamePreferred` message subscriptions are not working. This is because they are configured to go to the wrong assembly. 

To fix this I had to add the following line to the `app.config` of the `Store.CustomerRelations` project:

    <add Assembly="Store.Messages" Type="Store.Messages.Events.ClientBecamePreferred" Endpoint="Store.CustomerRelations" />

**Comment by SimonCropp** [comment]
Pr :)

**Comment by wolfbyte** [comment]
Is this the best solution to the problem?
