### ISSUE TITLE
update showcase

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#731]
http://docs.particular.net/samples/show-case/on-premise/

Since this is our only demo of how to use NSB with SignalR we should ensure it is representative of the current version of signalr. currently it uses V 1.0.0	 from February 2013

Should also update bootstrap, jquery etc

**Comment by SeanFeldman** [comment]
@SimonCropp I've used this just recently, don't mind to do it

**Comment by SimonCropp** [comment]
@SeanFeldman ok. ping @petersgiles or @weralabaj if u need help on the js/css changes
