### ISSUE TITLE
Provide samples for adding headers to messages coming from 3rd party system

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#733]
As a follow up to https://github.com/Particular/docs.particular.net/pull/729 provide code samples presenting how headers might be added to messages for various transports.
Add link(s) to this content from "Third Party Integration" article (https://github.com/Particular/docs.particular.net/pull/729) or extend the original article (depending on where we decide that should go).

**Comment by weralabaj** [comment]
@SimonCropp I see you're already doing this, e.g. here http://docs.particular.net/nservicebus/msmq/operations-scripting. Should that issue be closed?

**Comment by SimonCropp** [comment]
@weralabaj sounds good
