### ISSUE TITLE
Callbacks article/sample does not address Web

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#753]
A customer (Desk 12657) was trying to implement callbacks [following our doco to the letter](http://docs.particular.net/nservicebus/messaging/handling-responses-on-the-client-side#using-callbacks-object) and was led astray because it doesn't really talk about doing so within a web application, in particular, the synchronization object (Page / Controller).

The doco also does not talk about the Task overloads which are much simpler to use in a web context.

**Comment by andreasohlund** [comment]
+1 , doco on how to use the callback in conjunction with things like asp.net async,https://msdn.microsoft.com/en-us/library/ee728598(v=vs.100).aspx, is needed since that's one of the main use cases since that really helps thread usage on the web server
