### ISSUE TITLE
Add samples intro

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#758]
So add some content here http://docs.particular.net/samples/ that talks about the following and the whys

 - use self hosting
 - use Json serializer
 - use msmq (and point to how to setup pre-res, this is not currently written)
 - use in mem persistence
 - the sql connection string defaults
 - why they all define endpoint name instead of relying on convention

etc

also hack the engine to add a link to this on every sample page

**Comment by weralabaj** [comment]
[GG thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/Xr1e6ANU5OI/JbNsFZfhTn4J) related to missing pre-res and MSMQ configuration

**Comment by weralabaj** [comment]
@SimonCropp Could you have a look at https://github.com/Particular/docs.particular.net/pull/762? Would that form be ok with you?

**Comment by weralabaj** [comment]
I could add content on the other issues too, but i'd need some explanation for all but in memory persistence on what you had in mind.

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/
