### ISSUE TITLE
Message attribute in MessageEndpointMappings in App.config not documented

### ISSUE THREAD

**Issue by petersgiles** [Particular/docs.particular.net#773]
This page http://docs.particular.net/nservicebus/messaging/specify-message-destination doesn't have a description for this attribute 'Messages' in 'UnicastBusConfig'. found in v5 of unobtrusive sample
```
  <UnicastBusConfig>
    <MessageEndpointMappings>
      <add Messages="Messages" Endpoint="server"/>
    </MessageEndpointMappings>
  </UnicastBusConfig>
```

**Comment by petersgiles** [comment]
@SimonCropp @johnsimons tells me this is super old V2? probably just need to remove from any samples instead of adding to dodo

**Comment by SimonCropp** [comment]
@johnsimons so what version range does that setting exist in?

**Comment by johnsimons** [comment]
From 3.3

On Fri, 28 Aug 2015 at 12:01 Simon Cropp <notifications@github.com> wrote:

> @johnsimons <https://github.com/johnsimons> so what version range does
> that setting exist in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/docs.particular.net/issues/773#issuecomment-135603546>
> .
>
-- 

*John Simons*
*Engineer, Particular Software*

Email*:*  john.simons@particular.net
Web:    www.particular.net

**Comment by SimonCropp** [comment]
I am confused 

here it is in 4 https://github.com/Particular/NServiceBus/blob/4.7.6/src/NServiceBus.Core/Config/MessageEndpointMapping.cs#L18

here it is in 5
https://github.com/Particular/NServiceBus/blob/support-5.0/src/NServiceBus.Core/Config/MessageEndpointMapping.cs#L18

here it is in 6
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Config/MessageEndpointMapping.cs#L18

r u saying that it is obsolete?

**Comment by gbiellem** [comment]
It used to configure Multi DB support in the SQL transport so it's not obsolete 
http://docs.particular.net/nservicebus/sqlserver/multiple-databases#config

**Comment by johnsimons** [comment]
Good catch @gbiellem, I've updated that snippet

**Comment by johnsimons** [comment]
> r u saying that it is obsolete?

@SimonCropp  Yes, it should be, we left the previous one for backwards compatibility and I guess we never bother removing it completely, this was a long time ago before we knew better

**Comment by johnsimons** [comment]
Updated doco, see http://docs.particular.net/nservicebus/messaging/specify-message-destination#configuring-endpoint-mapping-using-app-config

**Comment by SimonCropp** [comment]
removed usage from samples and updated http://docs.particular.net/nservicebus/messaging/specify-message-destination#resolving-the-messages-to-map-resolving-with-messages
