### ISSUE TITLE
Document QueueBindings

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#775]
* add a new page that explains them 
 * add them to the upgrade guide as a replacement of for IWantQueueCreated http://docs.particular.net/nservicebus/upgrades/5to6

**Comment by SimonCropp** [comment]
@SzymonPobiega can u have a look at this?

**Comment by SzymonPobiega** [comment]
Yes, sure. I was away last four days. I'l take care of it.

**Comment by SzymonPobiega** [comment]
Added a pull here https://github.com/Particular/docs.particular.net/pull/807

**Comment by SzymonPobiega** [comment]
@danielmarbach did I understand you correctly that you want to take it over?

**Comment by danielmarbach** [comment]
Extended @SzymonPobiega PR to include queue declaration and creation into doco page. See https://github.com/Particular/docs.particular.net/pull/807

**Comment by danielmarbach** [comment]
Closing this in favour of the PR
