### ISSUE TITLE
Persistence guidance content

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#787]
Related to #786 

I recently had a customer call where we went over all of this for NHibernate vs. Raven. I'm only half joking when I say I may play back the recording of that call and transcribe it.

Similar to #786 this belongs in the "guidance" category, and will be somewhat opinion based, but it will stick to how the Raven/NH persistences differ because the underlying storage engines differ, and the ramifications of that in each case.

**Comment by weralabaj** [comment]
Moved to plat dev https://github.com/Particular/PlatformDevelopment/issues/1252
