### ISSUE TITLE
Add bus.defer changes to upgrade guide v6

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#788]
So this 

        bus.Defer(TimeSpan.FromSeconds(10), new DeferredMessage());

becomes this

        DeferredMessage message = new DeferredMessage();
        SendOptions sendOptions = new SendOptions();
        sendOptions.DelayDeliveryWith(TimeSpan.FromSeconds(10));
        bus.Send(message, sendOptions);

Also need general doco about defer

**Comment by mikeminutillo** [comment]
Covered by https://github.com/Particular/docs.particular.net/pull/1127 and https://github.com/Particular/docs.particular.net/issues/1116
