### ISSUE TITLE
Performing inti/config with Meth Sample

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#795]
To avoid the problems with our configuration interfaces like INeedInitialization 

for context https://github.com/Particular/docs.particular.net/pull/794#issuecomment-135555761

**Comment by mauroservienti** [comment]
`Meth Sample`?

**Comment by SimonCropp** [comment]
https://msdn.microsoft.com/en-us/library/dd460648(v=vs.110).aspx

**Comment by mauroservienti** [comment]
Did you mean `MEF` and not `Meth` in the title?

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/plugin-based-config/
