### ISSUE TITLE
add a v6 scaleout samples

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#799]
http://docs.particular.net/samples/scaleout/

**Comment by andreasohlund** [comment]
This would have to use the new routing that @SzymonPobiega is task leading. Do we add this to this section or a new one? (since the distributor is probably obsoleted as of v6)

**Comment by SimonCropp** [comment]
@andreasohlund is there any cost of moonlighting the current distributor for a while? ie keep it around for v6 timeframe

**Comment by andreasohlund** [comment]
Yes, there is a lot of nasty code in the core that we would have to figure
out how to fix in order to make the distributor work in v6 :(

**Comment by SimonCropp** [comment]
@andreasohlund let me phrase this another way. the distributor is using all supported APIs in version 5. all these APIS may have been used by people to build custom solutions, perhaps some similar to our distributor and perhaps some different. but either way the equivalent thing should be able to be build in v6. otherwise we risk the pitch forks of downstream consumers.

**Comment by andreasohlund** [comment]
> the distributor is using all supported APIs in version 5

It's actually using alot of "stringly typed" core hacks like https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/ContextualBus.cs#L31 so I'm not sure that's 100% true

**Comment by SimonCropp** [comment]
@andreasohlund so no one has forked distributor?

**Comment by andreasohlund** [comment]
>so no one has forked distributor?

Not sure, would that blocking us from not providing a v6 compat distributor
and guide them to use the new routing instead?

**Comment by SimonCropp** [comment]
perhaps. just that the optimal scenario is to give people  a period of transition.

**Comment by johnsimons** [comment]
@SzymonPobiega what do we do here ?

**Comment by SzymonPobiega** [comment]
We show a V6 cluster and how to access it from V5 and V6 endpoints. We have these scenarios covered here https://github.com/Particular/NServiceBus.ScenarioTests/blob/master/src/ScaleOutPubSubCompat.Runner/Tests.cs. It is a matter of extracting a proper sample from there.

**Comment by johnsimons** [comment]
@SzymonPobiega it seems you know what to do, assigning it to u

**Comment by SzymonPobiega** [comment]
I thought it was already assigned to me;-)

**Comment by SimonCropp** [comment]
this seems to be done
