### ISSUE TITLE
fix express doco

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#801]
So we have 
- http://docs.particular.net/samples/non-durable-messaging/
- http://docs.particular.net/nservicebus/messaging/non-durable-messaging

But we dont tell people how to configure MSMQ in express mode
Nor do we say how express manifests in other transports
Also need to add a v6 sample to non-durable-messaging

**Comment by weralabaj** [comment]
@SimonCropp seems like at least two out of three issues you listed here have been addressed, is that right? What did you have in mind regarding " how to configure MSMQ in express mode" - would be adding links to MSDN ok?

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers please submit a PR if you feel this is important
