### ISSUE TITLE
Add header-manipulation v6 sample

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#802]
http://docs.particular.net/samples/header-manipulation/

**Comment by SimonCropp** [comment]
@SzymonPobiega do u want to try this one?

**Comment by SzymonPobiega** [comment]
Yeah, sure. I'll try.

**Comment by SzymonPobiega** [comment]
Opened a PR for this here https://github.com/Particular/docs.particular.net/pull/818
