### ISSUE TITLE
update  SQL Server / NHibernate samples to newest

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#803]
* [x] http://docs.particular.net/samples/sqltransport-nhpersistence/
 * [x] http://docs.particular.net/samples/sqltransport-nhpersistence-outbox-ef/ - https://github.com/Particular/docs.particular.net/pull/1169
 * [x] http://docs.particular.net/samples/sqltransport-nhpersistence-outbox/ - https://github.com/Particular/docs.particular.net/pull/1162

**Comment by SimonCropp** [comment]
WIP PR https://github.com/Particular/docs.particular.net/pull/1044

**Comment by weralabaj** [comment]
All merged so closing this issue.
