### ISSUE TITLE
V4 to V5 upgrade guide don't mention that type name for transports changed

### ISSUE THREAD

**Issue by gbiellem** [Particular/docs.particular.net#805]
Maybe I missed it but I can;t find anything in the V4 to V5 upgrade guide that mentions that all of the transport types had the word "Transport" added to the TypeNames  in V5 

e.g.  NServiceBus.Msmq became NServiceBus.MsmqTransport

**Comment by SimonCropp** [comment]
http://docs.particular.net/nservicebus/upgrades/4to5#transport-definitions-for-usetransport-have-been-renamed
