### ISSUE TITLE
Add azure transports native send samples

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#810]
so an equivalent to these 
in Rabbit http://docs.particular.net/nservicebus/rabbitmq/operations-scripting#native-send
In MSMQ http://docs.particular.net/nservicebus/msmq/operations-scripting#native-send
In Sql http://docs.particular.net/nservicebus/sqlserver/operations-scripting#native-send

**Comment by SeanFeldman** [comment]
** ASB v6**: candidate? https://github.com/yvesgoeleven/NServiceBus.AsbNativeIntegration/tree/master/src

** ASQ v6**: requires transport fix: https://github.com/Particular/NServiceBus.AzureStorageQueues/tree/deserialization-spike

**Comment by SimonCropp** [comment]
some code that should help

 * https://github.com/Particular/docs.particular.net/blob/master/samples/azure/storage-persistence/Version_5/StorageReader/AzureHelper.cs
 * https://github.com/Particular/docs.particular.net/blob/master/samples/azure/storage-queues/Version_5/StorageReader/AzureHelper.cs

**Comment by SeanFeldman** [comment]
Replace by #886 & #887
