### ISSUE TITLE
MSMQ Distributor stops processing messages

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#815]
I'm stuck in analysis paralysis trying to figure out where to document this issue. I had a case where a customer's MSMQ worker process just dried up and stopped processing messages after some period of inactivity. In reality, MSMQ on the worker was binding to extra network IP/port combinations which you could discover via netstat. So it would work for awhile, then during a period of inactivity, the connection on the "good" interface would close up shop. On the next send of a ready message back to the distributor, a connection would be opened on the _wrong_ interface, and the distributor's control queue on the remote machine couldn't validate it, so it wouldn't go through properly. End result, ready message stuck at worker, worker dries up.

The fix is this Microsoft article, [MSMQ service might not send or receive messages after you restart a computer that is running Windows 7, Windows Server 2008 R2, Windows Vista or Windows Server 2008](https://support.microsoft.com/en-us/kb/2554746), which includes a hotfix that prevents MSMQ from binding to the bad interface.

* I considered adding to [MSMQ Information](http://docs.particular.net/nservicebus/msmq/) but that's just general information, not troubleshooting.
* [Transactions and Message Processing](http://docs.particular.net/nservicebus/operations/transactions-message-processing) contains some good MSMQ troubleshooting info about the DTC, but this issue would really be out of scope.
* [MSMQ transport](http://docs.particular.net/nservicebus/msmq/transportconfig) has more info about the mechanics of MSMQ but seems out of place here too.
* Right now I'm leaning toward a new article based on the problem and tailored to be found via search when you have the problem, similar to [MessageQueueException: Insufficient resources to perform operation](http://docs.particular.net/nservicebus/msmq/messagequeueexception-insufficient-resources-to-perform-operation) but then I'm not sure what to call it. There is no exception to search when this happens to you. I could call it something like "MSMQ Worker stops processing messages" although it's really a larger MSMQ problem. It could happen when sending any message. But I don't think my customer would have clicked on an article titled "MSMQ stops sending messages" - from his perspective, that's not what was happening.

Would the best solution be to have a general MSMQ troubleshooting article instead that just includes this as one section?

Please help @Particular/documentation

**Comment by SimonCropp** [comment]
rename this page http://docs.particular.net/nservicebus/msmq/messagequeueexception-insufficient-resources-to-perform-operation to be a "msmq common problems" and append it there. we will then add it to the menu

**Comment by SimonCropp** [comment]
actually u r right "Troubleshooting" is better
