### ISSUE TITLE
Better document how users can enforce processing limits

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#816]
Right now we have http://docs.particular.net/nservicebus/operations/throughput

Should be split into 2 docs one for throughput and one for concurrency with a potential index page talking about use cases for them and the pages would drill into the actual api to change them.

Also note that v6 (if we go ahead with https://github.com/Particular/NServiceBus/issues/2833) will default to not limit the concurrency

**Comment by danielmarbach** [comment]
@andreasohlund what is the state of that?

**Comment by andreasohlund** [comment]
Concurrency is covered by http://docs.particular.net/nservicebus/operations/tuning (please review) and we've actually removed the throughput limit. The idea was to handle that by a sample instead (I'll raise a separate issue for this)
