### ISSUE TITLE
SerializationContextExtensions.SkipSerialization

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#820]
eg used by callbacks to avoid serializing a enum/int

**Comment by johnsimons** [comment]
@SimonCropp can u provide more insight what u have in mind for this ?

**Comment by SimonCropp** [comment]
it is a public api... hence needs doco

**Comment by johnsimons** [comment]
So is there any existing doco on serialization ? where would should this be documented ? What is the context ?
I can create a single stand alone page and add it to it but IMO it is going to look silly.

**Comment by andreasohlund** [comment]
>So is there any existing doco on serialization ? where would should this be documented ? What is the context ?

@johnsimons pretty sure you could find those answers by spelunking the doco?

How about a "should you need to send a message but bypass the serialization step you can call XYZ"
added  to http://docs.particular.net/nservicebus/serialization/ ?

or perhaps a similar section somewhere in the pipeline doco http://docs.particular.net/nservicebus/pipeline/ ?

**Comment by johnsimons** [comment]
@andreasohlund none of the doco pages you referenced above have any granular doco regarding this topic, they are IMO very highlevel, are we sure we want to add this to them ?

Regarding "should you need to send a message but bypass the serialization step you can call XYZ", why would a user want to do this ? In what context ?

**Comment by andreasohlund** [comment]
>topic, they are IMO very highlevel, are we sure we want to add this to them ?

Not to worried but I guess we can add a sub page for "advanced topic" if needed?

>why would a user want to do this ? In what context ?

One would be to send a "control message" just like the callbacks package is doing it. (yes it's an advanced scenario, but not unlikely if your building some infrastructure thing)
