### ISSUE TITLE
add DoNotAutoSubscribeSagas to 3-4 upgrade guide

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#831]

**Comment by andreasohlund** [comment]
Pretty sure both was added in v4

**Comment by andreasohlund** [comment]
DoNotAutosubscribe sagas where added in v3
AutoSubscribePlainMessages was added in v4

**Comment by SimonCropp** [comment]
@andreasohlund thanks

**Comment by andreasohlund** [comment]
So essentially:  Sagas where not autosubscribed in v2.6 => add to v2=>v3 upgrade guide?

Plain messages where autosubscribe in v3 but not in v4 => add to v3=> v4 upgrade guide

**Comment by SimonCropp** [comment]
@andreasohlund i dont think we intend to do a 2 to 3 guide?

**Comment by andreasohlund** [comment]
I know @sfarmar has some info as well in v2.6 => v3.3 upgrades, would it hurt to put info like that in a upgrade guide?
