### ISSUE TITLE
ServiceControl Plugins for Send Only Endpoints

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/docs.particular.net#842]
The Custom Checks and Periodic Checks will not work out of the box for Send Only Endpoints. This is because they both rely on the `IWantToRunWhenTheBusStartsAndStops` interface which is not activated for Send Only Endpoints.

For Periodic Checks, a timer is created during Start and disposed of during Stop. This timer is the component that activates and calls the Periodic Check. Without it nothing will happen. You could resolve these yourself and call them but they don't report to ServiceControl on their own so you'd have to do that manually as well. 

For Custom Checks, these are resolved from the container during Start. Custom Checks are expected to report status in their constructor so the act of resolving them triggers them. Custom Checks DO report directly to ServiceControl on their own so if you manually resolve them they will report to SC. In fact, they will do so every time you resolve them so you can periodically resolve them to achieve a similar effect as Periodic Checks.

This info should be verified and added to the docs. It would make sense to investigate the behavior of the other ServiceControl plugins (SagaAudit and DebugSession) at the same time.

**Comment by weralabaj** [comment]
@Particular/servicecontrol-maintainers @mikeminutillo is that issue still relevant?

**Comment by mikeminutillo** [comment]
It is for V5. `IWantToRunWhenBusStartsAndStops` do not run for SendOnly endpoints. I'm not sure about V6.

**Comment by weralabaj** [comment]
OK then could that be done under @Particular/servicecontrol-maintainers budget?

**Comment by SimonCropp** [comment]
@Particular/servicecontrol-maintainers please submit a PR if you still feel this is important
