### ISSUE TITLE
Generate reference source

### ISSUE THREAD

**Issue by hmemcpy** [Particular/docs.particular.net#852]
The code/site that powers http://referencesource.microsoft.com/ and http://source.roslyn.io was just made open source: https://github.com/KirillOsenkov/SourceBrowser

I used it to generate NSB: http://nsbreferencesource.azurewebsites.net/
I must say, that's a nice way of browsing the code base.

Should we use this to build our own reference source and link to it?

**Comment by colin-higgins** [comment]
Aw yiss

**Comment by SimonCropp** [comment]
closing this. it cant really be addressed by any change in this repo. also it is a non trivial amount of work. if u want to proceed suggest u raise it in the platform dev repo and see if u can form a taskforce
