### ISSUE TITLE
Remove ServiceMatrix from Getting Started with the Particular Service Platform

### ISSUE THREAD

**Issue by petersgiles** [Particular/docs.particular.net#856]
Task force: @petersgiles @indualagarsamy 

### Description

Add guidance on building distributed systems on the documentation site. 

Relates to https://github.com/Particular/PlatformDevelopment/issues/454

Fixes this document http://docs.particular.net/platform/getting-started-with-particular-service-platform

This will tie in  the existing documentation including information from the following URLs

- http://docs.particular.net/platform/ 
- http://docs.particular.net/nservicebus/concept-overview 
- http://docs.particular.net/samples/endpoint-configuration/ 
- http://docs.particular.net/samples/step-by-step/
- http://docs.particular.net/nservicebus/messaging/publish-subscribe

### Customer Communication

We have improved Particular's guidance for building distributed systems.

### Alignment with Vision

Making Developers Better

### Plan of Attack

- [ ] Create a page that takes users on a journey through the current documentation
- [ ] Create an approach for gradual improvement of related samples

**Comment by petersgiles** [comment]
The PR was closed 15 days ago and no one has indicated if we even need a getting started page in this format anymore. 

My thought is that the samples are instructive enough and the we should just delete the page(s) in question.

**Comment by indualagarsamy** [comment]
@petersgiles - You are right. We are going to leave the existing documentation for SM with a discontinued tag / warning for a little while pointing to the the announcement page. I believe we can close this issue. I am working on a separate branch for these changes. I'll raise a PR when ready. 
The announcement PR is here: https://github.com/Particular/Announcements/pull/58
I believe we can close this issue.

**Comment by petersgiles** [comment]
done :)
