### ISSUE TITLE
native/non-native subscriptions

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#860]
This http://docs.particular.net/nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed#automatic-subscriptions

> Note that this only applies to transports that don't support publish-subscribe natively.

Is not enough

Context: https://groups.google.com/forum/#!topic/particularsoftware/BxG8VvHj0uk

**Comment by andreasohlund** [comment]
@ramonsmits I remember us talking about this, did you complete that pull?
