### ISSUE TITLE
Pub/sub doesn't clarify polymorphic events behavior

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#861]
For new users it's [confusing how polymorphic events are handled](https://groups.google.com/forum/#!topic/particularsoftware/g7roalODpLU).
Either add this to [pub/sub doco](https://github.com/Particular/docs.particular.net/edit/master/nservicebus/messaging/publish-subscribe/index.md) or link it to additional article if worth creating one.

There's an old [blog post by Udi](http://udidahan.com/2011/01/13/polymorphism-and-messaging/) that could be incorporated into doco or sample.

## Example

**Polymorphic Messages**
`Shared.Events` (Namespace)
`EventA : IEvent`
`EventB : EventA`

**Handlers**
`HandlerA : IHandle<EventA>`
`HandlerB : IHandle<EventB>`

**Invocation**

`bus.Publish<EventB>(e => ...);`

**Expected behaviour**

Handler A and B to be invoked

**Actual behaviour**

Handler A and B are invoked twice each

## Analysis

What's happening is that endpoint publishing these events has 2 subscriptions: one for `EventA` and one for `eventB`. When message of type `EventB` is published, it will be sent to subscriber twice (once because default rule filter on `EventA` subscription will catch it with `[NServiceBus.EnclosedMessageTypes] LIKE '%Shared.Events.EventA%' OR...` and once because default rule filter on `EventB` subscription will catch it with `[NServiceBus.EnclosedMessageTypes] LIKE '%Shared.Events.EventB%' OR...`). This is because published message `NServiceBus.EnclosedMessageTypes` header is `Shared.Events.EventA, Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null;Shared.Events.EventB, Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`
Since each event message will be delivered to an endpoint, each will go through polymorphic routing and will be invoked with event handlers that can handle it, i.e. `HandlerA` and `handlerB`. This will result in duplicate invocation of handlers.

## Workaround

1. Disable auto-subscription for subscriber endpoint 
1. Subscribe to base event only manually

[GG issue](https://groups.google.com/forum/#!topic/particularsoftware/g7roalODpLU)

**Comment by SimonCropp** [comment]
i am leaning towards a new page since http://docs.particular.net/nservicebus/messaging/publish-subscribe/ has a fair bit on it already

happy for it to be a sample

**Comment by SeanFeldman** [comment]
going for a sample
