### ISSUE TITLE
License Location: App Specific License pages

### ISSUE THREAD

**Issue by colin-higgins** [Particular/docs.particular.net#863]
I am not sure of the data on this, but I would assume that most people who go to the licensing page in our documentation are seeking information on 4.5+ so it could be useful to make the most recent instructions very prominent and perhaps have a license "troubleshooting" section.

I know there are issues up already to improve our code that looks for licensing, but I think there would be value in warning users about trial licenses anyways. 

Also, application specific pages for licensing could be useful too.
ServiceInsight and ServicePulse would basically just say they rely on the ServiceControl license with any details and then point to the ServiceControl page.

**Comment by gbiellem** [comment]
The app specific [license page](http://docs.particular.net/servicecontrol/license) for ServiceControl exists  and has been updated 
@HEskandari  - You offered to do one for ServiceInsight so passing this to you

**Comment by HEskandari** [comment]
Any objections if I update this after resolving Particular/ServiceInsight#580?

**Comment by SimonCropp** [comment]
can the various license pages be cross linked via related pages in the headers

**Comment by SimonCropp** [comment]
@HEskandari 580 is done. anything u need from me to get this going?

**Comment by HEskandari** [comment]
No, leave this with me, will get it done by tomorrow. Got side tracked with
other stuff.

**Comment by HEskandari** [comment]
Licensing related contents are linked now. Have updated the text as a part of #1709 PR to reflect latest changes in the licensing validation/installation. This can be closed now.
