### ISSUE TITLE
Update Azure storage persistence sample with explanation about data stored in tables/blob

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#866]
Provide explanation how and why storage tables and blob are used.

Sample: http://docs.particular.net/samples/azure/storage-persistence/

**Comment by weralabaj** [comment]
@Particular/azure-maintainers can you take care of it?

**Comment by SeanFeldman** [comment]
The sample already contains explanation about date, so I'm closing this.
