### ISSUE TITLE
how to shift SqlTransport audit log to long term storage

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#874]

**Comment by petersgiles** [comment]
http://solutioncenter.apexsql.com/sql-server-bulk-copy-and-bulk-import-and-export-techniques/

**Comment by petersgiles** [comment]
To archive in the same database with SQL you need a target table

```
CREATE TABLE [dbo].[audit_destination](
	[Id] [uniqueidentifier] NOT NULL,
	[CorrelationId] [varchar](255) NULL,
	[ReplyToAddress] [varchar](255) NULL,
	[Recoverable] [bit] NOT NULL,
	[Expires] [datetime] NULL,
	[Headers] [varchar](max) NOT NULL,
	[Body] [varbinary](max) NULL,
	[RowVersion] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

```
and then run this

```
/*
performing an INSERT and then a DELETE might lead to integrity issues, so perhaps a way to get around it, and to perform everything neatly in a single statement, is to take advantage of the [deleted] temporary table.
*/
DELETE FROM [dbo].[audit]
OUTPUT [deleted].*
INTO [dbo].[audit_destination] 
```

**Comment by petersgiles** [comment]
For BCP

Simplified

1. BCP out rows to be deleted to an archive file
1. BCP out rows to be retained
1. Drop indexes and truncate table
1. BCP in rows to be retained
1. Create indexes

More Detail

1. Back up the sourcedb
1. Change sourcedb to bulk-logged
1. Open command prompt
1. `bcp  server.sourcedb.table  out  Filename.flt  -T  -c`
1. `bcp "SELECT * FROM sourcedb.table WHERE keep_condition = 1"  queryout  Filename2.flt  -T -c`
1. `bcp Server.destinationdb.table in Filename.flt -T -c -b1000`
1. check the data 
1. From SSMS Truncate the sourcedb table
1. `bcp server.sourcedb.table in Filename2.flt -T -c -b1000`
1. Change sourcedb back to full

**Comment by petersgiles** [comment]
My feeling is that the least fuss way of dealing with the problem is a mix of both techniques

```
/*  With an audit_archive table */

DELETE FROM [dbo].[audit] 
OUTPUT [deleted].*
INTO [dbo].[audit_archive] 
```

Then in a command prompt

`bcp samples.dbo.audit_archive out archive.csv -c -q -T -S .\SQLExpress`

and Back in SQL in the samples database

`TRUNCATE TABLE  [dbo].[audit_archive] ;`

**Comment by petersgiles** [comment]
fixed: https://github.com/Particular/docs.particular.net/pull/943
