### ISSUE TITLE
Managing NServiceBus Using PowerShell

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#88]
http://particular.net/articles/managing-nservicebus-using-powershell

http://particular.net/Admin/Contents/Edit/262
http://particular.net/Contents/Item/Preview/262

KB
- [ ] Review content, seems to be in acurate 
- [ ] Update code snippets

**Comment by mauroservienti** [comment]
@sfarmar is this still valid?
there is a strong relationship between this and #135, #343, #491.

**Comment by SimonCropp** [comment]
done http://docs.particular.net/nservicebus/operations/management-using-powershell
