### ISSUE TITLE
Native integration with ASB document (+sample)

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#886]
Replaces  #810 

Documentation to provide more details about the scenario in general that [native integration sample](http://docs.particular.net/samples/azure/native-integration-asb/) provides

**Comment by yvesgoeleven** [comment]
Reopening to add a page & update to v7

**Comment by SimonCropp** [comment]
@SeanFeldman @yvesgoeleven why is this tied to v6?

**Comment by SeanFeldman** [comment]
No idea @SimonCropp. The v7 sample is there, but is not up to date due to our changes we're still undergoing with the transport.

**Comment by SimonCropp** [comment]
ok fair enough. if there is already a pending sample i guess the v6 label makes sense
