### ISSUE TITLE
Native integration with ASQ document (+sample)

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#887]
Replaces  #810

**Comment by andreasohlund** [comment]
Is this one done?

**Comment by SeanFeldman** [comment]
@andreasohlund not yet

**Comment by SeanFeldman** [comment]
@andreasohlund not yet. [ASB](https://github.com/Particular/docs.particular.net/issues/886) is done.

**Comment by andreasohlund** [comment]
Ah, got it!

**Comment by SimonCropp** [comment]
still think we dont need a sample for this. doco will do

**Comment by SeanFeldman** [comment]
@SimonCropp I'm ok with either.
Think there was something recently that @yvesgoeleven wanted to have this as a sample. 
@yvesgoeleven could you :+1:/:-1: this? Thanks.

**Comment by SimonCropp** [comment]
well considering msmq sql and rabbit are all simple docs pages. unless ASQ is different for some reason?

http://docs.particular.net/nservicebus/sqlserver/operations-scripting#native-send
http://docs.particular.net/nservicebus/msmq/operations-scripting#native-send
http://docs.particular.net/nservicebus/rabbitmq/operations-scripting#native-send

**Comment by andreasohlund** [comment]
:+1: for doco


@SimonCropp Since there is no "install time" on azure it would be awesome if we could get that "output the scripts to `.deployment` msbuild task" going similar to what you have done for the native sqlpersister?

**Comment by SeanFeldman** [comment]
Can I get more details on that "output the scripts to .deployment msbuild task"? :) thank you

**Comment by andreasohlund** [comment]
Eagerly awaiting the demo from @SimonCropp  ;)

**Comment by gbiellem** [comment]
Will this affect SC installation of Azure transports down the track?

**Comment by andreasohlund** [comment]
>Will this affect SC installation of Azure transports down the track?

I think it might help since the plan is to have the build output the scripts (powershell) "needed" to install the endpoint in higher environments?

**Comment by gbiellem** [comment]
I like the idea but I'm not keen on taking a dependency on Powershell for the SC installer.   
At the moment the SC has PS cmdlets to assist in scripting the setup of services but neither the WPF or base MSI installer use PowerShell directly.  Instead there is a core dll that is exposed to all three ways of adding a service ( PS, WPF and MSI unattended)

**Comment by Scooletz** [comment]
@SeanFeldman As the author, could you clarify the scope of this? Is it about sending raw messages with schema aligned to the ASQ?

**Comment by SeanFeldman** [comment]
Correct. That was the intent.

**Comment by SimonCropp** [comment]
submit a PR when you are ready to work on this
