### ISSUE TITLE
Improve release policy regarding support packages

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#892]
I just looked at the release policy and we should add something about all the other support packages like the transport and persistance. These are linked to a major NServiceBus version which I think is leading? Especially as those even have multiple majors within one NServiceBus major version.

**Comment by SimonCropp** [comment]
@ramonsmits that list was only meant to be a partial thing until we properly do this https://github.com/Particular/Website.Frontend/issues/347

So i think the partial list will suffice and any extra effort should be redirected to 347
