### ISSUE TITLE
operational scripting for ASB

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#894]
Similar to
- [RabbitMQ](http://docs.particular.net/nservicebus/rabbitmq/operations-scripting)
- [SQL](http://docs.particular.net/nservicebus/sqlserver/operations-scripting)
- [MSMQ](http://docs.particular.net/nservicebus/msmq/operations-scripting)

to complete the [native integration sample](https://github.com/Particular/docs.particular.net/issues/886)

Note: not intended for pub/sub. Just the commands

**Comment by SimonCropp** [comment]
this is not v6 related. removing tag

**Comment by SeanFeldman** [comment]
[Sample](https://blogs.msdn.microsoft.com/paolos/2014/12/02/how-to-create-service-bus-queues-topics-and-subscriptions-using-a-powershell-script/) to create queues/topics/subscriptions with PS.
