### ISSUE TITLE
Snippet solution doesn't compile

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#905]
In the process of writing documentation for `TransportMessage` obsoletion. The solution on latest master for the snippets doesn't compile. @andreasohlund verified as well. See below error message.

```
Severity    Code    Description    Project    File    Line
Error    CS0433    The type 'IProfile' exists in both 'NServiceBus.Host, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' and 'NServiceBus.Hosting.Azure, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'    Snippets_5    C:\dev\docs.particular.net\Snippets\Snippets_5\Logging\OverrideViaProfile.cs    22

andreas [15:44]
and

andreas [15:44]
Severity    Code    Description    Project    File    Line
Error    CS0433    The type 'IConfigureLoggingForProfile<T>' exists in both 'NServiceBus.Host, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' and 'NServiceBus.Hosting.Azure, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'    Snippets_5    C:\dev\docs.particular.net\Snippets\Snippets_5\Logging\OverrideViaProfile.cs    11
```

I'm parking this here for now to finish my doco task and come back to this as soon as I have time.

**Comment by andreasohlund** [comment]
Pretty sure this is the culprit https://github.com/Particular/docs.particular.net/commit/c220b03a7e08f95389d33eb226c7f945de4a2cf1#diff-f78d2bd9b69289d45c7dd6b460d085b5R32

cc @SeanFeldman

**Comment by danielmarbach** [comment]
Sorry running out of time for today...

**Comment by SeanFeldman** [comment]
@andreasohlund do you have Azure SDK installed?
It's required for `RoleEntryPoint`

**Comment by SeanFeldman** [comment]
We could drop reference to azure SDK and fake `RoleEntryPoint` for the code snippet.

**Comment by SeanFeldman** [comment]
@andreasohlund you're right, it's the nsb.hosting.azure :disappointed: - I'll fix it
