### ISSUE TITLE
ServicePulse: intro-failed-messages.md: Add a comment about what is the behaviour given scale out with a distributor

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#919]
Need to confirm, but i assume SLR and retry form SP will end up in the distributor queue

intro-failed-messages.md

**Comment by petersgiles** [comment]
@sfarmar is this about how service pulse behaves when the distributor is being used. Are you asking if the endpoints show up as a single endpoint or as multiple.

Further are you asking if those endpoints will disappear as the distributor is scaled down

**Comment by SimonCropp** [comment]
given the current status of the distributor moving forward i am closing this one. please feel free to open a PR if u think it is still work doing
