### ISSUE TITLE
"Exposing an NServiceBus Endpoint via WCF" needs to address deprecation

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#932]
WCF is likely coming out of the core for NSB Host V7 (Core V6) - Particular/NServiceBus.Host#45

The page "Exposing an NServiceBus Endpoint via WCF" is the doco for that issue and needs to be updated to state that it's being removed, explain why, and point to the [WCF Callbacks Sample](http://docs.particular.net/samples/web/wcf-callbacks/) as a better solution in all cases.

**Comment by danielmarbach** [comment]
Done in https://github.com/Particular/docs.particular.net/pull/1886
and #1928 Closing
