### ISSUE TITLE
Improve documentation of pub/sub in context of multi-site deployments

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#939]
Related to http://docs.particular.net/nservicebus/gateway/multi-site-deployments.

The information about pub/sub is scattered around entire page and not really useful. There is really good content in the ADSD training that can be used to add proper guidance to that page.
### Plan of attack
- [ ] Explain what service is (logical, deployed to multiple hosts)
- [ ] Explain why commands only make sense inside a service
- [ ] Explain a standard gateway scenario with multiple sites -- how services map to these sites

I think it is a days worth of an effort. But it is debatable if it makes sense without added some more ADSD-focused guidance type of doco.

**Comment by weralabaj** [comment]
@SzymonPobiega is that still relevant?
should it be tackled as part of Gateway's v6 update?

**Comment by SzymonPobiega** [comment]
@weralabaj not related to V6. This issue points to a general problem with this area of documentation.

**Comment by weralabaj** [comment]
@SzymonPobiega could you create a brief PoA for this? A few bullet points explaining what you think should be covered? That would enable other people to work on this too.
Plus, any idea how huge effort that would be? (1hr/1day/1week/who knows?).

**Comment by weralabaj** [comment]
For the person tackling it, seems like the Gateway overview page contains a lot of duplicated content on that http://docs.particular.net/nservicebus/gateway/. When doing the clean up it'd make sense to handle both at once.

**Comment by SimonCropp** [comment]
@SzymonPobiega if u still feel this is valuable can u start a PR
