### ISSUE TITLE
Create a custom container sample

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#951]
Based on [this SO issue](http://stackoverflow.com/questions/33841044/implementation-of-the-nservicebus-masstransit-icontainer-with-dryioc-or-lightinj/33847000?noredirect=1#comment55468274_33847000) a sample that demonstrates the usage of custom containers might be of value?

**Comment by andreasohlund** [comment]
What's missing from http://docs.particular.net/samples/containers/ ?

**Comment by sfarmar** [comment]
They are all supported containers samples (aren't they?)

**Comment by andreasohlund** [comment]
Are you saying we should have a sample for a non supported container? (its a fair chunk of work to get a container working)

**Comment by sfarmar** [comment]
I guess so, this is what the SO issue is about, I'd be happy to have a go at this?

**Comment by andreasohlund** [comment]
Given that the current plan is to (albeit slowly) move a way from container support in this for I don't really see the ROI of doing this?

**Comment by SimonCropp** [comment]
I think this is a case of "we welcome member from the community to create extensions to nsb and open source them, let us know if u need help"

**Comment by sfarmar** [comment]
In this case he went with another framework (rbus), I was following up on his comment:
`Still I found that it is not helpful. They should demonstrate further as the element of using container is very important on the implementation their ESB framework`

So I guess that if we see no value in this we can close this issue?

**Comment by SimonCropp** [comment]
given we want to move away from using containers spending effort on that now is not a good use of time. also any of the public repos for the current containers would be enough for somone to create their own container implementation
