### ISSUE TITLE
Document how to reschedule timeouts for the NH persister

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#954]
Eg. this is how you add X days:
```
UPDATE TimeoutEntity
   SET Time = DATEADD(day,10,Time)
 WHERE id IN 
 (
    select tt.Id
from TimeoutEntity tt
outer apply dbo.parseJSON(tt.Headers) as parsed
where parsed.StringValue LIKE 'Sales.Contracts.OrderPlaced%'
)
```
Require this func:

https://www.simple-talk.com/sql/t-sql-programming/consuming-json-strings-in-sql-server/

**Comment by SimonCropp** [comment]
@Particular/nhibernate-persistence-maintainers if you want to expose this please submit a PR
