### ISSUE TITLE
more doco about testing?

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#965]
Currently there is one page about UnitTesting using the NServiceBus.Testing Framework. While this gives some basic guidance on how to test handlers and sagas it does not:
- show users how to unit test custom behaviors, mutators, features or other extensibility points
- show users how to do integration or acceptance testing (e.g. using InMemory persistence)
- show users how to test without the testing framework

By providing samples on how to write tests we would not only help the user but also help us to identify issues with the testing experience (e.g. private constructors on public classes which are required parameters).

Would it make sense to provide more guidance on testing? Should that be a dedicated doco section or should we just at unit tests to some of the samples?

**Comment by SimonCropp** [comment]
+1

**Comment by sfarmar** [comment]
+1 I had a call with a customer and he pointed out the documentation is minimal and some samples would be really helpfull 

assigning this to myself ( @timbussmann @SimonCropp i will need your help...)

**Comment by SimonCropp** [comment]
@sfarmar a year later does this still require doing?

**Comment by weralabaj** [comment]
we have a separate issue for follow up https://github.com/Particular/docs.particular.net/issues/1938, but I think the basics have been addressed already. anything to move out to the other issue?

**Comment by indualagarsamy** [comment]
@timbussmann - can you please review currently what we have in our doco and see if it sufficiently address your original concern and also check out the issue @weralabaj mentioned? If all is well, can you close it?

**Comment by timbussmann** [comment]
taking the bullet points from the issue description:
> show users how to unit test custom behaviors, mutators, features or other extensibility points

This is not done. Not even sure which parts can be done as there is no easily usable way to test features for example. The last time I had a conversation about this, the conclusion was that it doesn't seem to yield huge value to make feature definitions testable. Custom behaviors should be fully testable with AAA tests and a sample would make sense.

> show users how to do integration or acceptance testing (e.g. using InMemory persistence)

Not sure we want to document this at the current point. I'm playing with this in my head for a quite a while now and I'll try to push this a bit forward a little bit, but at the current point, I wouldn't consider this a necessary documentation as we don't really support it.

> show users how to test without the testing framework

that's done via the AAA tests page and potential improvements are done via issue raised by @weralabaj 

given that, I'll raise a dedicated issue about behavior tests and close this issue.
