### ISSUE TITLE
Custom DataBus can be improved

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#972]
Current custom databus doco can be improved. The sample is kind of wrong.
- http://docs.particular.net/nservicebus/messaging/custom-databus

Add information about:

* Purging / expiration
* Key generation

**Comment by andreasohlund** [comment]
Be aware of this bug when docoing the purging: https://github.com/Particular/NServiceBus/issues/846

**Comment by weralabaj** [comment]
@ramonsmits isn't that duplicate https://github.com/Particular/docs.particular.net/issues/973?

**Comment by weralabaj** [comment]
Closing as duplicate, I copied Andreas comment to not lose it.
