### ISSUE TITLE
DataBus doco about purging, expiration, monitoring auditing

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#973]
Evolve the following in actual data bus documentation.

The followings items are important when working with the Data Bus.
- Auditing
- Error messages
- Purging of expired blobs
- Storage capacity monitoring
## Auditing

Be aware that if you have auditing enabled then these blobs can be part of the audit! This means that you cannot just purge blobs even when expired if the data is part of the audit.
## Error messages

When message that have blobs are forwarded to the error queue because they failed too many times then in order to retry them these blobs should still be available via the data bus. Meaning that if 'old' messages are retried and blobs are purged that processing will fail.
## Purging

When using the file share databus than blobs are not automatically purged. However, TTL information is included in the path generation. If messages have a TimeToBeReceived set then this will result in that data to be formatted in the path of the blob.

This can be used to purge data from the file system.

An alternative is to use the file creation timestamp or a combination of both.
## Monitoring

The location where blobs are stored should be monitored just like any other resource which has incrementing storage like a database or queue.

**Comment by weralabaj** [comment]
From Andreas:
Be aware of this bug when docoing the purging: https://github.com/Particular/NServiceBus/issues/846
