### ISSUE TITLE
Create an overview/intro page for ServicePulse

### ISSUE THREAD

**Issue by sergioc** [Particular/docs.particular.net#976]
Currently we don't have an overview/intro page for SP to follow-up on the individual installer's installation process. That forced us to pick [something "close" to that intro](http://docs.particular.net/servicepulse/intro-endpoints-heartbeats) to automatically show after installing SP. It only covers part of SP's features, so that's not ideal.

SI an example of a product that has such [intro page](http://docs.particular.net/serviceinsight/), and that works better.

CC // @gbiellem

**Comment by WojcikMike** [comment]
cc: @Particular/servicepulse-maintainers I think we should get involved in here

**Comment by weralabaj** [comment]
@Particular/servicepulse-maintainers see the referenced PR to see if there's anything you'd like to add, feel free to edit without consulting me first

**Comment by WojcikMike** [comment]
Awesome work @weralabaj I love it :100: :+1:
